.TH "vendor/phpunit/phpunit/src/Util/TestDox Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/src/Util/TestDox Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBResultPrinter\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBNamePrettifier\&.php\fP"
.br
.ti -1c
.RI "file \fBResultPrinter\&.php\fP"
.br
.in -1c
