.TH "vendor/swiftmailer/swiftmailer/tests Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/swiftmailer/swiftmailer/tests Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBacceptance\fP"
.br
.ti -1c
.RI "directory \fBbug\fP"
.br
.ti -1c
.RI "directory \fBfixtures\fP"
.br
.ti -1c
.RI "directory \fBsmoke\fP"
.br
.ti -1c
.RI "directory \fBunit\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbootstrap\&.php\fP"
.br
.ti -1c
.RI "file \fBIdenticalBinaryConstraint\&.php\fP"
.br
.ti -1c
.RI "file \fBStreamCollector\&.php\fP"
.br
.ti -1c
.RI "file \fBSwiftMailerSmokeTestCase\&.php\fP"
.br
.ti -1c
.RI "file \fBSwiftMailerTestCase\&.php\fP"
.br
.in -1c
