.TH "vendor/symfony/security-core/Symfony/Component/Security/Core/Authentication Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/security-core/Symfony/Component/Security/Core/Authentication Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBProvider\fP"
.br
.ti -1c
.RI "directory \fBRememberMe\fP"
.br
.ti -1c
.RI "directory \fBToken\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAuthenticationManagerInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBAuthenticationProviderManager\&.php\fP"
.br
.ti -1c
.RI "file \fBAuthenticationTrustResolver\&.php\fP"
.br
.ti -1c
.RI "file \fBAuthenticationTrustResolverInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBSimpleAuthenticatorInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBSimpleFormAuthenticatorInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBSimplePreAuthenticatorInterface\&.php\fP"
.br
.in -1c
