.TH "vendor/phpspec/phpspec/src/PhpSpec/Runner Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/phpspec/src/PhpSpec/Runner Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBMaintainer\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCollaboratorManager\&.php\fP"
.br
.ti -1c
.RI "file \fBExampleRunner\&.php\fP"
.br
.ti -1c
.RI "file \fBMatcherManager\&.php\fP"
.br
.ti -1c
.RI "file \fBSpecificationRunner\&.php\fP"
.br
.ti -1c
.RI "file \fBSuiteRunner\&.php\fP"
.br
.in -1c
