.TH "vendor/symfony/process/Symfony/Component/Process/Pipes Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/process/Symfony/Component/Process/Pipes Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAbstractPipes\&.php\fP"
.br
.ti -1c
.RI "file \fBPipesInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBUnixPipes\&.php\fP"
.br
.ti -1c
.RI "file \fBWindowsPipes\&.php\fP"
.br
.in -1c
