.TH "vendor/laravel/framework/src/Illuminate/Mail Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/laravel/framework/src/Illuminate/Mail Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBTransport\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMailer\&.php\fP"
.br
.ti -1c
.RI "file \fBMailServiceProvider\&.php\fP"
.br
.ti -1c
.RI "file \fBMessage\&.php\fP"
.br
.ti -1c
.RI "file \fBTransportManager\&.php\fP"
.br
.in -1c
