.TH "vendor/swiftmailer/swiftmailer/tests/unit/Swift/Events Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/swiftmailer/swiftmailer/tests/unit/Swift/Events Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCommandEventTest\&.php\fP"
.br
.ti -1c
.RI "file \fBEventObjectTest\&.php\fP"
.br
.ti -1c
.RI "file \fBResponseEventTest\&.php\fP"
.br
.ti -1c
.RI "file \fBSendEventTest\&.php\fP"
.br
.ti -1c
.RI "file \fBSimpleEventDispatcherTest\&.php\fP"
.br
.ti -1c
.RI "file \fBTransportChangeEventTest\&.php\fP"
.br
.ti -1c
.RI "file \fBTransportExceptionEventTest\&.php\fP"
.br
.in -1c
