.TH "vendor/doctrine/inflector/tests/Doctrine/Tests/Common/Inflector Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/doctrine/inflector/tests/Doctrine/Tests/Common/Inflector Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInflectorTest\&.php\fP"
.br
.in -1c
