.TH "vendor/phpspec/prophecy/spec/Prophecy/Prophecy Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/prophecy/spec/Prophecy/Prophecy Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMethodProphecySpec\&.php\fP"
.br
.ti -1c
.RI "file \fBObjectProphecySpec\&.php\fP"
.br
.ti -1c
.RI "file \fBRevealerSpec\&.php\fP"
.br
.in -1c
