.TH "vendor/laravel/framework/src/Illuminate/Database/Query Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/laravel/framework/src/Illuminate/Database/Query Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBGrammars\fP"
.br
.ti -1c
.RI "directory \fBProcessors\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBuilder\&.php\fP"
.br
.ti -1c
.RI "file \fBExpression\&.php\fP"
.br
.ti -1c
.RI "file \fBJoinClause\&.php\fP"
.br
.in -1c
