.TH "vendor/phpspec/prophecy/spec/Prophecy/Promise Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/prophecy/spec/Prophecy/Promise Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCallbackPromiseSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBReturnArgumentPromiseSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBReturnPromiseSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBThrowPromiseSpec\&.php\fP"
.br
.in -1c
