.TH "vendor/symfony/routing/Symfony/Component/Routing/Loader Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/routing/Symfony/Component/Routing/Loader Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAnnotationClassLoader\&.php\fP"
.br
.ti -1c
.RI "file \fBAnnotationDirectoryLoader\&.php\fP"
.br
.ti -1c
.RI "file \fBAnnotationFileLoader\&.php\fP"
.br
.ti -1c
.RI "file \fBClosureLoader\&.php\fP"
.br
.ti -1c
.RI "file \fBPhpFileLoader\&.php\fP"
.br
.ti -1c
.RI "file \fBXmlFileLoader\&.php\fP"
.br
.ti -1c
.RI "file \fBYamlFileLoader\&.php\fP"
.br
.in -1c
