.TH "vendor/symfony/routing/Symfony/Component/Routing Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/routing/Symfony/Component/Routing Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAnnotation\fP"
.br
.ti -1c
.RI "directory \fBException\fP"
.br
.ti -1c
.RI "directory \fBGenerator\fP"
.br
.ti -1c
.RI "directory \fBLoader\fP"
.br
.ti -1c
.RI "directory \fBMatcher\fP"
.br
.ti -1c
.RI "directory \fBTests\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCompiledRoute\&.php\fP"
.br
.ti -1c
.RI "file \fBRequestContext\&.php\fP"
.br
.ti -1c
.RI "file \fBRequestContextAwareInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBRoute\&.php\fP"
.br
.ti -1c
.RI "file \fBRouteCollection\&.php\fP"
.br
.ti -1c
.RI "file \fBRouteCompiler\&.php\fP"
.br
.ti -1c
.RI "file \fBRouteCompilerInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBRouter\&.php\fP"
.br
.ti -1c
.RI "file \fBRouterInterface\&.php\fP"
.br
.in -1c
