.TH "vendor/laravel/framework/src/Illuminate/Foundation/Console/Tinker/Presenters Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/laravel/framework/src/Illuminate/Foundation/Console/Tinker/Presenters Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBEloquentModelPresenter\&.php\fP"
.br
.ti -1c
.RI "file \fBIlluminateApplicationPresenter\&.php\fP"
.br
.ti -1c
.RI "file \fBIlluminateCollectionPresenter\&.php\fP"
.br
.in -1c
