.TH "vendor/symfony/translation/Symfony/Component/Translation/Tests Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/translation/Symfony/Component/Translation/Tests Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCatalogue\fP"
.br
.ti -1c
.RI "directory \fBDumper\fP"
.br
.ti -1c
.RI "directory \fBfixtures\fP"
.br
.ti -1c
.RI "directory \fBLoader\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIdentityTranslatorTest\&.php\fP"
.br
.ti -1c
.RI "file \fBIntervalTest\&.php\fP"
.br
.ti -1c
.RI "file \fBLoggingTranslatorTest\&.php\fP"
.br
.ti -1c
.RI "file \fBMessageCatalogueTest\&.php\fP"
.br
.ti -1c
.RI "file \fBMessageSelectorTest\&.php\fP"
.br
.ti -1c
.RI "file \fBPluralizationRulesTest\&.php\fP"
.br
.ti -1c
.RI "file \fBTranslatorCacheTest\&.php\fP"
.br
.ti -1c
.RI "file \fBTranslatorTest\&.php\fP"
.br
.in -1c
