.TH "vendor/psy/psysh/test/fixtures Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/psy/psysh/test/fixtures Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconfig\&.php\fP"
.br
.ti -1c
.RI "file \fBempty\&.php\fP"
.br
.in -1c
