.TH "vendor/nikic/php-parser/lib/PhpParser/Node/Scalar Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/nikic/php-parser/lib/PhpParser/Node/Scalar Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBMagicConst\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDNumber\&.php\fP"
.br
.ti -1c
.RI "file \fBEncapsed\&.php\fP"
.br
.ti -1c
.RI "file \fBLNumber\&.php\fP"
.br
.ti -1c
.RI "file \fBMagicConst\&.php\fP"
.br
.ti -1c
.RI "file \fBString_\&.php\fP"
.br
.in -1c
