.TH "vendor/phpspec/phpspec/spec/PhpSpec/Wrapper/Subject Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/phpspec/spec/PhpSpec/Wrapper/Subject Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBExpectation\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCallerSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBExpectationFactorySpec\&.php\fP"
.br
.ti -1c
.RI "file \fBWrappedObjectSpec\&.php\fP"
.br
.in -1c
