.TH "vendor/symfony/finder/Symfony/Component/Finder/Exception Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/finder/Symfony/Component/Finder/Exception Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAccessDeniedException\&.php\fP"
.br
.ti -1c
.RI "file \fBAdapterFailureException\&.php\fP"
.br
.ti -1c
.RI "file \fBExceptionInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBOperationNotPermitedException\&.php\fP"
.br
.ti -1c
.RI "file \fBShellCommandFailureException\&.php\fP"
.br
.in -1c
