.TH "vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage/Handler Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBLegacyPdoSessionHandler\&.php\fP"
.br
.ti -1c
.RI "file \fBMemcachedSessionHandler\&.php\fP"
.br
.ti -1c
.RI "file \fBMemcacheSessionHandler\&.php\fP"
.br
.ti -1c
.RI "file \fBMongoDbSessionHandler\&.php\fP"
.br
.ti -1c
.RI "file \fBNativeFileSessionHandler\&.php\fP"
.br
.ti -1c
.RI "file \fBNativeSessionHandler\&.php\fP"
.br
.ti -1c
.RI "file \fBNullSessionHandler\&.php\fP"
.br
.ti -1c
.RI "file \fBPdoSessionHandler\&.php\fP"
.br
.ti -1c
.RI "file \fBWriteCheckSessionHandler\&.php\fP"
.br
.in -1c
