.TH "vendor/phpunit/phpunit/src/Framework/Error Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/src/Framework/Error Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDeprecated\&.php\fP"
.br
.ti -1c
.RI "file \fBNotice\&.php\fP"
.br
.ti -1c
.RI "file \fBWarning\&.php\fP"
.br
.in -1c
