.TH "vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Stub Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConsecutiveCalls\&.php\fP"
.br
.ti -1c
.RI "file \fBException\&.php\fP"
.br
.ti -1c
.RI "file \fBMatcherCollection\&.php\fP"
.br
.ti -1c
.RI "file \fBReturn\&.php\fP"
.br
.ti -1c
.RI "file \fBReturnArgument\&.php\fP"
.br
.ti -1c
.RI "file \fBReturnCallback\&.php\fP"
.br
.ti -1c
.RI "file \fBReturnSelf\&.php\fP"
.br
.ti -1c
.RI "file \fBReturnValueMap\&.php\fP"
.br
.in -1c
