.TH "vendor/phpspec/phpspec/src/PhpSpec/Wrapper/Subject/Expectation Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/phpspec/src/PhpSpec/Wrapper/Subject/Expectation Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConstructorDecorator\&.php\fP"
.br
.ti -1c
.RI "file \fBDecorator\&.php\fP"
.br
.ti -1c
.RI "file \fBDispatcherDecorator\&.php\fP"
.br
.ti -1c
.RI "file \fBDuringCall\&.php\fP"
.br
.ti -1c
.RI "file \fBExpectationInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBNegative\&.php\fP"
.br
.ti -1c
.RI "file \fBNegativeThrow\&.php\fP"
.br
.ti -1c
.RI "file \fBPositive\&.php\fP"
.br
.ti -1c
.RI "file \fBPositiveThrow\&.php\fP"
.br
.ti -1c
.RI "file \fBThrowExpectation\&.php\fP"
.br
.ti -1c
.RI "file \fBUnwrapDecorator\&.php\fP"
.br
.in -1c
