.TH "vendor/phpspec/phpspec/src/PhpSpec/Matcher Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/phpspec/src/PhpSpec/Matcher Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArrayContainMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBArrayCountMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBArrayKeyMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBBasicMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBCallbackMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBComparisonMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBIdentityMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBMatcherInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBMatchersProviderInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBObjectStateMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBScalarMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBStringEndMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBStringRegexMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBStringStartMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBThrowMatcher\&.php\fP"
.br
.ti -1c
.RI "file \fBTypeMatcher\&.php\fP"
.br
.in -1c
