.TH "vendor/symfony/routing/Symfony/Component/Routing/Exception Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/routing/Symfony/Component/Routing/Exception Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBExceptionInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBInvalidParameterException\&.php\fP"
.br
.ti -1c
.RI "file \fBMethodNotAllowedException\&.php\fP"
.br
.ti -1c
.RI "file \fBMissingMandatoryParametersException\&.php\fP"
.br
.ti -1c
.RI "file \fBResourceNotFoundException\&.php\fP"
.br
.ti -1c
.RI "file \fBRouteNotFoundException\&.php\fP"
.br
.in -1c
