.TH "vendor/symfony/process/Symfony/Component/Process/Exception Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/process/Symfony/Component/Process/Exception Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBExceptionInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBInvalidArgumentException\&.php\fP"
.br
.ti -1c
.RI "file \fBLogicException\&.php\fP"
.br
.ti -1c
.RI "file \fBProcessFailedException\&.php\fP"
.br
.ti -1c
.RI "file \fBProcessTimedOutException\&.php\fP"
.br
.ti -1c
.RI "file \fBRuntimeException\&.php\fP"
.br
.in -1c
