.TH "vendor/laravel/framework/src/Illuminate/Routing/Matching Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/laravel/framework/src/Illuminate/Routing/Matching Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBHostValidator\&.php\fP"
.br
.ti -1c
.RI "file \fBMethodValidator\&.php\fP"
.br
.ti -1c
.RI "file \fBSchemeValidator\&.php\fP"
.br
.ti -1c
.RI "file \fBUriValidator\&.php\fP"
.br
.ti -1c
.RI "file \fBValidatorInterface\&.php\fP"
.br
.in -1c
