.TH "vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Session/Storage Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBHandler\fP"
.br
.ti -1c
.RI "directory \fBProxy\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMetadataBag\&.php\fP"
.br
.ti -1c
.RI "file \fBMockArraySessionStorage\&.php\fP"
.br
.ti -1c
.RI "file \fBMockFileSessionStorage\&.php\fP"
.br
.ti -1c
.RI "file \fBNativeSessionStorage\&.php\fP"
.br
.ti -1c
.RI "file \fBPhpBridgeSessionStorage\&.php\fP"
.br
.ti -1c
.RI "file \fBSessionStorageInterface\&.php\fP"
.br
.in -1c
