.TH "vendor/phpspec/prophecy/spec/Prophecy/Doubler Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/prophecy/spec/Prophecy/Doubler Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBClassPatch\fP"
.br
.ti -1c
.RI "directory \fBGenerator\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDoublerSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBLazyDoubleSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBNameGeneratorSpec\&.php\fP"
.br
.in -1c
