.TH "vendor/psy/psysh/src/Psy/Output Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/psy/psysh/src/Psy/Output Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOutputPager\&.php\fP"
.br
.ti -1c
.RI "file \fBPassthruPager\&.php\fP"
.br
.ti -1c
.RI "file \fBProcOutputPager\&.php\fP"
.br
.ti -1c
.RI "file \fBShellOutput\&.php\fP"
.br
.in -1c
