.TH "vendor/symfony/security-core/Symfony/Component/Security/Core/Authentication/Token/Storage Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/security-core/Symfony/Component/Security/Core/Authentication/Token/Storage Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTokenStorage\&.php\fP"
.br
.ti -1c
.RI "file \fBTokenStorageInterface\&.php\fP"
.br
.in -1c
