.TH "vendor/phpspec Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBphp-diff\fP"
.br
.ti -1c
.RI "directory \fBphpspec\fP"
.br
.ti -1c
.RI "directory \fBprophecy\fP"
.br
.in -1c
