.TH "vendor/phpspec/phpspec/spec/PhpSpec/Event Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/phpspec/spec/PhpSpec/Event Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBExampleEventSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBExpectationEventSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBMethodCallEventSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBSpecificationEventSpec\&.php\fP"
.br
.ti -1c
.RI "file \fBSuiteEventSpec\&.php\fP"
.br
.in -1c
