.TH "vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Exception Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Exception Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBadMethodCallException\&.php\fP"
.br
.ti -1c
.RI "file \fBException\&.php\fP"
.br
.ti -1c
.RI "file \fBRuntimeException\&.php\fP"
.br
.in -1c
