.TH "vendor/phpspec/php-diff/lib/Diff/Renderer/Text Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/php-diff/lib/Diff/Renderer/Text Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBContext\&.php\fP"
.br
.ti -1c
.RI "file \fBUnified\&.php\fP"
.br
.in -1c
