.TH "vendor/nikic/php-parser/test/PhpParser/Builder Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/nikic/php-parser/test/PhpParser/Builder Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClassTest\&.php\fP"
.br
.ti -1c
.RI "file \fBFunctionTest\&.php\fP"
.br
.ti -1c
.RI "file \fBInterfaceTest\&.php\fP"
.br
.ti -1c
.RI "file \fBMethodTest\&.php\fP"
.br
.ti -1c
.RI "file \fBNamespaceTest\&.php\fP"
.br
.ti -1c
.RI "file \fBParamTest\&.php\fP"
.br
.ti -1c
.RI "file \fBPropertyTest\&.php\fP"
.br
.ti -1c
.RI "file \fBTraitTest\&.php\fP"
.br
.ti -1c
.RI "file \fBUseTest\&.php\fP"
.br
.in -1c
