.TH "vendor/phpspec/phpspec/src/PhpSpec/Formatter/Presenter/Differ Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/phpspec/src/PhpSpec/Formatter/Presenter/Differ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBArrayEngine\&.php\fP"
.br
.ti -1c
.RI "file \fBDiffer\&.php\fP"
.br
.ti -1c
.RI "file \fBEngineInterface\&.php\fP"
.br
.ti -1c
.RI "file \fBObjectEngine\&.php\fP"
.br
.ti -1c
.RI "file \fBStringEngine\&.php\fP"
.br
.in -1c
