.TH "vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Tests/File Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Tests/File Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBMimeType\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFakeFile\&.php\fP"
.br
.ti -1c
.RI "file \fBFileTest\&.php\fP"
.br
.ti -1c
.RI "file \fBUploadedFileTest\&.php\fP"
.br
.in -1c
