.TH "vendor/swiftmailer/swiftmailer/tests/unit/Swift/Plugins Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/swiftmailer/swiftmailer/tests/unit/Swift/Plugins Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBLoggers\fP"
.br
.ti -1c
.RI "directory \fBReporters\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAntiFloodPluginTest\&.php\fP"
.br
.ti -1c
.RI "file \fBBandwidthMonitorPluginTest\&.php\fP"
.br
.ti -1c
.RI "file \fBDecoratorPluginTest\&.php\fP"
.br
.ti -1c
.RI "file \fBLoggerPluginTest\&.php\fP"
.br
.ti -1c
.RI "file \fBPopBeforeSmtpPluginTest\&.php\fP"
.br
.ti -1c
.RI "file \fBRedirectingPluginTest\&.php\fP"
.br
.ti -1c
.RI "file \fBReporterPluginTest\&.php\fP"
.br
.ti -1c
.RI "file \fBThrottlerPluginTest\&.php\fP"
.br
.in -1c
