.TH "vendor/phpspec/phpspec/src/PhpSpec/Exception/Example Directory Reference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpspec/phpspec/src/PhpSpec/Exception/Example Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBErrorException\&.php\fP"
.br
.ti -1c
.RI "file \fBExampleException\&.php\fP"
.br
.ti -1c
.RI "file \fBFailureException\&.php\fP"
.br
.ti -1c
.RI "file \fBMatcherException\&.php\fP"
.br
.ti -1c
.RI "file \fBNotEqualException\&.php\fP"
.br
.ti -1c
.RI "file \fBPendingException\&.php\fP"
.br
.ti -1c
.RI "file \fBSkippingException\&.php\fP"
.br
.ti -1c
.RI "file \fBStopOnFailureException\&.php\fP"
.br
.in -1c
