.TH "App" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCommands\fP"
.br
.ti -1c
.RI " \fBConsole\fP"
.br
.ti -1c
.RI " \fBEvents\fP"
.br
.ti -1c
.RI " \fBExceptions\fP"
.br
.ti -1c
.RI " \fBHttp\fP"
.br
.ti -1c
.RI " \fBProviders\fP"
.br
.ti -1c
.RI " \fBServices\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBController\fP 
.PP
\fBProject\fP that controls the home screen of the user
.PP
Class HomeController 
.PP
\fBController\fP for the \fBModule\fP class
.PP
Class ModuleController 
.PP
\fBController\fP for each \fBProject\fP class
.PP
Class ProjectController 
.PP
\fBController\fP that handles the permissions of the \fBProject\fP class
.PP
Class ProjectPermissionController 
.PP
\fBController\fP for all system based tasks
.PP
Class SystemController 
.PP
\fBController\fP for the welcome screen that the user first loads
.PP
Class WelcomeController 
.PP
Class \fBProject\fP
.PP
Class \fBUser\fP 
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
