.TH "Kernel" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kernel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKernel\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBschedule\fP (Schedule $schedule)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$commands\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file Kernel\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "schedule (Schedule $schedule)\fC [protected]\fP"
Define the application's command schedule\&.
.PP
\fBParameters:\fP
.RS 4
\fI$schedule\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 23 of file Kernel\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$commands\fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= [
        'App\Console\Commands\Inspire',
    ]
.fi
.PP
Definition at line 13 of file Kernel\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
