.TH "App\Permission" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Permission \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModel\fP\&.
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'permissions'"
.br
.ti -1c
.RI "\fB$fillable\fP = ['project_id', 'user_id', 'open', 'edit', '\fBshare\fP']"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file Permission\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBfillable\fP = ['project_id', 'user_id', 'open', 'edit', '\fBshare\fP']\fC [protected]\fP"

.PP
Definition at line 19 of file Permission\&.php\&.
.SS "$table = 'permissions'\fC [protected]\fP"

.PP
Definition at line 12 of file Permission\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
