.TH "Controller" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBController\fP\&.
.PP
Inherited by \fBAuthController\fP, \fBPasswordController\fP, \fBHomeController\fP, \fBModuleController\fP, \fBProjectController\fP, \fBProjectPermissionController\fP, \fBSystemController\fP, and \fBWelcomeController\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file Controller\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
