.TH "App\User" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\User \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModel\fP, \fBAuthenticatable\fP, and \fBCanResetPassword\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprojects\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'users'"
.br
.ti -1c
.RI "\fB$fillable\fP = ['\fBname\fP', 'email', 'password']"
.br
.ti -1c
.RI "\fB$hidden\fP = ['password', 'remember_token']"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file User\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "projects ()"
Establishes a hasMany relationship between \fBUser\fP and Projects
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 43 of file User\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBfillable\fP = ['\fBname\fP', 'email', 'password']\fC [protected]\fP"

.PP
Definition at line 29 of file User\&.php\&.
.SS "$hidden = ['password', 'remember_token']\fC [protected]\fP"

.PP
Definition at line 36 of file User\&.php\&.
.SS "$table = 'users'\fC [protected]\fP"

.PP
Definition at line 22 of file User\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
