.TH "App\Module" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
App\Module \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBModel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBproject\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$table\fP = 'modules'"
.br
.ti -1c
.RI "\fB$fillable\fP = ['project_id', '\fBname\fP', 'file_loc', 'screen_loc', 'type']"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file Module\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "project ()"

.PP
Definition at line 21 of file Module\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBfillable\fP = ['project_id', '\fBname\fP', 'file_loc', 'screen_loc', 'type']\fC [protected]\fP"

.PP
Definition at line 19 of file Module\&.php\&.
.SS "$table = 'modules'\fC [protected]\fP"

.PP
Definition at line 12 of file Module\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
