.TH "RedirectIfAuthenticated" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RedirectIfAuthenticated \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBGuard\fP $auth)"
.br
.ti -1c
.RI "\fBhandle\fP ($request, Closure $next)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$auth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file RedirectIfAuthenticated\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBGuard\fP $auth)"
Create a new filter instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$auth\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 22 of file RedirectIfAuthenticated\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "handle ( $request, Closure $next)"
Handle an incoming request\&.
.PP
\fBParameters:\fP
.RS 4
\fI$request\fP 
.br
\fI$next\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 34 of file RedirectIfAuthenticated\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$auth\fC [protected]\fP"

.PP
Definition at line 14 of file RedirectIfAuthenticated\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
