.TH "CreateProjectRequest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateProjectRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRequest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauthorize\fP ()"
.br
.ti -1c
.RI "\fBrules\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file CreateProjectRequest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "authorize ()"
Determine if the user is authorized to make this request\&.
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 12 of file CreateProjectRequest\&.php\&.
.SS "rules ()"
Get the validation rules that apply to the request\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 22 of file CreateProjectRequest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
