.TH "vendor/laravel/framework/src/Illuminate/Foundation/Testing/ApplicationTrait.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/laravel/framework/src/Illuminate/Foundation/Testing/ApplicationTrait.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBIlluminate\\Foundation\\Testing\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBrefreshApplication\fP ()"
.br
.ti -1c
.RI "\fBcall\fP ($method, $uri, $parameters=[], $cookies=[], $files=[], $server=[], $content=null)"
.br
.ti -1c
.RI "\fBcallSecure\fP ($method, $uri, $parameters=[], $cookies=[], $files=[], $server=[], $content=null)"
.br
.ti -1c
.RI "\fBaction\fP ($method, $action, $wildcards=[], $parameters=[], $cookies=[], $files=[], $server=[], $content=null)"
.br
.ti -1c
.RI "\fBroute\fP ($method, $\fBname\fP, $routeParameters=[], $parameters=[], $cookies=[], $files=[], $server=[], $content=null)"
.br
.ti -1c
.RI "\fBsession\fP (array $\fBdata\fP)"
.br
.ti -1c
.RI "\fBflushSession\fP ()"
.br
.ti -1c
.RI "\fBstartSession\fP ()"
.br
.ti -1c
.RI "\fBbe\fP (UserContract $user, $driver=null)"
.br
.ti -1c
.RI "\fBseed\fP ($class= '\fBDatabaseSeeder\fP')"
.br
.ti -1c
.RI "\fBartisan\fP ($command, $parameters=[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBApplicationTrait\fP"
.br
.ti -1c
.RI "\fB$response\fP"
.br
.ti -1c
.RI "\fB$code\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
