.TH "vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesAndRegistersUsers.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/laravel/framework/src/Illuminate/Foundation/Auth/AuthenticatesAndRegistersUsers.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBIlluminate\\Foundation\\Auth\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetRegister\fP ()"
.br
.ti -1c
.RI "\fBpostRegister\fP (\fBRequest\fP $request)"
.br
.ti -1c
.RI "\fBgetLogin\fP ()"
.br
.ti -1c
.RI "\fBpostLogin\fP (\fBRequest\fP $request)"
.br
.ti -1c
.RI "\fBgetFailedLoginMessage\fP ()"
.br
.ti -1c
.RI "\fBgetLogout\fP ()"
.br
.ti -1c
.RI "\fBredirectPath\fP ()"
.br
.ti -1c
.RI "\fBloginPath\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
