.TH "vendor/composer/autoload_psr4.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/composer/autoload_psr4.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$vendorDir\fP = dirname(dirname(__FILE__))"
.br
.ti -1c
.RI "\fB$baseDir\fP = dirname($vendorDir)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$baseDir = dirname($vendorDir)"

.PP
Definition at line 6 of file autoload_psr4\&.php\&.
.SS "$vendorDir = dirname(dirname(__FILE__))"

.PP
Definition at line 5 of file autoload_psr4\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
