.TH "BankAccount" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BankAccount \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetBalance\fP ()"
.br
.ti -1c
.RI "\fBdepositMoney\fP ($balance)"
.br
.ti -1c
.RI "\fBwithdrawMoney\fP ($balance)"
.br
.ti -1c
.RI "\fBgetBalance\fP ()"
.br
.ti -1c
.RI "\fBdepositMoney\fP ($balance)"
.br
.ti -1c
.RI "\fBwithdrawMoney\fP ($balance)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetBalance\fP ($balance)"
.br
.ti -1c
.RI "\fBsetBalance\fP ($balance)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$balance\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file BankAccount\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "depositMoney ( $balance)"

.PP
Definition at line 20 of file BankAccount\&.php\&.
.SS "depositMoney ( $balance)"
Deposits an amount of money to the bank account\&.
.PP
\fBParameters:\fP
.RS 4
\fI$balance\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBBankAccountException\fP\fP 
.RE
.PP

.PP
Definition at line 65 of file BankAccount\&.php\&.
.SS "getBalance ()"

.PP
Definition at line 6 of file BankAccount\&.php\&.
.SS "getBalance ()"
Returns the bank account's balance\&.
.PP
\fBReturns:\fP
.RS 4
float 
.RE
.PP

.PP
Definition at line 39 of file BankAccount\&.php\&.
.SS "setBalance ( $balance)\fC [protected]\fP"

.PP
Definition at line 11 of file BankAccount\&.php\&.
.SS "setBalance ( $balance)\fC [protected]\fP"
Sets the bank account's balance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$balance\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBBankAccountException\fP\fP 
.RE
.PP

.PP
Definition at line 50 of file BankAccount\&.php\&.
.SS "withdrawMoney ( $balance)"

.PP
Definition at line 27 of file BankAccount\&.php\&.
.SS "withdrawMoney ( $balance)"
Withdraws an amount of money from the bank account\&.
.PP
\fBParameters:\fP
.RS 4
\fI$balance\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBBankAccountException\fP\fP 
.RE
.PP

.PP
Definition at line 78 of file BankAccount\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$balance = 0\fC [protected]\fP"

.PP
Definition at line 4 of file BankAccount\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
