.TH "Blade" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Blade \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBlade\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcompile\fP ($\fBpath\fP=null)"
.br
.ti -1c
.RI "static \fBgetPath\fP ()"
.br
.ti -1c
.RI "static \fBsetPath\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBcompileString\fP ($value)"
.br
.ti -1c
.RI "static \fBcompileEchoDefaults\fP ($value)"
.br
.ti -1c
.RI "static \fBextend\fP ($compiler)"
.br
.ti -1c
.RI "static \fBcreateMatcher\fP ($function)"
.br
.ti -1c
.RI "static \fBcreateOpenMatcher\fP ($function)"
.br
.ti -1c
.RI "static \fBcreatePlainMatcher\fP ($function)"
.br
.ti -1c
.RI "static \fBsetContentTags\fP ($openTag, $closeTag, $escaped=false)"
.br
.ti -1c
.RI "static \fBsetEscapedContentTags\fP ($openTag, $closeTag)"
.br
.ti -1c
.RI "static \fBgetContentTags\fP ()"
.br
.ti -1c
.RI "static \fBgetEscapedContentTags\fP ()"
.br
.ti -1c
.RI "static \fBgetCompiledPath\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBisExpired\fP ($\fBpath\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1801 of file _ide_helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static compile ( $path = \fCnull\fP)\fC [static]\fP"
Compile the view at the given path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 1810 of file _ide_helper\&.php\&.
.SS "static compileEchoDefaults ( $value)\fC [static]\fP"
Compile the default values for the echo statement\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1853 of file _ide_helper\&.php\&.
.SS "static compileString ( $value)\fC [static]\fP"
Compile the given \fBBlade\fP template contents\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1842 of file _ide_helper\&.php\&.
.SS "static createMatcher ( $function)\fC [static]\fP"
Get the regular expression for a generic \fBBlade\fP function\&.
.PP
\fBParameters:\fP
.RS 4
\fI$function\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1875 of file _ide_helper\&.php\&.
.SS "static createOpenMatcher ( $function)\fC [static]\fP"
Get the regular expression for a generic \fBBlade\fP function\&.
.PP
\fBParameters:\fP
.RS 4
\fI$function\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1886 of file _ide_helper\&.php\&.
.SS "static createPlainMatcher ( $function)\fC [static]\fP"
Create a plain \fBBlade\fP matcher\&.
.PP
\fBParameters:\fP
.RS 4
\fI$function\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1897 of file _ide_helper\&.php\&.
.SS "static extend ( $compiler)\fC [static]\fP"
Register a custom \fBBlade\fP compiler\&.
.PP
\fBParameters:\fP
.RS 4
\fI$compiler\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 1864 of file _ide_helper\&.php\&.
.SS "static getCompiledPath ( $path)\fC [static]\fP"
Get the path to the compiled version of a view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1953 of file _ide_helper\&.php\&.
.SS "static getContentTags ()\fC [static]\fP"
Gets the content tags used for the compiler\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1932 of file _ide_helper\&.php\&.
.SS "static getEscapedContentTags ()\fC [static]\fP"
Gets the escaped content tags used for the compiler\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1942 of file _ide_helper\&.php\&.
.SS "static getPath ()\fC [static]\fP"
Get the path currently being compiled\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 1820 of file _ide_helper\&.php\&.
.SS "static isExpired ( $path)\fC [static]\fP"
Determine if the view at the given path is expired\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 1965 of file _ide_helper\&.php\&.
.SS "static setContentTags ( $openTag,  $closeTag,  $escaped = \fCfalse\fP)\fC [static]\fP"
Sets the content tags used for the compiler\&.
.PP
\fBParameters:\fP
.RS 4
\fI$openTag\fP 
.br
\fI$closeTag\fP 
.br
\fI$escaped\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 1910 of file _ide_helper\&.php\&.
.SS "static setEscapedContentTags ( $openTag,  $closeTag)\fC [static]\fP"
Sets the escaped content tags used for the compiler\&.
.PP
\fBParameters:\fP
.RS 4
\fI$openTag\fP 
.br
\fI$closeTag\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 1922 of file _ide_helper\&.php\&.
.SS "static setPath ( $path)\fC [static]\fP"
Set the path currently being compiled\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 1831 of file _ide_helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
