.TH "vendor/phpunit/phpunit/tests/Regression/GitHub/797/bootstrap797.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/phpunit/tests/Regression/GitHub/797/bootstrap797.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBGITHUB_ISSUE\fP = 797"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const GITHUB_ISSUE = 797"

.PP
Definition at line 6 of file bootstrap797\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
