.TH "c" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBb\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfoo\fP ()"
.br
.ti -1c
.RI "\fBbaz\fP (Baz $baz)"
.br
.ti -1c
.RI "\fBm\fP ($\fBa\fP, array $\fBb\fP, array $\fBc\fP=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file source4\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "baz (Baz $baz)"

.PP
Implements \fBb\fP\&.
.PP
Definition at line 27 of file source4\&.php\&.
.SS "foo ()"

.PP
Definition at line 23 of file source4\&.php\&.
.SS "m ( $a, array $b, array $c = \fCarray()\fP)"

.PP
Definition at line 5 of file source5\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
