.TH "vendor/laravel/framework/src/Illuminate/Support/Traits/CapsuleManagerTrait.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/laravel/framework/src/Illuminate/Support/Traits/CapsuleManagerTrait.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBIlluminate\\Support\\Traits\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetupContainer\fP (Container $container)"
.br
.ti -1c
.RI "\fBsetAsGlobal\fP ()"
.br
.ti -1c
.RI "\fBgetContainer\fP ()"
.br
.ti -1c
.RI "\fBsetContainer\fP (Container $container)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBCapsuleManagerTrait\fP"
.br
.ti -1c
.RI "\fB$container\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
