.TH "CarbonIntervalForHumansTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CarbonIntervalForHumansTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestGetTranslator\fP ()"
.br
.ti -1c
.RI "\fBtestSetTranslator\fP ()"
.br
.ti -1c
.RI "\fBtestGetLocale\fP ()"
.br
.ti -1c
.RI "\fBtestSetLocale\fP ()"
.br
.ti -1c
.RI "\fBtestYear\fP ()"
.br
.ti -1c
.RI "\fBtestYearToString\fP ()"
.br
.ti -1c
.RI "\fBtestYears\fP ()"
.br
.ti -1c
.RI "\fBtestYearsAndMonth\fP ()"
.br
.ti -1c
.RI "\fBtestAll\fP ()"
.br
.ti -1c
.RI "\fBtestYearsAndMonthInFrench\fP ()"
.br
.ti -1c
.RI "\fBtestYearsAndMonthInGerman\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file CarbonIntervalForHumansTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAll ()"

.PP
Definition at line 74 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testGetLocale ()"

.PP
Definition at line 36 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testGetTranslator ()"

.PP
Definition at line 18 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testSetLocale ()"

.PP
Definition at line 42 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testSetTranslator ()"

.PP
Definition at line 25 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testYear ()"

.PP
Definition at line 50 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testYears ()"

.PP
Definition at line 62 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testYearsAndMonth ()"

.PP
Definition at line 68 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testYearsAndMonthInFrench ()"

.PP
Definition at line 81 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testYearsAndMonthInGerman ()"

.PP
Definition at line 87 of file CarbonIntervalForHumansTest\&.php\&.
.SS "testYearToString ()"

.PP
Definition at line 56 of file CarbonIntervalForHumansTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
