.TH "CarbonIntervalAddTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CarbonIntervalAddTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestAdd\fP ()"
.br
.ti -1c
.RI "\fBtestAddWithDiffDateInterval\fP ()"
.br
.ti -1c
.RI "\fBtestAddWithNegativeDiffDateInterval\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file CarbonIntervalAddTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAdd ()"

.PP
Definition at line 17 of file CarbonIntervalAddTest\&.php\&.
.SS "testAddWithDiffDateInterval ()"

.PP
Definition at line 23 of file CarbonIntervalAddTest\&.php\&.
.SS "testAddWithNegativeDiffDateInterval ()"

.PP
Definition at line 30 of file CarbonIntervalAddTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
