.TH "ChildSuite" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChildSuite \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBsuite\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ChildSuite\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static suite ()\fC [static]\fP"

.PP
Definition at line 7 of file ChildSuite\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
