.TH "NodeTraverser" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeTraverser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeTraverser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtraverseFile\fP (array $nodes, $filename)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This is the file node visitor class\&.
.PP
This allows a filename to be set when visiting\&. 
.PP
Definition at line 12 of file NodeTraverser\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "traverseFile (array $nodes,  $filename)"
Transverse the file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$nodes\fP 
.br
\fI$filename\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 22 of file NodeTraverser\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
