.TH "ClassThatImplementsSerializable" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassThatImplementsSerializable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBserialize\fP ()"
.br
.ti -1c
.RI "\fBunserialize\fP ($serialized)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file ClassThatImplementsSerializable\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "serialize ()"

.PP
Definition at line 4 of file ClassThatImplementsSerializable\&.php\&.
.SS "unserialize ( $serialized)"

.PP
Definition at line 9 of file ClassThatImplementsSerializable\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
