.TH "Config" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IteratorAggregate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaddFile\fP ($filename)"
.br
.ti -1c
.RI "\fBgetFilenames\fP ()"
.br
.ti -1c
.RI "\fBgetIterator\fP ()"
.br
.ti -1c
.RI "\fBaddExclusiveFilter\fP ($pattern)"
.br
.ti -1c
.RI "\fBaddInclusiveFilter\fP ($pattern)"
.br
.ti -1c
.RI "\fBaddVisitor\fP (\fBAbstractNodeVisitor\fP $visitor)"
.br
.ti -1c
.RI "\fBgetVisitors\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$visitors\fP = array()"
.br
.ti -1c
.RI "\fB$filenames\fP = array()"
.br
.ti -1c
.RI "\fB$exclusiveFilters\fP = array()"
.br
.ti -1c
.RI "\fB$inclusiveFilters\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the config class\&.
.PP
This contains all the class preloader configuration\&. 
.PP
Definition at line 12 of file Config\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addExclusiveFilter ( $pattern)"
Add a filter used to filter out file names matching the pattern\&.
.PP
We're filtering the classes using a regular expression\&.
.PP
\fBParameters:\fP
.RS 4
\fI$pattern\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 100 of file Config\&.php\&.
.SS "addFile ( $filename)"
Add the filename owned by the config\&.
.PP
\fBParameters:\fP
.RS 4
\fI$filename\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 49 of file Config\&.php\&.
.SS "addInclusiveFilter ( $pattern)"
Add a filter used to grab only file names matching the pattern\&.
.PP
We're filtering the classes using a regular expression\&.
.PP
\fBParameters:\fP
.RS 4
\fI$pattern\fP Regular expression pattern
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 116 of file Config\&.php\&.
.SS "addVisitor (\fBAbstractNodeVisitor\fP $visitor)"
Add a visitor\&.
.PP
It will visit each node when traversing the node list of each file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$visitor\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 132 of file Config\&.php\&.
.SS "getFilenames ()"
Get an array of file names that satisfy any added filters\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 61 of file Config\&.php\&.
.SS "getIterator ()"
Get an iterator for the filenames\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 86 of file Config\&.php\&.
.SS "getVisitors ()"
Get an array of node visitors\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 144 of file Config\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$exclusiveFilters = array()\fC [protected]\fP"

.PP
Definition at line 33 of file Config\&.php\&.
.SS "$filenames = array()\fC [protected]\fP"

.PP
Definition at line 26 of file Config\&.php\&.
.SS "$inclusiveFilters = array()\fC [protected]\fP"

.PP
Definition at line 40 of file Config\&.php\&.
.SS "$visitors = array()\fC [protected]\fP"

.PP
Definition at line 19 of file Config\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
