.TH "AbstractNodeVisitor" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractNodeVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeVisitorAbstract\fP\&.
.PP
Inherited by \fBDirVisitor\fP, and \fBFileVisitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetFilename\fP ($filename)"
.br
.ti -1c
.RI "\fBgetFilename\fP ()"
.br
.ti -1c
.RI "\fBgetDir\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$filename\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is the abstract node visitor class\&.
.PP
This is used to track the filename\&. 
.PP
Definition at line 12 of file AbstractNodeVisitor\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDir ()"
Get the directory of the current file being parsed\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 50 of file AbstractNodeVisitor\&.php\&.
.SS "getFilename ()"
Get the full path to the current file being parsed\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 40 of file AbstractNodeVisitor\&.php\&.
.SS "setFilename ( $filename)"
Set the full path to the current file being parsed\&.
.PP
\fBParameters:\fP
.RS 4
\fI$filename\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 28 of file AbstractNodeVisitor\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$filename = ''\fC [protected]\fP"

.PP
Definition at line 19 of file AbstractNodeVisitor\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
