.TH "vendor/phpunit/php-token-stream/tests/_fixture/closure.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-token-stream/tests/_fixture/closure.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$function1\fP = function($\fBfoo\fP, $bar) use ($var) {}"
.br
.ti -1c
.RI "\fB$function2\fP = function(\fBFoo\fP $\fBfoo\fP, $bar) use ($var) {}"
.br
.ti -1c
.RI "\fB$function3\fP = function ($\fBfoo\fP, $bar, $\fBbaz\fP) {}"
.br
.ti -1c
.RI "\fB$function4\fP = function (\fBFoo\fP $\fBfoo\fP, $bar, $\fBbaz\fP) {}"
.br
.ti -1c
.RI "\fB$function5\fP = function () {}"
.br
.ti -1c
.RI "\fB$function6\fP = function() {}"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$function1 = function($\fBfoo\fP, $bar) use ($var) {}"

.PP
Definition at line 2 of file closure\&.php\&.
.SS "$function2 = function(\fBFoo\fP $\fBfoo\fP, $bar) use ($var) {}"

.PP
Definition at line 3 of file closure\&.php\&.
.SS "$function3 = function ($\fBfoo\fP, $bar, $\fBbaz\fP) {}"

.PP
Definition at line 4 of file closure\&.php\&.
.SS "$function4 = function (\fBFoo\fP $\fBfoo\fP, $bar, $\fBbaz\fP) {}"

.PP
Definition at line 5 of file closure\&.php\&.
.SS "$function5 = function () {}"

.PP
Definition at line 6 of file closure\&.php\&.
.SS "$function6 = function() {}"

.PP
Definition at line 7 of file closure\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
