.TH "vendor/phpunit/php-code-coverage/tests/PHP/CodeCoverageTest.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-code-coverage/tests/PHP/CodeCoverageTest.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPHP_CodeCoverageTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCodeCoverage\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP (!defined('\fBTEST_FILES_PATH\fP'))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP(!defined('\fBTEST_FILES_PATH\fP'))"

.PP
Definition at line 11 of file CodeCoverageTest\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
