.TH "CommonTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommonTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.PP
Inherited by \fBStaticStringyTestCase\fP, and \fBStringyTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBassertStringy\fP ($actual)"
.br
.ti -1c
.RI "\fBcharsProvider\fP ()"
.br
.ti -1c
.RI "\fBupperCaseFirstProvider\fP ()"
.br
.ti -1c
.RI "\fBlowerCaseFirstProvider\fP ()"
.br
.ti -1c
.RI "\fBcamelizeProvider\fP ()"
.br
.ti -1c
.RI "\fBupperCamelizeProvider\fP ()"
.br
.ti -1c
.RI "\fBdasherizeProvider\fP ()"
.br
.ti -1c
.RI "\fBunderscoredProvider\fP ()"
.br
.ti -1c
.RI "\fBswapCaseProvider\fP ()"
.br
.ti -1c
.RI "\fBtitleizeProvider\fP ()"
.br
.ti -1c
.RI "\fBhumanizeProvider\fP ()"
.br
.ti -1c
.RI "\fBtidyProvider\fP ()"
.br
.ti -1c
.RI "\fBcollapseWhitespaceProvider\fP ()"
.br
.ti -1c
.RI "\fBtoAsciiProvider\fP ()"
.br
.ti -1c
.RI "\fBpadProvider\fP ()"
.br
.ti -1c
.RI "\fBpadLeftProvider\fP ()"
.br
.ti -1c
.RI "\fBpadRightProvider\fP ()"
.br
.ti -1c
.RI "\fBpadBothProvider\fP ()"
.br
.ti -1c
.RI "\fBstartsWithProvider\fP ()"
.br
.ti -1c
.RI "\fBendsWithProvider\fP ()"
.br
.ti -1c
.RI "\fBtoSpacesProvider\fP ()"
.br
.ti -1c
.RI "\fBtoTabsProvider\fP ()"
.br
.ti -1c
.RI "\fBtoLowerCaseProvider\fP ()"
.br
.ti -1c
.RI "\fBtoTitleCaseProvider\fP ()"
.br
.ti -1c
.RI "\fBtoUpperCaseProvider\fP ()"
.br
.ti -1c
.RI "\fBslugifyProvider\fP ()"
.br
.ti -1c
.RI "\fBcontainsProvider\fP ()"
.br
.ti -1c
.RI "\fBcontainsAnyProvider\fP ()"
.br
.ti -1c
.RI "\fBcontainsAllProvider\fP ()"
.br
.ti -1c
.RI "\fBsurroundProvider\fP ()"
.br
.ti -1c
.RI "\fBinsertProvider\fP ()"
.br
.ti -1c
.RI "\fBtruncateProvider\fP ()"
.br
.ti -1c
.RI "\fBsafeTruncateProvider\fP ()"
.br
.ti -1c
.RI "\fBreverseProvider\fP ()"
.br
.ti -1c
.RI "\fBshuffleProvider\fP ()"
.br
.ti -1c
.RI "\fBtrimProvider\fP ()"
.br
.ti -1c
.RI "\fBlongestCommonPrefixProvider\fP ()"
.br
.ti -1c
.RI "\fBlongestCommonSuffixProvider\fP ()"
.br
.ti -1c
.RI "\fBlongestCommonSubstringProvider\fP ()"
.br
.ti -1c
.RI "\fBlengthProvider\fP ()"
.br
.ti -1c
.RI "\fBsubstrProvider\fP ()"
.br
.ti -1c
.RI "\fBatProvider\fP ()"
.br
.ti -1c
.RI "\fBfirstProvider\fP ()"
.br
.ti -1c
.RI "\fBlastProvider\fP ()"
.br
.ti -1c
.RI "\fBensureLeftProvider\fP ()"
.br
.ti -1c
.RI "\fBensureRightProvider\fP ()"
.br
.ti -1c
.RI "\fBremoveLeftProvider\fP ()"
.br
.ti -1c
.RI "\fBremoveRightProvider\fP ()"
.br
.ti -1c
.RI "\fBisAlphaProvider\fP ()"
.br
.ti -1c
.RI "\fBisAlphanumericProvider\fP ()"
.br
.ti -1c
.RI "\fBisBlankProvider\fP ()"
.br
.ti -1c
.RI "\fBisJsonProvider\fP ()"
.br
.ti -1c
.RI "\fBisLowerCaseProvider\fP ()"
.br
.ti -1c
.RI "\fBhasLowerCaseProvider\fP ()"
.br
.ti -1c
.RI "\fBisSerializedProvider\fP ()"
.br
.ti -1c
.RI "\fBisUpperCaseProvider\fP ()"
.br
.ti -1c
.RI "\fBhasUpperCaseProvider\fP ()"
.br
.ti -1c
.RI "\fBisHexadecimalProvider\fP ()"
.br
.ti -1c
.RI "\fBcountSubstrProvider\fP ()"
.br
.ti -1c
.RI "\fBreplaceProvider\fP ()"
.br
.ti -1c
.RI "\fBregexReplaceProvider\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file CommonTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "assertStringy ( $actual)"
Asserts that a variable is of a \fBStringy\fP instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$actual\fP 
.RE
.PP

.PP
Definition at line 12 of file CommonTest\&.php\&.
.SS "atProvider ()"

.PP
Definition at line 680 of file CommonTest\&.php\&.
.SS "camelizeProvider ()"

.PP
Definition at line 48 of file CommonTest\&.php\&.
.SS "charsProvider ()"

.PP
Definition at line 17 of file CommonTest\&.php\&.
.SS "collapseWhitespaceProvider ()"

.PP
Definition at line 170 of file CommonTest\&.php\&.
.SS "containsAllProvider ()"

.PP
Definition at line 455 of file CommonTest\&.php\&.
.SS "containsAnyProvider ()"

.PP
Definition at line 417 of file CommonTest\&.php\&.
.SS "containsProvider ()"

.PP
Definition at line 390 of file CommonTest\&.php\&.
.SS "countSubstrProvider ()"

.PP
Definition at line 970 of file CommonTest\&.php\&.
.SS "dasherizeProvider ()"

.PP
Definition at line 86 of file CommonTest\&.php\&.
.SS "endsWithProvider ()"

.PP
Definition at line 296 of file CommonTest\&.php\&.
.SS "ensureLeftProvider ()"

.PP
Definition at line 730 of file CommonTest\&.php\&.
.SS "ensureRightProvider ()"

.PP
Definition at line 746 of file CommonTest\&.php\&.
.SS "firstProvider ()"

.PP
Definition at line 694 of file CommonTest\&.php\&.
.SS "hasLowerCaseProvider ()"

.PP
Definition at line 888 of file CommonTest\&.php\&.
.SS "hasUpperCaseProvider ()"

.PP
Definition at line 933 of file CommonTest\&.php\&.
.SS "humanizeProvider ()"

.PP
Definition at line 151 of file CommonTest\&.php\&.
.SS "insertProvider ()"

.PP
Definition at line 504 of file CommonTest\&.php\&.
.SS "isAlphanumericProvider ()"

.PP
Definition at line 814 of file CommonTest\&.php\&.
.SS "isAlphaProvider ()"

.PP
Definition at line 798 of file CommonTest\&.php\&.
.SS "isBlankProvider ()"

.PP
Definition at line 833 of file CommonTest\&.php\&.
.SS "isHexadecimalProvider ()"

.PP
Definition at line 951 of file CommonTest\&.php\&.
.SS "isJsonProvider ()"

.PP
Definition at line 854 of file CommonTest\&.php\&.
.SS "isLowerCaseProvider ()"

.PP
Definition at line 874 of file CommonTest\&.php\&.
.SS "isSerializedProvider ()"

.PP
Definition at line 906 of file CommonTest\&.php\&.
.SS "isUpperCaseProvider ()"

.PP
Definition at line 919 of file CommonTest\&.php\&.
.SS "lastProvider ()"

.PP
Definition at line 712 of file CommonTest\&.php\&.
.SS "lengthProvider ()"

.PP
Definition at line 655 of file CommonTest\&.php\&.
.SS "longestCommonPrefixProvider ()"

.PP
Definition at line 607 of file CommonTest\&.php\&.
.SS "longestCommonSubstringProvider ()"

.PP
Definition at line 639 of file CommonTest\&.php\&.
.SS "longestCommonSuffixProvider ()"

.PP
Definition at line 623 of file CommonTest\&.php\&.
.SS "lowerCaseFirstProvider ()"

.PP
Definition at line 37 of file CommonTest\&.php\&.
.SS "padBothProvider ()"

.PP
Definition at line 262 of file CommonTest\&.php\&.
.SS "padLeftProvider ()"

.PP
Definition at line 236 of file CommonTest\&.php\&.
.SS "padProvider ()"

.PP
Definition at line 211 of file CommonTest\&.php\&.
.SS "padRightProvider ()"

.PP
Definition at line 249 of file CommonTest\&.php\&.
.SS "regexReplaceProvider ()"

.PP
Definition at line 1013 of file CommonTest\&.php\&.
.SS "removeLeftProvider ()"

.PP
Definition at line 762 of file CommonTest\&.php\&.
.SS "removeRightProvider ()"

.PP
Definition at line 780 of file CommonTest\&.php\&.
.SS "replaceProvider ()"

.PP
Definition at line 991 of file CommonTest\&.php\&.
.SS "reverseProvider ()"

.PP
Definition at line 573 of file CommonTest\&.php\&.
.SS "safeTruncateProvider ()"

.PP
Definition at line 545 of file CommonTest\&.php\&.
.SS "shuffleProvider ()"

.PP
Definition at line 584 of file CommonTest\&.php\&.
.SS "slugifyProvider ()"

.PP
Definition at line 369 of file CommonTest\&.php\&.
.SS "startsWithProvider ()"

.PP
Definition at line 279 of file CommonTest\&.php\&.
.SS "substrProvider ()"

.PP
Definition at line 665 of file CommonTest\&.php\&.
.SS "surroundProvider ()"

.PP
Definition at line 493 of file CommonTest\&.php\&.
.SS "swapCaseProvider ()"

.PP
Definition at line 128 of file CommonTest\&.php\&.
.SS "tidyProvider ()"

.PP
Definition at line 160 of file CommonTest\&.php\&.
.SS "titleizeProvider ()"

.PP
Definition at line 138 of file CommonTest\&.php\&.
.SS "toAsciiProvider ()"

.PP
Definition at line 188 of file CommonTest\&.php\&.
.SS "toLowerCaseProvider ()"

.PP
Definition at line 336 of file CommonTest\&.php\&.
.SS "toSpacesProvider ()"

.PP
Definition at line 313 of file CommonTest\&.php\&.
.SS "toTabsProvider ()"

.PP
Definition at line 325 of file CommonTest\&.php\&.
.SS "toTitleCaseProvider ()"

.PP
Definition at line 347 of file CommonTest\&.php\&.
.SS "toUpperCaseProvider ()"

.PP
Definition at line 358 of file CommonTest\&.php\&.
.SS "trimProvider ()"

.PP
Definition at line 593 of file CommonTest\&.php\&.
.SS "truncateProvider ()"

.PP
Definition at line 517 of file CommonTest\&.php\&.
.SS "underscoredProvider ()"

.PP
Definition at line 107 of file CommonTest\&.php\&.
.SS "upperCamelizeProvider ()"

.PP
Definition at line 67 of file CommonTest\&.php\&.
.SS "upperCaseFirstProvider ()"

.PP
Definition at line 26 of file CommonTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
