.TH "ComposerAutoloaderInit830da61585e7e48fa3319fcc4506435f" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComposerAutoloaderInit830da61585e7e48fa3319fcc4506435f \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBloadClassLoader\fP ($class)"
.br
.ti -1c
.RI "static \fBgetLoader\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file autoload_real\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getLoader ()\fC [static]\fP"

.PP
Definition at line 16 of file autoload_real\&.php\&.
.SS "static loadClassLoader ( $class)\fC [static]\fP"

.PP
Definition at line 9 of file autoload_real\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
