.TH "ConsoleColorWithForceSupport" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleColorWithForceSupport \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConsoleColor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetIsSupported\fP ($\fBisSupported\fP)"
.br
.ti -1c
.RI "\fBisSupported\fP ()"
.br
.ti -1c
.RI "\fBsetAre256ColorsSupported\fP ($\fBare256ColorsSupported\fP)"
.br
.ti -1c
.RI "\fBare256ColorsSupported\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 4 of file ConsoleColorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "are256ColorsSupported ()"

.PP
Definition at line 25 of file ConsoleColorTest\&.php\&.
.SS "isSupported ()"

.PP
Definition at line 15 of file ConsoleColorTest\&.php\&.
.SS "setAre256ColorsSupported ( $are256ColorsSupported)"

.PP
Definition at line 20 of file ConsoleColorTest\&.php\&.
.SS "setIsSupported ( $isSupported)"

.PP
Definition at line 10 of file ConsoleColorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
