.TH "CoveredClassWithAnonymousFunctionInStaticMethod" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoveredClassWithAnonymousFunctionInStaticMethod \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBrunAnonymous\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file source_with_class_and_anonymous_function\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static runAnonymous ()\fC [static]\fP"

.PP
Definition at line 5 of file source_with_class_and_anonymous_function\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
