.TH "CoveragePublicTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CoveragePublicTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP, and \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSomething\fP ()"
.br
.ti -1c
.RI "\fBtestSomething\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2 of file CoveragePublicTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testSomething ()"
\fBCoveredClass\fP::<public> 
.PP
Definition at line 7 of file CoveragePublicTest\&.php\&.
.SS "testSomething ()"
\fBCoveredClass\fP::<public> 
.PP
Definition at line 7 of file CoveragePublicTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
