.TH "CreateFromFormatTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateFromFormatTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestCreateFromFormatReturnsCarbon\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromFormatWithTimezoneString\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromFormatWithTimezone\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromFormatWithMillis\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file CreateFromFormatTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testCreateFromFormatReturnsCarbon ()"

.PP
Definition at line 16 of file CreateFromFormatTest\&.php\&.
.SS "testCreateFromFormatWithMillis ()"

.PP
Definition at line 37 of file CreateFromFormatTest\&.php\&.
.SS "testCreateFromFormatWithTimezone ()"

.PP
Definition at line 30 of file CreateFromFormatTest\&.php\&.
.SS "testCreateFromFormatWithTimezoneString ()"

.PP
Definition at line 23 of file CreateFromFormatTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
