.TH "CreateFromDateTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CreateFromDateTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestCreateFromDateWithDefaults\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromDate\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromDateWithYear\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromDateWithMonth\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromDateWithDay\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromDateWithTimezone\fP ()"
.br
.ti -1c
.RI "\fBtestCreateFromDateWithDateTimeZone\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file CreateFromDateTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testCreateFromDate ()"

.PP
Definition at line 22 of file CreateFromDateTest\&.php\&.
.SS "testCreateFromDateWithDateTimeZone ()"

.PP
Definition at line 53 of file CreateFromDateTest\&.php\&.
.SS "testCreateFromDateWithDay ()"

.PP
Definition at line 40 of file CreateFromDateTest\&.php\&.
.SS "testCreateFromDateWithDefaults ()"

.PP
Definition at line 16 of file CreateFromDateTest\&.php\&.
.SS "testCreateFromDateWithMonth ()"

.PP
Definition at line 34 of file CreateFromDateTest\&.php\&.
.SS "testCreateFromDateWithTimezone ()"

.PP
Definition at line 46 of file CreateFromDateTest\&.php\&.
.SS "testCreateFromDateWithYear ()"

.PP
Definition at line 28 of file CreateFromDateTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
