.TH "Crypt" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Crypt \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCrypt\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBencrypt\fP ($value)"
.br
.ti -1c
.RI "static \fBdecrypt\fP ($payload)"
.br
.ti -1c
.RI "static \fBsetKey\fP ($key)"
.br
.ti -1c
.RI "static \fBsetCipher\fP ($cipher)"
.br
.ti -1c
.RI "static \fBsetMode\fP ($mode)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2690 of file _ide_helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static decrypt ( $payload)\fC [static]\fP"
Decrypt the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$payload\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 2710 of file _ide_helper\&.php\&.
.SS "static encrypt ( $value)\fC [static]\fP"
Encrypt the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 2699 of file _ide_helper\&.php\&.
.SS "static setCipher ( $cipher)\fC [static]\fP"
Set the encryption cipher\&.
.PP
\fBParameters:\fP
.RS 4
\fI$cipher\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 2732 of file _ide_helper\&.php\&.
.SS "static setKey ( $key)\fC [static]\fP"
Set the encryption key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 2721 of file _ide_helper\&.php\&.
.SS "static setMode ( $mode)\fC [static]\fP"
Set the encryption mode\&.
.PP
\fBParameters:\fP
.RS 4
\fI$mode\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 2743 of file _ide_helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
