.TH "DiffTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DiffTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestDiffInYearsPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInYearsNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInYearsNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInYearsVsDefaultNow\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInYearsEnsureIsTruncated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMonthsPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMonthsNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMonthsNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMonthsVsDefaultNow\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMonthsEnsureIsTruncated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysVsDefaultNow\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysEnsureIsTruncated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysFilteredPositiveWithMutated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysFilteredPositiveWithSecondObject\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysFilteredNegativeNoSignWithMutated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysFilteredNegativeNoSignWithSecondObject\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysFilteredNegativeWithSignWithMutated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInDaysFilteredNegativeWithSignWithSecondObject\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInHoursFiltered\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInHoursFilteredNegative\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInHoursFilteredWorkHoursPerWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffFilteredUsingMinutesPositiveWithMutated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffFilteredPositiveWithSecondObject\fP ()"
.br
.ti -1c
.RI "\fBtestDiffFilteredNegativeNoSignWithMutated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffFilteredNegativeNoSignWithSecondObject\fP ()"
.br
.ti -1c
.RI "\fBtestDiffFilteredNegativeWithSignWithMutated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffFilteredNegativeWithSignWithSecondObject\fP ()"
.br
.ti -1c
.RI "\fBtestBug188DiffWithSameDates\fP ()"
.br
.ti -1c
.RI "\fBtestBug188DiffWithDatesOnlyHoursApart\fP ()"
.br
.ti -1c
.RI "\fBtestBug188DiffWithSameDates1DayApart\fP ()"
.br
.ti -1c
.RI "\fBtestBug188DiffWithDatesOnTheWeekend\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeekdaysPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeekdaysNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeekdaysNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeekendDaysPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeekendDaysNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeekendDaysNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeeksPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeeksNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeeksNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeeksVsDefaultNow\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInWeeksEnsureIsTruncated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInHoursPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInHoursNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInHoursNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInHoursVsDefaultNow\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInHoursEnsureIsTruncated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMinutesPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMinutesPositiveAlot\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMinutesNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMinutesNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMinutesVsDefaultNow\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInMinutesEnsureIsTruncated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInSecondsPositive\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInSecondsPositiveAlot\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInSecondsNegativeWithSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInSecondsNegativeNoSign\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInSecondsVsDefaultNow\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInSecondsEnsureIsTruncated\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInSecondsWithTimezones\fP ()"
.br
.ti -1c
.RI "\fBtestDiffInSecondsWithTimezonesAndVsDefault\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndSecond\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndSecondWithTimezone\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndSeconds\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyMinute\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndMinute\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndMinutes\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyHour\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndHour\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndHours\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyDay\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndDay\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndDays\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndWeeks\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyMonth\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndMonth\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndMonths\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyYear\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndYear\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndYears\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureSecond\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureSeconds\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyFutureMinute\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureMinute\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureMinutes\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyFutureHour\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureHour\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureHours\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyFutureDay\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureDay\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureDays\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyFutureWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureWeeks\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyFutureMonth\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureMonth\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureMonths\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndNearlyFutureYear\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureYear\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansNowAndFutureYears\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndSecond\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndSeconds\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyMinute\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndMinute\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndMinutes\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyHour\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndHour\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndHours\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyDay\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndDay\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndDays\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndWeeks\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyMonth\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndMonth\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndMonths\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyYear\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndYear\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndYears\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureSecond\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureSeconds\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyFutureMinute\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureMinute\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureMinutes\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyFutureHour\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureHour\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureHours\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyFutureDay\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureDay\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureDays\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyFutureWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureWeek\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureWeeks\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyFutureMonth\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureMonth\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureMonths\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndNearlyFutureYear\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureYear\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansOtherAndFutureYears\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansAbsoluteSeconds\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansAbsoluteMinutes\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansAbsoluteHours\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansAbsoluteDays\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansAbsoluteWeeks\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansAbsoluteMonths\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansAbsoluteYears\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansWithShorterMonthShouldStillBeAMonth\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file DiffTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testBug188DiffWithDatesOnlyHoursApart ()"

.PP
Definition at line 255 of file DiffTest\&.php\&.
.SS "testBug188DiffWithDatesOnTheWeekend ()"

.PP
Definition at line 273 of file DiffTest\&.php\&.
.SS "testBug188DiffWithSameDates ()"

.PP
Definition at line 246 of file DiffTest\&.php\&.
.SS "testBug188DiffWithSameDates1DayApart ()"

.PP
Definition at line 264 of file DiffTest\&.php\&.
.SS "testDiffFilteredNegativeNoSignWithMutated ()"

.PP
Definition at line 209 of file DiffTest\&.php\&.
.SS "testDiffFilteredNegativeNoSignWithSecondObject ()"

.PP
Definition at line 218 of file DiffTest\&.php\&.
.SS "testDiffFilteredNegativeWithSignWithMutated ()"

.PP
Definition at line 228 of file DiffTest\&.php\&.
.SS "testDiffFilteredNegativeWithSignWithSecondObject ()"

.PP
Definition at line 236 of file DiffTest\&.php\&.
.SS "testDiffFilteredPositiveWithSecondObject ()"

.PP
Definition at line 199 of file DiffTest\&.php\&.
.SS "testDiffFilteredUsingMinutesPositiveWithMutated ()"

.PP
Definition at line 191 of file DiffTest\&.php\&.
.SS "testDiffForHumansAbsoluteDays ()"

.PP
Definition at line 1002 of file DiffTest\&.php\&.
.SS "testDiffForHumansAbsoluteHours ()"

.PP
Definition at line 994 of file DiffTest\&.php\&.
.SS "testDiffForHumansAbsoluteMinutes ()"

.PP
Definition at line 986 of file DiffTest\&.php\&.
.SS "testDiffForHumansAbsoluteMonths ()"

.PP
Definition at line 1018 of file DiffTest\&.php\&.
.SS "testDiffForHumansAbsoluteSeconds ()"

.PP
Definition at line 978 of file DiffTest\&.php\&.
.SS "testDiffForHumansAbsoluteWeeks ()"

.PP
Definition at line 1010 of file DiffTest\&.php\&.
.SS "testDiffForHumansAbsoluteYears ()"

.PP
Definition at line 1028 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndDay ()"

.PP
Definition at line 526 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndDays ()"

.PP
Definition at line 532 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureDay ()"

.PP
Definition at line 652 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureDays ()"

.PP
Definition at line 658 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureHour ()"

.PP
Definition at line 632 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureHours ()"

.PP
Definition at line 638 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureMinute ()"

.PP
Definition at line 614 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureMinutes ()"

.PP
Definition at line 620 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureMonth ()"

.PP
Definition at line 688 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureMonths ()"

.PP
Definition at line 698 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureSecond ()"

.PP
Definition at line 596 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureSeconds ()"

.PP
Definition at line 602 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureWeek ()"

.PP
Definition at line 670 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureWeeks ()"

.PP
Definition at line 676 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureYear ()"

.PP
Definition at line 712 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndFutureYears ()"

.PP
Definition at line 718 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndHour ()"

.PP
Definition at line 504 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndHours ()"

.PP
Definition at line 510 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndMinute ()"

.PP
Definition at line 486 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndMinutes ()"

.PP
Definition at line 492 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndMonth ()"

.PP
Definition at line 562 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndMonths ()"

.PP
Definition at line 572 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyDay ()"

.PP
Definition at line 518 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyFutureDay ()"

.PP
Definition at line 644 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyFutureHour ()"

.PP
Definition at line 626 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyFutureMinute ()"

.PP
Definition at line 608 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyFutureMonth ()"

.PP
Definition at line 682 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyFutureWeek ()"

.PP
Definition at line 664 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyFutureYear ()"

.PP
Definition at line 706 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyHour ()"

.PP
Definition at line 498 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyMinute ()"

.PP
Definition at line 480 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyMonth ()"

.PP
Definition at line 556 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyWeek ()"

.PP
Definition at line 538 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndNearlyYear ()"

.PP
Definition at line 578 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndSecond ()"

.PP
Definition at line 462 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndSeconds ()"

.PP
Definition at line 474 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndSecondWithTimezone ()"

.PP
Definition at line 468 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndWeek ()"

.PP
Definition at line 544 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndWeeks ()"

.PP
Definition at line 550 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndYear ()"

.PP
Definition at line 584 of file DiffTest\&.php\&.
.SS "testDiffForHumansNowAndYears ()"

.PP
Definition at line 590 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndDay ()"

.PP
Definition at line 780 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndDays ()"

.PP
Definition at line 786 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureDay ()"

.PP
Definition at line 908 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureDays ()"

.PP
Definition at line 914 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureHour ()"

.PP
Definition at line 888 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureHours ()"

.PP
Definition at line 894 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureMinute ()"

.PP
Definition at line 870 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureMinutes ()"

.PP
Definition at line 876 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureMonth ()"

.PP
Definition at line 944 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureMonths ()"

.PP
Definition at line 954 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureSecond ()"

.PP
Definition at line 852 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureSeconds ()"

.PP
Definition at line 858 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureWeek ()"

.PP
Definition at line 926 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureWeeks ()"

.PP
Definition at line 932 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureYear ()"

.PP
Definition at line 966 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndFutureYears ()"

.PP
Definition at line 972 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndHour ()"

.PP
Definition at line 760 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndHours ()"

.PP
Definition at line 766 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndMinute ()"

.PP
Definition at line 742 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndMinutes ()"

.PP
Definition at line 748 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndMonth ()"

.PP
Definition at line 816 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndMonths ()"

.PP
Definition at line 826 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyDay ()"

.PP
Definition at line 772 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyFutureDay ()"

.PP
Definition at line 900 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyFutureHour ()"

.PP
Definition at line 882 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyFutureMinute ()"

.PP
Definition at line 864 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyFutureMonth ()"

.PP
Definition at line 938 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyFutureWeek ()"

.PP
Definition at line 920 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyFutureYear ()"

.PP
Definition at line 960 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyHour ()"

.PP
Definition at line 754 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyMinute ()"

.PP
Definition at line 736 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyMonth ()"

.PP
Definition at line 810 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyWeek ()"

.PP
Definition at line 792 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndNearlyYear ()"

.PP
Definition at line 834 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndSecond ()"

.PP
Definition at line 724 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndSeconds ()"

.PP
Definition at line 730 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndWeek ()"

.PP
Definition at line 798 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndWeeks ()"

.PP
Definition at line 804 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndYear ()"

.PP
Definition at line 840 of file DiffTest\&.php\&.
.SS "testDiffForHumansOtherAndYears ()"

.PP
Definition at line 846 of file DiffTest\&.php\&.
.SS "testDiffForHumansWithShorterMonthShouldStillBeAMonth ()"

.PP
Definition at line 1036 of file DiffTest\&.php\&.
.SS "testDiffInDaysEnsureIsTruncated ()"

.PP
Definition at line 98 of file DiffTest\&.php\&.
.SS "testDiffInDaysFilteredNegativeNoSignWithMutated ()"

.PP
Definition at line 122 of file DiffTest\&.php\&.
.SS "testDiffInDaysFilteredNegativeNoSignWithSecondObject ()"

.PP
Definition at line 130 of file DiffTest\&.php\&.
.SS "testDiffInDaysFilteredNegativeWithSignWithMutated ()"

.PP
Definition at line 140 of file DiffTest\&.php\&.
.SS "testDiffInDaysFilteredNegativeWithSignWithSecondObject ()"

.PP
Definition at line 148 of file DiffTest\&.php\&.
.SS "testDiffInDaysFilteredPositiveWithMutated ()"

.PP
Definition at line 104 of file DiffTest\&.php\&.
.SS "testDiffInDaysFilteredPositiveWithSecondObject ()"

.PP
Definition at line 112 of file DiffTest\&.php\&.
.SS "testDiffInDaysNegativeNoSign ()"

.PP
Definition at line 87 of file DiffTest\&.php\&.
.SS "testDiffInDaysNegativeWithSign ()"

.PP
Definition at line 81 of file DiffTest\&.php\&.
.SS "testDiffInDaysPositive ()"

.PP
Definition at line 75 of file DiffTest\&.php\&.
.SS "testDiffInDaysVsDefaultNow ()"

.PP
Definition at line 93 of file DiffTest\&.php\&.
.SS "testDiffInHoursEnsureIsTruncated ()"

.PP
Definition at line 373 of file DiffTest\&.php\&.
.SS "testDiffInHoursFiltered ()"

.PP
Definition at line 158 of file DiffTest\&.php\&.
.SS "testDiffInHoursFilteredNegative ()"

.PP
Definition at line 169 of file DiffTest\&.php\&.
.SS "testDiffInHoursFilteredWorkHoursPerWeek ()"

.PP
Definition at line 180 of file DiffTest\&.php\&.
.SS "testDiffInHoursNegativeNoSign ()"

.PP
Definition at line 360 of file DiffTest\&.php\&.
.SS "testDiffInHoursNegativeWithSign ()"

.PP
Definition at line 354 of file DiffTest\&.php\&.
.SS "testDiffInHoursPositive ()"

.PP
Definition at line 348 of file DiffTest\&.php\&.
.SS "testDiffInHoursVsDefaultNow ()"

.PP
Definition at line 366 of file DiffTest\&.php\&.
.SS "testDiffInMinutesEnsureIsTruncated ()"

.PP
Definition at line 408 of file DiffTest\&.php\&.
.SS "testDiffInMinutesNegativeNoSign ()"

.PP
Definition at line 397 of file DiffTest\&.php\&.
.SS "testDiffInMinutesNegativeWithSign ()"

.PP
Definition at line 391 of file DiffTest\&.php\&.
.SS "testDiffInMinutesPositive ()"

.PP
Definition at line 379 of file DiffTest\&.php\&.
.SS "testDiffInMinutesPositiveAlot ()"

.PP
Definition at line 385 of file DiffTest\&.php\&.
.SS "testDiffInMinutesVsDefaultNow ()"

.PP
Definition at line 403 of file DiffTest\&.php\&.
.SS "testDiffInMonthsEnsureIsTruncated ()"

.PP
Definition at line 69 of file DiffTest\&.php\&.
.SS "testDiffInMonthsNegativeNoSign ()"

.PP
Definition at line 58 of file DiffTest\&.php\&.
.SS "testDiffInMonthsNegativeWithSign ()"

.PP
Definition at line 52 of file DiffTest\&.php\&.
.SS "testDiffInMonthsPositive ()"

.PP
Definition at line 46 of file DiffTest\&.php\&.
.SS "testDiffInMonthsVsDefaultNow ()"

.PP
Definition at line 64 of file DiffTest\&.php\&.
.SS "testDiffInSecondsEnsureIsTruncated ()"

.PP
Definition at line 443 of file DiffTest\&.php\&.
.SS "testDiffInSecondsNegativeNoSign ()"

.PP
Definition at line 432 of file DiffTest\&.php\&.
.SS "testDiffInSecondsNegativeWithSign ()"

.PP
Definition at line 426 of file DiffTest\&.php\&.
.SS "testDiffInSecondsPositive ()"

.PP
Definition at line 414 of file DiffTest\&.php\&.
.SS "testDiffInSecondsPositiveAlot ()"

.PP
Definition at line 420 of file DiffTest\&.php\&.
.SS "testDiffInSecondsVsDefaultNow ()"

.PP
Definition at line 438 of file DiffTest\&.php\&.
.SS "testDiffInSecondsWithTimezones ()"

.PP
Definition at line 449 of file DiffTest\&.php\&.
.SS "testDiffInSecondsWithTimezonesAndVsDefault ()"

.PP
Definition at line 456 of file DiffTest\&.php\&.
.SS "testDiffInWeekdaysNegativeNoSign ()"

.PP
Definition at line 289 of file DiffTest\&.php\&.
.SS "testDiffInWeekdaysNegativeWithSign ()"

.PP
Definition at line 295 of file DiffTest\&.php\&.
.SS "testDiffInWeekdaysPositive ()"

.PP
Definition at line 283 of file DiffTest\&.php\&.
.SS "testDiffInWeekendDaysNegativeNoSign ()"

.PP
Definition at line 307 of file DiffTest\&.php\&.
.SS "testDiffInWeekendDaysNegativeWithSign ()"

.PP
Definition at line 313 of file DiffTest\&.php\&.
.SS "testDiffInWeekendDaysPositive ()"

.PP
Definition at line 301 of file DiffTest\&.php\&.
.SS "testDiffInWeeksEnsureIsTruncated ()"

.PP
Definition at line 342 of file DiffTest\&.php\&.
.SS "testDiffInWeeksNegativeNoSign ()"

.PP
Definition at line 331 of file DiffTest\&.php\&.
.SS "testDiffInWeeksNegativeWithSign ()"

.PP
Definition at line 325 of file DiffTest\&.php\&.
.SS "testDiffInWeeksPositive ()"

.PP
Definition at line 319 of file DiffTest\&.php\&.
.SS "testDiffInWeeksVsDefaultNow ()"

.PP
Definition at line 337 of file DiffTest\&.php\&.
.SS "testDiffInYearsEnsureIsTruncated ()"

.PP
Definition at line 40 of file DiffTest\&.php\&.
.SS "testDiffInYearsNegativeNoSign ()"

.PP
Definition at line 29 of file DiffTest\&.php\&.
.SS "testDiffInYearsNegativeWithSign ()"

.PP
Definition at line 23 of file DiffTest\&.php\&.
.SS "testDiffInYearsPositive ()"

.PP
Definition at line 17 of file DiffTest\&.php\&.
.SS "testDiffInYearsVsDefaultNow ()"

.PP
Definition at line 35 of file DiffTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
