.TH "Diff_Renderer_Html_Array" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Diff_Renderer_Html_Array \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDiff_Renderer_Abstract\fP\&.
.PP
Inherited by \fBDiff_Renderer_Html_Inline\fP, and \fBDiff_Renderer_Html_SideBySide\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrender\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBfixSpaces\fP ($\fBmatches\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$defaultOptions\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 45 of file Array\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static fixSpaces ( $matches)\fC [static]\fP"
Replace a string containing spaces with a \fBHTML\fP representation using  \&.
.PP
\fBParameters:\fP
.RS 4
\fI$matches\fP Regex matches array\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
string The \fBHTML\fP representation of the string\&. 
.RE
.PP

.PP
Definition at line 191 of file Array\&.php\&.
.SS "render ()"
Render and return an array structure suitable for generating \fBHTML\fP based differences\&. Generally called by subclasses that generate a \fBHTML\fP based diff and return an array of the changes to show in the diff\&.
.PP
\fBReturns:\fP
.RS 4
array An array of the generated chances, suitable for presentation in \fBHTML\fP\&. 
.RE
.PP

.PP
Definition at line 61 of file Array\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$defaultOptions\fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= array(
        'tabSize' => 4
    )
.fi
.PP
Definition at line 50 of file Array\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
