.TH "InflectorTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InflectorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDoctrineTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdataSampleWords\fP ()"
.br
.ti -1c
.RI "\fBtestInflectingSingulars\fP ($singular, $plural)"
.br
.ti -1c
.RI "\fBtestInflectingPlurals\fP ($singular, $plural)"
.br
.ti -1c
.RI "\fBtestCustomPluralRule\fP ()"
.br
.ti -1c
.RI "\fBtestCustomSingularRule\fP ()"
.br
.ti -1c
.RI "\fBtestRulesClearsCaches\fP ()"
.br
.ti -1c
.RI "\fBtestCustomRuleWithReset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file InflectorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "dataSampleWords ()"
Singular & Plural test data\&. Returns an array of sample words\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 15 of file InflectorTest\&.php\&.
.SS "testCustomPluralRule ()"
testCustomPluralRule method
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 103 of file InflectorTest\&.php\&.
.SS "testCustomRuleWithReset ()"
Test resetting inflection rules\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 184 of file InflectorTest\&.php\&.
.SS "testCustomSingularRule ()"
testCustomSingularRule method
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 132 of file InflectorTest\&.php\&.
.SS "testInflectingPlurals ( $singular,  $plural)"
testInflectingPlurals method
.PP
dataSampleWords 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 89 of file InflectorTest\&.php\&.
.SS "testInflectingSingulars ( $singular,  $plural)"
testInflectingSingulars method
.PP
dataSampleWords 
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 74 of file InflectorTest\&.php\&.
.SS "testRulesClearsCaches ()"
test that setting new rules clears the inflector caches\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 157 of file InflectorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
