.TH "ArrayObjectAsset" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArrayObjectAsset \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayObject\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Test asset that extends an internal \fBPHP\fP class
.PP
\fBAuthor:\fP
.RS 4
Marco Pivetta ocramius@gmail.com 
.RE
.PP

.PP
Definition at line 30 of file ArrayObjectAsset\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
Constructor - should not be called
.PP
\fBExceptions:\fP
.RS 4
\fIBadMethodCallException\fP 
.RE
.PP

.PP
Definition at line 37 of file ArrayObjectAsset\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
