.TH "SerializableArrayObjectAsset" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SerializableArrayObjectAsset \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayObject, and Serializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBserialize\fP ()"
.br
.ti -1c
.RI "\fBunserialize\fP ($serialized)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Serializable test asset that also extends an internal class
.PP
\fBAuthor:\fP
.RS 4
Marco Pivetta ocramius@gmail.com 
.RE
.PP

.PP
Definition at line 31 of file SerializableArrayObjectAsset\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
Constructor - should not be called
.PP
\fBExceptions:\fP
.RS 4
\fIBadMethodCallException\fP 
.RE
.PP

.PP
Definition at line 38 of file SerializableArrayObjectAsset\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "serialize ()"

.PP
Definition at line 46 of file SerializableArrayObjectAsset\&.php\&.
.SS "unserialize ( $serialized)"
Should not be called
.PP
\fBExceptions:\fP
.RS 4
\fIBadMethodCallException\fP 
.RE
.PP

.PP
Definition at line 58 of file SerializableArrayObjectAsset\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
