.TH "InvalidArgumentExceptionTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvalidArgumentExceptionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestFromNonExistingTypeWithNonExistingClass\fP ()"
.br
.ti -1c
.RI "\fBtestFromNonExistingTypeWithTrait\fP ()"
.br
.ti -1c
.RI "\fBtestFromNonExistingTypeWithInterface\fP ()"
.br
.ti -1c
.RI "\fBtestFromAbstractClass\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests for {
.PP
\fBSee also:\fP
.RS 4
}
.RE
.PP
\fBAuthor:\fP
.RS 4
Marco Pivetta ocramius@gmail.com
.RE
.PP

.PP
Definition at line 33 of file InvalidArgumentExceptionTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testFromAbstractClass ()"

.PP
Definition at line 72 of file InvalidArgumentExceptionTest\&.php\&.
.SS "testFromNonExistingTypeWithInterface ()"

.PP
Definition at line 61 of file InvalidArgumentExceptionTest\&.php\&.
.SS "testFromNonExistingTypeWithNonExistingClass ()"

.PP
Definition at line 35 of file InvalidArgumentExceptionTest\&.php\&.
.SS "testFromNonExistingTypeWithTrait ()"

.PP
Definition at line 44 of file InvalidArgumentExceptionTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
