.TH "UnexpectedValueExceptionTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnexpectedValueExceptionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestFromSerializationTriggeredException\fP ()"
.br
.ti -1c
.RI "\fBtestFromUncleanUnSerialization\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Tests for {
.PP
\fBSee also:\fP
.RS 4
}
.RE
.PP
\fBAuthor:\fP
.RS 4
Marco Pivetta ocramius@gmail.com
.RE
.PP

.PP
Definition at line 34 of file UnexpectedValueExceptionTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testFromSerializationTriggeredException ()"

.PP
Definition at line 36 of file UnexpectedValueExceptionTest\&.php\&.
.SS "testFromUncleanUnSerialization ()"

.PP
Definition at line 51 of file UnexpectedValueExceptionTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
