.TH "vendor/symfony/var-dumper/Symfony/Component/VarDumper/Tests/Fixtures/dumb-var.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/var-dumper/Symfony/Component/VarDumper/Tests/Fixtures/dumb-var.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSymfony\\Component\\VarDumper\\Tests\\Fixture\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(!class_exists('Symfony\\Component\\VarDumper\\Tests\\Fixture\\DumbFoo')) \fB$foo\fP = new DumbFoo()"
.br
.ti -1c
.RI "$\fBfoo\fP \fBbar\fP = 'bar'"
.br
.ti -1c
.RI "\fB$g\fP = fopen(__FILE__, '\fBr\fP')"
.br
.ti -1c
.RI "\fB$h\fP = fopen(__FILE__, '\fBr\fP')"
.br
.ti -1c
.RI "\fB$var\fP"
.br
.ti -1c
.RI "\fB$r\fP = array()"
.br
.ti -1c
.RI "\fB$r\fP [] =& $\fBr\fP"
.br
.ti -1c
.RI "\fB$var\fP ['recurs'] =& $\fBr\fP"
.br
.ti -1c
.RI "\fB$var\fP [] =& $var[0]"
.br
.ti -1c
.RI "\fB$var\fP ['sobj'] = $var['obj']"
.br
.ti -1c
.RI "\fB$var\fP ['snobj'] =& $var['nobj'][0]"
.br
.ti -1c
.RI "\fB$var\fP ['snobj2'] = $var['nobj'][0]"
.br
.ti -1c
.RI "\fB$var\fP ['file'] = __FILE__"
.br
.ti -1c
.RI "\fB$var\fP ['bin-key-\\xE9'] = ''"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
