.TH "vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/EventObject.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/swiftmailer/swiftmailer/lib/classes/Swift/Events/EventObject.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSwift_Events_EventObject\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
