.TH "Extensions_RepeatedTestTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Extensions_RepeatedTestTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBtestRepeatedOnce\fP ()"
.br
.ti -1c
.RI "\fBtestRepeatedMoreThanOnce\fP ()"
.br
.ti -1c
.RI "\fBtestRepeatedZero\fP ()"
.br
.ti -1c
.RI "\fBtestRepeatedNegative\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$suite\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file RepeatedTestTest\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 26 of file RepeatedTestTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testRepeatedMoreThanOnce ()"

.PP
Definition at line 43 of file RepeatedTestTest\&.php\&.
.SS "testRepeatedNegative ()"

.PP
Definition at line 61 of file RepeatedTestTest\&.php\&.
.SS "testRepeatedOnce ()"

.PP
Definition at line 34 of file RepeatedTestTest\&.php\&.
.SS "testRepeatedZero ()"

.PP
Definition at line 52 of file RepeatedTestTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$suite\fC [protected]\fP"

.PP
Definition at line 24 of file RepeatedTestTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
