.TH "FailureTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FailureTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestAssertArrayEqualsArray\fP ()"
.br
.ti -1c
.RI "\fBtestAssertIntegerEqualsInteger\fP ()"
.br
.ti -1c
.RI "\fBtestAssertObjectEqualsObject\fP ()"
.br
.ti -1c
.RI "\fBtestAssertNullEqualsString\fP ()"
.br
.ti -1c
.RI "\fBtestAssertStringEqualsString\fP ()"
.br
.ti -1c
.RI "\fBtestAssertTextEqualsText\fP ()"
.br
.ti -1c
.RI "\fBtestAssertStringMatchesFormat\fP ()"
.br
.ti -1c
.RI "\fBtestAssertNumericEqualsNumeric\fP ()"
.br
.ti -1c
.RI "\fBtestAssertTextSameText\fP ()"
.br
.ti -1c
.RI "\fBtestAssertObjectSameObject\fP ()"
.br
.ti -1c
.RI "\fBtestAssertObjectSameNull\fP ()"
.br
.ti -1c
.RI "\fBtestAssertFloatSameFloat\fP ()"
.br
.ti -1c
.RI "\fBtestAssertStringMatchesFormatFile\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2 of file FailureTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAssertArrayEqualsArray ()"

.PP
Definition at line 4 of file FailureTest\&.php\&.
.SS "testAssertFloatSameFloat ()"

.PP
Definition at line 65 of file FailureTest\&.php\&.
.SS "testAssertIntegerEqualsInteger ()"

.PP
Definition at line 9 of file FailureTest\&.php\&.
.SS "testAssertNullEqualsString ()"

.PP
Definition at line 25 of file FailureTest\&.php\&.
.SS "testAssertNumericEqualsNumeric ()"

.PP
Definition at line 45 of file FailureTest\&.php\&.
.SS "testAssertObjectEqualsObject ()"

.PP
Definition at line 14 of file FailureTest\&.php\&.
.SS "testAssertObjectSameNull ()"

.PP
Definition at line 60 of file FailureTest\&.php\&.
.SS "testAssertObjectSameObject ()"

.PP
Definition at line 55 of file FailureTest\&.php\&.
.SS "testAssertStringEqualsString ()"

.PP
Definition at line 30 of file FailureTest\&.php\&.
.SS "testAssertStringMatchesFormat ()"

.PP
Definition at line 40 of file FailureTest\&.php\&.
.SS "testAssertStringMatchesFormatFile ()"

.PP
Definition at line 71 of file FailureTest\&.php\&.
.SS "testAssertTextEqualsText ()"

.PP
Definition at line 35 of file FailureTest\&.php\&.
.SS "testAssertTextSameText ()"

.PP
Definition at line 50 of file FailureTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
