.TH "DialogHelper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DialogHelper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDialogHelper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetAnswer\fP ($answer)"
.br
.ti -1c
.RI "\fBaskConfirmation\fP (\fBOutputInterface\fP $output, $question, $default=true)"
.br
.ti -1c
.RI "\fBhasBeenAsked\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file DialogHelper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "askConfirmation (\fBOutputInterface\fP $output,  $question,  $default = \fCtrue\fP)"

.PP
Definition at line 18 of file DialogHelper\&.php\&.
.SS "hasBeenAsked ()"

.PP
Definition at line 24 of file DialogHelper\&.php\&.
.SS "setAnswer ( $answer)"

.PP
Definition at line 13 of file DialogHelper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
