.TH "File" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
File \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFile\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBexists\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBget\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBgetRequire\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBrequireOnce\fP ($file)"
.br
.ti -1c
.RI "static \fBput\fP ($\fBpath\fP, $contents)"
.br
.ti -1c
.RI "static \fBprepend\fP ($\fBpath\fP, $\fBdata\fP)"
.br
.ti -1c
.RI "static \fBappend\fP ($\fBpath\fP, $\fBdata\fP)"
.br
.ti -1c
.RI "static \fBdelete\fP ($paths)"
.br
.ti -1c
.RI "static \fBmove\fP ($\fBpath\fP, $target)"
.br
.ti -1c
.RI "static \fBcopy\fP ($\fBpath\fP, $target)"
.br
.ti -1c
.RI "static \fBname\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBextension\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBtype\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBsize\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBlastModified\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBisDirectory\fP ($directory)"
.br
.ti -1c
.RI "static \fBisWritable\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "static \fBisFile\fP ($file)"
.br
.ti -1c
.RI "static \fBglob\fP ($pattern, $flags=0)"
.br
.ti -1c
.RI "static \fBfiles\fP ($directory)"
.br
.ti -1c
.RI "static \fBallFiles\fP ($directory)"
.br
.ti -1c
.RI "static \fBdirectories\fP ($directory)"
.br
.ti -1c
.RI "static \fBmakeDirectory\fP ($\fBpath\fP, $mode=493, $recursive=false, $\fBforce\fP=false)"
.br
.ti -1c
.RI "static \fBcopyDirectory\fP ($directory, $destination, $\fBoptions\fP=null)"
.br
.ti -1c
.RI "static \fBdeleteDirectory\fP ($directory, $preserve=false)"
.br
.ti -1c
.RI "static \fBcleanDirectory\fP ($directory)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5048 of file _ide_helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static allFiles ( $directory)\fC [static]\fP"
Get all of the files from the given directory (recursive)\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 5285 of file _ide_helper\&.php\&.
.SS "static append ( $path,  $data)\fC [static]\fP"
Append to a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$data\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 5128 of file _ide_helper\&.php\&.
.SS "static cleanDirectory ( $directory)\fC [static]\fP"
Empty the specified directory of all files and folders\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5348 of file _ide_helper\&.php\&.
.SS "static copy ( $path,  $target)\fC [static]\fP"
Copy a file to a new location\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$target\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5163 of file _ide_helper\&.php\&.
.SS "static copyDirectory ( $directory,  $destination,  $options = \fCnull\fP)\fC [static]\fP"
Copy a directory from one location to another\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.br
\fI$destination\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5323 of file _ide_helper\&.php\&.
.SS "static delete ( $paths)\fC [static]\fP"
Delete the file at a given path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$paths\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5139 of file _ide_helper\&.php\&.
.SS "static deleteDirectory ( $directory,  $preserve = \fCfalse\fP)\fC [static]\fP"
Recursively delete a directory\&.
.PP
The directory itself may be optionally preserved\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.br
\fI$preserve\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5337 of file _ide_helper\&.php\&.
.SS "static directories ( $directory)\fC [static]\fP"
Get all of the directories within a given directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 5296 of file _ide_helper\&.php\&.
.SS "static exists ( $path)\fC [static]\fP"
Determine if a file exists\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5057 of file _ide_helper\&.php\&.
.SS "static extension ( $path)\fC [static]\fP"
Extract the file extension from a file path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 5185 of file _ide_helper\&.php\&.
.SS "static files ( $directory)\fC [static]\fP"
Get an array of all files in a directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 5274 of file _ide_helper\&.php\&.
.SS "static get ( $path)\fC [static]\fP"
Get the contents of a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIFileNotFoundException\fP 
.RE
.PP

.PP
Definition at line 5069 of file _ide_helper\&.php\&.
.SS "static getRequire ( $path)\fC [static]\fP"
Get the returned value of a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIFileNotFoundException\fP 
.RE
.PP

.PP
Definition at line 5081 of file _ide_helper\&.php\&.
.SS "static glob ( $pattern,  $flags = \fC0\fP)\fC [static]\fP"
Find path names matching a given pattern\&.
.PP
\fBParameters:\fP
.RS 4
\fI$pattern\fP 
.br
\fI$flags\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 5263 of file _ide_helper\&.php\&.
.SS "static isDirectory ( $directory)\fC [static]\fP"
Determine if the given path is a directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5229 of file _ide_helper\&.php\&.
.SS "static isFile ( $file)\fC [static]\fP"
Determine if the given path is a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5251 of file _ide_helper\&.php\&.
.SS "static isWritable ( $path)\fC [static]\fP"
Determine if the given path is writable\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5240 of file _ide_helper\&.php\&.
.SS "static lastModified ( $path)\fC [static]\fP"
Get the file's last modification time\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 5218 of file _ide_helper\&.php\&.
.SS "static makeDirectory ( $path,  $mode = \fC493\fP,  $recursive = \fCfalse\fP,  $force = \fCfalse\fP)\fC [static]\fP"
Create a directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$mode\fP 
.br
\fI$recursive\fP 
.br
\fI$force\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5310 of file _ide_helper\&.php\&.
.SS "static move ( $path,  $target)\fC [static]\fP"
Move a file to a new location\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$target\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5151 of file _ide_helper\&.php\&.
.SS "static name ( $path)\fC [static]\fP"
Extract the file name from a file path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 5174 of file _ide_helper\&.php\&.
.SS "static prepend ( $path,  $data)\fC [static]\fP"
Prepend to a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$data\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 5116 of file _ide_helper\&.php\&.
.SS "static put ( $path,  $contents)\fC [static]\fP"
Write the contents of a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$contents\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 5104 of file _ide_helper\&.php\&.
.SS "static requireOnce ( $file)\fC [static]\fP"
Require the given file once\&.
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 5092 of file _ide_helper\&.php\&.
.SS "static size ( $path)\fC [static]\fP"
Get the file size of a given file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 5207 of file _ide_helper\&.php\&.
.SS "static type ( $path)\fC [static]\fP"
Get the file type of a given file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 5196 of file _ide_helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
