.TH "gulpfile.js" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gulpfile.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBelixir\fP (function(mix){mix\&.less('app\&.less');})"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBelixir\fP = require('laravel-elixir')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "elixir (function(mix){mix\&.less('app\&.less');})"

.SH "Variable Documentation"
.PP 
.SS "var elixir = require('laravel-elixir')"

.PP
Definition at line 1 of file gulpfile\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
