.TH "Hash" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hash \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHash\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBmake\fP ($value, $\fBoptions\fP=array())"
.br
.ti -1c
.RI "static \fBcheck\fP ($value, $hashedValue, $\fBoptions\fP=array())"
.br
.ti -1c
.RI "static \fBneedsRehash\fP ($hashedValue, $\fBoptions\fP=array())"
.br
.ti -1c
.RI "static \fBsetRounds\fP ($rounds)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5779 of file _ide_helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static check ( $value,  $hashedValue,  $options = \fCarray()\fP)\fC [static]\fP"
Check the given plain value against a hash\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$hashedValue\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5803 of file _ide_helper\&.php\&.
.SS "static make ( $value,  $options = \fCarray()\fP)\fC [static]\fP"
\fBHash\fP the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 5790 of file _ide_helper\&.php\&.
.SS "static needsRehash ( $hashedValue,  $options = \fCarray()\fP)\fC [static]\fP"
Check if the given hash has been hashed using the given options\&.
.PP
\fBParameters:\fP
.RS 4
\fI$hashedValue\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 5815 of file _ide_helper\&.php\&.
.SS "static setRounds ( $rounds)\fC [static]\fP"
Set the default crypt cost factor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$rounds\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 5826 of file _ide_helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
