.TH "moduleScripts/RTUscripts/protolibs/modbus_tk/hooks.py" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moduleScripts/RTUscripts/protolibs/modbus_tk/hooks.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBprotolibs\&.modbus_tk\&.hooks\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBinstall_hook\fP (\fBname\fP, fct)"
.br
.ti -1c
.RI "def \fBuninstall_hook\fP"
.br
.ti -1c
.RI "def \fBcall_hooks\fP (\fBname\fP, args)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fB_lock\fP = threading\&.RLock()"
.br
.ti -1c
.RI "dictionary \fB_hooks\fP = {}"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
