.TH "DatabasePresenceVerifier" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabasePresenceVerifier \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPresenceVerifierInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBConnectionResolverInterface\fP $db)"
.br
.ti -1c
.RI "\fBgetCount\fP ($collection, $column, $value, $excludeId=null, $idColumn=null, array $extra=array())"
.br
.ti -1c
.RI "\fBgetMultiCount\fP ($collection, $column, array $\fBvalues\fP, array $extra=array())"
.br
.ti -1c
.RI "\fBsetConnection\fP ($connection)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBaddWhere\fP ($query, $key, $extraValue)"
.br
.ti -1c
.RI "\fBtable\fP ($table)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$db\fP"
.br
.ti -1c
.RI "\fB$connection\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file DatabasePresenceVerifier\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBConnectionResolverInterface\fP $db)"
Create a new database presence verifier\&.
.PP
\fBParameters:\fP
.RS 4
\fI$db\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 27 of file DatabasePresenceVerifier\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addWhere ( $query,  $key,  $extraValue)\fC [protected]\fP"
Add a 'where' clause to the given query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$key\fP 
.br
\fI$extraValue\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 89 of file DatabasePresenceVerifier\&.php\&.
.SS "getCount ( $collection,  $column,  $value,  $excludeId = \fCnull\fP,  $idColumn = \fCnull\fP, array $extra = \fCarray()\fP)"
Count the number of objects in a collection having the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$collection\fP 
.br
\fI$column\fP 
.br
\fI$value\fP 
.br
\fI$excludeId\fP 
.br
\fI$idColumn\fP 
.br
\fI$extra\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBPresenceVerifierInterface\fP\&.
.PP
Definition at line 43 of file DatabasePresenceVerifier\&.php\&.
.SS "getMultiCount ( $collection,  $column, array $values, array $extra = \fCarray()\fP)"
Count the number of objects in a collection with the given values\&.
.PP
\fBParameters:\fP
.RS 4
\fI$collection\fP 
.br
\fI$column\fP 
.br
\fI$values\fP 
.br
\fI$extra\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBPresenceVerifierInterface\fP\&.
.PP
Definition at line 69 of file DatabasePresenceVerifier\&.php\&.
.SS "setConnection ( $connection)"
Set the connection to be used\&.
.PP
\fBParameters:\fP
.RS 4
\fI$connection\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 122 of file DatabasePresenceVerifier\&.php\&.
.SS "table ( $table)\fC [protected]\fP"
Get a query builder for the given table\&.
.PP
\fBParameters:\fP
.RS 4
\fI$table\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 111 of file DatabasePresenceVerifier\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$connection = null\fC [protected]\fP"

.PP
Definition at line 19 of file DatabasePresenceVerifier\&.php\&.
.SS "$db\fC [protected]\fP"

.PP
Definition at line 12 of file DatabasePresenceVerifier\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
