.TH "Factory" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Factory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBQueueingFactory\fP, and \fBQueueingFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmake\fP ($\fBname\fP, $value, $\fBminutes\fP=0, $\fBpath\fP=null, $domain=null, $secure=false, $httpOnly=true)"
.br
.ti -1c
.RI "\fBforever\fP ($\fBname\fP, $value, $\fBpath\fP=null, $domain=null, $secure=false, $httpOnly=true)"
.br
.ti -1c
.RI "\fBforget\fP ($\fBname\fP, $\fBpath\fP=null, $domain=null)"
.br
.ti -1c
.RI "\fBmake\fP ($\fBname\fP, $value, $\fBminutes\fP=0, $\fBpath\fP=null, $domain=null, $secure=false, $httpOnly=true)"
.br
.ti -1c
.RI "\fBforever\fP ($\fBname\fP, $value, $\fBpath\fP=null, $domain=null, $secure=false, $httpOnly=true)"
.br
.ti -1c
.RI "\fBforget\fP ($\fBname\fP, $\fBpath\fP=null, $domain=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 142 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "forever ( $name,  $value,  $path = \fCnull\fP,  $domain = \fCnull\fP,  $secure = \fCfalse\fP,  $httpOnly = \fCtrue\fP)"
Create a cookie that lasts 'forever' (five years)\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$value\fP 
.br
\fI$path\fP 
.br
\fI$domain\fP 
.br
\fI$secure\fP 
.br
\fI$httpOnly\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBCookieJar\fP, and \fBCookieJar\fP\&.
.SS "forever ( $name,  $value,  $path = \fCnull\fP,  $domain = \fCnull\fP,  $secure = \fCfalse\fP,  $httpOnly = \fCtrue\fP)"

.PP
Implemented in \fBCookieJar\fP, and \fBCookieJar\fP\&.
.SS "forget ( $name,  $path = \fCnull\fP,  $domain = \fCnull\fP)"
Expire the given cookie\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$path\fP 
.br
\fI$domain\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBCookieJar\fP, and \fBCookieJar\fP\&.
.SS "forget ( $name,  $path = \fCnull\fP,  $domain = \fCnull\fP)"

.PP
Implemented in \fBCookieJar\fP, and \fBCookieJar\fP\&.
.SS "make ( $name,  $value,  $minutes = \fC0\fP,  $path = \fCnull\fP,  $domain = \fCnull\fP,  $secure = \fCfalse\fP,  $httpOnly = \fCtrue\fP)"
Create a new cookie instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$value\fP 
.br
\fI$minutes\fP 
.br
\fI$path\fP 
.br
\fI$domain\fP 
.br
\fI$secure\fP 
.br
\fI$httpOnly\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBCookieJar\fP, and \fBCookieJar\fP\&.
.SS "make ( $name,  $value,  $minutes = \fC0\fP,  $path = \fCnull\fP,  $domain = \fCnull\fP,  $secure = \fCfalse\fP,  $httpOnly = \fCtrue\fP)"

.PP
Implemented in \fBCookieJar\fP, and \fBCookieJar\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
