.TH "Schedule" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Schedule \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcall\fP ($\fBcallback\fP, array $parameters=array())"
.br
.ti -1c
.RI "\fBcommand\fP ($command)"
.br
.ti -1c
.RI "\fBexec\fP ($\fBcommand\fP)"
.br
.ti -1c
.RI "\fBevents\fP ()"
.br
.ti -1c
.RI "\fBdueEvents\fP (\fBApplication\fP $app)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$events\fP = []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Schedule\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "call ( $callback, array $parameters = \fCarray()\fP)"
Add a new callback event to the schedule\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP 
.br
\fI$parameters\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 21 of file Schedule\&.php\&.
.SS "command ( $command)"
Add a new \fBArtisan\fP command event to the schedule\&.
.PP
\fBParameters:\fP
.RS 4
\fI$command\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 34 of file Schedule\&.php\&.
.SS "dueEvents (\fBApplication\fP $app)"
Get all of the events on the schedule that are due\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 68 of file Schedule\&.php\&.
.SS "events ()"
Get all of the events on the schedule\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 57 of file Schedule\&.php\&.
.SS "exec ( $command)"
Add a new command event to the schedule\&.
.PP
\fBParameters:\fP
.RS 4
\fI$command\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 45 of file Schedule\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBevents\fP = []\fC [protected]\fP"

.PP
Definition at line 12 of file Schedule\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
