.TH "ExistenceAwareInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExistenceAwareInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDatabaseSessionHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetExists\fP ($value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file ExistenceAwareInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setExists ( $value)"
Set the existence state for the session\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBDatabaseSessionHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
