.TH "Arrayable" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Arrayable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBModel\fP, \fBModel\fP, \fBLengthAwarePaginator\fP, \fBPaginator\fP, \fBPaginator\fP, \fBCollection\fP, \fBCollection\fP, \fBFluent\fP, \fBMessageBag\fP, and \fBMessageBag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 130 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "toArray ()"
Get the instance as an array\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBMessageBag\fP, \fBCollection\fP, \fBModel\fP, \fBPaginator\fP, \fBModel\fP, \fBCollection\fP, \fBMessageBag\fP, \fBLengthAwarePaginator\fP, \fBPaginator\fP, and \fBFluent\fP\&.
.SS "toArray ()"

.PP
Implemented in \fBMessageBag\fP, \fBCollection\fP, \fBModel\fP, \fBPaginator\fP, \fBModel\fP, \fBCollection\fP, \fBMessageBag\fP, \fBLengthAwarePaginator\fP, \fBPaginator\fP, and \fBFluent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
