.TH "Collection" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collection \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCollection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfind\fP ($key, $default=null)"
.br
.ti -1c
.RI "\fBload\fP ($relations)"
.br
.ti -1c
.RI "\fBadd\fP ($item)"
.br
.ti -1c
.RI "\fBcontains\fP ($key, $value=null)"
.br
.ti -1c
.RI "\fBfetch\fP ($key)"
.br
.ti -1c
.RI "\fBmax\fP ($key)"
.br
.ti -1c
.RI "\fBmin\fP ($key)"
.br
.ti -1c
.RI "\fBmodelKeys\fP ()"
.br
.ti -1c
.RI "\fBmerge\fP ($items)"
.br
.ti -1c
.RI "\fBdiff\fP ($items)"
.br
.ti -1c
.RI "\fBintersect\fP ($items)"
.br
.ti -1c
.RI "\fBunique\fP ()"
.br
.ti -1c
.RI "\fBonly\fP ($\fBkeys\fP)"
.br
.ti -1c
.RI "\fBexcept\fP ($\fBkeys\fP)"
.br
.ti -1c
.RI "\fBgetDictionary\fP ($items=null)"
.br
.ti -1c
.RI "\fBtoBase\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file Collection\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "add ( $item)"
Add an item to the collection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$item\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 54 of file Collection\&.php\&.
.SS "contains ( $key,  $value = \fCnull\fP)"
Determine if a key exists in the collection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 68 of file Collection\&.php\&.
.SS "diff ( $items)"
\fBDiff\fP the collection with the given items\&.
.PP
\fBParameters:\fP
.RS 4
\fI$items\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
static 
.RE
.PP

.PP
Definition at line 158 of file Collection\&.php\&.
.SS "except ( $keys)"
Returns all models in the collection except the models with specified keys\&.
.PP
\fBParameters:\fP
.RS 4
\fI$keys\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
static 
.RE
.PP

.PP
Definition at line 229 of file Collection\&.php\&.
.SS "fetch ( $key)"
Fetch a nested element of the collection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
static 
.RE
.PP

.PP
Definition at line 91 of file Collection\&.php\&.
.SS "find ( $key,  $default = \fCnull\fP)"
Find a model in the collection by key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$default\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 14 of file Collection\&.php\&.
.SS "getDictionary ( $items = \fCnull\fP)"
Get a dictionary keyed by primary keys\&.
.PP
\fBParameters:\fP
.RS 4
\fI$items\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 242 of file Collection\&.php\&.
.SS "intersect ( $items)"
Intersect the collection with the given items\&.
.PP
\fBParameters:\fP
.RS 4
\fI$items\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
static 
.RE
.PP

.PP
Definition at line 181 of file Collection\&.php\&.
.SS "load ( $relations)"
Load a set of relationships onto the collection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$relations\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 34 of file Collection\&.php\&.
.SS "max ( $key)"
Get the max value of a given key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 102 of file Collection\&.php\&.
.SS "merge ( $items)"
Merge the collection with the given items\&.
.PP
\fBParameters:\fP
.RS 4
\fI$items\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
static 
.RE
.PP

.PP
Definition at line 140 of file Collection\&.php\&.
.SS "min ( $key)"
Get the min value of a given key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 116 of file Collection\&.php\&.
.SS "modelKeys ()"
Get the array of primary keys\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 129 of file Collection\&.php\&.
.SS "only ( $keys)"
Returns only the models from the collection with the specified keys\&.
.PP
\fBParameters:\fP
.RS 4
\fI$keys\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
static 
.RE
.PP

.PP
Definition at line 216 of file Collection\&.php\&.
.SS "toBase ()"
Get a base \fBSupport\fP collection instance from this collection\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 261 of file Collection\&.php\&.
.SS "unique ()"
Return only unique items from the collection\&.
.PP
\fBReturns:\fP
.RS 4
static 
.RE
.PP

.PP
Definition at line 203 of file Collection\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
