.TH "DatabaseTokenRepository" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseTokenRepository \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTokenRepositoryInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBConnectionInterface\fP $connection, $table, $hashKey, $expires=60)"
.br
.ti -1c
.RI "\fBcreate\fP (CanResetPasswordContract $user)"
.br
.ti -1c
.RI "\fBexists\fP (CanResetPasswordContract $user, $token)"
.br
.ti -1c
.RI "\fBdelete\fP ($token)"
.br
.ti -1c
.RI "\fBdeleteExpired\fP ()"
.br
.ti -1c
.RI "\fBcreateNewToken\fP (CanResetPasswordContract $user)"
.br
.ti -1c
.RI "\fBgetConnection\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBdeleteExisting\fP (CanResetPasswordContract $user)"
.br
.ti -1c
.RI "\fBgetPayload\fP ($email, $token)"
.br
.ti -1c
.RI "\fBtokenExpired\fP ($token)"
.br
.ti -1c
.RI "\fBgetCurrentTime\fP ()"
.br
.ti -1c
.RI "\fBgetTable\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$connection\fP"
.br
.ti -1c
.RI "\fB$table\fP"
.br
.ti -1c
.RI "\fB$hashKey\fP"
.br
.ti -1c
.RI "\fB$expires\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file DatabaseTokenRepository\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBConnectionInterface\fP $connection,  $table,  $hashKey,  $expires = \fC60\fP)"
Create a new token repository instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$connection\fP 
.br
\fI$table\fP 
.br
\fI$hashKey\fP 
.br
\fI$expires\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 46 of file DatabaseTokenRepository\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "create (CanResetPasswordContract $user)"
Create a new token record\&.
.PP
\fBParameters:\fP
.RS 4
\fI$user\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBTokenRepositoryInterface\fP\&.
.PP
Definition at line 60 of file DatabaseTokenRepository\&.php\&.
.SS "createNewToken (CanResetPasswordContract $user)"
Create a new token for the user\&.
.PP
\fBParameters:\fP
.RS 4
\fI$user\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 167 of file DatabaseTokenRepository\&.php\&.
.SS "delete ( $token)"
Delete a token record by token\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBTokenRepositoryInterface\fP\&.
.PP
Definition at line 144 of file DatabaseTokenRepository\&.php\&.
.SS "deleteExisting (CanResetPasswordContract $user)\fC [protected]\fP"
Delete all existing reset tokens from the database\&.
.PP
\fBParameters:\fP
.RS 4
\fI$user\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 82 of file DatabaseTokenRepository\&.php\&.
.SS "deleteExpired ()"
Delete expired tokens\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBTokenRepositoryInterface\fP\&.
.PP
Definition at line 154 of file DatabaseTokenRepository\&.php\&.
.SS "exists (CanResetPasswordContract $user,  $token)"
Determine if a token record exists and is valid\&.
.PP
\fBParameters:\fP
.RS 4
\fI$user\fP 
.br
\fI$token\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBTokenRepositoryInterface\fP\&.
.PP
Definition at line 106 of file DatabaseTokenRepository\&.php\&.
.SS "getConnection ()"
Get the database connection instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 187 of file DatabaseTokenRepository\&.php\&.
.SS "getCurrentTime ()\fC [protected]\fP"
Get the current UNIX timestamp\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 133 of file DatabaseTokenRepository\&.php\&.
.SS "getPayload ( $email,  $token)\fC [protected]\fP"
Build the record payload for the table\&.
.PP
\fBParameters:\fP
.RS 4
\fI$email\fP 
.br
\fI$token\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 94 of file DatabaseTokenRepository\&.php\&.
.SS "getTable ()\fC [protected]\fP"
Begin a new database query against the table\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 177 of file DatabaseTokenRepository\&.php\&.
.SS "tokenExpired ( $token)\fC [protected]\fP"
Determine if the token has expired\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 121 of file DatabaseTokenRepository\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$connection\fC [protected]\fP"

.PP
Definition at line 14 of file DatabaseTokenRepository\&.php\&.
.SS "$expires\fC [protected]\fP"

.PP
Definition at line 35 of file DatabaseTokenRepository\&.php\&.
.SS "$hashKey\fC [protected]\fP"

.PP
Definition at line 28 of file DatabaseTokenRepository\&.php\&.
.SS "$table\fC [protected]\fP"

.PP
Definition at line 21 of file DatabaseTokenRepository\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
