.TH "Illuminate\Cache" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Illuminate\Cache \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBConsole\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBApcStore\fP"
.br
.ti -1c
.RI "class \fBApcWrapper\fP"
.br
.ti -1c
.RI "class \fBArrayStore\fP"
.br
.ti -1c
.RI "class \fBCacheManager\fP"
.br
.ti -1c
.RI "class \fBCacheServiceProvider\fP"
.br
.ti -1c
.RI "class \fBDatabaseStore\fP"
.br
.ti -1c
.RI "class \fBFileStore\fP"
.br
.ti -1c
.RI "class \fBMemcachedConnector\fP"
.br
.ti -1c
.RI "class \fBMemcachedStore\fP"
.br
.ti -1c
.RI "class \fBNullStore\fP"
.br
.ti -1c
.RI "class \fBRedisStore\fP"
.br
.ti -1c
.RI "class \fBRedisTaggedCache\fP"
.br
.ti -1c
.RI "class \fBRepository\fP"
.br
.ti -1c
.RI "class \fBTaggableStore\fP"
.br
.ti -1c
.RI "class \fBTaggedCache\fP"
.br
.ti -1c
.RI "class \fBTagSet\fP"
.br
.ti -1c
.RI "class \fBWinCacheStore\fP"
.br
.ti -1c
.RI "class \fBXCacheStore\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
