.TH "QueueingDispatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueingDispatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDispatcher\fP, and \fBDispatcher\fP\&.
.PP
Inherited by \fBDispatcher\fP, and \fBDispatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdispatchToQueue\fP ($command)"
.br
.ti -1c
.RI "\fBdispatchToQueue\fP ($command)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "dispatchToQueue ( $command)"
Dispatch a command to its appropriate handler behind a queue\&.
.PP
\fBParameters:\fP
.RS 4
\fI$command\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBDispatcher\fP, and \fBDispatcher\fP\&.
.SS "dispatchToQueue ( $command)"

.PP
Implemented in \fBDispatcher\fP, and \fBDispatcher\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
