.TH "HandleExceptions" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HandleExceptions \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbootstrap\fP (\fBApplication\fP $app)"
.br
.ti -1c
.RI "\fBhandleError\fP ($level, $message, $file= '', $\fBline\fP=0, $context=array())"
.br
.ti -1c
.RI "\fBhandleException\fP ($\fBe\fP)"
.br
.ti -1c
.RI "\fBhandleShutdown\fP ()"
.br
.ti -1c
.RI "\fBbootstrap\fP (\fBApplication\fP $app)"
.br
.ti -1c
.RI "\fBhandleError\fP ($level, $message, $file= '', $\fBline\fP=0, $context=array())"
.br
.ti -1c
.RI "\fBhandleException\fP ($\fBe\fP)"
.br
.ti -1c
.RI "\fBhandleShutdown\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBrenderForConsole\fP ($\fBe\fP)"
.br
.ti -1c
.RI "\fBrenderHttpResponse\fP ($\fBe\fP)"
.br
.ti -1c
.RI "\fBfatalExceptionFromError\fP (array $error, $traceOffset=null)"
.br
.ti -1c
.RI "\fBisFatal\fP ($type)"
.br
.ti -1c
.RI "\fBgetExceptionHandler\fP ()"
.br
.ti -1c
.RI "\fBrenderForConsole\fP ($\fBe\fP)"
.br
.ti -1c
.RI "\fBrenderHttpResponse\fP ($\fBe\fP)"
.br
.ti -1c
.RI "\fBfatalExceptionFromError\fP (array $error, $traceOffset=null)"
.br
.ti -1c
.RI "\fBisFatal\fP ($type)"
.br
.ti -1c
.RI "\fBgetExceptionHandler\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$app\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1742 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "bootstrap (\fBApplication\fP $app)"
\fBBootstrap\fP the given application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 23 of file HandleExceptions\&.php\&.
.SS "bootstrap (\fBApplication\fP $app)"

.PP
Definition at line 1745 of file compiled\&.php\&.
.SS "fatalExceptionFromError (array $error,  $traceOffset = \fCnull\fP)\fC [protected]\fP"
Create a new fatal exception instance from an error array\&.
.PP
\fBParameters:\fP
.RS 4
\fI$error\fP 
.br
\fI$traceOffset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 127 of file HandleExceptions\&.php\&.
.SS "fatalExceptionFromError (array $error,  $traceOffset = \fCnull\fP)\fC [protected]\fP"

.PP
Definition at line 1785 of file compiled\&.php\&.
.SS "getExceptionHandler ()\fC [protected]\fP"
Get an instance of the exception handler\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 150 of file HandleExceptions\&.php\&.
.SS "getExceptionHandler ()\fC [protected]\fP"

.PP
Definition at line 1793 of file compiled\&.php\&.
.SS "handleError ( $level,  $message,  $file = \fC''\fP,  $line = \fC0\fP,  $context = \fCarray()\fP)"
Convert a \fBPHP\fP error to an ErrorException\&.
.PP
\fBParameters:\fP
.RS 4
\fI$level\fP 
.br
\fI$message\fP 
.br
\fI$file\fP 
.br
\fI$line\fP 
.br
\fI$context\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 53 of file HandleExceptions\&.php\&.
.SS "handleError ( $level,  $message,  $file = \fC''\fP,  $line = \fC0\fP,  $context = \fCarray()\fP)"

.PP
Definition at line 1756 of file compiled\&.php\&.
.SS "handleException ( $e)"
Handle an uncaught exception from the application\&.
.PP
Note: Most exceptions can be handled via the try / catch block in the HTTP and \fBConsole\fP kernels\&. But, fatal error exceptions must be handled differently since they are not normal exceptions\&.
.PP
\fBParameters:\fP
.RS 4
\fI$e\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 71 of file HandleExceptions\&.php\&.
.SS "handleException ( $e)"

.PP
Definition at line 1762 of file compiled\&.php\&.
.SS "handleShutdown ()"
Handle the \fBPHP\fP shutdown event\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 112 of file HandleExceptions\&.php\&.
.SS "handleShutdown ()"

.PP
Definition at line 1779 of file compiled\&.php\&.
.SS "isFatal ( $type)\fC [protected]\fP"
Determine if the error type is fatal\&.
.PP
\fBParameters:\fP
.RS 4
\fI$type\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 140 of file HandleExceptions\&.php\&.
.SS "isFatal ( $type)\fC [protected]\fP"

.PP
Definition at line 1789 of file compiled\&.php\&.
.SS "renderForConsole ( $e)\fC [protected]\fP"
Render an exception to the console\&.
.PP
\fBParameters:\fP
.RS 4
\fI$e\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 91 of file HandleExceptions\&.php\&.
.SS "renderForConsole ( $e)\fC [protected]\fP"

.PP
Definition at line 1771 of file compiled\&.php\&.
.SS "renderHttpResponse ( $e)\fC [protected]\fP"
Render an exception as an HTTP response and send it\&.
.PP
\fBParameters:\fP
.RS 4
\fI$e\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 102 of file HandleExceptions\&.php\&.
.SS "renderHttpResponse ( $e)\fC [protected]\fP"

.PP
Definition at line 1775 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$app\fC [protected]\fP"

.PP
Definition at line 1744 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
