.TH "Grammar" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Grammar \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGrammar\fP, and \fBGrammar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBwrapArray\fP (array $\fBvalues\fP)"
.br
.ti -1c
.RI "\fBwrapTable\fP ($table)"
.br
.ti -1c
.RI "\fBwrap\fP ($value, $prefixAlias=false)"
.br
.ti -1c
.RI "\fBcolumnize\fP (array $columns)"
.br
.ti -1c
.RI "\fBparameterize\fP (array $\fBvalues\fP)"
.br
.ti -1c
.RI "\fBparameter\fP ($value)"
.br
.ti -1c
.RI "\fBgetValue\fP ($expression)"
.br
.ti -1c
.RI "\fBisExpression\fP ($value)"
.br
.ti -1c
.RI "\fBgetDateFormat\fP ()"
.br
.ti -1c
.RI "\fBgetTablePrefix\fP ()"
.br
.ti -1c
.RI "\fBsetTablePrefix\fP ($prefix)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwrapValue\fP ($value)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$tablePrefix\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Grammar\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "columnize (array $columns)"
Convert an array of column names into a delimited string\&.
.PP
\fBParameters:\fP
.RS 4
\fI$columns\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 100 of file Grammar\&.php\&.
.SS "getDateFormat ()"
Get the format for database stored dates\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 154 of file Grammar\&.php\&.
.SS "getTablePrefix ()"
Get the grammar's table prefix\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 164 of file Grammar\&.php\&.
.SS "getValue ( $expression)"
Get the value of a raw expression\&.
.PP
\fBParameters:\fP
.RS 4
\fI$expression\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 133 of file Grammar\&.php\&.
.SS "isExpression ( $value)"
Determine if the given value is a raw expression\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 144 of file Grammar\&.php\&.
.SS "parameter ( $value)"
Get the appropriate query parameter place-holder for a value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 122 of file Grammar\&.php\&.
.SS "parameterize (array $values)"
Create query parameter place-holders for an array\&.
.PP
\fBParameters:\fP
.RS 4
\fI$values\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 111 of file Grammar\&.php\&.
.SS "setTablePrefix ( $prefix)"
Set the grammar's table prefix\&.
.PP
\fBParameters:\fP
.RS 4
\fI$prefix\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 175 of file Grammar\&.php\&.
.SS "wrap ( $value,  $prefixAlias = \fCfalse\fP)"
Wrap a value in keyword identifiers\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$prefixAlias\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 43 of file Grammar\&.php\&.
.SS "wrapArray (array $values)"
Wrap an array of values\&.
.PP
\fBParameters:\fP
.RS 4
\fI$values\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 18 of file Grammar\&.php\&.
.SS "wrapTable ( $table)"
Wrap a table in keyword identifiers\&.
.PP
\fBParameters:\fP
.RS 4
\fI$table\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 29 of file Grammar\&.php\&.
.SS "wrapValue ( $value)\fC [protected]\fP"
Wrap a single string in keyword identifiers\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 87 of file Grammar\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$tablePrefix = ''\fC [protected]\fP"

.PP
Definition at line 10 of file Grammar\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
