.TH "FilesystemServiceProvider" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilesystemServiceProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBServiceProvider\fP, and \fBServiceProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBregister\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBregisterNativeFilesystem\fP ()"
.br
.ti -1c
.RI "\fBregisterFlysystem\fP ()"
.br
.ti -1c
.RI "\fBregisterManager\fP ()"
.br
.ti -1c
.RI "\fBgetDefaultDriver\fP ()"
.br
.ti -1c
.RI "\fBgetCloudDriver\fP ()"
.br
.ti -1c
.RI "\fBregisterNativeFilesystem\fP ()"
.br
.ti -1c
.RI "\fBregisterFlysystem\fP ()"
.br
.ti -1c
.RI "\fBregisterManager\fP ()"
.br
.ti -1c
.RI "\fBgetDefaultDriver\fP ()"
.br
.ti -1c
.RI "\fBgetCloudDriver\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6612 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getCloudDriver ()\fC [protected]\fP"
Get the default cloud based file driver\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 77 of file FilesystemServiceProvider\&.php\&.
.SS "getCloudDriver ()\fC [protected]\fP"

.PP
Definition at line 6645 of file compiled\&.php\&.
.SS "getDefaultDriver ()\fC [protected]\fP"
Get the default file driver\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 67 of file FilesystemServiceProvider\&.php\&.
.SS "getDefaultDriver ()\fC [protected]\fP"

.PP
Definition at line 6641 of file compiled\&.php\&.
.SS "register ()"
Register the service provider\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 12 of file FilesystemServiceProvider\&.php\&.
.SS "register ()"

.PP
Definition at line 6614 of file compiled\&.php\&.
.SS "registerFlysystem ()\fC [protected]\fP"
Register the driver based filesystem\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 34 of file FilesystemServiceProvider\&.php\&.
.SS "registerFlysystem ()\fC [protected]\fP"

.PP
Definition at line 6625 of file compiled\&.php\&.
.SS "registerManager ()\fC [protected]\fP"
Register the filesystem manager\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 54 of file FilesystemServiceProvider\&.php\&.
.SS "registerManager ()\fC [protected]\fP"

.PP
Definition at line 6635 of file compiled\&.php\&.
.SS "registerNativeFilesystem ()\fC [protected]\fP"
Register the native filesystem implementation\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 24 of file FilesystemServiceProvider\&.php\&.
.SS "registerNativeFilesystem ()\fC [protected]\fP"

.PP
Definition at line 6619 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
