.TH "MailServiceProvider" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MailServiceProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBServiceProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBregisterSwiftMailer\fP ()"
.br
.ti -1c
.RI "\fBprovides\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetMailerDependencies\fP ($mailer, $app)"
.br
.ti -1c
.RI "\fBregisterSwiftTransport\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$defer\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file MailServiceProvider\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provides ()"
Get the services provided by the provider\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 114 of file MailServiceProvider\&.php\&.
.SS "register ()"
Register the service provider\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 20 of file MailServiceProvider\&.php\&.
.SS "registerSwiftMailer ()"
Register the \fBSwift\fP \fBMailer\fP instance\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 83 of file MailServiceProvider\&.php\&.
.SS "registerSwiftTransport ()\fC [protected]\fP"
Register the \fBSwift\fP \fBTransport\fP instance\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 101 of file MailServiceProvider\&.php\&.
.SS "setMailerDependencies ( $mailer,  $app)\fC [protected]\fP"
Set a few dependencies on the mailer instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$mailer\fP 
.br
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 63 of file MailServiceProvider\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$defer = true\fC [protected]\fP"

.PP
Definition at line 13 of file MailServiceProvider\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
