.TH "Illuminate\Support\Traits" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Illuminate\Support\Traits \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fB__call\fP ($method, $parameters)"
.br
.ti -1c
.RI "\fBsetupContainer\fP (\fBContainer\fP $container)"
.br
.ti -1c
.RI "\fBsetAsGlobal\fP ()"
.br
.ti -1c
.RI "\fBgetContainer\fP ()"
.br
.ti -1c
.RI "\fBsetContainer\fP (\fBContainer\fP $container)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBMacroable\fP"
.br
.ti -1c
.RI "trait \fBCapsuleManagerTrait\fP"
.br
.ti -1c
.RI "\fB$container\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__call ( $method,  $parameters)"
Dynamically handle calls to the class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$parameters\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 5398 of file compiled\&.php\&.
.SS "Illuminate\\Support\\Traits\\getContainer ()"
Get the IoC container instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 53 of file CapsuleManagerTrait\&.php\&.
.SS "Illuminate\\Support\\Traits\\setAsGlobal ()"
Make this capsule instance available globally\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 43 of file CapsuleManagerTrait\&.php\&.
.SS "Illuminate\\Support\\Traits\\setContainer (\fBContainer\fP $container)"
Set the IoC container instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$container\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 64 of file CapsuleManagerTrait\&.php\&.
.SS "Illuminate\\Support\\Traits\\setupContainer (\fBContainer\fP $container)\fC [protected]\fP"
Setup the IoC container instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$container\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 28 of file CapsuleManagerTrait\&.php\&.
.SH "Variable Documentation"
.PP 
.SS "$container"

.PP
Definition at line 20 of file CapsuleManagerTrait\&.php\&.
.SS "trait CapsuleManagerTrait"
\fBInitial value:\fP
.PP
.nf
{

    
    protected static $instance
.fi
.PP
Definition at line 6 of file CapsuleManagerTrait\&.php\&.
.SS "trait Macroable"
\fBInitial value:\fP
.PP
.nf
{
    protected static $macros = array()
.fi
.PP
Definition at line 5377 of file compiled\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
