.TH "Repository" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Repository \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhas\fP ($key)"
.br
.ti -1c
.RI "\fBget\fP ($key, $default=null)"
.br
.ti -1c
.RI "\fBpull\fP ($key, $default=null)"
.br
.ti -1c
.RI "\fBput\fP ($key, $value, $\fBminutes\fP)"
.br
.ti -1c
.RI "\fBadd\fP ($key, $value, $\fBminutes\fP)"
.br
.ti -1c
.RI "\fBforever\fP ($key, $value)"
.br
.ti -1c
.RI "\fBremember\fP ($key, $\fBminutes\fP, Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBsear\fP ($key, Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBrememberForever\fP ($key, Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBforget\fP ($key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Repository\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "add ( $key,  $value,  $minutes)"
\fBStore\fP an item in the cache if the key does not exist\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.br
\fI$minutes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "forever ( $key,  $value)"
\fBStore\fP an item in the cache indefinitely\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "forget ( $key)"
Remove an item from the cache\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "get ( $key,  $default = \fCnull\fP)"
Retrieve an item from the cache by key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$default\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "has ( $key)"
Determine if an item exists in the cache\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "pull ( $key,  $default = \fCnull\fP)"
Retrieve an item from the cache and delete it\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$default\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "put ( $key,  $value,  $minutes)"
\fBStore\fP an item in the cache\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.br
\fI$minutes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "remember ( $key,  $minutes, Closure $callback)"
Get an item from the cache, or store the default value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$minutes\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "rememberForever ( $key, Closure $callback)"
Get an item from the cache, or store the default value forever\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.
.SS "sear ( $key, Closure $callback)"
Get an item from the cache, or store the default value forever\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBRepository\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
