.TH "ApcStore" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApcStore \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTaggableStore\fP, and \fBStore\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBApcWrapper\fP $apc, $prefix= '')"
.br
.ti -1c
.RI "\fBget\fP ($key)"
.br
.ti -1c
.RI "\fBput\fP ($key, $value, $\fBminutes\fP)"
.br
.ti -1c
.RI "\fBincrement\fP ($key, $value=1)"
.br
.ti -1c
.RI "\fBdecrement\fP ($key, $value=1)"
.br
.ti -1c
.RI "\fBforever\fP ($key, $value)"
.br
.ti -1c
.RI "\fBforget\fP ($key)"
.br
.ti -1c
.RI "\fBflush\fP ()"
.br
.ti -1c
.RI "\fBgetPrefix\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$apc\fP"
.br
.ti -1c
.RI "\fB$prefix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ApcStore\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBApcWrapper\fP $apc,  $prefix = \fC''\fP)"
Create a new APC store\&.
.PP
\fBParameters:\fP
.RS 4
\fI$apc\fP 
.br
\fI$prefix\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 28 of file ApcStore\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "decrement ( $key,  $value = \fC1\fP)"
Decrement the value of an item in the cache\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int|bool 
.RE
.PP

.PP
Implements \fBStore\fP\&.
.PP
Definition at line 82 of file ApcStore\&.php\&.
.SS "flush ()"
Remove all items from the cache\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBStore\fP\&.
.PP
Definition at line 115 of file ApcStore\&.php\&.
.SS "forever ( $key,  $value)"
Store an item in the cache indefinitely\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array|bool 
.RE
.PP

.PP
Implements \fBStore\fP\&.
.PP
Definition at line 94 of file ApcStore\&.php\&.
.SS "forget ( $key)"
Remove an item from the cache\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBStore\fP\&.
.PP
Definition at line 105 of file ApcStore\&.php\&.
.SS "get ( $key)"
Retrieve an item from the cache by key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBStore\fP\&.
.PP
Definition at line 40 of file ApcStore\&.php\&.
.SS "getPrefix ()"
Get the cache key prefix\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBStore\fP\&.
.PP
Definition at line 125 of file ApcStore\&.php\&.
.SS "increment ( $key,  $value = \fC1\fP)"
Increment the value of an item in the cache\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int|bool 
.RE
.PP

.PP
Implements \fBStore\fP\&.
.PP
Definition at line 70 of file ApcStore\&.php\&.
.SS "put ( $key,  $value,  $minutes)"
Store an item in the cache for a given number of minutes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.br
\fI$minutes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBStore\fP\&.
.PP
Definition at line 58 of file ApcStore\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$apc\fC [protected]\fP"

.PP
Definition at line 12 of file ApcStore\&.php\&.
.SS "$prefix\fC [protected]\fP"

.PP
Definition at line 19 of file ApcStore\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
