.TH "GeneratorCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeneratorCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.PP
Inherited by \fBCommandMakeCommand\fP, \fBConsoleMakeCommand\fP, \fBEventMakeCommand\fP, \fBHandlerCommandCommand\fP, \fBHandlerEventCommand\fP, \fBModelMakeCommand\fP, \fBProviderMakeCommand\fP, \fBRequestMakeCommand\fP, \fBControllerMakeCommand\fP, and \fBMiddlewareMakeCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBFilesystem\fP $files)"
.br
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetStub\fP ()"
.br
.ti -1c
.RI "\fBgetPath\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBparseName\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBgetDefaultNamespace\fP ($rootNamespace)"
.br
.ti -1c
.RI "\fBmakeDirectory\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBbuildClass\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBreplaceNamespace\fP (&$stub, $\fBname\fP)"
.br
.ti -1c
.RI "\fBgetNamespace\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBreplaceClass\fP ($stub, $\fBname\fP)"
.br
.ti -1c
.RI "\fBgetNameInput\fP ()"
.br
.ti -1c
.RI "\fBgetArguments\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$files\fP"
.br
.ti -1c
.RI "\fB$type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file GeneratorCommand\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBFilesystem\fP $files)"
Create a new controller creator command instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$files\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 30 of file GeneratorCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "buildClass ( $name)\fC [protected]\fP"
Build the class with the given name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 132 of file GeneratorCommand\&.php\&.
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 49 of file GeneratorCommand\&.php\&.
.SS "getArguments ()\fC [protected]\fP"
Get the console command arguments\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 199 of file GeneratorCommand\&.php\&.
.SS "getDefaultNamespace ( $rootNamespace)\fC [protected]\fP"
Get the default namespace for the class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$rootNamespace\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 107 of file GeneratorCommand\&.php\&.
.SS "getNameInput ()\fC [protected]\fP"
Get the desired class name from the input\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 189 of file GeneratorCommand\&.php\&.
.SS "getNamespace ( $name)\fC [protected]\fP"
Get the full namespace name for a given class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 165 of file GeneratorCommand\&.php\&.
.SS "getPath ( $name)\fC [protected]\fP"
Get the destination class path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 71 of file GeneratorCommand\&.php\&.
.SS "getStub ()\fC [abstract]\fP, \fC [protected]\fP"
Get the stub file for the generator\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "makeDirectory ( $path)\fC [protected]\fP"
Build the directory for the class if necessary\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 118 of file GeneratorCommand\&.php\&.
.SS "parseName ( $name)\fC [protected]\fP"
Parse the name and format according to the root namespace\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 84 of file GeneratorCommand\&.php\&.
.SS "replaceClass ( $stub,  $name)\fC [protected]\fP"
Replace the class name for the given stub\&.
.PP
\fBParameters:\fP
.RS 4
\fI$stub\fP 
.br
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 177 of file GeneratorCommand\&.php\&.
.SS "replaceNamespace (& $stub,  $name)\fC [protected]\fP"
Replace the namespace for the given stub\&.
.PP
\fBParameters:\fP
.RS 4
\fI$stub\fP 
.br
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 146 of file GeneratorCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$files\fC [protected]\fP"

.PP
Definition at line 15 of file GeneratorCommand\&.php\&.
.SS "$type\fC [protected]\fP"

.PP
Definition at line 22 of file GeneratorCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
