.TH "ConfigCacheCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigCacheCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBFilesystem\fP $files)"
.br
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetFreshConfiguration\fP ()"
.br
.ti -1c
.RI "\fBsetRealSessionDriver\fP (array $config)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'config:cache'"
.br
.ti -1c
.RI "\fB$description\fP = 'Create \fBa\fP cache file \fBfor\fP faster configuration loading'"
.br
.ti -1c
.RI "\fB$files\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ConfigCacheCommand\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBFilesystem\fP $files)"
Create a new config cache command instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$files\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 35 of file ConfigCacheCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 47 of file ConfigCacheCommand\&.php\&.
.SS "getFreshConfiguration ()\fC [protected]\fP"
Boot a fresh copy of the application configuration\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 67 of file ConfigCacheCommand\&.php\&.
.SS "setRealSessionDriver (array $config)\fC [protected]\fP"
Set the 'real' session driver on the configuration array\&.
.PP
Typically the SessionManager forces the driver to 'array' in CLI environment\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 84 of file ConfigCacheCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$description = 'Create \fBa\fP cache file \fBfor\fP faster configuration loading'\fC [protected]\fP"

.PP
Definition at line 20 of file ConfigCacheCommand\&.php\&.
.SS "$files\fC [protected]\fP"

.PP
Definition at line 27 of file ConfigCacheCommand\&.php\&.
.SS "$\fBname\fP = 'config:cache'\fC [protected]\fP"

.PP
Definition at line 13 of file ConfigCacheCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
