.TH "Registrar" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Registrar \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRegistrar\fP, \fBRouter\fP, and \fBRouter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBget\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBpost\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBput\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBdelete\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBpatch\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBoptions\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBmatch\fP ($methods, $uri, $action)"
.br
.ti -1c
.RI "\fBresource\fP ($\fBname\fP, $controller, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBgroup\fP (array $attributes, Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBbefore\fP ($\fBcallback\fP)"
.br
.ti -1c
.RI "\fBafter\fP ($\fBcallback\fP)"
.br
.ti -1c
.RI "\fBfilter\fP ($\fBname\fP, $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBget\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBpost\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBput\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBdelete\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBpatch\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBoptions\fP ($uri, $action)"
.br
.ti -1c
.RI "\fBmatch\fP ($methods, $uri, $action)"
.br
.ti -1c
.RI "\fBresource\fP ($\fBname\fP, $controller, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBgroup\fP (array $attributes, Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBbefore\fP ($\fBcallback\fP)"
.br
.ti -1c
.RI "\fBafter\fP ($\fBcallback\fP)"
.br
.ti -1c
.RI "\fBfilter\fP ($\fBname\fP, $\fBcallback\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 174 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "after ( $callback)"
Register a new 'after' filter with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "after ( $callback)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "before ( $callback)"
Register a new 'before' filter with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "before ( $callback)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "delete ( $uri,  $action)"
Register a new DELETE route with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$uri\fP 
.br
\fI$action\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "delete ( $uri,  $action)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "filter ( $name,  $callback)"
Register a new filter with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "filter ( $name,  $callback)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "get ( $uri,  $action)"
Register a new GET route with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$uri\fP 
.br
\fI$action\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "get ( $uri,  $action)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "group (array $attributes, Closure $callback)"
Create a route group with shared attributes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$attributes\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "group (array $attributes, Closure $callback)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "match ( $methods,  $uri,  $action)"
Register a new route with the given verbs\&.
.PP
\fBParameters:\fP
.RS 4
\fI$methods\fP 
.br
\fI$uri\fP 
.br
\fI$action\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "match ( $methods,  $uri,  $action)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "options ( $uri,  $action)"
Register a new OPTIONS route with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$uri\fP 
.br
\fI$action\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "options ( $uri,  $action)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "patch ( $uri,  $action)"
Register a new PATCH route with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$uri\fP 
.br
\fI$action\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "patch ( $uri,  $action)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "post ( $uri,  $action)"
Register a new POST route with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$uri\fP 
.br
\fI$action\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "post ( $uri,  $action)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "put ( $uri,  $action)"
Register a new PUT route with the router\&.
.PP
\fBParameters:\fP
.RS 4
\fI$uri\fP 
.br
\fI$action\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "put ( $uri,  $action)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "resource ( $name,  $controller, array $options = \fCarray()\fP)"
\fBRoute\fP a resource to a controller\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$controller\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.
.SS "resource ( $name,  $controller, array $options = \fCarray()\fP)"

.PP
Implemented in \fBRouter\fP, and \fBRouter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
