.TH "Illuminate\Database\Console\Migrations" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Illuminate\Database\Console\Migrations \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBBaseCommand\fP"
.br
.ti -1c
.RI "class \fBInstallCommand\fP"
.br
.ti -1c
.RI "class \fBMigrateCommand\fP"
.br
.ti -1c
.RI "class \fBMigrateMakeCommand\fP"
.br
.ti -1c
.RI "class \fBRefreshCommand\fP"
.br
.ti -1c
.RI "class \fBResetCommand\fP"
.br
.ti -1c
.RI "class \fBRollbackCommand\fP"
.br
.ti -1c
.RI "class \fBStatusCommand\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
