.TH "ConfigureLogging" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigureLogging \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbootstrap\fP (\fBApplication\fP $app)"
.br
.ti -1c
.RI "\fBbootstrap\fP (\fBApplication\fP $app)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBregisterLogger\fP (\fBApplication\fP $app)"
.br
.ti -1c
.RI "\fBconfigureHandlers\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBconfigureSingleHandler\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBconfigureDailyHandler\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBconfigureSyslogHandler\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBconfigureErrorlogHandler\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBregisterLogger\fP (\fBApplication\fP $app)"
.br
.ti -1c
.RI "\fBconfigureHandlers\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBconfigureSingleHandler\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBconfigureDailyHandler\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBconfigureSyslogHandler\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.ti -1c
.RI "\fBconfigureErrorlogHandler\fP (\fBApplication\fP $app, \fBWriter\fP $\fBlog\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1700 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "bootstrap (\fBApplication\fP $app)"
\fBBootstrap\fP the given application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 15 of file ConfigureLogging\&.php\&.
.SS "bootstrap (\fBApplication\fP $app)"

.PP
Definition at line 1702 of file compiled\&.php\&.
.SS "configureDailyHandler (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"
Configure the \fBMonolog\fP handlers for the application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.br
\fI$log\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 76 of file ConfigureLogging\&.php\&.
.SS "configureDailyHandler (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"

.PP
Definition at line 1723 of file compiled\&.php\&.
.SS "configureErrorlogHandler (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"
Configure the \fBMonolog\fP handlers for the application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.br
\fI$log\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 103 of file ConfigureLogging\&.php\&.
.SS "configureErrorlogHandler (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"

.PP
Definition at line 1731 of file compiled\&.php\&.
.SS "configureHandlers (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"
Configure the \fBMonolog\fP handlers for the application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.br
\fI$log\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 50 of file ConfigureLogging\&.php\&.
.SS "configureHandlers (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"

.PP
Definition at line 1714 of file compiled\&.php\&.
.SS "configureSingleHandler (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"
Configure the \fBMonolog\fP handlers for the application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.br
\fI$log\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 64 of file ConfigureLogging\&.php\&.
.SS "configureSingleHandler (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"

.PP
Definition at line 1719 of file compiled\&.php\&.
.SS "configureSyslogHandler (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"
Configure the \fBMonolog\fP handlers for the application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.br
\fI$log\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 91 of file ConfigureLogging\&.php\&.
.SS "configureSyslogHandler (\fBApplication\fP $app, \fBWriter\fP $log)\fC [protected]\fP"

.PP
Definition at line 1727 of file compiled\&.php\&.
.SS "registerLogger (\fBApplication\fP $app)\fC [protected]\fP"
Register the logger instance in the container\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 34 of file ConfigureLogging\&.php\&.
.SS "registerLogger (\fBApplication\fP $app)\fC [protected]\fP"

.PP
Definition at line 1709 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
