.TH "PostgresConnection" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PostgresConnection \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConnection\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetDefaultQueryGrammar\fP ()"
.br
.ti -1c
.RI "\fBgetDefaultSchemaGrammar\fP ()"
.br
.ti -1c
.RI "\fBgetDefaultPostProcessor\fP ()"
.br
.ti -1c
.RI "\fBgetDoctrineDriver\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file PostgresConnection\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDefaultPostProcessor ()\fC [protected]\fP"
Get the default post processor instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 35 of file PostgresConnection\&.php\&.
.SS "getDefaultQueryGrammar ()\fC [protected]\fP"
Get the default query grammar instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 15 of file PostgresConnection\&.php\&.
.SS "getDefaultSchemaGrammar ()\fC [protected]\fP"
Get the default schema grammar instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 25 of file PostgresConnection\&.php\&.
.SS "getDoctrineDriver ()\fC [protected]\fP"
Get the \fBDoctrine\fP DBAL driver\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 45 of file PostgresConnection\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
