.TH "MorphPivot" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MorphPivot \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPivot\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdelete\fP ()"
.br
.ti -1c
.RI "\fBsetMorphType\fP ($morphType)"
.br
.ti -1c
.RI "\fBsetMorphClass\fP ($morphClass)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetKeysForSaveQuery\fP (\fBBuilder\fP $\fBquery\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$morphType\fP"
.br
.ti -1c
.RI "\fB$morphClass\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file MorphPivot\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "delete ()"
Delete the pivot model record from the database\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 43 of file MorphPivot\&.php\&.
.SS "setKeysForSaveQuery (\fBBuilder\fP $query)\fC [protected]\fP"
Set the keys for a save update query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 31 of file MorphPivot\&.php\&.
.SS "setMorphClass ( $morphClass)"
Set the morph class for the pivot\&.
.PP
\fBParameters:\fP
.RS 4
\fI$morphClass\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 71 of file MorphPivot\&.php\&.
.SS "setMorphType ( $morphType)"
Set the morph type for the pivot\&.
.PP
\fBParameters:\fP
.RS 4
\fI$morphType\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 58 of file MorphPivot\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$morphClass\fC [protected]\fP"

.PP
Definition at line 23 of file MorphPivot\&.php\&.
.SS "$morphType\fC [protected]\fP"

.PP
Definition at line 14 of file MorphPivot\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
