.TH "ForgetFailedCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ForgetFailedCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetArguments\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'queue:forget'"
.br
.ti -1c
.RI "\fB$description\fP = 'Delete \fBa\fP failed \fBqueue\fP job'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ForgetFailedCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 27 of file ForgetFailedCommand\&.php\&.
.SS "getArguments ()\fC [protected]\fP"
Get the console command arguments\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 44 of file ForgetFailedCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$description = 'Delete \fBa\fP failed \fBqueue\fP job'\fC [protected]\fP"

.PP
Definition at line 20 of file ForgetFailedCommand\&.php\&.
.SS "$\fBname\fP = 'queue:forget'\fC [protected]\fP"

.PP
Definition at line 13 of file ForgetFailedCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
