.TH "RouteCacheCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RouteCacheCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBFilesystem\fP $files)"
.br
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetFreshApplicationRoutes\fP ()"
.br
.ti -1c
.RI "\fBbuildRouteCacheFile\fP (\fBRouteCollection\fP $routes)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'route:cache'"
.br
.ti -1c
.RI "\fB$description\fP = 'Create \fBa\fP route cache file \fBfor\fP faster route registration'"
.br
.ti -1c
.RI "\fB$files\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file RouteCacheCommand\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBFilesystem\fP $files)"
Create a new route command instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$files\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 36 of file RouteCacheCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "buildRouteCacheFile (\fBRouteCollection\fP $routes)\fC [protected]\fP"
Build the route cache file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$routes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 91 of file RouteCacheCommand\&.php\&.
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 48 of file RouteCacheCommand\&.php\&.
.SS "getFreshApplicationRoutes ()\fC [protected]\fP"
Boot a fresh copy of the application and get the routes\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 76 of file RouteCacheCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$description = 'Create \fBa\fP route cache file \fBfor\fP faster route registration'\fC [protected]\fP"

.PP
Definition at line 21 of file RouteCacheCommand\&.php\&.
.SS "$files\fC [protected]\fP"

.PP
Definition at line 28 of file RouteCacheCommand\&.php\&.
.SS "$\fBname\fP = 'route:cache'\fC [protected]\fP"

.PP
Definition at line 14 of file RouteCacheCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
