.TH "SeedServiceProvider" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SeedServiceProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBServiceProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBprovides\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBregisterSeedCommand\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$defer\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file SeedServiceProvider\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provides ()"
Get the services provided by the provider\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 50 of file SeedServiceProvider\&.php\&.
.SS "register ()"
Register the service provider\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 20 of file SeedServiceProvider\&.php\&.
.SS "registerSeedCommand ()\fC [protected]\fP"
Register the seed console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 37 of file SeedServiceProvider\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$defer = true\fC [protected]\fP"

.PP
Definition at line 13 of file SeedServiceProvider\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
