.TH "EloquentModelPresenter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EloquentModelPresenter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectPresenter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcanPresent\fP ($value)"
.br
.ti -1c
.RI "\fBgetProperties\fP ($value, ReflectionClass $class, $propertyFilter)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBshowHidden\fP ($propertyFilter)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file EloquentModelPresenter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "canPresent ( $value)"
Determine if the presenter can present the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBPresenter\fP\&.
.PP
Definition at line 16 of file EloquentModelPresenter\&.php\&.
.SS "getProperties ( $value, ReflectionClass $class,  $propertyFilter)"
Get an array of Model object properties\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$class\fP 
.br
\fI$propertyFilter\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 29 of file EloquentModelPresenter\&.php\&.
.SS "showHidden ( $propertyFilter)\fC [protected]\fP"
Decide whether to show hidden properties, based on a ReflectionProperty filter\&.
.PP
\fBParameters:\fP
.RS 4
\fI$propertyFilter\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 66 of file EloquentModelPresenter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
