.TH "ValidatesWhenResolved" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValidatesWhenResolved \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFormRequest\fP, and \fBFormRequest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvalidate\fP ()"
.br
.ti -1c
.RI "\fBvalidate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 238 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "validate ()"
Validate the given class instance\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.SS "validate ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
