.TH "IronConnector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IronConnector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConnectorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (EncrypterContract $crypt, \fBRequest\fP $request)"
.br
.ti -1c
.RI "\fBconnect\fP (array $config)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$crypt\fP"
.br
.ti -1c
.RI "\fB$request\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file IronConnector\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (EncrypterContract $crypt, \fBRequest\fP $request)"
Create a new Iron connector instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$crypt\fP 
.br
\fI$request\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 31 of file IronConnector\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "connect (array $config)"
Establish a queue connection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBConnectorInterface\fP\&.
.PP
Definition at line 43 of file IronConnector\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$crypt\fC [protected]\fP"

.PP
Definition at line 15 of file IronConnector\&.php\&.
.SS "$request\fC [protected]\fP"

.PP
Definition at line 22 of file IronConnector\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
