.TH "DownCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DownCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'down'"
.br
.ti -1c
.RI "\fB$description\fP = 'Put the application into maintenance mode'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file DownCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 26 of file DownCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$description = 'Put the application into maintenance mode'\fC [protected]\fP"

.PP
Definition at line 19 of file DownCommand\&.php\&.
.SS "$\fBname\fP = 'down'\fC [protected]\fP"

.PP
Definition at line 12 of file DownCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
