.TH "DatabaseMigrationRepository" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseMigrationRepository \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMigrationRepositoryInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (Resolver $resolver, $\fBtable\fP)"
.br
.ti -1c
.RI "\fBgetRan\fP ()"
.br
.ti -1c
.RI "\fBgetLast\fP ()"
.br
.ti -1c
.RI "\fBlog\fP ($file, $batch)"
.br
.ti -1c
.RI "\fBdelete\fP ($migration)"
.br
.ti -1c
.RI "\fBgetNextBatchNumber\fP ()"
.br
.ti -1c
.RI "\fBgetLastBatchNumber\fP ()"
.br
.ti -1c
.RI "\fBcreateRepository\fP ()"
.br
.ti -1c
.RI "\fBrepositoryExists\fP ()"
.br
.ti -1c
.RI "\fBgetConnectionResolver\fP ()"
.br
.ti -1c
.RI "\fBgetConnection\fP ()"
.br
.ti -1c
.RI "\fBsetSource\fP ($\fBname\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBtable\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$resolver\fP"
.br
.ti -1c
.RI "\fB$table\fP"
.br
.ti -1c
.RI "\fB$connection\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file DatabaseMigrationRepository\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (Resolver $resolver,  $table)"
Create a new database migration repository instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$resolver\fP 
.br
\fI$table\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 35 of file DatabaseMigrationRepository\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createRepository ()"
Create the migration repository data store\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBMigrationRepositoryInterface\fP\&.
.PP
Definition at line 113 of file DatabaseMigrationRepository\&.php\&.
.SS "delete ( $migration)"
Remove a migration from the log\&.
.PP
\fBParameters:\fP
.RS 4
\fI$migration\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBMigrationRepositoryInterface\fP\&.
.PP
Definition at line 83 of file DatabaseMigrationRepository\&.php\&.
.SS "getConnection ()"
Resolve the database connection instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 165 of file DatabaseMigrationRepository\&.php\&.
.SS "getConnectionResolver ()"
Get the connection resolver instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 155 of file DatabaseMigrationRepository\&.php\&.
.SS "getLast ()"
Get the last migration batch\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implements \fBMigrationRepositoryInterface\fP\&.
.PP
Definition at line 56 of file DatabaseMigrationRepository\&.php\&.
.SS "getLastBatchNumber ()"
Get the last migration batch number\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 103 of file DatabaseMigrationRepository\&.php\&.
.SS "getNextBatchNumber ()"
Get the next migration batch number\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBMigrationRepositoryInterface\fP\&.
.PP
Definition at line 93 of file DatabaseMigrationRepository\&.php\&.
.SS "getRan ()"
Get the ran migrations\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implements \fBMigrationRepositoryInterface\fP\&.
.PP
Definition at line 46 of file DatabaseMigrationRepository\&.php\&.
.SS "log ( $file,  $batch)"
\fBLog\fP that a migration was run\&.
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP 
.br
\fI$batch\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBMigrationRepositoryInterface\fP\&.
.PP
Definition at line 70 of file DatabaseMigrationRepository\&.php\&.
.SS "repositoryExists ()"
Determine if the migration repository exists\&.
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBMigrationRepositoryInterface\fP\&.
.PP
Definition at line 133 of file DatabaseMigrationRepository\&.php\&.
.SS "setSource ( $name)"
Set the information source to gather data\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBMigrationRepositoryInterface\fP\&.
.PP
Definition at line 176 of file DatabaseMigrationRepository\&.php\&.
.SS "table ()\fC [protected]\fP"
Get a query builder for the migration table\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 145 of file DatabaseMigrationRepository\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$connection\fC [protected]\fP"

.PP
Definition at line 26 of file DatabaseMigrationRepository\&.php\&.
.SS "$resolver\fC [protected]\fP"

.PP
Definition at line 12 of file DatabaseMigrationRepository\&.php\&.
.SS "$\fBtable\fP\fC [protected]\fP"

.PP
Definition at line 19 of file DatabaseMigrationRepository\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
