.TH "Illuminate\Auth" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Illuminate\Auth \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBConsole\fP"
.br
.ti -1c
.RI " \fBMiddleware\fP"
.br
.ti -1c
.RI " \fBPasswords\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAuthManager\fP"
.br
.ti -1c
.RI "class \fBAuthServiceProvider\fP"
.br
.ti -1c
.RI "class \fBDatabaseUserProvider\fP"
.br
.ti -1c
.RI "class \fBEloquentUserProvider\fP"
.br
.ti -1c
.RI "class \fBGeneratorServiceProvider\fP"
.br
.ti -1c
.RI "class \fBGenericUser\fP"
.br
.ti -1c
.RI "class \fBGuard\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
