.TH "ConnectionResolverInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConnectionResolverInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBConnectionResolver\fP, \fBDatabaseManager\fP, and \fBDatabaseManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnection\fP ($\fBname\fP=null)"
.br
.ti -1c
.RI "\fBgetDefaultConnection\fP ()"
.br
.ti -1c
.RI "\fBsetDefaultConnection\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBconnection\fP ($\fBname\fP=null)"
.br
.ti -1c
.RI "\fBgetDefaultConnection\fP ()"
.br
.ti -1c
.RI "\fBsetDefaultConnection\fP ($\fBname\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10729 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "connection ( $name = \fCnull\fP)"
Get a database connection instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBDatabaseManager\fP, \fBDatabaseManager\fP, and \fBConnectionResolver\fP\&.
.SS "connection ( $name = \fCnull\fP)"

.PP
Implemented in \fBDatabaseManager\fP, \fBDatabaseManager\fP, and \fBConnectionResolver\fP\&.
.SS "getDefaultConnection ()"
Get the default connection name\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBDatabaseManager\fP, \fBDatabaseManager\fP, and \fBConnectionResolver\fP\&.
.SS "getDefaultConnection ()"

.PP
Implemented in \fBDatabaseManager\fP, \fBDatabaseManager\fP, and \fBConnectionResolver\fP\&.
.SS "setDefaultConnection ( $name)"
Set the default connection name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBDatabaseManager\fP, \fBDatabaseManager\fP, and \fBConnectionResolver\fP\&.
.SS "setDefaultConnection ( $name)"

.PP
Implemented in \fBDatabaseManager\fP, \fBDatabaseManager\fP, and \fBConnectionResolver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
