.TH "FrameGuard" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FrameGuard \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMiddleware\fP, and \fBMiddleware\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhandle\fP ($request, Closure $next)"
.br
.ti -1c
.RI "\fBhandle\fP ($request, Closure $next)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2457 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "handle ( $request, Closure $next)"
Handle the given request and get the response\&.
.PP
\fBParameters:\fP
.RS 4
\fI$request\fP 
.br
\fI$next\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBMiddleware\fP\&.
.PP
Definition at line 15 of file FrameGuard\&.php\&.
.SS "handle ( $request, Closure $next)"

.PP
Implements \fBMiddleware\fP\&.
.PP
Definition at line 2459 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
