.TH "GenericUser" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericUser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAuthenticatable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $attributes)"
.br
.ti -1c
.RI "\fBgetAuthIdentifier\fP ()"
.br
.ti -1c
.RI "\fBgetAuthPassword\fP ()"
.br
.ti -1c
.RI "\fBgetRememberToken\fP ()"
.br
.ti -1c
.RI "\fBsetRememberToken\fP ($value)"
.br
.ti -1c
.RI "\fBgetRememberTokenName\fP ()"
.br
.ti -1c
.RI "\fB__get\fP ($key)"
.br
.ti -1c
.RI "\fB__set\fP ($key, $value)"
.br
.ti -1c
.RI "\fB__isset\fP ($key)"
.br
.ti -1c
.RI "\fB__unset\fP ($key)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$attributes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file GenericUser\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $attributes)"
Create a new generic User object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$attributes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 20 of file GenericUser\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__get ( $key)"
Dynamically access the user's attributes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 82 of file GenericUser\&.php\&.
.SS "__isset ( $key)"
Dynamically check if a value is set on the user\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 105 of file GenericUser\&.php\&.
.SS "__set ( $key,  $value)"
Dynamically set an attribute on the user\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 94 of file GenericUser\&.php\&.
.SS "__unset ( $key)"
Dynamically unset a value on the user\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 116 of file GenericUser\&.php\&.
.SS "getAuthIdentifier ()"
Get the unique identifier for the user\&.
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBAuthenticatable\fP\&.
.PP
Definition at line 30 of file GenericUser\&.php\&.
.SS "getAuthPassword ()"
Get the password for the user\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBAuthenticatable\fP\&.
.PP
Definition at line 40 of file GenericUser\&.php\&.
.SS "getRememberToken ()"
Get the token value for the 'remember me' session\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBAuthenticatable\fP\&.
.PP
Definition at line 50 of file GenericUser\&.php\&.
.SS "getRememberTokenName ()"
Get the column name for the 'remember me' token\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBAuthenticatable\fP\&.
.PP
Definition at line 71 of file GenericUser\&.php\&.
.SS "setRememberToken ( $value)"
Set the token value for the 'remember me' session\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBAuthenticatable\fP\&.
.PP
Definition at line 61 of file GenericUser\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$attributes\fC [protected]\fP"

.PP
Definition at line 12 of file GenericUser\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
