.TH "KeyGenerateCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KeyGenerateCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetRandomKey\fP ()"
.br
.ti -1c
.RI "\fBgetOptions\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'key:generate'"
.br
.ti -1c
.RI "\fB$description\fP = 'Set the application key'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file KeyGenerateCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 28 of file KeyGenerateCommand\&.php\&.
.SS "getOptions ()\fC [protected]\fP"
Get the console command options\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 66 of file KeyGenerateCommand\&.php\&.
.SS "getRandomKey ()\fC [protected]\fP"
Generate a random key for the application\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 56 of file KeyGenerateCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$description = 'Set the application key'\fC [protected]\fP"

.PP
Definition at line 21 of file KeyGenerateCommand\&.php\&.
.SS "$\fBname\fP = 'key:generate'\fC [protected]\fP"

.PP
Definition at line 14 of file KeyGenerateCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
