.TH "QueueServiceProvider" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QueueServiceProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBServiceProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBregisterRestartCommand\fP ()"
.br
.ti -1c
.RI "\fBregisterConnectors\fP ($manager)"
.br
.ti -1c
.RI "\fBprovides\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBregisterManager\fP ()"
.br
.ti -1c
.RI "\fBregisterWorker\fP ()"
.br
.ti -1c
.RI "\fBregisterWorkCommand\fP ()"
.br
.ti -1c
.RI "\fBregisterListener\fP ()"
.br
.ti -1c
.RI "\fBregisterListenCommand\fP ()"
.br
.ti -1c
.RI "\fBregisterSubscriber\fP ()"
.br
.ti -1c
.RI "\fBregisterNullConnector\fP ($manager)"
.br
.ti -1c
.RI "\fBregisterSyncConnector\fP ($manager)"
.br
.ti -1c
.RI "\fBregisterBeanstalkdConnector\fP ($manager)"
.br
.ti -1c
.RI "\fBregisterDatabaseConnector\fP ($manager)"
.br
.ti -1c
.RI "\fBregisterRedisConnector\fP ($manager)"
.br
.ti -1c
.RI "\fBregisterSqsConnector\fP ($manager)"
.br
.ti -1c
.RI "\fBregisterIronConnector\fP ($manager)"
.br
.ti -1c
.RI "\fBregisterIronRequestBinder\fP ()"
.br
.ti -1c
.RI "\fBregisterFailedJobServices\fP ()"
.br
.ti -1c
.RI "\fBregisterQueueClosure\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$defer\fP = true"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file QueueServiceProvider\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provides ()"
Get the services provided by the provider\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 331 of file QueueServiceProvider\&.php\&.
.SS "register ()"
Register the service provider\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 32 of file QueueServiceProvider\&.php\&.
.SS "registerBeanstalkdConnector ( $manager)\fC [protected]\fP"
Register the Beanstalkd queue connector\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 212 of file QueueServiceProvider\&.php\&.
.SS "registerConnectors ( $manager)"
Register the connectors on the queue manager\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 170 of file QueueServiceProvider\&.php\&.
.SS "registerDatabaseConnector ( $manager)\fC [protected]\fP"
Register the database queue connector\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 226 of file QueueServiceProvider\&.php\&.
.SS "registerFailedJobServices ()\fC [protected]\fP"
Register the failed job services\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 303 of file QueueServiceProvider\&.php\&.
.SS "registerIronConnector ( $manager)\fC [protected]\fP"
Register the IronMQ queue connector\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 270 of file QueueServiceProvider\&.php\&.
.SS "registerIronRequestBinder ()\fC [protected]\fP"
Register the request rebinding event for the Iron queue\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 287 of file QueueServiceProvider\&.php\&.
.SS "registerListenCommand ()\fC [protected]\fP"
Register the queue listener console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 124 of file QueueServiceProvider\&.php\&.
.SS "registerListener ()\fC [protected]\fP"
Register the queue listener\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 109 of file QueueServiceProvider\&.php\&.
.SS "registerManager ()\fC [protected]\fP"
Register the queue manager\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 52 of file QueueServiceProvider\&.php\&.
.SS "registerNullConnector ( $manager)\fC [protected]\fP"
Register the Null queue connector\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 184 of file QueueServiceProvider\&.php\&.
.SS "registerQueueClosure ()\fC [protected]\fP"
Register the \fBIlluminate\fP queued closure job\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 318 of file QueueServiceProvider\&.php\&.
.SS "registerRedisConnector ( $manager)\fC [protected]\fP"
Register the \fBRedis\fP queue connector\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 240 of file QueueServiceProvider\&.php\&.
.SS "registerRestartCommand ()"
Register the queue restart console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 139 of file QueueServiceProvider\&.php\&.
.SS "registerSqsConnector ( $manager)\fC [protected]\fP"
Register the Amazon SQS queue connector\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 256 of file QueueServiceProvider\&.php\&.
.SS "registerSubscriber ()\fC [protected]\fP"
Register the push queue subscribe command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 154 of file QueueServiceProvider\&.php\&.
.SS "registerSyncConnector ( $manager)\fC [protected]\fP"
Register the Sync queue connector\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 198 of file QueueServiceProvider\&.php\&.
.SS "registerWorkCommand ()\fC [protected]\fP"
Register the queue worker console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 94 of file QueueServiceProvider\&.php\&.
.SS "registerWorker ()\fC [protected]\fP"
Register the queue worker\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 77 of file QueueServiceProvider\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$defer = true\fC [protected]\fP"

.PP
Definition at line 25 of file QueueServiceProvider\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
