.TH "UrlGenerator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UrlGenerator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBto\fP ($\fBpath\fP, $extra=array(), $\fBsecure\fP=null)"
.br
.ti -1c
.RI "\fBsecure\fP ($\fBpath\fP, $parameters=array())"
.br
.ti -1c
.RI "\fBasset\fP ($\fBpath\fP, $\fBsecure\fP=null)"
.br
.ti -1c
.RI "\fBroute\fP ($\fBname\fP, $parameters=array(), $absolute=true)"
.br
.ti -1c
.RI "\fBaction\fP ($action, $parameters=array(), $absolute=true)"
.br
.ti -1c
.RI "\fBsetRootControllerNamespace\fP ($rootNamespace)"
.br
.ti -1c
.RI "\fBto\fP ($\fBpath\fP, $extra=array(), $\fBsecure\fP=null)"
.br
.ti -1c
.RI "\fBsecure\fP ($\fBpath\fP, $parameters=array())"
.br
.ti -1c
.RI "\fBasset\fP ($\fBpath\fP, $\fBsecure\fP=null)"
.br
.ti -1c
.RI "\fBroute\fP ($\fBname\fP, $parameters=array(), $absolute=true)"
.br
.ti -1c
.RI "\fBaction\fP ($action, $parameters=array(), $absolute=true)"
.br
.ti -1c
.RI "\fBsetRootControllerNamespace\fP ($rootNamespace)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 207 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "action ( $action,  $parameters = \fCarray()\fP,  $absolute = \fCtrue\fP)"
Get the \fBURL\fP to a controller action\&.
.PP
\fBParameters:\fP
.RS 4
\fI$action\fP 
.br
\fI$parameters\fP 
.br
\fI$absolute\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "action ( $action,  $parameters = \fCarray()\fP,  $absolute = \fCtrue\fP)"

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "asset ( $path,  $secure = \fCnull\fP)"
Generate a \fBURL\fP to an application asset\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$secure\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "asset ( $path,  $secure = \fCnull\fP)"

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "route ( $name,  $parameters = \fCarray()\fP,  $absolute = \fCtrue\fP)"
Get the \fBURL\fP to a named route\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$parameters\fP 
.br
\fI$absolute\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "route ( $name,  $parameters = \fCarray()\fP,  $absolute = \fCtrue\fP)"

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "secure ( $path,  $parameters = \fCarray()\fP)"
Generate a secure, absolute \fBURL\fP to the given path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$parameters\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "secure ( $path,  $parameters = \fCarray()\fP)"

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "setRootControllerNamespace ( $rootNamespace)"
Set the root controller namespace\&.
.PP
\fBParameters:\fP
.RS 4
\fI$rootNamespace\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "setRootControllerNamespace ( $rootNamespace)"

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "to ( $path,  $extra = \fCarray()\fP,  $secure = \fCnull\fP)"
Generate a absolute \fBURL\fP to the given path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$extra\fP 
.br
\fI$secure\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.
.SS "to ( $path,  $extra = \fCarray()\fP,  $secure = \fCnull\fP)"

.PP
Implemented in \fBUrlGenerator\fP, and \fBUrlGenerator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
