.TH "Illuminate\Foundation\Validation" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Illuminate\Foundation\Validation \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFormRequest\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBValidatesRequests\fP"
.br
.ti -1c
.RI "trait \fBValidatesWhenResolvedTrait\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "trait ValidatesRequests"

.PP
Definition at line 4618 of file compiled\&.php\&.
.SS "trait ValidatesWhenResolvedTrait"

.PP
Definition at line 4659 of file compiled\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
