.TH "View" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
View \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAccess, \fBView\fP, ArrayAccess, and \fBView\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBFactory\fP $\fBfactory\fP, \fBEngineInterface\fP $engine, $view, $\fBpath\fP, $\fBdata\fP=array())"
.br
.ti -1c
.RI "\fBrender\fP (Closure $\fBcallback\fP=null)"
.br
.ti -1c
.RI "\fBrenderSections\fP ()"
.br
.ti -1c
.RI "\fBwith\fP ($key, $value=null)"
.br
.ti -1c
.RI "\fBnest\fP ($key, $view, array $\fBdata\fP=array())"
.br
.ti -1c
.RI "\fBwithErrors\fP ($provider)"
.br
.ti -1c
.RI "\fBgetFactory\fP ()"
.br
.ti -1c
.RI "\fBgetEngine\fP ()"
.br
.ti -1c
.RI "\fBname\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetData\fP ()"
.br
.ti -1c
.RI "\fBgetPath\fP ()"
.br
.ti -1c
.RI "\fBsetPath\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBoffsetExists\fP ($key)"
.br
.ti -1c
.RI "\fBoffsetGet\fP ($key)"
.br
.ti -1c
.RI "\fBoffsetSet\fP ($key, $value)"
.br
.ti -1c
.RI "\fBoffsetUnset\fP ($key)"
.br
.ti -1c
.RI "& \fB__get\fP ($key)"
.br
.ti -1c
.RI "\fB__set\fP ($key, $value)"
.br
.ti -1c
.RI "\fB__isset\fP ($key)"
.br
.ti -1c
.RI "\fB__unset\fP ($key)"
.br
.ti -1c
.RI "\fB__call\fP ($method, $parameters)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP (\fBFactory\fP $\fBfactory\fP, \fBEngineInterface\fP $engine, $view, $\fBpath\fP, $\fBdata\fP=array())"
.br
.ti -1c
.RI "\fBrender\fP (Closure $\fBcallback\fP=null)"
.br
.ti -1c
.RI "\fBrenderSections\fP ()"
.br
.ti -1c
.RI "\fBwith\fP ($key, $value=null)"
.br
.ti -1c
.RI "\fBnest\fP ($key, $view, array $\fBdata\fP=array())"
.br
.ti -1c
.RI "\fBwithErrors\fP ($provider)"
.br
.ti -1c
.RI "\fBgetFactory\fP ()"
.br
.ti -1c
.RI "\fBgetEngine\fP ()"
.br
.ti -1c
.RI "\fBname\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetData\fP ()"
.br
.ti -1c
.RI "\fBgetPath\fP ()"
.br
.ti -1c
.RI "\fBsetPath\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBoffsetExists\fP ($key)"
.br
.ti -1c
.RI "\fBoffsetGet\fP ($key)"
.br
.ti -1c
.RI "\fBoffsetSet\fP ($key, $value)"
.br
.ti -1c
.RI "\fBoffsetUnset\fP ($key)"
.br
.ti -1c
.RI "& \fB__get\fP ($key)"
.br
.ti -1c
.RI "\fB__set\fP ($key, $value)"
.br
.ti -1c
.RI "\fB__isset\fP ($key)"
.br
.ti -1c
.RI "\fB__unset\fP ($key)"
.br
.ti -1c
.RI "\fB__call\fP ($method, $parameters)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBrenderContents\fP ()"
.br
.ti -1c
.RI "\fBgetContents\fP ()"
.br
.ti -1c
.RI "\fBgatherData\fP ()"
.br
.ti -1c
.RI "\fBrenderContents\fP ()"
.br
.ti -1c
.RI "\fBgetContents\fP ()"
.br
.ti -1c
.RI "\fBgatherData\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$factory\fP"
.br
.ti -1c
.RI "\fB$engine\fP"
.br
.ti -1c
.RI "\fB$view\fP"
.br
.ti -1c
.RI "\fB$data\fP"
.br
.ti -1c
.RI "\fB$path\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 13572 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBFactory\fP $factory, \fBEngineInterface\fP $engine,  $view,  $path,  $data = \fCarray()\fP)"

.PP
Definition at line 13579 of file compiled\&.php\&.
.SS "__construct (\fBFactory\fP $factory, \fBEngineInterface\fP $engine,  $view,  $path,  $data = \fCarray()\fP)"
Create a new view instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$factory\fP 
.br
\fI$engine\fP 
.br
\fI$view\fP 
.br
\fI$path\fP 
.br
\fI$data\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 60 of file View\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__call ( $method,  $parameters)"
Dynamically bind parameters to the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$parameters\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 383 of file View\&.php\&.
.SS "__call ( $method,  $parameters)"

.PP
Definition at line 13705 of file compiled\&.php\&.
.SS "& __get ( $key)"
Get a piece of data from the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 335 of file View\&.php\&.
.SS "& __get ( $key)"

.PP
Definition at line 13689 of file compiled\&.php\&.
.SS "__isset ( $key)"
Check if a piece of data is bound to the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 358 of file View\&.php\&.
.SS "__isset ( $key)"

.PP
Definition at line 13697 of file compiled\&.php\&.
.SS "__set ( $key,  $value)"
Set a piece of data on the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 347 of file View\&.php\&.
.SS "__set ( $key,  $value)"

.PP
Definition at line 13693 of file compiled\&.php\&.
.SS "__toString ()"
Get the string contents of the view\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 398 of file View\&.php\&.
.SS "__toString ()"

.PP
Definition at line 13712 of file compiled\&.php\&.
.SS "__unset ( $key)"
Remove a piece of bound data from the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 369 of file View\&.php\&.
.SS "__unset ( $key)"

.PP
Definition at line 13701 of file compiled\&.php\&.
.SS "gatherData ()\fC [protected]\fP"
Get the data bound to the view instance\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 144 of file View\&.php\&.
.SS "gatherData ()\fC [protected]\fP"

.PP
Definition at line 13613 of file compiled\&.php\&.
.SS "getContents ()\fC [protected]\fP"
Get the evaluated contents of the view\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 134 of file View\&.php\&.
.SS "getContents ()\fC [protected]\fP"

.PP
Definition at line 13609 of file compiled\&.php\&.
.SS "getData ()"
Get the array of view data\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 258 of file View\&.php\&.
.SS "getData ()"

.PP
Definition at line 13661 of file compiled\&.php\&.
.SS "getEngine ()"
Get the view's rendering engine\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 228 of file View\&.php\&.
.SS "getEngine ()"

.PP
Definition at line 13649 of file compiled\&.php\&.
.SS "getFactory ()"
Get the view factory instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 218 of file View\&.php\&.
.SS "getFactory ()"

.PP
Definition at line 13645 of file compiled\&.php\&.
.SS "getName ()"
Get the name of the view\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 248 of file View\&.php\&.
.SS "getName ()"

.PP
Definition at line 13657 of file compiled\&.php\&.
.SS "getPath ()"
Get the path to the view file\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 268 of file View\&.php\&.
.SS "getPath ()"

.PP
Definition at line 13665 of file compiled\&.php\&.
.SS "name ()"
Get the name of the view\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBView\fP\&.
.PP
Definition at line 238 of file View\&.php\&.
.SS "name ()"

.PP
Implements \fBView\fP\&.
.PP
Definition at line 13653 of file compiled\&.php\&.
.SS "nest ( $key,  $view, array $data = \fCarray()\fP)"
Add a view instance to the view data\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$view\fP 
.br
\fI$data\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 188 of file View\&.php\&.
.SS "nest ( $key,  $view, array $data = \fCarray()\fP)"

.PP
Definition at line 13632 of file compiled\&.php\&.
.SS "offsetExists ( $key)"
Determine if a piece of data is bound\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 290 of file View\&.php\&.
.SS "offsetExists ( $key)"

.PP
Definition at line 13673 of file compiled\&.php\&.
.SS "offsetGet ( $key)"
Get a piece of bound data to the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 301 of file View\&.php\&.
.SS "offsetGet ( $key)"

.PP
Definition at line 13677 of file compiled\&.php\&.
.SS "offsetSet ( $key,  $value)"
Set a piece of data on the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 313 of file View\&.php\&.
.SS "offsetSet ( $key,  $value)"

.PP
Definition at line 13681 of file compiled\&.php\&.
.SS "offsetUnset ( $key)"
Unset a piece of data from the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 324 of file View\&.php\&.
.SS "offsetUnset ( $key)"

.PP
Definition at line 13685 of file compiled\&.php\&.
.SS "render (Closure $callback = \fCnull\fP)"
Get the string contents of the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 76 of file View\&.php\&.
.SS "render (Closure $callback = \fCnull\fP)"

.PP
Definition at line 13587 of file compiled\&.php\&.
.SS "renderContents ()\fC [protected]\fP"
Get the contents of the view instance\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 95 of file View\&.php\&.
.SS "renderContents ()\fC [protected]\fP"

.PP
Definition at line 13594 of file compiled\&.php\&.
.SS "renderSections ()"
Get the sections of the rendered view\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 119 of file View\&.php\&.
.SS "renderSections ()"

.PP
Definition at line 13602 of file compiled\&.php\&.
.SS "setPath ( $path)"
Set the path to the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 279 of file View\&.php\&.
.SS "setPath ( $path)"

.PP
Definition at line 13669 of file compiled\&.php\&.
.SS "with ( $key,  $value = \fCnull\fP)"
Add a piece of data to the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Implements \fBView\fP\&.
.PP
Definition at line 166 of file View\&.php\&.
.SS "with ( $key,  $value = \fCnull\fP)"

.PP
Implements \fBView\fP\&.
.PP
Definition at line 13623 of file compiled\&.php\&.
.SS "withErrors ( $provider)"
Add validation errors to the view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$provider\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 199 of file View\&.php\&.
.SS "withErrors ( $provider)"

.PP
Definition at line 13636 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBdata\fP\fC [protected]\fP"

.PP
Definition at line 13577 of file compiled\&.php\&.
.SS "$engine\fC [protected]\fP"

.PP
Definition at line 13575 of file compiled\&.php\&.
.SS "$\fBfactory\fP\fC [protected]\fP"

.PP
Definition at line 13574 of file compiled\&.php\&.
.SS "$\fBpath\fP\fC [protected]\fP"

.PP
Definition at line 13578 of file compiled\&.php\&.
.SS "$view\fC [protected]\fP"

.PP
Definition at line 13576 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
