.TH "RestartCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RestartCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'queue:restart'"
.br
.ti -1c
.RI "\fB$description\fP = 'Restart \fBqueue\fP worker daemons after their current job'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file RestartCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 26 of file RestartCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$description = 'Restart \fBqueue\fP worker daemons after their current job'\fC [protected]\fP"

.PP
Definition at line 19 of file RestartCommand\&.php\&.
.SS "$\fBname\fP = 'queue:restart'\fC [protected]\fP"

.PP
Definition at line 12 of file RestartCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
