.TH "ContextualBindingBuilder" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextualBindingBuilder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBContextualBindingBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBneeds\fP ($abstract)"
.br
.ti -1c
.RI "\fBgive\fP ($implementation)"
.br
.ti -1c
.RI "\fBneeds\fP ($abstract)"
.br
.ti -1c
.RI "\fBgive\fP ($implementation)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "give ( $implementation)"
Define the implementation for the contextual binding\&.
.PP
\fBParameters:\fP
.RS 4
\fI$implementation\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBContextualBindingBuilder\fP\&.
.SS "give ( $implementation)"

.PP
Implemented in \fBContextualBindingBuilder\fP\&.
.SS "needs ( $abstract)"
Define the abstract target that depends on the context\&.
.PP
\fBParameters:\fP
.RS 4
\fI$abstract\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Implemented in \fBContextualBindingBuilder\fP\&.
.SS "needs ( $abstract)"

.PP
Implemented in \fBContextualBindingBuilder\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
