.TH "Repository" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Repository \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAccess, \fBRepository\fP, ArrayAccess, and \fBRepository\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $items=array())"
.br
.ti -1c
.RI "\fBhas\fP ($key)"
.br
.ti -1c
.RI "\fBget\fP ($key, $default=null)"
.br
.ti -1c
.RI "\fBset\fP ($key, $value=null)"
.br
.ti -1c
.RI "\fBprepend\fP ($key, $value)"
.br
.ti -1c
.RI "\fBpush\fP ($key, $value)"
.br
.ti -1c
.RI "\fBall\fP ()"
.br
.ti -1c
.RI "\fBoffsetExists\fP ($key)"
.br
.ti -1c
.RI "\fBoffsetGet\fP ($key)"
.br
.ti -1c
.RI "\fBoffsetSet\fP ($key, $value)"
.br
.ti -1c
.RI "\fBoffsetUnset\fP ($key)"
.br
.ti -1c
.RI "\fB__construct\fP (array $items=array())"
.br
.ti -1c
.RI "\fBhas\fP ($key)"
.br
.ti -1c
.RI "\fBget\fP ($key, $default=null)"
.br
.ti -1c
.RI "\fBset\fP ($key, $value=null)"
.br
.ti -1c
.RI "\fBprepend\fP ($key, $value)"
.br
.ti -1c
.RI "\fBpush\fP ($key, $value)"
.br
.ti -1c
.RI "\fBall\fP ()"
.br
.ti -1c
.RI "\fBoffsetExists\fP ($key)"
.br
.ti -1c
.RI "\fBoffsetGet\fP ($key)"
.br
.ti -1c
.RI "\fBoffsetSet\fP ($key, $value)"
.br
.ti -1c
.RI "\fBoffsetUnset\fP ($key)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$items\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6126 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $items = \fCarray()\fP)"

.PP
Definition at line 6129 of file compiled\&.php\&.
.SS "__construct (array $items = \fCarray()\fP)"
Create a new configuration repository\&.
.PP
\fBParameters:\fP
.RS 4
\fI$items\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 21 of file Repository\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "all ()"
Get all of the configuration items for the application\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 108 of file Repository\&.php\&.
.SS "all ()"

.PP
Definition at line 6163 of file compiled\&.php\&.
.SS "get ( $key,  $default = \fCnull\fP)"
Get the specified configuration value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$default\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 44 of file Repository\&.php\&.
.SS "get ( $key,  $default = \fCnull\fP)"

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 6137 of file compiled\&.php\&.
.SS "has ( $key)"
Determine if the given configuration value exists\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 32 of file Repository\&.php\&.
.SS "has ( $key)"

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 6133 of file compiled\&.php\&.
.SS "offsetExists ( $key)"
Determine if the given configuration option exists\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 119 of file Repository\&.php\&.
.SS "offsetExists ( $key)"

.PP
Definition at line 6167 of file compiled\&.php\&.
.SS "offsetGet ( $key)"
Get a configuration option\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 130 of file Repository\&.php\&.
.SS "offsetGet ( $key)"

.PP
Definition at line 6171 of file compiled\&.php\&.
.SS "offsetSet ( $key,  $value)"
Set a configuration option\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 142 of file Repository\&.php\&.
.SS "offsetSet ( $key,  $value)"

.PP
Definition at line 6175 of file compiled\&.php\&.
.SS "offsetUnset ( $key)"
Unset a configuration option\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 153 of file Repository\&.php\&.
.SS "offsetUnset ( $key)"

.PP
Definition at line 6179 of file compiled\&.php\&.
.SS "prepend ( $key,  $value)"
Prepend a value onto an array configuration value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 78 of file Repository\&.php\&.
.SS "prepend ( $key,  $value)"

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 6151 of file compiled\&.php\&.
.SS "push ( $key,  $value)"
Push a value onto an array configuration value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 94 of file Repository\&.php\&.
.SS "push ( $key,  $value)"

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 6157 of file compiled\&.php\&.
.SS "set ( $key,  $value = \fCnull\fP)"
Set a given configuration value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 56 of file Repository\&.php\&.
.SS "set ( $key,  $value = \fCnull\fP)"

.PP
Implements \fBRepository\fP\&.
.PP
Definition at line 6141 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$items = array()\fC [protected]\fP"

.PP
Definition at line 6128 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
