.TH "SyncConnector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncConnector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConnectorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnect\fP (array $config)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file SyncConnector\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "connect (array $config)"
Establish a queue connection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBConnectorInterface\fP\&.
.PP
Definition at line 13 of file SyncConnector\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
