.TH "MySqlBuilder" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySqlBuilder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhasTable\fP ($\fBtable\fP)"
.br
.ti -1c
.RI "\fBgetColumnListing\fP ($\fBtable\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file MySqlBuilder\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getColumnListing ( $table)"
Get the column listing for a given table\&.
.PP
\fBParameters:\fP
.RS 4
\fI$table\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 28 of file MySqlBuilder\&.php\&.
.SS "hasTable ( $table)"
Determine if the given table exists\&.
.PP
\fBParameters:\fP
.RS 4
\fI$table\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 11 of file MySqlBuilder\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
