.TH "BcryptHasher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BcryptHasher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHasher\fP, and \fBHasher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmake\fP ($value, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBcheck\fP ($value, $hashedValue, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBneedsRehash\fP ($hashedValue, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBsetRounds\fP ($rounds)"
.br
.ti -1c
.RI "\fBmake\fP ($value, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBcheck\fP ($value, $hashedValue, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBneedsRehash\fP ($hashedValue, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBsetRounds\fP ($rounds)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$rounds\fP = 10"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4985 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "check ( $value,  $hashedValue, array $options = \fCarray()\fP)"
Check the given plain value against a hash\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$hashedValue\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBHasher\fP\&.
.PP
Definition at line 46 of file BcryptHasher\&.php\&.
.SS "check ( $value,  $hashedValue, array $options = \fCarray()\fP)"

.PP
Implements \fBHasher\fP\&.
.PP
Definition at line 4997 of file compiled\&.php\&.
.SS "make ( $value, array $options = \fCarray()\fP)"
\fBHash\fP the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implements \fBHasher\fP\&.
.PP
Definition at line 24 of file BcryptHasher\&.php\&.
.SS "make ( $value, array $options = \fCarray()\fP)"

.PP
Implements \fBHasher\fP\&.
.PP
Definition at line 4988 of file compiled\&.php\&.
.SS "needsRehash ( $hashedValue, array $options = \fCarray()\fP)"
Check if the given hash has been hashed using the given options\&.
.PP
\fBParameters:\fP
.RS 4
\fI$hashedValue\fP 
.br
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBHasher\fP\&.
.PP
Definition at line 58 of file BcryptHasher\&.php\&.
.SS "needsRehash ( $hashedValue, array $options = \fCarray()\fP)"

.PP
Implements \fBHasher\fP\&.
.PP
Definition at line 5001 of file compiled\&.php\&.
.SS "setRounds ( $rounds)"
Set the default password work factor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$rounds\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 71 of file BcryptHasher\&.php\&.
.SS "setRounds ( $rounds)"

.PP
Definition at line 5006 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$rounds = 10\fC [protected]\fP"

.PP
Definition at line 4987 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
