.TH "SqlServerGrammar" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SqlServerGrammar \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGrammar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcompileSelect\fP (\fBBuilder\fP $query)"
.br
.ti -1c
.RI "\fBcompileTruncate\fP (\fBBuilder\fP $query)"
.br
.ti -1c
.RI "\fBgetDateFormat\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcompileColumns\fP (\fBBuilder\fP $query, $columns)"
.br
.ti -1c
.RI "\fBcompileFrom\fP (\fBBuilder\fP $query, $table)"
.br
.ti -1c
.RI "\fBcompileAnsiOffset\fP (\fBBuilder\fP $query, $components)"
.br
.ti -1c
.RI "\fBcompileOver\fP ($orderings)"
.br
.ti -1c
.RI "\fBcompileRowConstraint\fP ($query)"
.br
.ti -1c
.RI "\fBcompileTableExpression\fP ($sql, $constraint)"
.br
.ti -1c
.RI "\fBcompileLimit\fP (\fBBuilder\fP $query, $limit)"
.br
.ti -1c
.RI "\fBcompileOffset\fP (\fBBuilder\fP $query, $offset)"
.br
.ti -1c
.RI "\fBwrapValue\fP ($value)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$operators\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file SqlServerGrammar\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "compileAnsiOffset (\fBBuilder\fP $query,  $components)\fC [protected]\fP"
Create a full ANSI offset clause for the query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$components\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 91 of file SqlServerGrammar\&.php\&.
.SS "compileColumns (\fBBuilder\fP $query,  $columns)\fC [protected]\fP"
Compile the 'select *' portion of the query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$columns\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 46 of file SqlServerGrammar\&.php\&.
.SS "compileFrom (\fBBuilder\fP $query,  $table)\fC [protected]\fP"
Compile the 'from' portion of the query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$table\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 70 of file SqlServerGrammar\&.php\&.
.SS "compileLimit (\fBBuilder\fP $query,  $limit)\fC [protected]\fP"
Compile the 'limit' portions of the query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$limit\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 173 of file SqlServerGrammar\&.php\&.
.SS "compileOffset (\fBBuilder\fP $query,  $offset)\fC [protected]\fP"
Compile the 'offset' portions of the query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$offset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 185 of file SqlServerGrammar\&.php\&.
.SS "compileOver ( $orderings)\fC [protected]\fP"
Compile the over statement for a table expression\&.
.PP
\fBParameters:\fP
.RS 4
\fI$orderings\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 129 of file SqlServerGrammar\&.php\&.
.SS "compileRowConstraint ( $query)\fC [protected]\fP"
Compile the limit / offset row constraint for a query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 140 of file SqlServerGrammar\&.php\&.
.SS "compileSelect (\fBBuilder\fP $query)"
Compile a select query into SQL\&.
.PP
\fBParameters:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 24 of file SqlServerGrammar\&.php\&.
.SS "compileTableExpression ( $sql,  $constraint)\fC [protected]\fP"
Compile a common table expression for a query\&.
.PP
\fBParameters:\fP
.RS 4
\fI$sql\fP 
.br
\fI$constraint\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 161 of file SqlServerGrammar\&.php\&.
.SS "compileTruncate (\fBBuilder\fP $query)"
Compile a truncate table statement into SQL\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 196 of file SqlServerGrammar\&.php\&.
.SS "getDateFormat ()"
Get the format for database stored dates\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 206 of file SqlServerGrammar\&.php\&.
.SS "wrapValue ( $value)\fC [protected]\fP"
Wrap a single string in keyword identifiers\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 217 of file SqlServerGrammar\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$operators\fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= array(
        '=', '<', '>', '<=', '>=', '!<', '!>', '<>', '!=',
        'like', 'not like', 'between', 'ilike',
        '&', '&=', '|', '|=', '^', '^=',
    )
.fi
.PP
Definition at line 12 of file SqlServerGrammar\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
