.TH "Pipeline" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Pipeline \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPipeline\fP, and \fBPipeline\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBContainer\fP $container)"
.br
.ti -1c
.RI "\fBsend\fP ($passable)"
.br
.ti -1c
.RI "\fBthrough\fP ($pipes)"
.br
.ti -1c
.RI "\fBvia\fP ($method)"
.br
.ti -1c
.RI "\fBthen\fP (Closure $destination)"
.br
.ti -1c
.RI "\fB__construct\fP (\fBContainer\fP $container)"
.br
.ti -1c
.RI "\fBsend\fP ($passable)"
.br
.ti -1c
.RI "\fBthrough\fP ($pipes)"
.br
.ti -1c
.RI "\fBvia\fP ($method)"
.br
.ti -1c
.RI "\fBthen\fP (Closure $destination)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetSlice\fP ()"
.br
.ti -1c
.RI "\fBgetInitialSlice\fP (Closure $destination)"
.br
.ti -1c
.RI "\fBgetSlice\fP ()"
.br
.ti -1c
.RI "\fBgetInitialSlice\fP (Closure $destination)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$container\fP"
.br
.ti -1c
.RI "\fB$passable\fP"
.br
.ti -1c
.RI "\fB$pipes\fP = array()"
.br
.ti -1c
.RI "\fB$method\fP = 'handle'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8981 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBContainer\fP $container)"

.PP
Definition at line 8987 of file compiled\&.php\&.
.SS "__construct (\fBContainer\fP $container)"
Create a new class instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$container\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 43 of file Pipeline\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getInitialSlice (Closure $destination)\fC [protected]\fP"
Get the initial slice to begin the stack call\&.
.PP
\fBParameters:\fP
.RS 4
\fI$destination\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 137 of file Pipeline\&.php\&.
.SS "getInitialSlice (Closure $destination)\fC [protected]\fP"

.PP
Definition at line 9024 of file compiled\&.php\&.
.SS "getSlice ()\fC [protected]\fP"
Get a Closure that represents a slice of the application onion\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 109 of file Pipeline\&.php\&.
.SS "getSlice ()\fC [protected]\fP"

.PP
Definition at line 9012 of file compiled\&.php\&.
.SS "send ( $passable)"
Set the object being sent through the pipeline\&.
.PP
\fBParameters:\fP
.RS 4
\fI$passable\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Implements \fBPipeline\fP\&.
.PP
Definition at line 54 of file Pipeline\&.php\&.
.SS "send ( $passable)"

.PP
Implements \fBPipeline\fP\&.
.PP
Definition at line 8991 of file compiled\&.php\&.
.SS "then (Closure $destination)"
Run the pipeline with a final destination callback\&.
.PP
\fBParameters:\fP
.RS 4
\fI$destination\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBPipeline\fP\&.
.PP
Definition at line 93 of file Pipeline\&.php\&.
.SS "then (Closure $destination)"

.PP
Implements \fBPipeline\fP\&.
.PP
Definition at line 9006 of file compiled\&.php\&.
.SS "through ( $pipes)"
Set the array of pipes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$pipes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Implements \fBPipeline\fP\&.
.PP
Definition at line 67 of file Pipeline\&.php\&.
.SS "through ( $pipes)"

.PP
Implements \fBPipeline\fP\&.
.PP
Definition at line 8996 of file compiled\&.php\&.
.SS "via ( $method)"
Set the method to call on the pipes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Implements \fBPipeline\fP\&.
.PP
Definition at line 80 of file Pipeline\&.php\&.
.SS "via ( $method)"

.PP
Implements \fBPipeline\fP\&.
.PP
Definition at line 9001 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$container\fC [protected]\fP"

.PP
Definition at line 8983 of file compiled\&.php\&.
.SS "$method = 'handle'\fC [protected]\fP"

.PP
Definition at line 8986 of file compiled\&.php\&.
.SS "$passable\fC [protected]\fP"

.PP
Definition at line 8984 of file compiled\&.php\&.
.SS "$pipes = array()\fC [protected]\fP"

.PP
Definition at line 8985 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
