.TH "ModelIdentifier" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModelIdentifier \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($class, $id)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$class\fP"
.br
.ti -1c
.RI "\fB$id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file ModelIdentifier\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $class,  $id)"
Create a new model identifier\&.
.PP
\fBParameters:\fP
.RS 4
\fI$class\fP 
.br
\fI$id\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 26 of file ModelIdentifier\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$class"

.PP
Definition at line 10 of file ModelIdentifier\&.php\&.
.SS "$id"

.PP
Definition at line 17 of file ModelIdentifier\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
