.TH "Response" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Response \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBResponse\fP, and \fBResponse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetContent\fP ($content)"
.br
.ti -1c
.RI "\fBgetOriginalContent\fP ()"
.br
.ti -1c
.RI "\fBsetContent\fP ($content)"
.br
.ti -1c
.RI "\fBgetOriginalContent\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$original\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBmorphToJson\fP ($content)"
.br
.ti -1c
.RI "\fBshouldBeJson\fP ($content)"
.br
.ti -1c
.RI "\fBmorphToJson\fP ($content)"
.br
.ti -1c
.RI "\fBshouldBeJson\fP ($content)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14673 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getOriginalContent ()"
Get the original response content\&.
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 81 of file Response\&.php\&.
.SS "getOriginalContent ()"

.PP
Definition at line 14699 of file compiled\&.php\&.
.SS "morphToJson ( $content)\fC [protected]\fP"
Morph the given content into JSON\&.
.PP
\fBParameters:\fP
.RS 4
\fI$content\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 56 of file Response\&.php\&.
.SS "morphToJson ( $content)\fC [protected]\fP"

.PP
Definition at line 14688 of file compiled\&.php\&.
.SS "setContent ( $content)"
Set the content on the response\&.
.PP
\fBParameters:\fP
.RS 4
\fI$content\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 25 of file Response\&.php\&.
.SS "setContent ( $content)"

.PP
Definition at line 14677 of file compiled\&.php\&.
.SS "shouldBeJson ( $content)\fC [protected]\fP"
Determine if the given content should be turned into JSON\&.
.PP
\fBParameters:\fP
.RS 4
\fI$content\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 69 of file Response\&.php\&.
.SS "shouldBeJson ( $content)\fC [protected]\fP"

.PP
Definition at line 14695 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$original"

.PP
Definition at line 14676 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
