.TH "PostgresConnector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PostgresConnector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConnector\fP, and \fBConnectorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnect\fP (array $config)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetDsn\fP (array $config)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$options\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file PostgresConnector\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "connect (array $config)"
Establish a database connection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBConnectorInterface\fP\&.
.PP
Definition at line 25 of file PostgresConnector\&.php\&.
.SS "getDsn (array $config)\fC [protected]\fP"
Create a DSN string from a configuration\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 69 of file PostgresConnector\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBoptions\fP\fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= array(
        PDO::ATTR_CASE => PDO::CASE_NATURAL,
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_ORACLE_NULLS => PDO::NULL_NATURAL,
        PDO::ATTR_STRINGIFY_FETCHES => false,
    )
.fi
.PP
Definition at line 12 of file PostgresConnector\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
