.TH "EnvironmentDetector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EnvironmentDetector \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdetect\fP (Closure $\fBcallback\fP, $consoleArgs=null)"
.br
.ti -1c
.RI "\fBdetect\fP (Closure $\fBcallback\fP, $consoleArgs=null)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBdetectWebEnvironment\fP (Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBdetectConsoleEnvironment\fP (Closure $\fBcallback\fP, array $args)"
.br
.ti -1c
.RI "\fBgetEnvironmentArgument\fP (array $args)"
.br
.ti -1c
.RI "\fBdetectWebEnvironment\fP (Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBdetectConsoleEnvironment\fP (Closure $\fBcallback\fP, array $args)"
.br
.ti -1c
.RI "\fBgetEnvironmentArgument\fP (array $args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1668 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "detect (Closure $callback,  $consoleArgs = \fCnull\fP)"
Detect the application's current environment\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP 
.br
\fI$consoleArgs\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 14 of file EnvironmentDetector\&.php\&.
.SS "detect (Closure $callback,  $consoleArgs = \fCnull\fP)"

.PP
Definition at line 1670 of file compiled\&.php\&.
.SS "detectConsoleEnvironment (Closure $callback, array $args)\fC [protected]\fP"
Set the application environment from command-line arguments\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP 
.br
\fI$args\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 42 of file EnvironmentDetector\&.php\&.
.SS "detectConsoleEnvironment (Closure $callback, array $args)\fC [protected]\fP"

.PP
Definition at line 1681 of file compiled\&.php\&.
.SS "detectWebEnvironment (Closure $callback)\fC [protected]\fP"
Set the application environment for a web request\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 30 of file EnvironmentDetector\&.php\&.
.SS "detectWebEnvironment (Closure $callback)\fC [protected]\fP"

.PP
Definition at line 1677 of file compiled\&.php\&.
.SS "getEnvironmentArgument (array $args)\fC [protected]\fP"
Get the environment argument from the console\&.
.PP
\fBParameters:\fP
.RS 4
\fI$args\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string|null 
.RE
.PP

.PP
Definition at line 61 of file EnvironmentDetector\&.php\&.
.SS "getEnvironmentArgument (array $args)\fC [protected]\fP"

.PP
Definition at line 1688 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
