.TH "Fluent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fluent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAccess, \fBArrayable\fP, \fBJsonable\fP, and JsonSerializable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($attributes=array())"
.br
.ti -1c
.RI "\fBget\fP ($key, $default=null)"
.br
.ti -1c
.RI "\fBgetAttributes\fP ()"
.br
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.ti -1c
.RI "\fBjsonSerialize\fP ()"
.br
.ti -1c
.RI "\fBtoJson\fP ($\fBoptions\fP=0)"
.br
.ti -1c
.RI "\fBoffsetExists\fP ($offset)"
.br
.ti -1c
.RI "\fBoffsetGet\fP ($offset)"
.br
.ti -1c
.RI "\fBoffsetSet\fP ($offset, $value)"
.br
.ti -1c
.RI "\fBoffsetUnset\fP ($offset)"
.br
.ti -1c
.RI "\fB__call\fP ($method, $parameters)"
.br
.ti -1c
.RI "\fB__get\fP ($key)"
.br
.ti -1c
.RI "\fB__set\fP ($key, $value)"
.br
.ti -1c
.RI "\fB__isset\fP ($key)"
.br
.ti -1c
.RI "\fB__unset\fP ($key)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$attributes\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file Fluent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $attributes = \fCarray()\fP)"
Create a new fluent container instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$attributes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 23 of file Fluent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__call ( $method,  $parameters)"
Handle dynamic calls to the container to set attributes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$parameters\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 141 of file Fluent\&.php\&.
.SS "__get ( $key)"
Dynamically retrieve the value of an attribute\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 154 of file Fluent\&.php\&.
.SS "__isset ( $key)"
Dynamically check if an attribute is set\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 177 of file Fluent\&.php\&.
.SS "__set ( $key,  $value)"
Dynamically set the value of an attribute\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 166 of file Fluent\&.php\&.
.SS "__unset ( $key)"
Dynamically unset an attribute\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 188 of file Fluent\&.php\&.
.SS "get ( $key,  $default = \fCnull\fP)"
Get an attribute from the container\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$default\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 38 of file Fluent\&.php\&.
.SS "getAttributes ()"
Get the attributes from the container\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 53 of file Fluent\&.php\&.
.SS "jsonSerialize ()"
Convert the object into something JSON serializable\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 73 of file Fluent\&.php\&.
.SS "offsetExists ( $offset)"
Determine if the given offset exists\&.
.PP
\fBParameters:\fP
.RS 4
\fI$offset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 95 of file Fluent\&.php\&.
.SS "offsetGet ( $offset)"
Get the value for a given offset\&.
.PP
\fBParameters:\fP
.RS 4
\fI$offset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 106 of file Fluent\&.php\&.
.SS "offsetSet ( $offset,  $value)"
Set the value at the given offset\&.
.PP
\fBParameters:\fP
.RS 4
\fI$offset\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 118 of file Fluent\&.php\&.
.SS "offsetUnset ( $offset)"
Unset the value at the given offset\&.
.PP
\fBParameters:\fP
.RS 4
\fI$offset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 129 of file Fluent\&.php\&.
.SS "toArray ()"
Convert the \fBFluent\fP instance to an array\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implements \fBArrayable\fP\&.
.PP
Definition at line 63 of file Fluent\&.php\&.
.SS "toJson ( $options = \fC0\fP)"
Convert the \fBFluent\fP instance to JSON\&.
.PP
\fBParameters:\fP
.RS 4
\fI$options\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBJsonable\fP\&.
.PP
Definition at line 84 of file Fluent\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$attributes = array()\fC [protected]\fP"

.PP
Definition at line 15 of file Fluent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
