.TH "MySqlConnector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MySqlConnector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConnector\fP, and \fBConnectorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnect\fP (array $config)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetDsn\fP (array $config)"
.br
.ti -1c
.RI "\fBconfigHasSocket\fP (array $config)"
.br
.ti -1c
.RI "\fBgetSocketDsn\fP (array $config)"
.br
.ti -1c
.RI "\fBgetHostDsn\fP (array $config)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file MySqlConnector\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "configHasSocket (array $config)\fC [protected]\fP"
Determine if the given configuration array has a UNIX socket value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 79 of file MySqlConnector\&.php\&.
.SS "connect (array $config)"
Establish a database connection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBConnectorInterface\fP\&.
.PP
Definition at line 11 of file MySqlConnector\&.php\&.
.SS "getDsn (array $config)\fC [protected]\fP"
Create a DSN string from a configuration\&.
.PP
Chooses socket or host/port based on the 'unix_socket' config value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 68 of file MySqlConnector\&.php\&.
.SS "getHostDsn (array $config)\fC [protected]\fP"
Get the DSN string for a host / port configuration\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 103 of file MySqlConnector\&.php\&.
.SS "getSocketDsn (array $config)\fC [protected]\fP"
Get the DSN string for a socket configuration\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 90 of file MySqlConnector\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
