.TH "BeanstalkdJob" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BeanstalkdJob \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJob\fP, and \fBJob\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBContainer\fP $container, Pheanstalk $pheanstalk, PheanstalkJob $job, $\fBqueue\fP)"
.br
.ti -1c
.RI "\fBfire\fP ()"
.br
.ti -1c
.RI "\fBgetRawBody\fP ()"
.br
.ti -1c
.RI "\fBdelete\fP ()"
.br
.ti -1c
.RI "\fBrelease\fP ($\fBdelay\fP=0)"
.br
.ti -1c
.RI "\fBbury\fP ()"
.br
.ti -1c
.RI "\fBattempts\fP ()"
.br
.ti -1c
.RI "\fBgetJobId\fP ()"
.br
.ti -1c
.RI "\fBgetContainer\fP ()"
.br
.ti -1c
.RI "\fBgetPheanstalk\fP ()"
.br
.ti -1c
.RI "\fBgetPheanstalkJob\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$pheanstalk\fP"
.br
.ti -1c
.RI "\fB$job\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file BeanstalkdJob\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBContainer\fP $container, Pheanstalk $pheanstalk, PheanstalkJob $job,  $queue)"
Create a new job instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$container\fP 
.br
\fI$pheanstalk\fP 
.br
\fI$job\fP 
.br
\fI$queue\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 33 of file BeanstalkdJob\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "attempts ()"
Get the number of times the job has been attempted\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBJob\fP\&.
.PP
Definition at line 106 of file BeanstalkdJob\&.php\&.
.SS "bury ()"
Bury the job in the queue\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 96 of file BeanstalkdJob\&.php\&.
.SS "delete ()"
Delete the job from the queue\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBJob\fP\&.
.PP
Definition at line 69 of file BeanstalkdJob\&.php\&.
.SS "fire ()"
Fire the job\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBJob\fP\&.
.PP
Definition at line 49 of file BeanstalkdJob\&.php\&.
.SS "getContainer ()"
Get the IoC container instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 128 of file BeanstalkdJob\&.php\&.
.SS "getJobId ()"
Get the job identifier\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 118 of file BeanstalkdJob\&.php\&.
.SS "getPheanstalk ()"
Get the underlying Pheanstalk instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 138 of file BeanstalkdJob\&.php\&.
.SS "getPheanstalkJob ()"
Get the underlying Pheanstalk job\&.
.PP
\fBReturns:\fP
.RS 4
PheanstalkJob 
.RE
.PP

.PP
Definition at line 148 of file BeanstalkdJob\&.php\&.
.SS "getRawBody ()"
Get the raw body string for the job\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 59 of file BeanstalkdJob\&.php\&.
.SS "release ( $delay = \fC0\fP)"
Release the job back into the queue\&.
.PP
\fBParameters:\fP
.RS 4
\fI$delay\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBJob\fP\&.
.PP
Definition at line 82 of file BeanstalkdJob\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$job\fC [protected]\fP"

.PP
Definition at line 22 of file BeanstalkdJob\&.php\&.
.SS "$pheanstalk\fC [protected]\fP"

.PP
Definition at line 15 of file BeanstalkdJob\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
