.TH "SchemeValidator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SchemeValidator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValidatorInterface\fP, and \fBValidatorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmatches\fP (\fBRoute\fP $route, \fBRequest\fP $request)"
.br
.ti -1c
.RI "\fBmatches\fP (\fBRoute\fP $route, \fBRequest\fP $request)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9068 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "matches (\fBRoute\fP $route, \fBRequest\fP $request)"
Validate a given rule against a route and request\&.
.PP
\fBParameters:\fP
.RS 4
\fI$route\fP 
.br
\fI$request\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBValidatorInterface\fP\&.
.PP
Definition at line 15 of file SchemeValidator\&.php\&.
.SS "matches (\fBRoute\fP $route, \fBRequest\fP $request)"

.PP
Implements \fBValidatorInterface\fP\&.
.PP
Definition at line 9070 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
