.TH "ViewServiceProvider" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewServiceProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBServiceProvider\fP, and \fBServiceProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBregisterEngineResolver\fP ()"
.br
.ti -1c
.RI "\fBregisterPhpEngine\fP ($resolver)"
.br
.ti -1c
.RI "\fBregisterBladeEngine\fP ($resolver)"
.br
.ti -1c
.RI "\fBregisterViewFinder\fP ()"
.br
.ti -1c
.RI "\fBregisterFactory\fP ()"
.br
.ti -1c
.RI "\fBregister\fP ()"
.br
.ti -1c
.RI "\fBregisterEngineResolver\fP ()"
.br
.ti -1c
.RI "\fBregisterPhpEngine\fP ($resolver)"
.br
.ti -1c
.RI "\fBregisterBladeEngine\fP ($resolver)"
.br
.ti -1c
.RI "\fBregisterViewFinder\fP ()"
.br
.ti -1c
.RI "\fBregisterFactory\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6682 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "register ()"
Register the service provider\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 16 of file ViewServiceProvider\&.php\&.
.SS "register ()"

.PP
Definition at line 6684 of file compiled\&.php\&.
.SS "registerBladeEngine ( $resolver)"
Register the \fBBlade\fP engine implementation\&.
.PP
\fBParameters:\fP
.RS 4
\fI$resolver\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 65 of file ViewServiceProvider\&.php\&.
.SS "registerBladeEngine ( $resolver)"

.PP
Definition at line 6706 of file compiled\&.php\&.
.SS "registerEngineResolver ()"
Register the engine resolver instance\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 30 of file ViewServiceProvider\&.php\&.
.SS "registerEngineResolver ()"

.PP
Definition at line 6690 of file compiled\&.php\&.
.SS "registerFactory ()"
Register the view environment\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 105 of file ViewServiceProvider\&.php\&.
.SS "registerFactory ()"

.PP
Definition at line 6724 of file compiled\&.php\&.
.SS "registerPhpEngine ( $resolver)"
Register the \fBPHP\fP engine implementation\&.
.PP
\fBParameters:\fP
.RS 4
\fI$resolver\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 54 of file ViewServiceProvider\&.php\&.
.SS "registerPhpEngine ( $resolver)"

.PP
Definition at line 6700 of file compiled\&.php\&.
.SS "registerViewFinder ()"
Register the view finder implementation\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 90 of file ViewServiceProvider\&.php\&.
.SS "registerViewFinder ()"

.PP
Definition at line 6717 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
