.TH "Composer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Composer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBFilesystem\fP $files, $workingPath=null)"
.br
.ti -1c
.RI "\fBdumpAutoloads\fP ($extra= '')"
.br
.ti -1c
.RI "\fBdumpOptimized\fP ()"
.br
.ti -1c
.RI "\fBsetWorkingPath\fP ($\fBpath\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBfindComposer\fP ()"
.br
.ti -1c
.RI "\fBgetProcess\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$files\fP"
.br
.ti -1c
.RI "\fB$workingPath\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file Composer\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBFilesystem\fP $files,  $workingPath = \fCnull\fP)"
Create a new \fBComposer\fP manager instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$files\fP 
.br
\fI$workingPath\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 29 of file Composer\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "dumpAutoloads ( $extra = \fC''\fP)"
Regenerate the \fBComposer\fP autoloader files\&.
.PP
\fBParameters:\fP
.RS 4
\fI$extra\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 41 of file Composer\&.php\&.
.SS "dumpOptimized ()"
Regenerate the optimized \fBComposer\fP autoloader files\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 55 of file Composer\&.php\&.
.SS "findComposer ()\fC [protected]\fP"
Get the composer command for the environment\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 65 of file Composer\&.php\&.
.SS "getProcess ()\fC [protected]\fP"
Get a new \fBSymfony\fP process instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 80 of file Composer\&.php\&.
.SS "setWorkingPath ( $path)"
Set the working path used by the class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 91 of file Composer\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$files\fC [protected]\fP"

.PP
Definition at line 13 of file Composer\&.php\&.
.SS "$workingPath\fC [protected]\fP"

.PP
Definition at line 20 of file Composer\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
