.TH "OptimizeCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptimizeCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBComposer\fP $composer)"
.br
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcompileClasses\fP ()"
.br
.ti -1c
.RI "\fBgetClassFiles\fP ()"
.br
.ti -1c
.RI "\fBregisterClassPreloaderCommand\fP ()"
.br
.ti -1c
.RI "\fBgetOptions\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'optimize'"
.br
.ti -1c
.RI "\fB$description\fP = 'Optimize the framework \fBfor\fP better performance'"
.br
.ti -1c
.RI "\fB$composer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file OptimizeCommand\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBComposer\fP $composer)"
Create a new optimize command instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$composer\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 37 of file OptimizeCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "compileClasses ()\fC [protected]\fP"
Generate the compiled class file\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 79 of file OptimizeCommand\&.php\&.
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 49 of file OptimizeCommand\&.php\&.
.SS "getClassFiles ()\fC [protected]\fP"
Get the classes that should be combined and compiled\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 95 of file OptimizeCommand\&.php\&.
.SS "getOptions ()\fC [protected]\fP"
Get the console command options\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 126 of file OptimizeCommand\&.php\&.
.SS "registerClassPreloaderCommand ()\fC [protected]\fP"
Register the pre-compiler command instance with \fBArtisan\fP\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 116 of file OptimizeCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$composer\fC [protected]\fP"

.PP
Definition at line 29 of file OptimizeCommand\&.php\&.
.SS "$description = 'Optimize the framework \fBfor\fP better performance'\fC [protected]\fP"

.PP
Definition at line 22 of file OptimizeCommand\&.php\&.
.SS "$\fBname\fP = 'optimize'\fC [protected]\fP"

.PP
Definition at line 15 of file OptimizeCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
