.TH "Hub" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Hub \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHub\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpipe\fP ($object, $pipeline=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Hub\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "pipe ( $object,  $pipeline = \fCnull\fP)"
Send an object through one of the available pipelines\&.
.PP
\fBParameters:\fP
.RS 4
\fI$object\fP 
.br
\fI$pipeline\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBHub\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
