.TH "Password" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Password \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFacade\fP\&.
.PP
Inherited by \fBPassword\fP\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBRESET_LINK_SENT\fP = 'passwords\&.sent'"
.br
.ti -1c
.RI "const \fBPASSWORD_RESET\fP = 'passwords\&.reset'"
.br
.ti -1c
.RI "const \fBINVALID_USER\fP = 'passwords\&.user'"
.br
.ti -1c
.RI "const \fBINVALID_PASSWORD\fP = 'passwords\&.password'"
.br
.ti -1c
.RI "const \fBINVALID_TOKEN\fP = 'passwords\&.token'"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetFacadeAccessor\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBSee also:\fP
.RS 4

.RE
.PP

.PP
Definition at line 6 of file Password\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getFacadeAccessor ()\fC [static]\fP, \fC [protected]\fP"
Get the registered name of the component\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 48 of file Password\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const INVALID_PASSWORD = 'passwords\&.password'"

.PP
Definition at line 34 of file Password\&.php\&.
.SS "const INVALID_TOKEN = 'passwords\&.token'"

.PP
Definition at line 41 of file Password\&.php\&.
.SS "const INVALID_USER = 'passwords\&.user'"

.PP
Definition at line 27 of file Password\&.php\&.
.SS "const PASSWORD_RESET = 'passwords\&.reset'"

.PP
Definition at line 20 of file Password\&.php\&.
.SS "const RESET_LINK_SENT = 'passwords\&.sent'"

.PP
Definition at line 13 of file Password\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
