.TH "Database" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Database \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDatabase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcommand\fP ($method, array $parameters=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Database\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "command ( $method, array $parameters = \fCarray()\fP)"
Run a command against the \fBRedis\fP database\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$parameters\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBDatabase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
