.TH "LoadConfiguration" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoadConfiguration \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbootstrap\fP (\fBApplication\fP $app)"
.br
.ti -1c
.RI "\fBbootstrap\fP (\fBApplication\fP $app)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBloadConfigurationFiles\fP (\fBApplication\fP $app, RepositoryContract $config)"
.br
.ti -1c
.RI "\fBgetConfigurationFiles\fP (\fBApplication\fP $app)"
.br
.ti -1c
.RI "\fBloadConfigurationFiles\fP (\fBApplication\fP $app, RepositoryContract $config)"
.br
.ti -1c
.RI "\fBgetConfigurationFiles\fP (\fBApplication\fP $app)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1839 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "bootstrap (\fBApplication\fP $app)"
\fBBootstrap\fP the given application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 17 of file LoadConfiguration\&.php\&.
.SS "bootstrap (\fBApplication\fP $app)"

.PP
Definition at line 1841 of file compiled\&.php\&.
.SS "getConfigurationFiles (\fBApplication\fP $app)\fC [protected]\fP"
Get all of the configuration files for the application\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 67 of file LoadConfiguration\&.php\&.
.SS "getConfigurationFiles (\fBApplication\fP $app)\fC [protected]\fP"

.PP
Definition at line 1861 of file compiled\&.php\&.
.SS "loadConfigurationFiles (\fBApplication\fP $app, RepositoryContract $config)\fC [protected]\fP"
Load the configuration items from all of the files\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.br
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 53 of file LoadConfiguration\&.php\&.
.SS "loadConfigurationFiles (\fBApplication\fP $app, RepositoryContract $config)\fC [protected]\fP"

.PP
Definition at line 1855 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
