.TH "ContextualBindingBuilder" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ContextualBindingBuilder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBContextualBindingBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBContainer\fP $container, $concrete)"
.br
.ti -1c
.RI "\fBneeds\fP ($abstract)"
.br
.ti -1c
.RI "\fBgive\fP ($implementation)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$container\fP"
.br
.ti -1c
.RI "\fB$concrete\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ContextualBindingBuilder\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBContainer\fP $container,  $concrete)"
Create a new contextual binding builder\&.
.PP
\fBParameters:\fP
.RS 4
\fI$container\fP 
.br
\fI$concrete\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 28 of file ContextualBindingBuilder\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "give ( $implementation)"
Define the implementation for the contextual binding\&.
.PP
\fBParameters:\fP
.RS 4
\fI$implementation\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBContextualBindingBuilder\fP\&.
.PP
Definition at line 53 of file ContextualBindingBuilder\&.php\&.
.SS "needs ( $abstract)"
Define the abstract target that depends on the context\&.
.PP
\fBParameters:\fP
.RS 4
\fI$abstract\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Implements \fBContextualBindingBuilder\fP\&.
.PP
Definition at line 40 of file ContextualBindingBuilder\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$concrete\fC [protected]\fP"

.PP
Definition at line 19 of file ContextualBindingBuilder\&.php\&.
.SS "$container\fC [protected]\fP"

.PP
Definition at line 12 of file ContextualBindingBuilder\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
