.TH "ListFailedCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListFailedCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfire\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBparseFailedJob\fP (array $failed)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP = 'queue:failed'"
.br
.ti -1c
.RI "\fB$description\fP = 'List all of the failed \fBqueue\fP jobs'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file ListFailedCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "fire ()"
Execute the console command\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 26 of file ListFailedCommand\&.php\&.
.SS "parseFailedJob (array $failed)\fC [protected]\fP"
Parse the failed job row\&.
.PP
\fBParameters:\fP
.RS 4
\fI$failed\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 53 of file ListFailedCommand\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$description = 'List all of the failed \fBqueue\fP jobs'\fC [protected]\fP"

.PP
Definition at line 19 of file ListFailedCommand\&.php\&.
.SS "$\fBname\fP = 'queue:failed'\fC [protected]\fP"

.PP
Definition at line 12 of file ListFailedCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
