.TH "DatabaseConnector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DatabaseConnector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConnectorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBConnectionResolverInterface\fP $connections)"
.br
.ti -1c
.RI "\fBconnect\fP (array $config)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$connections\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file DatabaseConnector\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBConnectionResolverInterface\fP $connections)"
Create a new connector instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$connections\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 21 of file DatabaseConnector\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "connect (array $config)"
Establish a queue connection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Implements \fBConnectorInterface\fP\&.
.PP
Definition at line 32 of file DatabaseConnector\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$connections\fC [protected]\fP"

.PP
Definition at line 13 of file DatabaseConnector\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
