.TH "Illuminate\Database\Connectors" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Illuminate\Database\Connectors \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBConnectionFactory\fP"
.br
.ti -1c
.RI "class \fBConnector\fP"
.br
.ti -1c
.RI "interface \fBConnectorInterface\fP"
.br
.ti -1c
.RI "class \fBMySqlConnector\fP"
.br
.ti -1c
.RI "class \fBPostgresConnector\fP"
.br
.ti -1c
.RI "class \fBSQLiteConnector\fP"
.br
.ti -1c
.RI "class \fBSqlServerConnector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
