.TH "SQLiteGrammar" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SQLiteGrammar \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGrammar\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcompileInsert\fP (\fBBuilder\fP $query, array $\fBvalues\fP)"
.br
.ti -1c
.RI "\fBcompileTruncate\fP (\fBBuilder\fP $query)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwhereDay\fP (\fBBuilder\fP $query, $where)"
.br
.ti -1c
.RI "\fBwhereMonth\fP (\fBBuilder\fP $query, $where)"
.br
.ti -1c
.RI "\fBwhereYear\fP (\fBBuilder\fP $query, $where)"
.br
.ti -1c
.RI "\fBdateBasedWhere\fP ($type, \fBBuilder\fP $query, $where)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$operators\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file SQLiteGrammar\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "compileInsert (\fBBuilder\fP $query, array $values)"
Compile an insert statement into SQL\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$values\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 25 of file SQLiteGrammar\&.php\&.
.SS "compileTruncate (\fBBuilder\fP $query)"
Compile a truncate table statement into SQL\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 68 of file SQLiteGrammar\&.php\&.
.SS "dateBasedWhere ( $type, \fBBuilder\fP $query,  $where)\fC [protected]\fP"
Compile a date based where clause\&.
.PP
\fBParameters:\fP
.RS 4
\fI$type\fP 
.br
\fI$query\fP 
.br
\fI$where\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 121 of file SQLiteGrammar\&.php\&.
.SS "whereDay (\fBBuilder\fP $query,  $where)\fC [protected]\fP"
Compile a 'where day' clause\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$where\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 84 of file SQLiteGrammar\&.php\&.
.SS "whereMonth (\fBBuilder\fP $query,  $where)\fC [protected]\fP"
Compile a 'where month' clause\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$where\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 96 of file SQLiteGrammar\&.php\&.
.SS "whereYear (\fBBuilder\fP $query,  $where)\fC [protected]\fP"
Compile a 'where year' clause\&.
.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.br
\fI$where\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 108 of file SQLiteGrammar\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$operators\fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= array(
        '=', '<', '>', '<=', '>=', '<>', '!=',
        'like', 'not like', 'between', 'ilike',
        '&', '|', '<<', '>>',
    )
.fi
.PP
Definition at line 12 of file SQLiteGrammar\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
