.TH "BaseCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.PP
Inherited by \fBMigrateCommand\fP, \fBMigrateMakeCommand\fP, and \fBStatusCommand\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMigrationPath\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file BaseCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getMigrationPath ()\fC [protected]\fP"
Get the path to the migration directory\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 12 of file BaseCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
