.TH "Mailer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mailer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMailer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBraw\fP ($\fBtext\fP, $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBsend\fP ($view, array $\fBdata\fP, $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBfailures\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file Mailer\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "failures ()"
Get the array of failed recipients\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBMailer\fP\&.
.SS "raw ( $text,  $callback)"
Send a new message when only a raw text part\&.
.PP
\fBParameters:\fP
.RS 4
\fI$text\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implemented in \fBMailer\fP\&.
.SS "send ( $view, array $data,  $callback)"
Send a new message using a view\&.
.PP
\fBParameters:\fP
.RS 4
\fI$view\fP 
.br
\fI$data\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implemented in \fBMailer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
