.TH "PasswordBroker" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PasswordBroker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPasswordBroker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBTokenRepositoryInterface\fP $tokens, \fBUserProvider\fP $users, MailerContract $mailer, $emailView)"
.br
.ti -1c
.RI "\fBsendResetLink\fP (array $credentials, Closure $\fBcallback\fP=null)"
.br
.ti -1c
.RI "\fBemailResetLink\fP (CanResetPasswordContract $user, $token, Closure $\fBcallback\fP=null)"
.br
.ti -1c
.RI "\fBreset\fP (array $credentials, Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBvalidator\fP (Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBvalidateNewPassword\fP (array $credentials)"
.br
.ti -1c
.RI "\fBgetUser\fP (array $credentials)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvalidateReset\fP (array $credentials)"
.br
.ti -1c
.RI "\fBvalidatePasswordWithDefaults\fP (array $credentials)"
.br
.ti -1c
.RI "\fBgetRepository\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$tokens\fP"
.br
.ti -1c
.RI "\fB$users\fP"
.br
.ti -1c
.RI "\fB$mailer\fP"
.br
.ti -1c
.RI "\fB$emailView\fP"
.br
.ti -1c
.RI "\fB$passwordValidator\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file PasswordBroker\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBTokenRepositoryInterface\fP $tokens, \fBUserProvider\fP $users, MailerContract $mailer,  $emailView)"
Create a new password broker instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$tokens\fP 
.br
\fI$users\fP 
.br
\fI$mailer\fP 
.br
\fI$emailView\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 56 of file PasswordBroker\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "emailResetLink (CanResetPasswordContract $user,  $token, Closure $callback = \fCnull\fP)"
Send the password reset link via e-mail\&.
.PP
\fBParameters:\fP
.RS 4
\fI$user\fP 
.br
\fI$token\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 104 of file PasswordBroker\&.php\&.
.SS "getRepository ()\fC [protected]\fP"
Get the password reset token repository implementation\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 250 of file PasswordBroker\&.php\&.
.SS "getUser (array $credentials)"
Get the user for the given credentials\&.
.PP
\fBParameters:\fP
.RS 4
\fI$credentials\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 231 of file PasswordBroker\&.php\&.
.SS "reset (array $credentials, Closure $callback)"
Reset the password for the given token\&.
.PP
\fBParameters:\fP
.RS 4
\fI$credentials\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBPasswordBroker\fP\&.
.PP
Definition at line 126 of file PasswordBroker\&.php\&.
.SS "sendResetLink (array $credentials, Closure $callback = \fCnull\fP)"
Send a password reset link to a user\&.
.PP
\fBParameters:\fP
.RS 4
\fI$credentials\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBPasswordBroker\fP\&.
.PP
Definition at line 74 of file PasswordBroker\&.php\&.
.SS "validateNewPassword (array $credentials)"
Determine if the passwords match for the request\&.
.PP
\fBParameters:\fP
.RS 4
\fI$credentials\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBPasswordBroker\fP\&.
.PP
Definition at line 193 of file PasswordBroker\&.php\&.
.SS "validatePasswordWithDefaults (array $credentials)\fC [protected]\fP"
Determine if the passwords are valid for the request\&.
.PP
\fBParameters:\fP
.RS 4
\fI$credentials\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 214 of file PasswordBroker\&.php\&.
.SS "validateReset (array $credentials)\fC [protected]\fP"
Validate a password reset for the given credentials\&.
.PP
\fBParameters:\fP
.RS 4
\fI$credentials\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 156 of file PasswordBroker\&.php\&.
.SS "validator (Closure $callback)"
Set a custom password validator\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Implements \fBPasswordBroker\fP\&.
.PP
Definition at line 182 of file PasswordBroker\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$emailView\fC [protected]\fP"

.PP
Definition at line 38 of file PasswordBroker\&.php\&.
.SS "$mailer\fC [protected]\fP"

.PP
Definition at line 31 of file PasswordBroker\&.php\&.
.SS "$passwordValidator\fC [protected]\fP"

.PP
Definition at line 45 of file PasswordBroker\&.php\&.
.SS "$tokens\fC [protected]\fP"

.PP
Definition at line 17 of file PasswordBroker\&.php\&.
.SS "$users\fC [protected]\fP"

.PP
Definition at line 24 of file PasswordBroker\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
