.TH "Manager" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Manager \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAuthManager\fP, \fBAuthManager\fP, \fBTransportManager\fP, \fBSessionManager\fP, and \fBSessionManager\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($app)"
.br
.ti -1c
.RI "\fBgetDefaultDriver\fP ()"
.br
.ti -1c
.RI "\fBdriver\fP ($driver=null)"
.br
.ti -1c
.RI "\fBextend\fP ($\fBdriver\fP, Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBgetDrivers\fP ()"
.br
.ti -1c
.RI "\fB__call\fP ($method, $parameters)"
.br
.ti -1c
.RI "\fB__construct\fP ($app)"
.br
.ti -1c
.RI "\fBgetDefaultDriver\fP ()"
.br
.ti -1c
.RI "\fBdriver\fP ($driver=null)"
.br
.ti -1c
.RI "\fBextend\fP ($\fBdriver\fP, Closure $\fBcallback\fP)"
.br
.ti -1c
.RI "\fBgetDrivers\fP ()"
.br
.ti -1c
.RI "\fB__call\fP ($method, $parameters)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateDriver\fP ($\fBdriver\fP)"
.br
.ti -1c
.RI "\fBcallCustomCreator\fP ($\fBdriver\fP)"
.br
.ti -1c
.RI "\fBcreateDriver\fP ($\fBdriver\fP)"
.br
.ti -1c
.RI "\fBcallCustomCreator\fP ($\fBdriver\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$app\fP"
.br
.ti -1c
.RI "\fB$customCreators\fP = array()"
.br
.ti -1c
.RI "\fB$drivers\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11332 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $app)"

.PP
Definition at line 11337 of file compiled\&.php\&.
.SS "__construct ( $app)"
Create a new manager instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 35 of file Manager\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__call ( $method,  $parameters)"
Dynamically call the default driver instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$parameters\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 137 of file Manager\&.php\&.
.SS "__call ( $method,  $parameters)"

.PP
Definition at line 11373 of file compiled\&.php\&.
.SS "callCustomCreator ( $driver)\fC [protected]\fP"
Call a custom driver creator\&.
.PP
\fBParameters:\fP
.RS 4
\fI$driver\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 101 of file Manager\&.php\&.
.SS "callCustomCreator ( $driver)\fC [protected]\fP"

.PP
Definition at line 11360 of file compiled\&.php\&.
.SS "createDriver ( $driver)\fC [protected]\fP"
Create a new driver instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$driver\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 76 of file Manager\&.php\&.
.SS "createDriver ( $driver)\fC [protected]\fP"

.PP
Definition at line 11350 of file compiled\&.php\&.
.SS "driver ( $driver = \fCnull\fP)"
Get a driver instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$driver\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 53 of file Manager\&.php\&.
.SS "driver ( $driver = \fCnull\fP)"

.PP
Definition at line 11342 of file compiled\&.php\&.
.SS "extend ( $driver, Closure $callback)"
Register a custom driver creator Closure\&.
.PP
\fBParameters:\fP
.RS 4
\fI$driver\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 113 of file Manager\&.php\&.
.SS "extend ( $driver, Closure $callback)"

.PP
Definition at line 11364 of file compiled\&.php\&.
.SS "getDefaultDriver ()\fC [abstract]\fP"
Get the default driver name\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.SS "getDefaultDriver ()\fC [abstract]\fP"

.SS "getDrivers ()"
Get all of the created 'drivers'\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 125 of file Manager\&.php\&.
.SS "getDrivers ()"

.PP
Definition at line 11369 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$app\fC [protected]\fP"

.PP
Definition at line 11334 of file compiled\&.php\&.
.SS "$customCreators = array()\fC [protected]\fP"

.PP
Definition at line 11335 of file compiled\&.php\&.
.SS "$drivers = array()\fC [protected]\fP"

.PP
Definition at line 11336 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
