.TH "Facade" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Facade \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFormFacade\fP, \fBHtmlFacade\fP, \fBApp\fP, \fBApp\fP, \fBArtisan\fP, \fBAuth\fP, \fBBlade\fP, \fBBus\fP, \fBCache\fP, \fBConfig\fP, \fBCookie\fP, \fBCrypt\fP, \fBDB\fP, \fBEvent\fP, \fBFile\fP, \fBHash\fP, \fBInput\fP, \fBLang\fP, \fBLog\fP, \fBLog\fP, \fBMail\fP, \fBPassword\fP, \fBQueue\fP, \fBRedirect\fP, \fBRedis\fP, \fBRequest\fP, \fBResponse\fP, \fBRoute\fP, \fBRoute\fP, \fBSchema\fP, \fBSession\fP, \fBStorage\fP, \fBURL\fP, \fBValidator\fP, \fBView\fP, \fBView\fP, and \fBFlash\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBswap\fP ($instance)"
.br
.ti -1c
.RI "static \fBshouldReceive\fP ()"
.br
.ti -1c
.RI "static \fBgetFacadeRoot\fP ()"
.br
.ti -1c
.RI "static \fBclearResolvedInstance\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBclearResolvedInstances\fP ()"
.br
.ti -1c
.RI "static \fBgetFacadeApplication\fP ()"
.br
.ti -1c
.RI "static \fBsetFacadeApplication\fP ($app)"
.br
.ti -1c
.RI "static \fB__callStatic\fP ($method, $args)"
.br
.ti -1c
.RI "static \fBswap\fP ($instance)"
.br
.ti -1c
.RI "static \fBshouldReceive\fP ()"
.br
.ti -1c
.RI "static \fBgetFacadeRoot\fP ()"
.br
.ti -1c
.RI "static \fBclearResolvedInstance\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBclearResolvedInstances\fP ()"
.br
.ti -1c
.RI "static \fBgetFacadeApplication\fP ()"
.br
.ti -1c
.RI "static \fBsetFacadeApplication\fP ($app)"
.br
.ti -1c
.RI "static \fB__callStatic\fP ($method, $args)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBcreateFreshMockInstance\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBcreateMockByName\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBisMock\fP ()"
.br
.ti -1c
.RI "static \fBgetMockableClass\fP ()"
.br
.ti -1c
.RI "static \fBgetFacadeAccessor\fP ()"
.br
.ti -1c
.RI "static \fBresolveFacadeInstance\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBcreateFreshMockInstance\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBcreateMockByName\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBisMock\fP ()"
.br
.ti -1c
.RI "static \fBgetMockableClass\fP ()"
.br
.ti -1c
.RI "static \fBgetFacadeAccessor\fP ()"
.br
.ti -1c
.RI "static \fBresolveFacadeInstance\fP ($\fBname\fP)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$app\fP"
.br
.ti -1c
.RI "static \fB$resolvedInstance\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5276 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static __callStatic ( $method,  $args)\fC [static]\fP"
Handle dynamic, static calls to the object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$args\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 200 of file Facade\&.php\&.
.SS "static __callStatic ( $method,  $args)\fC [static]\fP"

.PP
Definition at line 5353 of file compiled\&.php\&.
.SS "static clearResolvedInstance ( $name)\fC [static]\fP"
Clear a resolved facade instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 157 of file Facade\&.php\&.
.SS "static clearResolvedInstance ( $name)\fC [static]\fP"

.PP
Definition at line 5337 of file compiled\&.php\&.
.SS "static clearResolvedInstances ()\fC [static]\fP"
Clear all of the resolved instances\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 167 of file Facade\&.php\&.
.SS "static clearResolvedInstances ()\fC [static]\fP"

.PP
Definition at line 5341 of file compiled\&.php\&.
.SS "static createFreshMockInstance ( $name)\fC [static]\fP, \fC [protected]\fP"
Create a fresh mock instance for the given class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 64 of file Facade\&.php\&.
.SS "static createFreshMockInstance ( $name)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5295 of file compiled\&.php\&.
.SS "static createMockByName ( $name)\fC [static]\fP, \fC [protected]\fP"
Create a fresh mock instance for the given class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 82 of file Facade\&.php\&.
.SS "static createMockByName ( $name)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5303 of file compiled\&.php\&.
.SS "static getFacadeAccessor ()\fC [static]\fP, \fC [protected]\fP"
Get the registered name of the component\&.
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 128 of file Facade\&.php\&.
.SS "static getFacadeAccessor ()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5323 of file compiled\&.php\&.
.SS "static getFacadeApplication ()\fC [static]\fP"
Get the application instance behind the facade\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 177 of file Facade\&.php\&.
.SS "static getFacadeApplication ()\fC [static]\fP"

.PP
Definition at line 5345 of file compiled\&.php\&.
.SS "static getFacadeRoot ()\fC [static]\fP"
Get the root object behind the facade\&.
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 116 of file Facade\&.php\&.
.SS "static getFacadeRoot ()\fC [static]\fP"

.PP
Definition at line 5319 of file compiled\&.php\&.
.SS "static getMockableClass ()\fC [static]\fP, \fC [protected]\fP"
Get the mockable class for the bound instance\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 106 of file Facade\&.php\&.
.SS "static getMockableClass ()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5313 of file compiled\&.php\&.
.SS "static isMock ()\fC [static]\fP, \fC [protected]\fP"
Determines whether a mock is set as the instance of the facade\&.
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 94 of file Facade\&.php\&.
.SS "static isMock ()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5308 of file compiled\&.php\&.
.SS "static resolveFacadeInstance ( $name)\fC [static]\fP, \fC [protected]\fP"
Resolve the facade root instance from the container\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 139 of file Facade\&.php\&.
.SS "static resolveFacadeInstance ( $name)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5327 of file compiled\&.php\&.
.SS "static setFacadeApplication ( $app)\fC [static]\fP"
Set the application instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$app\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 188 of file Facade\&.php\&.
.SS "static setFacadeApplication ( $app)\fC [static]\fP"

.PP
Definition at line 5349 of file compiled\&.php\&.
.SS "static shouldReceive ()\fC [static]\fP"
Initiate a mock expectation on the facade\&.
.PP
\fBParameters:\fP
.RS 4
\fImixed\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 42 of file Facade\&.php\&.
.SS "static shouldReceive ()\fC [static]\fP"

.PP
Definition at line 5285 of file compiled\&.php\&.
.SS "static swap ( $instance)\fC [static]\fP"
Hotswap the underlying instance behind the facade\&.
.PP
\fBParameters:\fP
.RS 4
\fI$instance\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 29 of file Facade\&.php\&.
.SS "static swap ( $instance)\fC [static]\fP"

.PP
Definition at line 5280 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "static $app\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5278 of file compiled\&.php\&.
.SS "static $resolvedInstance\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 5279 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
