.TH "InheritanceB" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InheritanceB \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.PP
Inherited by \fBInheritanceA\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSomething\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file InheritanceB\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testSomething ()"

.PP
Definition at line 5 of file InheritanceB\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
