.TH "Issue1468Test" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Issue1468Test \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestFailure\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2 of file Issue1468Test\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testFailure ()"

.PP
\fBTodo\fP
.RS 4
Implement this test 
.RE
.PP

.PP
Definition at line 7 of file Issue1468Test\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
