.TH "Laravel" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Laravel \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBLaravel\fP - \fBA\fP \fBPHP\fP Framework For Web Artisans
.PP
\fBAuthor:\fP
.RS 4
Taylor Otwell taylorotwell@gmail.com 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
