.TH "Config" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Config \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $settings=[])"
.br
.ti -1c
.RI "\fBget\fP ($key, $default=null)"
.br
.ti -1c
.RI "\fBhas\fP ($key)"
.br
.ti -1c
.RI "\fBset\fP ($key, $value)"
.br
.ti -1c
.RI "\fBsetFallback\fP (\fBConfig\fP $fallback)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetDefault\fP ($key, $default)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$settings\fP = []"
.br
.ti -1c
.RI "\fB$fallback\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Config\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $settings = \fC[]\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$settings\fP 
.RE
.PP

.PP
Definition at line 22 of file Config\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "get ( $key,  $default = \fCnull\fP)"
Get a setting\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$default\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed config setting or default when not found 
.RE
.PP

.PP
Definition at line 35 of file Config\&.php\&.
.SS "getDefault ( $key,  $default)\fC [protected]\fP"
Try to retrieve a default setting from a config fallback\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$default\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed config setting or default when not found 
.RE
.PP

.PP
Definition at line 64 of file Config\&.php\&.
.SS "has ( $key)"
Check if an item exists by key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 51 of file Config\&.php\&.
.SS "set ( $key,  $value)"
Set a setting\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.br
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 81 of file Config\&.php\&.
.SS "setFallback (\fBConfig\fP $fallback)"
Set the fallback\&.
.PP
\fBParameters:\fP
.RS 4
\fI$fallback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 95 of file Config\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$fallback\fC [protected]\fP"

.PP
Definition at line 15 of file Config\&.php\&.
.SS "$settings = []\fC [protected]\fP"

.PP
Definition at line 10 of file Config\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
