.TH "PluginInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PluginInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAbstractPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMethod\fP ()"
.br
.ti -1c
.RI "\fBsetFilesystem\fP (\fBFilesystemInterface\fP $filesystem)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file PluginInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getMethod ()"
Get the method name\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBGetWithMetadata\fP, \fBEmptyDir\fP, \fBListFiles\fP, \fBListPaths\fP, and \fBListWith\fP\&.
.SS "setFilesystem (\fBFilesystemInterface\fP $filesystem)"
Set the \fBFilesystem\fP object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$filesystem\fP 
.RE
.PP

.PP
Implemented in \fBAbstractPlugin\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
