.TH "FilesystemInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilesystemInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFilesystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhas\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBread\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBreadStream\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBlistContents\fP ($directory= '', $recursive=false)"
.br
.ti -1c
.RI "\fBgetMetadata\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBgetSize\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBgetMimetype\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBgetTimestamp\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBgetVisibility\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBwrite\fP ($\fBpath\fP, $contents, array $config=[])"
.br
.ti -1c
.RI "\fBwriteStream\fP ($\fBpath\fP, $resource, array $config=[])"
.br
.ti -1c
.RI "\fBupdate\fP ($\fBpath\fP, $contents, array $config=[])"
.br
.ti -1c
.RI "\fBupdateStream\fP ($\fBpath\fP, $resource, array $config=[])"
.br
.ti -1c
.RI "\fBrename\fP ($\fBpath\fP, $newpath)"
.br
.ti -1c
.RI "\fBcopy\fP ($\fBpath\fP, $newpath)"
.br
.ti -1c
.RI "\fBdelete\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBdeleteDir\fP ($dirname)"
.br
.ti -1c
.RI "\fBcreateDir\fP ($dirname, array $config=[])"
.br
.ti -1c
.RI "\fBsetVisibility\fP ($\fBpath\fP, $visibility)"
.br
.ti -1c
.RI "\fBput\fP ($\fBpath\fP, $contents, array $config=[])"
.br
.ti -1c
.RI "\fBputStream\fP ($\fBpath\fP, $resource, array $config=[])"
.br
.ti -1c
.RI "\fBreadAndDelete\fP ($\fBpath\fP)"
.br
.ti -1c
.RI "\fBget\fP ($\fBpath\fP, \fBHandler\fP $handler=null)"
.br
.ti -1c
.RI "\fBaddPlugin\fP (\fBPluginInterface\fP $plugin)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file FilesystemInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addPlugin (\fBPluginInterface\fP $plugin)"
Register a plugin\&.
.PP
\fBParameters:\fP
.RS 4
\fI$plugin\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.SS "copy ( $path,  $newpath)"
Copy a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$newpath\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "createDir ( $dirname, array $config = \fC[]\fP)"
Create a directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$dirname\fP directory name 
.br
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "delete ( $path)"
Delete a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "deleteDir ( $dirname)"
Delete a directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$dirname\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "get ( $path, \fBHandler\fP $handler = \fCnull\fP)"
Get a file/directory handler\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$handler\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBHandler\fP file or directory handler 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "getMetadata ( $path)"
Get all the meta data of a file or directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
false|array 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "getMimetype ( $path)"
Get the mime-type of a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
false|string 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "getSize ( $path)"
Get all the meta data of a file or directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
false|int 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "getTimestamp ( $path)"
Get the timestamp of a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
false|int 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "getVisibility ( $path)"
Get the visibility of a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
false|string 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "has ( $path)"
Check whether a file exists\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "listContents ( $directory = \fC''\fP,  $recursive = \fCfalse\fP)"
List contents of a directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.br
\fI$recursive\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "put ( $path,  $contents, array $config = \fC[]\fP)"
Create a file or update if exists\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP path to file 
.br
\fI$contents\fP file contents 
.br
\fI$config\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBFileExistsException\fP\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool success boolean 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "putStream ( $path,  $resource, array $config = \fC[]\fP)"
Create a file or update if exists using a stream\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$resource\fP 
.br
\fI$config\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool success boolean 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "read ( $path)"
Read a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
false|string 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "readAndDelete ( $path)"
Read and delete a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBFileNotFoundException\fP\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string|false file contents 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "readStream ( $path)"
Read a file as a stream\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
false|resource 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "rename ( $path,  $newpath)"
Rename a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$newpath\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "setVisibility ( $path,  $visibility)"
Set the visibility for a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$visibility\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool success boolean 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "update ( $path,  $contents, array $config = \fC[]\fP)"
Update a file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$contents\fP 
.br
\fI$config\fP config array
.RE
.PP
\fBReturns:\fP
.RS 4
bool success boolean 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "updateStream ( $path,  $resource, array $config = \fC[]\fP)"
Update a file using a stream\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$resource\fP 
.br
\fI$config\fP config array
.RE
.PP
\fBReturns:\fP
.RS 4
bool success boolean 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "write ( $path,  $contents, array $config = \fC[]\fP)"
Write a new file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$contents\fP 
.br
\fI$config\fP \fBConfig\fP array
.RE
.PP
\fBReturns:\fP
.RS 4
bool success boolean 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.
.SS "writeStream ( $path,  $resource, array $config = \fC[]\fP)"
Write a new file using a stream\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$resource\fP 
.br
\fI$config\fP config array
.RE
.PP
\fBReturns:\fP
.RS 4
bool success boolean 
.RE
.PP

.PP
Implemented in \fBFilesystem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
