.TH "League\Flysystem\Adapter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
League\Flysystem\Adapter \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPolyfill\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAbstractAdapter\fP"
.br
.ti -1c
.RI "class \fBAbstractFtpAdapter\fP"
.br
.ti -1c
.RI "class \fBFtp\fP"
.br
.ti -1c
.RI "class \fBLocal\fP"
.br
.ti -1c
.RI "class \fBNullAdapter\fP"
.br
.ti -1c
.RI "class \fBSynologyFtp\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
