.TH "League\Flysystem\Plugin" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
League\Flysystem\Plugin \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAbstractPlugin\fP"
.br
.ti -1c
.RI "class \fBEmptyDir\fP"
.br
.ti -1c
.RI "class \fBGetWithMetadata\fP"
.br
.ti -1c
.RI "class \fBListFiles\fP"
.br
.ti -1c
.RI "class \fBListPaths\fP"
.br
.ti -1c
.RI "class \fBListWith\fP"
.br
.ti -1c
.RI "class \fBPluginNotFoundException\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBaddPlugin\fP (\fBPluginInterface\fP $plugin)"
.br
.ti -1c
.RI "\fBfindPlugin\fP ($method)"
.br
.ti -1c
.RI "\fBinvokePlugin\fP ($method, array $arguments, \fBFilesystemInterface\fP $filesystem)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBPluggableTrait\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "League\\Flysystem\\Plugin\\addPlugin (\fBPluginInterface\fP $plugin)"
Register a plugin\&.
.PP
\fBParameters:\fP
.RS 4
\fI$plugin\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 23 of file PluggableTrait\&.php\&.
.SS "League\\Flysystem\\Plugin\\findPlugin ( $method)\fC [protected]\fP"
Register a plugin\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fILogicException\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPluginInterface\fP $plugin 
.RE
.PP

.PP
Definition at line 39 of file PluggableTrait\&.php\&.
.SS "League\\Flysystem\\Plugin\\invokePlugin ( $method, array $arguments, \fBFilesystemInterface\fP $filesystem)\fC [protected]\fP"
Invoke a plugin by method name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 60 of file PluggableTrait\&.php\&.
.SH "Variable Documentation"
.PP 
.SS "trait PluggableTrait"
\fBInitial value:\fP
.PP
.nf
{
    
    protected $plugins = []
.fi
.PP
Definition at line 10 of file PluggableTrait\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
