.TH "LocalizationTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocalizationTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestGetTranslator\fP ()"
.br
.ti -1c
.RI "\fBtestSetTranslator\fP ()"
.br
.ti -1c
.RI "\fBtestGetLocale\fP ()"
.br
.ti -1c
.RI "\fBtestSetLocale\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansLocalizedInFrench\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansLocalizedInSpanish\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansLocalizedInItalian\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansLocalizedInGerman\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansLocalizedInTurkish\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansLocalizedInDanish\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansLocalizedInLithuanian\fP ()"
.br
.ti -1c
.RI "\fBtestDiffForHumansLocalizedInKorean\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file LocalizationTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testDiffForHumansLocalizedInDanish ()"

.PP
Definition at line 269 of file LocalizationTest\&.php\&.
.SS "testDiffForHumansLocalizedInFrench ()"
The purpose of these tests aren't to test the validitity of the translation but more so to test that the language file exists\&. 
.PP
Definition at line 55 of file LocalizationTest\&.php\&.
.SS "testDiffForHumansLocalizedInGerman ()"

.PP
Definition at line 182 of file LocalizationTest\&.php\&.
.SS "testDiffForHumansLocalizedInItalian ()"

.PP
Definition at line 171 of file LocalizationTest\&.php\&.
.SS "testDiffForHumansLocalizedInKorean ()"

.PP
Definition at line 338 of file LocalizationTest\&.php\&.
.SS "testDiffForHumansLocalizedInLithuanian ()"

.PP
Definition at line 327 of file LocalizationTest\&.php\&.
.SS "testDiffForHumansLocalizedInSpanish ()"

.PP
Definition at line 113 of file LocalizationTest\&.php\&.
.SS "testDiffForHumansLocalizedInTurkish ()"

.PP
Definition at line 211 of file LocalizationTest\&.php\&.
.SS "testGetLocale ()"

.PP
Definition at line 36 of file LocalizationTest\&.php\&.
.SS "testGetTranslator ()"

.PP
Definition at line 18 of file LocalizationTest\&.php\&.
.SS "testSetLocale ()"

.PP
Definition at line 42 of file LocalizationTest\&.php\&.
.SS "testSetTranslator ()"

.PP
Definition at line 25 of file LocalizationTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
