.TH "md_vendor_symfony_debug__symfony__component__debug__c_h_a_n_g_e_l_o_g" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_symfony_debug__symfony__component__debug__c_h_a_n_g_e_l_o_g \- CHANGELOG 

.SS "2\&.6\&.0 "
.PP
.IP "\(bu" 2
generalized ErrorHandler and ExceptionHandler, with some new methods and others deprecated
.IP "\(bu" 2
enhanced error messages for uncaught exceptions
.PP
.PP
.SS "2\&.5\&.0 "
.PP
.IP "\(bu" 2
added ExceptionHandler::setHandler()
.IP "\(bu" 2
added UndefinedMethodFatalErrorHandler
.IP "\(bu" 2
deprecated \fBDummyException\fP
.PP
.PP
.SS "2\&.4\&.0 "
.PP
.IP "\(bu" 2
added a DebugClassLoader able to wrap any autoloader providing a findFile method
.IP "\(bu" 2
improved error messages for not found classes and functions
.PP
.PP
.SS "2\&.3\&.0 "
.PP
.IP "\(bu" 2
added the component 
.PP

