.TH "md_vendor_phpunit_php-text-template__r_e_a_d_m_e" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_phpunit_php-text-template__r_e_a_d_m_e \- \fBText_Template\fP 

.SS "Installation "
.PP
\fBText_Template\fP should be installed using the \fCPEAR Installer\fP\&. This installer is the backbone of PEAR, which provides a distribution system for \fBPHP\fP packages, and is shipped with every release of \fBPHP\fP since version 4\&.3\&.0\&.
.PP
The PEAR channel (\fCpear\&.phpunit\&.de\fP) that is used to distribute \fBText_Template\fP needs to be registered with the local PEAR environment: 
.PP
.nf
sb@ubuntu ~ % pear channel-discover pear.phpunit.de
Adding Channel "pear.phpunit.de" succeeded
Discovery of channel "pear.phpunit.de" succeeded

.fi
.PP
.PP
This has to be done only once\&. Now the PEAR Installer can be used to install packages from the \fBPHPUnit\fP channel: 
.PP
.nf
sb@vmware ~ % pear install phpunit/Text_Template
downloading Text_Template-1.0.0.tgz ...
Starting to download Text_Template-1.0.0.tgz (2,493 bytes)
....done: 2,493 bytes
install ok: channel://pear.phpunit.de/Text_Template-1.0.0

.fi
.PP
.PP
After the installation you can find the \fBText_Template\fP source files inside your local PEAR directory; the path is usually \fC/usr/lib/php/Text\fP\&. 
