.TH "md_vendor_symfony_event-dispatcher__symfony__component__event_dispatcher__c_h_a_n_g_e_l_o_g" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_symfony_event-dispatcher__symfony__component__event_dispatcher__c_h_a_n_g_e_l_o_g \- CHANGELOG 

.SS "2\&.5\&.0 "
.PP
.IP "\(bu" 2
added Debug (originally in HttpKernel)
.IP "\(bu" 2
changed Debug to extend EventDispatcherInterface
.IP "\(bu" 2
added RegisterListenersPass (originally in HttpKernel)
.PP
.PP
.SS "2\&.1\&.0 "
.PP
.IP "\(bu" 2
added TraceableEventDispatcherInterface
.IP "\(bu" 2
added ContainerAwareEventDispatcher
.IP "\(bu" 2
added a reference to the EventDispatcher on the \fBEvent\fP
.IP "\(bu" 2
added a reference to the \fBEvent\fP name on the event
.IP "\(bu" 2
added fluid interface to the \fBdispatch()\fP method which now returns the \fBEvent\fP object
.IP "\(bu" 2
added GenericEvent event class
.IP "\(bu" 2
added the possibility for subscribers to subscribe several times for the same event
.IP "\(bu" 2
added ImmutableEventDispatcher 
.PP

