.TH "md_vendor_symfony_yaml__symfony__component__yaml__c_h_a_n_g_e_l_o_g" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_symfony_yaml__symfony__component__yaml__c_h_a_n_g_e_l_o_g \- CHANGELOG 

.SS "2\&.1\&.0 "
.PP
.IP "\(bu" 2
Yaml::parse() does not evaluate loaded files as \fBPHP\fP files by default anymore (call Yaml::enablePhpParsing() to get back the old behavior) 
.PP

