.TH "md_vendor_jakub-onderka_php-console-highlighter__r_e_a_d_m_e" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_jakub-onderka_php-console-highlighter__r_e_a_d_m_e \- \fBPHP\fP Console Highlighter 
Highlight \fBPHP\fP code in console (terminal)\&.
.PP
.SS "Example "
.PP
.PP
.SS "Install "
.PP
Just create a \fCcomposer\&.json\fP file and run the \fCphp composer\&.phar install\fP command to install it:
.PP
```json { 'require-dev': { 'jakub-onderka/php-console-highlighter': '0\&.*' } } ```
.PP
.SS "Usage "
.PP
```php <?php use \fBJakubOnderka\fP; use \fBJakubOnderka\fP;
.PP
require \fBDIR\fP \&. '/vendor/autoload\&.php';
.PP
$highlighter = new Highlighter(new ConsoleColor());
.PP
$fileContent = file_get_contents(\fBFILE\fP); echo $highlighter->getWholeFile($fileContent); ``` 
