.TH "md_vendor_phpunit_phpunit__change_log-4.0" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_phpunit_phpunit__change_log-4.0 \- Changes in \fBPHPUnit\fP 4\&.0 

.SS "\fBPHPUnit\fP 4\&.0\&.20"
.PP
.IP "\(bu" 2
Fixed \fC#1242\fP: \fC--self-update\fP uses OpenSSL API that is deprecated in \fBPHP\fP 5\&.6
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.19"
.PP
.IP "\(bu" 2
Fixed \fC#1193\fP: Process isolation does not work correctly when \fBPHPUnit\fP is used from PHAR
.IP "\(bu" 2
Fixed a BC break related to comparing \fCDOMNode\fP objects that was introduced in \fBPHPUnit\fP 4\&.0\&.18
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.18"
.PP
.IP "\(bu" 2
Fixed \fC#1218\fP: \fC--self-update\fP destroys symlink
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.17"
.PP
.IP "\(bu" 2
\fCDisplay a message that the PEAR installation method is no longer supported when PHPUnit was installed using the PEAR Installer\fP
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.16"
.PP
.IP "\(bu" 2
\fCFixed handling of the `--report-useless-tests`, `--strict-coverage`, `--disallow-test-output`, and `--enforce-time-limit` options\fP
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.15"
.PP
.IP "\(bu" 2
New release of \fBPHPUnit\fP as PHAR and PEAR package with updated dependencies
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.14"
.PP
.IP "\(bu" 2
New release of \fBPHPUnit\fP as PHAR and PEAR package with updated dependencies
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.13"
.PP
.IP "\(bu" 2
New release of \fBPHPUnit\fP as PHAR and PEAR package with updated dependencies
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.12"
.PP
.IP "\(bu" 2
\fCUse blacklist from PHP_CodeCoverage\fP
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.11"
.PP
.IP "\(bu" 2
\fCFixed unintended autoloader invokation triggered by the `` and `` annotations\fP
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.10"
.PP
.IP "\(bu" 2
New release of \fBPHPUnit\fP as PHAR and PEAR package with updated dependencies (most notably a \fCfix\fP in the mock object generator that caused a \fCperformance regression\fP)
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.9"
.PP
.IP "\(bu" 2
The 'No code coverage will be generated\&.' message was displayed even when code coverage reporting was not requested
.IP "\(bu" 2
Optimized the search for the \fC@before\fP, \fC@after\fP, \fC@beforeClass\fP and \fC@afterClass\fP annotations
.IP "\(bu" 2
Optimized the usage of \fC\fBSebastianBergmann\fP\\\fBEnvironment\fP\\Runtime::canCollectCodeCoverage()\fP
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.8"
.PP
.IP "\(bu" 2
Fixed \fC#1186\fP: \fC@before\fP and \fC@after\fP methods are not called in \fC@dataProvider\fP methods
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.7"
.PP
.IP "\(bu" 2
Removed dependency on \fCphpunit/dbunit\fP in \fCcomposer\&.json\fP that was unintentionally added in \fBPHPUnit\fP 4\&.0\&.6
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.6"
.PP
.IP "\(bu" 2
New release of \fBPHPUnit\fP as PHAR and PEAR package with updated dependencies
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.5"
.PP
.IP "\(bu" 2
New release of \fBPHPUnit\fP as PHAR and PEAR package with updated dependencies
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.4"
.PP
.IP "\(bu" 2
Fixed stacktrace filtering when \fBPHPUnit\fP is used from a PHAR
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.3"
.PP
.IP "\(bu" 2
New release of \fBPHPUnit\fP as PHAR and PEAR package with updated dependencies
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.2"
.PP
.IP "\(bu" 2
Fixed an issue related to displaying \fBPHPUnit\fP's version number
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.1"
.PP
.IP "\(bu" 2
Fixed collection of code coverage data for tests that use a data provider
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.0\&.0"
.PP
.IP "\(bu" 2
Implemented #382: Added the \fC$options\fP parameter to \fC\fBPHPUnit_Framework_TestCase::getMockFromWsdl()\fP\fP for configuring the \fCSoapClient\fP
.IP "\(bu" 2
Implemented #628: Added \fC\fBPHPUnit_Framework_Assert::countOf()\fP, a shortcut to get a\fP\fBPHPUnit_Framework_Constraint_Count\fP\fCinstance\fP
.IP "\(bu" 2
\fCImplemented #711:\fPcoverage-text\fCnow has an XML\fPshowOnlySummary\fCoption\fP
.IP "\(bu" 2
\fCImplemented #719: The\fP--stderr\fCswitch now respects\fP--colors\fCand\fP--debug\fC\fP
.IP "\(bu" 2
\fCImplemented #746: Allow identity checking for non-object types in all asserts that depend on\fPTraversableContains`
.IP "\(bu" 2
Implemented #758: Show a proper stack trace when  fails due to a unexpected exception being thrown
.IP "\(bu" 2
Implemented #773: Recursive and repeated arrays are more gracefully when comparison differences are exported
.IP "\(bu" 2
Implemented #813: Added \fC@before\fP, \fC@after\fP, \fC@beforeClass\fP and \fC@afterClass\fP annotations
.IP "\(bu" 2
Implemented #834: Added the \fC@requires OS\fP annotation
.IP "\(bu" 2
Implemented #835: Printers that extend \fC\fBPHPUnit_TextUI_ResultPrinter\fP\fP should have similar construction
.IP "\(bu" 2
Implemented #838: Added a base test listener
.IP "\(bu" 2
Implemented #859: Added \fBPHP\fP label validation to attribute assertions
.IP "\(bu" 2
Implemented #869: Added support for the adjacent sibling selector (+) to \fC\fBPHPUnit_Util_XML::findNodes()\fP\fP
.IP "\(bu" 2
Implemented #871: Add \fBComparator\fP for DateTime objects
.IP "\(bu" 2
Implemented #877: Added new HTML5 tags to \fC\fBPHPUnit_Util_XML::findNodes()\fP\fP
.IP "\(bu" 2
Added \fC--coverage-crap4j\fP switch to generate code coverage report in Crap4J XML format
.IP "\(bu" 2
\fC\fBassertCount()\fP\fP, \fC\fBassertNotCount()\fP\fP, \fC\fBassertSameSize()\fP\fP, and \fC\fBassertNotSameSize()\fP\fP now support all objects that implement the \fCTraversable\fP interface
.IP "\(bu" 2
\fBA\fP test will now fail in strict mode when it uses the \fC@covers\fP annotation and code that is not expected to be covered is executed
.IP "\(bu" 2
All relative paths in a configuration file are now resolved relative to that configuration file
.IP "\(bu" 2
Fixed #240: XML strings are escaped by removing invalid characters
.IP "\(bu" 2
Fixed #261: \fCsetUp()\fP and \fCsetUpBeforeClass()\fP are run before filters are applied
.IP "\(bu" 2
Fixed #541: Excluded groups are counted towards total number of tests being executed
.IP "\(bu" 2
Fixed #789: \fBPHP\fP INI settings would not be passed to child processes
.IP "\(bu" 2
Fixed #806: Array references are now properly displayed in error output
.IP "\(bu" 2
Fixed #808: Resources are now reported as \fCresource(13) of type (stream)\fP instead of \fCNULL\fP
.IP "\(bu" 2
Fixed #873: \fBPHPUnit\fP suppresses exceptions thrown outside of test case function
.IP "\(bu" 2
Fixed: \fCphpt\fP test cases now use the correct php binary when executed through wrapper scripts 
.PP

