.TH "md_vendor_phpspec_phpspec__c_h_a_n_g_e_s" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_phpspec_phpspec__c_h_a_n_g_e_s \- 2\&.1\&.1 / 2015-01-09 

.IP "\(bu" 2
Smoother rendering for progress bar
.IP "\(bu" 2
Fixed progress bar for case where no examples are found
.IP "\(bu" 2
Tidier output alignment + block width
.IP "\(bu" 2
Removed deprecated calls to Yaml::parse
.IP "\(bu" 2
More accurate lower bounds for composer installation
.PP
.PP
.SH "2\&.1\&.0 / 2014-12-14 "
.PP
.PP
.IP "\(bu" 2
No changes from RC3
.PP
.PP
.SH "2\&.1\&.0-RC3 / 2014-12-04 "
.PP
.PP
.IP "\(bu" 2
Removed minor BC break introduced in RC2
.PP
.PP
.SH "2\&.1\&.0-RC2 / 2014-11-14 "
.PP
.PP
.IP "\(bu" 2
Specify bootstrap file via configuration
.IP "\(bu" 2
Correct error codes while using --stop-on-failure
.IP "\(bu" 2
Better detection of empty specs
.IP "\(bu" 2
Fixed issue where non-spec files in spec folder caused errors
.IP "\(bu" 2
Better PSR-4 support
.PP
.PP
.SH "2\&.1\&.0-RC1 / 2014-09-14 "
.PP
.PP
.IP "\(bu" 2
Allow objects to be instantiated via static factory methods
.IP "\(bu" 2
Automatic generation of return statements using '--fake'
.IP "\(bu" 2
Test suite is automatically rerun when classes or methods have been generated
.IP "\(bu" 2
Allow examples to mark themselves as skipped
.IP "\(bu" 2
PSR-4 support
.IP "\(bu" 2
PSR-0 locator now supports underscores correctly
.IP "\(bu" 2
Ability to specify a custom bootstrap file using '--bootstrap' (for autoloader registration etc)
.IP "\(bu" 2
Ability to have a personal \&.phpspec\&.yml in home folder
.IP "\(bu" 2
Progress bar grows from left to right and flickers less
.IP "\(bu" 2
Improved diffs for object comparison
.IP "\(bu" 2
Throw an exception when construction method is redefined
.IP "\(bu" 2
Non-zero exit code when dependencies are missing
.IP "\(bu" 2
Respect exit code of commands other than 'run'
.IP "\(bu" 2
Higher CLI verbosity levels are handled properly
.IP "\(bu" 2
Code Generation and Stop on \fBFailure\fP are configurable through phpspec\&.yml
.IP "\(bu" 2
Fixes for object instantiation changes in newer versions of \fBPHP\fP
.IP "\(bu" 2
\fBPHP\fP 5\&.6 support
.IP "\(bu" 2
Fixes for progress bar sometimes rounding up to 100% when not all specs passed
.IP "\(bu" 2
Support for non-standard \fBComposer\fP autoloader location
.IP "\(bu" 2
Improved hhvm support
.IP "\(bu" 2
Extensions can now register new command
.IP "\(bu" 2
Resource locator de-duplicates resources (supports custom locators in extensions)
.PP
.PP
.SH "2\&.0\&.1 / 2014-07-01 "
.PP
.PP
.IP "\(bu" 2
Fixed the loading of the autoloader for projects using a custom composer vendor folder
.PP
.PP
.SH "2\&.0\&.0 / 2014-03-19 "
.PP
.PP
.IP "\(bu" 2
Improve support to windows
.IP "\(bu" 2
Improve support to hhvm
.IP "\(bu" 2
Improve acceptance tests coverage with Behat
.PP
.PP
.SH "2\&.0\&.0-RC4 / 2014-02-21 "
.PP
.PP
.IP "\(bu" 2
Revamped junit formatter
.IP "\(bu" 2
Fixed #269 Problem with exception masking and generation for not found class
.IP "\(bu" 2
HHVM is officially supported
.IP "\(bu" 2
Add psr0 validator
.IP "\(bu" 2
Remove Nyan from core
.IP "\(bu" 2
Added an exception if the specified config file does not exist
.IP "\(bu" 2
Fixed a problem with generating a constructor when it is first time added
.IP "\(bu" 2
Improved help
.IP "\(bu" 2
Fixed the suite runner in fast machines
.PP
.PP
.SH "2\&.0\&.0-RC3 / 2014-01-01 "
.PP
.PP
.IP "\(bu" 2
Fixed the \fBProphecy\fP constraint as the new release is 1\&.1
.IP "\(bu" 2
Refactored formatters to be defined as services
.PP
.PP
.SH "2\&.0\&.0-RC2 / 2013-12-30 "
.PP
.PP
.IP "\(bu" 2
Fixed the invocation of methods expecting an argument passed by reference
.IP "\(bu" 2
Fixed the instantiation of the wrapped object in shouldThrow
.PP
.PP
.SH "2\&.0\&.0-RC1 / 2013-12-26 "
.PP
.PP
.IP "\(bu" 2
Bump the \fBProphecy\fP requirement to \fC~1\&.0\&.5@dev\fP
.IP "\(bu" 2
Added a JUnit formatter
.IP "\(bu" 2
Added the \fC--stop-on-failure\fP option
.IP "\(bu" 2
Fixed the support of the \fC--no-interaction\fP option
.IP "\(bu" 2
Added more events to add extension points
.IP "\(bu" 2
Added the number of specs in the console output
.IP "\(bu" 2
Fixed the handling of Windows line endings in the StringEngine and in reading doc comments
.IP "\(bu" 2
Added extension points in the template loading
.IP "\(bu" 2
Added a constructor generator
.IP "\(bu" 2
Added a \fBHTML\fP formatter
.IP "\(bu" 2
Added a nyan cat formatter
.PP
.PP
.SH "2\&.0\&.0beta4 / 2013-05-19 "
.PP
.PP
.IP "\(bu" 2
Add collaborator constructor setter
.IP "\(bu" 2
Fix couple of bugs in \fBProphecy\fP integration layer
.IP "\(bu" 2
New (old) dot formatter
.PP
.PP
.SH "2\&.0\&.0beta3 / 2013-05-01 "
.PP
.PP
.IP "\(bu" 2
Prevent loading of unexisting \fBPHP\fP files
.IP "\(bu" 2
Fix typos in the error messages
.PP
.PP
.SH "2\&.0\&.0beta2 / 2013-04-30 "
.PP
.PP
.IP "\(bu" 2
Bump required \fBProphecy\fP version to 1\&.0\&.1
.IP "\(bu" 2
Support non-string values with ArrayContain matcher
.IP "\(bu" 2
Create \fCsrc\fP folder if does not exist
.IP "\(bu" 2
Fix stack trace and matchers failure printing
.PP
.PP
.SH "2\&.0\&.0beta1 / 2013-04-29 "
.PP
.PP
.IP "\(bu" 2
Initial release 
.PP

