.TH "md_vendor_symfony_event-dispatcher__symfony__component__event_dispatcher__r_e_a_d_m_e" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_symfony_event-dispatcher__symfony__component__event_dispatcher__r_e_a_d_m_e \- EventDispatcher Component 
The \fBSymfony\fP EventDispatcher component implements the Mediator pattern in a simple and effective way to make your projects truly extensible\&.
.PP
```php use \fBSymfony\fP; use \fBSymfony\fP;
.PP
$dispatcher = new EventDispatcher();
.PP
$dispatcher->addListener('event_name', function (\fBEvent\fP $event) { // \&.\&.\&. });
.PP
$dispatcher->dispatch('event_name'); ```
.PP
.SS "Resources "
.PP
You can run the unit tests with the following command: 
.PP
.nf
$ cd path/to/Symfony/Component/EventDispatcher/
$ composer install
$ phpunit
.fi
.PP
 
