.TH "md_vendor_laravel_framework_readme" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_laravel_framework_readme \- \fBLaravel\fP Framework (Kernel) 
\fC![Build Status](https://travis-ci\&.org/laravel/framework\&.svg)\fP \fC![Total Downloads](https://poser\&.pugx\&.org/laravel/framework/downloads\&.svg)\fP \fC![Latest Stable Version](https://poser\&.pugx\&.org/laravel/framework/v/stable\&.svg)\fP \fC![Latest Unstable Version](https://poser\&.pugx\&.org/laravel/framework/v/unstable\&.svg)\fP \fC![License](https://poser\&.pugx\&.org/laravel/framework/license\&.svg)\fP
.PP
.RS 4
\fBNote:\fP This repository contains the core code of the \fBLaravel\fP framework\&. If you want to build an application using \fBLaravel\fP 5, visit the main \fCLaravel repository\fP\&. 
.RE
.PP
.PP
.SS "\fBLaravel\fP \fBPHP\fP Framework"
.PP
\fBLaravel\fP is a web application framework with expressive, elegant syntax\&. We believe development must be an enjoyable, creative experience to be truly fulfilling\&. \fBLaravel\fP attempts to take the pain out of development by easing common tasks used in the majority of web projects, such as authentication, routing, sessions, queueing, and caching\&.
.PP
\fBLaravel\fP is accessible, yet powerful, providing powerful tools needed for large, robust applications\&. \fBA\fP superb inversion of control container, expressive migration system, and tightly integrated unit testing support give you the tools you need to build any application with which you are tasked\&.
.PP
.SS "Official Documentation"
.PP
Documentation for the framework can be found on the \fCLaravel website\fP\&.
.PP
.SS "Contributing"
.PP
Thank you for considering contributing to the \fBLaravel\fP framework! The contribution guide can be found in the \fCLaravel documentation\fP\&.
.PP
.SS "License"
.PP
The \fBLaravel\fP framework is open-sourced software licensed under the \fCMIT license\fP\&. 
