.TH "md_vendor_sebastian_version__change_log" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_sebastian_version__change_log \- \fBVersion\fP 1\&.0 
This is the list of changes for the \fBVersion\fP 1\&.0 release series\&.
.PP
.SS "\fBVersion\fP 1\&.0\&.3"
.PP
.IP "\(bu" 2
Only look for Git repository in the supplied path (and not in its parent directories)\&.
.PP
.PP
.SS "\fBVersion\fP 1\&.0\&.2"
.PP
.IP "\(bu" 2
Errors from \fCexec()\fPuting the Git command are now suppressed\&.
.PP
.PP
.SS "\fBVersion\fP 1\&.0\&.1"
.PP
.IP "\(bu" 2
Fixed #2: \fCgetVersion()\fP fails on Windows\&.
.PP
.PP
.SS "\fBVersion\fP 1\&.0\&.0"
.PP
.IP "\(bu" 2
Initial release\&. 
.PP

