.TH "md_vendor_symfony_yaml__symfony__component__yaml__r_e_a_d_m_e" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_symfony_yaml__symfony__component__yaml__r_e_a_d_m_e \- Yaml Component 
YAML implements most of the YAML 1\&.2 specification\&.
.PP
```php use \fBSymfony\fP;
.PP
$array = Yaml::parse(file_get_contents(filename));
.PP
print Yaml::dump($array); ```
.PP
.SS "Resources "
.PP
You can run the unit tests with the following command: 
.PP
.nf
$ cd path/to/Symfony/Component/Yaml/
$ composer install
$ phpunit
.fi
.PP
 
