.TH "md_vendor_phpunit_phpunit__change_log-4.2" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_phpunit_phpunit__change_log-4.2 \- Changes in \fBPHPUnit\fP 4\&.2 

.SS "\fBPHPUnit\fP 4\&.2\&.5"
.PP
.IP "\(bu" 2
New release of \fBPHPUnit\fP as \fBPHP\fP Archive (PHAR) with updated dependencies
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.2\&.4"
.PP
.IP "\(bu" 2
Fixed \fC#1413\fP: \fC\fBassertCount()\fP\fP hangs in infinite loop on HHVM
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.2\&.3"
.PP
.IP "\(bu" 2
Fixed \fC#1403\fP: \fCphpunit --self-update\fP does not work
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.2\&.2"
.PP
.IP "\(bu" 2
Fixed \fC#1399\fP: \fCenforceTimeLimit\fP configuration option is not handled
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.2\&.1"
.PP
.IP "\(bu" 2
Fixed \fC#1380\fP: \fCassertMatch()\fP returns \fCUnexpected end tag : hr\fP
.IP "\(bu" 2
Fixed \fC#1390\fP: Licensing issue with third-party components bundled in PHAR distribution
.PP
.PP
.SS "\fBPHPUnit\fP 4\&.2\&.0"
.PP
.IP "\(bu" 2
Tests annotated with `
.PP
\fBTodo\fP
.RS 4
\fCwill now be reported as risky when the\fP--disallow-todo-tests\fCoption is used or\fPbeStrictAboutTodoAnnotatedTests=true\fCis set in the configuration file\fP
.RE
.PP

.PP

