.TH "md_vendor_phpunit_phpunit__change_log-4.5" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_vendor_phpunit_phpunit__change_log-4.5 \- Changes in \fBPHPUnit\fP 4\&.5 

.SS "\fBPHPUnit\fP 4\&.5\&.0"
.PP
.IP "\(bu" 2
Added out-of-the-box support for \fCProphecy\fP
.IP "\(bu" 2
Implemented \fC#137\fP: Add support for variable number of tests shown per line in default result printer
.IP "\(bu" 2
Merged \fC#1478\fP: Improve the performance of \fC\fBPHPUnit_Framework_Constraint_IsEqual\fP\fP (which is used by \fC\fBassertEquals()\fP\fP, for instance) for the most common case
.IP "\(bu" 2
Fixed \fC#1474\fP: Allow the registration of custom comparators for \fC\fBassertEquals()\fP\fP et al\&. (again)
.IP "\(bu" 2
\fCDeprecated\fP the \fC--strict\fP commandline option and the XML configuration's \fCstrict\fP attribute 
.PP

