.TH "MethodCallback" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MethodCallback \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnonStaticCallback\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBstaticCallback\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file MethodCallback\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "nonStaticCallback ()"

.PP
Definition at line 13 of file MethodCallback\&.php\&.
.SS "static staticCallback ()\fC [static]\fP"

.PP
Definition at line 4 of file MethodCallback\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
