.TH "Mockable" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mockable \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($arg1=NULL, $arg2=NULL)"
.br
.ti -1c
.RI "\fBmockableMethod\fP ()"
.br
.ti -1c
.RI "\fBanotherMockableMethod\fP ()"
.br
.ti -1c
.RI "\fB__clone\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$constructorArgs\fP"
.br
.ti -1c
.RI "\fB$cloned\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file Mockable\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $arg1 = \fCNULL\fP,  $arg2 = \fCNULL\fP)"

.PP
Definition at line 7 of file Mockable\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__clone ()"

.PP
Definition at line 24 of file Mockable\&.php\&.
.SS "anotherMockableMethod ()"

.PP
Definition at line 18 of file Mockable\&.php\&.
.SS "mockableMethod ()"

.PP
Definition at line 12 of file Mockable\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$cloned"

.PP
Definition at line 5 of file Mockable\&.php\&.
.SS "$constructorArgs"

.PP
Definition at line 4 of file Mockable\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
