.TH "DummyHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummyHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Handler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBemit\fP (self, record)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class is a logger handler. It doesn't do anything
.fi
.PP
 
.PP
Definition at line 79 of file utils\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self)"

.PP
.nf
Constructor
.fi
.PP
 
.PP
Definition at line 82 of file utils\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def emit ( self,  record)"

.PP
.nf
do nothinbg with the given record
.fi
.PP
 
.PP
Definition at line 86 of file utils\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
