.TH "modbus_tk.simulator_rpc_client" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
modbus_tk.simulator_rpc_client \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSimulatorRpcClient\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBmodbus_simu\fP = \fBSimulatorRpcClient\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple modbus_simu = \fBSimulatorRpcClient\fP()"

.PP
Definition at line 106 of file simulator_rpc_client\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
