.TH "RpcHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RpcHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseRequestHandler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBhandle\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
An instance of this class is created every time an RPC call is received by the server
.fi
.PP
 
.PP
Definition at line 75 of file simulator\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def handle ( self)"

.PP
.nf
This function is called automatically by the SocketServer
.fi
.PP
 
.PP
Definition at line 78 of file simulator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
