.TH "MongoDBFormatter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MongoDBFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFormatterInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($maxNestingLevel=3, $exceptionTraceAsString=true)"
.br
.ti -1c
.RI "\fBformat\fP (array $record)"
.br
.ti -1c
.RI "\fBformatBatch\fP (array $records)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBformatArray\fP (array $record, $nestingLevel=0)"
.br
.ti -1c
.RI "\fBformatObject\fP ($value, $nestingLevel)"
.br
.ti -1c
.RI "\fBformatException\fP (\\Exception $exception, $nestingLevel)"
.br
.ti -1c
.RI "\fBformatDate\fP (\\DateTime $value, $nestingLevel)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Formats a record for use with the MongoDBHandler\&.
.PP
\fBAuthor:\fP
.RS 4
Florian Plattner me@florianplattner.de 
.RE
.PP

.PP
Definition at line 19 of file MongoDBFormatter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $maxNestingLevel = \fC3\fP,  $exceptionTraceAsString = \fCtrue\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$maxNestingLevel\fP 0 means infinite nesting, the $record itself is level 1, $record['context'] is 2 
.br
\fI$exceptionTraceAsString\fP set to false to log exception traces as a sub documents instead of strings 
.RE
.PP

.PP
Definition at line 28 of file MongoDBFormatter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "format (array $record)"

.PP
Implements \fBFormatterInterface\fP\&.
.PP
Definition at line 37 of file MongoDBFormatter\&.php\&.
.SS "formatArray (array $record,  $nestingLevel = \fC0\fP)\fC [protected]\fP"

.PP
Definition at line 54 of file MongoDBFormatter\&.php\&.
.SS "formatBatch (array $records)"

.PP
Implements \fBFormatterInterface\fP\&.
.PP
Definition at line 45 of file MongoDBFormatter\&.php\&.
.SS "formatDate (\\DateTime $value,  $nestingLevel)\fC [protected]\fP"

.PP
Definition at line 101 of file MongoDBFormatter\&.php\&.
.SS "formatException (\\Exception $exception,  $nestingLevel)\fC [protected]\fP"

.PP
Definition at line 83 of file MongoDBFormatter\&.php\&.
.SS "formatObject ( $value,  $nestingLevel)\fC [protected]\fP"

.PP
Definition at line 75 of file MongoDBFormatter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
