.TH "MailHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MailHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractProcessingHandler\fP\&.
.PP
Inherited by \fBMandrillHandler\fP, \fBNativeMailerHandler\fP, and \fBSwiftMailerHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhandleBatch\fP (array $records)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsend\fP ($content, array $records)"
.br
.ti -1c
.RI "\fBwrite\fP (array $record)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Base class for all mail handlers
.PP
\fBAuthor:\fP
.RS 4
Gyula Sallai 
.RE
.PP

.PP
Definition at line 19 of file MailHandler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "handleBatch (array $records)"
{} 
.PP
Implements \fBHandlerInterface\fP\&.
.PP
Definition at line 24 of file MailHandler\&.php\&.
.SS "send ( $content, array $records)\fC [abstract]\fP, \fC [protected]\fP"
Send a mail with the given content
.PP
\fBParameters:\fP
.RS 4
\fI$content\fP formatted email body to be sent 
.br
\fI$records\fP the array of log records that formed this content 
.RE
.PP

.SS "write (array $record)\fC [protected]\fP"
{} 
.PP
Definition at line 51 of file MailHandler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
