.TH "LogEntriesHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogEntriesHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSocketHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($token, $useSSL=true, $level=\fBLogger::DEBUG\fP, $bubble=true)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgenerateDataStream\fP ($record)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$logToken\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Robert Kaufmann III rok3@rok3.me 
.RE
.PP

.PP
Definition at line 19 of file LogEntriesHandler\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $token,  $useSSL = \fCtrue\fP,  $level = \fC\fBLogger::DEBUG\fP\fP,  $bubble = \fCtrue\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$token\fP \fBLog\fP token supplied by LogEntries 
.br
\fI$useSSL\fP Whether or not SSL encryption should be used\&. 
.br
\fI$level\fP The minimum logging level to trigger this handler 
.br
\fI$bubble\fP Whether or not messages that are handled should bubble up the stack\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMissingExtensionException\fP\fP If SSL encryption is set to true and OpenSSL is missing 
.RE
.PP

.PP
Definition at line 34 of file LogEntriesHandler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "generateDataStream ( $record)\fC [protected]\fP"
{}
.PP
\fBParameters:\fP
.RS 4
\fI$record\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 51 of file LogEntriesHandler\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$logToken\fC [protected]\fP"

.PP
Definition at line 24 of file LogEntriesHandler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
