.TH "CouchDBHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CouchDBHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractProcessingHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $\fBoptions\fP=array(), $level=\fBLogger::DEBUG\fP, $bubble=true)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwrite\fP (array $record)"
.br
.ti -1c
.RI "\fBgetDefaultFormatter\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
CouchDB handler
.PP
\fBAuthor:\fP
.RS 4
Markus Bachmann markus.bachmann@bachi.biz 
.RE
.PP

.PP
Definition at line 22 of file CouchDBHandler\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $options = \fCarray()\fP,  $level = \fC\fBLogger::DEBUG\fP\fP,  $bubble = \fCtrue\fP)"

.PP
Definition at line 26 of file CouchDBHandler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDefaultFormatter ()\fC [protected]\fP"

.PP
Definition at line 68 of file CouchDBHandler\&.php\&.
.SS "write (array $record)\fC [protected]\fP"

.PP
Definition at line 42 of file CouchDBHandler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
