.TH "GroupHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GroupHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructorOnlyTakesHandler\fP ()"
.br
.ti -1c
.RI "\fBtestHandle\fP ()"
.br
.ti -1c
.RI "\fBtestHandleBatch\fP ()"
.br
.ti -1c
.RI "\fBtestIsHandling\fP ()"
.br
.ti -1c
.RI "\fBtestHandleUsesProcessors\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file GroupHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstructorOnlyTakesHandler ()"
\fBMonolog\fP::__construct  InvalidArgumentException 
.PP
Definition at line 23 of file GroupHandlerTest\&.php\&.
.SS "testHandle ()"
\fBMonolog\fP::__construct  \fBMonolog\fP::handle 
.PP
Definition at line 32 of file GroupHandlerTest\&.php\&.
.SS "testHandleBatch ()"
\fBMonolog\fP::handleBatch 
.PP
Definition at line 48 of file GroupHandlerTest\&.php\&.
.SS "testHandleUsesProcessors ()"
\fBMonolog\fP::handle 
.PP
Definition at line 75 of file GroupHandlerTest\&.php\&.
.SS "testIsHandling ()"
\fBMonolog\fP::isHandling 
.PP
Definition at line 63 of file GroupHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
