.TH "FilterHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestIsHandling\fP ()"
.br
.ti -1c
.RI "\fBtestHandleProcessOnlyNeededLevels\fP ()"
.br
.ti -1c
.RI "\fBtestAcceptedLevelApi\fP ()"
.br
.ti -1c
.RI "\fBtestHandleUsesProcessors\fP ()"
.br
.ti -1c
.RI "\fBtestHandleRespectsBubble\fP ()"
.br
.ti -1c
.RI "\fBtestHandleWithCallback\fP ()"
.br
.ti -1c
.RI "\fBtestHandleWithBadCallbackThrowsException\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file FilterHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAcceptedLevelApi ()"
\fBMonolog\fP::setAcceptedLevels  \fBMonolog\fP::getAcceptedLevels 
.PP
Definition at line 84 of file FilterHandlerTest\&.php\&.
.SS "testHandleProcessOnlyNeededLevels ()"
\fBMonolog\fP::handle  \fBMonolog\fP::setAcceptedLevels  \fBMonolog\fP::isHandling 
.PP
Definition at line 41 of file FilterHandlerTest\&.php\&.
.SS "testHandleRespectsBubble ()"
\fBMonolog\fP::handle 
.PP
Definition at line 127 of file FilterHandlerTest\&.php\&.
.SS "testHandleUsesProcessors ()"
\fBMonolog\fP::handle 
.PP
Definition at line 107 of file FilterHandlerTest\&.php\&.
.SS "testHandleWithBadCallbackThrowsException ()"
\fBMonolog\fP::handle   
.PP
Definition at line 161 of file FilterHandlerTest\&.php\&.
.SS "testHandleWithCallback ()"
\fBMonolog\fP::handle 
.PP
Definition at line 143 of file FilterHandlerTest\&.php\&.
.SS "testIsHandling ()"
\fBMonolog\fP::isHandling 
.PP
Definition at line 22 of file FilterHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
