.TH "SyslogUdpHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyslogUdpHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractSyslogHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($host, $port=514, $facility=LOG_USER, $level=\fBLogger::DEBUG\fP, $bubble=true)"
.br
.ti -1c
.RI "\fBclose\fP ()"
.br
.ti -1c
.RI "\fBsetSocket\fP ($socket)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwrite\fP (array $record)"
.br
.ti -1c
.RI "\fBmakeCommonSyslogHeader\fP ($severity)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP \fBHandler\fP for logging to a remote syslogd server\&.
.PP
\fBAuthor:\fP
.RS 4
Jesper Skovgaard Nielsen nulpunkt@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file SyslogUdpHandler\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $host,  $port = \fC514\fP,  $facility = \fCLOG_USER\fP,  $level = \fC\fBLogger::DEBUG\fP\fP,  $bubble = \fCtrue\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$host\fP 
.br
\fI$port\fP 
.br
\fI$facility\fP 
.br
\fI$level\fP The minimum logging level at which this handler will be triggered 
.br
\fI$bubble\fP Whether the messages that are handled can bubble up the stack or not 
.RE
.PP

.PP
Definition at line 31 of file SyslogUdpHandler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "close ()"

.PP
Definition at line 49 of file SyslogUdpHandler\&.php\&.
.SS "makeCommonSyslogHeader ( $severity)\fC [protected]\fP"
Make common syslog header (see rfc5424) 
.PP
Definition at line 66 of file SyslogUdpHandler\&.php\&.
.SS "setSocket ( $socket)"
Inject your own socket, mainly used for testing 
.PP
Definition at line 76 of file SyslogUdpHandler\&.php\&.
.SS "write (array $record)\fC [protected]\fP"

.PP
Definition at line 38 of file SyslogUdpHandler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
