.TH "FormatterInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FormatterInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBChromePHPFormatter\fP, \fBFlowdockFormatter\fP, \fBJsonFormatter\fP, \fBMongoDBFormatter\fP, \fBNormalizerFormatter\fP, and \fBNormalizerFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat\fP (array $record)"
.br
.ti -1c
.RI "\fBformatBatch\fP (array $records)"
.br
.ti -1c
.RI "\fBformat\fP (array $record)"
.br
.ti -1c
.RI "\fBformatBatch\fP (array $records)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for formatters
.PP
\fBAuthor:\fP
.RS 4
Jordi Boggiano j.boggiano@seld.be 
.RE
.PP

.PP
Definition at line 12668 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "format (array $record)"
Formats a log record\&.
.PP
\fBParameters:\fP
.RS 4
\fI$record\fP \fBA\fP record to format 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed The formatted record 
.RE
.PP

.PP
Implemented in \fBLineFormatter\fP, \fBNormalizerFormatter\fP, \fBHtmlFormatter\fP, \fBLogstashFormatter\fP, \fBLineFormatter\fP, \fBGelfMessageFormatter\fP, \fBJsonFormatter\fP, \fBElasticaFormatter\fP, \fBFlowdockFormatter\fP, \fBWildfireFormatter\fP, \fBNormalizerFormatter\fP, \fBChromePHPFormatter\fP, \fBLogglyFormatter\fP, \fBMongoDBFormatter\fP, and \fBScalarFormatter\fP\&.
.SS "format (array $record)"

.PP
Implemented in \fBLineFormatter\fP, \fBNormalizerFormatter\fP, \fBHtmlFormatter\fP, \fBLogstashFormatter\fP, \fBLineFormatter\fP, \fBGelfMessageFormatter\fP, \fBJsonFormatter\fP, \fBElasticaFormatter\fP, \fBFlowdockFormatter\fP, \fBWildfireFormatter\fP, \fBNormalizerFormatter\fP, \fBChromePHPFormatter\fP, \fBLogglyFormatter\fP, \fBMongoDBFormatter\fP, and \fBScalarFormatter\fP\&.
.SS "formatBatch (array $records)"
Formats a set of log records\&.
.PP
\fBParameters:\fP
.RS 4
\fI$records\fP \fBA\fP set of records to format 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed The formatted set of records 
.RE
.PP

.PP
Implemented in \fBLineFormatter\fP, \fBNormalizerFormatter\fP, \fBHtmlFormatter\fP, \fBLineFormatter\fP, \fBWildfireFormatter\fP, \fBFlowdockFormatter\fP, \fBJsonFormatter\fP, \fBChromePHPFormatter\fP, \fBNormalizerFormatter\fP, and \fBMongoDBFormatter\fP\&.
.SS "formatBatch (array $records)"

.PP
Implemented in \fBLineFormatter\fP, \fBNormalizerFormatter\fP, \fBHtmlFormatter\fP, \fBLineFormatter\fP, \fBWildfireFormatter\fP, \fBFlowdockFormatter\fP, \fBJsonFormatter\fP, \fBChromePHPFormatter\fP, \fBNormalizerFormatter\fP, and \fBMongoDBFormatter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
