.TH "DoctrineCouchDBHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DoctrineCouchDBHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractProcessingHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (CouchDBClient $client, $level=\fBLogger::DEBUG\fP, $bubble=true)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwrite\fP (array $record)"
.br
.ti -1c
.RI "\fBgetDefaultFormatter\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
CouchDB handler for \fBDoctrine\fP CouchDB ODM
.PP
\fBAuthor:\fP
.RS 4
Markus Bachmann markus.bachmann@bachi.biz 
.RE
.PP

.PP
Definition at line 23 of file DoctrineCouchDBHandler\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (CouchDBClient $client,  $level = \fC\fBLogger::DEBUG\fP\fP,  $bubble = \fCtrue\fP)"

.PP
Definition at line 27 of file DoctrineCouchDBHandler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDefaultFormatter ()\fC [protected]\fP"

.PP
Definition at line 41 of file DoctrineCouchDBHandler\&.php\&.
.SS "write (array $record)\fC [protected]\fP"

.PP
Definition at line 36 of file DoctrineCouchDBHandler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
