.TH "DynamoDbHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DynamoDbHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractProcessingHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (DynamoDbClient $client, $table, $level=\fBLogger::DEBUG\fP, $bubble=true)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBDATE_FORMAT\fP = 'Y-m-d\\TH:i:s\&.uO'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwrite\fP (array $record)"
.br
.ti -1c
.RI "\fBfilterEmptyFields\fP (array $record)"
.br
.ti -1c
.RI "\fBgetDefaultFormatter\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$client\fP"
.br
.ti -1c
.RI "\fB$table\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Amazon DynamoDB handler (http://aws.amazon.com/dynamodb/)
.PP
\fBAndrew Lawson adlawson@gmail.com \fP
.PP
Definition at line 25 of file DynamoDbHandler\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (DynamoDbClient $client,  $table,  $level = \fC\fBLogger::DEBUG\fP\fP,  $bubble = \fCtrue\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$client\fP 
.br
\fI$table\fP 
.br
\fI$level\fP 
.br
\fI$bubble\fP 
.RE
.PP

.PP
Definition at line 45 of file DynamoDbHandler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "filterEmptyFields (array $record)\fC [protected]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$record\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 75 of file DynamoDbHandler\&.php\&.
.SS "getDefaultFormatter ()\fC [protected]\fP"
{} 
.PP
Definition at line 85 of file DynamoDbHandler\&.php\&.
.SS "write (array $record)\fC [protected]\fP"
{} 
.PP
Definition at line 60 of file DynamoDbHandler\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$client\fC [protected]\fP"

.PP
Definition at line 32 of file DynamoDbHandler\&.php\&.
.SS "$table\fC [protected]\fP"

.PP
Definition at line 37 of file DynamoDbHandler\&.php\&.
.SS "const DATE_FORMAT = 'Y-m-d\\TH:i:s\&.uO'"

.PP
Definition at line 27 of file DynamoDbHandler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
