.TH "ActivationStrategyInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ActivationStrategyInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBChannelLevelActivationStrategy\fP, and \fBErrorLevelActivationStrategy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBisHandlerActivated\fP (array $record)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface for activation strategies for the \fBFingersCrossedHandler\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Johannes M\&. Schmitt schmittjoh@gmail.com 
.RE
.PP

.PP
Definition at line 19 of file ActivationStrategyInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "isHandlerActivated (array $record)"
Returns whether the given record activates the handler\&.
.PP
\fBParameters:\fP
.RS 4
\fI$record\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Boolean 
.RE
.PP

.PP
Implemented in \fBChannelLevelActivationStrategy\fP, and \fBErrorLevelActivationStrategy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
