.TH "TagProcessor" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagProcessor \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $tags=array())"
.br
.ti -1c
.RI "\fB__invoke\fP (array $record)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adds a tags array into record
.PP
\fBAuthor:\fP
.RS 4
Martijn Riemers 
.RE
.PP

.PP
Definition at line 19 of file TagProcessor\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $tags = \fCarray()\fP)"

.PP
Definition at line 23 of file TagProcessor\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__invoke (array $record)"

.PP
Definition at line 28 of file TagProcessor\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
