.TH "WildfireFormatter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WildfireFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNormalizerFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat\fP (array $record)"
.br
.ti -1c
.RI "\fBformatBatch\fP (array $records)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBTABLE\fP = 'table'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBnormalize\fP ($\fBdata\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Serializes a log message according to Wildfire's header requirements
.PP
\fBAuthor:\fP
.RS 4
Eric Clemmons () eric@uxdriven.com 
.PP
Christophe Coevoet stof@notk.org 
.PP
Kirill chEbba Chebunin iam@chebba.org 
.RE
.PP

.PP
Definition at line 23 of file WildfireFormatter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "format (array $record)"
{} 
.PP
Implements \fBFormatterInterface\fP\&.
.PP
Definition at line 44 of file WildfireFormatter\&.php\&.
.SS "formatBatch (array $records)"

.PP
Implements \fBFormatterInterface\fP\&.
.PP
Definition at line 100 of file WildfireFormatter\&.php\&.
.SS "normalize ( $data)\fC [protected]\fP"

.PP
Definition at line 105 of file WildfireFormatter\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const TABLE = 'table'"

.PP
Definition at line 25 of file WildfireFormatter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
