.TH "LogglyFormatterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogglyFormatterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstruct\fP ()"
.br
.ti -1c
.RI "\fBtestFormat\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file LogglyFormatterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstruct ()"
\fBMonolog\fP::__construct 
.PP
Definition at line 21 of file LogglyFormatterTest\&.php\&.
.SS "testFormat ()"
\fBMonolog\fP\fBformat\fP 
.PP
Definition at line 32 of file LogglyFormatterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
