.TH "NewRelicHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewRelicHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestThehandlerThrowsAnExceptionIfTheNRExtensionIsNotLoaded\fP ()"
.br
.ti -1c
.RI "\fBtestThehandlerCanHandleTheRecord\fP ()"
.br
.ti -1c
.RI "\fBtestThehandlerCanAddContextParamsToTheNewRelicTrace\fP ()"
.br
.ti -1c
.RI "\fBtestThehandlerCanAddExplodedContextParamsToTheNewRelicTrace\fP ()"
.br
.ti -1c
.RI "\fBtestThehandlerCanAddExtraParamsToTheNewRelicTrace\fP ()"
.br
.ti -1c
.RI "\fBtestThehandlerCanAddExplodedExtraParamsToTheNewRelicTrace\fP ()"
.br
.ti -1c
.RI "\fBtestThehandlerCanAddExtraContextAndParamsToTheNewRelicTrace\fP ()"
.br
.ti -1c
.RI "\fBtestTheAppNameIsNullByDefault\fP ()"
.br
.ti -1c
.RI "\fBtestTheAppNameCanBeInjectedFromtheConstructor\fP ()"
.br
.ti -1c
.RI "\fBtestTheAppNameCanBeOverriddenFromEachLog\fP ()"
.br
.ti -1c
.RI "\fBtestTheTransactionNameIsNullByDefault\fP ()"
.br
.ti -1c
.RI "\fBtestTheTransactionNameCanBeInjectedFromTheConstructor\fP ()"
.br
.ti -1c
.RI "\fBtestTheTransactionNameCanBeOverriddenFromEachLog\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fB$appname\fP"
.br
.ti -1c
.RI "static \fB$customParameters\fP"
.br
.ti -1c
.RI "static \fB$transactionName\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file NewRelicHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()"

.PP
Definition at line 23 of file NewRelicHandlerTest\&.php\&.
.SS "testTheAppNameCanBeInjectedFromtheConstructor ()"

.PP
Definition at line 115 of file NewRelicHandlerTest\&.php\&.
.SS "testTheAppNameCanBeOverriddenFromEachLog ()"

.PP
Definition at line 123 of file NewRelicHandlerTest\&.php\&.
.SS "testTheAppNameIsNullByDefault ()"

.PP
Definition at line 107 of file NewRelicHandlerTest\&.php\&.
.SS "testThehandlerCanAddContextParamsToTheNewRelicTrace ()"

.PP
Definition at line 45 of file NewRelicHandlerTest\&.php\&.
.SS "testThehandlerCanAddExplodedContextParamsToTheNewRelicTrace ()"

.PP
Definition at line 52 of file NewRelicHandlerTest\&.php\&.
.SS "testThehandlerCanAddExplodedExtraParamsToTheNewRelicTrace ()"

.PP
Definition at line 77 of file NewRelicHandlerTest\&.php\&.
.SS "testThehandlerCanAddExtraContextAndParamsToTheNewRelicTrace ()"

.PP
Definition at line 91 of file NewRelicHandlerTest\&.php\&.
.SS "testThehandlerCanAddExtraParamsToTheNewRelicTrace ()"

.PP
Definition at line 66 of file NewRelicHandlerTest\&.php\&.
.SS "testThehandlerCanHandleTheRecord ()"

.PP
Definition at line 39 of file NewRelicHandlerTest\&.php\&.
.SS "testThehandlerThrowsAnExceptionIfTheNRExtensionIsNotLoaded ()"
\fBMonolog\fP 
.PP
Definition at line 33 of file NewRelicHandlerTest\&.php\&.
.SS "testTheTransactionNameCanBeInjectedFromTheConstructor ()"

.PP
Definition at line 139 of file NewRelicHandlerTest\&.php\&.
.SS "testTheTransactionNameCanBeOverriddenFromEachLog ()"

.PP
Definition at line 147 of file NewRelicHandlerTest\&.php\&.
.SS "testTheTransactionNameIsNullByDefault ()"

.PP
Definition at line 131 of file NewRelicHandlerTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$appname\fC [static]\fP"

.PP
Definition at line 19 of file NewRelicHandlerTest\&.php\&.
.SS "$customParameters\fC [static]\fP"

.PP
Definition at line 20 of file NewRelicHandlerTest\&.php\&.
.SS "$transactionName\fC [static]\fP"

.PP
Definition at line 21 of file NewRelicHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
