.TH "ChromePHPFormatter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChromePHPFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFormatterInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat\fP (array $record)"
.br
.ti -1c
.RI "\fBformatBatch\fP (array $records)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Formats a log message according to the ChromePHP array format
.PP
\fBAuthor:\fP
.RS 4
Christophe Coevoet stof@notk.org 
.RE
.PP

.PP
Definition at line 21 of file ChromePHPFormatter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "format (array $record)"
{} 
.PP
Implements \fBFormatterInterface\fP\&.
.PP
Definition at line 40 of file ChromePHPFormatter\&.php\&.
.SS "formatBatch (array $records)"

.PP
Implements \fBFormatterInterface\fP\&.
.PP
Definition at line 69 of file ChromePHPFormatter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
