.TH "RedisHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RedisHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructorShouldThrowExceptionForInvalidRedis\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorShouldWorkWithPredis\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorShouldWorkWithRedis\fP ()"
.br
.ti -1c
.RI "\fBtestPredisHandle\fP ()"
.br
.ti -1c
.RI "\fBtestRedisHandle\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file RedisHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstructorShouldThrowExceptionForInvalidRedis ()"
InvalidArgumentException 
.PP
Definition at line 23 of file RedisHandlerTest\&.php\&.
.SS "testConstructorShouldWorkWithPredis ()"

.PP
Definition at line 28 of file RedisHandlerTest\&.php\&.
.SS "testConstructorShouldWorkWithRedis ()"

.PP
Definition at line 34 of file RedisHandlerTest\&.php\&.
.SS "testPredisHandle ()"

.PP
Definition at line 40 of file RedisHandlerTest\&.php\&.
.SS "testRedisHandle ()"

.PP
Definition at line 56 of file RedisHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
