.TH "TestFooNorm" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestFooNorm \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$foo\fP = '\fBfoo\fP'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 223 of file NormalizerFormatterTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBfoo\fP = '\fBfoo\fP'"

.PP
Definition at line 225 of file NormalizerFormatterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
