.TH "LineFormatterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LineFormatterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestDefFormatWithString\fP ()"
.br
.ti -1c
.RI "\fBtestDefFormatWithArrayContext\fP ()"
.br
.ti -1c
.RI "\fBtestDefFormatExtras\fP ()"
.br
.ti -1c
.RI "\fBtestFormatExtras\fP ()"
.br
.ti -1c
.RI "\fBtestContextAndExtraOptionallyNotShownIfEmpty\fP ()"
.br
.ti -1c
.RI "\fBtestDefFormatWithObject\fP ()"
.br
.ti -1c
.RI "\fBtestDefFormatWithException\fP ()"
.br
.ti -1c
.RI "\fBtestDefFormatWithPreviousException\fP ()"
.br
.ti -1c
.RI "\fBtestBatchFormat\fP ()"
.br
.ti -1c
.RI "\fBtestFormatShouldStripInlineLineBreaks\fP ()"
.br
.ti -1c
.RI "\fBtestFormatShouldNotStripInlineLineBreaksWhenFlagIsSet\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBMonolog\fP 
.PP
Definition at line 17 of file LineFormatterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testBatchFormat ()"

.PP
Definition at line 144 of file LineFormatterTest\&.php\&.
.SS "testContextAndExtraOptionallyNotShownIfEmpty ()"

.PP
Definition at line 80 of file LineFormatterTest\&.php\&.
.SS "testDefFormatExtras ()"

.PP
Definition at line 52 of file LineFormatterTest\&.php\&.
.SS "testDefFormatWithArrayContext ()"

.PP
Definition at line 33 of file LineFormatterTest\&.php\&.
.SS "testDefFormatWithException ()"

.PP
Definition at line 109 of file LineFormatterTest\&.php\&.
.SS "testDefFormatWithObject ()"

.PP
Definition at line 94 of file LineFormatterTest\&.php\&.
.SS "testDefFormatWithPreviousException ()"

.PP
Definition at line 126 of file LineFormatterTest\&.php\&.
.SS "testDefFormatWithString ()"

.PP
Definition at line 19 of file LineFormatterTest\&.php\&.
.SS "testFormatExtras ()"

.PP
Definition at line 66 of file LineFormatterTest\&.php\&.
.SS "testFormatShouldNotStripInlineLineBreaksWhenFlagIsSet ()"

.PP
Definition at line 182 of file LineFormatterTest\&.php\&.
.SS "testFormatShouldStripInlineLineBreaks ()"

.PP
Definition at line 168 of file LineFormatterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
