.TH "RavenHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RavenHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractProcessingHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (Raven_Client $ravenClient, $level=\fBLogger::DEBUG\fP, $bubble=true)"
.br
.ti -1c
.RI "\fBhandleBatch\fP (array $records)"
.br
.ti -1c
.RI "\fBsetBatchFormatter\fP (\fBFormatterInterface\fP $formatter)"
.br
.ti -1c
.RI "\fBgetBatchFormatter\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwrite\fP (array $record)"
.br
.ti -1c
.RI "\fBgetDefaultFormatter\fP ()"
.br
.ti -1c
.RI "\fBgetDefaultBatchFormatter\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$ravenClient\fP"
.br
.ti -1c
.RI "\fB$batchFormatter\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBHandler\fP to send messages to a Sentry (https://github.com/getsentry/sentry) server using raven-php (https://github.com/getsentry/raven-php)
.PP
\fBAuthor:\fP
.RS 4
Marc Abramowitz marc@marc-abramowitz.com 
.RE
.PP

.PP
Definition at line 25 of file RavenHandler\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (Raven_Client $ravenClient,  $level = \fC\fBLogger::DEBUG\fP\fP,  $bubble = \fCtrue\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$ravenClient\fP 
.br
\fI$level\fP The minimum logging level at which this handler will be triggered 
.br
\fI$bubble\fP Whether the messages that are handled can bubble up the stack or not 
.RE
.PP

.PP
Definition at line 56 of file RavenHandler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getBatchFormatter ()"
Gets the formatter for the logs generated by \fBhandleBatch()\fP\&.
.PP
\fBReturns:\fP
.RS 4
FormatterInterface 
.RE
.PP

.PP
Definition at line 116 of file RavenHandler\&.php\&.
.SS "getDefaultBatchFormatter ()\fC [protected]\fP"
Gets the default formatter for the logs generated by \fBhandleBatch()\fP\&.
.PP
\fBReturns:\fP
.RS 4
FormatterInterface 
.RE
.PP

.PP
Definition at line 183 of file RavenHandler\&.php\&.
.SS "getDefaultFormatter ()\fC [protected]\fP"

.PP
Definition at line 173 of file RavenHandler\&.php\&.
.SS "\fBLineFormatter\fP The formatter \fBto\fP use \fBfor\fP the \fBlogs\fP generated via handleBatch (array $records)"
{} 
.PP
Implements \fBHandlerInterface\fP\&.
.PP
Definition at line 66 of file RavenHandler\&.php\&.
.SS "setBatchFormatter (\fBFormatterInterface\fP $formatter)"
Sets the formatter for the logs generated by \fBhandleBatch()\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$formatter\fP 
.RE
.PP

.PP
Definition at line 106 of file RavenHandler\&.php\&.
.SS "write (array $record)\fC [protected]\fP"
{} 
.PP
Definition at line 128 of file RavenHandler\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$batchFormatter\fC [protected]\fP"

.PP
Definition at line 49 of file RavenHandler\&.php\&.
.SS "$ravenClient\fC [protected]\fP"

.PP
Definition at line 44 of file RavenHandler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
