.TH "PushoverHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PushoverHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestWriteHeader\fP ()"
.br
.ti -1c
.RI "\fBtestWriteContent\fP ($content)"
.br
.ti -1c
.RI "\fBtestWriteWithComplexTitle\fP ()"
.br
.ti -1c
.RI "\fBtestWriteWithComplexMessage\fP ()"
.br
.ti -1c
.RI "\fBtestWriteWithTooLongMessage\fP ()"
.br
.ti -1c
.RI "\fBtestWriteWithHighPriority\fP ()"
.br
.ti -1c
.RI "\fBtestWriteWithEmergencyPriority\fP ()"
.br
.ti -1c
.RI "\fBtestWriteToMultipleUsers\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Almost all examples (expected header, titles, messages) taken from https://www.pushover.net/api 
.PP
\fBAuthor:\fP
.RS 4
Sebastian Göttschkes sebastian.goettschkes@googlemail.com 
.RE
.PP
\fBSee also:\fP
.RS 4
https://www.pushover.net/api 
.RE
.PP

.PP
Definition at line 23 of file PushoverHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testWriteContent ( $content)"
testWriteHeader 
.PP
Definition at line 44 of file PushoverHandlerTest\&.php\&.
.SS "testWriteHeader ()"

.PP
Definition at line 28 of file PushoverHandlerTest\&.php\&.
.SS "testWriteToMultipleUsers ()"

.PP
Definition at line 104 of file PushoverHandlerTest\&.php\&.
.SS "testWriteWithComplexMessage ()"

.PP
Definition at line 59 of file PushoverHandlerTest\&.php\&.
.SS "testWriteWithComplexTitle ()"

.PP
Definition at line 49 of file PushoverHandlerTest\&.php\&.
.SS "testWriteWithEmergencyPriority ()"

.PP
Definition at line 94 of file PushoverHandlerTest\&.php\&.
.SS "testWriteWithHighPriority ()"

.PP
Definition at line 84 of file PushoverHandlerTest\&.php\&.
.SS "testWriteWithTooLongMessage ()"

.PP
Definition at line 70 of file PushoverHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
