.TH "JsonFormatterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonFormatterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstruct\fP ()"
.br
.ti -1c
.RI "\fBtestFormat\fP ()"
.br
.ti -1c
.RI "\fBtestFormatBatch\fP ()"
.br
.ti -1c
.RI "\fBtestFormatBatchNewlines\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file JsonFormatterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstruct ()"
\fBMonolog\fP::__construct  \fBMonolog\fP::getBatchMode  \fBMonolog\fP::isAppendingNewlines 
.PP
Definition at line 24 of file JsonFormatterTest\&.php\&.
.SS "testFormat ()"
\fBMonolog\fP\fBformat\fP 
.PP
Definition at line 37 of file JsonFormatterTest\&.php\&.
.SS "testFormatBatch ()"
\fBMonolog\fP::formatBatch  \fBMonolog\fP::formatBatchJson 
.PP
Definition at line 52 of file JsonFormatterTest\&.php\&.
.SS "testFormatBatchNewlines ()"
\fBMonolog\fP::formatBatch  \fBMonolog\fP::formatBatchNewlines 
.PP
Definition at line 66 of file JsonFormatterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
