.TH "LogEntriesHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogEntriesHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestWriteContent\fP ()"
.br
.ti -1c
.RI "\fBtestWriteBatchContent\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Robert Kaufmann III rok3@rok3.me 
.RE
.PP

.PP
Definition at line 20 of file LogEntriesHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testWriteBatchContent ()"

.PP
Definition at line 43 of file LogEntriesHandlerTest\&.php\&.
.SS "testWriteContent ()"

.PP
Definition at line 32 of file LogEntriesHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
