.TH "LogstashFormatter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogstashFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNormalizerFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($applicationName, $systemName=null, $extraPrefix=null, $contextPrefix= 'ctxt_', $\fBversion\fP=self::V0)"
.br
.ti -1c
.RI "\fBformat\fP (array $record)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBV0\fP = 0"
.br
.ti -1c
.RI "const \fBV1\fP = 1"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBformatV0\fP (array $record)"
.br
.ti -1c
.RI "\fBformatV1\fP (array $record)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$systemName\fP"
.br
.ti -1c
.RI "\fB$applicationName\fP"
.br
.ti -1c
.RI "\fB$extraPrefix\fP"
.br
.ti -1c
.RI "\fB$contextPrefix\fP"
.br
.ti -1c
.RI "\fB$version\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Serializes a log message to Logstash \fBEvent\fP Format
.PP
\fBSee also:\fP
.RS 4
http://logstash.net/ 
.PP
https://github.com/logstash/logstash/blob/master/lib/logstash/event.rb
.RE
.PP
\fBAuthor:\fP
.RS 4
Tim Mower timothy.mower@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file LogstashFormatter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $applicationName,  $systemName = \fCnull\fP,  $extraPrefix = \fCnull\fP,  $contextPrefix = \fC'ctxt_'\fP,  $version = \fCself::V0\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$applicationName\fP the application that sends the data, used as the 'type' field of logstash 
.br
\fI$systemName\fP the system/machine name, used as the 'source' field of logstash, defaults to the hostname of the machine 
.br
\fI$extraPrefix\fP prefix for extra keys inside logstash 'fields' 
.br
\fI$contextPrefix\fP prefix for context keys inside logstash 'fields', defaults to ctxt_ 
.RE
.PP

.PP
Definition at line 58 of file LogstashFormatter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "format (array $record)"
{} 
.PP
Implements \fBFormatterInterface\fP\&.
.PP
Definition at line 73 of file LogstashFormatter\&.php\&.
.SS "formatV0 (array $record)\fC [protected]\fP"

.PP
Definition at line 86 of file LogstashFormatter\&.php\&.
.SS "formatV1 (array $record)\fC [protected]\fP"

.PP
Definition at line 129 of file LogstashFormatter\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$applicationName\fC [protected]\fP"

.PP
Definition at line 35 of file LogstashFormatter\&.php\&.
.SS "$contextPrefix\fC [protected]\fP"

.PP
Definition at line 45 of file LogstashFormatter\&.php\&.
.SS "$extraPrefix\fC [protected]\fP"

.PP
Definition at line 40 of file LogstashFormatter\&.php\&.
.SS "$systemName\fC [protected]\fP"

.PP
Definition at line 30 of file LogstashFormatter\&.php\&.
.SS "$\fBversion\fP\fC [protected]\fP"

.PP
Definition at line 50 of file LogstashFormatter\&.php\&.
.SS "const V0 = 0"

.PP
Definition at line 24 of file LogstashFormatter\&.php\&.
.SS "const V1 = 1"

.PP
Definition at line 25 of file LogstashFormatter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
