.TH "ZendMonitorHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZendMonitorHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestWrite\fP ()"
.br
.ti -1c
.RI "\fBtestGetDefaultFormatterReturnsNormalizerFormatter\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$zendMonitorHandler\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 15 of file ZendMonitorHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()"

.PP
Definition at line 19 of file ZendMonitorHandlerTest\&.php\&.
.SS "testGetDefaultFormatterReturnsNormalizerFormatter ()"
\fBMonolog\fP::getDefaultFormatter 
.PP
Definition at line 64 of file ZendMonitorHandlerTest\&.php\&.
.SS "testWrite ()"
\fBMonolog\fP::write 
.PP
Definition at line 29 of file ZendMonitorHandlerTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$zendMonitorHandler\fC [protected]\fP"

.PP
Definition at line 17 of file ZendMonitorHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
