.TH "FlowdockHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlowdockHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSocketHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($apiToken, $level=\fBLogger::DEBUG\fP, $bubble=true)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwrite\fP (array $record)"
.br
.ti -1c
.RI "\fBgenerateDataStream\fP ($record)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$apiToken\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sends notifications through the Flowdock push API
.PP
This must be configured with a FlowdockFormatter instance via \fBsetFormatter()\fP
.PP
Notes: API token - Flowdock API token
.PP
\fBAuthor:\fP
.RS 4
Dominik Liebler liebler.dominik@gmail.com 
.RE
.PP
\fBSee also:\fP
.RS 4
https://www.flowdock.com/api/push 
.RE
.PP

.PP
Definition at line 27 of file FlowdockHandler\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $apiToken,  $level = \fC\fBLogger::DEBUG\fP\fP,  $bubble = \fCtrue\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$apiToken\fP 
.br
\fI$level\fP The minimum logging level at which this handler will be triggered 
.br
\fI$bubble\fP Whether the messages that are handled can bubble up the stack or not
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBMissingExtensionException\fP\fP if OpenSSL is missing 
.RE
.PP

.PP
Definition at line 41 of file FlowdockHandler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "generateDataStream ( $record)\fC [protected]\fP"
{}
.PP
\fBParameters:\fP
.RS 4
\fI$record\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 69 of file FlowdockHandler\&.php\&.
.SS "write (array $record)\fC [protected]\fP"
{}
.PP
\fBParameters:\fP
.RS 4
\fI$record\fP 
.RE
.PP

.PP
Definition at line 56 of file FlowdockHandler\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$apiToken\fC [protected]\fP"

.PP
Definition at line 32 of file FlowdockHandler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
