.TH "vendor/monolog/monolog/tests/Monolog/Handler/NewRelicHandlerTest.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/monolog/monolog/tests/Monolog/Handler/NewRelicHandlerTest.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBNewRelicHandlerTest\fP"
.br
.ti -1c
.RI "class \fBStubNewRelicHandlerWithoutExtension\fP"
.br
.ti -1c
.RI "class \fBStubNewRelicHandler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMonolog\\Handler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBnewrelic_notice_error\fP ()"
.br
.ti -1c
.RI "\fBnewrelic_set_appname\fP ($appname)"
.br
.ti -1c
.RI "\fBnewrelic_name_transaction\fP ($transactionName)"
.br
.ti -1c
.RI "\fBnewrelic_add_custom_parameter\fP ($key, $value)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
