.TH "vendor/symfony/process/Symfony/Component/Process/Tests/NonStopableProcess.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/process/Symfony/Component/Process/Tests/NonStopableProcess.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBhandleSignal\fP ($signal)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$duration\fP = isset($argv[1]) ? (int) $argv[1] : 3"
.br
.ti -1c
.RI "\fB$start\fP = microtime(true)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "handleSignal ( $signal)"

.PP
Definition at line 10 of file NonStopableProcess\&.php\&.
.SH "Variable Documentation"
.PP 
.SS "$\fBduration\fP = isset($argv[1]) ? (int) $argv[1] : 3"

.PP
Definition at line 31 of file NonStopableProcess\&.php\&.
.SS "$start = microtime(true)"

.PP
Definition at line 32 of file NonStopableProcess\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
