.TH "Extender" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Extender \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBaz\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 9 of file classExtendsNamespacedClass\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
