.TH "PHP_CodeCoverage_Exception" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Exception \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException\&.
.PP
Inherited by \fBPHP_CodeCoverage_Exception_UnintentionallyCoveredCode\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 22 of file Exception\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
