.TH "PHP_CodeCoverage_Report_XML_Node" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Report_XML_Node \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPHP_CodeCoverage_Report_XML_Directory\fP, and \fBPHP_CodeCoverage_Report_XML_Project\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (DOMElement $context)"
.br
.ti -1c
.RI "\fBgetDom\fP ()"
.br
.ti -1c
.RI "\fBgetTotals\fP ()"
.br
.ti -1c
.RI "\fBaddDirectory\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBaddFile\fP ($\fBname\fP, $href)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetContextNode\fP (DOMElement $context)"
.br
.ti -1c
.RI "\fBgetContextNode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file Node\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (DOMElement $context)"

.PP
Definition at line 32 of file Node\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addDirectory ( $name)"

.PP
Definition at line 69 of file Node\&.php\&.
.SS "addFile ( $name,  $href)"

.PP
Definition at line 82 of file Node\&.php\&.
.SS "getContextNode ()\fC [protected]\fP"

.PP
Definition at line 48 of file Node\&.php\&.
.SS "getDom ()"

.PP
Definition at line 43 of file Node\&.php\&.
.SS "getTotals ()"

.PP
Definition at line 53 of file Node\&.php\&.
.SS "setContextNode (DOMElement $context)\fC [protected]\fP"

.PP
Definition at line 37 of file Node\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
