.TH "PHP_CodeCoverage_Report_Node_Directory" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Report_Node_Directory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHP_CodeCoverage_Report_Node\fP, and IteratorAggregate\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcount\fP ()"
.br
.ti -1c
.RI "\fBgetIterator\fP ()"
.br
.ti -1c
.RI "\fBaddDirectory\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBaddFile\fP ($\fBname\fP, array $coverageData, array $testData, $cacheTokens)"
.br
.ti -1c
.RI "\fBgetDirectories\fP ()"
.br
.ti -1c
.RI "\fBgetFiles\fP ()"
.br
.ti -1c
.RI "\fBgetChildNodes\fP ()"
.br
.ti -1c
.RI "\fBgetClasses\fP ()"
.br
.ti -1c
.RI "\fBgetTraits\fP ()"
.br
.ti -1c
.RI "\fBgetFunctions\fP ()"
.br
.ti -1c
.RI "\fBgetLinesOfCode\fP ()"
.br
.ti -1c
.RI "\fBgetNumExecutableLines\fP ()"
.br
.ti -1c
.RI "\fBgetNumExecutedLines\fP ()"
.br
.ti -1c
.RI "\fBgetNumClasses\fP ()"
.br
.ti -1c
.RI "\fBgetNumTestedClasses\fP ()"
.br
.ti -1c
.RI "\fBgetNumTraits\fP ()"
.br
.ti -1c
.RI "\fBgetNumTestedTraits\fP ()"
.br
.ti -1c
.RI "\fBgetNumMethods\fP ()"
.br
.ti -1c
.RI "\fBgetNumTestedMethods\fP ()"
.br
.ti -1c
.RI "\fBgetNumFunctions\fP ()"
.br
.ti -1c
.RI "\fBgetNumTestedFunctions\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$children\fP = array()"
.br
.ti -1c
.RI "\fB$directories\fP = array()"
.br
.ti -1c
.RI "\fB$files\fP = array()"
.br
.ti -1c
.RI "\fB$classes\fP"
.br
.ti -1c
.RI "\fB$traits\fP"
.br
.ti -1c
.RI "\fB$functions\fP"
.br
.ti -1c
.RI "\fB$linesOfCode\fP = null"
.br
.ti -1c
.RI "\fB$numFiles\fP = -1"
.br
.ti -1c
.RI "\fB$numExecutableLines\fP = -1"
.br
.ti -1c
.RI "\fB$numExecutedLines\fP = -1"
.br
.ti -1c
.RI "\fB$numClasses\fP = -1"
.br
.ti -1c
.RI "\fB$numTestedClasses\fP = -1"
.br
.ti -1c
.RI "\fB$numTraits\fP = -1"
.br
.ti -1c
.RI "\fB$numTestedTraits\fP = -1"
.br
.ti -1c
.RI "\fB$numMethods\fP = -1"
.br
.ti -1c
.RI "\fB$numTestedMethods\fP = -1"
.br
.ti -1c
.RI "\fB$numFunctions\fP = -1"
.br
.ti -1c
.RI "\fB$numTestedFunctions\fP = -1"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Directory\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addDirectory ( $name)"
Adds a new directory\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHP_CodeCoverage_Report_Node_Directory\fP 
.RE
.PP

.PP
Definition at line 151 of file Directory\&.php\&.
.SS "addFile ( $name, array $coverageData, array $testData,  $cacheTokens)"
Adds a new file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$coverageData\fP 
.br
\fI$testData\fP 
.br
\fI$cacheTokens\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHP_CodeCoverage_Report_Node_File\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPHP_CodeCoverage_Exception\fP\fP 
.RE
.PP

.PP
Definition at line 171 of file Directory\&.php\&.
.SS "count ()"
Returns the number of files in/under this node\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 119 of file Directory\&.php\&.
.SS "getChildNodes ()"
Returns the child nodes of this node\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 215 of file Directory\&.php\&.
.SS "getClasses ()"
Returns the classes of this node\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 225 of file Directory\&.php\&.
.SS "getDirectories ()"
Returns the directories in this directory\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 195 of file Directory\&.php\&.
.SS "getFiles ()"
Returns the files in this directory\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 205 of file Directory\&.php\&.
.SS "getFunctions ()"
Returns the functions of this node\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 267 of file Directory\&.php\&.
.SS "getIterator ()"
Returns an iterator for this node\&.
.PP
\fBReturns:\fP
.RS 4
RecursiveIteratorIterator 
.RE
.PP

.PP
Definition at line 137 of file Directory\&.php\&.
.SS "getLinesOfCode ()"
Returns the LOC/CLOC/NCLOC of this node\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 288 of file Directory\&.php\&.
.SS "getNumClasses ()"
Returns the number of classes\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 346 of file Directory\&.php\&.
.SS "getNumExecutableLines ()"
Returns the number of executable lines\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 310 of file Directory\&.php\&.
.SS "getNumExecutedLines ()"
Returns the number of executed lines\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 328 of file Directory\&.php\&.
.SS "getNumFunctions ()"
Returns the number of functions\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 454 of file Directory\&.php\&.
.SS "getNumMethods ()"
Returns the number of methods\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 418 of file Directory\&.php\&.
.SS "getNumTestedClasses ()"
Returns the number of tested classes\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 364 of file Directory\&.php\&.
.SS "getNumTestedFunctions ()"
Returns the number of tested functions\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 472 of file Directory\&.php\&.
.SS "getNumTestedMethods ()"
Returns the number of tested methods\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 436 of file Directory\&.php\&.
.SS "getNumTestedTraits ()"
Returns the number of tested traits\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 400 of file Directory\&.php\&.
.SS "getNumTraits ()"
Returns the number of traits\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 382 of file Directory\&.php\&.
.SS "getTraits ()"
Returns the traits of this node\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 246 of file Directory\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$children = array()\fC [protected]\fP"

.PP
Definition at line 27 of file Directory\&.php\&.
.SS "$classes\fC [protected]\fP"

.PP
Definition at line 42 of file Directory\&.php\&.
.SS "$directories = array()\fC [protected]\fP"

.PP
Definition at line 32 of file Directory\&.php\&.
.SS "$files = array()\fC [protected]\fP"

.PP
Definition at line 37 of file Directory\&.php\&.
.SS "$functions\fC [protected]\fP"

.PP
Definition at line 52 of file Directory\&.php\&.
.SS "$linesOfCode = null\fC [protected]\fP"

.PP
Definition at line 57 of file Directory\&.php\&.
.SS "$numClasses = -1\fC [protected]\fP"

.PP
Definition at line 77 of file Directory\&.php\&.
.SS "$numExecutableLines = -1\fC [protected]\fP"

.PP
Definition at line 67 of file Directory\&.php\&.
.SS "$numExecutedLines = -1\fC [protected]\fP"

.PP
Definition at line 72 of file Directory\&.php\&.
.SS "$numFiles = -1\fC [protected]\fP"

.PP
Definition at line 62 of file Directory\&.php\&.
.SS "$numFunctions = -1\fC [protected]\fP"

.PP
Definition at line 107 of file Directory\&.php\&.
.SS "$numMethods = -1\fC [protected]\fP"

.PP
Definition at line 97 of file Directory\&.php\&.
.SS "$numTestedClasses = -1\fC [protected]\fP"

.PP
Definition at line 82 of file Directory\&.php\&.
.SS "$numTestedFunctions = -1\fC [protected]\fP"

.PP
Definition at line 112 of file Directory\&.php\&.
.SS "$numTestedMethods = -1\fC [protected]\fP"

.PP
Definition at line 102 of file Directory\&.php\&.
.SS "$numTestedTraits = -1\fC [protected]\fP"

.PP
Definition at line 92 of file Directory\&.php\&.
.SS "$numTraits = -1\fC [protected]\fP"

.PP
Definition at line 87 of file Directory\&.php\&.
.SS "$traits\fC [protected]\fP"

.PP
Definition at line 47 of file Directory\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
