.TH "PHP_CodeCoverage_Report_Factory" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Report_Factory \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreate\fP (\fBPHP_CodeCoverage\fP $coverage)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Factory\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "create (\fBPHP_CodeCoverage\fP $coverage)"

.PP
\fBParameters:\fP
.RS 4
\fI$coverage\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHP_CodeCoverage_Report_Node_Directory\fP 
.RE
.PP

.PP
Definition at line 28 of file Factory\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
