.TH "PHP_Token_Includes" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_Token_Includes \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHP_Token\fP\&.
.PP
Inherited by \fBPHP_Token_INCLUDE\fP, \fBPHP_Token_INCLUDE_ONCE\fP, \fBPHP_Token_REQUIRE\fP, and \fBPHP_Token_REQUIRE_ONCE\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 223 of file Token\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getName ()"

.PP
Definition at line 228 of file Token\&.php\&.
.SS "getType ()"

.PP
Definition at line 246 of file Token\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBname\fP\fC [protected]\fP"

.PP
Definition at line 225 of file Token\&.php\&.
.SS "$type\fC [protected]\fP"

.PP
Definition at line 226 of file Token\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
