.TH "PHP_Token_InterfaceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_Token_InterfaceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestGetName\fP ()"
.br
.ti -1c
.RI "\fBtestGetParentNotExists\fP ()"
.br
.ti -1c
.RI "\fBtestHasParentNotExists\fP ()"
.br
.ti -1c
.RI "\fBtestGetParentExists\fP ()"
.br
.ti -1c
.RI "\fBtestHasParentExists\fP ()"
.br
.ti -1c
.RI "\fBtestGetInterfacesExists\fP ()"
.br
.ti -1c
.RI "\fBtestHasInterfacesExists\fP ()"
.br
.ti -1c
.RI "\fBtestGetPackageNamespace\fP ()"
.br
.ti -1c
.RI "\fBprovideFilesWithClassesWithinMultipleNamespaces\fP ()"
.br
.ti -1c
.RI "\fBtestGetPackageNamespaceForFileWithMultipleNamespaces\fP ($filepath)"
.br
.ti -1c
.RI "\fBtestGetPackageNamespaceIsEmptyForInterfacesThatAreNotWithinNamespaces\fP ()"
.br
.ti -1c
.RI "\fBtestGetPackageNamespaceWhenExtentingFromNamespaceClass\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$class\fP"
.br
.ti -1c
.RI "\fB$interfaces\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file InterfaceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provideFilesWithClassesWithinMultipleNamespaces ()"

.PP
Definition at line 128 of file InterfaceTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 29 of file InterfaceTest\&.php\&.
.SS "testGetInterfacesExists ()"
\fBPHP_Token_INTERFACE::getInterfaces\fP 
.PP
Definition at line 97 of file InterfaceTest\&.php\&.
.SS "testGetName ()"
\fBPHP_Token_INTERFACE::getName\fP 
.PP
Definition at line 47 of file InterfaceTest\&.php\&.
.SS "testGetPackageNamespace ()"
\fBPHP_Token_INTERFACE::getPackage\fP 
.PP
Definition at line 117 of file InterfaceTest\&.php\&.
.SS "testGetPackageNamespaceForFileWithMultipleNamespaces ( $filepath)"
provideFilesWithClassesWithinMultipleNamespaces  \fBPHP_Token_INTERFACE::getPackage\fP 
.PP
Definition at line 139 of file InterfaceTest\&.php\&.
.SS "testGetPackageNamespaceIsEmptyForInterfacesThatAreNotWithinNamespaces ()"

.PP
Definition at line 161 of file InterfaceTest\&.php\&.
.SS "testGetPackageNamespaceWhenExtentingFromNamespaceClass ()"
\fBPHP_Token_INTERFACE::getPackage\fP 
.PP
Definition at line 171 of file InterfaceTest\&.php\&.
.SS "testGetParentExists ()"
\fBPHP_Token_INTERFACE::getParent\fP 
.PP
Definition at line 77 of file InterfaceTest\&.php\&.
.SS "testGetParentNotExists ()"
\fBPHP_Token_INTERFACE::getParent\fP 
.PP
Definition at line 57 of file InterfaceTest\&.php\&.
.SS "testHasInterfacesExists ()"
\fBPHP_Token_INTERFACE::hasInterfaces\fP 
.PP
Definition at line 108 of file InterfaceTest\&.php\&.
.SS "testHasParentExists ()"
\fBPHP_Token_INTERFACE::hasParent\fP 
.PP
Definition at line 87 of file InterfaceTest\&.php\&.
.SS "testHasParentNotExists ()"
\fBPHP_Token_INTERFACE::hasParent\fP 
.PP
Definition at line 67 of file InterfaceTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$class\fC [protected]\fP"

.PP
Definition at line 26 of file InterfaceTest\&.php\&.
.SS "$interfaces\fC [protected]\fP"

.PP
Definition at line 27 of file InterfaceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
