.TH "PHP_CodeCoverage_Report_HTML_Renderer_Dashboard" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Report_HTML_Renderer_Dashboard \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHP_CodeCoverage_Report_HTML_Renderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrender\fP (\fBPHP_CodeCoverage_Report_Node_Directory\fP $\fBnode\fP, $file)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcomplexity\fP (array $classes, $baseLink)"
.br
.ti -1c
.RI "\fBcoverageDistribution\fP (array $classes)"
.br
.ti -1c
.RI "\fBinsufficientCoverage\fP (array $classes, $baseLink)"
.br
.ti -1c
.RI "\fBprojectRisks\fP (array $classes, $baseLink)"
.br
.ti -1c
.RI "\fBgetActiveBreadcrumb\fP (\fBPHP_CodeCoverage_Report_Node\fP $\fBnode\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file Dashboard\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "complexity (array $classes,  $baseLink)\fC [protected]\fP"
Returns the data for the Class/Method Complexity charts\&.
.PP
\fBParameters:\fP
.RS 4
\fI$classes\fP 
.br
\fI$baseLink\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 68 of file Dashboard\&.php\&.
.SS "coverageDistribution (array $classes)\fC [protected]\fP"
Returns the data for the Class / Method Coverage Distribution chart\&.
.PP
\fBParameters:\fP
.RS 4
\fI$classes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 112 of file Dashboard\&.php\&.
.SS "getActiveBreadcrumb (\fBPHP_CodeCoverage_Report_Node\fP $node)\fC [protected]\fP"

.PP
Definition at line 293 of file Dashboard\&.php\&.
.SS "insufficientCoverage (array $classes,  $baseLink)\fC [protected]\fP"
Returns the classes / methods with insufficient coverage\&.
.PP
\fBParameters:\fP
.RS 4
\fI$classes\fP 
.br
\fI$baseLink\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 182 of file Dashboard\&.php\&.
.SS "projectRisks (array $classes,  $baseLink)\fC [protected]\fP"
Returns the project risks according to the CRAP index\&.
.PP
\fBParameters:\fP
.RS 4
\fI$classes\fP 
.br
\fI$baseLink\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 240 of file Dashboard\&.php\&.
.SS "render (\fBPHP_CodeCoverage_Report_Node_Directory\fP $node,  $file)"

.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.br
\fI$file\fP 
.RE
.PP

.PP
Definition at line 28 of file Dashboard\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
