.TH "PHP_CodeCoverage_Report_XML_Directory" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Report_XML_Directory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHP_CodeCoverage_Report_XML_Node\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file Directory\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
