.TH "PHP_CodeCoverage_Report_HTML_Renderer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Report_HTML_Renderer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPHP_CodeCoverage_Report_HTML_Renderer_Dashboard\fP, \fBPHP_CodeCoverage_Report_HTML_Renderer_Directory\fP, and \fBPHP_CodeCoverage_Report_HTML_Renderer_File\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($templatePath, $generator, $date, $lowUpperBound, $highLowerBound)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBrenderItemTemplate\fP (\fBText_Template\fP $template, array $\fBdata\fP)"
.br
.ti -1c
.RI "\fBsetCommonTemplateVariables\fP (\fBText_Template\fP $template, \fBPHP_CodeCoverage_Report_Node\fP $\fBnode\fP)"
.br
.ti -1c
.RI "\fBgetBreadcrumbs\fP (\fBPHP_CodeCoverage_Report_Node\fP $\fBnode\fP)"
.br
.ti -1c
.RI "\fBgetActiveBreadcrumb\fP (\fBPHP_CodeCoverage_Report_Node\fP $\fBnode\fP)"
.br
.ti -1c
.RI "\fBgetInactiveBreadcrumb\fP (\fBPHP_CodeCoverage_Report_Node\fP $\fBnode\fP, $pathToRoot)"
.br
.ti -1c
.RI "\fBgetPathToRoot\fP (\fBPHP_CodeCoverage_Report_Node\fP $\fBnode\fP)"
.br
.ti -1c
.RI "\fBgetCoverageBar\fP ($percent)"
.br
.ti -1c
.RI "\fBgetColorLevel\fP ($percent)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$templatePath\fP"
.br
.ti -1c
.RI "\fB$generator\fP"
.br
.ti -1c
.RI "\fB$date\fP"
.br
.ti -1c
.RI "\fB$lowUpperBound\fP"
.br
.ti -1c
.RI "\fB$highLowerBound\fP"
.br
.ti -1c
.RI "\fB$version\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file Renderer\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $templatePath,  $generator,  $date,  $lowUpperBound,  $highLowerBound)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$templatePath\fP 
.br
\fI$generator\fP 
.br
\fI$date\fP 
.br
\fI$lowUpperBound\fP 
.br
\fI$highLowerBound\fP 
.RE
.PP

.PP
Definition at line 65 of file Renderer\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getActiveBreadcrumb (\fBPHP_CodeCoverage_Report_Node\fP $node)\fC [protected]\fP"

.PP
Definition at line 208 of file Renderer\&.php\&.
.SS "getBreadcrumbs (\fBPHP_CodeCoverage_Report_Node\fP $node)\fC [protected]\fP"

.PP
Definition at line 179 of file Renderer\&.php\&.
.SS "getColorLevel ( $percent)\fC [protected]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$percent\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 263 of file Renderer\&.php\&.
.SS "getCoverageBar ( $percent)\fC [protected]\fP"

.PP
Definition at line 244 of file Renderer\&.php\&.
.SS "getInactiveBreadcrumb (\fBPHP_CodeCoverage_Report_Node\fP $node,  $pathToRoot)\fC [protected]\fP"

.PP
Definition at line 222 of file Renderer\&.php\&.
.SS "getPathToRoot (\fBPHP_CodeCoverage_Report_Node\fP $node)\fC [protected]\fP"

.PP
Definition at line 231 of file Renderer\&.php\&.
.SS "renderItemTemplate (\fBText_Template\fP $template, array $data)\fC [protected]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$template\fP 
.br
\fI$data\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 82 of file Renderer\&.php\&.
.SS "setCommonTemplateVariables (\fBText_Template\fP $template, \fBPHP_CodeCoverage_Report_Node\fP $node)\fC [protected]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$template\fP 
.br
\fI$node\fP 
.RE
.PP

.PP
Definition at line 157 of file Renderer\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$date\fC [protected]\fP"

.PP
Definition at line 39 of file Renderer\&.php\&.
.SS "$generator\fC [protected]\fP"

.PP
Definition at line 34 of file Renderer\&.php\&.
.SS "$highLowerBound\fC [protected]\fP"

.PP
Definition at line 49 of file Renderer\&.php\&.
.SS "$lowUpperBound\fC [protected]\fP"

.PP
Definition at line 44 of file Renderer\&.php\&.
.SS "$templatePath\fC [protected]\fP"

.PP
Definition at line 29 of file Renderer\&.php\&.
.SS "$\fBversion\fP\fC [protected]\fP"

.PP
Definition at line 54 of file Renderer\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
