.TH "PHP_Token_Stream_CachingFactory" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_Token_Stream_CachingFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBget\fP ($filename)"
.br
.ti -1c
.RI "static \fBclear\fP ($filename=NULL)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$cache\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP caching factory for token stream objects\&.
.PP
\fBAuthor:\fP
.RS 4
Sebastian Bergmann sebastian@phpunit.de 
.RE
.PP
\fBCopyright:\fP
.RS 4
Sebastian Bergmann sebastian@phpunit.de  http://www.opensource.org/licenses/BSD-3-Clause The BSD 3-Clause License 
.RE
.PP
\fBVersion:\fP
.RS 4
Release: @ \fBClass available since Release 1\&.0\&.0 \fP
.RE
.PP

.PP
Definition at line 21 of file CachingFactory\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static clear ( $filename = \fCNULL\fP)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$filename\fP 
.RE
.PP

.PP
Definition at line 44 of file CachingFactory\&.php\&.
.SS "static get ( $filename)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$filename\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHP_Token_Stream\fP 
.RE
.PP

.PP
Definition at line 32 of file CachingFactory\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$cache = array()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 26 of file CachingFactory\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
