.TH "PHP_Token_FUNCTION" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_Token_FUNCTION \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHP_TokenWithScopeAndVisibility\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetArguments\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetCCN\fP ()"
.br
.ti -1c
.RI "\fBgetSignature\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$arguments\fP"
.br
.ti -1c
.RI "\fB$ccn\fP"
.br
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$signature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 254 of file Token\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getArguments ()"

.PP
Definition at line 261 of file Token\&.php\&.
.SS "getCCN ()"

.PP
Definition at line 335 of file Token\&.php\&.
.SS "getName ()"

.PP
Definition at line 293 of file Token\&.php\&.
.SS "getSignature ()"

.PP
Definition at line 368 of file Token\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$arguments\fC [protected]\fP"

.PP
Definition at line 256 of file Token\&.php\&.
.SS "$ccn\fC [protected]\fP"

.PP
Definition at line 257 of file Token\&.php\&.
.SS "$\fBname\fP\fC [protected]\fP"

.PP
Definition at line 258 of file Token\&.php\&.
.SS "$signature\fC [protected]\fP"

.PP
Definition at line 259 of file Token\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
