.TH "PHP_CodeCoverage_Report_XML_Totals" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Report_XML_Totals \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (DOMElement $container)"
.br
.ti -1c
.RI "\fBgetContainer\fP ()"
.br
.ti -1c
.RI "\fBsetNumLines\fP ($loc, $cloc, $ncloc, $executable, $executed)"
.br
.ti -1c
.RI "\fBsetNumClasses\fP ($count, $tested)"
.br
.ti -1c
.RI "\fBsetNumTraits\fP ($count, $tested)"
.br
.ti -1c
.RI "\fBsetNumMethods\fP ($count, $tested)"
.br
.ti -1c
.RI "\fBsetNumFunctions\fP ($count, $tested)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file Totals\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (DOMElement $container)"

.PP
Definition at line 52 of file Totals\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getContainer ()"

.PP
Definition at line 90 of file Totals\&.php\&.
.SS "setNumClasses ( $count,  $tested)"

.PP
Definition at line 108 of file Totals\&.php\&.
.SS "setNumFunctions ( $count,  $tested)"

.PP
Definition at line 138 of file Totals\&.php\&.
.SS "setNumLines ( $loc,  $cloc,  $ncloc,  $executable,  $executed)"

.PP
Definition at line 95 of file Totals\&.php\&.
.SS "setNumMethods ( $count,  $tested)"

.PP
Definition at line 128 of file Totals\&.php\&.
.SS "setNumTraits ( $count,  $tested)"

.PP
Definition at line 118 of file Totals\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
