.TH "PHP_CodeCoverage_Report_Crap4j" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CodeCoverage_Report_Crap4j \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprocess\fP (\fBPHP_CodeCoverage\fP $coverage, $target=null, $\fBname\fP=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file Crap4j\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "process (\fBPHP_CodeCoverage\fP $coverage,  $target = \fCnull\fP,  $name = \fCnull\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$coverage\fP 
.br
\fI$target\fP 
.br
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 30 of file Crap4j\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
