.TH "PHP_Token_INTERFACE" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_Token_INTERFACE \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHP_TokenWithScopeAndVisibility\fP\&.
.PP
Inherited by \fBPHP_Token_CLASS\fP, and \fBPHP_Token_TRAIT\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBhasParent\fP ()"
.br
.ti -1c
.RI "\fBgetPackage\fP ()"
.br
.ti -1c
.RI "\fBgetParent\fP ()"
.br
.ti -1c
.RI "\fBhasInterfaces\fP ()"
.br
.ti -1c
.RI "\fBgetInterfaces\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBarrayToName\fP (array $parts, $join= '\\\\')"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$interfaces\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 396 of file Token\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "arrayToName (array $parts,  $join = \fC'\\\\'\fP)\fC [protected]\fP"

.PP
Definition at line 453 of file Token\&.php\&.
.SS "getInterfaces ()"

.PP
Definition at line 492 of file Token\&.php\&.
.SS "getName ()"

.PP
Definition at line 400 of file Token\&.php\&.
.SS "getPackage ()"

.PP
Definition at line 410 of file Token\&.php\&.
.SS "getParent ()"

.PP
Definition at line 466 of file Token\&.php\&.
.SS "hasInterfaces ()"

.PP
Definition at line 484 of file Token\&.php\&.
.SS "hasParent ()"

.PP
Definition at line 405 of file Token\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$interfaces\fC [protected]\fP"

.PP
Definition at line 398 of file Token\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
