.TH "PHPCS_Sniffs_ControlStructures_ControlSignatureSniff" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPCS_Sniffs_ControlStructures_ControlSignatureSniff \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits PHP_CodeSniffer_Standards_AbstractPatternSniff, and PHP_CodeSniffer_Standards_AbstractPatternSniff\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetPatterns\fP ()"
.br
.ti -1c
.RI "\fBgetPatterns\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 2 of file ControlSignatureSniff\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 4 of file ControlSignatureSniff\&.php\&.
.SS "__construct ()"

.PP
Definition at line 4 of file ControlSignatureSniff\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getPatterns ()\fC [protected]\fP"

.PP
Definition at line 9 of file ControlSignatureSniff\&.php\&.
.SS "getPatterns ()\fC [protected]\fP"

.PP
Definition at line 9 of file ControlSignatureSniff\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
