.TH "SinceTag" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SinceTag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVersionTag\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBReflection\fP class for a 
.PP
\fBSince:\fP
.RS 4
tag in a Docblock\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Vasil Rangelov boen.robot@gmail.com  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 24 of file SinceTag\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
