.TH "MethodTag" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MethodTag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBReturnTag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetContent\fP ()"
.br
.ti -1c
.RI "\fBsetContent\fP ($content)"
.br
.ti -1c
.RI "\fBsetMethodName\fP ($method_name)"
.br
.ti -1c
.RI "\fBgetMethodName\fP ()"
.br
.ti -1c
.RI "\fBsetArguments\fP ($arguments)"
.br
.ti -1c
.RI "\fBgetArguments\fP ()"
.br
.ti -1c
.RI "\fBisStatic\fP ()"
.br
.ti -1c
.RI "\fBsetIsStatic\fP ($\fBisStatic\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$method_name\fP = ''"
.br
.ti -1c
.RI "\fB$arguments\fP = ''"
.br
.ti -1c
.RI "\fB$isStatic\fP = false"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBReflection\fP class for a  in a Docblock\&.
.PP
\fBAuthor:\fP
.RS 4
Mike van Riel mike.vanriel@naenius.com  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 24 of file MethodTag\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getArguments ()"
Returns an array containing each argument as array of type and name\&.
.PP
Please note that the argument sub-array may only contain 1 element if no type was specified\&.
.PP
\fBReturns:\fP
.RS 4
string[] 
.RE
.PP

.PP
Definition at line 170 of file MethodTag\&.php\&.
.SS "getContent ()"
{} 
.PP
Definition at line 39 of file MethodTag\&.php\&.
.SS "getMethodName ()"
Retrieves the method name\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 142 of file MethodTag\&.php\&.
.SS "isStatic ()"
Checks whether the method tag describes a static method or not\&.
.PP
\fBReturns:\fP
.RS 4
bool TRUE if the method declaration is for a static method, FALSE otherwise\&. 
.RE
.PP

.PP
Definition at line 190 of file MethodTag\&.php\&.
.SS "setArguments ( $arguments)"
Sets the arguments for this method\&.
.PP
\fBParameters:\fP
.RS 4
\fI$arguments\fP \fBA\fP comma-separated arguments line\&.
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 154 of file MethodTag\&.php\&.
.SS "setContent ( $content)"
{} 
.PP
Definition at line 57 of file MethodTag\&.php\&.
.SS "setIsStatic ( $isStatic)"
Sets a new value for whether the method is static or not\&.
.PP
\fBParameters:\fP
.RS 4
\fI$isStatic\fP The new value to set\&.
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 202 of file MethodTag\&.php\&.
.SS "setMethodName ( $method_name)"
Sets the name of this method\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method_name\fP The name of the method\&.
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 129 of file MethodTag\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$arguments = ''\fC [protected]\fP"

.PP
Definition at line 31 of file MethodTag\&.php\&.
.SS "$\fBisStatic\fP = false\fC [protected]\fP"

.PP
Definition at line 34 of file MethodTag\&.php\&.
.SS "$method_name = ''\fC [protected]\fP"

.PP
Definition at line 28 of file MethodTag\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
