.TH "DocBlockTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DocBlockTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstruct\fP ()"
.br
.ti -1c
.RI "\fBtestConstructWithTagsOnly\fP ()"
.br
.ti -1c
.RI "\fBtestIfStartOfTemplateIsDiscovered\fP ()"
.br
.ti -1c
.RI "\fBtestIfEndOfTemplateIsDiscovered\fP ()"
.br
.ti -1c
.RI "\fBtestConstructOneLiner\fP ()"
.br
.ti -1c
.RI "\fBtestConstructFromReflector\fP ()"
.br
.ti -1c
.RI "\fBtestExceptionOnInvalidObject\fP ()"
.br
.ti -1c
.RI "\fBtestDotSeperation\fP ()"
.br
.ti -1c
.RI "\fBtestInvalidTagBlock\fP ()"
.br
.ti -1c
.RI "\fBtestTagCaseSensitivity\fP ()"
.br
.ti -1c
.RI "\fBtestGetTagsByNameZeroAndOneMatch\fP ()"
.br
.ti -1c
.RI "\fBtestParseMultilineTag\fP ()"
.br
.ti -1c
.RI "\fBtestGetTagsByNameMultipleMatch\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Test class for \fBphpDocumentor\fP
.PP
\fBAuthor:\fP
.RS 4
Mike van Riel mike.vanriel@naenius.com 
.RE
.PP
\fBCopyright:\fP
.RS 4
2010-2011 Mike van Riel / Naenius\&. (http://www.naenius.com)  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 27 of file DocBlockTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstruct ()"

.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 34 of file DocBlockTest\&.php\&.
.SS "testConstructFromReflector ()"
::__construct
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 138 of file DocBlockTest\&.php\&.
.SS "testConstructOneLiner ()"
::cleanInput
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 121 of file DocBlockTest\&.php\&.
.SS "testConstructWithTagsOnly ()"
::splitDocBlock
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 70 of file DocBlockTest\&.php\&.
.SS "testDotSeperation ()"

.PP
Definition at line 164 of file DocBlockTest\&.php\&.
.SS "testExceptionOnInvalidObject ()"

.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 159 of file DocBlockTest\&.php\&.
.SS "testGetTagsByNameMultipleMatch ()"
testConstructWithTagsOnly  ::getTagsByName
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 291 of file DocBlockTest\&.php\&.
.SS "testGetTagsByNameZeroAndOneMatch ()"
testConstructFromReflector  ::getTagsByName
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 245 of file DocBlockTest\&.php\&.
.SS "testIfEndOfTemplateIsDiscovered ()"
::isTemplateEnd 
.PP
Definition at line 105 of file DocBlockTest\&.php\&.
.SS "testIfStartOfTemplateIsDiscovered ()"
::isTemplateStart 
.PP
Definition at line 87 of file DocBlockTest\&.php\&.
.SS "testInvalidTagBlock ()"
::parseTags  
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 187 of file DocBlockTest\&.php\&.
.SS "testParseMultilineTag ()"
testConstructWithTagsOnly  ::parseTags
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 258 of file DocBlockTest\&.php\&.
.SS "testTagCaseSensitivity ()"

.PP
Definition at line 207 of file DocBlockTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
