.TH "LinkTag" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinkTag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetContent\fP ()"
.br
.ti -1c
.RI "\fBsetContent\fP ($content)"
.br
.ti -1c
.RI "\fBgetLink\fP ()"
.br
.ti -1c
.RI "\fBsetLink\fP ($link)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$link\fP = ''"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBReflection\fP class for a \fBin a Docblock\&.  Ben Selby benmatselby@gmail.com  http://www.opensource.org/licenses/mit-license.php MIT  http://phpdoc.org \fP
.PP
Definition at line 24 of file LinkTag\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getContent ()"
{} 
.PP
Definition at line 32 of file LinkTag\&.php\&.
.SS "getLink ()"
Gets the link
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 62 of file LinkTag\&.php\&.
.SS "setContent ( $content)"
{} 
.PP
Definition at line 44 of file LinkTag\&.php\&.
.SS "setLink ( $link)"
Sets the link
.PP
\fBParameters:\fP
.RS 4
\fI$link\fP The link
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 74 of file LinkTag\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$link = ''\fC [protected]\fP"

.PP
Definition at line 27 of file LinkTag\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
