.TH "ParamTagTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParamTagTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructorParsesInputsIntoCorrectFields\fP ($type, $content, $extractedType, $extractedTypes, $extractedVarName, $extractedDescription)"
.br
.ti -1c
.RI "\fBprovideDataForConstructor\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Test class for 
.PP
\fBAuthor:\fP
.RS 4
Mike van Riel mike.vanriel@naenius.com 
.RE
.PP
\fBCopyright:\fP
.RS 4
2010-2011 Mike van Riel / Naenius\&. (http://www.naenius.com)  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 23 of file ParamTagTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provideDataForConstructor ()"
Data provider for \fBtestConstructorParsesInputsIntoCorrectFields()\fP
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 63 of file ParamTagTest\&.php\&.
.SS "testConstructorParsesInputsIntoCorrectFields ( $type,  $content,  $extractedType,  $extractedTypes,  $extractedVarName,  $extractedDescription)"
Test that the  can understand the 
.PP
\fBParameters:\fP
.RS 4
\fIDocBlock\&.\fP 
.br
\fI$type\fP 
.br
\fI$content\fP 
.br
\fI$extractedType\fP 
.br
\fI$extractedTypes\fP 
.br
\fI$extractedVarName\fP 
.br
\fI$extractedDescription\fP provideDataForConstructor
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 41 of file ParamTagTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
