.TH "SeeTag" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SeeTag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTag\fP\&.
.PP
Inherited by \fBCoversTag\fP, and \fBUsesTag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetContent\fP ()"
.br
.ti -1c
.RI "\fBsetContent\fP ($content)"
.br
.ti -1c
.RI "\fBgetReference\fP ()"
.br
.ti -1c
.RI "\fBsetReference\fP ($refers)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$refers\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBReflection\fP class for a 
.PP
\fBSee also:\fP
.RS 4
tag in \fBa\fP Docblock\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Mike van Riel mike.vanriel@naenius.com  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 24 of file SeeTag\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getContent ()"
{} 
.PP
Definition at line 32 of file SeeTag\&.php\&.
.SS "getReference ()"
Gets the structural element this tag refers to\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 62 of file SeeTag\&.php\&.
.SS "setContent ( $content)"
{} 
.PP
Definition at line 43 of file SeeTag\&.php\&.
.SS "setReference ( $refers)"
Sets the structural element this tag refers to\&.
.PP
\fBParameters:\fP
.RS 4
\fI$refers\fP The new type this tag refers to\&.
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 74 of file SeeTag\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$refers = null\fC [protected]\fP"

.PP
Definition at line 27 of file SeeTag\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
