.TH "CollectionTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollectionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstruct\fP ()"
.br
.ti -1c
.RI "\fBtestConstructWithTypes\fP ()"
.br
.ti -1c
.RI "\fBtestConstructWithNamespace\fP ()"
.br
.ti -1c
.RI "\fBtestConstructWithNamespaceAliases\fP ()"
.br
.ti -1c
.RI "\fBtestAdd\fP ($fixture, $expected)"
.br
.ti -1c
.RI "\fBtestAddWithoutNamespace\fP ($fixture, $expected)"
.br
.ti -1c
.RI "\fBtestAddWithInvalidArgument\fP ()"
.br
.ti -1c
.RI "\fBprovideTypesToExpand\fP ($method, $namespace= '\\My\\Space\\\\')"
.br
.ti -1c
.RI "\fBprovideTypesToExpandWithoutNamespace\fP ($method)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Test class for 
.PP
\fBphpDocumentor\fP
.PP
\fBAuthor:\fP
.RS 4
Mike van Riel mike.vanriel@naenius.com 
.RE
.PP
\fBCopyright:\fP
.RS 4
2010-2011 Mike van Riel / Naenius\&. (http://www.naenius.com)  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 27 of file CollectionTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provideTypesToExpand ( $method,  $namespace = \fC'\\My\\Space\\\\'\fP)"
Returns the types and their expected values to test the retrieval of types\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP Name of the method consuming this data provider\&. 
.br
\fI$namespace\fP Name of the namespace to user as basis\&.
.RE
.PP
\fBReturns:\fP
.RS 4
string[] 
.RE
.PP

.PP
Definition at line 147 of file CollectionTest\&.php\&.
.SS "provideTypesToExpandWithoutNamespace ( $method)"
Returns the types and their expected values to test the retrieval of types when no namespace is available\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP Name of the method consuming this data provider\&.
.RE
.PP
\fBReturns:\fP
.RS 4
string[] 
.RE
.PP

.PP
Definition at line 191 of file CollectionTest\&.php\&.
.SS "testAdd ( $fixture,  $expected)"

.PP
\fBParameters:\fP
.RS 4
\fI$fixture\fP 
.br
\fI$expected\fP provideTypesToExpand  \fBphpDocumentor\fP::add
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 95 of file CollectionTest\&.php\&.
.SS "testAddWithInvalidArgument ()"
\fBphpDocumentor\fP::add  InvalidArgumentException
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 132 of file CollectionTest\&.php\&.
.SS "testAddWithoutNamespace ( $fixture,  $expected)"

.PP
\fBParameters:\fP
.RS 4
\fI$fixture\fP 
.br
\fI$expected\fP provideTypesToExpandWithoutNamespace  \fBphpDocumentor\fP::add
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 115 of file CollectionTest\&.php\&.
.SS "testConstruct ()"
\fBphpDocumentor\fP::__construct  \fBphpDocumentor\fP::getContext
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 35 of file CollectionTest\&.php\&.
.SS "testConstructWithNamespace ()"
\fBphpDocumentor\fP::__construct
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 59 of file CollectionTest\&.php\&.
.SS "testConstructWithNamespaceAliases ()"
\fBphpDocumentor\fP::__construct
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 76 of file CollectionTest\&.php\&.
.SS "testConstructWithTypes ()"
\fBphpDocumentor\fP::__construct
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 48 of file CollectionTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
