.TH "Description" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Description \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Reflector\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($content, \fBDocBlock\fP $docblock=null)"
.br
.ti -1c
.RI "\fBgetContents\fP ()"
.br
.ti -1c
.RI "\fBsetContent\fP ($content)"
.br
.ti -1c
.RI "\fBgetParsedContents\fP ()"
.br
.ti -1c
.RI "\fBgetFormattedContents\fP ()"
.br
.ti -1c
.RI "\fBgetDocBlock\fP ()"
.br
.ti -1c
.RI "\fBsetDocBlock\fP (\fBDocBlock\fP $docblock=null)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBexport\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$contents\fP = ''"
.br
.ti -1c
.RI "\fB$parsedContents\fP = null"
.br
.ti -1c
.RI "\fB$docblock\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Parses a \fBDescription\fP of a \fBDocBlock\fP or tag\&.
.PP
\fBAuthor:\fP
.RS 4
Mike van Riel mike.vanriel@naenius.com  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 24 of file Description\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $content, \fBDocBlock\fP $docblock = \fCnull\fP)"
Populates the fields of a description\&.
.PP
\fBParameters:\fP
.RS 4
\fI$content\fP The description's conetnts\&. 
.br
\fI$docblock\fP The \fBDocBlock\fP which this description belongs to\&. 
.RE
.PP

.PP
Definition at line 41 of file Description\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"
Returns the long description as a string\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 219 of file Description\&.php\&.
.SS "static export ()\fC [static]\fP"
Builds a string representation of this object\&.
.PP
\fBTodo\fP
.RS 4
determine the exact format as used by \fBPHP\fP \fBReflection\fP and implement it\&.
.RE
.PP
.PP
\fBReturns:\fP
.RS 4
void  Not yet implemented 
.RE
.PP

.PP
Definition at line 209 of file Description\&.php\&.
.SS "getContents ()"
Gets the text of this description\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 51 of file Description\&.php\&.
.SS "getDocBlock ()"
Gets the docblock this tag belongs to\&.
.PP
\fBReturns:\fP
.RS 4
\fBDocBlock\fP The docblock this description belongs to\&. 
.RE
.PP

.PP
Definition at line 180 of file Description\&.php\&.
.SS "getFormattedContents ()"
Return a formatted variant of the Long \fBDescription\fP using MarkDown\&.
.PP
\fBTodo\fP
.RS 4
this should become a more intelligent piece of code where the configuration contains a setting what format long descriptions are\&.
.RE
.PP
.PP
Will be removed soon, in favor of adapters at PhpDocumentor itself that will process text in various formats\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 149 of file Description\&.php\&.
.SS "getParsedContents ()"
Returns the parsed text of this description\&.
.PP
\fBReturns:\fP
.RS 4
array An array of strings and tag objects, in the order they occur within the description\&. 
.RE
.PP

.PP
Definition at line 77 of file Description\&.php\&.
.SS "setContent ( $content)"
Sets the text of this description\&.
.PP
\fBParameters:\fP
.RS 4
\fI$content\fP The new text of this description\&.
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 63 of file Description\&.php\&.
.SS "setDocBlock (\fBDocBlock\fP $docblock = \fCnull\fP)"
Sets the docblock this tag belongs to\&.
.PP
\fBParameters:\fP
.RS 4
\fI$docblock\fP The new docblock this description belongs to\&. Setting NULL removes any association\&.
.RE
.PP
\fBReturns:\fP
.RS 4
$this 
.RE
.PP

.PP
Definition at line 193 of file Description\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$contents = ''\fC [protected]\fP"

.PP
Definition at line 27 of file Description\&.php\&.
.SS "$docblock = null\fC [protected]\fP"

.PP
Definition at line 33 of file Description\&.php\&.
.SS "$parsedContents = null\fC [protected]\fP"

.PP
Definition at line 30 of file Description\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
