.TH "ExampleTagTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleTagTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructorParesInputsIntoCorrectFields\fP ($type, $content, $exContent, $exDescription, $exStartingLine, $exLineCount, $exFilePath)"
.br
.ti -1c
.RI "\fBprovideDataForConstuctor\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Test class for 
.PP
\fBAuthor:\fP
.RS 4
Vasil Rangelov boen.robot@gmail.com 
.RE
.PP
\fBCopyright:\fP
.RS 4
2010-2011 Mike van Riel / Naenius\&. (http://www.naenius.com)  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 23 of file ExampleTagTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provideDataForConstuctor ()"
Data provider for testConstructorParesInputsIntoCorrectFields
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 65 of file ExampleTagTest\&.php\&.
.SS "testConstructorParesInputsIntoCorrectFields ( $type,  $content,  $exContent,  $exDescription,  $exStartingLine,  $exLineCount,  $exFilePath)"
Test that the  can understand the  \fBDocBlock\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$type\fP 
.br
\fI$content\fP 
.br
\fI$exContent\fP 
.br
\fI$exStartingLine\fP 
.br
\fI$exLineCount\fP 
.br
\fI$exFilepath\fP provideDataForConstuctor
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 41 of file ExampleTagTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
