.TH "ReturnTag" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReturnTag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTag\fP\&.
.PP
Inherited by \fBMethodTag\fP, \fBParamTag\fP, and \fBThrowsTag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetContent\fP ()"
.br
.ti -1c
.RI "\fBsetContent\fP ($content)"
.br
.ti -1c
.RI "\fBgetTypes\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetTypesCollection\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$type\fP = ''"
.br
.ti -1c
.RI "\fB$types\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBReflection\fP class for a 
.PP
\fBReturns:\fP
.RS 4
tag in a Docblock\&.
.RE
.PP
\fBAuthor:\fP
.RS 4
Mike van Riel mike.vanriel@naenius.com  http://www.opensource.org/licenses/mit-license.php MIT \fBhttp://phpdoc\&.org\fP
.RE
.PP

.PP
Definition at line 25 of file ReturnTag\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getContent ()"
{} 
.PP
Definition at line 36 of file ReturnTag\&.php\&.
.SS "getType ()"
Returns the type section of the variable\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 79 of file ReturnTag\&.php\&.
.SS "getTypes ()"
Returns the unique types of the variable\&.
.PP
\fBReturns:\fP
.RS 4
string[] 
.RE
.PP

.PP
Definition at line 69 of file ReturnTag\&.php\&.
.SS "getTypesCollection ()\fC [protected]\fP"
Returns the type collection\&.
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 89 of file ReturnTag\&.php\&.
.SS "setContent ( $content)"
{} 
.PP
Definition at line 48 of file ReturnTag\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$type = ''\fC [protected]\fP"

.PP
Definition at line 28 of file ReturnTag\&.php\&.
.SS "$types = null\fC [protected]\fP"

.PP
Definition at line 31 of file ReturnTag\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
