.TH "If_" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
If_ \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStmt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBNode\\Expr\fP $cond, array $subNodes=array(), array $attributes=array())"
.br
.ti -1c
.RI "\fBgetSubNodeNames\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$cond\fP"
.br
.ti -1c
.RI "\fB$stmts\fP"
.br
.ti -1c
.RI "\fB$elseifs\fP"
.br
.ti -1c
.RI "\fB$else\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file If_\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBNode\\Expr\fP $cond, array $subNodes = \fCarray()\fP, array $attributes = \fCarray()\fP)"
Constructs an if node\&.
.PP
\fBParameters:\fP
.RS 4
\fI$cond\fP Condition 
.br
\fI$subNodes\fP Array of the following optional subnodes: 'stmts' => array(): Statements 'elseifs' => array(): Elseif clauses 'else' => null : Else clause 
.br
\fI$attributes\fP Additional attributes 
.RE
.PP

.PP
Definition at line 28 of file If_\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getSubNodeNames ()"
Gets the names of the sub nodes\&.
.PP
\fBReturns:\fP
.RS 4
array Names of sub nodes 
.RE
.PP

.PP
Implements \fBNode\fP\&.
.PP
Definition at line 36 of file If_\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$cond"

.PP
Definition at line 10 of file If_\&.php\&.
.SS "$\fBelse\fP"

.PP
Definition at line 16 of file If_\&.php\&.
.SS "$elseifs"

.PP
Definition at line 14 of file If_\&.php\&.
.SS "$stmts"

.PP
Definition at line 12 of file If_\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
