.TH "Interface_" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Interface_ \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBClassLike\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP, array $subNodes=array(), array $attributes=array())"
.br
.ti -1c
.RI "\fBgetSubNodeNames\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$extends\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$specialNames\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file Interface_\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name, array $subNodes = \fCarray()\fP, array $attributes = \fCarray()\fP)"
Constructs a class node\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP \fBName\fP 
.br
\fI$subNodes\fP Array of the following optional subnodes: 'extends' => array(): \fBName\fP of extended interfaces 'stmts' => array(): Statements 
.br
\fI$attributes\fP Additional attributes 
.RE
.PP

.PP
Definition at line 28 of file Interface_\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getSubNodeNames ()"
Gets the names of the sub nodes\&.
.PP
\fBReturns:\fP
.RS 4
array Names of sub nodes 
.RE
.PP

.PP
Implements \fBNode\fP\&.
.PP
Definition at line 45 of file Interface_\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$extends"

.PP
Definition at line 11 of file Interface_\&.php\&.
.SS "$specialNames\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= array(
        'self'   => true,
        'parent' => true,
        'static' => true,
    )
.fi
.PP
Definition at line 13 of file Interface_\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
