.TH "Serializer\XMLTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Serializer\XMLTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSerialize\fP ()"
.br
.ti -1c
.RI "\fBtestError\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file XMLTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testError ()"
Unexpected node type 
.PP
Definition at line 161 of file XMLTest\&.php\&.
.SS "testSerialize ()"
\fBPhpParser\fP<extended> 
.PP
Definition at line 12 of file XMLTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
