.TH "Stmt\ClassTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stmt\ClassTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestIsAbstract\fP ()"
.br
.ti -1c
.RI "\fBtestIsFinal\fP ()"
.br
.ti -1c
.RI "\fBtestGetMethods\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file ClassTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testGetMethods ()"

.PP
Definition at line 23 of file ClassTest\&.php\&.
.SS "testIsAbstract ()"

.PP
Definition at line 7 of file ClassTest\&.php\&.
.SS "testIsFinal ()"

.PP
Definition at line 15 of file ClassTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
