.TH "FunctionLike" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionLike \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDeclaration\fP\&.
.PP
Inherited by \fBFunction_\fP, and \fBMethod\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmakeReturnByRef\fP ()"
.br
.ti -1c
.RI "\fBaddParam\fP ($param)"
.br
.ti -1c
.RI "\fBaddParams\fP (array $params)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$returnByRef\fP = false"
.br
.ti -1c
.RI "\fB$params\fP = array()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file FunctionLike\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addParam ( $param)"
Adds a parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fI$param\fP The parameter to add
.RE
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 32 of file FunctionLike\&.php\&.
.SS "addParams (array $params)"
Adds multiple parameters\&.
.PP
\fBParameters:\fP
.RS 4
\fI$params\fP The parameters to add
.RE
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 51 of file FunctionLike\&.php\&.
.SS "makeReturnByRef ()"
Make the function return by reference\&.
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 19 of file FunctionLike\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$params = array()\fC [protected]\fP"

.PP
Definition at line 12 of file FunctionLike\&.php\&.
.SS "$returnByRef = false\fC [protected]\fP"

.PP
Definition at line 11 of file FunctionLike\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
