.TH "NodeVisitor\NameResolverTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeVisitor\NameResolverTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestResolveNames\fP ()"
.br
.ti -1c
.RI "\fBtestResolveLocations\fP ()"
.br
.ti -1c
.RI "\fBtestNoResolveSpecialName\fP ()"
.br
.ti -1c
.RI "\fBtestAddNamespacedName\fP ()"
.br
.ti -1c
.RI "\fBtestAddTraitNamespacedName\fP ()"
.br
.ti -1c
.RI "\fBtestError\fP (\fBNode\fP $stmt, $errorMsg)"
.br
.ti -1c
.RI "\fBprovideTestError\fP ()"
.br
.ti -1c
.RI "\fBtestClassNameIsCaseInsensitive\fP ()"
.br
.ti -1c
.RI "\fBtestSpecialClassNamesAreCaseInsensitive\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateNamespacedAndNonNamespaced\fP (array $stmts)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file NameResolverTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createNamespacedAndNonNamespaced (array $stmts)\fC [protected]\fP"

.PP
Definition at line 245 of file NameResolverTest\&.php\&.
.SS "provideTestError ()"

.PP
Definition at line 302 of file NameResolverTest\&.php\&.
.SS "testAddNamespacedName ()"

.PP
Definition at line 252 of file NameResolverTest\&.php\&.
.SS "testAddTraitNamespacedName ()"

.PP
Definition at line 277 of file NameResolverTest\&.php\&.
.SS "testClassNameIsCaseInsensitive ()"

.PP
Definition at line 344 of file NameResolverTest\&.php\&.
.SS "testError (\fBNode\fP $stmt,  $errorMsg)"
provideTestError 
.PP
Definition at line 294 of file NameResolverTest\&.php\&.
.SS "testNoResolveSpecialName ()"

.PP
Definition at line 236 of file NameResolverTest\&.php\&.
.SS "testResolveLocations ()"
\fBPhpParser\fP 
.PP
Definition at line 149 of file NameResolverTest\&.php\&.
.SS "testResolveNames ()"
\fBPhpParser\fP 
.PP
Definition at line 20 of file NameResolverTest\&.php\&.
.SS "testSpecialClassNamesAreCaseInsensitive ()"

.PP
Definition at line 365 of file NameResolverTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
