.TH "Class_" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Class_ \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBClassLike\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP, array $subNodes=array(), array $attributes=array())"
.br
.ti -1c
.RI "\fBgetSubNodeNames\fP ()"
.br
.ti -1c
.RI "\fBisAbstract\fP ()"
.br
.ti -1c
.RI "\fBisFinal\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBverifyModifier\fP ($\fBa\fP, $\fBb\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBMODIFIER_PUBLIC\fP = 1"
.br
.ti -1c
.RI "const \fBMODIFIER_PROTECTED\fP = 2"
.br
.ti -1c
.RI "const \fBMODIFIER_PRIVATE\fP = 4"
.br
.ti -1c
.RI "const \fBMODIFIER_STATIC\fP = 8"
.br
.ti -1c
.RI "const \fBMODIFIER_ABSTRACT\fP = 16"
.br
.ti -1c
.RI "const \fBMODIFIER_FINAL\fP = 32"
.br
.ti -1c
.RI "const \fBVISIBILITY_MODIFER_MASK\fP = 7"
.br
.ti -1c
.RI "\fB$type\fP"
.br
.ti -1c
.RI "\fB$extends\fP"
.br
.ti -1c
.RI "\fB$implements\fP"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$specialNames\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file Class_\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name, array $subNodes = \fCarray()\fP, array $attributes = \fCarray()\fP)"
Constructs a class node\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP \fBName\fP 
.br
\fI$subNodes\fP Array of the following optional subnodes: 'type' => 0 : Type 'extends' => null : \fBName\fP of extended class 'implements' => array(): Names of implemented interfaces 'stmts' => array(): Statements 
.br
\fI$attributes\fP Additional attributes 
.RE
.PP

.PP
Definition at line 43 of file Class_\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getSubNodeNames ()"
Gets the names of the sub nodes\&.
.PP
\fBReturns:\fP
.RS 4
array Names of sub nodes 
.RE
.PP

.PP
Implements \fBNode\fP\&.
.PP
Definition at line 66 of file Class_\&.php\&.
.SS "isAbstract ()"

.PP
Definition at line 70 of file Class_\&.php\&.
.SS "isFinal ()"

.PP
Definition at line 74 of file Class_\&.php\&.
.SS "static verifyModifier ( $a,  $b)\fC [static]\fP"

.PP
Definition at line 81 of file Class_\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$extends"

.PP
Definition at line 22 of file Class_\&.php\&.
.SS "$implements"

.PP
Definition at line 24 of file Class_\&.php\&.
.SS "$specialNames\fC [static]\fP, \fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= array(
        'self'   => true,
        'parent' => true,
        'static' => true,
    )
.fi
.PP
Definition at line 26 of file Class_\&.php\&.
.SS "$type"

.PP
Definition at line 20 of file Class_\&.php\&.
.SS "const MODIFIER_ABSTRACT = 16"

.PP
Definition at line 14 of file Class_\&.php\&.
.SS "const MODIFIER_FINAL = 32"

.PP
Definition at line 15 of file Class_\&.php\&.
.SS "const MODIFIER_PRIVATE = 4"

.PP
Definition at line 12 of file Class_\&.php\&.
.SS "const MODIFIER_PROTECTED = 2"

.PP
Definition at line 11 of file Class_\&.php\&.
.SS "const MODIFIER_PUBLIC = 1"

.PP
Definition at line 10 of file Class_\&.php\&.
.SS "const MODIFIER_STATIC = 8"

.PP
Definition at line 13 of file Class_\&.php\&.
.SS "const VISIBILITY_MODIFER_MASK = 7"

.PP
Definition at line 17 of file Class_\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
