.TH "PhpParser\Node\Scalar" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhpParser\Node\Scalar \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMagicConst\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDNumber\fP"
.br
.ti -1c
.RI "class \fBEncapsed\fP"
.br
.ti -1c
.RI "class \fBLNumber\fP"
.br
.ti -1c
.RI "class \fBMagicConst\fP"
.br
.ti -1c
.RI "class \fBMagicConstTest\fP"
.br
.ti -1c
.RI "class \fBString_\fP"
.br
.ti -1c
.RI "class \fBStringTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
