.TH "Error" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Error \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException\&.
.PP
Inherited by \fBParseErrorException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $\fBline\fP=-1)"
.br
.ti -1c
.RI "\fBgetRawMessage\fP ()"
.br
.ti -1c
.RI "\fBsetRawMessage\fP ($message)"
.br
.ti -1c
.RI "\fBgetRawLine\fP ()"
.br
.ti -1c
.RI "\fBsetRawLine\fP ($\fBline\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBupdateMessage\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$rawMessage\fP"
.br
.ti -1c
.RI "\fB$rawLine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Error\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $line = \fC-1\fP)"
Creates an Exception signifying a parse error\&.
.PP
\fBParameters:\fP
.RS 4
\fI$message\fP \fBError\fP message 
.br
\fI$line\fP \fBError\fP line in \fBPHP\fP file 
.RE
.PP

.PP
Definition at line 16 of file Error\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getRawLine ()"
Gets the error line in the \fBPHP\fP file\&.
.PP
\fBReturns:\fP
.RS 4
int \fBError\fP line in the \fBPHP\fP file 
.RE
.PP

.PP
Definition at line 46 of file Error\&.php\&.
.SS "getRawMessage ()"
Gets the error message
.PP
\fBReturns:\fP
.RS 4
string \fBError\fP message 
.RE
.PP

.PP
Definition at line 27 of file Error\&.php\&.
.SS "setRawLine ( $line)"
Sets the line of the \fBPHP\fP file the error occurred in\&.
.PP
\fBParameters:\fP
.RS 4
\fI$line\fP \fBError\fP line in the \fBPHP\fP file 
.RE
.PP

.PP
Definition at line 55 of file Error\&.php\&.
.SS "setRawMessage ( $message)"
Sets the line of the \fBPHP\fP file the error occurred in\&.
.PP
\fBParameters:\fP
.RS 4
\fI$message\fP \fBError\fP message 
.RE
.PP

.PP
Definition at line 36 of file Error\&.php\&.
.SS "updateMessage ()\fC [protected]\fP"
Updates the exception message after a change to rawMessage or rawLine\&. 
.PP
Definition at line 63 of file Error\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$rawLine\fC [protected]\fP"

.PP
Definition at line 8 of file Error\&.php\&.
.SS "$rawMessage\fC [protected]\fP"

.PP
Definition at line 7 of file Error\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
