.TH "Builder\NamespaceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Builder\NamespaceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestCreation\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateNamespaceBuilder\fP ($fqn)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file NamespaceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createNamespaceBuilder ( $fqn)\fC [protected]\fP"

.PP
Definition at line 10 of file NamespaceTest\&.php\&.
.SS "testCreation ()"

.PP
Definition at line 14 of file NamespaceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
