.TH "Method" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Method \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFunctionLike\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBmakePublic\fP ()"
.br
.ti -1c
.RI "\fBmakeProtected\fP ()"
.br
.ti -1c
.RI "\fBmakePrivate\fP ()"
.br
.ti -1c
.RI "\fBmakeStatic\fP ()"
.br
.ti -1c
.RI "\fBmakeAbstract\fP ()"
.br
.ti -1c
.RI "\fBmakeFinal\fP ()"
.br
.ti -1c
.RI "\fBaddStmt\fP ($stmt)"
.br
.ti -1c
.RI "\fBgetNode\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$type\fP = 0"
.br
.ti -1c
.RI "\fB$stmts\fP = array()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file Method\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name)"
Creates a method builder\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP Name of the method 
.RE
.PP

.PP
Definition at line 20 of file Method\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addStmt ( $stmt)"
Adds a statement\&.
.PP
\fBParameters:\fP
.RS 4
\fI$stmt\fP The statement to add
.RE
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 102 of file Method\&.php\&.
.SS "getNode ()"
Returns the built method node\&.
.PP
\fBReturns:\fP
.RS 4
Stmt The built method node 
.RE
.PP

.PP
Implements \fBBuilder\fP\&.
.PP
Definition at line 117 of file Method\&.php\&.
.SS "makeAbstract ()"
Makes the method abstract\&.
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 73 of file Method\&.php\&.
.SS "makeFinal ()"
Makes the method final\&.
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 89 of file Method\&.php\&.
.SS "makePrivate ()"
Makes the method private\&.
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 51 of file Method\&.php\&.
.SS "makeProtected ()"
Makes the method protected\&.
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 40 of file Method\&.php\&.
.SS "makePublic ()"
Makes the method public\&.
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 29 of file Method\&.php\&.
.SS "makeStatic ()"
Makes the method static\&.
.PP
\fBReturns:\fP
.RS 4
$this The builder instance (for fluid interface) 
.RE
.PP

.PP
Definition at line 62 of file Method\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBname\fP\fC [protected]\fP"

.PP
Definition at line 11 of file Method\&.php\&.
.SS "$stmts = array()\fC [protected]\fP"

.PP
Definition at line 13 of file Method\&.php\&.
.SS "$type = 0\fC [protected]\fP"

.PP
Definition at line 12 of file Method\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
