.TH "Relative" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Relative \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBName\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBisUnqualified\fP ()"
.br
.ti -1c
.RI "\fBisQualified\fP ()"
.br
.ti -1c
.RI "\fBisFullyQualified\fP ()"
.br
.ti -1c
.RI "\fBisRelative\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file Relative\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "isFullyQualified ()"
Checks whether the name is fully qualified\&. (E\&.g\&. )
.PP
\fBReturns:\fP
.RS 4
bool Whether the name is fully qualified 
.RE
.PP

.PP
Definition at line 30 of file Relative\&.php\&.
.SS "isQualified ()"
Checks whether the name is qualified\&. (E\&.g\&. \fBName\fP)
.PP
\fBReturns:\fP
.RS 4
bool Whether the name is qualified 
.RE
.PP

.PP
Definition at line 21 of file Relative\&.php\&.
.SS "isRelative ()"
Checks whether the name is explicitly relative to the current namespace\&. (E\&.g\&. namespace)
.PP
\fBReturns:\fP
.RS 4
bool Whether the name is relative 
.RE
.PP

.PP
Definition at line 39 of file Relative\&.php\&.
.SS "isUnqualified ()"
Checks whether the name is unqualified\&. (E\&.g\&. \fBName\fP)
.PP
\fBReturns:\fP
.RS 4
bool Whether the name is unqualified 
.RE
.PP

.PP
Definition at line 12 of file Relative\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
