.TH "PhpParser\Node\Stmt\TraitUseAdaptation" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhpParser\Node\Stmt\TraitUseAdaptation \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAlias\fP"
.br
.ti -1c
.RI "class \fBPrecedence\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
