.TH "NodeTraverser" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NodeTraverser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeTraverserInterface\fP\&.
.PP
Inherited by \fBNodeTraverser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($cloneNodes=true)"
.br
.ti -1c
.RI "\fBaddVisitor\fP (\fBNodeVisitor\fP $visitor)"
.br
.ti -1c
.RI "\fBremoveVisitor\fP (\fBNodeVisitor\fP $visitor)"
.br
.ti -1c
.RI "\fBtraverse\fP (array $nodes)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBtraverseNode\fP (\fBNode\fP $\fBnode\fP)"
.br
.ti -1c
.RI "\fBtraverseArray\fP (array $nodes)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$visitors\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file NodeTraverser\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $cloneNodes = \fCtrue\fP)"
Constructs a node traverser\&.
.PP
\fBParameters:\fP
.RS 4
\fI$cloneNodes\fP Should the traverser clone the nodes when traversing the AST 
.RE
.PP

.PP
Definition at line 22 of file NodeTraverser\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addVisitor (\fBNodeVisitor\fP $visitor)"
Adds a visitor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$visitor\fP Visitor to add 
.RE
.PP

.PP
Implements \fBNodeTraverserInterface\fP\&.
.PP
Definition at line 32 of file NodeTraverser\&.php\&.
.SS "removeVisitor (\fBNodeVisitor\fP $visitor)"
Removes an added visitor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$visitor\fP 
.RE
.PP

.PP
Implements \fBNodeTraverserInterface\fP\&.
.PP
Definition at line 41 of file NodeTraverser\&.php\&.
.SS "traverse (array $nodes)"
Traverses an array of nodes using the registered visitors\&.
.PP
\fBParameters:\fP
.RS 4
\fINode[]\fP $nodes Array of nodes
.RE
.PP
\fBReturns:\fP
.RS 4
\fBNode\fP[] Traversed array of nodes 
.RE
.PP

.PP
Implements \fBNodeTraverserInterface\fP\&.
.PP
Definition at line 57 of file NodeTraverser\&.php\&.
.SS "traverseArray (array $nodes)\fC [protected]\fP"

.PP
Definition at line 111 of file NodeTraverser\&.php\&.
.SS "traverseNode (\fBNode\fP $node)\fC [protected]\fP"

.PP
Definition at line 75 of file NodeTraverser\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$visitors\fC [protected]\fP"

.PP
Definition at line 10 of file NodeTraverser\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
