.TH "InvalidTokenLexer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvalidTokenLexer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLexer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetNextToken\fP (&$value=null, &$startAttributes=null, &$endAttributes=null)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 134 of file ParserTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getNextToken (& $value = \fCnull\fP, & $startAttributes = \fCnull\fP, & $endAttributes = \fCnull\fP)"

.PP
Definition at line 135 of file ParserTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
