.TH "SpecificationInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpecificationInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjectBehavior\fP\&.
.SH "Detailed Description"
.PP 
This is the basic type for specification classes\&. ObjectBehaviour will implement this interface\&. If a spec class does not implement this interface \fBPhpSpec\fP runner will refuse to run the spec class\&. 
.PP
Definition at line 21 of file SpecificationInterface\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
