.TH "ExtensionInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExtensionInterface \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBload\fP (\fBServiceContainer\fP $container)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface \fBExtensionInterface\fP is used for \fBPhpSpec\fP extensions to interface with \fBPhpSpec\fP through the service container 
.PP
Definition at line 22 of file ExtensionInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "load (\fBServiceContainer\fP $container)"

.PP
\fBParameters:\fP
.RS 4
\fI$container\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
