.TH "PhpSpec\Exception\Wrapper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhpSpec\Exception\Wrapper \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCollaboratorException\fP"
.br
.ti -1c
.RI "class \fBMatcherNotFoundException\fP"
.br
.ti -1c
.RI "class \fBSubjectException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
