.TH "DispatcherDecorator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DispatcherDecorator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDecorator\fP, and \fBExpectationInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBExpectationInterface\fP $expectation, \fBEventDispatcherInterface\fP $dispatcher, \fBMatcherInterface\fP $matcher, \fBExampleNode\fP $example)"
.br
.ti -1c
.RI "\fBmatch\fP ($alias, $subject, array $arguments=array())"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file DispatcherDecorator\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBExpectationInterface\fP $expectation, \fBEventDispatcherInterface\fP $dispatcher, \fBMatcherInterface\fP $matcher, \fBExampleNode\fP $example)"

.PP
\fBParameters:\fP
.RS 4
\fI$expectation\fP 
.br
\fI$dispatcher\fP 
.br
\fI$matcher\fP 
.br
\fI$example\fP 
.RE
.PP

.PP
Definition at line 44 of file DispatcherDecorator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "match ( $alias,  $subject, array $arguments = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$alias\fP 
.br
\fI$subject\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implements \fBExpectationInterface\fP\&.
.PP
Definition at line 62 of file DispatcherDecorator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
