.TH "ResourceManager" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourceManager \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBResourceManagerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregisterLocator\fP (\fBResourceLocatorInterface\fP $locator)"
.br
.ti -1c
.RI "\fBlocateResources\fP ($query)"
.br
.ti -1c
.RI "\fBcreateResource\fP ($classname)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file ResourceManager\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createResource ( $classname)"

.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBResourceInterface\fP
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implements \fBResourceManagerInterface\fP\&.
.PP
Definition at line 68 of file ResourceManager\&.php\&.
.SS "locateResources ( $query)"

.PP
\fBParameters:\fP
.RS 4
\fI$query\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBResourceInterface\fP[] 
.RE
.PP

.PP
Implements \fBResourceManagerInterface\fP\&.
.PP
Definition at line 42 of file ResourceManager\&.php\&.
.SS "registerLocator (\fBResourceLocatorInterface\fP $locator)"

.PP
\fBParameters:\fP
.RS 4
\fI$locator\fP 
.RE
.PP

.PP
Definition at line 28 of file ResourceManager\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
