.TH "Positive" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Positive \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBExpectationInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBMatcherInterface\fP $matcher)"
.br
.ti -1c
.RI "\fBmatch\fP ($alias, $subject, array $arguments=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Positive\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBMatcherInterface\fP $matcher)"

.PP
\fBParameters:\fP
.RS 4
\fI$matcher\fP 
.RE
.PP

.PP
Definition at line 28 of file Positive\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "match ( $alias,  $subject, array $arguments = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$alias\fP 
.br
\fI$subject\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBExpectationInterface\fP\&.
.PP
Definition at line 40 of file Positive\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
