.TH "TaggedPresenter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaggedPresenter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStringPresenter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpresentString\fP ($string)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBpresentCodeLine\fP ($number, $\fBline\fP)"
.br
.ti -1c
.RI "\fBpresentHighlight\fP ($\fBline\fP)"
.br
.ti -1c
.RI "\fBpresentExceptionTraceHeader\fP ($header)"
.br
.ti -1c
.RI "\fBpresentExceptionTraceMethod\fP ($class, $type, $method, array $args)"
.br
.ti -1c
.RI "\fBpresentExceptionTraceFunction\fP ($function, array $args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file TaggedPresenter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "presentCodeLine ( $number,  $line)\fC [protected]\fP"

.PP
Definition at line 23 of file TaggedPresenter\&.php\&.
.SS "presentExceptionTraceFunction ( $function, array $args)\fC [protected]\fP"

.PP
Definition at line 49 of file TaggedPresenter\&.php\&.
.SS "presentExceptionTraceHeader ( $header)\fC [protected]\fP"

.PP
Definition at line 33 of file TaggedPresenter\&.php\&.
.SS "presentExceptionTraceMethod ( $class,  $type,  $method, array $args)\fC [protected]\fP"

.PP
Definition at line 38 of file TaggedPresenter\&.php\&.
.SS "presentHighlight ( $line)\fC [protected]\fP"

.PP
Definition at line 28 of file TaggedPresenter\&.php\&.
.SS "presentString ( $string)"

.PP
\fBParameters:\fP
.RS 4
\fI$string\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBPresenterInterface\fP\&.
.PP
Definition at line 18 of file TaggedPresenter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
