.TH "Unwrapper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Unwrapper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRevealerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBunwrapAll\fP (array $arguments)"
.br
.ti -1c
.RI "\fBunwrapOne\fP ($argument)"
.br
.ti -1c
.RI "\fBreveal\fP ($value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file Unwrapper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "reveal ( $value)"

.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBRevealerInterface\fP\&.
.PP
Definition at line 66 of file Unwrapper\&.php\&.
.SS "unwrapAll (array $arguments)"

.PP
\fBParameters:\fP
.RS 4
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 26 of file Unwrapper\&.php\&.
.SS "unwrapOne ( $argument)"

.PP
\fBParameters:\fP
.RS 4
\fI$argument\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 40 of file Unwrapper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
