.TH "StatisticsCollector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatisticsCollector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventSubscriberInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBafterSpecification\fP (\fBSpecificationEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBafterExample\fP (\fBExampleEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBbeforeSuite\fP (\fBSuiteEvent\fP $suiteEvent)"
.br
.ti -1c
.RI "\fBgetGlobalResult\fP ()"
.br
.ti -1c
.RI "\fBgetAllEvents\fP ()"
.br
.ti -1c
.RI "\fBgetPassedEvents\fP ()"
.br
.ti -1c
.RI "\fBgetPendingEvents\fP ()"
.br
.ti -1c
.RI "\fBgetSkippedEvents\fP ()"
.br
.ti -1c
.RI "\fBgetFailedEvents\fP ()"
.br
.ti -1c
.RI "\fBgetBrokenEvents\fP ()"
.br
.ti -1c
.RI "\fBgetCountsHash\fP ()"
.br
.ti -1c
.RI "\fBgetTotalSpecs\fP ()"
.br
.ti -1c
.RI "\fBgetEventsCount\fP ()"
.br
.ti -1c
.RI "\fBgetTotalSpecsCount\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetSubscribedEvents\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file StatisticsCollector\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "afterExample (\fBExampleEvent\fP $event)"

.PP
Definition at line 48 of file StatisticsCollector\&.php\&.
.SS "afterSpecification (\fBSpecificationEvent\fP $event)"

.PP
Definition at line 43 of file StatisticsCollector\&.php\&.
.SS "beforeSuite (\fBSuiteEvent\fP $suiteEvent)"

.PP
Definition at line 71 of file StatisticsCollector\&.php\&.
.SS "getAllEvents ()"

.PP
Definition at line 81 of file StatisticsCollector\&.php\&.
.SS "getBrokenEvents ()"

.PP
Definition at line 112 of file StatisticsCollector\&.php\&.
.SS "getCountsHash ()"

.PP
Definition at line 117 of file StatisticsCollector\&.php\&.
.SS "getEventsCount ()"

.PP
Definition at line 133 of file StatisticsCollector\&.php\&.
.SS "getFailedEvents ()"

.PP
Definition at line 107 of file StatisticsCollector\&.php\&.
.SS "getGlobalResult ()"

.PP
Definition at line 76 of file StatisticsCollector\&.php\&.
.SS "getPassedEvents ()"

.PP
Definition at line 92 of file StatisticsCollector\&.php\&.
.SS "getPendingEvents ()"

.PP
Definition at line 97 of file StatisticsCollector\&.php\&.
.SS "getSkippedEvents ()"

.PP
Definition at line 102 of file StatisticsCollector\&.php\&.
.SS "static getSubscribedEvents ()\fC [static]\fP"

.PP
Definition at line 33 of file StatisticsCollector\&.php\&.
.SS "getTotalSpecs ()"

.PP
Definition at line 128 of file StatisticsCollector\&.php\&.
.SS "getTotalSpecsCount ()"

.PP
Definition at line 138 of file StatisticsCollector\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
