.TH "ThrowMatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThrowMatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMatcherInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBUnwrapper\fP $unwrapper, \fBPresenterInterface\fP $presenter, \fBReflectionFactory\fP $\fBfactory\fP=null)"
.br
.ti -1c
.RI "\fBsupports\fP ($\fBname\fP, $subject, array $arguments)"
.br
.ti -1c
.RI "\fBpositiveMatch\fP ($\fBname\fP, $subject, array $arguments)"
.br
.ti -1c
.RI "\fBnegativeMatch\fP ($\fBname\fP, $subject, array $arguments)"
.br
.ti -1c
.RI "\fBverifyPositive\fP ($callable, array $arguments, $exception=null)"
.br
.ti -1c
.RI "\fBverifyNegative\fP ($callable, array $arguments, $exception=null)"
.br
.ti -1c
.RI "\fBgetPriority\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file ThrowMatcher\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBUnwrapper\fP $unwrapper, \fBPresenterInterface\fP $presenter, \fBReflectionFactory\fP $factory = \fCnull\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$unwrapper\fP 
.br
\fI$presenter\fP 
.br
\fI$factory\fP 
.RE
.PP

.PP
Definition at line 50 of file ThrowMatcher\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getPriority ()"

.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBMatcherInterface\fP\&.
.PP
Definition at line 206 of file ThrowMatcher\&.php\&.
.SS "negativeMatch ( $name,  $subject, array $arguments)"

.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$subject\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
DelayedCall 
.RE
.PP

.PP
Implements \fBMatcherInterface\fP\&.
.PP
Definition at line 88 of file ThrowMatcher\&.php\&.
.SS "positiveMatch ( $name,  $subject, array $arguments)"

.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$subject\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
DelayedCall 
.RE
.PP

.PP
Implements \fBMatcherInterface\fP\&.
.PP
Definition at line 76 of file ThrowMatcher\&.php\&.
.SS "supports ( $name,  $subject, array $arguments)"

.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$subject\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBMatcherInterface\fP\&.
.PP
Definition at line 64 of file ThrowMatcher\&.php\&.
.SS "verifyNegative ( $callable, array $arguments,  $exception = \fCnull\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$callable\fP 
.br
\fI$arguments\fP 
.br
\fI$exception\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 153 of file ThrowMatcher\&.php\&.
.SS "verifyPositive ( $callable, array $arguments,  $exception = \fCnull\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$callable\fP 
.br
\fI$arguments\fP 
.br
\fI$exception\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 101 of file ThrowMatcher\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
