.TH "BootstrapListener" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BootstrapListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventSubscriberInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBIO\fP $\fBio\fP)"
.br
.ti -1c
.RI "\fBbeforeSuite\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetSubscribedEvents\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file BootstrapListener\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBIO\fP $io)"

.PP
Definition at line 15 of file BootstrapListener\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "beforeSuite ()"

.PP
Definition at line 25 of file BootstrapListener\&.php\&.
.SS "static getSubscribedEvents ()\fC [static]\fP"

.PP
Definition at line 20 of file BootstrapListener\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
