.TH "ConsoleFormatter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBBasicFormatter\fP\&.
.PP
Inherited by \fBDotFormatter\fP, \fBPrettyFormatter\fP, and \fBProgressFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBPresenterInterface\fP $presenter, \fBIO\fP $\fBio\fP, \fBStatisticsCollector\fP $stats)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetIO\fP ()"
.br
.ti -1c
.RI "\fBprintException\fP (\fBExampleEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBprintSpecificException\fP (\fBExampleEvent\fP $\fBevent\fP, $type)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file ConsoleFormatter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBPresenterInterface\fP $presenter, \fBIO\fP $io, \fBStatisticsCollector\fP $stats)"

.PP
\fBParameters:\fP
.RS 4
\fI$presenter\fP 
.br
\fI$io\fP 
.br
\fI$stats\fP 
.RE
.PP

.PP
Definition at line 35 of file ConsoleFormatter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getIO ()\fC [protected]\fP"

.PP
\fBReturns:\fP
.RS 4
\fBIO\fP 
.RE
.PP

.PP
Definition at line 44 of file ConsoleFormatter\&.php\&.
.SS "printException (\fBExampleEvent\fP $event)\fC [protected]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.RE
.PP

.PP
Definition at line 52 of file ConsoleFormatter\&.php\&.
.SS "printSpecificException (\fBExampleEvent\fP $event,  $type)\fC [protected]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.br
\fI$type\fP 
.RE
.PP

.PP
Definition at line 75 of file ConsoleFormatter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
