.TH "PSR0Resource" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PSR0Resource \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBResourceInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $parts, \fBPSR0Locator\fP $locator)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetSpecName\fP ()"
.br
.ti -1c
.RI "\fBgetSrcFilename\fP ()"
.br
.ti -1c
.RI "\fBgetSrcNamespace\fP ()"
.br
.ti -1c
.RI "\fBgetSrcClassname\fP ()"
.br
.ti -1c
.RI "\fBgetSpecFilename\fP ()"
.br
.ti -1c
.RI "\fBgetSpecNamespace\fP ()"
.br
.ti -1c
.RI "\fBgetSpecClassname\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file PSR0Resource\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $parts, \fBPSR0Locator\fP $locator)"

.PP
\fBParameters:\fP
.RS 4
\fI$parts\fP 
.br
\fI$locator\fP 
.RE
.PP

.PP
Definition at line 33 of file PSR0Resource\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getName ()"

.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBResourceInterface\fP\&.
.PP
Definition at line 42 of file PSR0Resource\&.php\&.
.SS "getSpecClassname ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBResourceInterface\fP\&.
.PP
Definition at line 113 of file PSR0Resource\&.php\&.
.SS "getSpecFilename ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBResourceInterface\fP\&.
.PP
Definition at line 89 of file PSR0Resource\&.php\&.
.SS "getSpecName ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBResourceInterface\fP\&.
.PP
Definition at line 50 of file PSR0Resource\&.php\&.
.SS "getSpecNamespace ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBResourceInterface\fP\&.
.PP
Definition at line 102 of file PSR0Resource\&.php\&.
.SS "getSrcClassname ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBResourceInterface\fP\&.
.PP
Definition at line 81 of file PSR0Resource\&.php\&.
.SS "getSrcFilename ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBResourceInterface\fP\&.
.PP
Definition at line 58 of file PSR0Resource\&.php\&.
.SS "getSrcNamespace ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBResourceInterface\fP\&.
.PP
Definition at line 70 of file PSR0Resource\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
