.TH "MatcherNotFoundException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatcherNotFoundException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $keyword, $subject, array $arguments)"
.br
.ti -1c
.RI "\fBgetKeyword\fP ()"
.br
.ti -1c
.RI "\fBgetSubject\fP ()"
.br
.ti -1c
.RI "\fBgetArguments\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBMatcherNotFoundException\fP holds information about matcher not found exception 
.PP
Definition at line 22 of file MatcherNotFoundException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $keyword,  $subject, array $arguments)"

.PP
\fBParameters:\fP
.RS 4
\fI$message\fP 
.br
\fI$keyword\fP 
.br
\fI$subject\fP 
.br
\fI$arguments\fP 
.RE
.PP

.PP
Definition at line 45 of file MatcherNotFoundException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getArguments ()"

.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 73 of file MatcherNotFoundException\&.php\&.
.SS "getKeyword ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 57 of file MatcherNotFoundException\&.php\&.
.SS "getSubject ()"

.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 65 of file MatcherNotFoundException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
