.TH "WrapperInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WrapperInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBObjectBehavior\fP, \fBCollaborator\fP, and \fBSubject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetWrappedObject\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file WrapperInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getWrappedObject ()"

.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBSubject\fP, \fBCollaborator\fP, and \fBObjectBehavior\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
