.TH "PhpSpec\CodeGenerator\Generator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhpSpec\CodeGenerator\Generator \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassGenerator\fP"
.br
.ti -1c
.RI "class \fBCreateObjectTemplate\fP"
.br
.ti -1c
.RI "class \fBExistingConstructorTemplate\fP"
.br
.ti -1c
.RI "interface \fBGeneratorInterface\fP"
.br
.ti -1c
.RI "class \fBMethodGenerator\fP"
.br
.ti -1c
.RI "class \fBNamedConstructorGenerator\fP"
.br
.ti -1c
.RI "class \fBPromptingGenerator\fP"
.br
.ti -1c
.RI "class \fBReturnConstantGenerator\fP"
.br
.ti -1c
.RI "class \fBSpecificationGenerator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
