.TH "ExampleEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Event, and \fBEventInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBExampleNode\fP $example, $time=null, $result=null,\\Exception $exception=null)"
.br
.ti -1c
.RI "\fBgetExample\fP ()"
.br
.ti -1c
.RI "\fBgetSpecification\fP ()"
.br
.ti -1c
.RI "\fBgetSuite\fP ()"
.br
.ti -1c
.RI "\fBgetTitle\fP ()"
.br
.ti -1c
.RI "\fBgetMessage\fP ()"
.br
.ti -1c
.RI "\fBgetBacktrace\fP ()"
.br
.ti -1c
.RI "\fBgetTime\fP ()"
.br
.ti -1c
.RI "\fBgetResult\fP ()"
.br
.ti -1c
.RI "\fBgetException\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBPASSED\fP = 0"
.br
.ti -1c
.RI "const \fBPENDING\fP = 1"
.br
.ti -1c
.RI "const \fBSKIPPED\fP = 2"
.br
.ti -1c
.RI "const \fBFAILED\fP = 3"
.br
.ti -1c
.RI "const \fBBROKEN\fP = 4"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBExampleEvent\fP holds the information about the example event 
.PP
Definition at line 22 of file ExampleEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBExampleNode\fP $example,  $time = \fCnull\fP,  $result = \fCnull\fP, \\Exception $exception = \fCnull\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$example\fP 
.br
\fI$time\fP 
.br
\fI$result\fP 
.br
\fI$exception\fP 
.RE
.PP

.PP
Definition at line 75 of file ExampleEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getBacktrace ()"

.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 127 of file ExampleEvent\&.php\&.
.SS "getExample ()"

.PP
\fBReturns:\fP
.RS 4
ExampleNode 
.RE
.PP

.PP
Definition at line 87 of file ExampleEvent\&.php\&.
.SS "getException ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 151 of file ExampleEvent\&.php\&.
.SS "getMessage ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 119 of file ExampleEvent\&.php\&.
.SS "getResult ()"

.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 143 of file ExampleEvent\&.php\&.
.SS "getSpecification ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 95 of file ExampleEvent\&.php\&.
.SS "getSuite ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.PP
Definition at line 103 of file ExampleEvent\&.php\&.
.SS "getTime ()"

.PP
\fBReturns:\fP
.RS 4
float 
.RE
.PP

.PP
Definition at line 135 of file ExampleEvent\&.php\&.
.SS "getTitle ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 111 of file ExampleEvent\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const BROKEN = 4"
Spec is broken 
.PP
Definition at line 47 of file ExampleEvent\&.php\&.
.SS "const FAILED = 3"
Spec failed 
.PP
Definition at line 42 of file ExampleEvent\&.php\&.
.SS "const PASSED = 0"
Spec passed 
.PP
Definition at line 27 of file ExampleEvent\&.php\&.
.SS "const PENDING = 1"
Spec is pending 
.PP
Definition at line 32 of file ExampleEvent\&.php\&.
.SS "const SKIPPED = 2"
Spec is skipped 
.PP
Definition at line 37 of file ExampleEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
