.TH "BasicFormatter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicFormatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventSubscriberInterface\&.
.PP
Inherited by \fBConsoleFormatter\fP, \fBHtmlFormatter\fP, \fBJUnitFormatter\fP, and \fBTestableBasicFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBPresenterInterface\fP $presenter, \fBIO\fP $\fBio\fP, \fBStatisticsCollector\fP $stats)"
.br
.ti -1c
.RI "\fBbeforeSuite\fP (\fBSuiteEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBafterSuite\fP (\fBSuiteEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBbeforeExample\fP (\fBExampleEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBafterExample\fP (\fBExampleEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBbeforeSpecification\fP (\fBSpecificationEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBafterSpecification\fP (\fBSpecificationEvent\fP $\fBevent\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetSubscribedEvents\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetIO\fP ()"
.br
.ti -1c
.RI "\fBgetPresenter\fP ()"
.br
.ti -1c
.RI "\fBgetStatisticsCollector\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file BasicFormatter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBPresenterInterface\fP $presenter, \fBIO\fP $io, \fBStatisticsCollector\fP $stats)"

.PP
Definition at line 41 of file BasicFormatter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "afterExample (\fBExampleEvent\fP $event)"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.RE
.PP

.PP
Definition at line 110 of file BasicFormatter\&.php\&.
.SS "afterSpecification (\fBSpecificationEvent\fP $event)"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.RE
.PP

.PP
Definition at line 124 of file BasicFormatter\&.php\&.
.SS "afterSuite (\fBSuiteEvent\fP $event)"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.RE
.PP

.PP
Definition at line 96 of file BasicFormatter\&.php\&.
.SS "beforeExample (\fBExampleEvent\fP $event)"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.RE
.PP

.PP
Definition at line 103 of file BasicFormatter\&.php\&.
.SS "beforeSpecification (\fBSpecificationEvent\fP $event)"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.RE
.PP

.PP
Definition at line 117 of file BasicFormatter\&.php\&.
.SS "beforeSuite (\fBSuiteEvent\fP $event)"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.RE
.PP

.PP
Definition at line 89 of file BasicFormatter\&.php\&.
.SS "getIO ()\fC [protected]\fP"

.PP
\fBReturns:\fP
.RS 4
\fBIO\fP 
.RE
.PP

.PP
Definition at line 65 of file BasicFormatter\&.php\&.
.SS "getPresenter ()\fC [protected]\fP"

.PP
\fBReturns:\fP
.RS 4
PresenterInterface 
.RE
.PP

.PP
Definition at line 73 of file BasicFormatter\&.php\&.
.SS "getStatisticsCollector ()\fC [protected]\fP"

.PP
\fBReturns:\fP
.RS 4
StatisticsCollector 
.RE
.PP

.PP
Definition at line 81 of file BasicFormatter\&.php\&.
.SS "static getSubscribedEvents ()\fC [static]\fP"

.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 51 of file BasicFormatter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
