.TH "FailureException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FailureException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMatcherException\fP\&.
.PP
Inherited by \fBNotEqualException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class \fBFailureException\fP holds information about example failure exception 
.PP
Definition at line 19 of file FailureException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
