.TH "Template" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Template \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTemplate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrender\fP ($\fBtext\fP, array $templateVars=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Template\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "render ( $text, array $templateVars = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$text\fP 
.br
\fI$templateVars\fP 
.RE
.PP

.PP
Implemented in \fBTemplate\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
