.TH "ExceptionFactory" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExceptionFactory \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBnamedConstructorNotFound\fP ($classname, $method, array $arguments=array())"
.br
.ti -1c
.RI "\fBmethodNotFound\fP ($classname, $method, array $arguments=array())"
.br
.ti -1c
.RI "\fBmethodNotVisible\fP ($classname, $method, array $arguments=array())"
.br
.ti -1c
.RI "\fBclassNotFound\fP ($classname)"
.br
.ti -1c
.RI "\fBpropertyNotFound\fP ($subject, $\fBproperty\fP)"
.br
.ti -1c
.RI "\fBcallingMethodOnNonObject\fP ($method)"
.br
.ti -1c
.RI "\fBsettingPropertyOnNonObject\fP ($\fBproperty\fP)"
.br
.ti -1c
.RI "\fBgettingPropertyOnNonObject\fP ($\fBproperty\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBExceptionFactory\fP is responsible for creating various exceptions 
.PP
Definition at line 23 of file ExceptionFactory\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBPresenterInterface\fP $presenter)"

.PP
\fBParameters:\fP
.RS 4
\fI$presenter\fP 
.RE
.PP

.PP
Definition at line 33 of file ExceptionFactory\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "callingMethodOnNonObject ( $method)"

.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
SubjectException 
.RE
.PP

.PP
Definition at line 123 of file ExceptionFactory\&.php\&.
.SS "classNotFound ( $classname)"

.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFracture\fP 
.RE
.PP

.PP
Definition at line 98 of file ExceptionFactory\&.php\&.
.SS "gettingPropertyOnNonObject ( $property)"

.PP
\fBParameters:\fP
.RS 4
\fI$property\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
SubjectException 
.RE
.PP

.PP
Definition at line 149 of file ExceptionFactory\&.php\&.
.SS "methodNotFound ( $classname,  $method, array $arguments = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.br
\fI$method\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFracture\fP 
.RE
.PP

.PP
Definition at line 64 of file ExceptionFactory\&.php\&.
.SS "methodNotVisible ( $classname,  $method, array $arguments = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.br
\fI$method\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFracture\fP 
.RE
.PP

.PP
Definition at line 82 of file ExceptionFactory\&.php\&.
.SS "namedConstructorNotFound ( $classname,  $method, array $arguments = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.br
\fI$method\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFracture\fP 
.RE
.PP

.PP
Definition at line 45 of file ExceptionFactory\&.php\&.
.SS "propertyNotFound ( $subject,  $property)"

.PP
\fBParameters:\fP
.RS 4
\fI$subject\fP 
.br
\fI$property\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBFracture\fP 
.RE
.PP

.PP
Definition at line 111 of file ExceptionFactory\&.php\&.
.SS "settingPropertyOnNonObject ( $property)"

.PP
\fBParameters:\fP
.RS 4
\fI$property\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
SubjectException 
.RE
.PP

.PP
Definition at line 136 of file ExceptionFactory\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
