.TH "ArrayEngine" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArrayEngine \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStringEngine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsupports\fP ($expected, $actual)"
.br
.ti -1c
.RI "\fBcompare\fP ($expected, $actual)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ArrayEngine\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "compare ( $expected,  $actual)"

.PP
\fBParameters:\fP
.RS 4
\fI$expected\fP 
.br
\fI$actual\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBEngineInterface\fP\&.
.PP
Definition at line 23 of file ArrayEngine\&.php\&.
.SS "supports ( $expected,  $actual)"

.PP
\fBParameters:\fP
.RS 4
\fI$expected\fP 
.br
\fI$actual\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBEngineInterface\fP\&.
.PP
Definition at line 18 of file ArrayEngine\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
