.TH "CollaboratorManager" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CollaboratorManager \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBset\fP ($\fBname\fP, $collaborator)"
.br
.ti -1c
.RI "\fBhas\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBget\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBgetArgumentsFor\fP (ReflectionFunctionAbstract $function)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file CollaboratorManager\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBPresenterInterface\fP $presenter)"

.PP
\fBParameters:\fP
.RS 4
\fI$presenter\fP 
.RE
.PP

.PP
Definition at line 35 of file CollaboratorManager\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "get ( $name)"

.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
Collaborator
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 66 of file CollaboratorManager\&.php\&.
.SS "getArgumentsFor (ReflectionFunctionAbstract $function)"

.PP
\fBParameters:\fP
.RS 4
\fI$function\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 82 of file CollaboratorManager\&.php\&.
.SS "has ( $name)"

.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 54 of file CollaboratorManager\&.php\&.
.SS "set ( $name,  $collaborator)"

.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$collaborator\fP 
.RE
.PP

.PP
Definition at line 44 of file CollaboratorManager\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
