.TH "ClassNotFoundException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassNotFoundException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFractureException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $classname)"
.br
.ti -1c
.RI "\fBgetClassname\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class \fBClassNotFoundException\fP holds information about class not found exception 
.PP
Definition at line 19 of file ClassNotFoundException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $classname)"

.PP
\fBParameters:\fP
.RS 4
\fI$message\fP 
.br
\fI$classname\fP 
.RE
.PP

.PP
Definition at line 30 of file ClassNotFoundException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getClassname ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 40 of file ClassNotFoundException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
