.TH "FractureException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FractureException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBException\fP\&.
.PP
Inherited by \fBClassNotFoundException\fP, \fBFactoryDoesNotReturnObjectException\fP, \fBInterfaceNotImplementedException\fP, \fBMethodInvocationException\fP, and \fBPropertyNotFoundException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class \fBFractureException\fP holds information about fracture exception 
.PP
Definition at line 21 of file FractureException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
