.TH "PhpSpec\Wrapper\Subject\Expectation" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhpSpec\Wrapper\Subject\Expectation \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBConstructorDecorator\fP"
.br
.ti -1c
.RI "class \fBDecorator\fP"
.br
.ti -1c
.RI "class \fBDispatcherDecorator\fP"
.br
.ti -1c
.RI "class \fBDuringCall\fP"
.br
.ti -1c
.RI "interface \fBExpectationInterface\fP"
.br
.ti -1c
.RI "class \fBNegative\fP"
.br
.ti -1c
.RI "class \fBNegativeThrow\fP"
.br
.ti -1c
.RI "class \fBPositive\fP"
.br
.ti -1c
.RI "class \fBPositiveThrow\fP"
.br
.ti -1c
.RI "interface \fBThrowExpectation\fP"
.br
.ti -1c
.RI "class \fBUnwrapDecorator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
