.TH "FactoryDoesNotReturnObjectException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FactoryDoesNotReturnObjectException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFractureException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file FactoryDoesNotReturnObjectException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
