.TH "StopOnFailureListener" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StopOnFailureListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventSubscriberInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBIO\fP $\fBio\fP)"
.br
.ti -1c
.RI "\fBafterExample\fP (\fBExampleEvent\fP $\fBevent\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetSubscribedEvents\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file StopOnFailureListener\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBIO\fP $io)"

.PP
\fBParameters:\fP
.RS 4
\fI$io\fP 
.RE
.PP

.PP
Definition at line 31 of file StopOnFailureListener\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "afterExample (\fBExampleEvent\fP $event)"

.PP
\fBParameters:\fP
.RS 4
\fI$event\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 51 of file StopOnFailureListener\&.php\&.
.SS "static getSubscribedEvents ()\fC [static]\fP"

.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 39 of file StopOnFailureListener\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
