.TH "Formatter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Formatter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOutputFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($decorated=false, array $styles=array())"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class \fBFormatter\fP is responsible for configuring the console output formatting style 
.PP
Definition at line 23 of file Formatter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $decorated = \fCfalse\fP, array $styles = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$decorated\fP 
.br
\fI$styles\fP 
.RE
.PP

.PP
Definition at line 30 of file Formatter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
