.TH "Template" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Template \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTemplate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBIOInterface\fP $\fBio\fP)"
.br
.ti -1c
.RI "\fBrender\fP ($\fBtext\fP, array $templateVars=array())"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBDIR\fP = __DIR__"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file Template\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBIOInterface\fP $io)"

.PP
\fBParameters:\fP
.RS 4
\fI$io\fP 
.RE
.PP

.PP
Definition at line 31 of file Template\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "render ( $text, array $templateVars = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$text\fP 
.br
\fI$templateVars\fP 
.RE
.PP

.PP
Implements \fBTemplate\fP\&.
.PP
Definition at line 40 of file Template\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const DIR = __DIR__"

.PP
Definition at line 21 of file Template\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
