.TH "MatcherException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatcherException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBExampleException\fP\&.
.PP
Inherited by \fBFailureException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Class \fBMatcherException\fP holds information about matcher failure exception 
.PP
Definition at line 19 of file MatcherException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
