.TH "WrappedObject" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WrappedObject \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($instance, \fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBbeAnInstanceOf\fP ($classname, array $arguments=array())"
.br
.ti -1c
.RI "\fBbeConstructedWith\fP ($args)"
.br
.ti -1c
.RI "\fBbeConstructedThrough\fP ($factoryMethod, array $arguments=array())"
.br
.ti -1c
.RI "\fBgetFactoryMethod\fP ()"
.br
.ti -1c
.RI "\fBisInstantiated\fP ()"
.br
.ti -1c
.RI "\fBsetInstantiated\fP ($instantiated)"
.br
.ti -1c
.RI "\fBgetClassName\fP ()"
.br
.ti -1c
.RI "\fBsetClassName\fP ($classname)"
.br
.ti -1c
.RI "\fBgetArguments\fP ()"
.br
.ti -1c
.RI "\fBgetInstance\fP ()"
.br
.ti -1c
.RI "\fBsetInstance\fP ($instance)"
.br
.ti -1c
.RI "\fBinstantiate\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file WrappedObject\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $instance, \fBPresenterInterface\fP $presenter)"

.PP
\fBParameters:\fP
.RS 4
\fI$instance\fP 
.br
\fI$presenter\fP 
.RE
.PP

.PP
Definition at line 52 of file WrappedObject\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "beAnInstanceOf ( $classname, array $arguments = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 68 of file WrappedObject\&.php\&.
.SS "beConstructedThrough ( $factoryMethod, array $arguments = \fCarray()\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$factoryMethod\fP 
.br
\fI$arguments\fP 
.RE
.PP

.PP
Definition at line 109 of file WrappedObject\&.php\&.
.SS "beConstructedWith ( $args)"

.PP
\fBParameters:\fP
.RS 4
\fI$args\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 89 of file WrappedObject\&.php\&.
.SS "getArguments ()"

.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 171 of file WrappedObject\&.php\&.
.SS "getClassName ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 155 of file WrappedObject\&.php\&.
.SS "getFactoryMethod ()"

.PP
\fBReturns:\fP
.RS 4
callable|null 
.RE
.PP

.PP
Definition at line 131 of file WrappedObject\&.php\&.
.SS "getInstance ()"

.PP
\fBReturns:\fP
.RS 4
object|null 
.RE
.PP

.PP
Definition at line 179 of file WrappedObject\&.php\&.
.SS "instantiate ()"

.PP
\fBReturns:\fP
.RS 4
object 
.RE
.PP

.PP
Definition at line 195 of file WrappedObject\&.php\&.
.SS "isInstantiated ()"

.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 139 of file WrappedObject\&.php\&.
.SS "setClassName ( $classname)"

.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.RE
.PP

.PP
Definition at line 163 of file WrappedObject\&.php\&.
.SS "setInstance ( $instance)"

.PP
\fBParameters:\fP
.RS 4
\fI$instance\fP 
.RE
.PP

.PP
Definition at line 187 of file WrappedObject\&.php\&.
.SS "setInstantiated ( $instantiated)"

.PP
\fBParameters:\fP
.RS 4
\fI$instantiated\fP 
.RE
.PP

.PP
Definition at line 147 of file WrappedObject\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
