.TH "PHPUnit_Extensions_PhptTestCase" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Extensions_PhptTestCase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_Test\fP, and \fBPHPUnit_Framework_SelfDescribing\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($filename)"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.ti -1c
.RI "\fBrun\fP (\fBPHPUnit_Framework_TestResult\fP $result=null)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file PhptTestCase\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $filename)"
Constructs a test case with the given filename\&.
.PP
\fBParameters:\fP
.RS 4
\fI$filename\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPHPUnit_Framework_Exception\fP\fP 
.RE
.PP

.PP
Definition at line 62 of file PhptTestCase\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "count ()"
Counts the number of test cases executed by run(TestResult result)\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 85 of file PhptTestCase\&.php\&.
.SS "getName ()"
Returns the name of the test case\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 162 of file PhptTestCase\&.php\&.
.SS "run (\fBPHPUnit_Framework_TestResult\fP $result = \fCnull\fP)"
Runs a test and collects its result in a TestResult instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$result\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_TestResult\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_Test\fP\&.
.PP
Definition at line 96 of file PhptTestCase\&.php\&.
.SS "toString ()"
Returns a string representation of the test case\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_SelfDescribing\fP\&.
.PP
Definition at line 172 of file PhptTestCase\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
