.TH "PHPUnit_Framework_Constraint_Xor" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_Constraint_Xor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_Constraint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetConstraints\fP (array $constraints)"
.br
.ti -1c
.RI "\fBevaluate\fP ($other, $description= '', $returnResult=false)"
.br
.ti -1c
.RI "\fBtoString\fP ()"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$constraints\fP = array()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file Xor\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "count ()"
Counts the number of constraint elements\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 3\&.4\&.0 
.RE
.PP

.PP
Definition at line 116 of file Xor\&.php\&.
.SS "evaluate ( $other,  $description = \fC''\fP,  $returnResult = \fCfalse\fP)"
Evaluates the constraint for parameter $other
.PP
If $returnResult is set to false (the default), an exception is thrown in case of a failure\&. null is returned otherwise\&.
.PP
If $returnResult is true, the result of the evaluation is returned as a boolean value instead: true in case of success, false in case of a failure\&.
.PP
\fBParameters:\fP
.RS 4
\fI$other\fP Value or object to evaluate\&. 
.br
\fI$description\fP Additional information about the test 
.br
\fI$returnResult\fP Whether to return a result or throw an exception 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPHPUnit_Framework_ExpectationFailedException\fP\fP 
.RE
.PP

.PP
Definition at line 64 of file Xor\&.php\&.
.SS "setConstraints (array $constraints)"

.PP
\fBParameters:\fP
.RS 4
\fIPHPUnit_Framework_Constraint[]\fP $constraints 
.RE
.PP

.PP
Definition at line 33 of file Xor\&.php\&.
.SS "toString ()"
Returns a string representation of the constraint\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_SelfDescribing\fP\&.
.PP
Definition at line 95 of file Xor\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$constraints = array()\fC [protected]\fP"

.PP
Definition at line 28 of file Xor\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
