.TH "PHPUnit_Extensions_RepeatedTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Extensions_RepeatedTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Extensions_TestDecorator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBPHPUnit_Framework_Test\fP $test, $timesRepeat=1, $processIsolation=false)"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.ti -1c
.RI "\fBrun\fP (\fBPHPUnit_Framework_TestResult\fP $result=null)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$filter\fP = false"
.br
.ti -1c
.RI "\fB$groups\fP = array()"
.br
.ti -1c
.RI "\fB$excludeGroups\fP = array()"
.br
.ti -1c
.RI "\fB$processIsolation\fP = false"
.br
.ti -1c
.RI "\fB$timesRepeat\fP = 1"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file RepeatedTest\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBPHPUnit_Framework_Test\fP $test,  $timesRepeat = \fC1\fP,  $processIsolation = \fCfalse\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$timesRepeat\fP 
.br
\fI$processIsolation\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPHPUnit_Framework_Exception\fP\fP 
.RE
.PP

.PP
Definition at line 54 of file RepeatedTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "count ()"
Counts the number of test cases that will be run by this test\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 77 of file RepeatedTest\&.php\&.
.SS "run (\fBPHPUnit_Framework_TestResult\fP $result = \fCnull\fP)"
Runs the decorated test and collects the result in a TestResult\&.
.PP
\fBParameters:\fP
.RS 4
\fI$result\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_TestResult\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPHPUnit_Framework_Exception\fP\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_Test\fP\&.
.PP
Definition at line 90 of file RepeatedTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$excludeGroups = array()\fC [protected]\fP"

.PP
Definition at line 36 of file RepeatedTest\&.php\&.
.SS "$\fBfilter\fP = false\fC [protected]\fP"

.PP
Definition at line 26 of file RepeatedTest\&.php\&.
.SS "$groups = array()\fC [protected]\fP"

.PP
Definition at line 31 of file RepeatedTest\&.php\&.
.SS "$processIsolation = false\fC [protected]\fP"

.PP
Definition at line 41 of file RepeatedTest\&.php\&.
.SS "$timesRepeat = 1\fC [protected]\fP"

.PP
Definition at line 46 of file RepeatedTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
