.TH "PHPUnit_Util_Log_JSON" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Util_Log_JSON \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Util_Printer\fP, and \fBPHPUnit_Framework_TestListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaddError\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddFailure\fP (\fBPHPUnit_Framework_Test\fP $test, \fBPHPUnit_Framework_AssertionFailedError\fP $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddIncompleteTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddRiskyTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddSkippedTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBstartTestSuite\fP (\fBPHPUnit_Framework_TestSuite\fP $suite)"
.br
.ti -1c
.RI "\fBendTestSuite\fP (\fBPHPUnit_Framework_TestSuite\fP $suite)"
.br
.ti -1c
.RI "\fBstartTest\fP (\fBPHPUnit_Framework_Test\fP $test)"
.br
.ti -1c
.RI "\fBendTest\fP (\fBPHPUnit_Framework_Test\fP $test, $time)"
.br
.ti -1c
.RI "\fBwrite\fP ($buffer)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwriteCase\fP ($status, $time, array $trace=array(), $message= '', $test=null)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$currentTestSuiteName\fP = ''"
.br
.ti -1c
.RI "\fB$currentTestName\fP = ''"
.br
.ti -1c
.RI "\fB$currentTestPass\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file JSON\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addError (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
An error occurred\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 51 of file JSON\&.php\&.
.SS "addFailure (\fBPHPUnit_Framework_Test\fP $test, \fBPHPUnit_Framework_AssertionFailedError\fP $e,  $time)"
\fBA\fP failure occurred\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 71 of file JSON\&.php\&.
.SS "addIncompleteTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Incomplete test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 91 of file JSON\&.php\&.
.SS "addRiskyTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Risky test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 4\&.0\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 112 of file JSON\&.php\&.
.SS "addSkippedTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Skipped test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 132 of file JSON\&.php\&.
.SS "endTest (\fBPHPUnit_Framework_Test\fP $test,  $time)"
\fBA\fP test ended\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 200 of file JSON\&.php\&.
.SS "endTestSuite (\fBPHPUnit_Framework_TestSuite\fP $suite)"
\fBA\fP testsuite ended\&.
.PP
\fBParameters:\fP
.RS 4
\fI$suite\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 169 of file JSON\&.php\&.
.SS "startTest (\fBPHPUnit_Framework_Test\fP $test)"
\fBA\fP test started\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 180 of file JSON\&.php\&.
.SS "startTestSuite (\fBPHPUnit_Framework_TestSuite\fP $suite)"
\fBA\fP testsuite started\&.
.PP
\fBParameters:\fP
.RS 4
\fI$suite\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 150 of file JSON\&.php\&.
.SS "write ( $buffer)"

.PP
\fBParameters:\fP
.RS 4
\fI$buffer\fP 
.RE
.PP

.PP
Definition at line 238 of file JSON\&.php\&.
.SS "writeCase ( $status,  $time, array $trace = \fCarray()\fP,  $message = \fC''\fP,  $test = \fCnull\fP)\fC [protected]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$status\fP 
.br
\fI$time\fP 
.br
\fI$trace\fP 
.br
\fI$message\fP 
.br
\fI$test\fP 
.RE
.PP

.PP
Definition at line 214 of file JSON\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$currentTestName = ''\fC [protected]\fP"

.PP
Definition at line 36 of file JSON\&.php\&.
.SS "$currentTestPass = true\fC [protected]\fP"

.PP
Definition at line 42 of file JSON\&.php\&.
.SS "$currentTestSuiteName = ''\fC [protected]\fP"

.PP
Definition at line 31 of file JSON\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
