.TH "PHPUnit_Framework_Test" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_Test \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Countable\&.
.PP
Inherited by \fBDoubleTestCase\fP, \fBPHPUnit_Extensions_PhptTestCase\fP, \fBPHPUnit_Extensions_TestDecorator\fP, \fBPHPUnit_Framework_TestCase\fP, and \fBPHPUnit_Framework_TestSuite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrun\fP (\fBPHPUnit_Framework_TestResult\fP $result=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Test\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "run (\fBPHPUnit_Framework_TestResult\fP $result = \fCnull\fP)"
Runs a test and collects its result in a TestResult instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$result\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_TestResult\fP 
.RE
.PP

.PP
Implemented in \fBPHPUnit_Framework_TestSuite\fP, \fBPHPUnit_Framework_TestCase\fP, \fBPHPUnit_Extensions_TestDecorator\fP, \fBPHPUnit_Extensions_PhptTestCase\fP, \fBPHPUnit_Extensions_RepeatedTest\fP, and \fBDoubleTestCase\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
