.TH "PHPUnit_Framework_MockObject_Invocation_Object" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_MockObject_Invocation_Object \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_MockObject_Invocation_Static\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($className, $methodName, array $parameters, $object, $cloneObjects=FALSE)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$object\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file Object\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $className,  $methodName, array $parameters,  $object,  $cloneObjects = \fCFALSE\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$className\fP 
.br
\fI$methodname\fP 
.br
\fI$parameters\fP 
.br
\fI$object\fP 
.br
\fI$cloneObjects\fP 
.RE
.PP

.PP
Definition at line 36 of file Object\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$object"

.PP
Definition at line 27 of file Object\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
