.TH "PHPUnit_Framework_MockObject_Builder_Match" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_MockObject_Builder_Match \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_MockObject_Builder_Stub\fP\&.
.PP
Inherited by \fBPHPUnit_Framework_MockObject_Builder_ParametersMatch\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBafter\fP ($\fBid\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Match\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "after ( $id)"
Defines the expectation which must occur before the current is valid\&.
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP The identification of the expectation that should occur before this one\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_MockObject_Builder_Stub\fP 
.RE
.PP

.PP
Implemented in \fBPHPUnit_Framework_MockObject_Builder_InvocationMocker\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
