.TH "PHPUnit_Runner_Exception" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Runner_Exception \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException, and \fBPHPUnit_Exception\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 20 of file Exception\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
