.TH "PHPUnit_Util_TestDox_ResultPrinter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Util_TestDox_ResultPrinter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Util_Printer\fP, and \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Inherited by \fBPHPUnit_Util_TestDox_ResultPrinter_HTML\fP, and \fBPHPUnit_Util_TestDox_ResultPrinter_Text\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($out=null)"
.br
.ti -1c
.RI "\fBflush\fP ()"
.br
.ti -1c
.RI "\fBaddError\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddFailure\fP (\fBPHPUnit_Framework_Test\fP $test, \fBPHPUnit_Framework_AssertionFailedError\fP $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddIncompleteTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddRiskyTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddSkippedTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBstartTestSuite\fP (\fBPHPUnit_Framework_TestSuite\fP $suite)"
.br
.ti -1c
.RI "\fBendTestSuite\fP (\fBPHPUnit_Framework_TestSuite\fP $suite)"
.br
.ti -1c
.RI "\fBstartTest\fP (\fBPHPUnit_Framework_Test\fP $test)"
.br
.ti -1c
.RI "\fBendTest\fP (\fBPHPUnit_Framework_Test\fP $test, $time)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBdoEndClass\fP ()"
.br
.ti -1c
.RI "\fBstartRun\fP ()"
.br
.ti -1c
.RI "\fBstartClass\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBonTest\fP ($\fBname\fP, $success=true)"
.br
.ti -1c
.RI "\fBendClass\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBendRun\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$prettifier\fP"
.br
.ti -1c
.RI "\fB$testClass\fP = ''"
.br
.ti -1c
.RI "\fB$testStatus\fP = false"
.br
.ti -1c
.RI "\fB$tests\fP = array()"
.br
.ti -1c
.RI "\fB$successful\fP = 0"
.br
.ti -1c
.RI "\fB$failed\fP = 0"
.br
.ti -1c
.RI "\fB$risky\fP = 0"
.br
.ti -1c
.RI "\fB$skipped\fP = 0"
.br
.ti -1c
.RI "\fB$incomplete\fP = 0"
.br
.ti -1c
.RI "\fB$testTypeOfInterest\fP = '\fBPHPUnit_Framework_TestCase\fP'"
.br
.ti -1c
.RI "\fB$currentTestClassPrettified\fP"
.br
.ti -1c
.RI "\fB$currentTestMethodPrettified\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file ResultPrinter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $out = \fCnull\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$out\fP 
.RE
.PP

.PP
Definition at line 89 of file ResultPrinter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addError (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
An error occurred\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 116 of file ResultPrinter\&.php\&.
.SS "addFailure (\fBPHPUnit_Framework_Test\fP $test, \fBPHPUnit_Framework_AssertionFailedError\fP $e,  $time)"
\fBA\fP failure occurred\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 131 of file ResultPrinter\&.php\&.
.SS "addIncompleteTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Incomplete test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 146 of file ResultPrinter\&.php\&.
.SS "addRiskyTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Risky test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 4\&.0\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 162 of file ResultPrinter\&.php\&.
.SS "addSkippedTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Skipped test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 3\&.0\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 178 of file ResultPrinter\&.php\&.
.SS "doEndClass ()\fC [protected]\fP"

.PP
\fBSince:\fP
.RS 4
Method available since Release 2\&.3\&.0 
.RE
.PP

.PP
Definition at line 281 of file ResultPrinter\&.php\&.
.SS "endClass ( $name)\fC [protected]\fP"
Handler for 'end class' event\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP

.PP
Definition at line 322 of file ResultPrinter\&.php\&.
.SS "endRun ()\fC [protected]\fP"
Handler for 'end run' event\&. 
.PP
Definition at line 330 of file ResultPrinter\&.php\&.
.SS "endTest (\fBPHPUnit_Framework_Test\fP $test,  $time)"
\fBA\fP test ended\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 254 of file ResultPrinter\&.php\&.
.SS "endTestSuite (\fBPHPUnit_Framework_TestSuite\fP $suite)"
\fBA\fP testsuite ended\&.
.PP
\fBParameters:\fP
.RS 4
\fI$suite\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 2\&.2\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 202 of file ResultPrinter\&.php\&.
.SS "flush ()"
Flush buffer and close output\&. 
.PP
Definition at line 101 of file ResultPrinter\&.php\&.
.SS "onTest ( $name,  $success = \fCtrue\fP)\fC [protected]\fP"
Handler for 'on test' event\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$success\fP 
.RE
.PP

.PP
Definition at line 313 of file ResultPrinter\&.php\&.
.SS "startClass ( $name)\fC [protected]\fP"
Handler for 'start class' event\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP

.PP
Definition at line 303 of file ResultPrinter\&.php\&.
.SS "startRun ()\fC [protected]\fP"
Handler for 'start run' event\&. 
.PP
Definition at line 294 of file ResultPrinter\&.php\&.
.SS "startTest (\fBPHPUnit_Framework_Test\fP $test)"
\fBA\fP test started\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 211 of file ResultPrinter\&.php\&.
.SS "startTestSuite (\fBPHPUnit_Framework_TestSuite\fP $suite)"
\fBA\fP testsuite started\&.
.PP
\fBParameters:\fP
.RS 4
\fI$suite\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 2\&.2\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 192 of file ResultPrinter\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$currentTestClassPrettified\fC [protected]\fP"

.PP
Definition at line 77 of file ResultPrinter\&.php\&.
.SS "$currentTestMethodPrettified\fC [protected]\fP"

.PP
Definition at line 82 of file ResultPrinter\&.php\&.
.SS "$failed = 0\fC [protected]\fP"

.PP
Definition at line 52 of file ResultPrinter\&.php\&.
.SS "$incomplete = 0\fC [protected]\fP"

.PP
Definition at line 67 of file ResultPrinter\&.php\&.
.SS "$prettifier\fC [protected]\fP"

.PP
Definition at line 27 of file ResultPrinter\&.php\&.
.SS "$risky = 0\fC [protected]\fP"

.PP
Definition at line 57 of file ResultPrinter\&.php\&.
.SS "$skipped = 0\fC [protected]\fP"

.PP
Definition at line 62 of file ResultPrinter\&.php\&.
.SS "$successful = 0\fC [protected]\fP"

.PP
Definition at line 47 of file ResultPrinter\&.php\&.
.SS "$testClass = ''\fC [protected]\fP"

.PP
Definition at line 32 of file ResultPrinter\&.php\&.
.SS "$tests = array()\fC [protected]\fP"

.PP
Definition at line 42 of file ResultPrinter\&.php\&.
.SS "$testStatus = false\fC [protected]\fP"

.PP
Definition at line 37 of file ResultPrinter\&.php\&.
.SS "$testTypeOfInterest = '\fBPHPUnit_Framework_TestCase\fP'\fC [protected]\fP"

.PP
Definition at line 72 of file ResultPrinter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
