.TH "PHPUnit_Extensions_PhptTestSuite" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Extensions_PhptTestSuite \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestSuite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($directory, array $\fBoptions\fP=array())"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file PhptTestSuite\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $directory, array $options = \fCarray()\fP)"
Constructs a new TestSuite for \&.phpt test cases\&.
.PP
\fBParameters:\fP
.RS 4
\fI$directory\fP 
.br
\fI$options\fP Array with ini settings for the php instance run, key being the name if the setting, value the ini value\&. 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPHPUnit_Framework_Exception\fP\fP 
.RE
.PP

.PP
Definition at line 32 of file PhptTestSuite\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
