.TH "PHPUnit_Framework_Error" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_Error \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_Exception\fP\&.
.PP
Inherited by \fBPHPUnit_Framework_Error_Deprecated\fP, \fBPHPUnit_Framework_Error_Notice\fP, and \fBPHPUnit_Framework_Error_Warning\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $code, $file, $\fBline\fP, Exception $previous=null)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file Error\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $code,  $file,  $line, Exception $previous = \fCnull\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$message\fP 
.br
\fI$code\fP 
.br
\fI$file\fP 
.br
\fI$line\fP 
.br
\fI$previous\fP 
.RE
.PP

.PP
Definition at line 33 of file Error\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
