.TH "PHPUnit_Util_Filter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Util_Filter \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetFilteredStacktrace\fP (Exception $\fBe\fP, $asString=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Filter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getFilteredStacktrace (Exception $e,  $asString = \fCtrue\fP)\fC [static]\fP"
Filters stack frames from \fBPHPUnit\fP classes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$e\fP 
.br
\fI$asString\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 31 of file Filter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
