.TH "PHPUnit_Extensions_TestDecorator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Extensions_TestDecorator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_Assert\fP, \fBPHPUnit_Framework_Test\fP, and \fBPHPUnit_Framework_SelfDescribing\fP\&.
.PP
Inherited by \fBPHPUnit_Extensions_RepeatedTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBPHPUnit_Framework_Test\fP $test)"
.br
.ti -1c
.RI "\fBtoString\fP ()"
.br
.ti -1c
.RI "\fBbasicRun\fP (\fBPHPUnit_Framework_TestResult\fP $result)"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.ti -1c
.RI "\fBgetTest\fP ()"
.br
.ti -1c
.RI "\fBrun\fP (\fBPHPUnit_Framework_TestResult\fP $result=null)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateResult\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$test\fP = null"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file TestDecorator\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBPHPUnit_Framework_Test\fP $test)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.RE
.PP

.PP
Definition at line 40 of file TestDecorator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "basicRun (\fBPHPUnit_Framework_TestResult\fP $result)"
Runs the test and collects the result in a TestResult\&.
.PP
\fBParameters:\fP
.RS 4
\fI$result\fP 
.RE
.PP

.PP
Definition at line 61 of file TestDecorator\&.php\&.
.SS "count ()"
Counts the number of test cases that will be run by this test\&.
.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 72 of file TestDecorator\&.php\&.
.SS "createResult ()\fC [protected]\fP"
Creates a default TestResult object\&.
.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_TestResult\fP 
.RE
.PP

.PP
Definition at line 82 of file TestDecorator\&.php\&.
.SS "getTest ()"
Returns the test to be run\&.
.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_Test\fP 
.RE
.PP

.PP
Definition at line 92 of file TestDecorator\&.php\&.
.SS "run (\fBPHPUnit_Framework_TestResult\fP $result = \fCnull\fP)"
Runs the decorated test and collects the result in a TestResult\&.
.PP
\fBParameters:\fP
.RS 4
\fI$result\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_TestResult\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_Test\fP\&.
.PP
Definition at line 104 of file TestDecorator\&.php\&.
.SS "toString ()"
Returns a string representation of the test\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_SelfDescribing\fP\&.
.PP
Definition at line 50 of file TestDecorator\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$test = null\fC [protected]\fP"

.PP
Definition at line 33 of file TestDecorator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
