.TH "PHPUnit_Util_TestDox_NamePrettifier" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Util_TestDox_NamePrettifier \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprettifyTestClass\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBprettifyTestMethod\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBsetPrefix\fP ($prefix)"
.br
.ti -1c
.RI "\fBsetSuffix\fP ($suffix)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$prefix\fP = 'Test'"
.br
.ti -1c
.RI "\fB$suffix\fP = 'Test'"
.br
.ti -1c
.RI "\fB$strings\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file NamePrettifier\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "prettifyTestClass ( $name)"
Prettifies the name of a test class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 45 of file NamePrettifier\&.php\&.
.SS "prettifyTestMethod ( $name)"
Prettifies the name of a test method\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 72 of file NamePrettifier\&.php\&.
.SS "setPrefix ( $prefix)"
Sets the prefix of test names\&.
.PP
\fBParameters:\fP
.RS 4
\fI$prefix\fP 
.RE
.PP

.PP
Definition at line 132 of file NamePrettifier\&.php\&.
.SS "setSuffix ( $suffix)"
Sets the suffix of test names\&.
.PP
\fBParameters:\fP
.RS 4
\fI$suffix\fP 
.RE
.PP

.PP
Definition at line 142 of file NamePrettifier\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$prefix = 'Test'\fC [protected]\fP"

.PP
Definition at line 27 of file NamePrettifier\&.php\&.
.SS "$strings = array()\fC [protected]\fP"

.PP
Definition at line 37 of file NamePrettifier\&.php\&.
.SS "$suffix = 'Test'\fC [protected]\fP"

.PP
Definition at line 32 of file NamePrettifier\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
