.TH "PHPUnit_Framework_MockObject_Stub_MatcherCollection" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_MockObject_Stub_MatcherCollection \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPHPUnit_Framework_MockObject_InvocationMocker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaddMatcher\fP (\fBPHPUnit_Framework_MockObject_Matcher_Invocation\fP $matcher)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file MatcherCollection\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addMatcher (\fBPHPUnit_Framework_MockObject_Matcher_Invocation\fP $matcher)"
Adds a new matcher to the collection which can be used as an expectation or a stub\&.
.PP
\fBParameters:\fP
.RS 4
\fI$matcher\fP \fBMatcher\fP for invocations to mock objects\&. 
.RE
.PP

.PP
Implemented in \fBPHPUnit_Framework_MockObject_InvocationMocker\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
