.TH "PHPUnit_Util_Filesystem" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Util_Filesystem \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBclassNameToFilename\fP ($className)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$buffer\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Filesystem\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static classNameToFilename ( $className)\fC [static]\fP"
Maps class names to source file names:
.IP "\(bu" 2
PEAR CS: Foo_Bar_Baz -> Foo/Bar/Baz\&.php
.IP "\(bu" 2
Namespace: \fBFoo\fP -> Foo/Bar/Baz\&.php
.PP
.PP
\fBParameters:\fP
.RS 4
\fI$className\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 3\&.4\&.0 
.RE
.PP

.PP
Definition at line 38 of file Filesystem\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$buffer = array()\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 27 of file Filesystem\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
