.TH "PHPUnit_Util_Log_JUnit" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Util_Log_JUnit \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Util_Printer\fP, and \fBPHPUnit_Framework_TestListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($out=null, $logIncompleteSkipped=false)"
.br
.ti -1c
.RI "\fBflush\fP ()"
.br
.ti -1c
.RI "\fBaddError\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddFailure\fP (\fBPHPUnit_Framework_Test\fP $test, \fBPHPUnit_Framework_AssertionFailedError\fP $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddIncompleteTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddRiskyTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBaddSkippedTest\fP (\fBPHPUnit_Framework_Test\fP $test, Exception $\fBe\fP, $time)"
.br
.ti -1c
.RI "\fBstartTestSuite\fP (\fBPHPUnit_Framework_TestSuite\fP $suite)"
.br
.ti -1c
.RI "\fBendTestSuite\fP (\fBPHPUnit_Framework_TestSuite\fP $suite)"
.br
.ti -1c
.RI "\fBstartTest\fP (\fBPHPUnit_Framework_Test\fP $test)"
.br
.ti -1c
.RI "\fBendTest\fP (\fBPHPUnit_Framework_Test\fP $test, $time)"
.br
.ti -1c
.RI "\fBgetXML\fP ()"
.br
.ti -1c
.RI "\fBsetWriteDocument\fP ($flag)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$document\fP"
.br
.ti -1c
.RI "\fB$root\fP"
.br
.ti -1c
.RI "\fB$logIncompleteSkipped\fP = false"
.br
.ti -1c
.RI "\fB$writeDocument\fP = true"
.br
.ti -1c
.RI "\fB$testSuites\fP = array()"
.br
.ti -1c
.RI "\fB$testSuiteTests\fP = array(0)"
.br
.ti -1c
.RI "\fB$testSuiteAssertions\fP = array(0)"
.br
.ti -1c
.RI "\fB$testSuiteErrors\fP = array(0)"
.br
.ti -1c
.RI "\fB$testSuiteFailures\fP = array(0)"
.br
.ti -1c
.RI "\fB$testSuiteTimes\fP = array(0)"
.br
.ti -1c
.RI "\fB$testSuiteLevel\fP = 0"
.br
.ti -1c
.RI "\fB$currentTestCase\fP = null"
.br
.ti -1c
.RI "\fB$attachCurrentTestCase\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file JUnit\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $out = \fCnull\fP,  $logIncompleteSkipped = \fCfalse\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$out\fP 
.br
\fI$logIncompleteSkipped\fP 
.RE
.PP

.PP
Definition at line 97 of file JUnit\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addError (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
An error occurred\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 130 of file JUnit\&.php\&.
.SS "addFailure (\fBPHPUnit_Framework_Test\fP $test, \fBPHPUnit_Framework_AssertionFailedError\fP $e,  $time)"
\fBA\fP failure occurred\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 163 of file JUnit\&.php\&.
.SS "addIncompleteTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Incomplete test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 198 of file JUnit\&.php\&.
.SS "addRiskyTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Risky test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 4\&.0\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 227 of file JUnit\&.php\&.
.SS "addSkippedTest (\fBPHPUnit_Framework_Test\fP $test, Exception $e,  $time)"
Skipped test\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$e\fP 
.br
\fI$time\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 3\&.0\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 256 of file JUnit\&.php\&.
.SS "endTest (\fBPHPUnit_Framework_Test\fP $test,  $time)"
\fBA\fP test ended\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.br
\fI$time\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 390 of file JUnit\&.php\&.
.SS "endTestSuite (\fBPHPUnit_Framework_TestSuite\fP $suite)"
\fBA\fP testsuite ended\&.
.PP
\fBParameters:\fP
.RS 4
\fI$suite\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 2\&.2\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 318 of file JUnit\&.php\&.
.SS "flush ()"
Flush buffer and close output\&. 
.PP
Definition at line 114 of file JUnit\&.php\&.
.SS "getXML ()"
Returns the XML as a string\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 2\&.2\&.0 
.RE
.PP

.PP
Definition at line 436 of file JUnit\&.php\&.
.SS "setWriteDocument ( $flag)"
Enables or disables the writing of the document in \fBflush()\fP\&.
.PP
This is a 'hack' needed for the integration of \fBPHPUnit\fP with Phing\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 2\&.2\&.0 
.RE
.PP

.PP
Definition at line 451 of file JUnit\&.php\&.
.SS "startTest (\fBPHPUnit_Framework_Test\fP $test)"
\fBA\fP test started\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 361 of file JUnit\&.php\&.
.SS "startTestSuite (\fBPHPUnit_Framework_TestSuite\fP $suite)"
\fBA\fP testsuite started\&.
.PP
\fBParameters:\fP
.RS 4
\fI$suite\fP 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 2\&.2\&.0 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_TestListener\fP\&.
.PP
Definition at line 283 of file JUnit\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$attachCurrentTestCase = true\fC [protected]\fP"

.PP
Definition at line 89 of file JUnit\&.php\&.
.SS "$currentTestCase = null\fC [protected]\fP"

.PP
Definition at line 84 of file JUnit\&.php\&.
.SS "$\fBdocument\fP\fC [protected]\fP"

.PP
Definition at line 29 of file JUnit\&.php\&.
.SS "$logIncompleteSkipped = false\fC [protected]\fP"

.PP
Definition at line 39 of file JUnit\&.php\&.
.SS "$root\fC [protected]\fP"

.PP
Definition at line 34 of file JUnit\&.php\&.
.SS "$testSuiteAssertions = array(0)\fC [protected]\fP"

.PP
Definition at line 59 of file JUnit\&.php\&.
.SS "$testSuiteErrors = array(0)\fC [protected]\fP"

.PP
Definition at line 64 of file JUnit\&.php\&.
.SS "$testSuiteFailures = array(0)\fC [protected]\fP"

.PP
Definition at line 69 of file JUnit\&.php\&.
.SS "$testSuiteLevel = 0\fC [protected]\fP"

.PP
Definition at line 79 of file JUnit\&.php\&.
.SS "$testSuites = array()\fC [protected]\fP"

.PP
Definition at line 49 of file JUnit\&.php\&.
.SS "$testSuiteTests = array(0)\fC [protected]\fP"

.PP
Definition at line 54 of file JUnit\&.php\&.
.SS "$testSuiteTimes = array(0)\fC [protected]\fP"

.PP
Definition at line 74 of file JUnit\&.php\&.
.SS "$writeDocument = true\fC [protected]\fP"

.PP
Definition at line 44 of file JUnit\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
