.TH "PHPUnit_Util_Getopt" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Util_Getopt \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetopt\fP (array $args, $short_options, $long_options=null)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBparseShortOption\fP ($arg, $short_options, &$opts, &$args)"
.br
.ti -1c
.RI "static \fBparseLongOption\fP ($arg, $long_options, &$opts, &$args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file Getopt\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getopt (array $args,  $short_options,  $long_options = \fCnull\fP)\fC [static]\fP"

.PP
Definition at line 25 of file Getopt\&.php\&.
.SS "static parseLongOption ( $arg,  $long_options, & $opts, & $args)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 117 of file Getopt\&.php\&.
.SS "static parseShortOption ( $arg,  $short_options, & $opts, & $args)\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 79 of file Getopt\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
