.TH "PHPUnit_Framework_MockObject_Builder_Namespace" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_MockObject_Builder_Namespace \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPHPUnit_Framework_MockObject_InvocationMocker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlookupId\fP ($id)"
.br
.ti -1c
.RI "\fBregisterId\fP ($id, \fBPHPUnit_Framework_MockObject_Builder_Match\fP $builder)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file Namespace\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "lookupId ( $id)"
Looks up the match builder with identification $id and returns it\&.
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP The identifiction of the match builder\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_MockObject_Builder_Match\fP 
.RE
.PP

.PP
Implemented in \fBPHPUnit_Framework_MockObject_InvocationMocker\fP\&.
.SS "registerId ( $id, \fBPHPUnit_Framework_MockObject_Builder_Match\fP $builder)"
Registers the match builder $builder with the identification $id\&. The builder can later be looked up using \fBlookupId()\fP to figure out if it has been invoked\&.
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP The identification of the match builder\&. 
.br
\fI$builder\fP The builder which is being registered\&. 
.RE
.PP

.PP
Implemented in \fBPHPUnit_Framework_MockObject_InvocationMocker\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
