.TH "PHPUnit_Framework_MockObject_Matcher_InvokedRecorder" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_MockObject_Matcher_InvokedRecorder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_MockObject_Matcher_Invocation\fP\&.
.PP
Inherited by \fBPHPUnit_Framework_MockObject_Matcher_AnyInvokedCount\fP, \fBPHPUnit_Framework_MockObject_Matcher_InvokedAtLeastCount\fP, \fBPHPUnit_Framework_MockObject_Matcher_InvokedAtLeastOnce\fP, \fBPHPUnit_Framework_MockObject_Matcher_InvokedAtMostCount\fP, and \fBPHPUnit_Framework_MockObject_Matcher_InvokedCount\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetInvocationCount\fP ()"
.br
.ti -1c
.RI "\fBgetInvocations\fP ()"
.br
.ti -1c
.RI "\fBhasBeenInvoked\fP ()"
.br
.ti -1c
.RI "\fBinvoked\fP (\fBPHPUnit_Framework_MockObject_Invocation\fP $invocation)"
.br
.ti -1c
.RI "\fBmatches\fP (\fBPHPUnit_Framework_MockObject_Invocation\fP $invocation)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$invocations\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 26 of file InvokedRecorder\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getInvocationCount ()"

.PP
\fBReturns:\fP
.RS 4
integer 
.RE
.PP

.PP
Definition at line 36 of file InvokedRecorder\&.php\&.
.SS "getInvocations ()"

.PP
\fBReturns:\fP
.RS 4
\fBPHPUnit_Framework_MockObject_Invocation\fP[] 
.RE
.PP

.PP
Definition at line 44 of file InvokedRecorder\&.php\&.
.SS "hasBeenInvoked ()"

.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 52 of file InvokedRecorder\&.php\&.
.SS "invoked (\fBPHPUnit_Framework_MockObject_Invocation\fP $invocation)"

.PP
\fBParameters:\fP
.RS 4
\fI$invocation\fP 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_MockObject_Matcher_Invocation\fP\&.
.PP
Definition at line 60 of file InvokedRecorder\&.php\&.
.SS "matches (\fBPHPUnit_Framework_MockObject_Invocation\fP $invocation)"

.PP
\fBParameters:\fP
.RS 4
\fI$invocation\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Implements \fBPHPUnit_Framework_MockObject_Matcher_Invocation\fP\&.
.PP
Definition at line 69 of file InvokedRecorder\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$invocations = array()\fC [protected]\fP"

.PP
Definition at line 31 of file InvokedRecorder\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
