.TH "PHPUnit_Util_Fileloader" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Util_Fileloader \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcheckAndLoad\fP ($filename)"
.br
.ti -1c
.RI "static \fBload\fP ($filename)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Fileloader\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static checkAndLoad ( $filename)\fC [static]\fP"
Checks if a \fBPHP\fP sourcefile is readable\&. The sourcefile is loaded through the \fBload()\fP method\&.
.PP
\fBParameters:\fP
.RS 4
\fI$filename\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBPHPUnit_Framework_Exception\fP\fP 
.RE
.PP

.PP
Definition at line 32 of file Fileloader\&.php\&.
.SS "static load ( $filename)\fC [static]\fP"
Loads a \fBPHP\fP sourcefile\&.
.PP
\fBParameters:\fP
.RS 4
\fI$filename\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 3\&.0\&.0 
.RE
.PP

.PP
Definition at line 54 of file Fileloader\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
