.TH "moduleScripts/RTUscripts/protolibs/portlogger.py" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
moduleScripts/RTUscripts/protolibs/portlogger.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPortLogger\fP"
.br
.ti -1c
.RI "class \fBPortLoggerTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBprotolibs\&.portlogger\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBprogramDescription\fP"
.br
.ti -1c
.RI "string \fBusage\fP = ''' %prog [\fBoptions\fP] /dir/\fBto\fP/symlink1 /dir/\fBto\fP/symlink2 \&.\&.\&.'''"
.br
.ti -1c
.RI "tuple \fBparser\fP = OptionParser(description=programDescription, usage=usage)"
.br
.ti -1c
.RI "string \fBhelp\fP = '''Name of \fBa\fP symlink \fBto\fP connect \fBa\fP pseudoterminal \fBto\fP'''"
.br
.ti -1c
.RI "string \fBaction\fP = '\fBappend\fP'"
.br
.ti -1c
.RI "tuple \fBport_logger\fP"
.br
.ti -1c
.RI "string \fBuser_input\fP = ''"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
