.TH "CachedDoubler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CachedDoubler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDoubler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBregisterClassPatch\fP (\fBClassPatch\\ClassPatchInterface\fP $patch)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateDoubleClass\fP (ReflectionClass $class=null, array $interfaces)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Cached class doubler\&. Prevents mirroring/creation of the same structure twice\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file CachedDoubler\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createDoubleClass (ReflectionClass $class = \fCnull\fP, array $interfaces)\fC [protected]\fP"
{} 
.PP
Definition at line 39 of file CachedDoubler\&.php\&.
.SS "registerClassPatch (\fBClassPatch\\ClassPatchInterface\fP $patch)"
{} 
.PP
Definition at line 29 of file CachedDoubler\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
