.TH "RevealerInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RevealerInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUnwrapper\fP, and \fBRevealer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreveal\fP ($value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Prophecies revealer interface\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 19 of file RevealerInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "reveal ( $value)"
Unwraps value(s)\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBUnwrapper\fP, and \fBRevealer\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
