.TH "TraversablePatch" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraversablePatch \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBClassPatchInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsupports\fP (\fBClassNode\fP $\fBnode\fP)"
.br
.ti -1c
.RI "\fBapply\fP (\fBClassNode\fP $\fBnode\fP)"
.br
.ti -1c
.RI "\fBgetPriority\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Traversable interface patch\&. Forces classes that implement interfaces, that extend Traversable to also implement Iterator\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 23 of file TraversablePatch\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "apply (\fBClassNode\fP $node)"
Forces class to implement Iterator interface\&.
.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Implements \fBClassPatchInterface\fP\&.
.PP
Definition at line 63 of file TraversablePatch\&.php\&.
.SS "getPriority ()"
Returns patch priority, which determines when patch will be applied\&.
.PP
\fBReturns:\fP
.RS 4
int Priority number (higher - earlier) 
.RE
.PP

.PP
Implements \fBClassPatchInterface\fP\&.
.PP
Definition at line 79 of file TraversablePatch\&.php\&.
.SS "supports (\fBClassNode\fP $node)"
Supports nodetree, that implement Traversable, but not Iterator or IteratorAggregate\&.
.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBClassPatchInterface\fP\&.
.PP
Definition at line 32 of file TraversablePatch\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
