.TH "Prophecy\Prophecy" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prophecy\Prophecy \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBMethodProphecy\fP"
.br
.ti -1c
.RI "class \fBObjectProphecy\fP"
.br
.ti -1c
.RI "interface \fBProphecyInterface\fP"
.br
.ti -1c
.RI "interface \fBProphecySubjectInterface\fP"
.br
.ti -1c
.RI "class \fBRevealer\fP"
.br
.ti -1c
.RI "interface \fBRevealerInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
