.TH "ArgumentNode" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArgumentNode \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetTypeHint\fP ()"
.br
.ti -1c
.RI "\fBsetTypeHint\fP ($typeHint=null)"
.br
.ti -1c
.RI "\fBgetDefault\fP ()"
.br
.ti -1c
.RI "\fBsetDefault\fP ($default=null)"
.br
.ti -1c
.RI "\fBisOptional\fP ()"
.br
.ti -1c
.RI "\fBsetAsPassedByReference\fP ($byReference=true)"
.br
.ti -1c
.RI "\fBisPassedByReference\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBArgument\fP node\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 19 of file ArgumentNode\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name)"

.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP

.PP
Definition at line 30 of file ArgumentNode\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDefault ()"

.PP
Definition at line 50 of file ArgumentNode\&.php\&.
.SS "getName ()"

.PP
Definition at line 35 of file ArgumentNode\&.php\&.
.SS "getTypeHint ()"

.PP
Definition at line 40 of file ArgumentNode\&.php\&.
.SS "isOptional ()"

.PP
Definition at line 61 of file ArgumentNode\&.php\&.
.SS "isPassedByReference ()"

.PP
Definition at line 71 of file ArgumentNode\&.php\&.
.SS "setAsPassedByReference ( $byReference = \fCtrue\fP)"

.PP
Definition at line 66 of file ArgumentNode\&.php\&.
.SS "setDefault ( $default = \fCnull\fP)"

.PP
Definition at line 55 of file ArgumentNode\&.php\&.
.SS "setTypeHint ( $typeHint = \fCnull\fP)"

.PP
Definition at line 45 of file ArgumentNode\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
