.TH "ReflectionInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReflectionInterface \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Reflection interface\&. All reflected classes implement this interface\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 20 of file ReflectionInterface\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
