.TH "LazyDouble" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LazyDouble \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBDoubler\fP $doubler)"
.br
.ti -1c
.RI "\fBsetParentClass\fP ($class)"
.br
.ti -1c
.RI "\fBaddInterface\fP ($interface)"
.br
.ti -1c
.RI "\fBsetArguments\fP (array $arguments=null)"
.br
.ti -1c
.RI "\fBgetInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Lazy double\&. Gives simple interface to describe double before creating it\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 25 of file LazyDouble\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBDoubler\fP $doubler)"
Initializes lazy double\&.
.PP
\fBParameters:\fP
.RS 4
\fI$doubler\fP 
.RE
.PP

.PP
Definition at line 38 of file LazyDouble\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addInterface ( $interface)"
Tells doubler to implement specific interface with double\&.
.PP
\fBParameters:\fP
.RS 4
\fI$interface\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 76 of file LazyDouble\&.php\&.
.SS "getInstance ()"
Creates double instance or returns already created one\&.
.PP
\fBReturns:\fP
.RS 4
\fBDoubleInterface\fP 
.RE
.PP

.PP
Definition at line 113 of file LazyDouble\&.php\&.
.SS "setArguments (array $arguments = \fCnull\fP)"
Sets constructor arguments\&.
.PP
\fBParameters:\fP
.RS 4
\fI$arguments\fP 
.RE
.PP

.PP
Definition at line 103 of file LazyDouble\&.php\&.
.SS "setParentClass ( $class)"
Tells doubler to use specific class as parent one for double\&.
.PP
\fBParameters:\fP
.RS 4
\fI$class\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 51 of file LazyDouble\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
