.TH "CallCenter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallCenter \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBStringUtil\fP $util=null)"
.br
.ti -1c
.RI "\fBmakeCall\fP (\fBObjectProphecy\fP $prophecy, $methodName, array $arguments)"
.br
.ti -1c
.RI "\fBfindCalls\fP ($methodName, \fBArgumentsWildcard\fP $wildcard)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Calls receiver & manager\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 25 of file CallCenter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBStringUtil\fP $util = \fCnull\fP)"
Initializes call center\&.
.PP
\fBParameters:\fP
.RS 4
\fI$util\fP 
.RE
.PP

.PP
Definition at line 39 of file CallCenter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "findCalls ( $methodName, \fBArgumentsWildcard\fP $wildcard)"
Searches for calls by method name & arguments wildcard\&.
.PP
\fBParameters:\fP
.RS 4
\fI$methodName\fP 
.br
\fI$wildcard\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBCall\fP[] 
.RE
.PP

.PP
Definition at line 118 of file CallCenter\&.php\&.
.SS "makeCall (\fBObjectProphecy\fP $prophecy,  $methodName, array $arguments)"
Makes and records specific method call for object prophecy\&.
.PP
\fBParameters:\fP
.RS 4
\fI$prophecy\fP 
.br
\fI$methodName\fP 
.br
\fI$arguments\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed Returns null if no promise for prophecy found or promise return value\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 55 of file CallCenter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
