.TH "ClassCreator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassCreator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBClassCodeGenerator\fP $generator=null)"
.br
.ti -1c
.RI "\fBcreate\fP ($classname, Node\\ClassNode $class)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class creator\&. Creates specific class in current environment\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file ClassCreator\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBClassCodeGenerator\fP $generator = \fCnull\fP)"
Initializes creator\&.
.PP
\fBParameters:\fP
.RS 4
\fI$generator\fP 
.RE
.PP

.PP
Definition at line 31 of file ClassCreator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "create ( $classname, Node\\ClassNode $class)"
Creates class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.br
\fI$class\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 46 of file ClassCreator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
