.TH "ClassCodeGenerator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassCodeGenerator \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgenerate\fP ($classname, Node\\ClassNode $class)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class code creator\&. Generates \fBPHP\fP code for specific class node tree\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 20 of file ClassCodeGenerator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "generate ( $classname, Node\\ClassNode $class)"
Generates \fBPHP\fP code for class node\&.
.PP
\fBParameters:\fP
.RS 4
\fI$classname\fP 
.br
\fI$class\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 30 of file ClassCodeGenerator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
