.TH "ClassCreatorException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassCreatorException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException, and \fBDoublerException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, \fBClassNode\fP $\fBnode\fP)"
.br
.ti -1c
.RI "\fBgetClassNode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ClassCreatorException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message, \fBClassNode\fP $node)"

.PP
Definition at line 20 of file ClassCreatorException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getClassNode ()"

.PP
Definition at line 27 of file ClassCreatorException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
