.TH "Prophet" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prophet \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBDoubler\fP $doubler=null, \fBRevealerInterface\fP $revealer=null, \fBStringUtil\fP $util=null)"
.br
.ti -1c
.RI "\fBprophesize\fP ($classOrInterface=null)"
.br
.ti -1c
.RI "\fBgetProphecies\fP ()"
.br
.ti -1c
.RI "\fBgetDoubler\fP ()"
.br
.ti -1c
.RI "\fBcheckPredictions\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBProphet\fP creates prophecies\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 30 of file Prophet\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBDoubler\fP $doubler = \fCnull\fP, \fBRevealerInterface\fP $revealer = \fCnull\fP, \fBStringUtil\fP $util = \fCnull\fP)"
Initializes \fBProphet\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$doubler\fP 
.br
\fI$revealer\fP 
.br
\fI$util\fP 
.RE
.PP

.PP
Definition at line 48 of file Prophet\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "checkPredictions ()"
Checks all predictions defined by prophecies of this \fBProphet\fP\&.
.PP
\fBExceptions:\fP
.RS 4
\fI\fBException\fP\fP 
.RE
.PP

.PP
Definition at line 119 of file Prophet\&.php\&.
.SS "getDoubler ()"
Returns \fBDoubler\fP instance assigned to this \fBProphet\fP\&.
.PP
\fBReturns:\fP
.RS 4
\fBDoubler\fP 
.RE
.PP

.PP
Definition at line 109 of file Prophet\&.php\&.
.SS "getProphecies ()"
Returns all created object prophecies\&.
.PP
\fBReturns:\fP
.RS 4
ObjectProphecy[] 
.RE
.PP

.PP
Definition at line 99 of file Prophet\&.php\&.
.SS "prophesize ( $classOrInterface = \fCnull\fP)"
Creates new object prophecy\&.
.PP
\fBParameters:\fP
.RS 4
\fI$classOrInterface\fP Class or interface name
.RE
.PP
\fBReturns:\fP
.RS 4
ObjectProphecy 
.RE
.PP

.PP
Definition at line 75 of file Prophet\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
