.TH "Call" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Call \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($methodName, array $arguments, $\fBreturnValue\fP, \fBException\fP $exception=null, $file, $\fBline\fP)"
.br
.ti -1c
.RI "\fBgetMethodName\fP ()"
.br
.ti -1c
.RI "\fBgetArguments\fP ()"
.br
.ti -1c
.RI "\fBgetReturnValue\fP ()"
.br
.ti -1c
.RI "\fBgetException\fP ()"
.br
.ti -1c
.RI "\fBgetFile\fP ()"
.br
.ti -1c
.RI "\fBgetLine\fP ()"
.br
.ti -1c
.RI "\fBgetCallPlace\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCall\fP object\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 21 of file Call\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $methodName, array $arguments,  $returnValue, \fBException\fP $exception = \fCnull\fP,  $file,  $line)"
Initializes call\&.
.PP
\fBParameters:\fP
.RS 4
\fI$methodName\fP 
.br
\fI$arguments\fP 
.br
\fI$returnValue\fP 
.br
\fI$exception\fP 
.br
\fI$file\fP 
.br
\fI$line\fP 
.RE
.PP

.PP
Definition at line 40 of file Call\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getArguments ()"
Returns called method arguments\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 69 of file Call\&.php\&.
.SS "getCallPlace ()"
Returns short notation for callee place\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 119 of file Call\&.php\&.
.SS "getException ()"
Returns exception that call thrown\&.
.PP
\fBReturns:\fP
.RS 4
null|Exception 
.RE
.PP

.PP
Definition at line 89 of file Call\&.php\&.
.SS "getFile ()"
Returns callee filename\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 99 of file Call\&.php\&.
.SS "getLine ()"
Returns callee line number\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 109 of file Call\&.php\&.
.SS "getMethodName ()"
Returns called method name\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 59 of file Call\&.php\&.
.SS "getReturnValue ()"
Returns called method return value\&.
.PP
\fBReturns:\fP
.RS 4
null|mixed 
.RE
.PP

.PP
Definition at line 79 of file Call\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
