.TH "AnyValueToken" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnyValueToken \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTokenInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscoreArgument\fP ($argument)"
.br
.ti -1c
.RI "\fBisLast\fP ()"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Any single value token\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 19 of file AnyValueToken\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"
Returns string representation for token\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBTokenInterface\fP\&.
.PP
Definition at line 48 of file AnyValueToken\&.php\&.
.SS "isLast ()"
Returns false\&.
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBTokenInterface\fP\&.
.PP
Definition at line 38 of file AnyValueToken\&.php\&.
.SS "scoreArgument ( $argument)"
Always scores 3 for any argument\&.
.PP
\fBParameters:\fP
.RS 4
\fI$argument\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBTokenInterface\fP\&.
.PP
Definition at line 28 of file AnyValueToken\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
