.TH "ObjectStateToken" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectStateToken \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTokenInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($methodName, $value, \fBStringUtil\fP $util=null, ComparatorFactory $comparatorFactory=null)"
.br
.ti -1c
.RI "\fBscoreArgument\fP ($argument)"
.br
.ti -1c
.RI "\fBisLast\fP ()"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Object state-checker token\&.
.PP
\fBAuthor:\fP
.RS 4
Konstantin Kudryashov ever.zet@gmail.com 
.RE
.PP

.PP
Definition at line 23 of file ObjectStateToken\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $methodName,  $value, \fBStringUtil\fP $util = \fCnull\fP, ComparatorFactory $comparatorFactory = \fCnull\fP)"
Initializes token\&.
.PP
\fBParameters:\fP
.RS 4
\fI$methodName\fP 
.br
\fI$value\fP Expected return value 
.br
\fI$util\fP 
.br
\fI$comparatorFactory\fP 
.RE
.PP

.PP
Definition at line 38 of file ObjectStateToken\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"
Returns string representation for token\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBTokenInterface\fP\&.
.PP
Definition at line 97 of file ObjectStateToken\&.php\&.
.SS "isLast ()"
Returns false\&.
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBTokenInterface\fP\&.
.PP
Definition at line 87 of file ObjectStateToken\&.php\&.
.SS "scoreArgument ( $argument)"
Scores 8 if argument is an object, which method returns expected value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$argument\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool|int 
.RE
.PP

.PP
Implements \fBTokenInterface\fP\&.
.PP
Definition at line 58 of file ObjectStateToken\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
