.TH "Prophecy\Exception" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prophecy\Exception \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCall\fP"
.br
.ti -1c
.RI " \fBDoubler\fP"
.br
.ti -1c
.RI " \fBPrediction\fP"
.br
.ti -1c
.RI " \fBProphecy\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBException\fP"
.br
.ti -1c
.RI "class \fBInvalidArgumentException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
