.TH "Prophecy\Exception\Doubler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Prophecy\Exception\Doubler \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassCreatorException\fP"
.br
.ti -1c
.RI "class \fBClassMirrorException\fP"
.br
.ti -1c
.RI "class \fBClassNotFoundException\fP"
.br
.ti -1c
.RI "class \fBDoubleException\fP"
.br
.ti -1c
.RI "interface \fBDoublerException\fP"
.br
.ti -1c
.RI "class \fBInterfaceNotFoundException\fP"
.br
.ti -1c
.RI "class \fBMethodNotFoundException\fP"
.br
.ti -1c
.RI "class \fBReturnByReferenceException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
