.TH "ICSClient.ICSClientException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ICSClient.ICSClientException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBICSClient\&.NoSuchPointError\fP\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Base class for the exceptions thrown by the icsClient
.fi
.PP
 
.PP
Definition at line 77 of file ics_clients\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
