.TH "RtuMaster" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RtuMaster \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaster\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBset_timeout\fP (self, timeout_in_sec)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Subclass of Master. Implements the Modbus RTU MAC layer
.fi
.PP
 
.PP
Definition at line 77 of file modbus_rtu\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  serial,  interchar_multiplier = \fC1\&.5\fP)"

.PP
.nf
Constructor. Pass the pyserial.Serial object
.fi
.PP
 
.PP
Definition at line 80 of file modbus_rtu\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def set_timeout ( self,  timeout_in_sec)"

.PP
.nf
Change the timeout value
.fi
.PP
 
.PP
Definition at line 101 of file modbus_rtu\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
