.TH "OverlapModbusBlockError" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OverlapModbusBlockError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Exception raised when adding modbus block on a memory address
range already in use

.fi
.PP
 
.PP
Definition at line 77 of file modbus\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
