.TH "protolibs.serial_delay_test" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
protolibs.serial_delay_test \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBreceiver\fP (slave)"
.br
.ti -1c
.RI "def \fBsender\fP (port1, port2)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBSAMPLES\fP = 100"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def protolibs\&.serial_delay_test\&.receiver ( slave)"

.PP
Definition at line 19 of file serial_delay_test\&.py\&.
.SS "def protolibs\&.serial_delay_test\&.sender ( port1,  port2)"

.PP
Definition at line 37 of file serial_delay_test\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "int SAMPLES = 100"

.PP
Definition at line 17 of file serial_delay_test\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
