.TH "TcpQuery" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TcpQuery \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuery\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBbuild_request\fP (self, pdu, slave)"
.br
.ti -1c
.RI "def \fBparse_response\fP (self, response)"
.br
.ti -1c
.RI "def \fBparse_request\fP (self, request)"
.br
.ti -1c
.RI "def \fBbuild_response\fP (self, response_pdu)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Subclass of a Query. Adds the Modbus TCP specific part of the protocol
.fi
.PP
 
.PP
Definition at line 86 of file modbus_tcp\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self)"

.PP
.nf
Constructor
.fi
.PP
 
.PP
Definition at line 92 of file modbus_tcp\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def build_request ( self,  pdu,  slave)"

.PP
.nf
Add the Modbus TCP part to the request
.fi
.PP
 
.PP
Definition at line 107 of file modbus_tcp\&.py\&.
.SS "def build_response ( self,  response_pdu)"

.PP
.nf
Build the response
.fi
.PP
 
.PP
Definition at line 139 of file modbus_tcp\&.py\&.
.SS "def parse_request ( self,  request)"

.PP
.nf
Extract the pdu from a modbus request
.fi
.PP
 
.PP
Definition at line 127 of file modbus_tcp\&.py\&.
.SS "def parse_response ( self,  response)"

.PP
.nf
Extract the pdu from the Modbus TCP response
.fi
.PP
 
.PP
Definition at line 117 of file modbus_tcp\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
