.TH "ModbusInvalidMbapError" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ModbusInvalidMbapError \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, value)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Exception raised when the modbus TCP header doesn't correspond to what is expected
.fi
.PP
 
.PP
Definition at line 21 of file modbus_tcp\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  value)"

.PP
Definition at line 23 of file modbus_tcp\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
