.TH "LogitHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogitHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Handler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, dest)"
.br
.ti -1c
.RI "def \fBemit\fP (self, record)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
This class is a logger handler. It send to a udp socket
.fi
.PP
 
.PP
Definition at line 66 of file utils\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  dest)"

.PP
.nf
Constructor
.fi
.PP
 
.PP
Definition at line 69 of file utils\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def emit ( self,  record)"

.PP
.nf
format and send the record over udp
.fi
.PP
 
.PP
Definition at line 75 of file utils\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
