.TH "TcpMaster" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TcpMaster \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMaster\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBset_timeout\fP (self, timeout_in_sec)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Subclass of Master. Implements the Modbus TCP MAC layer
.fi
.PP
 
.PP
Definition at line 146 of file modbus_tcp\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  host = \fC'127\&.0\&.0\&.1'\fP,  port = \fC502\fP,  timeout_in_sec = \fC5\&.0\fP)"

.PP
.nf
Constructor. Set the communication settings
.fi
.PP
 
.PP
Definition at line 149 of file modbus_tcp\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def set_timeout ( self,  timeout_in_sec)"

.PP
.nf
Change the timeout value
.fi
.PP
 
.PP
Definition at line 174 of file modbus_tcp\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
