.TH "CompositeServer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CompositeServer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBServer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBset_verbose\fP (self, verbose)"
.br
.ti -1c
.RI "def \fBstart\fP (self)"
.br
.ti -1c
.RI "def \fBstop\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
make possible to have several servers sharing the same databank
.fi
.PP
 
.PP
Definition at line 40 of file simulator\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  list_of_server_classes,  list_of_server_args,  databank = \fCNone\fP)"

.PP
.nf
Constructor
.fi
.PP
 
.PP
Definition at line 43 of file simulator\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def set_verbose ( self,  verbose)"

.PP
.nf
if verbose is true the sent and received packets will be logged
.fi
.PP
 
.PP
Definition at line 51 of file simulator\&.py\&.
.SS "def start ( self)"

.PP
.nf
Start the server. It will handle request
.fi
.PP
 
.PP
Definition at line 65 of file simulator\&.py\&.
.SS "def stop ( self)"

.PP
.nf
stop the server. It doesn't handle request anymore
.fi
.PP
 
.PP
Definition at line 70 of file simulator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
