.TH "InvalidArgumentException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvalidArgumentException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits InvalidArgumentException\&.
.SH "Detailed Description"
.PP 
Definition at line 5 of file InvalidArgumentException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
