.TH "AbstractContextAwareMatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractContextAwareMatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractMatcher\fP, and \fBContextAware\fP\&.
.PP
Inherited by \fBMongoClientMatcher\fP, \fBMongoDatabaseMatcher\fP, \fBObjectAttributesMatcher\fP, \fBObjectMethodsMatcher\fP, and \fBVariablesMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetContext\fP (\fBContext\fP $context)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetVariable\fP ($var)"
.br
.ti -1c
.RI "\fBgetVariables\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$context\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An abstract tab completion \fBMatcher\fP which implements \fBContextAware\fP\&.
.PP
The \fBAutoCompleter\fP service will inject a \fBContext\fP instance into all \fBContextAware\fP Matchers\&.
.PP
\fBAuthor:\fP
.RS 4
Marc Garcia markcial@gmail.com 
.RE
.PP

.PP
Definition at line 25 of file AbstractContextAwareMatcher\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getVariable ( $var)\fC [protected]\fP"
Get a \fBContext\fP variable by name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP Variable name
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 51 of file AbstractContextAwareMatcher\&.php\&.
.SS "getVariables ()\fC [protected]\fP"
Get all variables in the current \fBContext\fP\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 61 of file AbstractContextAwareMatcher\&.php\&.
.SS "setContext (\fBContext\fP $context)"
\fBContextAware\fP interface\&.
.PP
\fBParameters:\fP
.RS 4
\fI$context\fP 
.RE
.PP

.PP
Implements \fBContextAware\fP\&.
.PP
Definition at line 39 of file AbstractContextAwareMatcher\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$context\fC [protected]\fP"

.PP
Definition at line 32 of file AbstractContextAwareMatcher\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
