.TH "ConfigurationTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigurationTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestDefaults\fP ()"
.br
.ti -1c
.RI "\fBtestGettersAndSetters\fP ()"
.br
.ti -1c
.RI "\fBtestFilesAndDirectories\fP ($home, $configFile, $historyFile, $manualDbFile)"
.br
.ti -1c
.RI "\fBdirectories\fP ()"
.br
.ti -1c
.RI "\fBtestLoadConfig\fP ()"
.br
.ti -1c
.RI "\fBtestLoadConfigFile\fP ()"
.br
.ti -1c
.RI "\fBtestSetTempDirIsDeprecated\fP ()"
.br
.ti -1c
.RI "\fBtestGetTempDirIsDeprecated\fP ()"
.br
.ti -1c
.RI "\fBtestBaseDirConfigIsDeprecated\fP ()"
.br
.ti -1c
.RI "\fBtestConfigIncludes\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file ConfigurationTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "directories ()"

.PP
Definition at line 62 of file ConfigurationTest\&.php\&.
.SS "testBaseDirConfigIsDeprecated ()"
\fBPHPUnit_Framework_Error_Deprecated\fP 
.PP
Definition at line 153 of file ConfigurationTest\&.php\&.
.SS "testConfigIncludes ()"

.PP
Definition at line 163 of file ConfigurationTest\&.php\&.
.SS "testDefaults ()"

.PP
Definition at line 22 of file ConfigurationTest\&.php\&.
.SS "testFilesAndDirectories ( $home,  $configFile,  $historyFile,  $manualDbFile)"
directories 
.PP
Definition at line 49 of file ConfigurationTest\&.php\&.
.SS "testGetTempDirIsDeprecated ()"
\fBPHPUnit_Framework_Error_Deprecated\fP 
.PP
Definition at line 144 of file ConfigurationTest\&.php\&.
.SS "testGettersAndSetters ()"

.PP
Definition at line 33 of file ConfigurationTest\&.php\&.
.SS "testLoadConfig ()"

.PP
Definition at line 88 of file ConfigurationTest\&.php\&.
.SS "testLoadConfigFile ()"

.PP
Definition at line 112 of file ConfigurationTest\&.php\&.
.SS "testSetTempDirIsDeprecated ()"
\fBPHPUnit_Framework_Error_Deprecated\fP 
.PP
Definition at line 135 of file ConfigurationTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
