.TH "InstanceOfPass" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstanceOfPass \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCodeCleanerPass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBenterNode\fP (\fBNode\fP $\fBnode\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Validate that the instanceof statement does not receive a scalar value or a non-class constant\&.
.PP
\fBAuthor:\fP
.RS 4
Martin Hasoň martin.hason@gmail.com 
.RE
.PP

.PP
Definition at line 26 of file InstanceOfPass\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "enterNode (\fBNode\fP $node)"
Validate that the instanceof statement does not receive a scalar value or a non-class constant\&.
.PP
\fBExceptions:\fP
.RS 4
\fIFatalErrorException\fP if a scalar or a non-class constant is given
.RE
.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Implements \fBNodeVisitor\fP\&.
.PP
Definition at line 35 of file InstanceOfPass\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
