.TH "Exception" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exception \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBBreakException\fP, \fBBreakException\fP, \fBErrorException\fP, \fBFatalErrorException\fP, \fBParseErrorException\fP, \fBRuntimeException\fP, \fBThrowUpException\fP, and \fBThrowUpException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetRawMessage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An interface for \fBPsy\fP Exceptions\&. 
.PP
Definition at line 17 of file Exception\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getRawMessage ()"
This is the only thing, really\&.\&.\&.
.PP
Return a raw (unformatted) version of the message\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBErrorException\fP, \fBFatalErrorException\fP, \fBRuntimeException\fP, \fBBreakException\fP, and \fBThrowUpException\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
