.TH "MethodEnumerator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MethodEnumerator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEnumerator\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBlistItems\fP (\fBInputInterface\fP $input,\\Reflector $reflector=null, $target=null)"
.br
.ti -1c
.RI "\fBgetMethods\fP ($showAll,\\Reflector $reflector)"
.br
.ti -1c
.RI "\fBprepareMethods\fP (array $methods)"
.br
.ti -1c
.RI "\fBgetKindLabel\fP (\\ReflectionClass $reflector)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Method \fBEnumerator\fP class\&. 
.PP
Definition at line 19 of file MethodEnumerator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getKindLabel (\\ReflectionClass $reflector)\fC [protected]\fP"
Get a label for the particular kind of 'class' represented\&.
.PP
\fBParameters:\fP
.RS 4
\fI$reflector\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 110 of file MethodEnumerator\&.php\&.
.SS "getMethods ( $showAll, \\Reflector $reflector)\fC [protected]\fP"
Get defined methods for the given class or object Reflector\&.
.PP
\fBParameters:\fP
.RS 4
\fI$showAll\fP Include private and protected methods\&. 
.br
\fI$reflector\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 63 of file MethodEnumerator\&.php\&.
.SS "listItems (\fBInputInterface\fP $input, \\Reflector $reflector = \fCnull\fP,  $target = \fCnull\fP)\fC [protected]\fP"
{} 
.PP
Definition at line 24 of file MethodEnumerator\&.php\&.
.SS "prepareMethods (array $methods)\fC [protected]\fP"
Prepare formatted method array\&.
.PP
\fBParameters:\fP
.RS 4
\fI$methods\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 85 of file MethodEnumerator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
