.TH "Psy\TabCompletion\Matcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Psy\TabCompletion\Matcher \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAbstractContextAwareMatcher\fP"
.br
.ti -1c
.RI "class \fBAbstractMatcher\fP"
.br
.ti -1c
.RI "class \fBClassAttributesMatcher\fP"
.br
.ti -1c
.RI "class \fBClassMethodsMatcher\fP"
.br
.ti -1c
.RI "class \fBClassNamesMatcher\fP"
.br
.ti -1c
.RI "class \fBCommandsMatcher\fP"
.br
.ti -1c
.RI "class \fBConstantsMatcher\fP"
.br
.ti -1c
.RI "class \fBFunctionsMatcher\fP"
.br
.ti -1c
.RI "class \fBKeywordsMatcher\fP"
.br
.ti -1c
.RI "class \fBMongoClientMatcher\fP"
.br
.ti -1c
.RI "class \fBMongoDatabaseMatcher\fP"
.br
.ti -1c
.RI "class \fBObjectAttributesMatcher\fP"
.br
.ti -1c
.RI "class \fBObjectMethodsMatcher\fP"
.br
.ti -1c
.RI "class \fBVariablesMatcher\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
