.TH "ClassMethodsMatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassMethodsMatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMatches\fP (array $tokens, array $info=array())"
.br
.ti -1c
.RI "\fBhasMatched\fP (array $tokens)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP class method tab completion \fBMatcher\fP\&.
.PP
Given a namespace and class, this matcher provides completion for static methods\&.
.PP
\fBAuthor:\fP
.RS 4
Marc Garcia markcial@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file ClassMethodsMatcher\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getMatches (array $tokens, array $info = \fCarray()\fP)"

.PP
Definition at line 27 of file ClassMethodsMatcher\&.php\&.
.SS "hasMatched (array $tokens)"

.PP
Definition at line 58 of file ClassMethodsMatcher\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
