.TH "AutoCompleterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoCompleterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestClassesCompletion\fP ($\fBline\fP, $mustContain, $mustNotContain)"
.br
.ti -1c
.RI "\fBclassesInput\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file AutoCompleterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "classesInput ()"

.SH "TODO "
.PP
.PP
draft, open to modifications
.IP "\(bu" 2
[ ] if the variable is an array, return the square bracket for completion
.IP "\(bu" 2
[ ] if the variable is a constructor or method, reflect to complete as a function call
.IP "\(bu" 2
[ ] if the preceding token is a variable, call operators or keywords compatible for completion
.IP "\(bu" 2
[X] a command always should be the second token after php_open_tag
.IP "\(bu" 2
[X] keywords are never consecutive
.IP "\(bu" 2
[X] namespacing completion should work just fine
.IP "\(bu" 2
[X] after a new keyword, should always be a class constructor, never a function call or keyword, constant, or variable that does not contain a existing class name\&.
.IP "\(bu" 2
[X] on a namespaced constructor the completion must show the classes related, not constants\&.
.PP
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 93 of file AutoCompleterTest\&.php\&.
.SS "testClassesCompletion ( $line,  $mustContain,  $mustNotContain)"

.PP
\fBParameters:\fP
.RS 4
\fI$line\fP 
.br
\fI$mustContain\fP 
.br
\fI$mustNotContain\fP classesInput 
.RE
.PP

.PP
Definition at line 29 of file AutoCompleterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
