.TH "ErrorExceptionTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErrorExceptionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestInstance\fP ()"
.br
.ti -1c
.RI "\fBtestMessage\fP ()"
.br
.ti -1c
.RI "\fBtestErrorLevels\fP ($level, $type)"
.br
.ti -1c
.RI "\fBtestThrowException\fP ($level, $type)"
.br
.ti -1c
.RI "\fBgetLevels\fP ()"
.br
.ti -1c
.RI "\fBtestThrowExceptionAsErrorHandler\fP ($level, $type)"
.br
.ti -1c
.RI "\fBgetUserLevels\fP ()"
.br
.ti -1c
.RI "\fBtestIgnoreExecutionLoopFilename\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file ErrorExceptionTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getLevels ()"

.PP
Definition at line 60 of file ErrorExceptionTest\&.php\&.
.SS "getUserLevels ()"

.PP
Definition at line 87 of file ErrorExceptionTest\&.php\&.
.SS "testErrorLevels ( $level,  $type)"
getLevels 
.PP
Definition at line 39 of file ErrorExceptionTest\&.php\&.
.SS "testIgnoreExecutionLoopFilename ()"

.PP
Definition at line 97 of file ErrorExceptionTest\&.php\&.
.SS "testInstance ()"

.PP
Definition at line 19 of file ErrorExceptionTest\&.php\&.
.SS "testMessage ()"

.PP
Definition at line 28 of file ErrorExceptionTest\&.php\&.
.SS "testThrowException ( $level,  $type)"
getLevels 
.PP
Definition at line 48 of file ErrorExceptionTest\&.php\&.
.SS "testThrowExceptionAsErrorHandler ( $level,  $type)"
getUserLevels 
.PP
Definition at line 75 of file ErrorExceptionTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
