.TH "InterfaceEnumerator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InterfaceEnumerator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBEnumerator\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBlistItems\fP (\fBInputInterface\fP $input,\\Reflector $reflector=null, $target=null)"
.br
.ti -1c
.RI "\fBprepareInterfaces\fP (array $interfaces)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Interface \fBEnumerator\fP class\&. 
.PP
Definition at line 19 of file InterfaceEnumerator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "listItems (\fBInputInterface\fP $input, \\Reflector $reflector = \fCnull\fP,  $target = \fCnull\fP)\fC [protected]\fP"
{} 
.PP
Definition at line 24 of file InterfaceEnumerator\&.php\&.
.SS "prepareInterfaces (array $interfaces)\fC [protected]\fP"
Prepare formatted interface array\&.
.PP
\fBParameters:\fP
.RS 4
\fI$interfaces\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 61 of file InterfaceEnumerator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
