.TH "CodeCleanerPass" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CodeCleanerPass \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeVisitorAbstract\fP\&.
.PP
Inherited by \fBAbstractClassPass\fP, \fBAssignThisVariablePass\fP, \fBCalledClassPass\fP, \fBCallTimePassByReferencePass\fP, \fBFunctionReturnInWriteContextPass\fP, \fBImplicitReturnPass\fP, \fBInstanceOfPass\fP, \fBLeavePsyshAlonePass\fP, \fBLegacyEmptyPass\fP, \fBMagicConstantsPass\fP, \fBNamespaceAwarePass\fP, \fBNamespacePass\fP, and \fBStaticConstructorPass\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP \fBCodeCleaner\fP pass is a \fBPhpParser\fP Node Visitor\&. 
.PP
Definition at line 19 of file CodeCleanerPass\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
