.TH "PresenterManagerAware" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PresenterManagerAware \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDumpCommand\fP, \fBListCommand\fP, \fBParseCommand\fP, \fBClosurePresenter\fP, and \fBRecursivePresenter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetPresenterManager\fP (\fBPresenterManager\fP $manager)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPresenterManager\fP injects itself as a dependency to all Presenters which implement \fBPresenterManagerAware\fP\&. 
.PP
Definition at line 18 of file PresenterManagerAware\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setPresenterManager (\fBPresenterManager\fP $manager)"
Set a reference to the \fBPresenterManager\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$manager\fP 
.RE
.PP

.PP
Implemented in \fBListCommand\fP, \fBDumpCommand\fP, \fBParseCommand\fP, \fBRecursivePresenter\fP, and \fBClosurePresenter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
