.TH "FatalErrorException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FatalErrorException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBErrorException\fP, and \fBException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message='', $code=0, $severity=9000, $filename=null, $lineno=null, $previous=null)"
.br
.ti -1c
.RI "\fBgetRawMessage\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP 'fatal error' \fBException\fP for \fBPsy\fP\&. 
.PP
Definition at line 17 of file FatalErrorException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message = \fC''\fP,  $code = \fC0\fP,  $severity = \fC9000\fP,  $filename = \fCnull\fP,  $lineno = \fCnull\fP,  $previous = \fCnull\fP)"
Create a fatal error\&.
.PP
\fBParameters:\fP
.RS 4
\fI$message\fP (default: '') 
.br
\fI$code\fP (default: 0) 
.br
\fI$severity\fP (default: 9000) 
.br
\fI$filename\fP (default: null) 
.br
\fI$lineno\fP (default: null) 
.br
\fI$previous\fP (default: null) 
.RE
.PP

.PP
Definition at line 31 of file FatalErrorException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getRawMessage ()"
Return a raw (unformatted) version of the error message\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBException\fP\&.
.PP
Definition at line 43 of file FatalErrorException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
