.TH "ParseErrorExceptionTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseErrorExceptionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestInstance\fP ()"
.br
.ti -1c
.RI "\fBtestMessage\fP ()"
.br
.ti -1c
.RI "\fBtestConstructFromParseError\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file ParseErrorExceptionTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstructFromParseError ()"

.PP
Definition at line 36 of file ParseErrorExceptionTest\&.php\&.
.SS "testInstance ()"

.PP
Definition at line 19 of file ParseErrorExceptionTest\&.php\&.
.SS "testMessage ()"

.PP
Definition at line 28 of file ParseErrorExceptionTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
