.TH "StaticConstructorPassTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StaticConstructorPassTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCodeCleanerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestProcessInvalidStatement\fP ($code)"
.br
.ti -1c
.RI "\fBtestProcessInvalidStatementCatchedByParser\fP ($code)"
.br
.ti -1c
.RI "\fBinvalidStatements\fP ()"
.br
.ti -1c
.RI "\fBinvalidParserStatements\fP ()"
.br
.ti -1c
.RI "\fBtestProcessValidStatement\fP ($code)"
.br
.ti -1c
.RI "\fBvalidStatements\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file StaticConstructorPassTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "invalidParserStatements ()"

.PP
Definition at line 57 of file StaticConstructorPassTest\&.php\&.
.SS "invalidStatements ()"

.PP
Definition at line 43 of file StaticConstructorPassTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 18 of file StaticConstructorPassTest\&.php\&.
.SS "testProcessInvalidStatement ( $code)"
invalidStatements   
.PP
Definition at line 27 of file StaticConstructorPassTest\&.php\&.
.SS "testProcessInvalidStatementCatchedByParser ( $code)"
invalidParserStatements   
.PP
Definition at line 37 of file StaticConstructorPassTest\&.php\&.
.SS "testProcessValidStatement ( $code)"
validStatements 
.PP
Definition at line 72 of file StaticConstructorPassTest\&.php\&.
.SS "validStatements ()"

.PP
Definition at line 78 of file StaticConstructorPassTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
