.TH "BreakException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BreakException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBException\fP, and \fBException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message='', $code=0,\\\fBException\fP $previous=null)"
.br
.ti -1c
.RI "\fBgetRawMessage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP break exception, used for halting the \fBPsy\fP \fBShell\fP\&. 
.PP
Definition at line 17 of file BreakException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message = \fC''\fP,  $code = \fC0\fP, \\\fBException\fP $previous = \fCnull\fP)"
{} 
.PP
Definition at line 24 of file BreakException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getRawMessage ()"
Return a raw (unformatted) version of the error message\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBException\fP\&.
.PP
Definition at line 35 of file BreakException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
