.TH "ConstantsMatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConstantsMatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMatches\fP (array $tokens, array $info=array())"
.br
.ti -1c
.RI "\fBhasMatched\fP (array $tokens)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP constant name tab completion \fBMatcher\fP\&.
.PP
This matcher provides completion for all defined constants\&.
.PP
\fBAuthor:\fP
.RS 4
Marc Garcia markcial@gmail.com 
.RE
.PP

.PP
Definition at line 21 of file ConstantsMatcher\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getMatches (array $tokens, array $info = \fCarray()\fP)"

.PP
Definition at line 26 of file ConstantsMatcher\&.php\&.
.SS "hasMatched (array $tokens)"

.PP
Definition at line 38 of file ConstantsMatcher\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
