.TH "ObjectPresenter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectPresenter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRecursivePresenter\fP\&.
.PP
Inherited by \fBEloquentModelPresenter\fP, \fBIlluminateApplicationPresenter\fP, \fBExceptionPresenter\fP, \fBMongoCursorPresenter\fP, and \fBPHPParserPresenter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcanPresent\fP ($value)"
.br
.ti -1c
.RI "\fBpresentRef\fP ($value)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBFMT\fP = '<object>\\\\<<class>%s</class> <strong>#%s</strong>></object>'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBpresentValue\fP ($value, $depth=null, $\fBoptions\fP=0)"
.br
.ti -1c
.RI "\fBformatProperties\fP ($props)"
.br
.ti -1c
.RI "\fBgetProperties\fP ($value,\\ReflectionClass $class, $propertyFilter)"
.br
.ti -1c
.RI "\fBpropertyKey\fP (\\ReflectionProperty $prop)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
An object \fBPresenter\fP\&. 
.PP
Definition at line 17 of file ObjectPresenter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "canPresent ( $value)"
\fBObjectPresenter\fP can present objects\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Implements \fBPresenter\fP\&.
.PP
Definition at line 28 of file ObjectPresenter\&.php\&.
.SS "formatProperties ( $props)\fC [protected]\fP"
Format object properties\&.
.PP
\fBParameters:\fP
.RS 4
\fI$props\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 77 of file ObjectPresenter\&.php\&.
.SS "getProperties ( $value, \\ReflectionClass $class,  $propertyFilter)\fC [protected]\fP"
Get an array of object properties\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$class\fP 
.br
\fI$propertyFilter\fP \fBOne\fP of  constants
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 103 of file ObjectPresenter\&.php\&.
.SS "presentRef ( $value)"
Present a reference to the object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBPresenter\fP\&.
.PP
Definition at line 40 of file ObjectPresenter\&.php\&.
.SS "presentValue ( $value,  $depth = \fCnull\fP,  $options = \fC0\fP)\fC [protected]\fP"
Present the object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$depth\fP (default: null) 
.br
\fI$options\fP \fBOne\fP of \fBPresenter\fP constants
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 54 of file ObjectPresenter\&.php\&.
.SS "propertyKey (\\ReflectionProperty $prop)\fC [protected]\fP"

.PP
Definition at line 132 of file ObjectPresenter\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const FMT = '<object>\\\\<<class>%s</class> <strong>#%s</strong>></object>'"

.PP
Definition at line 19 of file ObjectPresenter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
