.TH "PsyVersionCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PsyVersionCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBconfigure\fP ()"
.br
.ti -1c
.RI "\fBexecute\fP (\fBInputInterface\fP $input, \fBOutputInterface\fP $output)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP dumb little command for printing out the current \fBPsy\fP \fBShell\fP version\&. 
.PP
Definition at line 20 of file PsyVersionCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "configure ()\fC [protected]\fP"
{} 
.PP
Definition at line 25 of file PsyVersionCommand\&.php\&.
.SS "execute (\fBInputInterface\fP $input, \fBOutputInterface\fP $output)\fC [protected]\fP"
{} 
.PP
Definition at line 37 of file PsyVersionCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
