.TH "PHPParserPresenter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPParserPresenter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectPresenter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcanPresent\fP ($value)"
.br
.ti -1c
.RI "\fBpresentRef\fP ($value)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBFMT\fP = '<object>\\\\<<class>%s</class>></object>'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetProperties\fP ($value,\\ReflectionClass $class, $propertyFilter)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP \fBPhpParser\fP \fBPresenter\fP\&. 
.PP
Definition at line 19 of file PHPParserPresenter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "canPresent ( $value)"
\fBPHPParserPresenter\fP can present parse trees\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Implements \fBPresenter\fP\&.
.PP
Definition at line 30 of file PHPParserPresenter\&.php\&.
.SS "getProperties ( $value, \\ReflectionClass $class,  $propertyFilter)\fC [protected]\fP"
Get an array of object properties\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$class\fP 
.br
\fI$propertyFilter\fP \fBOne\fP of  constants
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 56 of file PHPParserPresenter\&.php\&.
.SS "presentRef ( $value)"
Present a reference to the object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBPresenter\fP\&.
.PP
Definition at line 42 of file PHPParserPresenter\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const FMT = '<object>\\\\<<class>%s</class>></object>'"

.PP
Definition at line 21 of file PHPParserPresenter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
