.TH "ValidConstantPassTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValidConstantPassTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCodeCleanerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestProcessInvalidConstantReferences\fP ($code)"
.br
.ti -1c
.RI "\fBgetInvalidReferences\fP ()"
.br
.ti -1c
.RI "\fBtestProcessValidConstantReferences\fP ($code)"
.br
.ti -1c
.RI "\fBgetValidReferences\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file ValidConstantPassTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getInvalidReferences ()"

.PP
Definition at line 33 of file ValidConstantPassTest\&.php\&.
.SS "getValidReferences ()"

.PP
Definition at line 53 of file ValidConstantPassTest\&.php\&.
.SS "setUp ()"

.PP
Definition at line 18 of file ValidConstantPassTest\&.php\&.
.SS "testProcessInvalidConstantReferences ( $code)"
getInvalidReferences   
.PP
Definition at line 27 of file ValidConstantPassTest\&.php\&.
.SS "testProcessValidConstantReferences ( $code)"
getValidReferences 
.PP
Definition at line 47 of file ValidConstantPassTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
