.TH "MongoCursorPresenter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MongoCursorPresenter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectPresenter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcanPresent\fP ($value)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetProperties\fP ($value,\\ReflectionClass $class, $propertyFilter)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP Mongo Cursor \fBPresenter\fP\&. 
.PP
Definition at line 17 of file MongoCursorPresenter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "canPresent ( $value)"
\fBMongoCursorPresenter\fP can present Mongo Cursors\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Implements \fBPresenter\fP\&.
.PP
Definition at line 29 of file MongoCursorPresenter\&.php\&.
.SS "getProperties ( $value, \\ReflectionClass $class,  $propertyFilter)\fC [protected]\fP"
Get an array of object properties\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$class\fP 
.br
\fI$propertyFilter\fP \fBOne\fP of  constants
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 43 of file MongoCursorPresenter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
