.TH "ShellTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShellTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.ti -1c
.RI "\fBtestScopeVariables\fP ()"
.br
.ti -1c
.RI "\fBtestUnknownScopeVariablesThrowExceptions\fP ()"
.br
.ti -1c
.RI "\fBtestIncludes\fP ()"
.br
.ti -1c
.RI "\fBtestIncludesConfig\fP ()"
.br
.ti -1c
.RI "\fBtestAddMatchersViaConfig\fP ()"
.br
.ti -1c
.RI "\fBtestRenderingExceptions\fP ()"
.br
.ti -1c
.RI "\fBtestHandlingErrors\fP ()"
.br
.ti -1c
.RI "\fBtestNotHandlingErrors\fP ()"
.br
.ti -1c
.RI "\fBtestVersion\fP ()"
.br
.ti -1c
.RI "\fBtestCodeBuffer\fP ()"
.br
.ti -1c
.RI "\fBtestKeepCodeBufferOpen\fP ()"
.br
.ti -1c
.RI "\fBtestCodeBufferThrowsParseExceptions\fP ()"
.br
.ti -1c
.RI "\fBtestClosuresSupport\fP ()"
.br
.ti -1c
.RI "\fBtestWriteStdout\fP ()"
.br
.ti -1c
.RI "\fBtestWriteStdoutWithoutNewline\fP ()"
.br
.ti -1c
.RI "\fBtestWriteReturnValue\fP ($input, $expected)"
.br
.ti -1c
.RI "\fBgetReturnValues\fP ()"
.br
.ti -1c
.RI "\fBtestWriteException\fP ($exception, $expected)"
.br
.ti -1c
.RI "\fBgetRenderedExceptions\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file ShellTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getRenderedExceptions ()"

.PP
Definition at line 308 of file ShellTest\&.php\&.
.SS "getReturnValues ()"

.PP
Definition at line 285 of file ShellTest\&.php\&.
.SS "tearDown ()"

.PP
Definition at line 25 of file ShellTest\&.php\&.
.SS "testAddMatchersViaConfig ()"

.PP
Definition at line 88 of file ShellTest\&.php\&.
.SS "testClosuresSupport ()"

.PP
Definition at line 229 of file ShellTest\&.php\&.
.SS "testCodeBuffer ()"

.PP
Definition at line 179 of file ShellTest\&.php\&.
.SS "testCodeBufferThrowsParseExceptions ()"

.PP
Definition at line 222 of file ShellTest\&.php\&.
.SS "testHandlingErrors ()"

.PP
Definition at line 126 of file ShellTest\&.php\&.
.SS "testIncludes ()"

.PP
Definition at line 65 of file ShellTest\&.php\&.
.SS "testIncludesConfig ()"

.PP
Definition at line 75 of file ShellTest\&.php\&.
.SS "testKeepCodeBufferOpen ()"

.PP
Definition at line 199 of file ShellTest\&.php\&.
.SS "testNotHandlingErrors ()"
\fBPsy\fP 
.PP
Definition at line 155 of file ShellTest\&.php\&.
.SS "testRenderingExceptions ()"

.PP
Definition at line 101 of file ShellTest\&.php\&.
.SS "testScopeVariables ()"

.PP
Definition at line 32 of file ShellTest\&.php\&.
.SS "testUnknownScopeVariablesThrowExceptions ()"

.PP
Definition at line 58 of file ShellTest\&.php\&.
.SS "testVersion ()"

.PP
Definition at line 169 of file ShellTest\&.php\&.
.SS "testWriteException ( $exception,  $expected)"
getRenderedExceptions 
.PP
Definition at line 296 of file ShellTest\&.php\&.
.SS "testWriteReturnValue ( $input,  $expected)"
getReturnValues 
.PP
Definition at line 273 of file ShellTest\&.php\&.
.SS "testWriteStdout ()"

.PP
Definition at line 240 of file ShellTest\&.php\&.
.SS "testWriteStdoutWithoutNewline ()"

.PP
Definition at line 255 of file ShellTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
