.TH "RuntimeException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RuntimeException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException, and \fBException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message='', $code=0,\\\fBException\fP $previous=null)"
.br
.ti -1c
.RI "\fBgetRawMessage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP \fBRuntimeException\fP for \fBPsy\fP\&. 
.PP
Definition at line 17 of file RuntimeException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message = \fC''\fP,  $code = \fC0\fP, \\\fBException\fP $previous = \fCnull\fP)"
Make this bad boy\&.
.PP
\fBParameters:\fP
.RS 4
\fI$message\fP (default: '') 
.br
\fI$code\fP (default: 0) 
.br
\fI$previous\fP (default: null) 
.RE
.PP

.PP
Definition at line 28 of file RuntimeException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getRawMessage ()"
Return a raw (unformatted) version of the error message\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBException\fP\&.
.PP
Definition at line 39 of file RuntimeException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
