.TH "MagicConstantsPass" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MagicConstantsPass \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCodeCleanerPass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBenterNode\fP (\fBNode\fP $\fBnode\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Swap out \fBDIR\fP and \fBFILE\fP magic constants with our best guess? 
.PP
Definition at line 24 of file MagicConstantsPass\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "enterNode (\fBNode\fP $node)"
Swap out \fBDIR\fP and \fBFILE\fP constants, because the default ones when calling eval() don't make sense\&.
.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
null|FuncCall|StringNode 
.RE
.PP

.PP
Implements \fBNodeVisitor\fP\&.
.PP
Definition at line 34 of file MagicConstantsPass\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
