.TH "ResourcePresenter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourcePresenter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRecursivePresenter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcanPresent\fP ($value)"
.br
.ti -1c
.RI "\fBpresentRef\fP ($value)"
.br
.ti -1c
.RI "\fBpresentValue\fP ($value, $depth=null, $\fBoptions\fP=0)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBFMT\fP = '<resource>\\\\<%s <strong>resource #%s</strong>></resource>'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBformatMetadata\fP ($value)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP resource \fBPresenter\fP\&. 
.PP
Definition at line 17 of file ResourcePresenter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "canPresent ( $value)"
Resource presenter can present resources\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Implements \fBPresenter\fP\&.
.PP
Definition at line 28 of file ResourcePresenter\&.php\&.
.SS "formatMetadata ( $value)\fC [protected]\fP"
Format resource metadata\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 78 of file ResourcePresenter\&.php\&.
.SS "presentRef ( $value)"
Present a reference to the value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBPresenter\fP\&.
.PP
Definition at line 40 of file ResourcePresenter\&.php\&.
.SS "presentValue ( $value,  $depth = \fCnull\fP,  $options = \fC0\fP)"
Present the resource\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.br
\fI$depth\fP (default: null) 
.br
\fI$options\fP \fBOne\fP of \fBPresenter\fP constants
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 62 of file ResourcePresenter\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const FMT = '<resource>\\\\<%s <strong>resource #%s</strong>></resource>'"

.PP
Definition at line 19 of file ResourcePresenter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
