.TH "NamespaceAwarePass" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NamespaceAwarePass \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCodeCleanerPass\fP\&.
.PP
Inherited by \fBUseStatementPass\fP, \fBValidClassNamePass\fP, \fBValidConstantPass\fP, and \fBValidFunctionNamePass\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbeforeTraverse\fP (array $nodes)"
.br
.ti -1c
.RI "\fBenterNode\fP (\fBNode\fP $\fBnode\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetFullyQualifiedName\fP ($\fBname\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$namespace\fP"
.br
.ti -1c
.RI "\fB$currentScope\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract namespace-aware code cleaner pass\&. 
.PP
Definition at line 22 of file NamespaceAwarePass\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "beforeTraverse (array $nodes)"
TODO: should this be final? Extending classes should be sure to either use afterTraverse or call parent::beforeTraverse() when overloading\&.
.PP
Reset the namespace and the current scope before beginning analysis\&. 
.PP
Implements \fBNodeVisitor\fP\&.
.PP
Definition at line 33 of file NamespaceAwarePass\&.php\&.
.SS "enterNode (\fBNode\fP $node)"
TODO: should this be final? Extending classes should be sure to either use leaveNode or call parent::enterNode() when overloading\&.
.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Implements \fBNodeVisitor\fP\&.
.PP
Definition at line 45 of file NamespaceAwarePass\&.php\&.
.SS "getFullyQualifiedName ( $name)\fC [protected]\fP"
Get a fully-qualified name (class, function, interface, etc)\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 59 of file NamespaceAwarePass\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$currentScope\fC [protected]\fP"

.PP
Definition at line 25 of file NamespaceAwarePass\&.php\&.
.SS "$namespace\fC [protected]\fP"

.PP
Definition at line 24 of file NamespaceAwarePass\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
