.TH "Redirect" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Redirect \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRedirect\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBhome\fP ($status=302)"
.br
.ti -1c
.RI "static \fBback\fP ($status=302, $headers=array())"
.br
.ti -1c
.RI "static \fBrefresh\fP ($status=302, $headers=array())"
.br
.ti -1c
.RI "static \fBguest\fP ($\fBpath\fP, $status=302, $headers=array(), $\fBsecure\fP=null)"
.br
.ti -1c
.RI "static \fBintended\fP ($default= '/', $status=302, $headers=array(), $\fBsecure\fP=null)"
.br
.ti -1c
.RI "static \fBto\fP ($\fBpath\fP, $status=302, $headers=array(), $\fBsecure\fP=null)"
.br
.ti -1c
.RI "static \fBaway\fP ($\fBpath\fP, $status=302, $headers=array())"
.br
.ti -1c
.RI "static \fBsecure\fP ($\fBpath\fP, $status=302, $headers=array())"
.br
.ti -1c
.RI "static \fBroute\fP ($route, $parameters=array(), $status=302, $headers=array())"
.br
.ti -1c
.RI "static \fBaction\fP ($action, $parameters=array(), $status=302, $headers=array())"
.br
.ti -1c
.RI "static \fBgetUrlGenerator\fP ()"
.br
.ti -1c
.RI "static \fBsetSession\fP ($session)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8554 of file _ide_helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static action ( $action,  $parameters = \fCarray()\fP,  $status = \fC302\fP,  $headers = \fCarray()\fP)\fC [static]\fP"
Create a new redirect response to a controller action\&.
.PP
\fBParameters:\fP
.RS 4
\fI$action\fP 
.br
\fI$parameters\fP 
.br
\fI$status\fP 
.br
\fI$headers\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8683 of file _ide_helper\&.php\&.
.SS "static away ( $path,  $status = \fC302\fP,  $headers = \fCarray()\fP)\fC [static]\fP"
Create a new redirect response to an external \fBURL\fP (no validation)\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$status\fP 
.br
\fI$headers\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8642 of file _ide_helper\&.php\&.
.SS "static back ( $status = \fC302\fP,  $headers = \fCarray()\fP)\fC [static]\fP"
Create a new redirect response to the previous location\&.
.PP
\fBParameters:\fP
.RS 4
\fI$status\fP 
.br
\fI$headers\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8575 of file _ide_helper\&.php\&.
.SS "static getUrlGenerator ()\fC [static]\fP"
Get the \fBURL\fP generator instance\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8693 of file _ide_helper\&.php\&.
.SS "static guest ( $path,  $status = \fC302\fP,  $headers = \fCarray()\fP,  $secure = \fCnull\fP)\fC [static]\fP"
Create a new redirect response, while putting the current \fBURL\fP in the session\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$status\fP 
.br
\fI$headers\fP 
.br
\fI$secure\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8601 of file _ide_helper\&.php\&.
.SS "static home ( $status = \fC302\fP)\fC [static]\fP"
Create a new redirect response to the 'home' route\&.
.PP
\fBParameters:\fP
.RS 4
\fI$status\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8563 of file _ide_helper\&.php\&.
.SS "static intended ( $default = \fC'/'\fP,  $status = \fC302\fP,  $headers = \fCarray()\fP,  $secure = \fCnull\fP)\fC [static]\fP"
Create a new redirect response to the previously intended location\&.
.PP
\fBParameters:\fP
.RS 4
\fI$default\fP 
.br
\fI$status\fP 
.br
\fI$headers\fP 
.br
\fI$secure\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8615 of file _ide_helper\&.php\&.
.SS "static refresh ( $status = \fC302\fP,  $headers = \fCarray()\fP)\fC [static]\fP"
Create a new redirect response to the current URI\&.
.PP
\fBParameters:\fP
.RS 4
\fI$status\fP 
.br
\fI$headers\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8587 of file _ide_helper\&.php\&.
.SS "static route ( $route,  $parameters = \fCarray()\fP,  $status = \fC302\fP,  $headers = \fCarray()\fP)\fC [static]\fP"
Create a new redirect response to a named route\&.
.PP
\fBParameters:\fP
.RS 4
\fI$route\fP 
.br
\fI$parameters\fP 
.br
\fI$status\fP 
.br
\fI$headers\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8669 of file _ide_helper\&.php\&.
.SS "static secure ( $path,  $status = \fC302\fP,  $headers = \fCarray()\fP)\fC [static]\fP"
Create a new redirect response to the given HTTPS path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$status\fP 
.br
\fI$headers\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8655 of file _ide_helper\&.php\&.
.SS "static setSession ( $session)\fC [static]\fP"
Set the active session store\&.
.PP
\fBParameters:\fP
.RS 4
\fI$session\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 8704 of file _ide_helper\&.php\&.
.SS "static to ( $path,  $status = \fC302\fP,  $headers = \fCarray()\fP,  $secure = \fCnull\fP)\fC [static]\fP"
Create a new redirect response to the given path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$status\fP 
.br
\fI$headers\fP 
.br
\fI$secure\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 8629 of file _ide_helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
