.TH "RequirementsTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RequirementsTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestOne\fP ()"
.br
.ti -1c
.RI "\fBtestTwo\fP ()"
.br
.ti -1c
.RI "\fBtestThree\fP ()"
.br
.ti -1c
.RI "\fBtestFour\fP ()"
.br
.ti -1c
.RI "\fBtestFive\fP ()"
.br
.ti -1c
.RI "\fBtestSix\fP ()"
.br
.ti -1c
.RI "\fBtestSeven\fP ()"
.br
.ti -1c
.RI "\fBtestEight\fP ()"
.br
.ti -1c
.RI "\fBtestNine\fP ()"
.br
.ti -1c
.RI "\fBtestTen\fP ()"
.br
.ti -1c
.RI "\fBtestEleven\fP ()"
.br
.ti -1c
.RI "\fBtestAllPossibleRequirements\fP ()"
.br
.ti -1c
.RI "\fBtestExistingFunction\fP ()"
.br
.ti -1c
.RI "\fBtestExistingMethod\fP ()"
.br
.ti -1c
.RI "\fBtestExistingExtension\fP ()"
.br
.ti -1c
.RI "\fBtestExistingOs\fP ()"
.br
.ti -1c
.RI "\fBtestAlwaysSkip\fP ()"
.br
.ti -1c
.RI "\fBtestAlwaysSkip2\fP ()"
.br
.ti -1c
.RI "\fBtestAlwaysSkip3\fP ()"
.br
.ti -1c
.RI "\fBtestSpace\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2 of file RequirementsTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAllPossibleRequirements ()"
\fBPHP\fP 99-dev  \fBPHPUnit\fP 9-dev  OS DOESNOTEXIST  function testFuncOne  function testFuncTwo  extension testExtOne  extension testExtTwo 
.PP
Definition at line 89 of file RequirementsTest\&.php\&.
.SS "testAlwaysSkip ()"
\fBPHPUnit\fP 1111111 
.PP
Definition at line 124 of file RequirementsTest\&.php\&.
.SS "testAlwaysSkip2 ()"
\fBPHP\fP 9999999 
.PP
Definition at line 131 of file RequirementsTest\&.php\&.
.SS "testAlwaysSkip3 ()"
OS DOESNOTEXIST 
.PP
Definition at line 138 of file RequirementsTest\&.php\&.
.SS "testEight ()"
\fBPHP\fP 5\&.4-dev 
.PP
Definition at line 54 of file RequirementsTest\&.php\&.
.SS "testEleven ()"
OS Linux 
.PP
Definition at line 76 of file RequirementsTest\&.php\&.
.SS "testExistingExtension ()"
extension spl 
.PP
Definition at line 110 of file RequirementsTest\&.php\&.
.SS "testExistingFunction ()"
function array_merge 
.PP
Definition at line 96 of file RequirementsTest\&.php\&.
.SS "testExistingMethod ()"
function ReflectionMethod::setAccessible 
.PP
Definition at line 103 of file RequirementsTest\&.php\&.
.SS "testExistingOs ()"
OS \&.* 
.PP
Definition at line 117 of file RequirementsTest\&.php\&.
.SS "testFive ()"
\fBPHP\fP 5\&.4\&.0RC6 
.PP
Definition at line 33 of file RequirementsTest\&.php\&.
.SS "testFour ()"
\fBPHPUnit\fP 2\&.0  \fBPHP\fP 1\&.0 
.PP
Definition at line 26 of file RequirementsTest\&.php\&.
.SS "testNine ()"
function testFunc 
.PP
Definition at line 62 of file RequirementsTest\&.php\&.
.SS "testOne ()"

.PP
Definition at line 4 of file RequirementsTest\&.php\&.
.SS "testSeven ()"
\fBPHP\fP 5\&.4\&.0beta2 
.PP
Definition at line 47 of file RequirementsTest\&.php\&.
.SS "testSix ()"
\fBPHP\fP 5\&.4\&.0-alpha1 
.PP
Definition at line 40 of file RequirementsTest\&.php\&.
.SS "testSpace ()"
extension spl  OS \&.* 
.PP
Definition at line 146 of file RequirementsTest\&.php\&.
.SS "testTen ()"
extension testExt 
.PP
Definition at line 69 of file RequirementsTest\&.php\&.
.SS "testThree ()"
\fBPHP\fP 2\&.0 
.PP
Definition at line 18 of file RequirementsTest\&.php\&.
.SS "testTwo ()"
\fBPHPUnit\fP 1\&.0 
.PP
Definition at line 11 of file RequirementsTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
