.TH "vendor/nikic/php-parser/test_old/run.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/nikic/php-parser/test_old/run.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP('cli'!==php_sapi_name()) \fBshowHelp\fP ($error)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$options\fP = array()"
.br
.ti -1c
.RI "\fB$arguments\fP = array()"
.br
.ti -1c
.RI "foreach($argv as $arg) \fBif\fP(count($arguments)!==2) \fB$SHOW_PROGRESS\fP = true"
.br
.ti -1c
.RI "\fBif\fP(count($\fBoptions\fP) > 0) \fB$TEST_TYPE\fP = $arguments[0]"
.br
.ti -1c
.RI "\fB$DIR\fP = $arguments[1]"
.br
.ti -1c
.RI "\fBif\fP('Symfony'===$TEST_TYPE) elseif('PHP'===$TEST_TYPE) \fBelse\fP"
.br
.ti -1c
.RI "\fB$parser\fP = new \fBPhpParser\\Parser\fP(new \fBPhpParser\\Lexer\\Emulative\fP)"
.br
.ti -1c
.RI "\fB$prettyPrinter\fP = new \fBPhpParser\\PrettyPrinter\\Standard\fP"
.br
.ti -1c
.RI "\fB$nodeDumper\fP = new \fBPhpParser\\NodeDumper\fP"
.br
.ti -1c
.RI "\fB$parseFail\fP = $ppFail = $compareFail = $count = 0"
.br
.ti -1c
.RI "\fB$readTime\fP = $parseTime = $ppTime = $reparseTime = $compareTime = 0"
.br
.ti -1c
.RI "\fB$totalStartTime\fP = microtime(true)"
.br
.ti -1c
.RI "\fBif\fP(0!==$parseFail) \fBif\fP(0!==$ppFail) \fBif\fP (0!==$compareFail)"
.br
.ti -1c
.RI "\fBif\fP(0!==$parseFail) \fBif\fP(0!==$ppFail) \fB$count\fP"
.br
.ti -1c
.RI "\fBif\fP(0!==$parseFail) \fBif\fP(0!==$ppFail) \fBn\fP"
.br
.ti -1c
.RI "\fBif\fP(0!==$parseFail) \fBif\fP(0!==$ppFail) \fB$parseTime\fP"
.br
.ti -1c
.RI "\fBif\fP(0!==$parseFail) \fBif\fP(0!==$ppFail) \fB$ppTime\fP"
.br
.ti -1c
.RI "\fBif\fP(0!==$parseFail) \fBif\fP(0!==$ppFail) \fB$reparseTime\fP"
.br
.ti -1c
.RI "\fBif\fP(0!==$parseFail) \fBif\fP(0!==$ppFail) \fB$compareTime\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBif\fP ('cli'!==php_sapi_name()) showHelp ( $error)"

.PP
Definition at line 10 of file run\&.php\&.
.SH "Variable Documentation"
.PP 
.SS "$arguments = array()"

.PP
Definition at line 27 of file run\&.php\&.
.SS "\fBif\fP (0!==$parseFail) \fBif\fP (0!==$ppFail) $compareTime"

.PP
Definition at line 174 of file run\&.php\&.
.SS "\fBif\fP (0!==$parseFail) \fBif\fP (0!==$ppFail) $count"

.PP
Definition at line 174 of file run\&.php\&.
.SS "$DIR = $arguments[1]"

.PP
Definition at line 54 of file run\&.php\&.
.SS "$nodeDumper = new \fBPhpParser\\NodeDumper\fP"

.PP
Definition at line 73 of file run\&.php\&.
.SS "$\fBoptions\fP = array()"

.PP
Definition at line 26 of file run\&.php\&.
.SS "$parseFail = $ppFail = $compareFail = $count = 0"

.PP
Definition at line 75 of file run\&.php\&.
.SS "$parser = new \fBPhpParser\\Parser\fP(new \fBPhpParser\\Lexer\\Emulative\fP)"

.PP
Definition at line 71 of file run\&.php\&.
.SS "\fBif\fP (0!==$parseFail) \fBif\fP (0!==$ppFail) $parseTime"

.PP
Definition at line 174 of file run\&.php\&.
.SS "\fBif\fP (0!==$parseFail) \fBif\fP (0!==$ppFail) $ppTime"

.PP
Definition at line 174 of file run\&.php\&.
.SS "$prettyPrinter = new \fBPhpParser\\PrettyPrinter\\Standard\fP"

.PP
Definition at line 72 of file run\&.php\&.
.SS "\fBif\fP (0!==$parseFail) \fBif\fP (0!==$ppFail) $readTime = $parseTime = $ppTime = $reparseTime = $compareTime = 0"

.PP
Definition at line 77 of file run\&.php\&.
.SS "\fBif\fP (0!==$parseFail) \fBif\fP (0!==$ppFail) $reparseTime"

.PP
Definition at line 174 of file run\&.php\&.
.SS "foreach ($argv as $arg) \fBif\fP (count($arguments)!==2) $SHOW_PROGRESS = true"

.PP
Definition at line 44 of file run\&.php\&.
.SS "\fBif\fP (count($\fBoptions\fP) > 0) $TEST_TYPE = $arguments[0]"

.PP
Definition at line 53 of file run\&.php\&.
.SS "$totalStartTime = microtime(true)"

.PP
Definition at line 78 of file run\&.php\&.
.SS "foreach (new RecursiveIteratorIterator(new RecursiveDirectoryIterator($DIR),RecursiveIteratorIterator::LEAVES_ONLY) as $file) \fBif\fP (0===$parseFail &&0===$ppFail &&0===$compareFail) else"
\fBInitial value:\fP
.PP
.nf
{
    showHelp('Test type must be either "Symfony" or "PHP"!')
.fi
.PP
Definition at line 64 of file run\&.php\&.
.SS "\fBif\fP (0!==$parseFail) \fBif\fP (0!==$ppFail) \fBif\fP(0!==$compareFail)"

.PP
Definition at line 174 of file run\&.php\&.
.SS "\fBif\fP (0!==$parseFail) \fBif\fP (0!==$ppFail) microtime (true)-$totalStartTime memory_get_peak_usage (true) n"

.PP
Definition at line 174 of file run\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
