.TH "SampleArrayAccess" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleArrayAccess \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayAccess\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBoffsetSet\fP ($offset, $value)"
.br
.ti -1c
.RI "\fBoffsetExists\fP ($offset)"
.br
.ti -1c
.RI "\fBoffsetUnset\fP ($offset)"
.br
.ti -1c
.RI "\fBoffsetGet\fP ($offset)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sample class that implements ArrayAccess copied from http://www.php.net/manual/en/class.arrayaccess.php with some minor changes This class required for \fBPHPUnit_Framework_Constraint_ArrayHasKey\fP testing 
.PP
Definition at line 9 of file SampleArrayAccess\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 13 of file SampleArrayAccess\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "offsetExists ( $offset)"

.PP
Definition at line 25 of file SampleArrayAccess\&.php\&.
.SS "offsetGet ( $offset)"

.PP
Definition at line 33 of file SampleArrayAccess\&.php\&.
.SS "offsetSet ( $offset,  $value)"

.PP
Definition at line 17 of file SampleArrayAccess\&.php\&.
.SS "offsetUnset ( $offset)"

.PP
Definition at line 29 of file SampleArrayAccess\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
