.TH "Line" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Line \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($type=self::UNCHANGED, $content= '')"
.br
.ti -1c
.RI "\fBgetContent\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBADDED\fP = 1"
.br
.ti -1c
.RI "const \fBREMOVED\fP = 2"
.br
.ti -1c
.RI "const \fBUNCHANGED\fP = 3"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file Line\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $type = \fCself::UNCHANGED\fP,  $content = \fC''\fP)"

.PP
\fBParameters:\fP
.RS 4
\fI$type\fP 
.br
\fI$content\fP 
.RE
.PP

.PP
Definition at line 41 of file Line\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getContent ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 50 of file Line\&.php\&.
.SS "getType ()"

.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 58 of file Line\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const ADDED = 1"

.PP
Definition at line 23 of file Line\&.php\&.
.SS "const REMOVED = 2"

.PP
Definition at line 24 of file Line\&.php\&.
.SS "const UNCHANGED = 3"

.PP
Definition at line 25 of file Line\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
