.TH "Book" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Book \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$author\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file Book\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$author = null"

.PP
Definition at line 25 of file Book\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
