.TH "TimeEfficientImplementationTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeEfficientImplementationTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestBothEmpty\fP ()"
.br
.ti -1c
.RI "\fBtestIsStrictComparison\fP ()"
.br
.ti -1c
.RI "\fBtestEqualSequences\fP ()"
.br
.ti -1c
.RI "\fBtestDistinctSequences\fP ()"
.br
.ti -1c
.RI "\fBtestCommonSubsequence\fP ()"
.br
.ti -1c
.RI "\fBtestSingleElementSubsequenceAtStart\fP ()"
.br
.ti -1c
.RI "\fBtestSingleElementSubsequenceAtMiddle\fP ()"
.br
.ti -1c
.RI "\fBtestSingleElementSubsequenceAtEnd\fP ()"
.br
.ti -1c
.RI "\fBtestReversedSequences\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Some of these tests are volontary stressfull, in order to give some approximative benchmark hints\&. 
.PP
Definition at line 18 of file TimeEfficientImplementationTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 24 of file TimeEfficientImplementationTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 32 of file TimeEfficientImplementationTest\&.php\&.
.SS "testBothEmpty ()"

.PP
Definition at line 37 of file TimeEfficientImplementationTest\&.php\&.
.SS "testCommonSubsequence ()"

.PP
Definition at line 102 of file TimeEfficientImplementationTest\&.php\&.
.SS "testDistinctSequences ()"

.PP
Definition at line 82 of file TimeEfficientImplementationTest\&.php\&.
.SS "testEqualSequences ()"

.PP
Definition at line 70 of file TimeEfficientImplementationTest\&.php\&.
.SS "testIsStrictComparison ()"

.PP
Definition at line 46 of file TimeEfficientImplementationTest\&.php\&.
.SS "testReversedSequences ()"

.PP
Definition at line 159 of file TimeEfficientImplementationTest\&.php\&.
.SS "testSingleElementSubsequenceAtEnd ()"

.PP
Definition at line 148 of file TimeEfficientImplementationTest\&.php\&.
.SS "testSingleElementSubsequenceAtMiddle ()"

.PP
Definition at line 137 of file TimeEfficientImplementationTest\&.php\&.
.SS "testSingleElementSubsequenceAtStart ()"

.PP
Definition at line 126 of file TimeEfficientImplementationTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
