.TH "NumericComparator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumericComparator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBScalarComparator\fP\&.
.PP
Inherited by \fBDoubleComparator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaccepts\fP ($expected, $actual)"
.br
.ti -1c
.RI "\fBassertEquals\fP ($expected, $actual, $delta=0\&.0, $canonicalize=false, $ignoreCase=false)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file NumericComparator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "accepts ( $expected,  $actual)"
Returns whether the comparator can compare two values\&.
.PP
\fBParameters:\fP
.RS 4
\fI$expected\fP The first value to compare 
.br
\fI$actual\fP The second value to compare 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 32 of file NumericComparator\&.php\&.
.SS "assertEquals ( $expected,  $actual,  $delta = \fC0\&.0\fP,  $canonicalize = \fCfalse\fP,  $ignoreCase = \fCfalse\fP)"
Asserts that two values are equal\&.
.PP
\fBParameters:\fP
.RS 4
\fI$expected\fP The first value to compare 
.br
\fI$actual\fP The second value to compare 
.br
\fI$delta\fP The allowed numerical distance between two values to consider them equal 
.br
\fI$canonicalize\fP If set to TRUE, arrays are sorted before comparison 
.br
\fI$ignoreCase\fP If set to TRUE, upper- and lowercasing is ignored when comparing string values 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBComparisonFailure\fP\fP Thrown when the comparison fails\&. Contains information about the specific errors that lead to the failure\&. 
.RE
.PP

.PP
Definition at line 56 of file NumericComparator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
