.TH "BlacklistTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BlacklistTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestGlobalVariableThatIsNotBlacklistedIsNotTreatedAsBlacklisted\fP ()"
.br
.ti -1c
.RI "\fBtestGlobalVariableCanBeBlacklisted\fP ()"
.br
.ti -1c
.RI "\fBtestStaticAttributeThatIsNotBlacklistedIsNotTreatedAsBlacklisted\fP ()"
.br
.ti -1c
.RI "\fBtestClassCanBeBlacklisted\fP ()"
.br
.ti -1c
.RI "\fBtestSubclassesCanBeBlacklisted\fP ()"
.br
.ti -1c
.RI "\fBtestImplementorsCanBeBlacklisted\fP ()"
.br
.ti -1c
.RI "\fBtestClassNamePrefixesCanBeBlacklisted\fP ()"
.br
.ti -1c
.RI "\fBtestStaticAttributeCanBeBlacklisted\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Sebastian Bergmann sebastian@phpunit.de 
.RE
.PP
\fBCopyright:\fP
.RS 4
2001-2014 Sebastian Bergmann sebastian@phpunit.de  http://www.opensource.org/licenses/BSD-3-Clause The BSD 3-Clause License \fBhttp://www\&.github\&.com/sebastianbergmann/global-state\fP
.RE
.PP

.PP
Definition at line 53 of file BlacklistTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 60 of file BlacklistTest\&.php\&.
.SS "testClassCanBeBlacklisted ()"

.PP
Definition at line 87 of file BlacklistTest\&.php\&.
.SS "testClassNamePrefixesCanBeBlacklisted ()"

.PP
Definition at line 123 of file BlacklistTest\&.php\&.
.SS "testGlobalVariableCanBeBlacklisted ()"

.PP
Definition at line 70 of file BlacklistTest\&.php\&.
.SS "testGlobalVariableThatIsNotBlacklistedIsNotTreatedAsBlacklisted ()"

.PP
Definition at line 65 of file BlacklistTest\&.php\&.
.SS "testImplementorsCanBeBlacklisted ()"

.PP
Definition at line 111 of file BlacklistTest\&.php\&.
.SS "testStaticAttributeCanBeBlacklisted ()"

.PP
Definition at line 135 of file BlacklistTest\&.php\&.
.SS "testStaticAttributeThatIsNotBlacklistedIsNotTreatedAsBlacklisted ()"

.PP
Definition at line 77 of file BlacklistTest\&.php\&.
.SS "testSubclassesCanBeBlacklisted ()"

.PP
Definition at line 99 of file BlacklistTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
