.TH "NumericComparatorTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NumericComparatorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBacceptsSucceedsProvider\fP ()"
.br
.ti -1c
.RI "\fBacceptsFailsProvider\fP ()"
.br
.ti -1c
.RI "\fBassertEqualsSucceedsProvider\fP ()"
.br
.ti -1c
.RI "\fBassertEqualsFailsProvider\fP ()"
.br
.ti -1c
.RI "\fBtestAcceptsSucceeds\fP ($expected, $actual)"
.br
.ti -1c
.RI "\fBtestAcceptsFails\fP ($expected, $actual)"
.br
.ti -1c
.RI "\fBtestAssertEqualsSucceeds\fP ($expected, $actual, $delta=0\&.0)"
.br
.ti -1c
.RI "\fBtestAssertEqualsFails\fP ($expected, $actual, $delta=0\&.0)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file NumericComparatorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "acceptsFailsProvider ()"

.PP
Definition at line 42 of file NumericComparatorTest\&.php\&.
.SS "acceptsSucceedsProvider ()"

.PP
Definition at line 31 of file NumericComparatorTest\&.php\&.
.SS "assertEqualsFailsProvider ()"

.PP
Definition at line 65 of file NumericComparatorTest\&.php\&.
.SS "assertEqualsSucceedsProvider ()"

.PP
Definition at line 53 of file NumericComparatorTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 26 of file NumericComparatorTest\&.php\&.
.SS "testAcceptsFails ( $expected,  $actual)"
::accepts  acceptsFailsProvider 
.PP
Definition at line 91 of file NumericComparatorTest\&.php\&.
.SS "testAcceptsSucceeds ( $expected,  $actual)"
::accepts  acceptsSucceedsProvider 
.PP
Definition at line 80 of file NumericComparatorTest\&.php\&.
.SS "testAssertEqualsFails ( $expected,  $actual,  $delta = \fC0\&.0\fP)"
\fBassertEquals\fP  assertEqualsFailsProvider 
.PP
Definition at line 120 of file NumericComparatorTest\&.php\&.
.SS "testAssertEqualsSucceeds ( $expected,  $actual,  $delta = \fC0\&.0\fP)"
\fBassertEquals\fP  assertEqualsSucceedsProvider 
.PP
Definition at line 102 of file NumericComparatorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
