.TH "SebastianBergmann\Diff" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SebastianBergmann\Diff \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBLCS\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBChunk\fP"
.br
.ti -1c
.RI "class \fBDiff\fP"
.br
.ti -1c
.RI "class \fBDiffer\fP"
.br
.ti -1c
.RI "class \fBDifferTest\fP"
.br
.ti -1c
.RI "class \fBLine\fP"
.br
.ti -1c
.RI "class \fBParser\fP"
.br
.ti -1c
.RI "class \fBParserTest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
