.TH "ExporterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExporterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexportProvider\fP ()"
.br
.ti -1c
.RI "\fBtestExport\fP ($value, $expected)"
.br
.ti -1c
.RI "\fBtestExport2\fP ()"
.br
.ti -1c
.RI "\fBshortenedExportProvider\fP ()"
.br
.ti -1c
.RI "\fBtestShortenedExport\fP ($value, $expected)"
.br
.ti -1c
.RI "\fBprovideNonBinaryMultibyteStrings\fP ()"
.br
.ti -1c
.RI "\fBtestNonBinaryStringExport\fP ($value, $expectedLength)"
.br
.ti -1c
.RI "\fBtestNonObjectCanBeReturnedAsArray\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBSebastianBergmann\fP 
.PP
Definition at line 16 of file ExporterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "exportProvider ()"

.PP
Definition at line 28 of file ExporterTest\&.php\&.
.SS "provideNonBinaryMultibyteStrings ()"

.PP
Definition at line 303 of file ExporterTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 23 of file ExporterTest\&.php\&.
.SS "shortenedExportProvider ()"

.PP
Definition at line 267 of file ExporterTest\&.php\&.
.SS "testExport ( $value,  $expected)"
exportProvider 
.PP
Definition at line 175 of file ExporterTest\&.php\&.
.SS "testExport2 ()"

.PP
Definition at line 183 of file ExporterTest\&.php\&.
.SS "testNonBinaryStringExport ( $value,  $expectedLength)"
provideNonBinaryMultibyteStrings 
.PP
Definition at line 316 of file ExporterTest\&.php\&.
.SS "testNonObjectCanBeReturnedAsArray ()"

.PP
Definition at line 324 of file ExporterTest\&.php\&.
.SS "testShortenedExport ( $value,  $expected)"
shortenedExportProvider 
.PP
Definition at line 295 of file ExporterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
