.TH "ComparisonFailure" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComparisonFailure \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($expected, $actual, $expectedAsString, $actualAsString, $identical=false, $message= '')"
.br
.ti -1c
.RI "\fBgetActual\fP ()"
.br
.ti -1c
.RI "\fBgetExpected\fP ()"
.br
.ti -1c
.RI "\fBgetActualAsString\fP ()"
.br
.ti -1c
.RI "\fBgetExpectedAsString\fP ()"
.br
.ti -1c
.RI "\fBgetDiff\fP ()"
.br
.ti -1c
.RI "\fBtoString\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$expected\fP"
.br
.ti -1c
.RI "\fB$actual\fP"
.br
.ti -1c
.RI "\fB$expectedAsString\fP"
.br
.ti -1c
.RI "\fB$actualAsString\fP"
.br
.ti -1c
.RI "\fB$identical\fP"
.br
.ti -1c
.RI "\fB$message\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file ComparisonFailure\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $expected,  $actual,  $expectedAsString,  $actualAsString,  $identical = \fCfalse\fP,  $message = \fC''\fP)"
Initialises with the expected value and the actual value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$expected\fP Expected value retrieved\&. 
.br
\fI$actual\fP Actual value retrieved\&. 
.br
\fI$expectedAsString\fP 
.br
\fI$actualAsString\fP 
.br
\fI$identical\fP 
.br
\fI$message\fP \fBA\fP string which is prefixed on all returned lines in the difference output\&. 
.RE
.PP

.PP
Definition at line 74 of file ComparisonFailure\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getActual ()"

.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 86 of file ComparisonFailure\&.php\&.
.SS "getActualAsString ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 102 of file ComparisonFailure\&.php\&.
.SS "getDiff ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 118 of file ComparisonFailure\&.php\&.
.SS "getExpected ()"

.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 94 of file ComparisonFailure\&.php\&.
.SS "getExpectedAsString ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 110 of file ComparisonFailure\&.php\&.
.SS "toString ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 132 of file ComparisonFailure\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$actual\fC [protected]\fP"

.PP
Definition at line 37 of file ComparisonFailure\&.php\&.
.SS "$actualAsString\fC [protected]\fP"

.PP
Definition at line 49 of file ComparisonFailure\&.php\&.
.SS "$expected\fC [protected]\fP"

.PP
Definition at line 31 of file ComparisonFailure\&.php\&.
.SS "$expectedAsString\fC [protected]\fP"

.PP
Definition at line 43 of file ComparisonFailure\&.php\&.
.SS "$identical\fC [protected]\fP"

.PP
Definition at line 54 of file ComparisonFailure\&.php\&.
.SS "$message\fC [protected]\fP"

.PP
Definition at line 61 of file ComparisonFailure\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
