.TH "sims.tcptank.vdevs" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sims.tcptank.vdevs \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBslave\fP (points, args, kwds)"
.br
.ti -1c
.RI "def \fBrw_master\fP (points, clients, args, kwds)"
.br
.ti -1c
.RI "def \fBexecute_master\fP (points, clients, args, kwds)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmaster\fP = \fBrw_master\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def sims\&.tcptank\&.vdevs\&.execute_master ( points,  clients,  args,  kwds)"

.PP
.nf
Code for the master device in this system. 
@param clients dictionary of ICS client objects indexed by device
.fi
.PP
 
.PP
Definition at line 52 of file vdevs\&.py\&.
.SS "def sims\&.tcptank\&.vdevs\&.rw_master ( points,  clients,  args,  kwds)"

.PP
.nf
Code for the master device in this system. 
@param clients dictionary of ICS client objects indexed by device
.fi
.PP
 
.PP
Definition at line 24 of file vdevs\&.py\&.
.SS "def sims\&.tcptank\&.vdevs\&.slave ( points,  args,  kwds)"

.PP
Definition at line 13 of file vdevs\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "master = \fBrw_master\fP"

.PP
Definition at line 82 of file vdevs\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
