.TH "SingletonClass" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SingletonClass \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdoSomething\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetInstance\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file SingletonClass\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()\fC [protected]\fP"

.PP
Definition at line 13 of file SingletonClass\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "doSomething ()"

.PP
Definition at line 9 of file SingletonClass\&.php\&.
.SS "static getInstance ()\fC [static]\fP"

.PP
Definition at line 5 of file SingletonClass\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
