.TH "spec\Prophecy" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spec\Prophecy \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBArgument\fP"
.br
.ti -1c
.RI " \fBCall\fP"
.br
.ti -1c
.RI " \fBDoubler\fP"
.br
.ti -1c
.RI " \fBException\fP"
.br
.ti -1c
.RI " \fBPrediction\fP"
.br
.ti -1c
.RI " \fBPromise\fP"
.br
.ti -1c
.RI " \fBProphecy\fP"
.br
.ti -1c
.RI " \fBUtil\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBArgumentSpec\fP"
.br
.ti -1c
.RI "class \fBProphetSpec\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
