.TH "ObjectStateTokenFixtureB" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectStateTokenFixtureB \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectStateTokenFixtureA\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($value)"
.br
.ti -1c
.RI "\fBgetSelf\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$errors\fP"
.br
.ti -1c
.RI "\fB$value\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 87 of file ObjectStateTokenSpec\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $value)"

.PP
Definition at line 92 of file ObjectStateTokenSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getSelf ()"

.PP
Definition at line 97 of file ObjectStateTokenSpec\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$errors"

.PP
Definition at line 89 of file ObjectStateTokenSpec\&.php\&.
.SS "$value = null"

.PP
Definition at line 90 of file ObjectStateTokenSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
