.TH "WithProperties" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WithProperties \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$baz\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$bar\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file InstantiatorSpec\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$bar\fC [protected]\fP"

.PP
Definition at line 50 of file InstantiatorSpec\&.php\&.
.SS "$\fBbaz\fP"

.PP
Definition at line 52 of file InstantiatorSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
