.TH "LogicalNotTokenSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogicalNotTokenSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ($token)"
.br
.ti -1c
.RI "\fBit_implements_TokenInterface\fP ()"
.br
.ti -1c
.RI "\fBit_holds_originating_token\fP ($token)"
.br
.ti -1c
.RI "\fBit_has_simple_string_representation\fP ($token)"
.br
.ti -1c
.RI "\fBit_wraps_non_token_argument_into_ExactValueToken\fP ()"
.br
.ti -1c
.RI "\fBit_scores_4_if_preset_token_does_not_match_the_argument\fP ($token)"
.br
.ti -1c
.RI "\fBit_does_not_score_if_preset_token_matches_argument\fP ($token)"
.br
.ti -1c
.RI "\fBit_is_last_if_preset_token_is_last\fP ($token)"
.br
.ti -1c
.RI "\fBit_is_not_last_if_preset_token_is_not_last\fP ($token)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file LogicalNotTokenSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_does_not_score_if_preset_token_matches_argument ( $token)"

.PP
Definition at line 48 of file LogicalNotTokenSpec\&.php\&.
.SS "it_has_simple_string_representation ( $token)"

.PP
Definition at line 28 of file LogicalNotTokenSpec\&.php\&.
.SS "it_holds_originating_token ( $token)"

.PP
Definition at line 23 of file LogicalNotTokenSpec\&.php\&.
.SS "it_implements_TokenInterface ()"

.PP
Definition at line 18 of file LogicalNotTokenSpec\&.php\&.
.SS "it_is_last_if_preset_token_is_last ( $token)"

.PP
Definition at line 54 of file LogicalNotTokenSpec\&.php\&.
.SS "it_is_not_last_if_preset_token_is_not_last ( $token)"

.PP
Definition at line 60 of file LogicalNotTokenSpec\&.php\&.
.SS "it_scores_4_if_preset_token_does_not_match_the_argument ( $token)"

.PP
Definition at line 42 of file LogicalNotTokenSpec\&.php\&.
.SS "it_wraps_non_token_argument_into_ExactValueToken ()"

.PP
Definition at line 34 of file LogicalNotTokenSpec\&.php\&.
.SS "let ( $token)"

.PP
\fBParameters:\fP
.RS 4
\fI$token\fP 
.RE
.PP

.PP
Definition at line 13 of file LogicalNotTokenSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
