.TH "CallCenterSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallCenterSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBObjectProphecy\fP $objectProphecy)"
.br
.ti -1c
.RI "\fBit_records_calls_made_through_makeCall_method\fP (\fBObjectProphecy\fP $objectProphecy, \fBArgumentsWildcard\fP $wildcard)"
.br
.ti -1c
.RI "\fBit_returns_null_for_any_call_through_makeCall_if_no_method_prophecies_added\fP ($objectProphecy)"
.br
.ti -1c
.RI "\fBit_executes_promise_of_method_prophecy_that_matches_signature_passed_to_makeCall\fP ($objectProphecy, $method1, $method2, $method3, $arguments1, $arguments2, $arguments3, $promise)"
.br
.ti -1c
.RI "\fBit_executes_promise_of_method_prophecy_that_matches_with_highest_score_to_makeCall\fP ($objectProphecy, $method1, $method2, $method3, $arguments1, $arguments2, $arguments3, $promise)"
.br
.ti -1c
.RI "\fBit_throws_exception_if_call_does_not_match_any_of_defined_method_prophecies\fP ($objectProphecy, $method, $arguments)"
.br
.ti -1c
.RI "\fBit_returns_null_if_method_prophecy_that_matches_makeCall_arguments_has_no_promise\fP ($objectProphecy, $method, $arguments)"
.br
.ti -1c
.RI "\fBit_finds_recorded_calls_by_a_method_name_and_arguments_wildcard\fP ($objectProphecy, $wildcard)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file CallCenterSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_executes_promise_of_method_prophecy_that_matches_signature_passed_to_makeCall ( $objectProphecy,  $method1,  $method2,  $method3,  $arguments1,  $arguments2,  $arguments3,  $promise)"

.PP
\fBParameters:\fP
.RS 4
\fI$method1\fP 
.br
\fI$method2\fP 
.br
\fI$method3\fP 
.br
\fI$arguments1\fP 
.br
\fI$arguments2\fP 
.br
\fI$arguments3\fP 
.br
\fI$promise\fP 
.RE
.PP

.PP
Definition at line 49 of file CallCenterSpec\&.php\&.
.SS "it_executes_promise_of_method_prophecy_that_matches_with_highest_score_to_makeCall ( $objectProphecy,  $method1,  $method2,  $method3,  $arguments1,  $arguments2,  $arguments3,  $promise)"

.PP
\fBParameters:\fP
.RS 4
\fI$method1\fP 
.br
\fI$method2\fP 
.br
\fI$method3\fP 
.br
\fI$arguments1\fP 
.br
\fI$arguments2\fP 
.br
\fI$arguments3\fP 
.br
\fI$promise\fP 
.RE
.PP

.PP
Definition at line 92 of file CallCenterSpec\&.php\&.
.SS "it_finds_recorded_calls_by_a_method_name_and_arguments_wildcard ( $objectProphecy,  $wildcard)"

.PP
\fBParameters:\fP
.RS 4
\fI$wildcard\fP 
.RE
.PP

.PP
Definition at line 169 of file CallCenterSpec\&.php\&.
.SS "it_records_calls_made_through_makeCall_method (\fBObjectProphecy\fP $objectProphecy, \fBArgumentsWildcard\fP $wildcard)"

.PP
Definition at line 15 of file CallCenterSpec\&.php\&.
.SS "it_returns_null_for_any_call_through_makeCall_if_no_method_prophecies_added ( $objectProphecy)"

.PP
Definition at line 31 of file CallCenterSpec\&.php\&.
.SS "it_returns_null_if_method_prophecy_that_matches_makeCall_arguments_has_no_promise ( $objectProphecy,  $method,  $arguments)"

.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$arguments\fP 
.RE
.PP

.PP
Definition at line 150 of file CallCenterSpec\&.php\&.
.SS "it_throws_exception_if_call_does_not_match_any_of_defined_method_prophecies ( $objectProphecy,  $method,  $arguments)"

.PP
\fBParameters:\fP
.RS 4
\fI$method\fP 
.br
\fI$arguments\fP 
.RE
.PP

.PP
Definition at line 130 of file CallCenterSpec\&.php\&.
.SS "let (\fBObjectProphecy\fP $objectProphecy)"

.PP
Definition at line 11 of file CallCenterSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
