.TH "ReportPassedItemSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReportPassedItemSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBTemplate\fP $template, \fBExampleEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBit_writes_a_pass_message_for_a_passing_example\fP (\fBTemplate\fP $template, \fBExampleEvent\fP $\fBevent\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBEVENT_TITLE\fP = 'it works'"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file ReportPassedItemSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_writes_a_pass_message_for_a_passing_example (\fBTemplate\fP $template, \fBExampleEvent\fP $event)"

.PP
Definition at line 20 of file ReportPassedItemSpec\&.php\&.
.SS "let (\fBTemplate\fP $template, \fBExampleEvent\fP $event)"

.PP
Definition at line 15 of file ReportPassedItemSpec\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const EVENT_TITLE = 'it works'"

.PP
Definition at line 13 of file ReportPassedItemSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
