.TH "spec\Prophecy\Doubler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spec\Prophecy\Doubler \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBClassPatch\fP"
.br
.ti -1c
.RI " \fBGenerator\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDoublerSpec\fP"
.br
.ti -1c
.RI "class \fBLazyDoubleSpec\fP"
.br
.ti -1c
.RI "class \fBNameGeneratorSpec\fP"
.br
.ti -1c
.RI "class \fBWithFinalConstructor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
