.TH "StringEngineSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringEngineSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBit_is_a_diff_engine\fP ()"
.br
.ti -1c
.RI "\fBit_supports_string_values\fP ()"
.br
.ti -1c
.RI "\fBit_calculates_strings_diff\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file StringEngineSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_calculates_strings_diff ()"

.PP
Definition at line 19 of file StringEngineSpec\&.php\&.
.SS "it_is_a_diff_engine ()"

.PP
Definition at line 9 of file StringEngineSpec\&.php\&.
.SS "it_supports_string_values ()"

.PP
Definition at line 14 of file StringEngineSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
