.TH "ClassGeneratorSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassGeneratorSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBIO\fP $\fBio\fP, \fBTemplateRenderer\fP $tpl, \fBFilesystem\fP $fs)"
.br
.ti -1c
.RI "\fBit_is_a_generator\fP ()"
.br
.ti -1c
.RI "\fBit_supports_class_generation\fP (\fBResourceInterface\fP $resource)"
.br
.ti -1c
.RI "\fBit_does_not_support_anything_else\fP (\fBResourceInterface\fP $resource)"
.br
.ti -1c
.RI "\fBits_priority_is_0\fP ()"
.br
.ti -1c
.RI "\fBit_generates_class_from_resource_and_puts_it_into_appropriate_folder\fP ($\fBio\fP, $tpl, $fs, \fBResourceInterface\fP $resource)"
.br
.ti -1c
.RI "\fBit_uses_template_provided_by_templating_system_if_there_is_one\fP ($\fBio\fP, $tpl, $fs, \fBResourceInterface\fP $resource)"
.br
.ti -1c
.RI "\fBit_creates_folder_for_class_if_needed\fP ($\fBio\fP, $tpl, $fs, \fBResourceInterface\fP $resource)"
.br
.ti -1c
.RI "\fBit_asks_confirmation_if_class_already_exists\fP ($\fBio\fP, $tpl, $fs, \fBResourceInterface\fP $resource)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file ClassGeneratorSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_asks_confirmation_if_class_already_exists ( $io,  $tpl,  $fs, \fBResourceInterface\fP $resource)"

.PP
Definition at line 105 of file ClassGeneratorSpec\&.php\&.
.SS "it_creates_folder_for_class_if_needed ( $io,  $tpl,  $fs, \fBResourceInterface\fP $resource)"

.PP
Definition at line 90 of file ClassGeneratorSpec\&.php\&.
.SS "it_does_not_support_anything_else (\fBResourceInterface\fP $resource)"

.PP
Definition at line 30 of file ClassGeneratorSpec\&.php\&.
.SS "it_generates_class_from_resource_and_puts_it_into_appropriate_folder ( $io,  $tpl,  $fs, \fBResourceInterface\fP $resource)"

.PP
Definition at line 40 of file ClassGeneratorSpec\&.php\&.
.SS "it_is_a_generator ()"

.PP
Definition at line 20 of file ClassGeneratorSpec\&.php\&.
.SS "it_supports_class_generation (\fBResourceInterface\fP $resource)"

.PP
Definition at line 25 of file ClassGeneratorSpec\&.php\&.
.SS "it_uses_template_provided_by_templating_system_if_there_is_one ( $io,  $tpl,  $fs, \fBResourceInterface\fP $resource)"

.PP
Definition at line 65 of file ClassGeneratorSpec\&.php\&.
.SS "its_priority_is_0 ()"

.PP
Definition at line 35 of file ClassGeneratorSpec\&.php\&.
.SS "let (\fBIO\fP $io, \fBTemplateRenderer\fP $tpl, \fBFilesystem\fP $fs)"

.PP
Definition at line 15 of file ClassGeneratorSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
