.TH "StopOnFailureExceptionSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StopOnFailureExceptionSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ()"
.br
.ti -1c
.RI "\fBit_is_an_example_exception\fP ()"
.br
.ti -1c
.RI "\fBit_has_a_the_result_of_the_last_spec\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file StopOnFailureExceptionSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_has_a_the_result_of_the_last_spec ()"

.PP
Definition at line 21 of file StopOnFailureExceptionSpec\&.php\&.
.SS "it_is_an_example_exception ()"

.PP
Definition at line 16 of file StopOnFailureExceptionSpec\&.php\&.
.SS "let ()"

.PP
Definition at line 11 of file StopOnFailureExceptionSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
