.TH "OptionsConfigSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OptionsConfigSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBit_says_rerun_is_enabled_when_setting_is_true\fP ()"
.br
.ti -1c
.RI "\fBit_says_rerun_is_not_enabled_when_setting_is_false\fP ()"
.br
.ti -1c
.RI "\fBit_says_faking_is_enabled_when_setting_is_true\fP ()"
.br
.ti -1c
.RI "\fBit_says_faking_is_not_enabled_when_setting_is_false\fP ()"
.br
.ti -1c
.RI "\fBit_says_bootstrap_path_is_false_when_setting_is_false\fP ()"
.br
.ti -1c
.RI "\fBit_returns_bootstrap_path_when_one_is_specified\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file OptionsConfigSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_returns_bootstrap_path_when_one_is_specified ()"

.PP
Definition at line 45 of file OptionsConfigSpec\&.php\&.
.SS "it_says_bootstrap_path_is_false_when_setting_is_false ()"

.PP
Definition at line 38 of file OptionsConfigSpec\&.php\&.
.SS "it_says_faking_is_enabled_when_setting_is_true ()"

.PP
Definition at line 24 of file OptionsConfigSpec\&.php\&.
.SS "it_says_faking_is_not_enabled_when_setting_is_false ()"

.PP
Definition at line 31 of file OptionsConfigSpec\&.php\&.
.SS "it_says_rerun_is_enabled_when_setting_is_true ()"

.PP
Definition at line 10 of file OptionsConfigSpec\&.php\&.
.SS "it_says_rerun_is_not_enabled_when_setting_is_false ()"

.PP
Definition at line 17 of file OptionsConfigSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
