.TH "MethodNodeSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MethodNodeSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ()"
.br
.ti -1c
.RI "\fBit_has_a_name\fP ()"
.br
.ti -1c
.RI "\fBit_has_public_visibility_by_default\fP ()"
.br
.ti -1c
.RI "\fBits_visibility_is_mutable\fP ()"
.br
.ti -1c
.RI "\fBit_is_not_static_by_default\fP ()"
.br
.ti -1c
.RI "\fBit_does_not_return_a_reference_by_default\fP ()"
.br
.ti -1c
.RI "\fBit_should_be_settable_as_returning_a_reference_through_setter\fP ()"
.br
.ti -1c
.RI "\fBit_should_be_settable_as_static_through_setter\fP ()"
.br
.ti -1c
.RI "\fBit_accepts_only_supported_visibilities\fP ()"
.br
.ti -1c
.RI "\fBit_lowercases_visibility_before_setting_it\fP ()"
.br
.ti -1c
.RI "\fBits_useParentCode_causes_method_to_call_parent\fP ($argument1, $argument2)"
.br
.ti -1c
.RI "\fBits_code_is_mutable\fP ()"
.br
.ti -1c
.RI "\fBits_reference_returning_methods_will_generate_exceptions\fP ()"
.br
.ti -1c
.RI "\fBits_setCode_provided_with_null_cleans_method_body\fP ()"
.br
.ti -1c
.RI "\fBit_is_constructable_with_code\fP ()"
.br
.ti -1c
.RI "\fBit_does_not_have_arguments_by_default\fP ()"
.br
.ti -1c
.RI "\fBit_supports_adding_arguments\fP ($argument1, $argument2)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file MethodNodeSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_accepts_only_supported_visibilities ()"

.PP
Definition at line 52 of file MethodNodeSpec\&.php\&.
.SS "it_does_not_have_arguments_by_default ()"

.PP
Definition at line 107 of file MethodNodeSpec\&.php\&.
.SS "it_does_not_return_a_reference_by_default ()"

.PP
Definition at line 35 of file MethodNodeSpec\&.php\&.
.SS "it_has_a_name ()"

.PP
Definition at line 14 of file MethodNodeSpec\&.php\&.
.SS "it_has_public_visibility_by_default ()"

.PP
Definition at line 19 of file MethodNodeSpec\&.php\&.
.SS "it_is_constructable_with_code ()"

.PP
Definition at line 101 of file MethodNodeSpec\&.php\&.
.SS "it_is_not_static_by_default ()"

.PP
Definition at line 30 of file MethodNodeSpec\&.php\&.
.SS "it_lowercases_visibility_before_setting_it ()"

.PP
Definition at line 57 of file MethodNodeSpec\&.php\&.
.SS "it_should_be_settable_as_returning_a_reference_through_setter ()"

.PP
Definition at line 40 of file MethodNodeSpec\&.php\&.
.SS "it_should_be_settable_as_static_through_setter ()"

.PP
Definition at line 46 of file MethodNodeSpec\&.php\&.
.SS "it_supports_adding_arguments ( $argument1,  $argument2)"

.PP
\fBParameters:\fP
.RS 4
\fI$argument1\fP 
.br
\fI$argument2\fP 
.RE
.PP

.PP
Definition at line 116 of file MethodNodeSpec\&.php\&.
.SS "its_code_is_mutable ()"

.PP
Definition at line 82 of file MethodNodeSpec\&.php\&.
.SS "its_reference_returning_methods_will_generate_exceptions ()"

.PP
Definition at line 88 of file MethodNodeSpec\&.php\&.
.SS "its_setCode_provided_with_null_cleans_method_body ()"

.PP
Definition at line 95 of file MethodNodeSpec\&.php\&.
.SS "its_useParentCode_causes_method_to_call_parent ( $argument1,  $argument2)"

.PP
\fBParameters:\fP
.RS 4
\fI$argument1\fP 
.br
\fI$argument2\fP 
.RE
.PP

.PP
Definition at line 67 of file MethodNodeSpec\&.php\&.
.SS "its_visibility_is_mutable ()"

.PP
Definition at line 24 of file MethodNodeSpec\&.php\&.
.SS "let ()"

.PP
Definition at line 9 of file MethodNodeSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
