.TH "MagicCallPatchSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MagicCallPatchSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBit_is_a_patch\fP ()"
.br
.ti -1c
.RI "\fBit_supports_anything\fP ($\fBnode\fP)"
.br
.ti -1c
.RI "\fBit_discovers_api_using_phpdoc\fP ($\fBnode\fP)"
.br
.ti -1c
.RI "\fBit_ignores_existing_methods\fP ($\fBnode\fP)"
.br
.ti -1c
.RI "\fBit_has_50_priority\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file MagicCallPatchSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_discovers_api_using_phpdoc ( $node)"

.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Definition at line 27 of file MagicCallPatchSpec\&.php\&.
.SS "it_has_50_priority ()"

.PP
Definition at line 49 of file MagicCallPatchSpec\&.php\&.
.SS "it_ignores_existing_methods ( $node)"

.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Definition at line 39 of file MagicCallPatchSpec\&.php\&.
.SS "it_is_a_patch ()"

.PP
Definition at line 11 of file MagicCallPatchSpec\&.php\&.
.SS "it_supports_anything ( $node)"

.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Definition at line 19 of file MagicCallPatchSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
