.TH "LazyDoubleSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LazyDoubleSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ($doubler)"
.br
.ti -1c
.RI "\fBit_returns_anonymous_double_instance_by_default\fP ($doubler, $double)"
.br
.ti -1c
.RI "\fBit_returns_class_double_instance_if_set\fP ($doubler, $double, $class)"
.br
.ti -1c
.RI "\fBit_returns_same_double_instance_if_called_2_times\fP ($doubler, $double1, $double2)"
.br
.ti -1c
.RI "\fBits_setParentClass_throws_ClassNotFoundException_if_class_not_found\fP ()"
.br
.ti -1c
.RI "\fBits_setParentClass_throws_exception_if_prophecy_is_already_created\fP ($doubler, $double)"
.br
.ti -1c
.RI "\fBits_addInterface_throws_InterfaceNotFoundException_if_no_interface_found\fP ()"
.br
.ti -1c
.RI "\fBits_addInterface_throws_exception_if_prophecy_is_already_created\fP ($doubler, $double)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file LazyDoubleSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_returns_anonymous_double_instance_by_default ( $doubler,  $double)"

.PP
\fBParameters:\fP
.RS 4
\fI$double\fP 
.RE
.PP

.PP
Definition at line 20 of file LazyDoubleSpec\&.php\&.
.SS "it_returns_class_double_instance_if_set ( $doubler,  $double,  $class)"

.PP
\fBParameters:\fP
.RS 4
\fI$double\fP 
.br
\fI$class\fP 
.RE
.PP

.PP
Definition at line 31 of file LazyDoubleSpec\&.php\&.
.SS "it_returns_same_double_instance_if_called_2_times ( $doubler,  $double1,  $double2)"

.PP
\fBParameters:\fP
.RS 4
\fI$double1\fP 
.br
\fI$double2\fP 
.RE
.PP

.PP
Definition at line 44 of file LazyDoubleSpec\&.php\&.
.SS "its_addInterface_throws_exception_if_prophecy_is_already_created ( $doubler,  $double)"

.PP
\fBParameters:\fP
.RS 4
\fI$double\fP 
.RE
.PP

.PP
Definition at line 85 of file LazyDoubleSpec\&.php\&.
.SS "its_addInterface_throws_InterfaceNotFoundException_if_no_interface_found ()"

.PP
Definition at line 76 of file LazyDoubleSpec\&.php\&.
.SS "its_setParentClass_throws_ClassNotFoundException_if_class_not_found ()"

.PP
Definition at line 55 of file LazyDoubleSpec\&.php\&.
.SS "its_setParentClass_throws_exception_if_prophecy_is_already_created ( $doubler,  $double)"

.PP
\fBParameters:\fP
.RS 4
\fI$double\fP 
.RE
.PP

.PP
Definition at line 64 of file LazyDoubleSpec\&.php\&.
.SS "let ( $doubler)"

.PP
\fBParameters:\fP
.RS 4
\fI$doubler\fP 
.RE
.PP

.PP
Definition at line 12 of file LazyDoubleSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
