.TH "TemplateSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TemplateSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBIOInterface\fP $\fBio\fP)"
.br
.ti -1c
.RI "\fBit_renders_the_string_as_is\fP ($\fBio\fP)"
.br
.ti -1c
.RI "\fBit_renders_a_variable\fP ($\fBio\fP)"
.br
.ti -1c
.RI "\fBit_works_for_many_instances_of_vars\fP ($\fBio\fP)"
.br
.ti -1c
.RI "\fBit_renders_a_file\fP ($\fBio\fP)"
.br
.ti -1c
.RI "\fBletgo\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file TemplateSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_renders_a_file ( $io)"

.PP
Definition at line 39 of file TemplateSpec\&.php\&.
.SS "it_renders_a_variable ( $io)"

.PP
Definition at line 24 of file TemplateSpec\&.php\&.
.SS "it_renders_the_string_as_is ( $io)"

.PP
Definition at line 17 of file TemplateSpec\&.php\&.
.SS "it_works_for_many_instances_of_vars ( $io)"

.PP
Definition at line 30 of file TemplateSpec\&.php\&.
.SS "let (\fBIOInterface\fP $io)"

.PP
Definition at line 12 of file TemplateSpec\&.php\&.
.SS "letgo ()"

.PP
Definition at line 50 of file TemplateSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
