.TH "ProphetSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProphetSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ($doubler, $double)"
.br
.ti -1c
.RI "\fBit_constructs_new_prophecy_on_prophesize_call\fP ()"
.br
.ti -1c
.RI "\fBit_constructs_new_prophecy_with_parent_class_if_specified\fP ($doubler, $newDouble)"
.br
.ti -1c
.RI "\fBit_constructs_new_prophecy_with_interface_if_specified\fP ($doubler, $newDouble)"
.br
.ti -1c
.RI "\fBit_exposes_all_created_prophecies_through_getter\fP ()"
.br
.ti -1c
.RI "\fBit_does_nothing_during_checkPredictions_call_if_no_predictions_defined\fP ()"
.br
.ti -1c
.RI "\fBit_throws_AggregateException_if_defined_predictions_fail\fP ($method1, $method2, $arguments1, $arguments2)"
.br
.ti -1c
.RI "\fBit_exposes_doubler_through_getter\fP ($doubler)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file ProphetSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_constructs_new_prophecy_on_prophesize_call ()"

.PP
Definition at line 21 of file ProphetSpec\&.php\&.
.SS "it_constructs_new_prophecy_with_interface_if_specified ( $doubler,  $newDouble)"

.PP
\fBParameters:\fP
.RS 4
\fI$newDouble\fP 
.RE
.PP

.PP
Definition at line 40 of file ProphetSpec\&.php\&.
.SS "it_constructs_new_prophecy_with_parent_class_if_specified ( $doubler,  $newDouble)"

.PP
\fBParameters:\fP
.RS 4
\fI$newDouble\fP 
.RE
.PP

.PP
Definition at line 30 of file ProphetSpec\&.php\&.
.SS "it_does_nothing_during_checkPredictions_call_if_no_predictions_defined ()"

.PP
Definition at line 55 of file ProphetSpec\&.php\&.
.SS "it_exposes_all_created_prophecies_through_getter ()"

.PP
Definition at line 47 of file ProphetSpec\&.php\&.
.SS "it_exposes_doubler_through_getter ( $doubler)"

.PP
Definition at line 87 of file ProphetSpec\&.php\&.
.SS "it_throws_AggregateException_if_defined_predictions_fail ( $method1,  $method2,  $arguments1,  $arguments2)"

.PP
\fBParameters:\fP
.RS 4
\fI$method1\fP 
.br
\fI$method2\fP 
.br
\fI$arguments1\fP 
.br
\fI$arguments2\fP 
.RE
.PP

.PP
Definition at line 66 of file ProphetSpec\&.php\&.
.SS "let ( $doubler,  $double)"

.PP
\fBParameters:\fP
.RS 4
\fI$doubler\fP 
.br
\fI$double\fP 
.RE
.PP

.PP
Definition at line 14 of file ProphetSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
