.TH "CallbackMatcherSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallbackMatcherSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_is_a_matcher\fP ()"
.br
.ti -1c
.RI "\fBit_supports_same_alias_it_was_constructed_with\fP ()"
.br
.ti -1c
.RI "\fBit_does_not_support_anything_else\fP ()"
.br
.ti -1c
.RI "\fBit_matches_if_callback_returns_true\fP ($presenter)"
.br
.ti -1c
.RI "\fBit_does_not_match_if_callback_returns_false\fP ($presenter)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file CallbackMatcherSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_does_not_match_if_callback_returns_false ( $presenter)"

.PP
Definition at line 42 of file CallbackMatcherSpec\&.php\&.
.SS "it_does_not_support_anything_else ()"

.PP
Definition at line 30 of file CallbackMatcherSpec\&.php\&.
.SS "it_is_a_matcher ()"

.PP
Definition at line 20 of file CallbackMatcherSpec\&.php\&.
.SS "it_matches_if_callback_returns_true ( $presenter)"

.PP
Definition at line 35 of file CallbackMatcherSpec\&.php\&.
.SS "it_supports_same_alias_it_was_constructed_with ()"

.PP
Definition at line 25 of file CallbackMatcherSpec\&.php\&.
.SS "let (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 12 of file CallbackMatcherSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
