.TH "ExampleNodeSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExampleNodeSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (ReflectionFunctionAbstract $function)"
.br
.ti -1c
.RI "\fBit_provides_a_link_to_title\fP ()"
.br
.ti -1c
.RI "\fBit_provides_a_link_to_function\fP ($function)"
.br
.ti -1c
.RI "\fBit_provides_a_link_to_specification\fP (\fBSpecificationNode\fP $specification)"
.br
.ti -1c
.RI "\fBit_is_not_pending_by_default\fP ()"
.br
.ti -1c
.RI "\fBit_is_pending_after_marked_as_pending_with_no_args\fP ()"
.br
.ti -1c
.RI "\fBit_is_pending_after_marked_as_pending_with_true\fP ()"
.br
.ti -1c
.RI "\fBit_is_not_pending_after_marked_as_pending_with_false\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 12 of file ExampleNodeSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_is_not_pending_after_marked_as_pending_with_false ()"

.PP
Definition at line 52 of file ExampleNodeSpec\&.php\&.
.SS "it_is_not_pending_by_default ()"

.PP
Definition at line 35 of file ExampleNodeSpec\&.php\&.
.SS "it_is_pending_after_marked_as_pending_with_no_args ()"

.PP
Definition at line 40 of file ExampleNodeSpec\&.php\&.
.SS "it_is_pending_after_marked_as_pending_with_true ()"

.PP
Definition at line 46 of file ExampleNodeSpec\&.php\&.
.SS "it_provides_a_link_to_function ( $function)"

.PP
Definition at line 24 of file ExampleNodeSpec\&.php\&.
.SS "it_provides_a_link_to_specification (\fBSpecificationNode\fP $specification)"

.PP
Definition at line 29 of file ExampleNodeSpec\&.php\&.
.SS "it_provides_a_link_to_title ()"

.PP
Definition at line 19 of file ExampleNodeSpec\&.php\&.
.SS "let (ReflectionFunctionAbstract $function)"

.PP
Definition at line 14 of file ExampleNodeSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
