.TH "MethodGeneratorSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MethodGeneratorSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBIO\fP $\fBio\fP, \fBTemplateRenderer\fP $tpl, \fBFilesystem\fP $fs)"
.br
.ti -1c
.RI "\fBit_is_a_generator\fP ()"
.br
.ti -1c
.RI "\fBit_supports_method_generation\fP (\fBResourceInterface\fP $resource)"
.br
.ti -1c
.RI "\fBit_does_not_support_anything_else\fP (\fBResourceInterface\fP $resource)"
.br
.ti -1c
.RI "\fBits_priority_is_0\fP ()"
.br
.ti -1c
.RI "\fBit_generates_class_method_from_resource\fP ($\fBio\fP, $tpl, $fs, \fBResourceInterface\fP $resource)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file MethodGeneratorSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_does_not_support_anything_else (\fBResourceInterface\fP $resource)"

.PP
Definition at line 30 of file MethodGeneratorSpec\&.php\&.
.SS "it_generates_class_method_from_resource ( $io,  $tpl,  $fs, \fBResourceInterface\fP $resource)"

.PP
Definition at line 40 of file MethodGeneratorSpec\&.php\&.
.SS "it_is_a_generator ()"

.PP
Definition at line 20 of file MethodGeneratorSpec\&.php\&.
.SS "it_supports_method_generation (\fBResourceInterface\fP $resource)"

.PP
Definition at line 25 of file MethodGeneratorSpec\&.php\&.
.SS "its_priority_is_0 ()"

.PP
Definition at line 35 of file MethodGeneratorSpec\&.php\&.
.SS "let (\fBIO\fP $io, \fBTemplateRenderer\fP $tpl, \fBFilesystem\fP $fs)"

.PP
Definition at line 15 of file MethodGeneratorSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
