.TH "ExceptionSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExceptionSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBit_extends_basic_exception\fP ()"
.br
.ti -1c
.RI "\fBit_could_have_a_cause\fP (ReflectionMethod $cause)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 9 of file ExceptionSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_could_have_a_cause (ReflectionMethod $cause)"

.PP
Definition at line 16 of file ExceptionSpec\&.php\&.
.SS "it_extends_basic_exception ()"

.PP
Definition at line 11 of file ExceptionSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
