.TH "ArrayContainMatcherSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArrayContainMatcherSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_is_a_matcher\fP ()"
.br
.ti -1c
.RI "\fBit_responds_to_contain\fP ()"
.br
.ti -1c
.RI "\fBit_matches_array_with_specified_value\fP ()"
.br
.ti -1c
.RI "\fBit_does_not_match_array_without_specified_value\fP ()"
.br
.ti -1c
.RI "\fBit_matches_array_without_specified_value\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file ArrayContainMatcherSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_does_not_match_array_without_specified_value ()"

.PP
Definition at line 35 of file ArrayContainMatcherSpec\&.php\&.
.SS "it_is_a_matcher ()"

.PP
Definition at line 20 of file ArrayContainMatcherSpec\&.php\&.
.SS "it_matches_array_with_specified_value ()"

.PP
Definition at line 30 of file ArrayContainMatcherSpec\&.php\&.
.SS "it_matches_array_without_specified_value ()"

.PP
Definition at line 42 of file ArrayContainMatcherSpec\&.php\&.
.SS "it_responds_to_contain ()"

.PP
Definition at line 25 of file ArrayContainMatcherSpec\&.php\&.
.SS "let (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 12 of file ArrayContainMatcherSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
