.TH "ObjectEngineSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ObjectEngineSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBExporter\fP $exporter, \fBStringEngine\fP $stringDiffer)"
.br
.ti -1c
.RI "\fBit_is_a_differ_engine\fP ()"
.br
.ti -1c
.RI "\fBit_does_not_support_scalars\fP ()"
.br
.ti -1c
.RI "\fBit_only_supports_objects\fP ()"
.br
.ti -1c
.RI "\fBit_converts_objects_to_string_and_diffs_the_result\fP (\fBExporter\fP $exporter, \fBStringEngine\fP $stringDiffer)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file ObjectEngineSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_converts_objects_to_string_and_diffs_the_result (\fBExporter\fP $exporter, \fBStringEngine\fP $stringDiffer)"

.PP
Definition at line 32 of file ObjectEngineSpec\&.php\&.
.SS "it_does_not_support_scalars ()"

.PP
Definition at line 22 of file ObjectEngineSpec\&.php\&.
.SS "it_is_a_differ_engine ()"

.PP
Definition at line 17 of file ObjectEngineSpec\&.php\&.
.SS "it_only_supports_objects ()"

.PP
Definition at line 27 of file ObjectEngineSpec\&.php\&.
.SS "let (\fBExporter\fP $exporter, \fBStringEngine\fP $stringDiffer)"

.PP
Definition at line 12 of file ObjectEngineSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
