.TH "ClassNotFoundExceptionSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassNotFoundExceptionSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ()"
.br
.ti -1c
.RI "\fBit_is_a_prophecy_exception\fP ()"
.br
.ti -1c
.RI "\fBits_getClassname_returns_classname\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file ClassNotFoundExceptionSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_is_a_prophecy_exception ()"

.PP
Definition at line 15 of file ClassNotFoundExceptionSpec\&.php\&.
.SS "its_getClassname_returns_classname ()"

.PP
Definition at line 21 of file ClassNotFoundExceptionSpec\&.php\&.
.SS "let ()"

.PP
Definition at line 10 of file ClassNotFoundExceptionSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
