.TH "spec\Prophecy\Promise" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spec\Prophecy\Promise \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCallbackPromiseSpec\fP"
.br
.ti -1c
.RI "class \fBClassCallback\fP"
.br
.ti -1c
.RI "class \fBRequiredArgumentException\fP"
.br
.ti -1c
.RI "class \fBReturnArgumentPromiseSpec\fP"
.br
.ti -1c
.RI "class \fBReturnPromiseSpec\fP"
.br
.ti -1c
.RI "class \fBThrowPromiseSpec\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBfunctionCallbackFirstArgument\fP ($args)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "spec\\Prophecy\\Promise\\functionCallbackFirstArgument ( $args)"
Callback function used to test callbackpromise
.PP
\fBParameters:\fP
.RS 4
\fIarray\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 107 of file CallbackPromiseSpec\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
