.TH "ThrowPromiseSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThrowPromiseSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ()"
.br
.ti -1c
.RI "\fBit_is_promise\fP ()"
.br
.ti -1c
.RI "\fBit_instantiates_and_throws_exception_from_provided_classname\fP ($object, $method)"
.br
.ti -1c
.RI "\fBit_instantiates_exceptions_with_required_arguments\fP ($object, $method)"
.br
.ti -1c
.RI "\fBit_throws_provided_exception\fP ($object, $method)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file ThrowPromiseSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_instantiates_and_throws_exception_from_provided_classname ( $object,  $method)"

.PP
\fBParameters:\fP
.RS 4
\fI$object\fP 
.br
\fI$method\fP 
.RE
.PP

.PP
Definition at line 23 of file ThrowPromiseSpec\&.php\&.
.SS "it_instantiates_exceptions_with_required_arguments ( $object,  $method)"

.PP
\fBParameters:\fP
.RS 4
\fI$object\fP 
.br
\fI$method\fP 
.RE
.PP

.PP
Definition at line 35 of file ThrowPromiseSpec\&.php\&.
.SS "it_is_promise ()"

.PP
Definition at line 14 of file ThrowPromiseSpec\&.php\&.
.SS "it_throws_provided_exception ( $object,  $method)"

.PP
\fBParameters:\fP
.RS 4
\fI$object\fP 
.br
\fI$method\fP 
.RE
.PP

.PP
Definition at line 47 of file ThrowPromiseSpec\&.php\&.
.SS "let ()"

.PP
Definition at line 9 of file ThrowPromiseSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
