.TH "SuiteSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SuiteSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBit_is_countable\fP ()"
.br
.ti -1c
.RI "\fBit_provides_a_link_to_specifications\fP (\fBSpecificationNode\fP $spec)"
.br
.ti -1c
.RI "\fBit_provides_a_count_of_examples\fP (\fBSpecificationNode\fP $spec)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file SuiteSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_is_countable ()"

.PP
Definition at line 12 of file SuiteSpec\&.php\&.
.SS "it_provides_a_count_of_examples (\fBSpecificationNode\fP $spec)"

.PP
Definition at line 26 of file SuiteSpec\&.php\&.
.SS "it_provides_a_link_to_specifications (\fBSpecificationNode\fP $spec)"

.PP
Definition at line 17 of file SuiteSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
