.TH "spec\PhpSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spec\PhpSpec \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCodeGenerator\fP"
.br
.ti -1c
.RI " \fBConfig\fP"
.br
.ti -1c
.RI " \fBConsole\fP"
.br
.ti -1c
.RI " \fBEvent\fP"
.br
.ti -1c
.RI " \fBException\fP"
.br
.ti -1c
.RI " \fBFormatter\fP"
.br
.ti -1c
.RI " \fBListener\fP"
.br
.ti -1c
.RI " \fBLoader\fP"
.br
.ti -1c
.RI " \fBLocator\fP"
.br
.ti -1c
.RI " \fBMatcher\fP"
.br
.ti -1c
.RI " \fBProcess\fP"
.br
.ti -1c
.RI " \fBRunner\fP"
.br
.ti -1c
.RI " \fBUtil\fP"
.br
.ti -1c
.RI " \fBWrapper\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBServiceContainerSpec\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
