.TH "MethodNotFoundExceptionSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MethodNotFoundExceptionSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ()"
.br
.ti -1c
.RI "\fBit_is_DoubleException\fP ()"
.br
.ti -1c
.RI "\fBit_has_MethodName\fP ()"
.br
.ti -1c
.RI "\fBit_has_classnamej\fP ()"
.br
.ti -1c
.RI "\fBit_has_an_arguments_list\fP ()"
.br
.ti -1c
.RI "\fBit_has_a_default_null_argument_list\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file MethodNotFoundExceptionSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_has_a_default_null_argument_list ()"

.PP
Definition at line 35 of file MethodNotFoundExceptionSpec\&.php\&.
.SS "it_has_an_arguments_list ()"

.PP
Definition at line 30 of file MethodNotFoundExceptionSpec\&.php\&.
.SS "it_has_classnamej ()"

.PP
Definition at line 25 of file MethodNotFoundExceptionSpec\&.php\&.
.SS "it_has_MethodName ()"

.PP
Definition at line 20 of file MethodNotFoundExceptionSpec\&.php\&.
.SS "it_is_DoubleException ()"

.PP
Definition at line 15 of file MethodNotFoundExceptionSpec\&.php\&.
.SS "let ()"

.PP
Definition at line 10 of file MethodNotFoundExceptionSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
