.TH "WrappedObjectSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WrappedObjectSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_instantiates_object_using_classname\fP ()"
.br
.ti -1c
.RI "\fBit_keeps_instantiated_object\fP ()"
.br
.ti -1c
.RI "\fBit_can_be_instantiated_with_a_factory_method\fP ()"
.br
.ti -1c
.RI "\fBit_can_be_instantiated_with_a_factory_method_with_method_name_only\fP ()"
.br
.ti -1c
.RI "\fBit_throws_an_exception_when_factory_method_returns_a_non_object\fP ()"
.br
.ti -1c
.RI "\fBit_throws_an_exception_when_trying_to_change_constructor_params_after_instantiation\fP ()"
.br
.ti -1c
.RI "\fBit_throws_an_exception_when_trying_to_change_factory_method_after_instantiation\fP ()"
.br
.ti -1c
.RI "\fBit_throws_an_exception_when_trying_to_change_from_constructor_to_factory_method_after_instantiation\fP ()"
.br
.ti -1c
.RI "\fBit_throws_an_exception_when_trying_to_change_from_factory_method_to_constructor_after_instantiation\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file WrappedObjectSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_can_be_instantiated_with_a_factory_method ()"

.PP
Definition at line 30 of file WrappedObjectSpec\&.php\&.
.SS "it_can_be_instantiated_with_a_factory_method_with_method_name_only ()"

.PP
Definition at line 42 of file WrappedObjectSpec\&.php\&.
.SS "it_instantiates_object_using_classname ()"

.PP
Definition at line 18 of file WrappedObjectSpec\&.php\&.
.SS "it_keeps_instantiated_object ()"

.PP
Definition at line 24 of file WrappedObjectSpec\&.php\&.
.SS "it_throws_an_exception_when_factory_method_returns_a_non_object ()"

.PP
Definition at line 55 of file WrappedObjectSpec\&.php\&.
.SS "it_throws_an_exception_when_trying_to_change_constructor_params_after_instantiation ()"

.PP
Definition at line 64 of file WrappedObjectSpec\&.php\&.
.SS "it_throws_an_exception_when_trying_to_change_factory_method_after_instantiation ()"

.PP
Definition at line 73 of file WrappedObjectSpec\&.php\&.
.SS "it_throws_an_exception_when_trying_to_change_from_constructor_to_factory_method_after_instantiation ()"

.PP
Definition at line 83 of file WrappedObjectSpec\&.php\&.
.SS "it_throws_an_exception_when_trying_to_change_from_factory_method_to_constructor_after_instantiation ()"

.PP
Definition at line 93 of file WrappedObjectSpec\&.php\&.
.SS "let (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 13 of file WrappedObjectSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
