.TH "CallSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ($exception)"
.br
.ti -1c
.RI "\fBit_exposes_method_name_through_getter\fP ()"
.br
.ti -1c
.RI "\fBit_exposes_arguments_through_getter\fP ()"
.br
.ti -1c
.RI "\fBit_exposes_return_value_through_getter\fP ()"
.br
.ti -1c
.RI "\fBit_exposes_exception_through_getter\fP ($exception)"
.br
.ti -1c
.RI "\fBit_exposes_file_and_line_through_getter\fP ()"
.br
.ti -1c
.RI "\fBit_returns_shortpath_to_callPlace\fP ()"
.br
.ti -1c
.RI "\fBit_returns_unknown_as_callPlace_if_no_file_or_line_provided\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file CallSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_exposes_arguments_through_getter ()"

.PP
Definition at line 22 of file CallSpec\&.php\&.
.SS "it_exposes_exception_through_getter ( $exception)"

.PP
Definition at line 32 of file CallSpec\&.php\&.
.SS "it_exposes_file_and_line_through_getter ()"

.PP
Definition at line 37 of file CallSpec\&.php\&.
.SS "it_exposes_method_name_through_getter ()"

.PP
Definition at line 17 of file CallSpec\&.php\&.
.SS "it_exposes_return_value_through_getter ()"

.PP
Definition at line 27 of file CallSpec\&.php\&.
.SS "it_returns_shortpath_to_callPlace ()"

.PP
Definition at line 43 of file CallSpec\&.php\&.
.SS "it_returns_unknown_as_callPlace_if_no_file_or_line_provided ()"

.PP
Definition at line 48 of file CallSpec\&.php\&.
.SS "let ( $exception)"

.PP
\fBParameters:\fP
.RS 4
\fI$exception\fP 
.RE
.PP

.PP
Definition at line 12 of file CallSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
