.TH "spec\PhpSpec\Exception\Example" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spec\PhpSpec\Exception\Example \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBNotEqualExceptionSpec\fP"
.br
.ti -1c
.RI "class \fBStopOnFailureExceptionSpec\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
