.TH "MethodProphecyExceptionSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MethodProphecyExceptionSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP ($objectProphecy, $methodProphecy)"
.br
.ti -1c
.RI "\fBit_extends_DoubleException\fP ()"
.br
.ti -1c
.RI "\fBit_holds_a_stub_reference\fP ($methodProphecy)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file MethodProphecyExceptionSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_extends_DoubleException ()"

.PP
Definition at line 21 of file MethodProphecyExceptionSpec\&.php\&.
.SS "it_holds_a_stub_reference ( $methodProphecy)"

.PP
Definition at line 26 of file MethodProphecyExceptionSpec\&.php\&.
.SS "let ( $objectProphecy,  $methodProphecy)"

.PP
\fBParameters:\fP
.RS 4
\fI$objectProphecy\fP 
.br
\fI$methodProphecy\fP 
.RE
.PP

.PP
Definition at line 14 of file MethodProphecyExceptionSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
