.TH "DecoratorSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DecoratorSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBExpectationInterface\fP $expectation)"
.br
.ti -1c
.RI "\fBit_returns_the_decorated_expectation\fP (\fBExpectationInterface\fP $expectation)"
.br
.ti -1c
.RI "\fBit_keeps_looking_for_nested_expectations\fP (AbstractDecorator $decorator, \fBExpectationInterface\fP $expectation)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file DecoratorSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_keeps_looking_for_nested_expectations (AbstractDecorator $decorator, \fBExpectationInterface\fP $expectation)"

.PP
Definition at line 24 of file DecoratorSpec\&.php\&.
.SS "it_returns_the_decorated_expectation (\fBExpectationInterface\fP $expectation)"

.PP
Definition at line 19 of file DecoratorSpec\&.php\&.
.SS "let (\fBExpectationInterface\fP $expectation)"

.PP
Definition at line 13 of file DecoratorSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
