.TH "TemplateRendererSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TemplateRendererSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBFilesystem\fP $fs)"
.br
.ti -1c
.RI "\fBit_does_not_have_registered_locations_by_default\fP ()"
.br
.ti -1c
.RI "\fBit_has_locations_setter\fP ()"
.br
.ti -1c
.RI "\fBit_provides_a_method_to_prepend_location\fP ()"
.br
.ti -1c
.RI "\fBit_provides_a_method_to_append_location\fP ()"
.br
.ti -1c
.RI "\fBit_normalizes_locations\fP ()"
.br
.ti -1c
.RI "\fBit_reads_existing_file_from_registered_location\fP ($fs)"
.br
.ti -1c
.RI "\fBit_reads_existing_file_from_first_registered_location\fP ($fs)"
.br
.ti -1c
.RI "\fBit_replaces_placeholders_in_template_with_provided_values\fP ($fs)"
.br
.ti -1c
.RI "\fBit_can_render_template_from_string\fP ()"
.br
.ti -1c
.RI "\fBit_returns_null_if_template_is_not_found_in_any_registered_locations\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file TemplateRendererSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_can_render_template_from_string ()"

.PP
Definition at line 86 of file TemplateRendererSpec\&.php\&.
.SS "it_does_not_have_registered_locations_by_default ()"

.PP
Definition at line 17 of file TemplateRendererSpec\&.php\&.
.SS "it_has_locations_setter ()"

.PP
Definition at line 22 of file TemplateRendererSpec\&.php\&.
.SS "it_normalizes_locations ()"

.PP
Definition at line 44 of file TemplateRendererSpec\&.php\&.
.SS "it_provides_a_method_to_append_location ()"

.PP
Definition at line 36 of file TemplateRendererSpec\&.php\&.
.SS "it_provides_a_method_to_prepend_location ()"

.PP
Definition at line 28 of file TemplateRendererSpec\&.php\&.
.SS "it_reads_existing_file_from_first_registered_location ( $fs)"

.PP
Definition at line 63 of file TemplateRendererSpec\&.php\&.
.SS "it_reads_existing_file_from_registered_location ( $fs)"

.PP
Definition at line 54 of file TemplateRendererSpec\&.php\&.
.SS "it_replaces_placeholders_in_template_with_provided_values ( $fs)"

.PP
Definition at line 75 of file TemplateRendererSpec\&.php\&.
.SS "it_returns_null_if_template_is_not_found_in_any_registered_locations ()"

.PP
Definition at line 94 of file TemplateRendererSpec\&.php\&.
.SS "let (\fBFilesystem\fP $fs)"

.PP
Definition at line 12 of file TemplateRendererSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
