.TH "SpecificationEventSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpecificationEventSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBSuite\fP $suite, \fBSpecificationNode\fP $specification)"
.br
.ti -1c
.RI "\fBit_is_an_event\fP ()"
.br
.ti -1c
.RI "\fBit_provides_a_link_to_suite\fP ($suite)"
.br
.ti -1c
.RI "\fBit_provides_a_link_to_specification\fP ($specification)"
.br
.ti -1c
.RI "\fBit_provides_a_link_to_time\fP ()"
.br
.ti -1c
.RI "\fBit_provides_a_link_to_result\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11 of file SpecificationEventSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_is_an_event ()"

.PP
Definition at line 20 of file SpecificationEventSpec\&.php\&.
.SS "it_provides_a_link_to_result ()"

.PP
Definition at line 41 of file SpecificationEventSpec\&.php\&.
.SS "it_provides_a_link_to_specification ( $specification)"

.PP
Definition at line 31 of file SpecificationEventSpec\&.php\&.
.SS "it_provides_a_link_to_suite ( $suite)"

.PP
Definition at line 26 of file SpecificationEventSpec\&.php\&.
.SS "it_provides_a_link_to_time ()"

.PP
Definition at line 36 of file SpecificationEventSpec\&.php\&.
.SS "let (\fBSuite\fP $suite, \fBSpecificationNode\fP $specification)"

.PP
Definition at line 13 of file SpecificationEventSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
