.TH "SpecificationRunnerSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpecificationRunnerSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBEventDispatcherInterface\fP $dispatcher, \fBExampleRunner\fP $exampleRunner)"
.br
.ti -1c
.RI "\fBit_passes_each_specification_example_to_ExampleRunner\fP (\fBSpecificationNode\fP $specification, \fBExampleNode\fP $ex1, \fBExampleNode\fP $ex2, \fBExampleRunner\fP $exampleRunner)"
.br
.ti -1c
.RI "\fBit_returns_examples_max_resultCode\fP (\fBSpecificationNode\fP $specification, \fBExampleNode\fP $ex1, \fBExampleNode\fP $ex2, \fBExampleRunner\fP $exampleRunner)"
.br
.ti -1c
.RI "\fBit_returns_0_resultCode_if_no_examples_found\fP (\fBSpecificationNode\fP $specification)"
.br
.ti -1c
.RI "\fBit_dispatches_SpecificationEvent_before_and_after_examples_run\fP (\fBEventDispatcherInterface\fP $dispatcher, \fBSpecificationNode\fP $specification)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file SpecificationRunnerSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_dispatches_SpecificationEvent_before_and_after_examples_run (\fBEventDispatcherInterface\fP $dispatcher, \fBSpecificationNode\fP $specification)"

.PP
Definition at line 52 of file SpecificationRunnerSpec\&.php\&.
.SS "it_passes_each_specification_example_to_ExampleRunner (\fBSpecificationNode\fP $specification, \fBExampleNode\fP $ex1, \fBExampleNode\fP $ex2, \fBExampleRunner\fP $exampleRunner)"

.PP
Definition at line 21 of file SpecificationRunnerSpec\&.php\&.
.SS "it_returns_0_resultCode_if_no_examples_found (\fBSpecificationNode\fP $specification)"

.PP
Definition at line 45 of file SpecificationRunnerSpec\&.php\&.
.SS "it_returns_examples_max_resultCode (\fBSpecificationNode\fP $specification, \fBExampleNode\fP $ex1, \fBExampleNode\fP $ex2, \fBExampleRunner\fP $exampleRunner)"

.PP
Definition at line 33 of file SpecificationRunnerSpec\&.php\&.
.SS "let (\fBEventDispatcherInterface\fP $dispatcher, \fBExampleRunner\fP $exampleRunner)"

.PP
Definition at line 16 of file SpecificationRunnerSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
