.TH "spec\Prophecy\Prophecy" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
spec\Prophecy\Prophecy \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassWithFinalMethod\fP"
.br
.ti -1c
.RI "class \fBMethodProphecySpec\fP"
.br
.ti -1c
.RI "class \fBObjectProphecySpec\fP"
.br
.ti -1c
.RI "class \fBObjectProphecySpecFixtureA\fP"
.br
.ti -1c
.RI "class \fBObjectProphecySpecFixtureB\fP"
.br
.ti -1c
.RI "class \fBRevealerSpec\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
