.TH "ExceptionFactorySpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExceptionFactorySpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_creates_a_named_constructor_not_found_exception\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_creates_a_method_not_found_exception\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_creates_a_method_not_visible_exception\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_creates_a_class_not_found_exception\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_creates_a_property_not_found_exception\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_creates_a_calling_method_on_non_object_exception\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_creates_a_setting_property_on_non_object_exception\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBit_creates_an_accessing_property_on_non_object_exception\fP (\fBPresenterInterface\fP $presenter)"
.br
.ti -1c
.RI "\fBshouldCreateNamedConstructorNotFoundException\fP ()"
.br
.ti -1c
.RI "\fBshouldCreateMethodNotFoundException\fP ()"
.br
.ti -1c
.RI "\fBshouldCreateMethodNotVisibleException\fP ()"
.br
.ti -1c
.RI "\fBshouldCreateClassNotFoundException\fP ()"
.br
.ti -1c
.RI "\fBshouldCreatePropertyNotFoundException\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 10 of file ExceptionFactorySpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_creates_a_calling_method_on_non_object_exception (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 99 of file ExceptionFactorySpec\&.php\&.
.SS "it_creates_a_class_not_found_exception (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 72 of file ExceptionFactorySpec\&.php\&.
.SS "it_creates_a_method_not_found_exception (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 41 of file ExceptionFactorySpec\&.php\&.
.SS "it_creates_a_method_not_visible_exception (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 56 of file ExceptionFactorySpec\&.php\&.
.SS "it_creates_a_named_constructor_not_found_exception (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 26 of file ExceptionFactorySpec\&.php\&.
.SS "it_creates_a_property_not_found_exception (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 85 of file ExceptionFactorySpec\&.php\&.
.SS "it_creates_a_setting_property_on_non_object_exception (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 110 of file ExceptionFactorySpec\&.php\&.
.SS "it_creates_an_accessing_property_on_non_object_exception (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 121 of file ExceptionFactorySpec\&.php\&.
.SS "let (\fBPresenterInterface\fP $presenter)"

.PP
Definition at line 15 of file ExceptionFactorySpec\&.php\&.
.SS "shouldCreateClassNotFoundException ()"

.PP
Definition at line 159 of file ExceptionFactorySpec\&.php\&.
.SS "shouldCreateMethodNotFoundException ()"

.PP
Definition at line 141 of file ExceptionFactorySpec\&.php\&.
.SS "shouldCreateMethodNotVisibleException ()"

.PP
Definition at line 150 of file ExceptionFactorySpec\&.php\&.
.SS "shouldCreateNamedConstructorNotFoundException ()"

.PP
Definition at line 132 of file ExceptionFactorySpec\&.php\&.
.SS "shouldCreatePropertyNotFoundException ()"

.PP
Definition at line 166 of file ExceptionFactorySpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
