.TH "StatisticsCollectorSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatisticsCollectorSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlet\fP (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"
.br
.ti -1c
.RI "\fBit_is_an_event_listener\fP ()"
.br
.ti -1c
.RI "\fBit_listens_to_stats_generating_events\fP ()"
.br
.ti -1c
.RI "\fBit_knows_no_specs_have_run_initially\fP ()"
.br
.ti -1c
.RI "\fBit_counts_how_many_specs_have_run\fP (\fBSpecificationEvent\fP $specEvent1, \fBSpecificationEvent\fP $specEvent2)"
.br
.ti -1c
.RI "\fBit_knows_no_examples_have_run_initially\fP ()"
.br
.ti -1c
.RI "\fBit_counts_how_many_examples_have_run\fP (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"
.br
.ti -1c
.RI "\fBit_logs_all_example_events\fP (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"
.br
.ti -1c
.RI "\fBit_logs_all_example_events_by_type\fP (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"
.br
.ti -1c
.RI "\fBit_counts_example_results_by_type\fP (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"
.br
.ti -1c
.RI "\fBit_returns_the_worst_result_as_the_global_result\fP (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"
.br
.ti -1c
.RI "\fBit_records_how_many_specs_are_in_the_suite\fP (\fBSuiteEvent\fP $suiteEvent, \fBSuite\fP $suite, \fBSpecificationNode\fP $spec)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 13 of file StatisticsCollectorSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_counts_example_results_by_type (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"

.PP
Definition at line 80 of file StatisticsCollectorSpec\&.php\&.
.SS "it_counts_how_many_examples_have_run (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"

.PP
Definition at line 53 of file StatisticsCollectorSpec\&.php\&.
.SS "it_counts_how_many_specs_have_run (\fBSpecificationEvent\fP $specEvent1, \fBSpecificationEvent\fP $specEvent2)"

.PP
Definition at line 40 of file StatisticsCollectorSpec\&.php\&.
.SS "it_is_an_event_listener ()"

.PP
Definition at line 21 of file StatisticsCollectorSpec\&.php\&.
.SS "it_knows_no_examples_have_run_initially ()"

.PP
Definition at line 48 of file StatisticsCollectorSpec\&.php\&.
.SS "it_knows_no_specs_have_run_initially ()"

.PP
Definition at line 35 of file StatisticsCollectorSpec\&.php\&.
.SS "it_listens_to_stats_generating_events ()"

.PP
Definition at line 26 of file StatisticsCollectorSpec\&.php\&.
.SS "it_logs_all_example_events (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"

.PP
Definition at line 61 of file StatisticsCollectorSpec\&.php\&.
.SS "it_logs_all_example_events_by_type (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"

.PP
Definition at line 72 of file StatisticsCollectorSpec\&.php\&.
.SS "it_records_how_many_specs_are_in_the_suite (\fBSuiteEvent\fP $suiteEvent, \fBSuite\fP $suite, \fBSpecificationNode\fP $spec)"

.PP
Definition at line 104 of file StatisticsCollectorSpec\&.php\&.
.SS "it_returns_the_worst_result_as_the_global_result (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"

.PP
Definition at line 96 of file StatisticsCollectorSpec\&.php\&.
.SS "let (\fBExampleEvent\fP $failingExample, \fBExampleEvent\fP $passingExample)"

.PP
Definition at line 15 of file StatisticsCollectorSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
