.TH "TraversablePatchSpec" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraversablePatchSpec \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBObjectBehavior\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBit_is_a_patch\fP ()"
.br
.ti -1c
.RI "\fBit_supports_class_that_implements_only_Traversable\fP ($\fBnode\fP)"
.br
.ti -1c
.RI "\fBit_does_not_support_class_that_implements_Iterator\fP ($\fBnode\fP)"
.br
.ti -1c
.RI "\fBit_does_not_support_class_that_implements_IteratorAggregate\fP ($\fBnode\fP)"
.br
.ti -1c
.RI "\fBit_has_100_priority\fP ()"
.br
.ti -1c
.RI "\fBit_forces_node_to_implement_IteratorAggregate\fP ($\fBnode\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 8 of file TraversablePatchSpec\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "it_does_not_support_class_that_implements_Iterator ( $node)"

.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Definition at line 28 of file TraversablePatchSpec\&.php\&.
.SS "it_does_not_support_class_that_implements_IteratorAggregate ( $node)"

.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Definition at line 38 of file TraversablePatchSpec\&.php\&.
.SS "it_forces_node_to_implement_IteratorAggregate ( $node)"

.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Definition at line 53 of file TraversablePatchSpec\&.php\&.
.SS "it_has_100_priority ()"

.PP
Definition at line 45 of file TraversablePatchSpec\&.php\&.
.SS "it_is_a_patch ()"

.PP
Definition at line 10 of file TraversablePatchSpec\&.php\&.
.SS "it_supports_class_that_implements_only_Traversable ( $node)"

.PP
\fBParameters:\fP
.RS 4
\fI$node\fP 
.RE
.PP

.PP
Definition at line 18 of file TraversablePatchSpec\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
