.TH "SSH" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSH \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits SSH\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBinto\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBconnection\fP ($\fBname\fP=null)"
.br
.ti -1c
.RI "static \fBgroup\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBmultiple\fP ($names)"
.br
.ti -1c
.RI "static \fBresolve\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBgetDefaultConnection\fP ()"
.br
.ti -1c
.RI "static \fBsetDefaultConnection\fP ($\fBname\fP)"
.br
.ti -1c
.RI "static \fBdefine\fP ($\fBtask\fP, $commands)"
.br
.ti -1c
.RI "static \fBtask\fP ($task, $\fBcallback\fP=null)"
.br
.ti -1c
.RI "static \fBrun\fP ($commands, $\fBcallback\fP=null)"
.br
.ti -1c
.RI "static \fBget\fP ($remote, $local)"
.br
.ti -1c
.RI "static \fBgetString\fP ($remote)"
.br
.ti -1c
.RI "static \fBput\fP ($local, $remote)"
.br
.ti -1c
.RI "static \fBputString\fP ($remote, $contents)"
.br
.ti -1c
.RI "static \fBdisplay\fP ($\fBline\fP)"
.br
.ti -1c
.RI "static \fBstatus\fP ()"
.br
.ti -1c
.RI "static \fBgetGateway\fP ()"
.br
.ti -1c
.RI "static \fBgetOutput\fP ()"
.br
.ti -1c
.RI "static \fBsetOutput\fP ($output)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11389 of file _ide_helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static connection ( $name = \fCnull\fP)\fC [static]\fP"
Get a remote connection instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11409 of file _ide_helper\&.php\&.
.SS "static define ( $task,  $commands)\fC [static]\fP"
Define a set of commands as a task\&.
.PP
\fBParameters:\fP
.RS 4
\fI$task\fP 
.br
\fI$commands\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11475 of file _ide_helper\&.php\&.
.SS "static display ( $line)\fC [static]\fP"
Display the given line using the default output\&.
.PP
\fBParameters:\fP
.RS 4
\fI$line\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11557 of file _ide_helper\&.php\&.
.SS "static get ( $remote,  $local)\fC [static]\fP"
Download the contents of a remote file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$remote\fP 
.br
\fI$local\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11511 of file _ide_helper\&.php\&.
.SS "static getDefaultConnection ()\fC [static]\fP"
Get the default connection name\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 11452 of file _ide_helper\&.php\&.
.SS "static getGateway ()\fC [static]\fP"
Get the gateway implementation\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 11578 of file _ide_helper\&.php\&.
.SS "static getOutput ()\fC [static]\fP"
Get the output implementation for the connection\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11588 of file _ide_helper\&.php\&.
.SS "static getString ( $remote)\fC [static]\fP"
Get the contents of a remote file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$remote\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 11522 of file _ide_helper\&.php\&.
.SS "static group ( $name)\fC [static]\fP"
Get a connection group instance by name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11420 of file _ide_helper\&.php\&.
.SS "static into ( $name)\fC [static]\fP"
Get a remote connection instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11398 of file _ide_helper\&.php\&.
.SS "static multiple ( $names)\fC [static]\fP"
Resolve a multiple connection instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$names\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11431 of file _ide_helper\&.php\&.
.SS "static put ( $local,  $remote)\fC [static]\fP"
Upload a local file to the server\&.
.PP
\fBParameters:\fP
.RS 4
\fI$local\fP 
.br
\fI$remote\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11534 of file _ide_helper\&.php\&.
.SS "static putString ( $remote,  $contents)\fC [static]\fP"
Upload a string to to the given file on the server\&.
.PP
\fBParameters:\fP
.RS 4
\fI$remote\fP 
.br
\fI$contents\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11546 of file _ide_helper\&.php\&.
.SS "static resolve ( $name)\fC [static]\fP"
Resolve a remote connection instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11442 of file _ide_helper\&.php\&.
.SS "static run ( $commands,  $callback = \fCnull\fP)\fC [static]\fP"
Run a set of commands against the connection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$commands\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11499 of file _ide_helper\&.php\&.
.SS "static setDefaultConnection ( $name)\fC [static]\fP"
Set the default connection name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11463 of file _ide_helper\&.php\&.
.SS "static setOutput ( $output)\fC [static]\fP"
Set the output implementation\&.
.PP
\fBParameters:\fP
.RS 4
\fI$output\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11599 of file _ide_helper\&.php\&.
.SS "static status ()\fC [static]\fP"
Get the exit status of the last command\&.
.PP
\fBReturns:\fP
.RS 4
int|bool 
.RE
.PP

.PP
Definition at line 11567 of file _ide_helper\&.php\&.
.SS "static task ( $task,  $callback = \fCnull\fP)\fC [static]\fP"
Run a task against the connection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$task\fP 
.br
\fI$callback\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11487 of file _ide_helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
