.TH "vendor/league/flysystem/src/Adapter/Polyfill/StreamedCopyTrait.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/league/flysystem/src/Adapter/Polyfill/StreamedCopyTrait.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBLeague\\Flysystem\\Adapter\\Polyfill\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwriteStream\fP ($\fBpath\fP, $resource, \fBConfig\fP $config)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "trait \fBStreamedCopyTrait\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
