.TH "StringsTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringsTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestToString\fP ()"
.br
.ti -1c
.RI "\fBtestSetToStringFormat\fP ()"
.br
.ti -1c
.RI "\fBtestResetToStringFormat\fP ()"
.br
.ti -1c
.RI "\fBtestExtendedClassToString\fP ()"
.br
.ti -1c
.RI "\fBtestToDateString\fP ()"
.br
.ti -1c
.RI "\fBtestToFormattedDateString\fP ()"
.br
.ti -1c
.RI "\fBtestToLocalizedFormattedDateString\fP ()"
.br
.ti -1c
.RI "\fBtestToLocalizedFormattedTimezonedDateString\fP ()"
.br
.ti -1c
.RI "\fBtestToTimeString\fP ()"
.br
.ti -1c
.RI "\fBtestToDateTimeString\fP ()"
.br
.ti -1c
.RI "\fBtestToDateTimeStringWithPaddedZeroes\fP ()"
.br
.ti -1c
.RI "\fBtestToDayDateTimeString\fP ()"
.br
.ti -1c
.RI "\fBtestToAtomString\fP ()"
.br
.ti -1c
.RI "\fBtestToCOOKIEString\fP ()"
.br
.ti -1c
.RI "\fBtestToIso8601String\fP ()"
.br
.ti -1c
.RI "\fBtestToRC822String\fP ()"
.br
.ti -1c
.RI "\fBtestToRfc850String\fP ()"
.br
.ti -1c
.RI "\fBtestToRfc1036String\fP ()"
.br
.ti -1c
.RI "\fBtestToRfc1123String\fP ()"
.br
.ti -1c
.RI "\fBtestToRfc2822String\fP ()"
.br
.ti -1c
.RI "\fBtestToRfc3339String\fP ()"
.br
.ti -1c
.RI "\fBtestToRssString\fP ()"
.br
.ti -1c
.RI "\fBtestToW3cString\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file StringsTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testExtendedClassToString ()"

.PP
Definition at line 38 of file StringsTest\&.php\&.
.SS "testResetToStringFormat ()"

.PP
Definition at line 31 of file StringsTest\&.php\&.
.SS "testSetToStringFormat ()"

.PP
Definition at line 25 of file StringsTest\&.php\&.
.SS "testToAtomString ()"

.PP
Definition at line 96 of file StringsTest\&.php\&.
.SS "testToCOOKIEString ()"

.PP
Definition at line 101 of file StringsTest\&.php\&.
.SS "testToDateString ()"

.PP
Definition at line 44 of file StringsTest\&.php\&.
.SS "testToDateTimeString ()"

.PP
Definition at line 80 of file StringsTest\&.php\&.
.SS "testToDateTimeStringWithPaddedZeroes ()"

.PP
Definition at line 85 of file StringsTest\&.php\&.
.SS "testToDayDateTimeString ()"

.PP
Definition at line 90 of file StringsTest\&.php\&.
.SS "testToFormattedDateString ()"

.PP
Definition at line 49 of file StringsTest\&.php\&.
.SS "testToIso8601String ()"

.PP
Definition at line 112 of file StringsTest\&.php\&.
.SS "testToLocalizedFormattedDateString ()"

.PP
Definition at line 54 of file StringsTest\&.php\&.
.SS "testToLocalizedFormattedTimezonedDateString ()"

.PP
Definition at line 70 of file StringsTest\&.php\&.
.SS "testToRC822String ()"

.PP
Definition at line 117 of file StringsTest\&.php\&.
.SS "testToRfc1036String ()"

.PP
Definition at line 127 of file StringsTest\&.php\&.
.SS "testToRfc1123String ()"

.PP
Definition at line 132 of file StringsTest\&.php\&.
.SS "testToRfc2822String ()"

.PP
Definition at line 137 of file StringsTest\&.php\&.
.SS "testToRfc3339String ()"

.PP
Definition at line 142 of file StringsTest\&.php\&.
.SS "testToRfc850String ()"

.PP
Definition at line 122 of file StringsTest\&.php\&.
.SS "testToRssString ()"

.PP
Definition at line 147 of file StringsTest\&.php\&.
.SS "testToString ()"

.PP
Definition at line 20 of file StringsTest\&.php\&.
.SS "testToTimeString ()"

.PP
Definition at line 75 of file StringsTest\&.php\&.
.SS "testToW3cString ()"

.PP
Definition at line 152 of file StringsTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
