.TH "SuperClosureException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SuperClosureException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBClosureAnalysisException\fP, and \fBClosureUnserializationException\fP\&.
.SH "Detailed Description"
.PP 
This is a marker exception for the \fBSuperClosure\fP library\&. 
.PP
Definition at line 6 of file SuperClosureException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
