.TH "MagicConstantVisitor" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MagicConstantVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeVisitorAbstract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $location)"
.br
.ti -1c
.RI "\fBleaveNode\fP (AstNode $\fBnode\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a visitor that resolves magic constants (e\&.g\&., \fBFILE\fP) to their intended values within a closure's AST\&. 
.PP
Definition at line 14 of file MagicConstantVisitor\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $location)"

.PP
\fBParameters:\fP
.RS 4
\fI$location\fP 
.RE
.PP

.PP
Definition at line 24 of file MagicConstantVisitor\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "leaveNode (AstNode $node)"

.PP
Definition at line 29 of file MagicConstantVisitor\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
