.TH "ClosureLocatorVisitor" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClosureLocatorVisitor \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNodeVisitorAbstract\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($reflection)"
.br
.ti -1c
.RI "\fBenterNode\fP (AstNode $\fBnode\fP)"
.br
.ti -1c
.RI "\fBleaveNode\fP (AstNode $\fBnode\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$closureNode\fP"
.br
.ti -1c
.RI "\fB$location\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a visitor that extends the nikic/php-parser library and looks for a closure node and its location\&. 
.PP
Definition at line 17 of file ClosureLocatorVisitor\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $reflection)"

.PP
\fBParameters:\fP
.RS 4
\fI$reflection\fP 
.RE
.PP

.PP
Definition at line 37 of file ClosureLocatorVisitor\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "enterNode (AstNode $node)"

.PP
Definition at line 52 of file ClosureLocatorVisitor\&.php\&.
.SS "leaveNode (AstNode $node)"

.PP
Definition at line 86 of file ClosureLocatorVisitor\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$closureNode"

.PP
Definition at line 27 of file ClosureLocatorVisitor\&.php\&.
.SS "$location"

.PP
Definition at line 32 of file ClosureLocatorVisitor\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
