.TH "Swift_Mime_Headers_PathHeader" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_Headers_PathHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Mime_Headers_AbstractHeader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP, \fBSwift_Mime_Grammar\fP $grammar)"
.br
.ti -1c
.RI "\fBgetFieldType\fP ()"
.br
.ti -1c
.RI "\fBsetFieldBodyModel\fP ($model)"
.br
.ti -1c
.RI "\fBgetFieldBodyModel\fP ()"
.br
.ti -1c
.RI "\fBsetAddress\fP ($address)"
.br
.ti -1c
.RI "\fBgetAddress\fP ()"
.br
.ti -1c
.RI "\fBgetFieldBody\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP Path Header in \fBSwift\fP Mailer, such a Return-Path\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file PathHeader\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name, \fBSwift_Mime_Grammar\fP $grammar)"
Creates a new PathHeader with the given $name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$grammar\fP 
.RE
.PP

.PP
Definition at line 31 of file PathHeader\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getAddress ()"
Get the address which is used in this Header (if any)\&.
.PP
Null is returned if no address is set\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 101 of file PathHeader\&.php\&.
.SS "getFieldBody ()"
Get the string value of the body in this Header\&.
.PP
This is not necessarily RFC 2822 compliant since folding white space will not be added at this stage (see \fBtoString()\fP for that)\&.
.PP
\fBSee also:\fP
.RS 4
\fBtoString()\fP
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBSwift_Mime_Header\fP\&.
.PP
Definition at line 116 of file PathHeader\&.php\&.
.SS "getFieldBodyModel ()"
Get the model for the field body\&. This method returns a string email address\&.
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implements \fBSwift_Mime_Header\fP\&.
.PP
Definition at line 69 of file PathHeader\&.php\&.
.SS "getFieldType ()"
Get the type of Header that this instance represents\&.
.PP
\fBSee also:\fP
.RS 4
\fBTYPE_TEXT\fP, \fBTYPE_PARAMETERIZED\fP, \fBTYPE_MAILBOX\fP 
.PP
\fBTYPE_DATE\fP, \fBTYPE_ID\fP, \fBTYPE_PATH\fP
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBSwift_Mime_Header\fP\&.
.PP
Definition at line 45 of file PathHeader\&.php\&.
.SS "setAddress ( $address)"
Set the Address which should appear in this Header\&.
.PP
\fBParameters:\fP
.RS 4
\fI$address\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSwift_RfcComplianceException\fP\fP 
.RE
.PP

.PP
Definition at line 81 of file PathHeader\&.php\&.
.SS "setFieldBodyModel ( $model)"
Set the model for the field body\&. This method takes a string for an address\&.
.PP
\fBParameters:\fP
.RS 4
\fI$model\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSwift_RfcComplianceException\fP\fP 
.RE
.PP

.PP
Implements \fBSwift_Mime_Header\fP\&.
.PP
Definition at line 58 of file PathHeader\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
