.TH "Swift_Bug76Test" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Bug76Test \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.ti -1c
.RI "\fBtestBase64EncodedLineLengthNeverExceeds76CharactersEvenIfArgsDo\fP ()"
.br
.ti -1c
.RI "\fBassertMaxLineLength\fP ($length, $filePath, $message= '%s')"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file Bug76Test\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "assertMaxLineLength ( $length,  $filePath,  $message = \fC'%s'\fP)"

.PP
Definition at line 49 of file Bug76Test\&.php\&.
.SS "setUp ()"

.PP
Definition at line 9 of file Bug76Test\&.php\&.
.SS "tearDown ()"

.PP
Definition at line 27 of file Bug76Test\&.php\&.
.SS "testBase64EncodedLineLengthNeverExceeds76CharactersEvenIfArgsDo ()"

.PP
Definition at line 33 of file Bug76Test\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
