.TH "Swift_Transport_Esmtp_Auth_NTLMAuthenticatorTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Transport_Esmtp_Auth_NTLMAuthenticatorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwiftMailerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestKeywordIsNtlm\fP ()"
.br
.ti -1c
.RI "\fBtestMessage1Generator\fP ()"
.br
.ti -1c
.RI "\fBtestLMv1Generator\fP ()"
.br
.ti -1c
.RI "\fBtestLMv2Generator\fP ()"
.br
.ti -1c
.RI "\fBtestMessage3v1Generator\fP ()"
.br
.ti -1c
.RI "\fBtestMessage3v2Generator\fP ()"
.br
.ti -1c
.RI "\fBtestGetDomainAndUsername\fP ()"
.br
.ti -1c
.RI "\fBtestGetDomainAndUsernameWithExtension\fP ()"
.br
.ti -1c
.RI "\fBtestGetDomainAndUsernameWithAtSymbol\fP ()"
.br
.ti -1c
.RI "\fBtestGetDomainAndUsernameWithAtSymbolAndExtension\fP ()"
.br
.ti -1c
.RI "\fBtestSuccessfulAuthentication\fP ()"
.br
.ti -1c
.RI "\fBtestAuthenticationFailureSendRsetAndReturnFalse\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBhex2bin\fP ($hex)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file NTLMAuthenticatorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "hex2bin ( $hex)\fC [protected]\fP"
Hex2bin replacement for < \fBPHP\fP 5\&.4 
.PP
\fBParameters:\fP
.RS 4
\fI$hex\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string Binary 
.RE
.PP

.PP
Definition at line 229 of file NTLMAuthenticatorTest\&.php\&.
.SS "setUp ()"

.PP
Definition at line 9 of file NTLMAuthenticatorTest\&.php\&.
.SS "testAuthenticationFailureSendRsetAndReturnFalse ()"

.PP
Definition at line 182 of file NTLMAuthenticatorTest\&.php\&.
.SS "testGetDomainAndUsername ()"

.PP
Definition at line 97 of file NTLMAuthenticatorTest\&.php\&.
.SS "testGetDomainAndUsernameWithAtSymbol ()"

.PP
Definition at line 127 of file NTLMAuthenticatorTest\&.php\&.
.SS "testGetDomainAndUsernameWithAtSymbolAndExtension ()"

.PP
Definition at line 142 of file NTLMAuthenticatorTest\&.php\&.
.SS "testGetDomainAndUsernameWithExtension ()"

.PP
Definition at line 112 of file NTLMAuthenticatorTest\&.php\&.
.SS "testKeywordIsNtlm ()"

.PP
Definition at line 18 of file NTLMAuthenticatorTest\&.php\&.
.SS "testLMv1Generator ()"

.PP
Definition at line 34 of file NTLMAuthenticatorTest\&.php\&.
.SS "testLMv2Generator ()"

.PP
Definition at line 48 of file NTLMAuthenticatorTest\&.php\&.
.SS "testMessage1Generator ()"

.PP
Definition at line 24 of file NTLMAuthenticatorTest\&.php\&.
.SS "testMessage3v1Generator ()"

.PP
Definition at line 64 of file NTLMAuthenticatorTest\&.php\&.
.SS "testMessage3v2Generator ()"

.PP
Definition at line 81 of file NTLMAuthenticatorTest\&.php\&.
.SS "testSuccessfulAuthentication ()"

.PP
Definition at line 157 of file NTLMAuthenticatorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
