.TH "Swift_Mime_HeaderSet" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_HeaderSet \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Mime_CharsetObserver\fP\&.
.PP
Inherited by \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaddMailboxHeader\fP ($\fBname\fP, $addresses=null)"
.br
.ti -1c
.RI "\fBaddDateHeader\fP ($\fBname\fP, $timestamp=null)"
.br
.ti -1c
.RI "\fBaddTextHeader\fP ($\fBname\fP, $value=null)"
.br
.ti -1c
.RI "\fBaddParameterizedHeader\fP ($\fBname\fP, $value=null, $params=array())"
.br
.ti -1c
.RI "\fBaddIdHeader\fP ($\fBname\fP, $ids=null)"
.br
.ti -1c
.RI "\fBaddPathHeader\fP ($\fBname\fP, $\fBpath\fP=null)"
.br
.ti -1c
.RI "\fBhas\fP ($\fBname\fP, $index=0)"
.br
.ti -1c
.RI "\fBset\fP (\fBSwift_Mime_Header\fP $header, $index=0)"
.br
.ti -1c
.RI "\fBget\fP ($\fBname\fP, $index=0)"
.br
.ti -1c
.RI "\fBgetAll\fP ($\fBname\fP=null)"
.br
.ti -1c
.RI "\fBlistAll\fP ()"
.br
.ti -1c
.RI "\fBremove\fP ($\fBname\fP, $index=0)"
.br
.ti -1c
.RI "\fBremoveAll\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBnewInstance\fP ()"
.br
.ti -1c
.RI "\fBdefineOrdering\fP (array $sequence)"
.br
.ti -1c
.RI "\fBsetAlwaysDisplayed\fP (array $names)"
.br
.ti -1c
.RI "\fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP collection of MIME headers\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file HeaderSet\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addDateHeader ( $name,  $timestamp = \fCnull\fP)"
Add a new Date header using $timestamp (UNIX time)\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$timestamp\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "addIdHeader ( $name,  $ids = \fCnull\fP)"
Add a new ID header for Message-ID or Content-ID\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$ids\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "addMailboxHeader ( $name,  $addresses = \fCnull\fP)"
Add a new Mailbox Header with a list of $addresses\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$addresses\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "addParameterizedHeader ( $name,  $value = \fCnull\fP,  $params = \fCarray()\fP)"
Add a new ParameterizedHeader with $name, $value and $params\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$value\fP 
.br
\fI$params\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "addPathHeader ( $name,  $path = \fCnull\fP)"
Add a new Path header with an address (path) in it\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$path\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "addTextHeader ( $name,  $value = \fCnull\fP)"
Add a new basic text header with $name and $value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$value\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "defineOrdering (array $sequence)"
Define a list of Header names as an array in the correct order\&.
.PP
These Headers will be output in the given order where present\&.
.PP
\fBParameters:\fP
.RS 4
\fI$sequence\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "get ( $name,  $index = \fC0\fP)"
Get the header with the given $name\&. If multiple headers match, the actual one may be specified by $index\&. Returns NULL if none present\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$index\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSwift_Mime_Header\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "getAll ( $name = \fCnull\fP)"
Get all headers with the given $name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "has ( $name,  $index = \fC0\fP)"
Returns true if at least one header with the given $name exists\&.
.PP
If multiple headers match, the actual one may be specified by $index\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$index\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "listAll ()"
Return the name of all Headers
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "newInstance ()"
Create a new instance of this HeaderSet\&.
.PP
\fBReturns:\fP
.RS 4
\fBSwift_Mime_HeaderSet\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "remove ( $name,  $index = \fC0\fP)"
Remove the header with the given $name if it's set\&.
.PP
If multiple headers match, the actual one may be specified by $index\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$index\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "removeAll ( $name)"
Remove all headers with the given $name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "set (\fBSwift_Mime_Header\fP $header,  $index = \fC0\fP)"
Set a header in the HeaderSet\&.
.PP
The header may be a previously fetched header via \fBget()\fP or it may be one that has been created separately\&.
.PP
If $index is specified, the header will be inserted into the set at this offset\&.
.PP
\fBParameters:\fP
.RS 4
\fI$header\fP 
.br
\fI$index\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "setAlwaysDisplayed (array $names)"
Set a list of header names which must always be displayed when set\&.
.PP
Usually headers without a field value won't be output unless set here\&.
.PP
\fBParameters:\fP
.RS 4
\fI$names\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.
.SS "toString ()"
Returns a string with a representation of all headers\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_SimpleHeaderSet\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
