.TH "Swift_Mime_ParameterizedHeader" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_ParameterizedHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Mime_Header\fP\&.
.PP
Inherited by \fBSwift_Mime_Headers_ParameterizedHeader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetParameter\fP ($parameter, $value)"
.br
.ti -1c
.RI "\fBgetParameter\fP ($parameter)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP MIME Header with parameters\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file ParameterizedHeader\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getParameter ( $parameter)"
Get the value of $parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fI$parameter\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_Headers_ParameterizedHeader\fP\&.
.SS "setParameter ( $parameter,  $value)"
Set the value of $parameter\&.
.PP
\fBParameters:\fP
.RS 4
\fI$parameter\fP 
.br
\fI$value\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Mime_Headers_ParameterizedHeader\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
