.TH "Swift_Mime_ContentEncoder_Base64ContentEncoder" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_ContentEncoder_Base64ContentEncoder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Encoder_Base64Encoder\fP, and \fBSwift_Mime_ContentEncoder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBencodeByteStream\fP (\fBSwift_OutputByteStream\fP $os, \fBSwift_InputByteStream\fP $is, $firstLineOffset=0, $maxLineLength=0)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles Base 64 Transfer Encoding in \fBSwift\fP Mailer\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file Base64ContentEncoder\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "encodeByteStream (\fBSwift_OutputByteStream\fP $os, \fBSwift_InputByteStream\fP $is,  $firstLineOffset = \fC0\fP,  $maxLineLength = \fC0\fP)"
Encode stream $in to stream $out\&.
.PP
\fBParameters:\fP
.RS 4
\fI$os\fP 
.br
\fI$is\fP 
.br
\fI$firstLineOffset\fP 
.br
\fI$maxLineLength,optional,0\fP indicates the default of 76 bytes 
.RE
.PP

.PP
Implements \fBSwift_Mime_ContentEncoder\fP\&.
.PP
Definition at line 26 of file Base64ContentEncoder\&.php\&.
.SS "getName ()"
Get the name of this encoding scheme\&. Returns the string 'base64'\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBSwift_Mime_ContentEncoder\fP\&.
.PP
Definition at line 100 of file Base64ContentEncoder\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
