.TH "Swift_KeyCache_SimpleKeyCacheInputStream" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_KeyCache_SimpleKeyCacheInputStream \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_KeyCache_KeyCacheInputStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetKeyCache\fP (\fBSwift_KeyCache\fP $keyCache)"
.br
.ti -1c
.RI "\fBsetWriteThroughStream\fP (\fBSwift_InputByteStream\fP $is)"
.br
.ti -1c
.RI "\fBwrite\fP ($bytes, \fBSwift_InputByteStream\fP $is=null)"
.br
.ti -1c
.RI "\fBcommit\fP ()"
.br
.ti -1c
.RI "\fBbind\fP (\fBSwift_InputByteStream\fP $is)"
.br
.ti -1c
.RI "\fBunbind\fP (\fBSwift_InputByteStream\fP $is)"
.br
.ti -1c
.RI "\fBflushBuffers\fP ()"
.br
.ti -1c
.RI "\fBsetNsKey\fP ($nsKey)"
.br
.ti -1c
.RI "\fBsetItemKey\fP ($itemKey)"
.br
.ti -1c
.RI "\fB__clone\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Writes data to a KeyCache using a stream\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file SimpleKeyCacheInputStream\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__clone ()"
Any implementation should be cloneable, allowing the clone to access a separate $nsKey and $itemKey\&. 
.PP
Implements \fBSwift_KeyCache_KeyCacheInputStream\fP\&.
.PP
Definition at line 123 of file SimpleKeyCacheInputStream\&.php\&.
.SS "bind (\fBSwift_InputByteStream\fP $is)"
Not used\&. 
.PP
Implements \fBSwift_InputByteStream\fP\&.
.PP
Definition at line 79 of file SimpleKeyCacheInputStream\&.php\&.
.SS "commit ()"
Not used\&. 
.PP
Implements \fBSwift_InputByteStream\fP\&.
.PP
Definition at line 72 of file SimpleKeyCacheInputStream\&.php\&.
.SS "flushBuffers ()"
Flush the contents of the stream (empty it) and set the internal pointer to the beginning\&. 
.PP
Implements \fBSwift_InputByteStream\fP\&.
.PP
Definition at line 94 of file SimpleKeyCacheInputStream\&.php\&.
.SS "setItemKey ( $itemKey)"
Set the itemKey which will be written to\&.
.PP
\fBParameters:\fP
.RS 4
\fI$itemKey\fP 
.RE
.PP

.PP
Implements \fBSwift_KeyCache_KeyCacheInputStream\fP\&.
.PP
Definition at line 114 of file SimpleKeyCacheInputStream\&.php\&.
.SS "setKeyCache (\fBSwift_KeyCache\fP $keyCache)"
Set the KeyCache to wrap\&.
.PP
\fBParameters:\fP
.RS 4
\fI$keyCache\fP 
.RE
.PP

.PP
Implements \fBSwift_KeyCache_KeyCacheInputStream\fP\&.
.PP
Definition at line 35 of file SimpleKeyCacheInputStream\&.php\&.
.SS "setNsKey ( $nsKey)"
Set the nsKey which will be written to\&.
.PP
\fBParameters:\fP
.RS 4
\fI$nsKey\fP 
.RE
.PP

.PP
Implements \fBSwift_KeyCache_KeyCacheInputStream\fP\&.
.PP
Definition at line 104 of file SimpleKeyCacheInputStream\&.php\&.
.SS "setWriteThroughStream (\fBSwift_InputByteStream\fP $is)"
Specify a stream to write through for each \fBwrite()\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$is\fP 
.RE
.PP

.PP
Implements \fBSwift_KeyCache_KeyCacheInputStream\fP\&.
.PP
Definition at line 45 of file SimpleKeyCacheInputStream\&.php\&.
.SS "unbind (\fBSwift_InputByteStream\fP $is)"
Not used\&. 
.PP
Implements \fBSwift_InputByteStream\fP\&.
.PP
Definition at line 86 of file SimpleKeyCacheInputStream\&.php\&.
.SS "write ( $bytes, \fBSwift_InputByteStream\fP $is = \fCnull\fP)"
Writes $bytes to the end of the stream\&.
.PP
\fBParameters:\fP
.RS 4
\fI$bytes\fP 
.br
\fI$is\fP optional 
.RE
.PP

.PP
Definition at line 56 of file SimpleKeyCacheInputStream\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
