.TH "Swift_Mime_ContentEncoder_QpContentEncoderAcceptanceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_ContentEncoder_QpContentEncoderAcceptanceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingAndDecodingSamples\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingAndDecodingSamplesFromDiConfiguredInstance\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingLFTextWithDiConfiguredInstance\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingCRTextWithDiConfiguredInstance\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingLFCRTextWithDiConfiguredInstance\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingCRLFTextWithDiConfiguredInstance\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingDotStuffingWithDiConfiguredInstance\fP ()"
.br
.ti -1c
.RI "\fBtestDotStuffingEncodingAndDecodingSamplesFromDiConfiguredInstance\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file QpContentEncoderAcceptanceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()"

.PP
Definition at line 8 of file QpContentEncoderAcceptanceTest\&.php\&.
.SS "testDotStuffingEncodingAndDecodingSamplesFromDiConfiguredInstance ()"

.PP
Definition at line 142 of file QpContentEncoderAcceptanceTest\&.php\&.
.SS "testEncodingAndDecodingSamples ()"

.PP
Definition at line 14 of file QpContentEncoderAcceptanceTest\&.php\&.
.SS "testEncodingAndDecodingSamplesFromDiConfiguredInstance ()"

.PP
Definition at line 61 of file QpContentEncoderAcceptanceTest\&.php\&.
.SS "testEncodingCRLFTextWithDiConfiguredInstance ()"

.PP
Definition at line 124 of file QpContentEncoderAcceptanceTest\&.php\&.
.SS "testEncodingCRTextWithDiConfiguredInstance ()"

.PP
Definition at line 112 of file QpContentEncoderAcceptanceTest\&.php\&.
.SS "testEncodingDotStuffingWithDiConfiguredInstance ()"

.PP
Definition at line 130 of file QpContentEncoderAcceptanceTest\&.php\&.
.SS "testEncodingLFCRTextWithDiConfiguredInstance ()"

.PP
Definition at line 118 of file QpContentEncoderAcceptanceTest\&.php\&.
.SS "testEncodingLFTextWithDiConfiguredInstance ()"

.PP
Definition at line 106 of file QpContentEncoderAcceptanceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
