.TH "Swift_Transport_Esmtp_Auth_CramMd5AuthenticatorTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Transport_Esmtp_Auth_CramMd5AuthenticatorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwiftMailerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestKeywordIsCramMd5\fP ()"
.br
.ti -1c
.RI "\fBtestSuccessfulAuthentication\fP ()"
.br
.ti -1c
.RI "\fBtestAuthenticationFailureSendRsetAndReturnFalse\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file CramMd5AuthenticatorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()"

.PP
Definition at line 7 of file CramMd5AuthenticatorTest\&.php\&.
.SS "testAuthenticationFailureSendRsetAndReturnFalse ()"

.PP
Definition at line 39 of file CramMd5AuthenticatorTest\&.php\&.
.SS "testKeywordIsCramMd5 ()"

.PP
Definition at line 12 of file CramMd5AuthenticatorTest\&.php\&.
.SS "testSuccessfulAuthentication ()"

.PP
Definition at line 22 of file CramMd5AuthenticatorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
