.TH "Swift_Mime_Grammar" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_Grammar \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fB__wakeup\fP ()"
.br
.ti -1c
.RI "\fBgetDefinition\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBgetGrammarDefinitions\fP ()"
.br
.ti -1c
.RI "\fBgetSpecials\fP ()"
.br
.ti -1c
.RI "\fBescapeSpecials\fP ($token, $include=array(), $exclude=array())"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBinit\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the grammar to use for validation, implements the RFC 2822 (and friends) ABNF grammar definitions\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier 
.PP
Chris Corbyn 
.RE
.PP

.PP
Definition at line 17 of file Grammar\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"
Initialize some RFC 2822 (and friends) ABNF grammar definitions\&. 
.PP
Definition at line 36 of file Grammar\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__wakeup ()"

.PP
Definition at line 41 of file Grammar\&.php\&.
.SS "escapeSpecials ( $token,  $include = \fCarray()\fP,  $exclude = \fCarray()\fP)"
Escape special characters in a string (convert to quoted-pairs)\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP 
.br
\fIstring[]\fP $include additional chars to escape 
.br
\fIstring[]\fP $exclude chars from escaping
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 168 of file Grammar\&.php\&.
.SS "getDefinition ( $name)"
Get the grammar defined for $name token\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP exactly as written in the RFC
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 128 of file Grammar\&.php\&.
.SS "getGrammarDefinitions ()"
Returns the tokens defined in RFC 2822 (and some related RFCs)\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 144 of file Grammar\&.php\&.
.SS "getSpecials ()"
Returns the current special characters used in the syntax which need to be escaped\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 154 of file Grammar\&.php\&.
.SS "init ()\fC [protected]\fP"

.PP
Definition at line 46 of file Grammar\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
