.TH "Swift_Mime_Headers_PathHeaderTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_Headers_PathHeaderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestTypeIsPathHeader\fP ()"
.br
.ti -1c
.RI "\fBtestSingleAddressCanBeSetAndFetched\fP ()"
.br
.ti -1c
.RI "\fBtestAddressMustComplyWithRfc2822\fP ()"
.br
.ti -1c
.RI "\fBtestValueIsAngleAddrWithValidAddress\fP ()"
.br
.ti -1c
.RI "\fBtestValueIsEmptyAngleBracketsIfEmptyAddressSet\fP ()"
.br
.ti -1c
.RI "\fBtestSetBodyModel\fP ()"
.br
.ti -1c
.RI "\fBtestGetBodyModel\fP ()"
.br
.ti -1c
.RI "\fBtestToString\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file PathHeaderTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAddressMustComplyWithRfc2822 ()"

.PP
Definition at line 18 of file PathHeaderTest\&.php\&.
.SS "testGetBodyModel ()"

.PP
Definition at line 57 of file PathHeaderTest\&.php\&.
.SS "testSetBodyModel ()"

.PP
Definition at line 50 of file PathHeaderTest\&.php\&.
.SS "testSingleAddressCanBeSetAndFetched ()"

.PP
Definition at line 11 of file PathHeaderTest\&.php\&.
.SS "testToString ()"

.PP
Definition at line 64 of file PathHeaderTest\&.php\&.
.SS "testTypeIsPathHeader ()"

.PP
Definition at line 5 of file PathHeaderTest\&.php\&.
.SS "testValueIsAngleAddrWithValidAddress ()"

.PP
Definition at line 28 of file PathHeaderTest\&.php\&.
.SS "testValueIsEmptyAngleBracketsIfEmptyAddressSet ()"

.PP
Definition at line 43 of file PathHeaderTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
