.TH "Swift_Mime_Headers_IdentificationHeaderTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_Headers_IdentificationHeaderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestTypeIsIdHeader\fP ()"
.br
.ti -1c
.RI "\fBtestValueMatchesMsgIdSpec\fP ()"
.br
.ti -1c
.RI "\fBtestIdCanBeRetrievedVerbatim\fP ()"
.br
.ti -1c
.RI "\fBtestMultipleIdsCanBeSet\fP ()"
.br
.ti -1c
.RI "\fBtestSettingMultipleIdsProducesAListValue\fP ()"
.br
.ti -1c
.RI "\fBtestIdLeftCanBeQuoted\fP ()"
.br
.ti -1c
.RI "\fBtestIdLeftCanContainAnglesAsQuotedPairs\fP ()"
.br
.ti -1c
.RI "\fBtestIdLeftCanBeDotAtom\fP ()"
.br
.ti -1c
.RI "\fBtestInvalidIdLeftThrowsException\fP ()"
.br
.ti -1c
.RI "\fBtestIdRightCanBeDotAtom\fP ()"
.br
.ti -1c
.RI "\fBtestIdRightCanBeLiteral\fP ()"
.br
.ti -1c
.RI "\fBtestInvalidIdRightThrowsException\fP ()"
.br
.ti -1c
.RI "\fBtestMissingAtSignThrowsException\fP ()"
.br
.ti -1c
.RI "\fBtestSetBodyModel\fP ()"
.br
.ti -1c
.RI "\fBtestGetBodyModel\fP ()"
.br
.ti -1c
.RI "\fBtestStringValue\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file IdentificationHeaderTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testGetBodyModel ()"

.PP
Definition at line 171 of file IdentificationHeaderTest\&.php\&.
.SS "testIdCanBeRetrievedVerbatim ()"

.PP
Definition at line 36 of file IdentificationHeaderTest\&.php\&.
.SS "testIdLeftCanBeDotAtom ()"

.PP
Definition at line 92 of file IdentificationHeaderTest\&.php\&.
.SS "testIdLeftCanBeQuoted ()"

.PP
Definition at line 68 of file IdentificationHeaderTest\&.php\&.
.SS "testIdLeftCanContainAnglesAsQuotedPairs ()"

.PP
Definition at line 80 of file IdentificationHeaderTest\&.php\&.
.SS "testIdRightCanBeDotAtom ()"

.PP
Definition at line 112 of file IdentificationHeaderTest\&.php\&.
.SS "testIdRightCanBeLiteral ()"

.PP
Definition at line 124 of file IdentificationHeaderTest\&.php\&.
.SS "testInvalidIdLeftThrowsException ()"

.PP
Definition at line 100 of file IdentificationHeaderTest\&.php\&.
.SS "testInvalidIdRightThrowsException ()"

.PP
Definition at line 136 of file IdentificationHeaderTest\&.php\&.
.SS "testMissingAtSignThrowsException ()"

.PP
Definition at line 148 of file IdentificationHeaderTest\&.php\&.
.SS "testMultipleIdsCanBeSet ()"

.PP
Definition at line 43 of file IdentificationHeaderTest\&.php\&.
.SS "testSetBodyModel ()"

.PP
Definition at line 164 of file IdentificationHeaderTest\&.php\&.
.SS "testSettingMultipleIdsProducesAListValue ()"

.PP
Definition at line 50 of file IdentificationHeaderTest\&.php\&.
.SS "testStringValue ()"

.PP
Definition at line 178 of file IdentificationHeaderTest\&.php\&.
.SS "testTypeIsIdHeader ()"

.PP
Definition at line 5 of file IdentificationHeaderTest\&.php\&.
.SS "testValueMatchesMsgIdSpec ()"

.PP
Definition at line 11 of file IdentificationHeaderTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
