.TH "Swift_Mime_Headers_UnstructuredHeader" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_Headers_UnstructuredHeader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Mime_Headers_AbstractHeader\fP\&.
.PP
Inherited by \fBSwift_Mime_Headers_ParameterizedHeader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP, \fBSwift_Mime_HeaderEncoder\fP $encoder, \fBSwift_Mime_Grammar\fP $grammar)"
.br
.ti -1c
.RI "\fBgetFieldType\fP ()"
.br
.ti -1c
.RI "\fBsetFieldBodyModel\fP ($model)"
.br
.ti -1c
.RI "\fBgetFieldBodyModel\fP ()"
.br
.ti -1c
.RI "\fBgetValue\fP ()"
.br
.ti -1c
.RI "\fBsetValue\fP ($value)"
.br
.ti -1c
.RI "\fBgetFieldBody\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBA\fP Simple MIME Header\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file UnstructuredHeader\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name, \fBSwift_Mime_HeaderEncoder\fP $encoder, \fBSwift_Mime_Grammar\fP $grammar)"
Creates a new SimpleHeader with $name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$encoder\fP 
.br
\fI$grammar\fP 
.RE
.PP

.PP
Definition at line 32 of file UnstructuredHeader\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getFieldBody ()"
Get the value of this header prepared for rendering\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBSwift_Mime_Header\fP\&.
.PP
Definition at line 102 of file UnstructuredHeader\&.php\&.
.SS "getFieldBodyModel ()"
Get the model for the field body\&.
.PP
This method returns a string\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBSwift_Mime_Header\fP\&.
.PP
Definition at line 71 of file UnstructuredHeader\&.php\&.
.SS "getFieldType ()"
Get the type of Header that this instance represents\&.
.PP
\fBSee also:\fP
.RS 4
\fBTYPE_TEXT\fP, \fBTYPE_PARAMETERIZED\fP, \fBTYPE_MAILBOX\fP 
.PP
\fBTYPE_DATE\fP, \fBTYPE_ID\fP, \fBTYPE_PATH\fP
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBSwift_Mime_Header\fP\&.
.PP
Definition at line 47 of file UnstructuredHeader\&.php\&.
.SS "getValue ()"
Get the (unencoded) value of this header\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 81 of file UnstructuredHeader\&.php\&.
.SS "setFieldBodyModel ( $model)"
Set the model for the field body\&.
.PP
This method takes a string for the field value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$model\fP 
.RE
.PP

.PP
Implements \fBSwift_Mime_Header\fP\&.
.PP
Definition at line 59 of file UnstructuredHeader\&.php\&.
.SS "setValue ( $value)"
Set the (unencoded) value of this header\&.
.PP
\fBParameters:\fP
.RS 4
\fI$value\fP 
.RE
.PP

.PP
Definition at line 91 of file UnstructuredHeader\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
