.TH "Swift_Transport_FailoverTransportTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Transport_FailoverTransportTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwiftMailerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestFirstTransportIsUsed\fP ()"
.br
.ti -1c
.RI "\fBtestMessageCanBeTriedOnNextTransportIfExceptionThrown\fP ()"
.br
.ti -1c
.RI "\fBtestZeroIsReturnedIfTransportReturnsZero\fP ()"
.br
.ti -1c
.RI "\fBtestTransportsWhichThrowExceptionsAreNotRetried\fP ()"
.br
.ti -1c
.RI "\fBtestExceptionIsThrownIfAllTransportsDie\fP ()"
.br
.ti -1c
.RI "\fBtestStoppingTransportStopsAllDelegates\fP ()"
.br
.ti -1c
.RI "\fBtestTransportShowsAsNotStartedIfAllDelegatesDead\fP ()"
.br
.ti -1c
.RI "\fBtestRestartingTransportRestartsDeadDelegates\fP ()"
.br
.ti -1c
.RI "\fBtestFailureReferenceIsPassedToDelegates\fP ()"
.br
.ti -1c
.RI "\fBtestRegisterPluginDelegatesToLoadedTransports\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file FailoverTransportTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testExceptionIsThrownIfAllTransportsDie ()"

.PP
Definition at line 206 of file FailoverTransportTest\&.php\&.
.SS "testFailureReferenceIsPassedToDelegates ()"

.PP
Definition at line 454 of file FailoverTransportTest\&.php\&.
.SS "testFirstTransportIsUsed ()"

.PP
Definition at line 5 of file FailoverTransportTest\&.php\&.
.SS "testMessageCanBeTriedOnNextTransportIfExceptionThrown ()"

.PP
Definition at line 42 of file FailoverTransportTest\&.php\&.
.SS "testRegisterPluginDelegatesToLoadedTransports ()"

.PP
Definition at line 489 of file FailoverTransportTest\&.php\&.
.SS "testRestartingTransportRestartsDeadDelegates ()"

.PP
Definition at line 372 of file FailoverTransportTest\&.php\&.
.SS "testStoppingTransportStopsAllDelegates ()"

.PP
Definition at line 267 of file FailoverTransportTest\&.php\&.
.SS "testTransportShowsAsNotStartedIfAllDelegatesDead ()"

.PP
Definition at line 306 of file FailoverTransportTest\&.php\&.
.SS "testTransportsWhichThrowExceptionsAreNotRetried ()"

.PP
Definition at line 134 of file FailoverTransportTest\&.php\&.
.SS "testZeroIsReturnedIfTransportReturnsZero ()"

.PP
Definition at line 99 of file FailoverTransportTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
