.TH "Swift_CharacterReader_GenericFixedWidthReader" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_CharacterReader_GenericFixedWidthReader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_CharacterReader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($width)"
.br
.ti -1c
.RI "\fBgetCharPositions\fP ($string, $startOffset, &$currentMap, &$ignoredChars)"
.br
.ti -1c
.RI "\fBgetMapType\fP ()"
.br
.ti -1c
.RI "\fBvalidateByteSequence\fP ($bytes, $\fBsize\fP)"
.br
.ti -1c
.RI "\fBgetInitialByteSize\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Provides fixed-width byte sizes for reading fixed-width character sets\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.PP
Xavier De Cock xdecock@gmail.com 
.RE
.PP

.PP
Definition at line 17 of file GenericFixedWidthReader\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $width)"
Creates a new GenericFixedWidthReader using $width bytes per character\&.
.PP
\fBParameters:\fP
.RS 4
\fI$width\fP 
.RE
.PP

.PP
Definition at line 31 of file GenericFixedWidthReader\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getCharPositions ( $string,  $startOffset, & $currentMap, & $ignoredChars)"
Returns the complete character map\&.
.PP
\fBParameters:\fP
.RS 4
\fI$string\fP 
.br
\fI$startOffset\fP 
.br
\fI$currentMap\fP 
.br
\fI$ignoredChars\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBSwift_CharacterReader\fP\&.
.PP
Definition at line 46 of file GenericFixedWidthReader\&.php\&.
.SS "getInitialByteSize ()"
Returns the number of bytes which should be read to start each character\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBSwift_CharacterReader\fP\&.
.PP
Definition at line 93 of file GenericFixedWidthReader\&.php\&.
.SS "getMapType ()"
Returns the mapType\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBSwift_CharacterReader\fP\&.
.PP
Definition at line 62 of file GenericFixedWidthReader\&.php\&.
.SS "validateByteSequence ( $bytes,  $size)"
Returns an integer which specifies how many more bytes to read\&.
.PP
\fBA\fP positive integer indicates the number of more bytes to fetch before invoking this method again\&.
.PP
\fBA\fP value of zero means this is already a valid character\&. \fBA\fP value of -1 means this cannot possibly be a valid character\&.
.PP
\fBParameters:\fP
.RS 4
\fI$bytes\fP 
.br
\fI$size\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBSwift_CharacterReader\fP\&.
.PP
Definition at line 81 of file GenericFixedWidthReader\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
