.TH "Swift_Transport_Esmtp_Auth_CramMd5Authenticator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Transport_Esmtp_Auth_CramMd5Authenticator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Transport_Esmtp_Authenticator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetAuthKeyword\fP ()"
.br
.ti -1c
.RI "\fBauthenticate\fP (\fBSwift_Transport_SmtpAgent\fP $agent, $username, $password)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles CRAM-MD5 authentication\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file CramMd5Authenticator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "authenticate (\fBSwift_Transport_SmtpAgent\fP $agent,  $username,  $password)"
Try to authenticate the user with $username and $password\&.
.PP
\fBParameters:\fP
.RS 4
\fI$agent\fP 
.br
\fI$username\fP 
.br
\fI$password\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBSwift_Transport_Esmtp_Authenticator\fP\&.
.PP
Definition at line 37 of file CramMd5Authenticator\&.php\&.
.SS "getAuthKeyword ()"
Get the name of the AUTH mechanism this Authenticator handles\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBSwift_Transport_Esmtp_Authenticator\fP\&.
.PP
Definition at line 23 of file CramMd5Authenticator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
