.TH "Swift_StreamFilters_StringReplacementFilterFactoryTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_StreamFilters_StringReplacementFilterFactoryTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestInstancesOfStringReplacementFilterAreCreated\fP ()"
.br
.ti -1c
.RI "\fBtestSameInstancesAreCached\fP ()"
.br
.ti -1c
.RI "\fBtestDifferingInstancesAreNotCached\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file StringReplacementFilterFactoryTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testDifferingInstancesAreNotCached ()"

.PP
Definition at line 22 of file StringReplacementFilterFactoryTest\&.php\&.
.SS "testInstancesOfStringReplacementFilterAreCreated ()"

.PP
Definition at line 5 of file StringReplacementFilterFactoryTest\&.php\&.
.SS "testSameInstancesAreCached ()"

.PP
Definition at line 14 of file StringReplacementFilterFactoryTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
