.TH "Swift_MessageAcceptanceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_MessageAcceptanceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Mime_SimpleMessageAcceptanceTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestAddPartWrapper\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_createMessage\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 6 of file MessageAcceptanceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "_createMessage ()\fC [protected]\fP"

.PP
Definition at line 50 of file MessageAcceptanceTest\&.php\&.
.SS "testAddPartWrapper ()"

.PP
Definition at line 8 of file MessageAcceptanceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
