.TH "Swift_Mime_ContentEncoder_QpContentEncoderProxy" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_ContentEncoder_QpContentEncoderProxy \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Mime_ContentEncoder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBSwift_Mime_ContentEncoder_QpContentEncoder\fP $safeEncoder, \fBSwift_Mime_ContentEncoder_NativeQpContentEncoder\fP $nativeEncoder, $charset)"
.br
.ti -1c
.RI "\fB__clone\fP ()"
.br
.ti -1c
.RI "\fBcharsetChanged\fP ($charset)"
.br
.ti -1c
.RI "\fBencodeByteStream\fP (\fBSwift_OutputByteStream\fP $os, \fBSwift_InputByteStream\fP $is, $firstLineOffset=0, $maxLineLength=0)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBencodeString\fP ($string, $firstLineOffset=0, $maxLineLength=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Proxy for quoted-printable content encoders\&.
.PP
Switches on the best QP encoder implementation for current charset\&.
.PP
\fBAuthor:\fP
.RS 4
Jean-François Simon jeanfrancois.simon@sensiolabs.com 
.RE
.PP

.PP
Definition at line 18 of file QpContentEncoderProxy\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBSwift_Mime_ContentEncoder_QpContentEncoder\fP $safeEncoder, \fBSwift_Mime_ContentEncoder_NativeQpContentEncoder\fP $nativeEncoder,  $charset)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$safeEncoder\fP 
.br
\fI$nativeEncoder\fP 
.br
\fI$charset\fP 
.RE
.PP

.PP
Definition at line 42 of file QpContentEncoderProxy\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__clone ()"
Make a deep copy of object 
.PP
Definition at line 52 of file QpContentEncoderProxy\&.php\&.
.SS "charsetChanged ( $charset)"
{Notify this observer that the entity's charset has changed\&.
.PP
\fBParameters:\fP
.RS 4
\fI$charset\fP 
.RE
.PP
} 
.PP
Implements \fBSwift_Mime_CharsetObserver\fP\&.
.PP
Definition at line 61 of file QpContentEncoderProxy\&.php\&.
.SS "encodeByteStream (\fBSwift_OutputByteStream\fP $os, \fBSwift_InputByteStream\fP $is,  $firstLineOffset = \fC0\fP,  $maxLineLength = \fC0\fP)"
{Encode $in to $out\&.
.PP
\fBParameters:\fP
.RS 4
\fI$os\fP to read from 
.br
\fI$is\fP to write to 
.br
\fI$firstLineOffset\fP 
.br
\fI$maxLineLength\fP - 0 indicates the default length for this encoding
.RE
.PP
} 
.PP
Implements \fBSwift_Mime_ContentEncoder\fP\&.
.PP
Definition at line 69 of file QpContentEncoderProxy\&.php\&.
.SS "encodeString ( $string,  $firstLineOffset = \fC0\fP,  $maxLineLength = \fC0\fP)"
{Encode a given string to produce an encoded string\&.
.PP
\fBParameters:\fP
.RS 4
\fI$string\fP 
.br
\fI$firstLineOffset\fP if first line needs to be shorter 
.br
\fI$maxLineLength\fP - 0 indicates the default length for this encoding
.RE
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP
} 
.PP
Implements \fBSwift_Encoder\fP\&.
.PP
Definition at line 85 of file QpContentEncoderProxy\&.php\&.
.SS "getName ()"
{Get the MIME name of this content encoding scheme\&.
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP
} 
.PP
Implements \fBSwift_Mime_ContentEncoder\fP\&.
.PP
Definition at line 77 of file QpContentEncoderProxy\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
