.TH "Swift_Mime_MimePartAcceptanceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_MimePartAcceptanceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.PP
Inherited by \fBSwift_MimePartAcceptanceTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestCharsetIsSetInHeader\fP ()"
.br
.ti -1c
.RI "\fBtestFormatIsSetInHeaders\fP ()"
.br
.ti -1c
.RI "\fBtestDelSpIsSetInHeaders\fP ()"
.br
.ti -1c
.RI "\fBtestAll3ParamsInHeaders\fP ()"
.br
.ti -1c
.RI "\fBtestBodyIsCanonicalized\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_createMimePart\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file MimePartAcceptanceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "_createMimePart ()\fC [protected]\fP"

.PP
Definition at line 118 of file MimePartAcceptanceTest\&.php\&.
.SS "setUp ()"

.PP
Definition at line 10 of file MimePartAcceptanceTest\&.php\&.
.SS "testAll3ParamsInHeaders ()"

.PP
Definition at line 81 of file MimePartAcceptanceTest\&.php\&.
.SS "testBodyIsCanonicalized ()"

.PP
Definition at line 98 of file MimePartAcceptanceTest\&.php\&.
.SS "testCharsetIsSetInHeader ()"

.PP
Definition at line 36 of file MimePartAcceptanceTest\&.php\&.
.SS "testDelSpIsSetInHeaders ()"

.PP
Definition at line 66 of file MimePartAcceptanceTest\&.php\&.
.SS "testFormatIsSetInHeaders ()"

.PP
Definition at line 51 of file MimePartAcceptanceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
