.TH "Swift_Plugins_Pop_Pop3Connection" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Plugins_Pop_Pop3Connection \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSwift_Plugins_PopBeforeSmtpPlugin\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconnect\fP ()"
.br
.ti -1c
.RI "\fBdisconnect\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Pop3Connection interface for connecting and disconnecting to a POP3 host\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file Pop3Connection\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "connect ()"
Connect to the POP3 host and throw an Exception if it fails\&.
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSwift_Plugins_Pop_Pop3Exception\fP\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Plugins_PopBeforeSmtpPlugin\fP\&.
.SS "disconnect ()"
Disconnect from the POP3 host and throw an Exception if it fails\&.
.PP
\fBExceptions:\fP
.RS 4
\fI\fBSwift_Plugins_Pop_Pop3Exception\fP\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Plugins_PopBeforeSmtpPlugin\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
