.TH "Swift_Mime_HeaderEncoder_Base64HeaderEncoderAcceptanceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_HeaderEncoder_Base64HeaderEncoderAcceptanceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingJIS\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file Base64HeaderEncoderAcceptanceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()"

.PP
Definition at line 7 of file Base64HeaderEncoderAcceptanceTest\&.php\&.
.SS "testEncodingJIS ()"

.PP
Definition at line 12 of file Base64HeaderEncoderAcceptanceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
