.TH "Swift_KeyCache_DiskKeyCacheAcceptanceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_KeyCache_DiskKeyCacheAcceptanceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestStringDataCanBeSetAndFetched\fP ()"
.br
.ti -1c
.RI "\fBtestStringDataCanBeOverwritten\fP ()"
.br
.ti -1c
.RI "\fBtestStringDataCanBeAppended\fP ()"
.br
.ti -1c
.RI "\fBtestHasKeyReturnValue\fP ()"
.br
.ti -1c
.RI "\fBtestNsKeyIsWellPartitioned\fP ()"
.br
.ti -1c
.RI "\fBtestItemKeyIsWellPartitioned\fP ()"
.br
.ti -1c
.RI "\fBtestByteStreamCanBeImported\fP ()"
.br
.ti -1c
.RI "\fBtestByteStreamCanBeAppended\fP ()"
.br
.ti -1c
.RI "\fBtestByteStreamAndStringCanBeAppended\fP ()"
.br
.ti -1c
.RI "\fBtestDataCanBeExportedToByteStream\fP ()"
.br
.ti -1c
.RI "\fBtestKeyCanBeCleared\fP ()"
.br
.ti -1c
.RI "\fBtestNsKeyCanBeCleared\fP ()"
.br
.ti -1c
.RI "\fBtestKeyCacheInputStream\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()"

.PP
Definition at line 9 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testByteStreamAndStringCanBeAppended ()"

.PP
Definition at line 118 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testByteStreamCanBeAppended ()"

.PP
Definition at line 100 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testByteStreamCanBeImported ()"

.PP
Definition at line 89 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testDataCanBeExportedToByteStream ()"

.PP
Definition at line 133 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testHasKeyReturnValue ()"

.PP
Definition at line 56 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testItemKeyIsWellPartitioned ()"

.PP
Definition at line 77 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testKeyCacheInputStream ()"

.PP
Definition at line 176 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testKeyCanBeCleared ()"

.PP
Definition at line 151 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testNsKeyCanBeCleared ()"

.PP
Definition at line 161 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testNsKeyIsWellPartitioned ()"

.PP
Definition at line 65 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testStringDataCanBeAppended ()"

.PP
Definition at line 45 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testStringDataCanBeOverwritten ()"

.PP
Definition at line 34 of file DiskKeyCacheAcceptanceTest\&.php\&.
.SS "testStringDataCanBeSetAndFetched ()"

.PP
Definition at line 26 of file DiskKeyCacheAcceptanceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
