.TH "Swift_Plugins_Loggers_EchoLoggerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Plugins_Loggers_EchoLoggerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestAddingEntryDumpsSingleLineWithoutHtml\fP ()"
.br
.ti -1c
.RI "\fBtestAddingEntryDumpsEscapedLineWithHtml\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file EchoLoggerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAddingEntryDumpsEscapedLineWithHtml ()"

.PP
Definition at line 15 of file EchoLoggerTest\&.php\&.
.SS "testAddingEntryDumpsSingleLineWithoutHtml ()"

.PP
Definition at line 5 of file EchoLoggerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
