.TH "Swift_Plugins_BandwidthMonitorPluginTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Plugins_BandwidthMonitorPluginTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtestBytesOutIncreasesWhenCommandsSent\fP ()"
.br
.ti -1c
.RI "\fBtestBytesInIncreasesWhenResponsesReceived\fP ()"
.br
.ti -1c
.RI "\fBtestCountersCanBeReset\fP ()"
.br
.ti -1c
.RI "\fBtestBytesOutIncreasesAccordingToMessageLength\fP ()"
.br
.ti -1c
.RI "\fB_write\fP ($is)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file BandwidthMonitorPluginTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "_write ( $is)"

.PP
Definition at line 121 of file BandwidthMonitorPluginTest\&.php\&.
.SS "setUp ()"

.PP
Definition at line 5 of file BandwidthMonitorPluginTest\&.php\&.
.SS "testBytesInIncreasesWhenResponsesReceived ()"

.PP
Definition at line 21 of file BandwidthMonitorPluginTest\&.php\&.
.SS "testBytesOutIncreasesAccordingToMessageLength ()"

.PP
Definition at line 56 of file BandwidthMonitorPluginTest\&.php\&.
.SS "testBytesOutIncreasesWhenCommandsSent ()"

.PP
Definition at line 10 of file BandwidthMonitorPluginTest\&.php\&.
.SS "testCountersCanBeReset ()"

.PP
Definition at line 32 of file BandwidthMonitorPluginTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
