.TH "Swift_StreamFilters_ByteArrayReplacementFilterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_StreamFilters_ByteArrayReplacementFilterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestBasicReplacementsAreMade\fP ()"
.br
.ti -1c
.RI "\fBtestShouldBufferReturnsTrueIfPartialMatchAtEndOfBuffer\fP ()"
.br
.ti -1c
.RI "\fBtestFilterCanMakeMultipleReplacements\fP ()"
.br
.ti -1c
.RI "\fBtestMultipleReplacementsCanBeDifferent\fP ()"
.br
.ti -1c
.RI "\fBtestShouldBufferReturnsFalseIfPartialMatchNotAtEndOfString\fP ()"
.br
.ti -1c
.RI "\fBtestShouldBufferReturnsTrueIfAnyOfMultipleMatchesAtEndOfString\fP ()"
.br
.ti -1c
.RI "\fBtestConvertingAllLineEndingsToCRLFWhenInputIsLF\fP ()"
.br
.ti -1c
.RI "\fBtestConvertingAllLineEndingsToCRLFWhenInputIsCR\fP ()"
.br
.ti -1c
.RI "\fBtestConvertingAllLineEndingsToCRLFWhenInputIsCRLF\fP ()"
.br
.ti -1c
.RI "\fBtestConvertingAllLineEndingsToCRLFWhenInputIsLFCR\fP ()"
.br
.ti -1c
.RI "\fBtestConvertingAllLineEndingsToCRLFWhenInputContainsLFLF\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file ByteArrayReplacementFilterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testBasicReplacementsAreMade ()"

.PP
Definition at line 5 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testConvertingAllLineEndingsToCRLFWhenInputContainsLFLF ()"

.PP
Definition at line 110 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testConvertingAllLineEndingsToCRLFWhenInputIsCR ()"

.PP
Definition at line 71 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testConvertingAllLineEndingsToCRLFWhenInputIsCRLF ()"

.PP
Definition at line 84 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testConvertingAllLineEndingsToCRLFWhenInputIsLF ()"

.PP
Definition at line 58 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testConvertingAllLineEndingsToCRLFWhenInputIsLFCR ()"

.PP
Definition at line 97 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testFilterCanMakeMultipleReplacements ()"

.PP
Definition at line 23 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testMultipleReplacementsCanBeDifferent ()"

.PP
Definition at line 32 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testShouldBufferReturnsFalseIfPartialMatchNotAtEndOfString ()"

.PP
Definition at line 41 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testShouldBufferReturnsTrueIfAnyOfMultipleMatchesAtEndOfString ()"

.PP
Definition at line 49 of file ByteArrayReplacementFilterTest\&.php\&.
.SS "testShouldBufferReturnsTrueIfPartialMatchAtEndOfBuffer ()"

.PP
Definition at line 14 of file ByteArrayReplacementFilterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
