.TH "vendor/swiftmailer/swiftmailer/lib/swift_required_pear.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/swiftmailer/swiftmailer/lib/swift_required_pear.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP (class_exists('\fBSwift\fP', false))"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP(class_exists('\fBSwift\fP', false))"

.PP
Definition at line 15 of file swift_required_pear\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
