.TH "Swift_StreamFilters_StringReplacementFilter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_StreamFilters_StringReplacementFilter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_StreamFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($search, $replace)"
.br
.ti -1c
.RI "\fBshouldBuffer\fP ($buffer)"
.br
.ti -1c
.RI "\fBfilter\fP ($buffer)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Processes bytes as they pass through a buffer and replaces sequences in it\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file StringReplacementFilter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $search,  $replace)"
Create a new StringReplacementFilter with $search and $replace\&.
.PP
\fBParameters:\fP
.RS 4
\fI$search\fP 
.br
\fI$replace\fP 
.RE
.PP

.PP
Definition at line 30 of file StringReplacementFilter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "filter ( $buffer)"
Perform the actual replacements on $buffer and return the result\&.
.PP
\fBParameters:\fP
.RS 4
\fI$buffer\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBSwift_StreamFilter\fP\&.
.PP
Definition at line 62 of file StringReplacementFilter\&.php\&.
.SS "shouldBuffer ( $buffer)"
Returns true if based on the buffer passed more bytes should be buffered\&.
.PP
\fBParameters:\fP
.RS 4
\fI$buffer\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBSwift_StreamFilter\fP\&.
.PP
Definition at line 43 of file StringReplacementFilter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
