.TH "Swift_Encoder_Rfc2231Encoder" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Encoder_Rfc2231Encoder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Encoder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBSwift_CharacterStream\fP $charStream)"
.br
.ti -1c
.RI "\fBencodeString\fP ($string, $firstLineOffset=0, $maxLineLength=0)"
.br
.ti -1c
.RI "\fBcharsetChanged\fP ($charset)"
.br
.ti -1c
.RI "\fB__clone\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles RFC 2231 specified Encoding in \fBSwift\fP Mailer\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file Rfc2231Encoder\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBSwift_CharacterStream\fP $charStream)"
Creates a new Rfc2231Encoder using the given character stream instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI\fBSwift_CharacterStream\fP\fP 
.RE
.PP

.PP
Definition at line 30 of file Rfc2231Encoder\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__clone ()"
Make a deep copy of object 
.PP
Definition at line 88 of file Rfc2231Encoder\&.php\&.
.SS "charsetChanged ( $charset)"
Updates the charset used\&.
.PP
\fBParameters:\fP
.RS 4
\fI$charset\fP 
.RE
.PP

.PP
Implements \fBSwift_Mime_CharsetObserver\fP\&.
.PP
Definition at line 80 of file Rfc2231Encoder\&.php\&.
.SS "encodeString ( $string,  $firstLineOffset = \fC0\fP,  $maxLineLength = \fC0\fP)"
Takes an unencoded string and produces a string encoded according to RFC 2231 from it\&.
.PP
\fBParameters:\fP
.RS 4
\fI$string\fP 
.br
\fI$firstLineOffset\fP 
.br
\fI$maxLineLength\fP optional, 0 indicates the default of 75 bytes
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implements \fBSwift_Encoder\fP\&.
.PP
Definition at line 45 of file Rfc2231Encoder\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
