.TH "Swift_Plugins_DecoratorPluginTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Plugins_DecoratorPluginTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwiftMailerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestMessageBodyReceivesReplacements\fP ()"
.br
.ti -1c
.RI "\fBtestReplacementsCanBeAppliedToSameMessageMultipleTimes\fP ()"
.br
.ti -1c
.RI "\fBtestReplacementsCanBeMadeInHeaders\fP ()"
.br
.ti -1c
.RI "\fBtestReplacementsAreMadeOnSubparts\fP ()"
.br
.ti -1c
.RI "\fBtestReplacementsCanBeTakenFromCustomReplacementsObject\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file DecoratorPluginTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testMessageBodyReceivesReplacements ()"

.PP
Definition at line 5 of file DecoratorPluginTest\&.php\&.
.SS "testReplacementsAreMadeOnSubparts ()"

.PP
Definition at line 106 of file DecoratorPluginTest\&.php\&.
.SS "testReplacementsCanBeAppliedToSameMessageMultipleTimes ()"

.PP
Definition at line 30 of file DecoratorPluginTest\&.php\&.
.SS "testReplacementsCanBeMadeInHeaders ()"

.PP
Definition at line 66 of file DecoratorPluginTest\&.php\&.
.SS "testReplacementsCanBeTakenFromCustomReplacementsObject ()"

.PP
Definition at line 141 of file DecoratorPluginTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
