.TH "Swift_Transport_EsmtpHandlerMixin" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Transport_EsmtpHandlerMixin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Transport_EsmtpHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUsername\fP ($user)"
.br
.ti -1c
.RI "\fBsetPassword\fP ($pass)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ExtensionSupportTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setPassword ( $pass)"

.SS "setUsername ( $user)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
