.TH "Swift_Events_CommandEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Events_CommandEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Events_EventObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBSwift_Transport\fP $source, $command, $successCodes=array())"
.br
.ti -1c
.RI "\fBgetCommand\fP ()"
.br
.ti -1c
.RI "\fBgetSuccessCodes\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generated when a command is sent over an SMTP connection\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file CommandEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBSwift_Transport\fP $source,  $command,  $successCodes = \fCarray()\fP)"
Create a new CommandEvent for $source with $command\&.
.PP
\fBParameters:\fP
.RS 4
\fI$source\fP 
.br
\fI$command\fP 
.br
\fI$successCodes\fP 
.RE
.PP

.PP
Definition at line 39 of file CommandEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getCommand ()"
Get the command which was sent to the server\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 51 of file CommandEvent\&.php\&.
.SS "getSuccessCodes ()"
Get the numeric response codes which indicate success for this command\&.
.PP
\fBReturns:\fP
.RS 4
integer[] 
.RE
.PP

.PP
Definition at line 61 of file CommandEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
