.TH "Swift_Plugins_Logger" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Plugins_Logger \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSwift_Plugins_LoggerPlugin\fP, \fBSwift_Plugins_Loggers_ArrayLogger\fP, and \fBSwift_Plugins_Loggers_EchoLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBadd\fP ($entry)"
.br
.ti -1c
.RI "\fBclear\fP ()"
.br
.ti -1c
.RI "\fBdump\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logs events in the Transport system\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file Logger\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "add ( $entry)"
Add a log entry\&.
.PP
\fBParameters:\fP
.RS 4
\fI$entry\fP 
.RE
.PP

.PP
Implemented in \fBSwift_Plugins_Loggers_ArrayLogger\fP, \fBSwift_Plugins_LoggerPlugin\fP, and \fBSwift_Plugins_Loggers_EchoLogger\fP\&.
.SS "clear ()"
Clear the log contents\&. 
.PP
Implemented in \fBSwift_Plugins_Loggers_ArrayLogger\fP, \fBSwift_Plugins_Loggers_EchoLogger\fP, and \fBSwift_Plugins_LoggerPlugin\fP\&.
.SS "dump ()"
Get this log as a string\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBSwift_Plugins_Loggers_ArrayLogger\fP, \fBSwift_Plugins_Loggers_EchoLogger\fP, and \fBSwift_Plugins_LoggerPlugin\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
