.TH "Swift_Encoder_Rfc2231EncoderTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Encoder_Rfc2231EncoderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwiftMailerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestEncodingAsciiCharactersProducesValidToken\fP ()"
.br
.ti -1c
.RI "\fBtestEncodingNonAsciiCharactersProducesValidToken\fP ()"
.br
.ti -1c
.RI "\fBtestMaximumLineLengthCanBeSet\fP ()"
.br
.ti -1c
.RI "\fBtestFirstLineCanHaveShorterLength\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file Rfc2231EncoderTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testEncodingAsciiCharactersProducesValidToken ()"

.PP
Definition at line 16 of file Rfc2231EncoderTest\&.php\&.
.SS "testEncodingNonAsciiCharactersProducesValidToken ()"

.PP
Definition at line 47 of file Rfc2231EncoderTest\&.php\&.
.SS "testFirstLineCanHaveShorterLength ()"

.PP
Definition at line 110 of file Rfc2231EncoderTest\&.php\&.
.SS "testMaximumLineLengthCanBeSet ()"

.PP
Definition at line 77 of file Rfc2231EncoderTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
