.TH "Swift_ReplacementFilterFactory" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_ReplacementFilterFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSwift_StreamFilters_StringReplacementFilterFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateFilter\fP ($search, $replace)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Creates StreamFilters\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file ReplacementFilterFactory\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createFilter ( $search,  $replace)"
Create a filter to replace $search with $replace\&.
.PP
\fBParameters:\fP
.RS 4
\fI$search\fP 
.br
\fI$replace\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSwift_StreamFilter\fP 
.RE
.PP

.PP
Implemented in \fBSwift_StreamFilters_StringReplacementFilterFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
