.TH "Swift_Signer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Signer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSwift_Signers_BodySigner\fP, and \fBSwift_Signers_HeaderSigner\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreset\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base Class of Signer Infrastructure\&.
.PP
\fBAuthor:\fP
.RS 4
Xavier De Cock xdecock@gmail.com 
.RE
.PP

.PP
Definition at line 17 of file Signer\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "reset ()"

.PP
Implemented in \fBSwift_Signers_DKIMSigner\fP, \fBSwift_Signers_SMimeSigner\fP, \fBSwift_Signers_DomainKeySigner\fP, and \fBSwift_Signers_OpenDKIMSigner\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
