.TH "Swift_Plugins_ImpersonatePlugin" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Plugins_ImpersonatePlugin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Events_SendListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($sender)"
.br
.ti -1c
.RI "\fBbeforeSendPerformed\fP (\fBSwift_Events_SendEvent\fP $evt)"
.br
.ti -1c
.RI "\fBsendPerformed\fP (\fBSwift_Events_SendEvent\fP $evt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Replaces the sender of a message\&.
.PP
\fBAuthor:\fP
.RS 4
Arjen Brouwer 
.RE
.PP

.PP
Definition at line 15 of file ImpersonatePlugin\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $sender)"
Create a new ImpersonatePlugin to impersonate $sender\&.
.PP
\fBParameters:\fP
.RS 4
\fI$sender\fP address 
.RE
.PP

.PP
Definition at line 29 of file ImpersonatePlugin\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "beforeSendPerformed (\fBSwift_Events_SendEvent\fP $evt)"
Invoked immediately before the Message is sent\&.
.PP
\fBParameters:\fP
.RS 4
\fI$evt\fP 
.RE
.PP

.PP
Implements \fBSwift_Events_SendListener\fP\&.
.PP
Definition at line 39 of file ImpersonatePlugin\&.php\&.
.SS "sendPerformed (\fBSwift_Events_SendEvent\fP $evt)"
Invoked immediately after the Message is sent\&.
.PP
\fBParameters:\fP
.RS 4
\fI$evt\fP 
.RE
.PP

.PP
Implements \fBSwift_Events_SendListener\fP\&.
.PP
Definition at line 56 of file ImpersonatePlugin\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
