.TH "Swift_ByteStream_FileByteStreamAcceptanceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_ByteStream_FileByteStreamAcceptanceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.ti -1c
.RI "\fBtestFileDataCanBeRead\fP ()"
.br
.ti -1c
.RI "\fBtestFileDataCanBeReadSequentially\fP ()"
.br
.ti -1c
.RI "\fBtestFilenameIsReturned\fP ()"
.br
.ti -1c
.RI "\fBtestFileCanBeWrittenTo\fP ()"
.br
.ti -1c
.RI "\fBtestReadingFromThenWritingToFile\fP ()"
.br
.ti -1c
.RI "\fBtestWritingToFileWithCanonicalization\fP ()"
.br
.ti -1c
.RI "\fBtestBindingOtherStreamsMirrorsWriteOperations\fP ()"
.br
.ti -1c
.RI "\fBtestBindingOtherStreamsMirrorsFlushOperations\fP ()"
.br
.ti -1c
.RI "\fBtestUnbindingStreamPreventsFurtherWrites\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file FileByteStreamAcceptanceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()"

.PP
Definition at line 8 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "tearDown ()"

.PP
Definition at line 22 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testBindingOtherStreamsMirrorsFlushOperations ()"

.PP
Definition at line 111 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testBindingOtherStreamsMirrorsWriteOperations ()"

.PP
Definition at line 83 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testFileCanBeWrittenTo ()"

.PP
Definition at line 51 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testFileDataCanBeRead ()"

.PP
Definition at line 27 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testFileDataCanBeReadSequentially ()"

.PP
Definition at line 37 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testFilenameIsReturned ()"

.PP
Definition at line 45 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testReadingFromThenWritingToFile ()"

.PP
Definition at line 60 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testUnbindingStreamPreventsFurtherWrites ()"

.PP
Definition at line 130 of file FileByteStreamAcceptanceTest\&.php\&.
.SS "testWritingToFileWithCanonicalization ()"

.PP
Definition at line 71 of file FileByteStreamAcceptanceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
