.TH "Swift_Preferences" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Preferences \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetCharset\fP ($charset)"
.br
.ti -1c
.RI "\fBsetTempDir\fP ($dir)"
.br
.ti -1c
.RI "\fBsetCacheType\fP ($type)"
.br
.ti -1c
.RI "\fBsetQPDotEscape\fP ($dotEscape)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetInstance\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Changes some global preference settings in \fBSwift\fP Mailer\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file Preferences\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getInstance ()\fC [static]\fP"
Gets the instance of Preferences\&.
.PP
\fBReturns:\fP
.RS 4
\fBSwift_Preferences\fP 
.RE
.PP

.PP
Definition at line 31 of file Preferences\&.php\&.
.SS "setCacheType ( $type)"
Set the type of cache to use (i\&.e\&. 'disk' or 'array')\&.
.PP
\fBParameters:\fP
.RS 4
\fI$type\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSwift_Preferences\fP 
.RE
.PP

.PP
Definition at line 77 of file Preferences\&.php\&.
.SS "setCharset ( $charset)"
Set the default charset used\&.
.PP
\fBParameters:\fP
.RS 4
\fI$charset\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSwift_Preferences\fP 
.RE
.PP

.PP
Definition at line 47 of file Preferences\&.php\&.
.SS "setQPDotEscape ( $dotEscape)"
Set the QuotedPrintable dot escaper preference\&.
.PP
\fBParameters:\fP
.RS 4
\fI$dotEscape\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSwift_Preferences\fP 
.RE
.PP

.PP
Definition at line 92 of file Preferences\&.php\&.
.SS "setTempDir ( $dir)"
Set the directory where temporary files can be saved\&.
.PP
\fBParameters:\fP
.RS 4
\fI$dir\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSwift_Preferences\fP 
.RE
.PP

.PP
Definition at line 62 of file Preferences\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
