.TH "Swift_Mime_ContentEncoder_QpContentEncoderTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_ContentEncoder_QpContentEncoderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwiftMailerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestNameIsQuotedPrintable\fP ()"
.br
.ti -1c
.RI "\fBtestPermittedCharactersAreNotEncoded\fP ()"
.br
.ti -1c
.RI "\fBtestLinearWhiteSpaceAtLineEndingIsEncoded\fP ()"
.br
.ti -1c
.RI "\fBtestCRLFIsLeftAlone\fP ()"
.br
.ti -1c
.RI "\fBtestLinesLongerThan76CharactersAreSoftBroken\fP ()"
.br
.ti -1c
.RI "\fBtestMaxLineLengthCanBeSpecified\fP ()"
.br
.ti -1c
.RI "\fBtestBytesBelowPermittedRangeAreEncoded\fP ()"
.br
.ti -1c
.RI "\fBtestDecimalByte61IsEncoded\fP ()"
.br
.ti -1c
.RI "\fBtestBytesAbovePermittedRangeAreEncoded\fP ()"
.br
.ti -1c
.RI "\fBtestFirstLineLengthCanBeDifferent\fP ()"
.br
.ti -1c
.RI "\fBtestObserverInterfaceCanChangeCharset\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file QpContentEncoderTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testBytesAbovePermittedRangeAreEncoded ()"

.PP
Definition at line 396 of file QpContentEncoderTest\&.php\&.
.SS "testBytesBelowPermittedRangeAreEncoded ()"

.PP
Definition at line 328 of file QpContentEncoderTest\&.php\&.
.SS "testCRLFIsLeftAlone ()"

.PP
Definition at line 180 of file QpContentEncoderTest\&.php\&.
.SS "testDecimalByte61IsEncoded ()"

.PP
Definition at line 363 of file QpContentEncoderTest\&.php\&.
.SS "testFirstLineLengthCanBeDifferent ()"

.PP
Definition at line 431 of file QpContentEncoderTest\&.php\&.
.SS "testLinearWhiteSpaceAtLineEndingIsEncoded ()"

.PP
Definition at line 69 of file QpContentEncoderTest\&.php\&.
.SS "testLinesLongerThan76CharactersAreSoftBroken ()"

.PP
Definition at line 258 of file QpContentEncoderTest\&.php\&.
.SS "testMaxLineLengthCanBeSpecified ()"

.PP
Definition at line 298 of file QpContentEncoderTest\&.php\&.
.SS "testNameIsQuotedPrintable ()"

.PP
Definition at line 5 of file QpContentEncoderTest\&.php\&.
.SS "testObserverInterfaceCanChangeCharset ()"

.PP
Definition at line 464 of file QpContentEncoderTest\&.php\&.
.SS "testPermittedCharactersAreNotEncoded ()"

.PP
Definition at line 29 of file QpContentEncoderTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
