.TH "Swift_Events_TransportExceptionEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Events_TransportExceptionEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Events_EventObject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBSwift_Transport\fP $transport, \fBSwift_TransportException\fP $ex)"
.br
.ti -1c
.RI "\fBgetException\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generated when a TransportException is thrown from the Transport system\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file TransportExceptionEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBSwift_Transport\fP $transport, \fBSwift_TransportException\fP $ex)"
Create a new TransportExceptionEvent for $transport\&.
.PP
\fBParameters:\fP
.RS 4
\fI$transport\fP 
.br
\fI$ex\fP 
.RE
.PP

.PP
Definition at line 31 of file TransportExceptionEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getException ()"
Get the TransportException thrown\&.
.PP
\fBReturns:\fP
.RS 4
\fBSwift_TransportException\fP 
.RE
.PP

.PP
Definition at line 42 of file TransportExceptionEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
