.TH "Swift_Transport_StreamBuffer_TlsSocketAcceptanceTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Transport_StreamBuffer_TlsSocketAcceptanceTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Transport_StreamBuffer_AbstractStreamBufferAcceptanceTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fB_initializeBuffer\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 5 of file TlsSocketAcceptanceTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "_initializeBuffer ()\fC [protected]\fP"

.PP
Definition at line 25 of file TlsSocketAcceptanceTest\&.php\&.
.SS "setUp ()"

.PP
Definition at line 8 of file TlsSocketAcceptanceTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
