.TH "Swift_Plugins_ReporterPlugin" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Plugins_ReporterPlugin \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Events_SendListener\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBSwift_Plugins_Reporter\fP $reporter)"
.br
.ti -1c
.RI "\fBbeforeSendPerformed\fP (\fBSwift_Events_SendEvent\fP $evt)"
.br
.ti -1c
.RI "\fBsendPerformed\fP (\fBSwift_Events_SendEvent\fP $evt)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Does real time reporting of pass/fail for each recipient\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file ReporterPlugin\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBSwift_Plugins_Reporter\fP $reporter)"
Create a new ReporterPlugin using $reporter\&.
.PP
\fBParameters:\fP
.RS 4
\fI$reporter\fP 
.RE
.PP

.PP
Definition at line 30 of file ReporterPlugin\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "beforeSendPerformed (\fBSwift_Events_SendEvent\fP $evt)"
Not used\&. 
.PP
Implements \fBSwift_Events_SendListener\fP\&.
.PP
Definition at line 38 of file ReporterPlugin\&.php\&.
.SS "sendPerformed (\fBSwift_Events_SendEvent\fP $evt)"
Invoked immediately after the Message is sent\&.
.PP
\fBParameters:\fP
.RS 4
\fI$evt\fP 
.RE
.PP

.PP
Implements \fBSwift_Events_SendListener\fP\&.
.PP
Definition at line 47 of file ReporterPlugin\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
