.TH "Swift_Transport_MailTransportTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Transport_MailTransportTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwiftMailerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestTransportInvokesMailOncePerMessage\fP ()"
.br
.ti -1c
.RI "\fBtestTransportUsesToFieldBodyInSending\fP ()"
.br
.ti -1c
.RI "\fBtestTransportUsesSubjectFieldBodyInSending\fP ()"
.br
.ti -1c
.RI "\fBtestTransportUsesBodyOfMessage\fP ()"
.br
.ti -1c
.RI "\fBtestTransportUsesHeadersFromMessage\fP ()"
.br
.ti -1c
.RI "\fBtestTransportReturnsCountOfAllRecipientsIfInvokerReturnsTrue\fP ()"
.br
.ti -1c
.RI "\fBtestTransportReturnsZeroIfInvokerReturnsFalse\fP ()"
.br
.ti -1c
.RI "\fBtestToHeaderIsRemovedFromHeaderSetDuringSending\fP ()"
.br
.ti -1c
.RI "\fBtestSubjectHeaderIsRemovedFromHeaderSetDuringSending\fP ()"
.br
.ti -1c
.RI "\fBtestToHeaderIsPutBackAfterSending\fP ()"
.br
.ti -1c
.RI "\fBtestSubjectHeaderIsPutBackAfterSending\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file MailTransportTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testSubjectHeaderIsPutBackAfterSending ()"

.PP
Definition at line 228 of file MailTransportTest\&.php\&.
.SS "testSubjectHeaderIsRemovedFromHeaderSetDuringSending ()"

.PP
Definition at line 180 of file MailTransportTest\&.php\&.
.SS "testToHeaderIsPutBackAfterSending ()"

.PP
Definition at line 204 of file MailTransportTest\&.php\&.
.SS "testToHeaderIsRemovedFromHeaderSetDuringSending ()"

.PP
Definition at line 156 of file MailTransportTest\&.php\&.
.SS "testTransportInvokesMailOncePerMessage ()"

.PP
Definition at line 5 of file MailTransportTest\&.php\&.
.SS "testTransportReturnsCountOfAllRecipientsIfInvokerReturnsTrue ()"

.PP
Definition at line 110 of file MailTransportTest\&.php\&.
.SS "testTransportReturnsZeroIfInvokerReturnsFalse ()"

.PP
Definition at line 133 of file MailTransportTest\&.php\&.
.SS "testTransportUsesBodyOfMessage ()"

.PP
Definition at line 64 of file MailTransportTest\&.php\&.
.SS "testTransportUsesHeadersFromMessage ()"

.PP
Definition at line 87 of file MailTransportTest\&.php\&.
.SS "testTransportUsesSubjectFieldBodyInSending ()"

.PP
Definition at line 42 of file MailTransportTest\&.php\&.
.SS "testTransportUsesToFieldBodyInSending ()"

.PP
Definition at line 20 of file MailTransportTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
