.TH "Swift_Filterable" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Filterable \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBSwift_ByteStream_AbstractFilterableInputStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaddFilter\fP (\fBSwift_StreamFilter\fP $\fBfilter\fP, $key)"
.br
.ti -1c
.RI "\fBremoveFilter\fP ($key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows StreamFilters to operate on a stream\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file Filterable\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addFilter (\fBSwift_StreamFilter\fP $filter,  $key)"
Add a new StreamFilter, referenced by $key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$filter\fP 
.br
\fI$key\fP 
.RE
.PP

.PP
Implemented in \fBSwift_ByteStream_AbstractFilterableInputStream\fP\&.
.SS "removeFilter ( $key)"
Remove an existing filter using $key\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP 
.RE
.PP

.PP
Implemented in \fBSwift_ByteStream_AbstractFilterableInputStream\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
