.TH "Swift_SendmailTransport" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_SendmailTransport \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwift_Transport_SendmailTransport\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($command= '/usr/sbin/sendmail-bs')"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBnewInstance\fP ($command= '/usr/sbin/sendmail-bs')"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
SendmailTransport for sending mail through a Sendmail/Postfix (etc\&.\&.) binary\&.
.PP
\fBAuthor:\fP
.RS 4
Chris Corbyn 
.RE
.PP

.PP
Definition at line 16 of file SendmailTransport\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $command = \fC'/usr/sbin/sendmail -bs'\fP)"
Create a new SendmailTransport, optionally using $command for sending\&.
.PP
\fBParameters:\fP
.RS 4
\fI$command\fP 
.RE
.PP

.PP
Definition at line 23 of file SendmailTransport\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static newInstance ( $command = \fC'/usr/sbin/sendmail -bs'\fP)\fC [static]\fP"
Create a new SendmailTransport instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$command\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBSwift_SendmailTransport\fP 
.RE
.PP

.PP
Definition at line 41 of file SendmailTransport\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
