.TH "Swift_Mime_HeaderEncoder_QpHeaderEncoderTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Swift_Mime_HeaderEncoder_QpHeaderEncoderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSwiftMailerTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestNameIsQ\fP ()"
.br
.ti -1c
.RI "\fBtestSpaceAndTabNeverAppear\fP ()"
.br
.ti -1c
.RI "\fBtestSpaceIsRepresentedByUnderscore\fP ()"
.br
.ti -1c
.RI "\fBtestEqualsAndQuestionAndUnderscoreAreEncoded\fP ()"
.br
.ti -1c
.RI "\fBtestParensAndQuotesAreEncoded\fP ()"
.br
.ti -1c
.RI "\fBtestOnlyCharactersAllowedInPhrasesAreUsed\fP ()"
.br
.ti -1c
.RI "\fBtestEqualsNeverAppearsAtEndOfLine\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file QpHeaderEncoderTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testEqualsAndQuestionAndUnderscoreAreEncoded ()"

.PP
Definition at line 66 of file QpHeaderEncoderTest\&.php\&.
.SS "testEqualsNeverAppearsAtEndOfLine ()"

.PP
Definition at line 176 of file QpHeaderEncoderTest\&.php\&.
.SS "testNameIsQ ()"

.PP
Definition at line 8 of file QpHeaderEncoderTest\&.php\&.
.SS "testOnlyCharactersAllowedInPhrasesAreUsed ()"

.PP
Definition at line 122 of file QpHeaderEncoderTest\&.php\&.
.SS "testParensAndQuotesAreEncoded ()"

.PP
Definition at line 95 of file QpHeaderEncoderTest\&.php\&.
.SS "testSpaceAndTabNeverAppear ()"

.PP
Definition at line 16 of file QpHeaderEncoderTest\&.php\&.
.SS "testSpaceIsRepresentedByUnderscore ()"

.PP
Definition at line 35 of file QpHeaderEncoderTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
