.TH "Symfony\Component\Routing" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\Routing \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBAnnotation\fP"
.br
.ti -1c
.RI " \fBException\fP"
.br
.ti -1c
.RI " \fBGenerator\fP"
.br
.ti -1c
.RI " \fBLoader\fP"
.br
.ti -1c
.RI " \fBMatcher\fP"
.br
.ti -1c
.RI " \fBTests\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCompiledRoute\fP"
.br
.ti -1c
.RI "class \fBRequestContext\fP"
.br
.ti -1c
.RI "interface \fBRequestContextAwareInterface\fP"
.br
.ti -1c
.RI "class \fBRoute\fP"
.br
.ti -1c
.RI "class \fBRouteCollection\fP"
.br
.ti -1c
.RI "class \fBRouteCompiler\fP"
.br
.ti -1c
.RI "interface \fBRouteCompilerInterface\fP"
.br
.ti -1c
.RI "class \fBRouter\fP"
.br
.ti -1c
.RI "interface \fBRouterInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
