.TH "TestKernelThatThrowsException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestKernelThatThrowsException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHttpKernelInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhandle\fP (\fBRequest\fP $request, $type=self::MASTER_REQUEST, $catch=true)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 138 of file ExceptionListenerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "handle (\fBRequest\fP $request,  $type = \fCself::MASTER_REQUEST\fP,  $catch = \fCtrue\fP)"

.PP
Implements \fBHttpKernelInterface\fP\&.
.PP
Definition at line 140 of file ExceptionListenerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
