.TH "DescriptorApplication1" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DescriptorApplication1 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApplication\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file DescriptorApplication1\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
