.TH "CacheWarmer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CacheWarmer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCacheWarmerInterface\fP\&.
.PP
Inherited by \fBTestCacheWarmer\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBwriteCacheFile\fP ($file, $content)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Abstract cache warmer that knows how to write a file to the cache\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 19 of file CacheWarmer\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "writeCacheFile ( $file,  $content)\fC [protected]\fP"

.PP
Definition at line 21 of file CacheWarmer\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
