.TH "FileLocator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileLocator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseFileLocator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBKernelInterface\fP $kernel, $\fBpath\fP=null, array $paths=array())"
.br
.ti -1c
.RI "\fBlocate\fP ($file, $currentPath=null, $first=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFileLocator\fP uses the \fBKernelInterface\fP to locate resources in bundles\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 22 of file FileLocator\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBKernelInterface\fP $kernel,  $path = \fCnull\fP, array $paths = \fCarray()\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$kernel\fP \fBA\fP \fBKernelInterface\fP instance 
.br
\fI$path\fP The path the global resource directory 
.br
\fI$paths\fP An array of paths where to look for resources 
.RE
.PP

.PP
Definition at line 34 of file FileLocator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "locate ( $file,  $currentPath = \fCnull\fP,  $first = \fCtrue\fP)"
{} 
.PP
Definition at line 48 of file FileLocator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
