.TH "ConsoleEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Event\&.
.PP
Inherited by \fBConsoleCommandEvent\fP, \fBConsoleExceptionEvent\fP, and \fBConsoleTerminateEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBCommand\fP $command, \fBInputInterface\fP $input, \fBOutputInterface\fP $output)"
.br
.ti -1c
.RI "\fBgetCommand\fP ()"
.br
.ti -1c
.RI "\fBgetInput\fP ()"
.br
.ti -1c
.RI "\fBgetOutput\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$command\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows to inspect input and output of a command\&.
.PP
\fBAuthor:\fP
.RS 4
Francesco Levorato git@flevour.net 
.RE
.PP

.PP
Definition at line 24 of file ConsoleEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBCommand\fP $command, \fBInputInterface\fP $input, \fBOutputInterface\fP $output)"

.PP
Definition at line 31 of file ConsoleEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getCommand ()"
Gets the command that is executed\&.
.PP
\fBReturns:\fP
.RS 4
\fBCommand\fP \fBA\fP \fBCommand\fP instance 
.RE
.PP

.PP
Definition at line 43 of file ConsoleEvent\&.php\&.
.SS "getInput ()"
Gets the input instance\&.
.PP
\fBReturns:\fP
.RS 4
InputInterface An InputInterface instance 
.RE
.PP

.PP
Definition at line 53 of file ConsoleEvent\&.php\&.
.SS "getOutput ()"
Gets the output instance\&.
.PP
\fBReturns:\fP
.RS 4
OutputInterface An OutputInterface instance 
.RE
.PP

.PP
Definition at line 63 of file ConsoleEvent\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$command\fC [protected]\fP"

.PP
Definition at line 26 of file ConsoleEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
