.TH "RouteNotFoundException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RouteNotFoundException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits InvalidArgumentException, and \fBExceptionInterface\fP\&.
.SH "Detailed Description"
.PP 
\fBException\fP thrown when a route does not exist\&.
.PP
\fBAuthor:\fP
.RS 4
Alexandre Salomé alexandre.salome@gmail.com
.RE
.PP

.PP
Definition at line 21 of file RouteNotFoundException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
