.TH "AuthenticationManagerInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthenticationManagerInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAuthenticationProviderManager\fP, and \fBAuthenticationProviderInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBauthenticate\fP (\fBTokenInterface\fP $token)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthenticationManagerInterface\fP is the interface for authentication managers, which process \fBToken\fP authentication\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 23 of file AuthenticationManagerInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "authenticate (\fBTokenInterface\fP $token)"
Attempts to authenticate a TokenInterface object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP The TokenInterface instance to authenticate
.RE
.PP
\fBReturns:\fP
.RS 4
TokenInterface An authenticated TokenInterface instance, never null
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIAuthenticationException\fP if the authentication fails 
.RE
.PP

.PP
Implemented in \fBAuthenticationProviderManager\fP, \fBUserAuthenticationProvider\fP, \fBPreAuthenticatedAuthenticationProvider\fP, \fBRememberMeAuthenticationProvider\fP, \fBAnonymousAuthenticationProvider\fP, and \fBSimpleAuthenticationProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
