.TH "Cookie" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cookie \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP, $value=null, $expire=0, $\fBpath\fP= '/', $domain=null, $secure=false, $httpOnly=true)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetValue\fP ()"
.br
.ti -1c
.RI "\fBgetDomain\fP ()"
.br
.ti -1c
.RI "\fBgetExpiresTime\fP ()"
.br
.ti -1c
.RI "\fBgetPath\fP ()"
.br
.ti -1c
.RI "\fBisSecure\fP ()"
.br
.ti -1c
.RI "\fBisHttpOnly\fP ()"
.br
.ti -1c
.RI "\fBisCleared\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP, $value=null, $expire=0, $\fBpath\fP= '/', $domain=null, $secure=false, $httpOnly=true)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBgetValue\fP ()"
.br
.ti -1c
.RI "\fBgetDomain\fP ()"
.br
.ti -1c
.RI "\fBgetExpiresTime\fP ()"
.br
.ti -1c
.RI "\fBgetPath\fP ()"
.br
.ti -1c
.RI "\fBisSecure\fP ()"
.br
.ti -1c
.RI "\fBisHttpOnly\fP ()"
.br
.ti -1c
.RI "\fBisCleared\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$value\fP"
.br
.ti -1c
.RI "\fB$domain\fP"
.br
.ti -1c
.RI "\fB$expire\fP"
.br
.ti -1c
.RI "\fB$path\fP"
.br
.ti -1c
.RI "\fB$secure\fP"
.br
.ti -1c
.RI "\fB$httpOnly\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a cookie\&.
.PP
\fBAuthor:\fP
.RS 4
Johannes M\&. Schmitt schmittjoh@gmail.com
.RE
.PP

.PP
Definition at line 14855 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name,  $value = \fCnull\fP,  $expire = \fC0\fP,  $path = \fC'/'\fP,  $domain = \fCnull\fP,  $secure = \fCfalse\fP,  $httpOnly = \fCtrue\fP)"

.PP
Definition at line 14864 of file compiled\&.php\&.
.SS "__construct ( $name,  $value = \fCnull\fP,  $expire = \fC0\fP,  $path = \fC'/'\fP,  $domain = \fCnull\fP,  $secure = \fCfalse\fP,  $httpOnly = \fCtrue\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The name of the cookie 
.br
\fI$value\fP The value of the cookie 
.br
\fI$expire\fP The time the cookie expires 
.br
\fI$path\fP The path on the server in which the cookie will be available on 
.br
\fI$domain\fP The domain that the cookie is available to 
.br
\fI$secure\fP Whether the cookie should only be transmitted over a secure HTTPS connection from the client 
.br
\fI$httpOnly\fP Whether the cookie will be made accessible only through the HTTP protocol
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 46 of file Cookie\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"
Returns the cookie as a string\&.
.PP
\fBReturns:\fP
.RS 4
string The cookie 
.RE
.PP

.PP
Definition at line 82 of file Cookie\&.php\&.
.SS "__toString ()"

.PP
Definition at line 14889 of file compiled\&.php\&.
.SS "getDomain ()"
Gets the domain that the cookie is available to\&.
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP

.PP
Definition at line 146 of file Cookie\&.php\&.
.SS "getDomain ()"

.PP
Definition at line 14922 of file compiled\&.php\&.
.SS "getExpiresTime ()"
Gets the time the cookie expires\&.
.PP
\fBReturns:\fP
.RS 4
int
.RE
.PP

.PP
Definition at line 158 of file Cookie\&.php\&.
.SS "getExpiresTime ()"

.PP
Definition at line 14926 of file compiled\&.php\&.
.SS "getName ()"
Gets the name of the cookie\&.
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP

.PP
Definition at line 122 of file Cookie\&.php\&.
.SS "getName ()"

.PP
Definition at line 14914 of file compiled\&.php\&.
.SS "getPath ()"
Gets the path on the server in which the cookie will be available on\&.
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP

.PP
Definition at line 170 of file Cookie\&.php\&.
.SS "getPath ()"

.PP
Definition at line 14930 of file compiled\&.php\&.
.SS "getValue ()"
Gets the value of the cookie\&.
.PP
\fBReturns:\fP
.RS 4
string
.RE
.PP

.PP
Definition at line 134 of file Cookie\&.php\&.
.SS "getValue ()"

.PP
Definition at line 14918 of file compiled\&.php\&.
.SS "isCleared ()"
Whether this cookie is about to be cleared\&.
.PP
\fBReturns:\fP
.RS 4
bool
.RE
.PP

.PP
Definition at line 206 of file Cookie\&.php\&.
.SS "isCleared ()"

.PP
Definition at line 14942 of file compiled\&.php\&.
.SS "isHttpOnly ()"
Checks whether the cookie will be made accessible only through the HTTP protocol\&.
.PP
\fBReturns:\fP
.RS 4
bool
.RE
.PP

.PP
Definition at line 194 of file Cookie\&.php\&.
.SS "isHttpOnly ()"

.PP
Definition at line 14938 of file compiled\&.php\&.
.SS "isSecure ()"
Checks whether the cookie should only be transmitted over a secure HTTPS connection from the client\&.
.PP
\fBReturns:\fP
.RS 4
bool
.RE
.PP

.PP
Definition at line 182 of file Cookie\&.php\&.
.SS "isSecure ()"

.PP
Definition at line 14934 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$domain\fC [protected]\fP"

.PP
Definition at line 14859 of file compiled\&.php\&.
.SS "$expire\fC [protected]\fP"

.PP
Definition at line 14860 of file compiled\&.php\&.
.SS "$httpOnly\fC [protected]\fP"

.PP
Definition at line 14863 of file compiled\&.php\&.
.SS "$\fBname\fP\fC [protected]\fP"

.PP
Definition at line 14857 of file compiled\&.php\&.
.SS "$\fBpath\fP\fC [protected]\fP"

.PP
Definition at line 14861 of file compiled\&.php\&.
.SS "$secure\fC [protected]\fP"

.PP
Definition at line 14862 of file compiled\&.php\&.
.SS "$value\fC [protected]\fP"

.PP
Definition at line 14858 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
