.TH "ConfirmationQuestion" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfirmationQuestion \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuestion\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($question, $default=true)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a yes/no question\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 19 of file ConfirmationQuestion\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $question,  $default = \fCtrue\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$question\fP The question to ask to the user 
.br
\fI$default\fP The default answer to return, true or false 
.RE
.PP

.PP
Definition at line 27 of file ConfirmationQuestion\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
