.TH "Logger" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Logger \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLoggerInterface\fP\&.
.PP
Inherited by \fBTestLogger\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBgetLogs\fP ($level=false)"
.br
.ti -1c
.RI "\fBclear\fP ()"
.br
.ti -1c
.RI "\fBlog\fP ($level, $message, array $context=array())"
.br
.ti -1c
.RI "\fBemergency\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBalert\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBcritical\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBerror\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBwarning\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBnotice\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBinfo\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBdebug\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBemerg\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBcrit\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBerr\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBwarn\fP ($message, array $context=array())"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$logs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file Logger\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 20 of file Logger\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "alert ( $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 54 of file Logger\&.php\&.
.SS "clear ()"

.PP
Definition at line 30 of file Logger\&.php\&.
.SS "crit ( $message, array $context = \fCarray()\fP)"

.PP
\fBDeprecated\fP
.RS 4

.RE
.PP

.PP
Definition at line 102 of file Logger\&.php\&.
.SS "critical ( $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 59 of file Logger\&.php\&.
.SS "debug ( $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 84 of file Logger\&.php\&.
.SS "emerg ( $message, array $context = \fCarray()\fP)"

.PP
\fBDeprecated\fP
.RS 4

.RE
.PP

.PP
Definition at line 92 of file Logger\&.php\&.
.SS "emergency ( $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 49 of file Logger\&.php\&.
.SS "err ( $message, array $context = \fCarray()\fP)"

.PP
\fBDeprecated\fP
.RS 4

.RE
.PP

.PP
Definition at line 112 of file Logger\&.php\&.
.SS "error ( $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 64 of file Logger\&.php\&.
.SS "getLogs ( $level = \fCfalse\fP)"

.PP
Definition at line 25 of file Logger\&.php\&.
.SS "info ( $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 79 of file Logger\&.php\&.
.SS "log ( $level,  $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 44 of file Logger\&.php\&.
.SS "notice ( $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 74 of file Logger\&.php\&.
.SS "warn ( $message, array $context = \fCarray()\fP)"

.PP
\fBDeprecated\fP
.RS 4

.RE
.PP

.PP
Definition at line 122 of file Logger\&.php\&.
.SS "warning ( $message, array $context = \fCarray()\fP)"

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 69 of file Logger\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBlogs\fP\fC [protected]\fP"

.PP
Definition at line 18 of file Logger\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
