.TH "Table" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Table \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBOutputInterface\fP $output)"
.br
.ti -1c
.RI "\fBsetStyle\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBgetStyle\fP ()"
.br
.ti -1c
.RI "\fBsetHeaders\fP (array $headers)"
.br
.ti -1c
.RI "\fBsetRows\fP (array $rows)"
.br
.ti -1c
.RI "\fBaddRows\fP (array $rows)"
.br
.ti -1c
.RI "\fBaddRow\fP ($row)"
.br
.ti -1c
.RI "\fBsetRow\fP ($column, array $row)"
.br
.ti -1c
.RI "\fBrender\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBsetStyleDefinition\fP ($\fBname\fP, \fBTableStyle\fP $\fBstyle\fP)"
.br
.ti -1c
.RI "static \fBgetStyleDefinition\fP ($\fBname\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides helpers to display a table\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.PP
Саша Стаменковић umpirsky@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file Table\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBOutputInterface\fP $output)"

.PP
Definition at line 64 of file Table\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addRow ( $row)"

.PP
Definition at line 163 of file Table\&.php\&.
.SS "addRows (array $rows)"

.PP
Definition at line 154 of file Table\&.php\&.
.SS "getStyle ()"
Gets the current table style\&.
.PP
\fBReturns:\fP
.RS 4
\fBTableStyle\fP 
.RE
.PP

.PP
Definition at line 135 of file Table\&.php\&.
.SS "static getStyleDefinition ( $name)\fC [static]\fP"
Gets a style definition by name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The style name
.RE
.PP
\fBReturns:\fP
.RS 4
\fBTableStyle\fP \fBA\fP \fBTableStyle\fP instance 
.RE
.PP

.PP
Definition at line 97 of file Table\&.php\&.
.SS "render ()"
Renders table to output\&.
.PP
Example: +---------------+-----------------------+------------------+ | ISBN | Title | \fBAuthor\fP | +---------------+-----------------------+------------------+ | 99921-58-10-7 | Divine Comedy | Dante Alighieri | | 9971-5-0210-0 | \fBA\fP Tale of Two Cities | Charles Dickens | | 960-425-059-0 | The Lord of the Rings | J\&. R\&. R\&. Tolkien | +---------------+-----------------------+------------------+ 
.PP
Definition at line 223 of file Table\&.php\&.
.SS "setHeaders (array $headers)"

.PP
Definition at line 140 of file Table\&.php\&.
.SS "setRow ( $column, array $row)"

.PP
Definition at line 204 of file Table\&.php\&.
.SS "setRows (array $rows)"

.PP
Definition at line 147 of file Table\&.php\&.
.SS "setStyle ( $name)"
Sets table style\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The style name or a \fBTableStyle\fP instance
.RE
.PP
\fBReturns:\fP
.RS 4
\fBTable\fP 
.RE
.PP

.PP
Definition at line 117 of file Table\&.php\&.
.SS "static setStyleDefinition ( $name, \fBTableStyle\fP $style)\fC [static]\fP"
Sets a style definition\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The style name 
.br
\fI$style\fP \fBA\fP \fBTableStyle\fP instance 
.RE
.PP

.PP
Definition at line 81 of file Table\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
