.TH "RoleHierarchyInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoleHierarchyInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRoleHierarchy\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetReachableRoles\fP (array $roles)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRoleHierarchyInterface\fP is the interface for a role hierarchy\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 19 of file RoleHierarchyInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getReachableRoles (array $roles)"
Returns an array of all reachable roles by the given ones\&.
.PP
Reachable roles are the roles directly assigned but also all roles that are transitively reachable from them in the role hierarchy\&.
.PP
\fBParameters:\fP
.RS 4
\fIRoleInterface[]\fP $roles An array of directly assigned roles
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRoleInterface\fP[] An array of all reachable roles 
.RE
.PP

.PP
Implemented in \fBRoleHierarchy\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
