.TH "UnsupportedUserException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnsupportedUserException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAuthenticationServiceException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This exception is thrown when an account is reloaded from a provider which doesn't support the passed implementation of UserInterface\&.
.PP
\fBAuthor:\fP
.RS 4
Johannes M\&. Schmitt schmittjoh@gmail.com 
.RE
.PP

.PP
Definition at line 20 of file UnsupportedUserException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
