.TH "RoleInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoleInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRole\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetRole\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRoleInterface\fP represents a role granted to a user\&.
.PP
\fBA\fP role must either have a string representation or it needs to be explicitly supported by at least one AccessDecisionManager\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 22 of file RoleInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getRole ()"
Returns the role\&.
.PP
This method returns a string representation whenever possible\&.
.PP
When the role cannot be represented with sufficient precision by a string, it should return null\&.
.PP
\fBReturns:\fP
.RS 4
string|null \fBA\fP string representation of the role, or null 
.RE
.PP

.PP
Implemented in \fBRole\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
