.TH "IcuDatFileLoaderTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IcuDatFileLoaderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLocalizedTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestLoadInvalidResource\fP ()"
.br
.ti -1c
.RI "\fBtestDatEnglishLoad\fP ()"
.br
.ti -1c
.RI "\fBtestDatFrenchLoad\fP ()"
.br
.ti -1c
.RI "\fBtestLoadNonExistingResource\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file IcuDatFileLoaderTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 19 of file IcuDatFileLoaderTest\&.php\&.
.SS "testDatEnglishLoad ()"

.PP
Definition at line 35 of file IcuDatFileLoaderTest\&.php\&.
.SS "testDatFrenchLoad ()"

.PP
Definition at line 49 of file IcuDatFileLoaderTest\&.php\&.
.SS "testLoadInvalidResource ()"

.PP
Definition at line 29 of file IcuDatFileLoaderTest\&.php\&.
.SS "testLoadNonExistingResource ()"

.PP
Definition at line 63 of file IcuDatFileLoaderTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
