.TH "AuthenticationEvents" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthenticationEvents \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBAUTHENTICATION_SUCCESS\fP = 'security\&.authentication\&.success'"
.br
.ti -1c
.RI "const \fBAUTHENTICATION_FAILURE\fP = 'security\&.authentication\&.failure'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file AuthenticationEvents\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const AUTHENTICATION_FAILURE = 'security\&.authentication\&.failure'"

.PP
Definition at line 37 of file AuthenticationEvents\&.php\&.
.SS "const AUTHENTICATION_SUCCESS = 'security\&.authentication\&.success'"

.PP
Definition at line 25 of file AuthenticationEvents\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
