.TH "TestUser" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestUser \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$name\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file AbstractTokenTest\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name)"

.PP
Definition at line 22 of file AbstractTokenTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"

.PP
Definition at line 27 of file AbstractTokenTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBname\fP\fC [protected]\fP"

.PP
Definition at line 20 of file AbstractTokenTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
