.TH "LegacyPdoSessionHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LegacyPdoSessionHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestIncompleteOptions\fP ()"
.br
.ti -1c
.RI "\fBtestWrongPdoErrMode\fP ()"
.br
.ti -1c
.RI "\fBtestWrongTableOptionsWrite\fP ()"
.br
.ti -1c
.RI "\fBtestWrongTableOptionsRead\fP ()"
.br
.ti -1c
.RI "\fBtestWriteRead\fP ()"
.br
.ti -1c
.RI "\fBtestMultipleInstances\fP ()"
.br
.ti -1c
.RI "\fBtestSessionDestroy\fP ()"
.br
.ti -1c
.RI "\fBtestSessionGC\fP ()"
.br
.ti -1c
.RI "\fBtestGetConnection\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
legacy 
.PP
Definition at line 19 of file LegacyPdoSessionHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 23 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testGetConnection ()"

.PP
Definition at line 107 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testIncompleteOptions ()"

.PP
Definition at line 37 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testMultipleInstances ()"

.PP
Definition at line 74 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testSessionDestroy ()"

.PP
Definition at line 83 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testSessionGC ()"

.PP
Definition at line 94 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testWriteRead ()"

.PP
Definition at line 67 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testWrongPdoErrMode ()"

.PP
Definition at line 43 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testWrongTableOptionsRead ()"

.PP
Definition at line 60 of file LegacyPdoSessionHandlerTest\&.php\&.
.SS "testWrongTableOptionsWrite ()"

.PP
Definition at line 53 of file LegacyPdoSessionHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
