.TH "StreamedResponseListener" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamedResponseListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventSubscriberInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBonKernelResponse\fP (\fBFilterResponseEvent\fP $\fBevent\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetSubscribedEvents\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBStreamedResponseListener\fP is responsible for sending the \fBResponse\fP to the client\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 25 of file StreamedResponseListener\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getSubscribedEvents ()\fC [static]\fP"

.PP
Definition at line 45 of file StreamedResponseListener\&.php\&.
.SS "onKernelResponse (\fBFilterResponseEvent\fP $event)"
Filters the \fBResponse\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$event\fP \fBA\fP FilterResponseEvent instance 
.RE
.PP

.PP
Definition at line 32 of file StreamedResponseListener\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
