.TH "RedirectableUrlMatcherInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RedirectableUrlMatcherInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRedirectableUrlMatcher\fP, and \fBRedirectableUrlMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBredirect\fP ($\fBpath\fP, $route, $scheme=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRedirectableUrlMatcherInterface\fP knows how to redirect the user\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 21 of file RedirectableUrlMatcherInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "redirect ( $path,  $route,  $scheme = \fCnull\fP)"
Redirects the user to another \fBURL\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP The path info to redirect to\&. 
.br
\fI$route\fP The route name that matched 
.br
\fI$scheme\fP The \fBURL\fP scheme (null to keep the current one)
.RE
.PP
\fBReturns:\fP
.RS 4
array An array of parameters
.RE
.PP

.PP
Implemented in \fBRedirectableUrlMatcher\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
