.TH "FilterControllerEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterControllerEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBKernelEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBHttpKernelInterface\fP $kernel, $controller, \fBRequest\fP $request, $requestType)"
.br
.ti -1c
.RI "\fBgetController\fP ()"
.br
.ti -1c
.RI "\fBsetController\fP ($controller)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows filtering of a controller callable\&.
.PP
You can call \fBgetController()\fP to retrieve the current controller\&. With \fBsetController()\fP you can set a new controller that is used in the processing of the request\&.
.PP
Controllers should be callables\&.
.PP
\fBAuthor:\fP
.RS 4
Bernhard Schussek bschussek@gmail.com
.RE
.PP

.PP
Definition at line 30 of file FilterControllerEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBHttpKernelInterface\fP $kernel,  $controller, \fBRequest\fP $request,  $requestType)"

.PP
Definition at line 39 of file FilterControllerEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getController ()"
Returns the current controller\&.
.PP
\fBReturns:\fP
.RS 4
callable
.RE
.PP

.PP
Definition at line 53 of file FilterControllerEvent\&.php\&.
.SS "setController ( $controller)"
Sets a new controller\&.
.PP
\fBParameters:\fP
.RS 4
\fI$controller\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 67 of file FilterControllerEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
