.TH "IniFileDumper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IniFileDumper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileDumper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat\fP (\fBMessageCatalogue\fP $messages, $domain= 'messages')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetExtension\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBIniFileDumper\fP generates an ini formatted string representation of a message catalogue\&.
.PP
\fBAuthor:\fP
.RS 4
Stealth35 
.RE
.PP

.PP
Definition at line 21 of file IniFileDumper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "format (\fBMessageCatalogue\fP $messages,  $domain = \fC'messages'\fP)"
{} 
.PP
Definition at line 26 of file IniFileDumper\&.php\&.
.SS "getExtension ()\fC [protected]\fP"
{} 
.PP
Definition at line 41 of file IniFileDumper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
