.TH "RecursiveDirectoryIterator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RecursiveDirectoryIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RecursiveDirectoryIterator, and RecursiveDirectoryIterator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBpath\fP, $flags, $ignoreUnreadableDirs=false)"
.br
.ti -1c
.RI "\fBcurrent\fP ()"
.br
.ti -1c
.RI "\fBgetChildren\fP ()"
.br
.ti -1c
.RI "\fBrewind\fP ()"
.br
.ti -1c
.RI "\fBisRewindable\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP ($\fBpath\fP, $flags, $ignoreUnreadableDirs=false)"
.br
.ti -1c
.RI "\fBcurrent\fP ()"
.br
.ti -1c
.RI "\fBgetChildren\fP ()"
.br
.ti -1c
.RI "\fBrewind\fP ()"
.br
.ti -1c
.RI "\fBisRewindable\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extends the  to support relative paths\&.
.PP
\fBAuthor:\fP
.RS 4
Victor Berchet victor@suumit.com 
.RE
.PP

.PP
Definition at line 15423 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $path,  $flags,  $ignoreUnreadableDirs = \fCfalse\fP)"

.PP
Definition at line 15427 of file compiled\&.php\&.
.SS "__construct ( $path,  $flags,  $ignoreUnreadableDirs = \fCfalse\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP 
.br
\fI$flags\fP 
.br
\fI$ignoreUnreadableDirs\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 43 of file RecursiveDirectoryIterator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "current ()"
Return an instance of \fBSplFileInfo\fP with support for relative paths\&.
.PP
\fBReturns:\fP
.RS 4
\fBSplFileInfo\fP \fBFile\fP information 
.RE
.PP

.PP
Definition at line 58 of file RecursiveDirectoryIterator\&.php\&.
.SS "current ()"

.PP
Definition at line 15435 of file compiled\&.php\&.
.SS "getChildren ()"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP
\fBExceptions:\fP
.RS 4
\fIAccessDeniedException\fP 
.RE
.PP

.PP
Definition at line 68 of file RecursiveDirectoryIterator\&.php\&.
.SS "getChildren ()"

.PP
Definition at line 15439 of file compiled\&.php\&.
.SS "isRewindable ()"
Checks if the stream is rewindable\&.
.PP
\fBReturns:\fP
.RS 4
bool true when the stream is rewindable, false otherwise 
.RE
.PP

.PP
Definition at line 109 of file RecursiveDirectoryIterator\&.php\&.
.SS "isRewindable ()"

.PP
Definition at line 15463 of file compiled\&.php\&.
.SS "rewind ()"
Do nothing for non rewindable stream\&. 
.PP
Definition at line 92 of file RecursiveDirectoryIterator\&.php\&.
.SS "rewind ()"

.PP
Definition at line 15455 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
