.TH "QtFileDumper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QtFileDumper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileDumper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat\fP (\fBMessageCatalogue\fP $messages, $domain)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetExtension\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBQtFileDumper\fP generates ts files from a message catalogue\&.
.PP
\fBAuthor:\fP
.RS 4
Benjamin Eberlei kontakt@beberlei.de 
.RE
.PP

.PP
Definition at line 21 of file QtFileDumper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "format (\fBMessageCatalogue\fP $messages,  $domain)"
{} 
.PP
Definition at line 26 of file QtFileDumper\&.php\&.
.SS "getExtension ()\fC [protected]\fP"
{} 
.PP
Definition at line 46 of file QtFileDumper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
