.TH "TranslatorInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranslatorInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTranslator\fP, \fBIdentityTranslator\fP, \fBLoggingTranslator\fP, and \fBTranslator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtrans\fP ($id, array $parameters=array(), $domain=null, $\fBlocale\fP=null)"
.br
.ti -1c
.RI "\fBtransChoice\fP ($id, $number, array $parameters=array(), $domain=null, $\fBlocale\fP=null)"
.br
.ti -1c
.RI "\fBsetLocale\fP ($\fBlocale\fP)"
.br
.ti -1c
.RI "\fBgetLocale\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTranslatorInterface\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 21 of file TranslatorInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getLocale ()"
Returns the current locale\&.
.PP
\fBReturns:\fP
.RS 4
string The locale
.RE
.PP

.PP
Implemented in \fBTranslator\fP, \fBTranslator\fP, \fBLoggingTranslator\fP, and \fBIdentityTranslator\fP\&.
.SS "setLocale ( $locale)"
Sets the current locale\&.
.PP
\fBParameters:\fP
.RS 4
\fI$locale\fP The locale
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implemented in \fBTranslator\fP, \fBTranslatorWithInvalidLocale\fP, \fBTranslator\fP, \fBLoggingTranslator\fP, and \fBIdentityTranslator\fP\&.
.SS "trans ( $id, array $parameters = \fCarray()\fP,  $domain = \fCnull\fP,  $locale = \fCnull\fP)"
Translates the given message\&.
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP The message id (may also be an object that can be cast to string) 
.br
\fI$parameters\fP An array of parameters for the message 
.br
\fI$domain\fP The domain for the message or null to use the default 
.br
\fI$locale\fP The locale or null to use the default
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implemented in \fBTranslator\fP, \fBTranslator\fP, \fBIdentityTranslator\fP, and \fBLoggingTranslator\fP\&.
.SS "transChoice ( $id,  $number, array $parameters = \fCarray()\fP,  $domain = \fCnull\fP,  $locale = \fCnull\fP)"
Translates the given choice message by choosing a translation according to a number\&.
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP The message id (may also be an object that can be cast to string) 
.br
\fI$number\fP The number to use to find the indice of the message 
.br
\fI$parameters\fP An array of parameters for the message 
.br
\fI$domain\fP The domain for the message or null to use the default 
.br
\fI$locale\fP The locale or null to use the default
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implemented in \fBTranslator\fP, \fBTranslator\fP, \fBIdentityTranslator\fP, and \fBLoggingTranslator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
