.TH "InnerTypeIterator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InnerTypeIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits ArrayIterator\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcurrent\fP ()"
.br
.ti -1c
.RI "\fBisFile\fP ()"
.br
.ti -1c
.RI "\fBisDir\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file FileTypeFilterIteratorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "current ()"

.PP
Definition at line 58 of file FileTypeFilterIteratorTest\&.php\&.
.SS "isDir ()"

.PP
Definition at line 68 of file FileTypeFilterIteratorTest\&.php\&.
.SS "isFile ()"

.PP
Definition at line 63 of file FileTypeFilterIteratorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
