.TH "OperationInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAbstractOperation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetDomains\fP ()"
.br
.ti -1c
.RI "\fBgetMessages\fP ($domain)"
.br
.ti -1c
.RI "\fBgetNewMessages\fP ($domain)"
.br
.ti -1c
.RI "\fBgetObsoleteMessages\fP ($domain)"
.br
.ti -1c
.RI "\fBgetResult\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an operation on catalogue(s)\&.
.PP
\fBAuthor:\fP
.RS 4
Jean-François Simon jeanfrancois.simon@sensiolabs.com 
.RE
.PP

.PP
Definition at line 21 of file OperationInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDomains ()"
Returns domains affected by operation\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBAbstractOperation\fP\&.
.SS "getMessages ( $domain)"
Returns all valid messages after operation\&.
.PP
\fBParameters:\fP
.RS 4
\fI$domain\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBAbstractOperation\fP\&.
.SS "getNewMessages ( $domain)"
Returns new messages after operation\&.
.PP
\fBParameters:\fP
.RS 4
\fI$domain\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBAbstractOperation\fP\&.
.SS "getObsoleteMessages ( $domain)"
Returns obsolete messages after operation\&.
.PP
\fBParameters:\fP
.RS 4
\fI$domain\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Implemented in \fBAbstractOperation\fP\&.
.SS "getResult ()"
Returns resulting catalogue\&.
.PP
\fBReturns:\fP
.RS 4
\fBMessageCatalogueInterface\fP 
.RE
.PP

.PP
Implemented in \fBAbstractOperation\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
