.TH "AbstractProfilerStorageTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractProfilerStorageTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.PP
Inherited by \fBFileProfilerStorageTest\fP, \fBMemcachedProfilerStorageTest\fP, \fBMemcacheProfilerStorageTest\fP, \fBMongoDbProfilerStorageTest\fP, \fBRedisProfilerStorageTest\fP, and \fBSqliteProfilerStorageTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestStore\fP ()"
.br
.ti -1c
.RI "\fBtestChildren\fP ()"
.br
.ti -1c
.RI "\fBtestStoreSpecialCharsInUrl\fP ()"
.br
.ti -1c
.RI "\fBtestStoreDuplicateToken\fP ()"
.br
.ti -1c
.RI "\fBtestRetrieveByIp\fP ()"
.br
.ti -1c
.RI "\fBtestRetrieveByUrl\fP ()"
.br
.ti -1c
.RI "\fBtestStoreTime\fP ()"
.br
.ti -1c
.RI "\fBtestRetrieveByEmptyUrlAndIp\fP ()"
.br
.ti -1c
.RI "\fBtestRetrieveByMethodAndLimit\fP ()"
.br
.ti -1c
.RI "\fBtestPurge\fP ()"
.br
.ti -1c
.RI "\fBtestDuplicates\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetStorage\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file AbstractProfilerStorageTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getStorage ()\fC [abstract]\fP, \fC [protected]\fP"

.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "testChildren ()"

.PP
Definition at line 30 of file AbstractProfilerStorageTest\&.php\&.
.SS "testDuplicates ()"
three duplicates 
.PP
Definition at line 234 of file AbstractProfilerStorageTest\&.php\&.
.SS "testPurge ()"

.PP
Definition at line 208 of file AbstractProfilerStorageTest\&.php\&.
.SS "testRetrieveByEmptyUrlAndIp ()"

.PP
Definition at line 182 of file AbstractProfilerStorageTest\&.php\&.
.SS "testRetrieveByIp ()"

.PP
Definition at line 99 of file AbstractProfilerStorageTest\&.php\&.
.SS "testRetrieveByMethodAndLimit ()"

.PP
Definition at line 193 of file AbstractProfilerStorageTest\&.php\&.
.SS "testRetrieveByUrl ()"

.PP
Definition at line 111 of file AbstractProfilerStorageTest\&.php\&.
.SS "testStore ()"

.PP
Definition at line 18 of file AbstractProfilerStorageTest\&.php\&.
.SS "testStoreDuplicateToken ()"

.PP
Definition at line 84 of file AbstractProfilerStorageTest\&.php\&.
.SS "testStoreSpecialCharsInUrl ()"

.PP
Definition at line 59 of file AbstractProfilerStorageTest\&.php\&.
.SS "testStoreTime ()"

.PP
Definition at line 157 of file AbstractProfilerStorageTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
