.TH "PhpAdapter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhpAdapter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractAdapter\fP, and \fBAbstractAdapter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsearchInDirectory\fP ($dir)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBsearchInDirectory\fP ($dir)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcanBeUsed\fP ()"
.br
.ti -1c
.RI "\fBcanBeUsed\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBPHP\fP finder engine implementation\&.
.PP
\fBAuthor:\fP
.RS 4
Jean-François Simon contact@jfsimon.fr 
.RE
.PP

.PP
Definition at line 15935 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "canBeUsed ()\fC [protected]\fP"
{} 
.PP
Definition at line 94 of file PhpAdapter\&.php\&.
.SS "canBeUsed ()\fC [protected]\fP"

.PP
Definition at line 15981 of file compiled\&.php\&.
.SS "getName ()"
{} 
.PP
Implements \fBAdapterInterface\fP\&.
.PP
Definition at line 86 of file PhpAdapter\&.php\&.
.SS "getName ()"

.PP
Implements \fBAdapterInterface\fP\&.
.PP
Definition at line 15977 of file compiled\&.php\&.
.SS "searchInDirectory ( $dir)"
{} 
.PP
Implements \fBAdapterInterface\fP\&.
.PP
Definition at line 26 of file PhpAdapter\&.php\&.
.SS "searchInDirectory ( $dir)"

.PP
Implements \fBAdapterInterface\fP\&.
.PP
Definition at line 15937 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
