.TH "Helper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Helper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHelperInterface\fP\&.
.PP
Inherited by \fBDebugFormatterHelper\fP, \fBDescriptorHelper\fP, \fBFormatterHelper\fP, \fBInputAwareHelper\fP, \fBProcessHelper\fP, \fBProgressHelper\fP, \fBQuestionHelper\fP, and \fBTableHelper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetHelperSet\fP (\fBHelperSet\fP $helperSet=null)"
.br
.ti -1c
.RI "\fBgetHelperSet\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBstrlen\fP ($string)"
.br
.ti -1c
.RI "static \fBformatTime\fP ($secs)"
.br
.ti -1c
.RI "static \fBformatMemory\fP ($memory)"
.br
.ti -1c
.RI "static \fBstrlenWithoutDecoration\fP (\fBOutputFormatterInterface\fP $formatter, $string)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$helperSet\fP = null"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBHelper\fP is the base class for all helper classes\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 21 of file Helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static formatMemory ( $memory)\fC [static]\fP"

.PP
Definition at line 92 of file Helper\&.php\&.
.SS "static formatTime ( $secs)\fC [static]\fP"

.PP
Definition at line 65 of file Helper\&.php\&.
.SS "getHelperSet ()"
Gets the helper set associated with this helper\&.
.PP
\fBReturns:\fP
.RS 4
\fBHelperSet\fP \fBA\fP \fBHelperSet\fP instance 
.RE
.PP

.PP
Implements \fBHelperInterface\fP\&.
.PP
Definition at line 40 of file Helper\&.php\&.
.SS "setHelperSet (\fBHelperSet\fP $helperSet = \fCnull\fP)"
Sets the helper set associated with this helper\&.
.PP
\fBParameters:\fP
.RS 4
\fI$helperSet\fP \fBA\fP \fBHelperSet\fP instance 
.RE
.PP

.PP
Implements \fBHelperInterface\fP\&.
.PP
Definition at line 30 of file Helper\&.php\&.
.SS "static strlen ( $string)\fC [static]\fP"
Returns the length of a string, using mb_strwidth if it is available\&.
.PP
\fBParameters:\fP
.RS 4
\fI$string\fP The string to check its length
.RE
.PP
\fBReturns:\fP
.RS 4
int The length of the string 
.RE
.PP

.PP
Definition at line 52 of file Helper\&.php\&.
.SS "static strlenWithoutDecoration (\fBOutputFormatterInterface\fP $formatter,  $string)\fC [static]\fP"

.PP
Definition at line 109 of file Helper\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$helperSet = null\fC [protected]\fP"

.PP
Definition at line 23 of file Helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
