.TH "HIncludeFragmentRendererTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HIncludeFragmentRendererTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestRenderExceptionWhenControllerAndNoSigner\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithControllerAndSigner\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithUri\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithDefault\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithAttributesOptions\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithDefaultText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file HIncludeFragmentRendererTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testRenderExceptionWhenControllerAndNoSigner ()"

.PP
Definition at line 24 of file HIncludeFragmentRendererTest\&.php\&.
.SS "testRenderWithAttributesOptions ()"

.PP
Definition at line 61 of file HIncludeFragmentRendererTest\&.php\&.
.SS "testRenderWithControllerAndSigner ()"

.PP
Definition at line 30 of file HIncludeFragmentRendererTest\&.php\&.
.SS "testRenderWithDefault ()"

.PP
Definition at line 46 of file HIncludeFragmentRendererTest\&.php\&.
.SS "testRenderWithDefaultText ()"

.PP
Definition at line 76 of file HIncludeFragmentRendererTest\&.php\&.
.SS "testRenderWithUri ()"

.PP
Definition at line 37 of file HIncludeFragmentRendererTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
