.TH "FileBag" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileBag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBParameterBag\fP, and \fBParameterBag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $parameters=array())"
.br
.ti -1c
.RI "\fBreplace\fP (array $files=array())"
.br
.ti -1c
.RI "\fBset\fP ($key, $value)"
.br
.ti -1c
.RI "\fBadd\fP (array $files=array())"
.br
.ti -1c
.RI "\fB__construct\fP (array $parameters=array())"
.br
.ti -1c
.RI "\fBreplace\fP (array $files=array())"
.br
.ti -1c
.RI "\fBset\fP ($key, $value)"
.br
.ti -1c
.RI "\fBadd\fP (array $files=array())"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBconvertFileInformation\fP ($file)"
.br
.ti -1c
.RI "\fBfixPhpFilesArray\fP ($\fBdata\fP)"
.br
.ti -1c
.RI "\fBconvertFileInformation\fP ($file)"
.br
.ti -1c
.RI "\fBfixPhpFilesArray\fP ($\fBdata\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBFileBag\fP is a container for uploaded files\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.PP
Bulat Shakirzyanov mallluhuct@gmail.com
.RE
.PP

.PP
Definition at line 3479 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $parameters = \fCarray()\fP)"

.PP
Definition at line 3482 of file compiled\&.php\&.
.SS "__construct (array $parameters = \fCarray()\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$parameters\fP An array of HTTP files
.RE
.PP

.PP
Definition at line 35 of file FileBag\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "add (array $files = \fCarray()\fP)"
{}
.PP
Definition at line 70 of file FileBag\&.php\&.
.SS "add (array $files = \fCarray()\fP)"

.PP
Definition at line 3498 of file compiled\&.php\&.
.SS "convertFileInformation ( $file)\fC [protected]\fP"
Converts uploaded files to UploadedFile instances\&.
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP \fBA\fP (multi-dimensional) array of uploaded file information
.RE
.PP
\fBReturns:\fP
.RS 4
array \fBA\fP (multi-dimensional) array of UploadedFile instances 
.RE
.PP

.PP
Definition at line 84 of file FileBag\&.php\&.
.SS "convertFileInformation ( $file)\fC [protected]\fP"

.PP
Definition at line 3504 of file compiled\&.php\&.
.SS "fixPhpFilesArray ( $data)\fC [protected]\fP"
Fixes a malformed \fBPHP\fP $_FILES array\&.
.PP
\fBPHP\fP has a bug that the format of the $_FILES array differs, depending on whether the uploaded file fields had normal field names or array-like field names ('normal' vs\&. 'parent[child]')\&.
.PP
This method fixes the array to look like the 'normal' $_FILES array\&.
.PP
It's safe to pass an already converted array, in which case this method just returns the original array unmodified\&.
.PP
\fBParameters:\fP
.RS 4
\fI$data\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 125 of file FileBag\&.php\&.
.SS "fixPhpFilesArray ( $data)\fC [protected]\fP"

.PP
Definition at line 3525 of file compiled\&.php\&.
.SS "replace (array $files = \fCarray()\fP)"
{}
.PP
Definition at line 45 of file FileBag\&.php\&.
.SS "replace (array $files = \fCarray()\fP)"

.PP
Definition at line 3486 of file compiled\&.php\&.
.SS "set ( $key,  $value)"
{}
.PP
Definition at line 56 of file FileBag\&.php\&.
.SS "set ( $key,  $value)"

.PP
Definition at line 3491 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
