.TH "AttributeBagInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AttributeBagInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSessionBagInterface\fP, and \fBSessionBagInterface\fP\&.
.PP
Inherited by \fBAttributeBag\fP, and \fBAttributeBag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhas\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBget\fP ($\fBname\fP, $default=null)"
.br
.ti -1c
.RI "\fBset\fP ($\fBname\fP, $value)"
.br
.ti -1c
.RI "\fBall\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP (array $attributes)"
.br
.ti -1c
.RI "\fBremove\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBhas\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBget\fP ($\fBname\fP, $default=null)"
.br
.ti -1c
.RI "\fBset\fP ($\fBname\fP, $value)"
.br
.ti -1c
.RI "\fBall\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP (array $attributes)"
.br
.ti -1c
.RI "\fBremove\fP ($\fBname\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attributes store\&.
.PP
\fBAuthor:\fP
.RS 4
Drak drak@zikula.org 
.RE
.PP

.PP
Definition at line 3779 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "all ()"
Returns attributes\&.
.PP
\fBReturns:\fP
.RS 4
array Attributes 
.RE
.PP

.PP
Implemented in \fBAttributeBag\fP, and \fBAttributeBag\fP\&.
.SS "all ()"

.PP
Implemented in \fBAttributeBag\fP, and \fBAttributeBag\fP\&.
.SS "get ( $name,  $default = \fCnull\fP)"
Returns an attribute\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The attribute name 
.br
\fI$default\fP The default value if not found
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Implemented in \fBAttributeBag\fP, \fBAttributeBag\fP, and \fBNamespacedAttributeBag\fP\&.
.SS "get ( $name,  $default = \fCnull\fP)"

.PP
Implemented in \fBAttributeBag\fP, \fBAttributeBag\fP, and \fBNamespacedAttributeBag\fP\&.
.SS "has ( $name)"
Checks if an attribute is defined\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The attribute name
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the attribute is defined, false otherwise 
.RE
.PP

.PP
Implemented in \fBAttributeBag\fP, \fBAttributeBag\fP, and \fBNamespacedAttributeBag\fP\&.
.SS "has ( $name)"

.PP
Implemented in \fBAttributeBag\fP, \fBAttributeBag\fP, and \fBNamespacedAttributeBag\fP\&.
.SS "remove ( $name)"
Removes an attribute\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
mixed The removed value or null when it does not exist 
.RE
.PP

.PP
Implemented in \fBAttributeBag\fP, \fBAttributeBag\fP, and \fBNamespacedAttributeBag\fP\&.
.SS "remove ( $name)"

.PP
Implemented in \fBAttributeBag\fP, \fBAttributeBag\fP, and \fBNamespacedAttributeBag\fP\&.
.SS "replace (array $attributes)"
Sets attributes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$attributes\fP Attributes 
.RE
.PP

.PP
Implemented in \fBAttributeBag\fP, and \fBAttributeBag\fP\&.
.SS "replace (array $attributes)"

.PP
Implemented in \fBAttributeBag\fP, and \fBAttributeBag\fP\&.
.SS "set ( $name,  $value)"
Sets an attribute\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$value\fP 
.RE
.PP

.PP
Implemented in \fBAttributeBag\fP, \fBAttributeBag\fP, and \fBNamespacedAttributeBag\fP\&.
.SS "set ( $name,  $value)"

.PP
Implemented in \fBAttributeBag\fP, \fBAttributeBag\fP, and \fBNamespacedAttributeBag\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
