.TH "ControllerReference" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ControllerReference \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($controller, array $attributes=array(), array $query=array())"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$controller\fP"
.br
.ti -1c
.RI "\fB$attributes\fP = array()"
.br
.ti -1c
.RI "\fB$query\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Acts as a marker and a data holder for a \fBController\fP\&.
.PP
Some methods in \fBSymfony\fP accept both a URI (as a string) or a controller as an argument\&. In the latter case, instead of passing an array representing the controller, you can use an instance of this class\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP
\fBSee also:\fP
.RS 4
FragmentRendererInterface 
.RE
.PP

.PP
Definition at line 27 of file ControllerReference\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $controller, array $attributes = \fCarray()\fP, array $query = \fCarray()\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$controller\fP The controller name 
.br
\fI$attributes\fP An array of parameters to add to the \fBRequest\fP attributes 
.br
\fI$query\fP An array of parameters to add to the \fBRequest\fP query string 
.RE
.PP

.PP
Definition at line 40 of file ControllerReference\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$attributes = array()"

.PP
Definition at line 30 of file ControllerReference\&.php\&.
.SS "$controller"

.PP
Definition at line 29 of file ControllerReference\&.php\&.
.SS "$query = array()"

.PP
Definition at line 31 of file ControllerReference\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
