.TH "LogoutException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogoutException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntimeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message= 'Logout Exception',\\Exception $previous=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLogoutException\fP is thrown when the account cannot be logged out\&.
.PP
\fBAuthor:\fP
.RS 4
Jeremy Mikola jmikola@gmail.com 
.RE
.PP

.PP
Definition at line 19 of file LogoutException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message = \fC'Logout Exception'\fP, \\Exception $previous = \fCnull\fP)"

.PP
Definition at line 21 of file LogoutException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
