.TH "Symfony\Component\Routing\Exception" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\Routing\Exception \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "interface \fBExceptionInterface\fP"
.br
.ti -1c
.RI "class \fBInvalidParameterException\fP"
.br
.ti -1c
.RI "class \fBMethodNotAllowedException\fP"
.br
.ti -1c
.RI "class \fBMissingMandatoryParametersException\fP"
.br
.ti -1c
.RI "class \fBResourceNotFoundException\fP"
.br
.ti -1c
.RI "class \fBRouteNotFoundException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
