.TH "HttpKernel" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HttpKernel \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHttpKernelInterface\fP, and \fBTerminableInterface\fP\&.
.PP
Inherited by \fBContainerAwareHttpKernel\fP, \fBTestHttpKernel\fP, \fBTestMultipleHttpKernel\fP, and \fBTestHttpKernel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBEventDispatcherInterface\fP $dispatcher, \fBControllerResolverInterface\fP $resolver, \fBRequestStack\fP $requestStack=null)"
.br
.ti -1c
.RI "\fBhandle\fP (\fBRequest\fP $request, $type=\fBHttpKernelInterface::MASTER_REQUEST\fP, $catch=true)"
.br
.ti -1c
.RI "\fBterminate\fP (\fBRequest\fP $request, \fBResponse\fP $response)"
.br
.ti -1c
.RI "\fBterminateWithException\fP (\\Exception $exception)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$dispatcher\fP"
.br
.ti -1c
.RI "\fB$resolver\fP"
.br
.ti -1c
.RI "\fB$requestStack\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBHttpKernel\fP notifies events to convert a \fBRequest\fP object to a \fBResponse\fP one\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 36 of file HttpKernel\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBEventDispatcherInterface\fP $dispatcher, \fBControllerResolverInterface\fP $resolver, \fBRequestStack\fP $requestStack = \fCnull\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$dispatcher\fP An EventDispatcherInterface instance 
.br
\fI$resolver\fP \fBA\fP ControllerResolverInterface instance 
.br
\fI$requestStack\fP \fBA\fP stack for master/sub requests
.RE
.PP

.PP
Definition at line 51 of file HttpKernel\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "handle (\fBRequest\fP $request,  $type = \fC\fBHttpKernelInterface::MASTER_REQUEST\fP\fP,  $catch = \fCtrue\fP)"
{}
.PP
Implements \fBHttpKernelInterface\fP\&.
.PP
Definition at line 63 of file HttpKernel\&.php\&.
.SS "terminate (\fBRequest\fP $request, \fBResponse\fP $response)"
{}
.PP
Implements \fBTerminableInterface\fP\&.
.PP
Definition at line 83 of file HttpKernel\&.php\&.
.SS "terminateWithException (\\Exception $exception)"

.PP
\fBExceptions:\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line 93 of file HttpKernel\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$dispatcher\fC [protected]\fP"

.PP
Definition at line 38 of file HttpKernel\&.php\&.
.SS "$requestStack\fC [protected]\fP"

.PP
Definition at line 40 of file HttpKernel\&.php\&.
.SS "$resolver\fC [protected]\fP"

.PP
Definition at line 39 of file HttpKernel\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
