.TH "ConsoleEvents" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleEvents \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBCOMMAND\fP = 'console\&.command'"
.br
.ti -1c
.RI "const \fBTERMINATE\fP = 'console\&.terminate'"
.br
.ti -1c
.RI "const \fBEXCEPTION\fP = 'console\&.exception'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains all events dispatched by an \fBApplication\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Francesco Levorato git@flevour.net 
.RE
.PP

.PP
Definition at line 19 of file ConsoleEvents\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const COMMAND = 'console\&.command'"

.PP
Definition at line 33 of file ConsoleEvents\&.php\&.
.SS "const EXCEPTION = 'console\&.exception'"

.PP
Definition at line 60 of file ConsoleEvents\&.php\&.
.SS "const TERMINATE = 'console\&.terminate'"

.PP
Definition at line 46 of file ConsoleEvents\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
