.TH "ResourceNotFoundException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResourceNotFoundException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits RuntimeException, and \fBExceptionInterface\fP\&.
.SH "Detailed Description"
.PP 
The resource was not found\&.
.PP
This exception should trigger an HTTP 404 response in your application code\&.
.PP
\fBAuthor:\fP
.RS 4
Kris Wallsmith kris@symfony.com
.RE
.PP

.PP
Definition at line 23 of file ResourceNotFoundException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
