.TH "FlattenException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FlattenException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFlattenException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtoArray\fP ()"
.br
.ti -1c
.RI "\fBgetStatusCode\fP ()"
.br
.ti -1c
.RI "\fBsetStatusCode\fP ($code)"
.br
.ti -1c
.RI "\fBgetHeaders\fP ()"
.br
.ti -1c
.RI "\fBsetHeaders\fP (array $headers)"
.br
.ti -1c
.RI "\fBgetClass\fP ()"
.br
.ti -1c
.RI "\fBsetClass\fP ($class)"
.br
.ti -1c
.RI "\fBgetFile\fP ()"
.br
.ti -1c
.RI "\fBsetFile\fP ($file)"
.br
.ti -1c
.RI "\fBgetLine\fP ()"
.br
.ti -1c
.RI "\fBsetLine\fP ($\fBline\fP)"
.br
.ti -1c
.RI "\fBgetMessage\fP ()"
.br
.ti -1c
.RI "\fBsetMessage\fP ($message)"
.br
.ti -1c
.RI "\fBgetCode\fP ()"
.br
.ti -1c
.RI "\fBsetCode\fP ($code)"
.br
.ti -1c
.RI "\fBgetPrevious\fP ()"
.br
.ti -1c
.RI "\fBsetPrevious\fP (\fBFlattenException\fP $previous)"
.br
.ti -1c
.RI "\fBgetAllPrevious\fP ()"
.br
.ti -1c
.RI "\fBgetTrace\fP ()"
.br
.ti -1c
.RI "\fBsetTraceFromException\fP (\\Exception $exception)"
.br
.ti -1c
.RI "\fBsetTrace\fP ($trace, $file, $\fBline\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcreate\fP (\\Exception $exception, $statusCode=null, array $headers=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBFlattenException\fP wraps a \fBPHP\fP \fBException\fP to be able to serialize it\&.
.PP
Basically, this class removes all objects from the trace\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 64 of file FlattenException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static create (\\Exception $exception,  $statusCode = \fCnull\fP, array $headers = \fCarray()\fP)\fC [static]\fP"

.PP
Definition at line 76 of file FlattenException\&.php\&.
.SS "getAllPrevious ()"

.PP
Definition at line 198 of file FlattenException\&.php\&.
.SS "getClass ()"

.PP
Definition at line 138 of file FlattenException\&.php\&.
.SS "getCode ()"

.PP
Definition at line 178 of file FlattenException\&.php\&.
.SS "getFile ()"

.PP
Definition at line 148 of file FlattenException\&.php\&.
.SS "getHeaders ()"

.PP
Definition at line 128 of file FlattenException\&.php\&.
.SS "getLine ()"

.PP
Definition at line 158 of file FlattenException\&.php\&.
.SS "getMessage ()"

.PP
Definition at line 168 of file FlattenException\&.php\&.
.SS "getPrevious ()"

.PP
Definition at line 188 of file FlattenException\&.php\&.
.SS "getStatusCode ()"

.PP
Definition at line 118 of file FlattenException\&.php\&.
.SS "getTrace ()"

.PP
Definition at line 209 of file FlattenException\&.php\&.
.SS "setClass ( $class)"

.PP
Definition at line 143 of file FlattenException\&.php\&.
.SS "setCode ( $code)"

.PP
Definition at line 183 of file FlattenException\&.php\&.
.SS "setFile ( $file)"

.PP
Definition at line 153 of file FlattenException\&.php\&.
.SS "setHeaders (array $headers)"

.PP
Definition at line 133 of file FlattenException\&.php\&.
.SS "setLine ( $line)"

.PP
Definition at line 163 of file FlattenException\&.php\&.
.SS "setMessage ( $message)"

.PP
Definition at line 173 of file FlattenException\&.php\&.
.SS "setPrevious (\fBFlattenException\fP $previous)"

.PP
Definition at line 193 of file FlattenException\&.php\&.
.SS "setStatusCode ( $code)"

.PP
Definition at line 123 of file FlattenException\&.php\&.
.SS "setTrace ( $trace,  $file,  $line)"

.PP
Definition at line 219 of file FlattenException\&.php\&.
.SS "setTraceFromException (\\Exception $exception)"

.PP
Definition at line 214 of file FlattenException\&.php\&.
.SS "toArray ()"

.PP
Definition at line 104 of file FlattenException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
