.TH "IteratorTestCase" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IteratorTestCase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.PP
Inherited by \fBCustomFilterIteratorTest\fP, \fBFilecontentFilterIteratorTest\fP, \fBFilenameFilterIteratorTest\fP, \fBPathFilterIteratorTest\fP, \fBRealIteratorTestCase\fP, and \fBRecursiveDirectoryIteratorTest\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBassertIterator\fP ($expected,\\Traversable $iterator)"
.br
.ti -1c
.RI "\fBassertOrderedIterator\fP ($expected,\\Traversable $iterator)"
.br
.ti -1c
.RI "\fBassertOrderedIteratorForGroups\fP ($expected,\\Traversable $iterator)"
.br
.ti -1c
.RI "\fBassertIteratorInForeach\fP ($expected,\\Traversable $iterator)"
.br
.ti -1c
.RI "\fBassertOrderedIteratorInForeach\fP ($expected,\\Traversable $iterator)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file IteratorTestCase\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "assertIterator ( $expected, \\Traversable $iterator)\fC [protected]\fP"

.PP
Definition at line 16 of file IteratorTestCase\&.php\&.
.SS "assertIteratorInForeach ( $expected, \\Traversable $iterator)\fC [protected]\fP"
Same as \fBIteratorTestCase::assertIterator\fP with foreach usage\&.
.PP
\fBParameters:\fP
.RS 4
\fI$expected\fP 
.br
\fI$iterator\fP 
.RE
.PP

.PP
Definition at line 68 of file IteratorTestCase\&.php\&.
.SS "assertOrderedIterator ( $expected, \\Traversable $iterator)\fC [protected]\fP"

.PP
Definition at line 30 of file IteratorTestCase\&.php\&.
.SS "assertOrderedIteratorForGroups ( $expected, \\Traversable $iterator)\fC [protected]\fP"
Same as assertOrderedIterator, but checks the order of groups of array elements\&.
.PP
\fBParameters:\fP
.RS 4
\fI$expected\fP - an array of arrays\&. For any two subarrays $a and $b such that $a goes before $b in $expected, the method asserts that any element of $a goes before any element of $b in the sequence generated by $iterator 
.br
\fI$iterator\fP 
.RE
.PP

.PP
Definition at line 47 of file IteratorTestCase\&.php\&.
.SS "assertOrderedIteratorInForeach ( $expected, \\Traversable $iterator)\fC [protected]\fP"
Same as \fBIteratorTestCase::assertOrderedIterator\fP with foreach usage\&.
.PP
\fBParameters:\fP
.RS 4
\fI$expected\fP 
.br
\fI$iterator\fP 
.RE
.PP

.PP
Definition at line 88 of file IteratorTestCase\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
