.TH "TestWithDispatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestWithDispatcher \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBfoo\fP (\fBEvent\fP $\fBe\fP, $\fBname\fP, $dispatcher)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$name\fP"
.br
.ti -1c
.RI "\fB$dispatcher\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 329 of file AbstractEventDispatcherTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "foo (\fBEvent\fP $e,  $name,  $dispatcher)"

.PP
Definition at line 334 of file AbstractEventDispatcherTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$dispatcher"

.PP
Definition at line 332 of file AbstractEventDispatcherTest\&.php\&.
.SS "$\fBname\fP"

.PP
Definition at line 331 of file AbstractEventDispatcherTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
