.TH "ClonerInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClonerInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMockCloner\fP, and \fBAbstractCloner\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcloneVar\fP ($var)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Nicolas Grekas p@tchwork.com 
.RE
.PP

.PP
Definition at line 17 of file ClonerInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "cloneVar ( $var)"
Clones a \fBPHP\fP variable\&.
.PP
\fBParameters:\fP
.RS 4
\fI$var\fP Any \fBPHP\fP variable\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBData\fP The cloned variable represented by a \fBData\fP object\&. 
.RE
.PP

.PP
Implemented in \fBAbstractCloner\fP, and \fBMockCloner\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
