.TH "Symfony\Component\HttpKernel\DataCollector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\HttpKernel\DataCollector \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUtil\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBConfigDataCollector\fP"
.br
.ti -1c
.RI "class \fBDataCollector\fP"
.br
.ti -1c
.RI "interface \fBDataCollectorInterface\fP"
.br
.ti -1c
.RI "class \fBDumpDataCollector\fP"
.br
.ti -1c
.RI "class \fBEventDataCollector\fP"
.br
.ti -1c
.RI "class \fBExceptionDataCollector\fP"
.br
.ti -1c
.RI "interface \fBLateDataCollectorInterface\fP"
.br
.ti -1c
.RI "class \fBLoggerDataCollector\fP"
.br
.ti -1c
.RI "class \fBMemoryDataCollector\fP"
.br
.ti -1c
.RI "class \fBRequestDataCollector\fP"
.br
.ti -1c
.RI "class \fBRouterDataCollector\fP"
.br
.ti -1c
.RI "class \fBTimeDataCollector\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
