.TH "Symfony\Component\HttpKernel\Tests" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\HttpKernel\Tests \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBBundle\fP"
.br
.ti -1c
.RI " \fBCacheClearer\fP"
.br
.ti -1c
.RI " \fBCacheWarmer\fP"
.br
.ti -1c
.RI " \fBConfig\fP"
.br
.ti -1c
.RI " \fBController\fP"
.br
.ti -1c
.RI " \fBDataCollector\fP"
.br
.ti -1c
.RI " \fBDebug\fP"
.br
.ti -1c
.RI " \fBDependencyInjection\fP"
.br
.ti -1c
.RI " \fBEventListener\fP"
.br
.ti -1c
.RI " \fBFixtures\fP"
.br
.ti -1c
.RI " \fBFragment\fP"
.br
.ti -1c
.RI " \fBHttpCache\fP"
.br
.ti -1c
.RI " \fBProfiler\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClientTest\fP"
.br
.ti -1c
.RI "class \fBController\fP"
.br
.ti -1c
.RI "class \fBHttpKernelTest\fP"
.br
.ti -1c
.RI "class \fBKernelTest\fP"
.br
.ti -1c
.RI "class \fBLogger\fP"
.br
.ti -1c
.RI "class \fBTestHttpKernel\fP"
.br
.ti -1c
.RI "class \fBUriSignerTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcontroller_func\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Symfony\\Component\\HttpKernel\\Tests\\controller_func ()"

.PP
Definition at line 297 of file HttpKernelTest\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
