.TH "AuthenticationProviderInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthenticationProviderInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAuthenticationManagerInterface\fP\&.
.PP
Inherited by \fBAnonymousAuthenticationProvider\fP, \fBPreAuthenticatedAuthenticationProvider\fP, \fBRememberMeAuthenticationProvider\fP, \fBSimpleAuthenticationProvider\fP, and \fBUserAuthenticationProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsupports\fP (\fBTokenInterface\fP $token)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthenticationProviderInterface\fP is the interface for all authentication providers\&.
.PP
Concrete implementations processes specific \fBToken\fP instances\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 25 of file AuthenticationProviderInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "supports (\fBTokenInterface\fP $token)"
Checks whether this provider supports the given token\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP \fBA\fP TokenInterface instance
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the implementation supports the \fBToken\fP, false otherwise 
.RE
.PP

.PP
Implemented in \fBUserAuthenticationProvider\fP, \fBPreAuthenticatedAuthenticationProvider\fP, \fBRememberMeAuthenticationProvider\fP, \fBAnonymousAuthenticationProvider\fP, and \fBSimpleAuthenticationProvider\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
