.TH "InputArgument" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputArgument \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBname\fP, $mode=null, $description= '', $default=null)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBisRequired\fP ()"
.br
.ti -1c
.RI "\fBisArray\fP ()"
.br
.ti -1c
.RI "\fBsetDefault\fP ($default=null)"
.br
.ti -1c
.RI "\fBgetDefault\fP ()"
.br
.ti -1c
.RI "\fBgetDescription\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBREQUIRED\fP = 1"
.br
.ti -1c
.RI "const \fBOPTIONAL\fP = 2"
.br
.ti -1c
.RI "const \fBIS_ARRAY\fP = 4"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a command line argument\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 21 of file InputArgument\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $name,  $mode = \fCnull\fP,  $description = \fC''\fP,  $default = \fCnull\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The argument name 
.br
\fI$mode\fP The argument mode: self::REQUIRED or self::OPTIONAL 
.br
\fI$description\fP \fBA\fP description text 
.br
\fI$default\fP The default value (for self::OPTIONAL mode only)
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 44 of file InputArgument\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDefault ()"
Returns the default value\&.
.PP
\fBReturns:\fP
.RS 4
mixed The default value 
.RE
.PP

.PP
Definition at line 118 of file InputArgument\&.php\&.
.SS "getDescription ()"
Returns the description text\&.
.PP
\fBReturns:\fP
.RS 4
string The description text 
.RE
.PP

.PP
Definition at line 128 of file InputArgument\&.php\&.
.SS "getName ()"
Returns the argument name\&.
.PP
\fBReturns:\fP
.RS 4
string The argument name 
.RE
.PP

.PP
Definition at line 64 of file InputArgument\&.php\&.
.SS "isArray ()"
Returns true if the argument can take multiple values\&.
.PP
\fBReturns:\fP
.RS 4
bool true if mode is self::IS_ARRAY, false otherwise 
.RE
.PP

.PP
Definition at line 84 of file InputArgument\&.php\&.
.SS "isRequired ()"
Returns true if the argument is required\&.
.PP
\fBReturns:\fP
.RS 4
bool true if parameter mode is self::REQUIRED, false otherwise 
.RE
.PP

.PP
Definition at line 74 of file InputArgument\&.php\&.
.SS "setDefault ( $default = \fCnull\fP)"
Sets the default value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$default\fP The default value
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 96 of file InputArgument\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const IS_ARRAY = 4"

.PP
Definition at line 25 of file InputArgument\&.php\&.
.SS "const OPTIONAL = 2"

.PP
Definition at line 24 of file InputArgument\&.php\&.
.SS "const REQUIRED = 1"

.PP
Definition at line 23 of file InputArgument\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
