.TH "KernelEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KernelEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Event\&.
.PP
Inherited by \fBFilterControllerEvent\fP, \fBFilterResponseEvent\fP, \fBFinishRequestEvent\fP, and \fBGetResponseEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBHttpKernelInterface\fP $kernel, \fBRequest\fP $request, $requestType)"
.br
.ti -1c
.RI "\fBgetKernel\fP ()"
.br
.ti -1c
.RI "\fBgetRequest\fP ()"
.br
.ti -1c
.RI "\fBgetRequestType\fP ()"
.br
.ti -1c
.RI "\fBisMasterRequest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base class for events thrown in the \fBHttpKernel\fP component\&.
.PP
\fBAuthor:\fP
.RS 4
Bernhard Schussek bschussek@gmail.com
.RE
.PP

.PP
Definition at line 25 of file KernelEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBHttpKernelInterface\fP $kernel, \fBRequest\fP $request,  $requestType)"

.PP
Definition at line 49 of file KernelEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getKernel ()"
Returns the kernel in which this event was thrown\&.
.PP
\fBReturns:\fP
.RS 4
\fBHttpKernelInterface\fP
.RE
.PP

.PP
Definition at line 63 of file KernelEvent\&.php\&.
.SS "getRequest ()"
Returns the request the kernel is currently processing\&.
.PP
\fBReturns:\fP
.RS 4
\fBRequest\fP
.RE
.PP

.PP
Definition at line 75 of file KernelEvent\&.php\&.
.SS "getRequestType ()"
Returns the request type the kernel is currently processing\&.
.PP
\fBReturns:\fP
.RS 4
int \fBOne\fP of \fBHttpKernelInterface::MASTER_REQUEST\fP and \fBHttpKernelInterface::SUB_REQUEST\fP
.RE
.PP

.PP
Definition at line 88 of file KernelEvent\&.php\&.
.SS "isMasterRequest ()"
Checks if this is a master request\&.
.PP
\fBReturns:\fP
.RS 4
bool True if the request is a master request
.RE
.PP

.PP
Definition at line 100 of file KernelEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
