.TH "AbstractDescriptorTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractDescriptorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.PP
Inherited by \fBJsonDescriptorTest\fP, \fBMarkdownDescriptorTest\fP, \fBTextDescriptorTest\fP, and \fBXmlDescriptorTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestDescribeInputArgument\fP (\fBInputArgument\fP $argument, $expectedDescription)"
.br
.ti -1c
.RI "\fBtestDescribeInputOption\fP (\fBInputOption\fP $option, $expectedDescription)"
.br
.ti -1c
.RI "\fBtestDescribeInputDefinition\fP (\fBInputDefinition\fP $definition, $expectedDescription)"
.br
.ti -1c
.RI "\fBtestDescribeCommand\fP (\fBCommand\fP $command, $expectedDescription)"
.br
.ti -1c
.RI "\fBtestDescribeApplication\fP (\fBApplication\fP $application, $expectedDescription)"
.br
.ti -1c
.RI "\fBgetDescribeInputArgumentTestData\fP ()"
.br
.ti -1c
.RI "\fBgetDescribeInputOptionTestData\fP ()"
.br
.ti -1c
.RI "\fBgetDescribeInputDefinitionTestData\fP ()"
.br
.ti -1c
.RI "\fBgetDescribeCommandTestData\fP ()"
.br
.ti -1c
.RI "\fBgetDescribeApplicationTestData\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetDescriptor\fP ()"
.br
.ti -1c
.RI "\fBgetFormat\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file AbstractDescriptorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDescribeApplicationTestData ()"

.PP
Definition at line 80 of file AbstractDescriptorTest\&.php\&.
.SS "getDescribeCommandTestData ()"

.PP
Definition at line 75 of file AbstractDescriptorTest\&.php\&.
.SS "getDescribeInputArgumentTestData ()"

.PP
Definition at line 60 of file AbstractDescriptorTest\&.php\&.
.SS "getDescribeInputDefinitionTestData ()"

.PP
Definition at line 70 of file AbstractDescriptorTest\&.php\&.
.SS "getDescribeInputOptionTestData ()"

.PP
Definition at line 65 of file AbstractDescriptorTest\&.php\&.
.SS "getDescriptor ()\fC [abstract]\fP, \fC [protected]\fP"

.SS "getFormat ()\fC [abstract]\fP, \fC [protected]\fP"

.SS "testDescribeApplication (\fBApplication\fP $application,  $expectedDescription)"
getDescribeApplicationTestData 
.PP
Definition at line 48 of file AbstractDescriptorTest\&.php\&.
.SS "testDescribeCommand (\fBCommand\fP $command,  $expectedDescription)"
getDescribeCommandTestData 
.PP
Definition at line 42 of file AbstractDescriptorTest\&.php\&.
.SS "testDescribeInputArgument (\fBInputArgument\fP $argument,  $expectedDescription)"
getDescribeInputArgumentTestData 
.PP
Definition at line 24 of file AbstractDescriptorTest\&.php\&.
.SS "testDescribeInputDefinition (\fBInputDefinition\fP $definition,  $expectedDescription)"
getDescribeInputDefinitionTestData 
.PP
Definition at line 36 of file AbstractDescriptorTest\&.php\&.
.SS "testDescribeInputOption (\fBInputOption\fP $option,  $expectedDescription)"
getDescribeInputOptionTestData 
.PP
Definition at line 30 of file AbstractDescriptorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
