.TH "TraceableEventDispatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraceableEventDispatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTraceableEventDispatcherInterface\fP\&.
.PP
Inherited by \fBTraceableEventDispatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBEventDispatcherInterface\fP $dispatcher, Stopwatch $stopwatch, \fBLoggerInterface\fP $logger=null)"
.br
.ti -1c
.RI "\fBaddListener\fP ($eventName, $listener, $priority=0)"
.br
.ti -1c
.RI "\fBaddSubscriber\fP (EventSubscriberInterface $subscriber)"
.br
.ti -1c
.RI "\fBremoveListener\fP ($eventName, $listener)"
.br
.ti -1c
.RI "\fBremoveSubscriber\fP (EventSubscriberInterface $subscriber)"
.br
.ti -1c
.RI "\fBgetListeners\fP ($eventName=null)"
.br
.ti -1c
.RI "\fBhasListeners\fP ($eventName=null)"
.br
.ti -1c
.RI "\fBdispatch\fP ($eventName, \fBEvent\fP $\fBevent\fP=null)"
.br
.ti -1c
.RI "\fBgetCalledListeners\fP ()"
.br
.ti -1c
.RI "\fBgetNotCalledListeners\fP ()"
.br
.ti -1c
.RI "\fB__call\fP ($method, $arguments)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBpreDispatch\fP ($eventName, \fBEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBpostDispatch\fP ($eventName, \fBEvent\fP $\fBevent\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$logger\fP"
.br
.ti -1c
.RI "\fB$stopwatch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Collects some data about event listeners\&.
.PP
This event dispatcher delegates the dispatching to another one\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 27 of file TraceableEventDispatcher\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBEventDispatcherInterface\fP $dispatcher, Stopwatch $stopwatch, \fBLoggerInterface\fP $logger = \fCnull\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$dispatcher\fP An \fBEventDispatcherInterface\fP instance 
.br
\fI$stopwatch\fP \fBA\fP Stopwatch instance 
.br
\fI$logger\fP \fBA\fP LoggerInterface instance 
.RE
.PP

.PP
Definition at line 42 of file TraceableEventDispatcher\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__call ( $method,  $arguments)"
Proxies all method calls to the original event dispatcher\&.
.PP
\fBParameters:\fP
.RS 4
\fI$method\fP The method name 
.br
\fI$arguments\fP The method arguments
.RE
.PP
\fBReturns:\fP
.RS 4
mixed 
.RE
.PP

.PP
Definition at line 188 of file TraceableEventDispatcher\&.php\&.
.SS "addListener ( $eventName,  $listener,  $priority = \fC0\fP)"
{Adds an event listener that listens on the specified events\&.
.PP
\fBParameters:\fP
.RS 4
\fI$eventName\fP The event to listen on 
.br
\fI$listener\fP The listener 
.br
\fI$priority\fP The higher this value, the earlier an event listener will be triggered in the chain (defaults to 0)
.RE
.PP
} 
.PP
Implements \fBEventDispatcherInterface\fP\&.
.PP
Definition at line 53 of file TraceableEventDispatcher\&.php\&.
.SS "addSubscriber (EventSubscriberInterface $subscriber)"
{Adds an event subscriber\&.
.PP
The subscriber is asked for all the events he is interested in and added as a listener for these events\&.
.PP
\fBParameters:\fP
.RS 4
\fI$subscriber\fP The subscriber\&.
.RE
.PP
} 
.PP
Implements \fBEventDispatcherInterface\fP\&.
.PP
Definition at line 61 of file TraceableEventDispatcher\&.php\&.
.SS "dispatch ( $eventName, \fBEvent\fP $event = \fCnull\fP)"
{Dispatches an event to all registered listeners\&.
.PP
\fBParameters:\fP
.RS 4
\fI$eventName\fP The name of the event to dispatch\&. The name of the event is the name of the method that is invoked on listeners\&. 
.br
\fI$event\fP The event to pass to the event handlers/listeners\&. If not supplied, an empty \fBEvent\fP instance is created\&.
.RE
.PP
\fBReturns:\fP
.RS 4
\fBEvent\fP
.RE
.PP
} 
.PP
Implements \fBEventDispatcherInterface\fP\&.
.PP
Definition at line 101 of file TraceableEventDispatcher\&.php\&.
.SS "getCalledListeners ()"
{Gets the called listeners\&.
.PP
\fBReturns:\fP
.RS 4
array An array of called listeners
.RE
.PP
} 
.PP
Implements \fBTraceableEventDispatcherInterface\fP\&.
.PP
Definition at line 127 of file TraceableEventDispatcher\&.php\&.
.SS "getListeners ( $eventName = \fCnull\fP)"
{Gets the listeners of a specific event or all listeners\&.
.PP
\fBParameters:\fP
.RS 4
\fI$eventName\fP The name of the event
.RE
.PP
\fBReturns:\fP
.RS 4
array The event listeners for the specified event, or all event listeners by event name
.RE
.PP
} 
.PP
Implements \fBEventDispatcherInterface\fP\&.
.PP
Definition at line 85 of file TraceableEventDispatcher\&.php\&.
.SS "getNotCalledListeners ()"
{Gets the not called listeners\&.
.PP
\fBReturns:\fP
.RS 4
array An array of not called listeners
.RE
.PP
} 
.PP
Implements \fBTraceableEventDispatcherInterface\fP\&.
.PP
Definition at line 143 of file TraceableEventDispatcher\&.php\&.
.SS "hasListeners ( $eventName = \fCnull\fP)"
{Checks whether an event has any registered listeners\&.
.PP
\fBParameters:\fP
.RS 4
\fI$eventName\fP The name of the event
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the specified event has any listeners, false otherwise
.RE
.PP
} 
.PP
Implements \fBEventDispatcherInterface\fP\&.
.PP
Definition at line 93 of file TraceableEventDispatcher\&.php\&.
.SS "postDispatch ( $eventName, \fBEvent\fP $event)\fC [protected]\fP"
Called after dispatching the event\&.
.PP
\fBParameters:\fP
.RS 4
\fI$eventName\fP The event name 
.br
\fI$event\fP The event 
.RE
.PP

.PP
Definition at line 209 of file TraceableEventDispatcher\&.php\&.
.SS "preDispatch ( $eventName, \fBEvent\fP $event)\fC [protected]\fP"
Called before dispatching the event\&.
.PP
\fBParameters:\fP
.RS 4
\fI$eventName\fP The event name 
.br
\fI$event\fP The event 
.RE
.PP

.PP
Definition at line 199 of file TraceableEventDispatcher\&.php\&.
.SS "removeListener ( $eventName,  $listener)"
{Removes an event listener from the specified events\&.
.PP
\fBParameters:\fP
.RS 4
\fI$eventName\fP The event to remove a listener from 
.br
\fI$listener\fP The listener to remove
.RE
.PP
} 
.PP
Implements \fBEventDispatcherInterface\fP\&.
.PP
Definition at line 69 of file TraceableEventDispatcher\&.php\&.
.SS "removeSubscriber (EventSubscriberInterface $subscriber)"
{Removes an event subscriber\&.
.PP
\fBParameters:\fP
.RS 4
\fI$subscriber\fP The subscriber
.RE
.PP
} 
.PP
Implements \fBEventDispatcherInterface\fP\&.
.PP
Definition at line 77 of file TraceableEventDispatcher\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$logger\fC [protected]\fP"

.PP
Definition at line 29 of file TraceableEventDispatcher\&.php\&.
.SS "$stopwatch\fC [protected]\fP"

.PP
Definition at line 30 of file TraceableEventDispatcher\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
