.TH "AuthenticationEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthenticationEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Event\&.
.PP
Inherited by \fBAuthenticationFailureEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBTokenInterface\fP $token)"
.br
.ti -1c
.RI "\fBgetAuthenticationToken\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This is a general purpose authentication event\&.
.PP
\fBAuthor:\fP
.RS 4
Johannes M\&. Schmitt schmittjoh@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file AuthenticationEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBTokenInterface\fP $token)"

.PP
Definition at line 26 of file AuthenticationEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getAuthenticationToken ()"

.PP
Definition at line 31 of file AuthenticationEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
