.TH "RoleVoter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoleVoter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBVoterInterface\fP\&.
.PP
Inherited by \fBRoleHierarchyVoter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($prefix= 'ROLE_')"
.br
.ti -1c
.RI "\fBsupportsAttribute\fP ($\fBattribute\fP)"
.br
.ti -1c
.RI "\fBsupportsClass\fP ($class)"
.br
.ti -1c
.RI "\fBvote\fP (\fBTokenInterface\fP $token, $object, array $attributes)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBextractRoles\fP (\fBTokenInterface\fP $token)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBRoleVoter\fP votes if any attribute starts with a given prefix\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 21 of file RoleVoter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $prefix = \fC'ROLE_'\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$prefix\fP The role prefix 
.RE
.PP

.PP
Definition at line 30 of file RoleVoter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "extractRoles (\fBTokenInterface\fP $token)\fC [protected]\fP"

.PP
Definition at line 75 of file RoleVoter\&.php\&.
.SS "supportsAttribute ( $attribute)"
{Checks if the voter supports the given attribute\&.
.PP
\fBParameters:\fP
.RS 4
\fI$attribute\fP An attribute
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if this \fBVoter\fP supports the attribute, false otherwise
.RE
.PP
} 
.PP
Implements \fBVoterInterface\fP\&.
.PP
Definition at line 38 of file RoleVoter\&.php\&.
.SS "supportsClass ( $class)"
{Checks if the voter supports the given class\&.
.PP
\fBParameters:\fP
.RS 4
\fI$class\fP \fBA\fP class name
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if this \fBVoter\fP can process the class
.RE
.PP
} 
.PP
Implements \fBVoterInterface\fP\&.
.PP
Definition at line 46 of file RoleVoter\&.php\&.
.SS "vote (\fBTokenInterface\fP $token,  $object, array $attributes)"
{Returns the vote for the given parameters\&.
.PP
This method must return one of the following constants: ACCESS_GRANTED, ACCESS_DENIED, or ACCESS_ABSTAIN\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP \fBA\fP TokenInterface instance 
.br
\fI$object\fP The object to secure 
.br
\fI$attributes\fP An array of attributes associated with the method being invoked
.RE
.PP
\fBReturns:\fP
.RS 4
int either ACCESS_GRANTED, ACCESS_ABSTAIN, or ACCESS_DENIED
.RE
.PP
} 
.PP
Implements \fBVoterInterface\fP\&.
.PP
Definition at line 54 of file RoleVoter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
