.TH "MergeExtensionConfigurationPass" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MergeExtensionConfigurationPass \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseMergeExtensionConfigurationPass\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $extensions)"
.br
.ti -1c
.RI "\fBprocess\fP (ContainerBuilder $container)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Ensures certain extensions are always loaded\&.
.PP
\fBAuthor:\fP
.RS 4
Kris Wallsmith kris@symfony.com 
.RE
.PP

.PP
Definition at line 22 of file MergeExtensionConfigurationPass\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $extensions)"

.PP
Definition at line 26 of file MergeExtensionConfigurationPass\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "process (ContainerBuilder $container)"

.PP
Definition at line 31 of file MergeExtensionConfigurationPass\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
