.TH "DoctrineCaster" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DoctrineCaster \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcastCommonProxy\fP (CommonProxy $proxy, array $\fBa\fP, \fBStub\fP $stub, $isNested)"
.br
.ti -1c
.RI "static \fBcastOrmProxy\fP (OrmProxy $proxy, array $\fBa\fP, \fBStub\fP $stub, $isNested)"
.br
.ti -1c
.RI "static \fBcastPersistentCollection\fP (PersistentCollection $coll, array $\fBa\fP, \fBStub\fP $stub, $isNested)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Casts \fBDoctrine\fP related classes to array representation\&.
.PP
\fBAuthor:\fP
.RS 4
Nicolas Grekas p@tchwork.com 
.RE
.PP

.PP
Definition at line 24 of file DoctrineCaster\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static castCommonProxy (CommonProxy $proxy, array $a, \fBStub\fP $stub,  $isNested)\fC [static]\fP"

.PP
Definition at line 26 of file DoctrineCaster\&.php\&.
.SS "static castOrmProxy (OrmProxy $proxy, array $a, \fBStub\fP $stub,  $isNested)\fC [static]\fP"

.PP
Definition at line 37 of file DoctrineCaster\&.php\&.
.SS "static castPersistentCollection (PersistentCollection $coll, array $a, \fBStub\fP $stub,  $isNested)\fC [static]\fP"

.PP
Definition at line 49 of file DoctrineCaster\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
