.TH "SessionUnavailableException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SessionUnavailableException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAuthenticationException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMessageKey\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This exception is thrown when no session is available\&.
.PP
Possible reasons for this are: 
.PP
.nf
a) The session timed out because the user waited too long.
b) The user has disabled cookies, and a new session is started on each
   request.

.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Johannes M\&. Schmitt schmittjoh@gmail.com 
.PP
Alexander iam.asm89@gmail.com 
.RE
.PP

.PP
Definition at line 26 of file SessionUnavailableException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getMessageKey ()"
{} 
.PP
Definition at line 31 of file SessionUnavailableException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
