.TH "TestEventDispatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestEventDispatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventDispatcher, and \fBTraceableEventDispatcherInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetCalledListeners\fP ()"
.br
.ti -1c
.RI "\fBgetNotCalledListeners\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file TestEventDispatcher\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getCalledListeners ()"
Gets the called listeners\&.
.PP
\fBReturns:\fP
.RS 4
array An array of called listeners 
.RE
.PP

.PP
Implements \fBTraceableEventDispatcherInterface\fP\&.
.PP
Definition at line 19 of file TestEventDispatcher\&.php\&.
.SS "getNotCalledListeners ()"
Gets the not called listeners\&.
.PP
\fBReturns:\fP
.RS 4
array An array of not called listeners 
.RE
.PP

.PP
Implements \fBTraceableEventDispatcherInterface\fP\&.
.PP
Definition at line 24 of file TestEventDispatcher\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
