.TH "UrlMatcherTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UrlMatcherTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestNoMethodSoAllowed\fP ()"
.br
.ti -1c
.RI "\fBtestMethodNotAllowed\fP ()"
.br
.ti -1c
.RI "\fBtestHeadAllowedWhenRequirementContainsGet\fP ()"
.br
.ti -1c
.RI "\fBtestMethodNotAllowedAggregatesAllowedMethods\fP ()"
.br
.ti -1c
.RI "\fBtestMatch\fP ()"
.br
.ti -1c
.RI "\fBtestMatchWithPrefixes\fP ()"
.br
.ti -1c
.RI "\fBtestMatchWithDynamicPrefix\fP ()"
.br
.ti -1c
.RI "\fBtestMatchSpecialRouteName\fP ()"
.br
.ti -1c
.RI "\fBtestMatchNonAlpha\fP ()"
.br
.ti -1c
.RI "\fBtestMatchWithDotMetacharacterInRequirements\fP ()"
.br
.ti -1c
.RI "\fBtestMatchOverriddenRoute\fP ()"
.br
.ti -1c
.RI "\fBtestMatchRegression\fP ()"
.br
.ti -1c
.RI "\fBtestDefaultRequirementForOptionalVariables\fP ()"
.br
.ti -1c
.RI "\fBtestMatchingIsEager\fP ()"
.br
.ti -1c
.RI "\fBtestAdjacentVariables\fP ()"
.br
.ti -1c
.RI "\fBtestOptionalVariableWithNoRealSeparator\fP ()"
.br
.ti -1c
.RI "\fBtestRequiredVariableWithNoRealSeparator\fP ()"
.br
.ti -1c
.RI "\fBtestDefaultRequirementOfVariable\fP ()"
.br
.ti -1c
.RI "\fBtestDefaultRequirementOfVariableDisallowsSlash\fP ()"
.br
.ti -1c
.RI "\fBtestDefaultRequirementOfVariableDisallowsNextSeparator\fP ()"
.br
.ti -1c
.RI "\fBtestSchemeRequirementBC\fP ()"
.br
.ti -1c
.RI "\fBtestSchemeRequirement\fP ()"
.br
.ti -1c
.RI "\fBtestCondition\fP ()"
.br
.ti -1c
.RI "\fBtestDecodeOnce\fP ()"
.br
.ti -1c
.RI "\fBtestCannotRelyOnPrefix\fP ()"
.br
.ti -1c
.RI "\fBtestWithHost\fP ()"
.br
.ti -1c
.RI "\fBtestWithHostOnRouteCollection\fP ()"
.br
.ti -1c
.RI "\fBtestWithOutHostHostDoesNotMatch\fP ()"
.br
.ti -1c
.RI "\fBtestPathIsCaseSensitive\fP ()"
.br
.ti -1c
.RI "\fBtestHostIsCaseInsensitive\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 21 of file UrlMatcherTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAdjacentVariables ()"

.PP
Definition at line 238 of file UrlMatcherTest\&.php\&.
.SS "testCannotRelyOnPrefix ()"

.PP
Definition at line 358 of file UrlMatcherTest\&.php\&.
.SS "testCondition ()"

.PP
Definition at line 339 of file UrlMatcherTest\&.php\&.
.SS "testDecodeOnce ()"

.PP
Definition at line 349 of file UrlMatcherTest\&.php\&.
.SS "testDefaultRequirementForOptionalVariables ()"

.PP
Definition at line 220 of file UrlMatcherTest\&.php\&.
.SS "testDefaultRequirementOfVariable ()"

.PP
Definition at line 282 of file UrlMatcherTest\&.php\&.
.SS "testDefaultRequirementOfVariableDisallowsNextSeparator ()"

.PP
Definition at line 306 of file UrlMatcherTest\&.php\&.
.SS "testDefaultRequirementOfVariableDisallowsSlash ()"

.PP
Definition at line 294 of file UrlMatcherTest\&.php\&.
.SS "testHeadAllowedWhenRequirementContainsGet ()"

.PP
Definition at line 47 of file UrlMatcherTest\&.php\&.
.SS "testHostIsCaseInsensitive ()"

.PP
Definition at line 421 of file UrlMatcherTest\&.php\&.
.SS "testMatch ()"

.PP
Definition at line 72 of file UrlMatcherTest\&.php\&.
.SS "testMatchingIsEager ()"

.PP
Definition at line 229 of file UrlMatcherTest\&.php\&.
.SS "testMatchNonAlpha ()"

.PP
Definition at line 164 of file UrlMatcherTest\&.php\&.
.SS "testMatchOverriddenRoute ()"

.PP
Definition at line 184 of file UrlMatcherTest\&.php\&.
.SS "testMatchRegression ()"

.PP
Definition at line 201 of file UrlMatcherTest\&.php\&.
.SS "testMatchSpecialRouteName ()"

.PP
Definition at line 155 of file UrlMatcherTest\&.php\&.
.SS "testMatchWithDotMetacharacterInRequirements ()"

.PP
Definition at line 175 of file UrlMatcherTest\&.php\&.
.SS "testMatchWithDynamicPrefix ()"

.PP
Definition at line 144 of file UrlMatcherTest\&.php\&.
.SS "testMatchWithPrefixes ()"

.PP
Definition at line 133 of file UrlMatcherTest\&.php\&.
.SS "testMethodNotAllowed ()"

.PP
Definition at line 32 of file UrlMatcherTest\&.php\&.
.SS "testMethodNotAllowedAggregatesAllowedMethods ()"

.PP
Definition at line 56 of file UrlMatcherTest\&.php\&.
.SS "testNoMethodSoAllowed ()"

.PP
Definition at line 23 of file UrlMatcherTest\&.php\&.
.SS "testOptionalVariableWithNoRealSeparator ()"

.PP
Definition at line 258 of file UrlMatcherTest\&.php\&.
.SS "testPathIsCaseSensitive ()"

.PP
Definition at line 412 of file UrlMatcherTest\&.php\&.
.SS "testRequiredVariableWithNoRealSeparator ()"

.PP
Definition at line 273 of file UrlMatcherTest\&.php\&.
.SS "testSchemeRequirement ()"

.PP
Definition at line 328 of file UrlMatcherTest\&.php\&.
.SS "testSchemeRequirementBC ()"

.PP
Definition at line 318 of file UrlMatcherTest\&.php\&.
.SS "testWithHost ()"

.PP
Definition at line 374 of file UrlMatcherTest\&.php\&.
.SS "testWithHostOnRouteCollection ()"

.PP
Definition at line 383 of file UrlMatcherTest\&.php\&.
.SS "testWithOutHostHostDoesNotMatch ()"

.PP
Definition at line 400 of file UrlMatcherTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
