.TH "Expression" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Expression \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValueInterface\fP, and \fBValueInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($expr)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBrender\fP ()"
.br
.ti -1c
.RI "\fBrenderPattern\fP ()"
.br
.ti -1c
.RI "\fBisCaseSensitive\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBprepend\fP ($expr)"
.br
.ti -1c
.RI "\fBappend\fP ($expr)"
.br
.ti -1c
.RI "\fBisRegex\fP ()"
.br
.ti -1c
.RI "\fBisGlob\fP ()"
.br
.ti -1c
.RI "\fBgetGlob\fP ()"
.br
.ti -1c
.RI "\fBgetRegex\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP ($expr)"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBrender\fP ()"
.br
.ti -1c
.RI "\fBrenderPattern\fP ()"
.br
.ti -1c
.RI "\fBisCaseSensitive\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBprepend\fP ($expr)"
.br
.ti -1c
.RI "\fBappend\fP ($expr)"
.br
.ti -1c
.RI "\fBisRegex\fP ()"
.br
.ti -1c
.RI "\fBisGlob\fP ()"
.br
.ti -1c
.RI "\fBgetGlob\fP ()"
.br
.ti -1c
.RI "\fBgetRegex\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcreate\fP ($expr)"
.br
.ti -1c
.RI "static \fBcreate\fP ($expr)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBTYPE_REGEX\fP = 1"
.br
.ti -1c
.RI "const \fBTYPE_GLOB\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jean-François Simon contact@jfsimon.fr 
.RE
.PP

.PP
Definition at line 15251 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $expr)"

.PP
Definition at line 15260 of file compiled\&.php\&.
.SS "__construct ( $expr)"

.PP
\fBParameters:\fP
.RS 4
\fI$expr\fP 
.RE
.PP

.PP
Definition at line 40 of file Expression\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"

.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 52 of file Expression\&.php\&.
.SS "__toString ()"

.PP
Definition at line 15268 of file compiled\&.php\&.
.SS "append ( $expr)"
{} 
.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 102 of file Expression\&.php\&.
.SS "append ( $expr)"

.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 15293 of file compiled\&.php\&.
.SS "static create ( $expr)\fC [static]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI$expr\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBExpression\fP 
.RE
.PP

.PP
Definition at line 32 of file Expression\&.php\&.
.SS "static create ( $expr)\fC [static]\fP"

.PP
Definition at line 15256 of file compiled\&.php\&.
.SS "getGlob ()"

.PP
\fBExceptions:\fP
.RS 4
\fI\fP 
.RE
.PP

.PP
Definition at line 130 of file Expression\&.php\&.
.SS "getGlob ()"

.PP
Definition at line 15306 of file compiled\&.php\&.
.SS "getRegex ()"

.PP
\fBReturns:\fP
.RS 4
\fBRegex\fP 
.RE
.PP

.PP
Definition at line 142 of file Expression\&.php\&.
.SS "getRegex ()"

.PP
Definition at line 15313 of file compiled\&.php\&.
.SS "getType ()"

.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 84 of file Expression\&.php\&.
.SS "getType ()"

.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 15284 of file compiled\&.php\&.
.SS "isCaseSensitive ()"

.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 76 of file Expression\&.php\&.
.SS "isCaseSensitive ()"

.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 15280 of file compiled\&.php\&.
.SS "isGlob ()"

.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 120 of file Expression\&.php\&.
.SS "isGlob ()"

.PP
Definition at line 15302 of file compiled\&.php\&.
.SS "isRegex ()"

.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 112 of file Expression\&.php\&.
.SS "isRegex ()"

.PP
Definition at line 15298 of file compiled\&.php\&.
.SS "prepend ( $expr)"
{} 
.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 92 of file Expression\&.php\&.
.SS "prepend ( $expr)"

.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 15288 of file compiled\&.php\&.
.SS "render ()"
{} 
.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 60 of file Expression\&.php\&.
.SS "render ()"

.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 15272 of file compiled\&.php\&.
.SS "renderPattern ()"
{} 
.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 68 of file Expression\&.php\&.
.SS "renderPattern ()"

.PP
Implements \fBValueInterface\fP\&.
.PP
Definition at line 15276 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const TYPE_GLOB = 2"

.PP
Definition at line 15254 of file compiled\&.php\&.
.SS "const TYPE_REGEX = 1"

.PP
Definition at line 15253 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
