.TH "FragmentHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FragmentHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestRenderWhenRendererDoesNotExist\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithUnknownRenderer\fP ()"
.br
.ti -1c
.RI "\fBtestDeliverWithUnsuccessfulResponse\fP ()"
.br
.ti -1c
.RI "\fBtestRender\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBgetHandler\fP ($\fBreturnValue\fP, $arguments=array())"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file FragmentHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getHandler ( $returnValue,  $arguments = \fCarray()\fP)\fC [protected]\fP"

.PP
Definition at line 72 of file FragmentHandlerTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 22 of file FragmentHandlerTest\&.php\&.
.SS "testDeliverWithUnsuccessfulResponse ()"
\fBError\fP when rendering 'http://localhost/' (Status code is 404)\&. 
.PP
Definition at line 58 of file FragmentHandlerTest\&.php\&.
.SS "testRender ()"

.PP
Definition at line 65 of file FragmentHandlerTest\&.php\&.
.SS "testRenderWhenRendererDoesNotExist ()"

.PP
Definition at line 38 of file FragmentHandlerTest\&.php\&.
.SS "testRenderWithUnknownRenderer ()"

.PP
Definition at line 47 of file FragmentHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
