.TH "TerminableInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TerminableInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHttpCache\fP, \fBHttpKernel\fP, and \fBKernel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBterminate\fP (\fBRequest\fP $request, \fBResponse\fP $response)"
.br
.ti -1c
.RI "\fBterminate\fP (\fBRequest\fP $request, \fBResponse\fP $response)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Terminable extends the \fBKernel\fP request/response cycle with dispatching a post response event after sending the response and before shutting down the kernel\&.
.PP
\fBAuthor:\fP
.RS 4
Jordi Boggiano j.boggiano@seld.be 
.PP
Pierre Minnieur pierre.minnieur@sensiolabs.de
.RE
.PP

.PP
Definition at line 1251 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "terminate (\fBRequest\fP $request, \fBResponse\fP $response)"
Terminates a request/response cycle\&.
.PP
Should be called after sending the response and before shutting down the kernel\&.
.PP
\fBParameters:\fP
.RS 4
\fI$request\fP \fBA\fP \fBRequest\fP instance 
.br
\fI$response\fP \fBA\fP \fBResponse\fP instance
.RE
.PP

.PP
Implemented in \fBHttpCache\fP, \fBKernel\fP, and \fBHttpKernel\fP\&.
.SS "terminate (\fBRequest\fP $request, \fBResponse\fP $response)"

.PP
Implemented in \fBHttpCache\fP, \fBKernel\fP, and \fBHttpKernel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
