.TH "DebugFormatterHelper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DebugFormatterHelper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHelper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstart\fP ($id, $message, $prefix= 'RUN')"
.br
.ti -1c
.RI "\fBprogress\fP ($id, $buffer, $error=false, $prefix= 'OUT', $errorPrefix= 'ERR')"
.br
.ti -1c
.RI "\fBstop\fP ($id, $message, $successful, $prefix= 'RES')"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Helps outputting debug information when running an external program from a command\&.
.PP
An external program can be a \fBProcess\fP, an HTTP request, or anything else\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 21 of file DebugFormatterHelper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getName ()"
{Returns the canonical name of this helper\&.
.PP
\fBReturns:\fP
.RS 4
string The canonical name
.RE
.PP
} 
.PP
Implements \fBHelperInterface\fP\&.
.PP
Definition at line 123 of file DebugFormatterHelper\&.php\&.
.SS "progress ( $id,  $buffer,  $error = \fCfalse\fP,  $prefix = \fC'OUT'\fP,  $errorPrefix = \fC'ERR'\fP)"
Adds progress to a formatting session
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP The id of the formatting session 
.br
\fI$buffer\fP The message to display 
.br
\fI$error\fP Whether to consider the buffer as error 
.br
\fI$prefix\fP The prefix for output 
.br
\fI$errorPrefix\fP The prefix for error output
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 54 of file DebugFormatterHelper\&.php\&.
.SS "start ( $id,  $message,  $prefix = \fC'RUN'\fP)"
Starts a debug formatting session
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP The id of the formatting session 
.br
\fI$message\fP The message to display 
.br
\fI$prefix\fP The prefix to use
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 36 of file DebugFormatterHelper\&.php\&.
.SS "stop ( $id,  $message,  $successful,  $prefix = \fC'RES'\fP)"
Stops a formatting session
.PP
\fBParameters:\fP
.RS 4
\fI$id\fP The id of the formatting session 
.br
\fI$message\fP The message to display 
.br
\fI$successful\fP Whether to consider the result as success 
.br
\fI$prefix\fP The prefix for the end output
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 95 of file DebugFormatterHelper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
