.TH "StringUtils" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StringUtils \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBequals\fP ($knownString, $userInput)"
.br
.ti -1c
.RI "static \fBsafeStrlen\fP ($string)"
.br
.ti -1c
.RI "static \fBequals\fP ($knownString, $userInput)"
.br
.ti -1c
.RI "static \fBsafeStrlen\fP ($string)"
.br
.in -1c
.SH "Detailed Description"
.PP 
String utility functions\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 14949 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static equals ( $knownString,  $userInput)\fC [static]\fP"
Compares two strings\&.
.PP
This method implements a constant-time algorithm to compare strings\&. Regardless of the used implementation, it will leak length information\&.
.PP
\fBParameters:\fP
.RS 4
\fI$knownString\fP The string of known length to compare against 
.br
\fI$userInput\fP The string that the user can control
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the two strings are the same, false otherwise 
.RE
.PP

.PP
Definition at line 39 of file StringUtils\&.php\&.
.SS "static equals ( $knownString,  $userInput)\fC [static]\fP"

.PP
Definition at line 14954 of file compiled\&.php\&.
.SS "static safeStrlen ( $string)\fC [static]\fP"
Returns the number of bytes in a string\&.
.PP
\fBParameters:\fP
.RS 4
\fI$string\fP The string whose length we wish to obtain
.RE
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 78 of file StringUtils\&.php\&.
.SS "static safeStrlen ( $string)\fC [static]\fP"

.PP
Definition at line 14976 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
