.TH "DataDumperInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataDumperInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDumpDataCollector\fP, \fBMockDumper\fP, and \fBAbstractDumper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdump\fP (\fBData\fP $\fBdata\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDataDumperInterface\fP for dumping Data objects\&.
.PP
\fBAuthor:\fP
.RS 4
Nicolas Grekas p@tchwork.com 
.RE
.PP

.PP
Definition at line 21 of file DataDumperInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "dump (\fBData\fP $data)"
Dumps a Data object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$data\fP \fBA\fP Data object\&. 
.RE
.PP

.PP
Implemented in \fBMockDumper\fP, and \fBDumpDataCollector\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
