.TH "DescriptorInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DescriptorInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDescriptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdescribe\fP (\fBOutputInterface\fP $output, $object, array $\fBoptions\fP=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDescriptor\fP interface\&.
.PP
\fBAuthor:\fP
.RS 4
Jean-François Simon contact@jfsimon.fr 
.RE
.PP

.PP
Definition at line 21 of file DescriptorInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "describe (\fBOutputInterface\fP $output,  $object, array $options = \fCarray()\fP)"
Describes an InputArgument instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$output\fP 
.br
\fI$object\fP 
.br
\fI$options\fP 
.RE
.PP

.PP
Implemented in \fBDescriptor\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
