.TH "OperationNotPermitedException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OperationNotPermitedException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAdapterFailureException\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jean-François Simon contact@jfsimon.fr 
.RE
.PP

.PP
Definition at line 17 of file OperationNotPermitedException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
