.TH "JsonResponseTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonResponseTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructorEmptyCreatesJsonObject\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorWithArrayCreatesJsonArray\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorWithAssocArrayCreatesJsonObject\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorWithSimpleTypes\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorWithCustomStatus\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorAddsContentTypeHeader\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorWithCustomHeaders\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorWithCustomContentType\fP ()"
.br
.ti -1c
.RI "\fBtestCreate\fP ()"
.br
.ti -1c
.RI "\fBtestStaticCreateEmptyJsonObject\fP ()"
.br
.ti -1c
.RI "\fBtestStaticCreateJsonArray\fP ()"
.br
.ti -1c
.RI "\fBtestStaticCreateJsonObject\fP ()"
.br
.ti -1c
.RI "\fBtestStaticCreateWithSimpleTypes\fP ()"
.br
.ti -1c
.RI "\fBtestStaticCreateWithCustomStatus\fP ()"
.br
.ti -1c
.RI "\fBtestStaticCreateAddsContentTypeHeader\fP ()"
.br
.ti -1c
.RI "\fBtestStaticCreateWithCustomHeaders\fP ()"
.br
.ti -1c
.RI "\fBtestStaticCreateWithCustomContentType\fP ()"
.br
.ti -1c
.RI "\fBtestSetCallback\fP ()"
.br
.ti -1c
.RI "\fBtestJsonEncodeFlags\fP ()"
.br
.ti -1c
.RI "\fBtestGetEncodingOptions\fP ()"
.br
.ti -1c
.RI "\fBtestSetEncodingOptions\fP ()"
.br
.ti -1c
.RI "\fBtestSetCallbackInvalidIdentifier\fP ()"
.br
.ti -1c
.RI "\fBtestSetContent\fP ()"
.br
.ti -1c
.RI "\fBtestSetContentJsonSerializeError\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file JsonResponseTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstructorAddsContentTypeHeader ()"

.PP
Definition at line 57 of file JsonResponseTest\&.php\&.
.SS "testConstructorEmptyCreatesJsonObject ()"

.PP
Definition at line 18 of file JsonResponseTest\&.php\&.
.SS "testConstructorWithArrayCreatesJsonArray ()"

.PP
Definition at line 24 of file JsonResponseTest\&.php\&.
.SS "testConstructorWithAssocArrayCreatesJsonObject ()"

.PP
Definition at line 30 of file JsonResponseTest\&.php\&.
.SS "testConstructorWithCustomContentType ()"

.PP
Definition at line 70 of file JsonResponseTest\&.php\&.
.SS "testConstructorWithCustomHeaders ()"

.PP
Definition at line 63 of file JsonResponseTest\&.php\&.
.SS "testConstructorWithCustomStatus ()"

.PP
Definition at line 51 of file JsonResponseTest\&.php\&.
.SS "testConstructorWithSimpleTypes ()"

.PP
Definition at line 36 of file JsonResponseTest\&.php\&.
.SS "testCreate ()"

.PP
Definition at line 78 of file JsonResponseTest\&.php\&.
.SS "testGetEncodingOptions ()"

.PP
Definition at line 169 of file JsonResponseTest\&.php\&.
.SS "testJsonEncodeFlags ()"

.PP
Definition at line 162 of file JsonResponseTest\&.php\&.
.SS "testSetCallback ()"

.PP
Definition at line 154 of file JsonResponseTest\&.php\&.
.SS "testSetCallbackInvalidIdentifier ()"

.PP
Definition at line 191 of file JsonResponseTest\&.php\&.
.SS "testSetContent ()"

.PP
Definition at line 200 of file JsonResponseTest\&.php\&.
.SS "testSetContentJsonSerializeError ()"
Exception  Failed calling \fBSymfony\fP::jsonSerialize() \fBhttp://php\&.net/manual/en/jsonserializable\&.jsonserialize\&.php#114688\fP
.PP
Definition at line 210 of file JsonResponseTest\&.php\&.
.SS "testSetEncodingOptions ()"

.PP
Definition at line 176 of file JsonResponseTest\&.php\&.
.SS "testStaticCreateAddsContentTypeHeader ()"

.PP
Definition at line 133 of file JsonResponseTest\&.php\&.
.SS "testStaticCreateEmptyJsonObject ()"

.PP
Definition at line 87 of file JsonResponseTest\&.php\&.
.SS "testStaticCreateJsonArray ()"

.PP
Definition at line 94 of file JsonResponseTest\&.php\&.
.SS "testStaticCreateJsonObject ()"

.PP
Definition at line 101 of file JsonResponseTest\&.php\&.
.SS "testStaticCreateWithCustomContentType ()"

.PP
Definition at line 146 of file JsonResponseTest\&.php\&.
.SS "testStaticCreateWithCustomHeaders ()"

.PP
Definition at line 139 of file JsonResponseTest\&.php\&.
.SS "testStaticCreateWithCustomStatus ()"

.PP
Definition at line 127 of file JsonResponseTest\&.php\&.
.SS "testStaticCreateWithSimpleTypes ()"

.PP
Definition at line 108 of file JsonResponseTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
