.TH "UploadedFileTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UploadedFileTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructWhenFileNotExists\fP ()"
.br
.ti -1c
.RI "\fBtestFileUploadsWithNoMimeType\fP ()"
.br
.ti -1c
.RI "\fBtestFileUploadsWithUnknownMimeType\fP ()"
.br
.ti -1c
.RI "\fBtestGuessClientExtension\fP ()"
.br
.ti -1c
.RI "\fBtestGuessClientExtensionWithIncorrectMimeType\fP ()"
.br
.ti -1c
.RI "\fBtestErrorIsOkByDefault\fP ()"
.br
.ti -1c
.RI "\fBtestGetClientOriginalName\fP ()"
.br
.ti -1c
.RI "\fBtestGetClientOriginalExtension\fP ()"
.br
.ti -1c
.RI "\fBtestMoveLocalFileIsNotAllowed\fP ()"
.br
.ti -1c
.RI "\fBtestMoveLocalFileIsAllowedInTestMode\fP ()"
.br
.ti -1c
.RI "\fBtestGetClientOriginalNameSanitizeFilename\fP ()"
.br
.ti -1c
.RI "\fBtestGetSize\fP ()"
.br
.ti -1c
.RI "\fBtestGetExtension\fP ()"
.br
.ti -1c
.RI "\fBtestIsValid\fP ()"
.br
.ti -1c
.RI "\fBtestIsInvalidOnUploadError\fP ($error)"
.br
.ti -1c
.RI "\fBuploadedFileErrorProvider\fP ()"
.br
.ti -1c
.RI "\fBtestIsInvalidIfNotHttpUpload\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file UploadedFileTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 18 of file UploadedFileTest\&.php\&.
.SS "testConstructWhenFileNotExists ()"

.PP
Definition at line 25 of file UploadedFileTest\&.php\&.
.SS "testErrorIsOkByDefault ()"

.PP
Definition at line 92 of file UploadedFileTest\&.php\&.
.SS "testFileUploadsWithNoMimeType ()"

.PP
Definition at line 36 of file UploadedFileTest\&.php\&.
.SS "testFileUploadsWithUnknownMimeType ()"

.PP
Definition at line 53 of file UploadedFileTest\&.php\&.
.SS "testGetClientOriginalExtension ()"

.PP
Definition at line 118 of file UploadedFileTest\&.php\&.
.SS "testGetClientOriginalName ()"

.PP
Definition at line 105 of file UploadedFileTest\&.php\&.
.SS "testGetClientOriginalNameSanitizeFilename ()"

.PP
Definition at line 174 of file UploadedFileTest\&.php\&.
.SS "testGetExtension ()"

.PP
Definition at line 208 of file UploadedFileTest\&.php\&.
.SS "testGetSize ()"

.PP
Definition at line 187 of file UploadedFileTest\&.php\&.
.SS "testGuessClientExtension ()"

.PP
Definition at line 66 of file UploadedFileTest\&.php\&.
.SS "testGuessClientExtensionWithIncorrectMimeType ()"

.PP
Definition at line 79 of file UploadedFileTest\&.php\&.
.SS "testIsInvalidIfNotHttpUpload ()"

.PP
Definition at line 260 of file UploadedFileTest\&.php\&.
.SS "testIsInvalidOnUploadError ( $error)"
uploadedFileErrorProvider 
.PP
Definition at line 236 of file UploadedFileTest\&.php\&.
.SS "testIsValid ()"

.PP
Definition at line 219 of file UploadedFileTest\&.php\&.
.SS "testMoveLocalFileIsAllowedInTestMode ()"

.PP
Definition at line 147 of file UploadedFileTest\&.php\&.
.SS "testMoveLocalFileIsNotAllowed ()"

.PP
Definition at line 134 of file UploadedFileTest\&.php\&.
.SS "uploadedFileErrorProvider ()"

.PP
Definition at line 249 of file UploadedFileTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
