.TH "PhpGeneratorDumper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhpGeneratorDumper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGeneratorDumper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdump\fP (array $\fBoptions\fP=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPhpGeneratorDumper\fP creates a \fBPHP\fP class able to generate URLs for a given set of routes\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.PP
Tobias Schultze http://tobion.de
.RE
.PP

.PP
Definition at line 22 of file PhpGeneratorDumper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "dump (array $options = \fCarray()\fP)"
Dumps a set of routes to a \fBPHP\fP class\&.
.PP
Available options:
.PP
.IP "\(bu" 2
class: The class name
.IP "\(bu" 2
base_class: The base class name
.PP
.PP
\fBParameters:\fP
.RS 4
\fI$options\fP An array of options
.RE
.PP
\fBReturns:\fP
.RS 4
string \fBA\fP \fBPHP\fP class representing the generator class
.RE
.PP

.PP
Implements \fBGeneratorDumperInterface\fP\&.
.PP
Definition at line 38 of file PhpGeneratorDumper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
