.TH "ApacheUrlMatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApacheUrlMatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUrlMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmatch\fP ($pathinfo)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBApacheUrlMatcher\fP matches \fBURL\fP based on Apache mod_rewrite matching (see ApacheMatcherDumper)\&.
.PP
\fBDeprecated\fP
.RS 4
Deprecated since version 2\&.5, to be removed in 3\&.0\&. The performance gains are minimal and it's very hard to replicate the behavior of \fBPHP\fP implementation\&.
.RE
.PP
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.PP
Arnaud Le Blanc arnaud.lb@gmail.com 
.RE
.PP

.PP
Definition at line 26 of file ApacheUrlMatcher\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "match ( $pathinfo)"
Tries to match a \fBURL\fP based on Apache mod_rewrite matching\&.
.PP
Returns false if no route matches the \fBURL\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$pathinfo\fP The pathinfo to be parsed
.RE
.PP
\fBReturns:\fP
.RS 4
array An array of parameters
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIMethodNotAllowedException\fP If the current method is not allowed 
.RE
.PP

.PP
Implements \fBUrlMatcherInterface\fP\&.
.PP
Definition at line 39 of file ApacheUrlMatcher\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
