.TH "NullSessionHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NullSessionHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSaveHandlers\fP ()"
.br
.ti -1c
.RI "\fBtestSession\fP ()"
.br
.ti -1c
.RI "\fBtestNothingIsPersisted\fP ()"
.br
.ti -1c
.RI "\fBgetStorage\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Test class for NullSessionHandler\&.
.PP
\fBAuthor:\fP
.RS 4
Drak drak@zikula.org
.RE
.PP
disabled 
.PP
Definition at line 26 of file NullSessionHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getStorage ()"

.PP
Definition at line 54 of file NullSessionHandlerTest\&.php\&.
.SS "testNothingIsPersisted ()"

.PP
Definition at line 44 of file NullSessionHandlerTest\&.php\&.
.SS "testSaveHandlers ()"

.PP
Definition at line 28 of file NullSessionHandlerTest\&.php\&.
.SS "testSession ()"

.PP
Definition at line 34 of file NullSessionHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
