.TH "TranslatorListenerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranslatorListenerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestLocaleIsSetInOnKernelRequest\fP ()"
.br
.ti -1c
.RI "\fBtestDefaultLocaleIsUsedOnExceptionsInOnKernelRequest\fP ()"
.br
.ti -1c
.RI "\fBtestLocaleIsSetInOnKernelFinishRequestWhenParentRequestExists\fP ()"
.br
.ti -1c
.RI "\fBtestLocaleIsNotSetInOnKernelFinishRequestWhenParentRequestDoesNotExist\fP ()"
.br
.ti -1c
.RI "\fBtestDefaultLocaleIsUsedOnExceptionsInOnKernelFinishRequest\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file TranslatorListenerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 26 of file TranslatorListenerTest\&.php\&.
.SS "testDefaultLocaleIsUsedOnExceptionsInOnKernelFinishRequest ()"

.PP
Definition at line 81 of file TranslatorListenerTest\&.php\&.
.SS "testDefaultLocaleIsUsedOnExceptionsInOnKernelRequest ()"

.PP
Definition at line 44 of file TranslatorListenerTest\&.php\&.
.SS "testLocaleIsNotSetInOnKernelFinishRequestWhenParentRequestDoesNotExist ()"

.PP
Definition at line 71 of file TranslatorListenerTest\&.php\&.
.SS "testLocaleIsSetInOnKernelFinishRequestWhenParentRequestExists ()"

.PP
Definition at line 59 of file TranslatorListenerTest\&.php\&.
.SS "testLocaleIsSetInOnKernelRequest ()"

.PP
Definition at line 33 of file TranslatorListenerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
