.TH "AccessDecisionManagerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AccessDecisionManagerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSupportsClass\fP ()"
.br
.ti -1c
.RI "\fBtestSupportsAttribute\fP ()"
.br
.ti -1c
.RI "\fBtestSetVotersEmpty\fP ()"
.br
.ti -1c
.RI "\fBtestSetUnsupportedStrategy\fP ()"
.br
.ti -1c
.RI "\fBtestStrategies\fP ($strategy, $voters, $allowIfAllAbstainDecisions, $allowIfEqualGrantedDeniedDecisions, $expected)"
.br
.ti -1c
.RI "\fBtestStrategiesWith2Roles\fP ($token, $strategy, $voter, $expected)"
.br
.ti -1c
.RI "\fBgetStrategiesWith2RolesTests\fP ()"
.br
.ti -1c
.RI "\fBgetStrategyTests\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetVoterFor2Roles\fP ($token, $vote1, $vote2)"
.br
.ti -1c
.RI "\fBgetVoters\fP ($grants, $denies, $abstains)"
.br
.ti -1c
.RI "\fBgetVoter\fP ($vote)"
.br
.ti -1c
.RI "\fBgetVoterSupportsClass\fP ($ret)"
.br
.ti -1c
.RI "\fBgetVoterSupportsAttribute\fP ($ret)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file AccessDecisionManagerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getStrategiesWith2RolesTests ()"

.PP
Definition at line 86 of file AccessDecisionManagerTest\&.php\&.
.SS "getStrategyTests ()"

.PP
Definition at line 118 of file AccessDecisionManagerTest\&.php\&.
.SS "getVoter ( $vote)\fC [protected]\fP"

.PP
Definition at line 169 of file AccessDecisionManagerTest\&.php\&.
.SS "getVoterFor2Roles ( $token,  $vote1,  $vote2)\fC [protected]\fP"

.PP
Definition at line 104 of file AccessDecisionManagerTest\&.php\&.
.SS "getVoters ( $grants,  $denies,  $abstains)\fC [protected]\fP"

.PP
Definition at line 153 of file AccessDecisionManagerTest\&.php\&.
.SS "getVoterSupportsAttribute ( $ret)\fC [protected]\fP"

.PP
Definition at line 189 of file AccessDecisionManagerTest\&.php\&.
.SS "getVoterSupportsClass ( $ret)\fC [protected]\fP"

.PP
Definition at line 179 of file AccessDecisionManagerTest\&.php\&.
.SS "testSetUnsupportedStrategy ()"

.PP
Definition at line 60 of file AccessDecisionManagerTest\&.php\&.
.SS "testSetVotersEmpty ()"

.PP
Definition at line 52 of file AccessDecisionManagerTest\&.php\&.
.SS "testStrategies ( $strategy,  $voters,  $allowIfAllAbstainDecisions,  $allowIfEqualGrantedDeniedDecisions,  $expected)"
getStrategyTests 
.PP
Definition at line 68 of file AccessDecisionManagerTest\&.php\&.
.SS "testStrategiesWith2Roles ( $token,  $strategy,  $voter,  $expected)"
getStrategiesWith2RolesTests 
.PP
Definition at line 79 of file AccessDecisionManagerTest\&.php\&.
.SS "testSupportsAttribute ()"

.PP
Definition at line 34 of file AccessDecisionManagerTest\&.php\&.
.SS "testSupportsClass ()"

.PP
Definition at line 19 of file AccessDecisionManagerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
