.TH "ConsoleExceptionEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleExceptionEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBConsoleEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBCommand\fP $command, \fBInputInterface\fP $input, \fBOutputInterface\fP $output,\\Exception $exception, $exitCode)"
.br
.ti -1c
.RI "\fBgetException\fP ()"
.br
.ti -1c
.RI "\fBsetException\fP (\\Exception $exception)"
.br
.ti -1c
.RI "\fBgetExitCode\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Allows to handle exception thrown in a command\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 23 of file ConsoleExceptionEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBCommand\fP $command, \fBInputInterface\fP $input, \fBOutputInterface\fP $output, \\Exception $exception,  $exitCode)"

.PP
Definition at line 28 of file ConsoleExceptionEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getException ()"
Returns the thrown exception\&.
.PP
\fBReturns:\fP
.RS 4
The thrown exception 
.RE
.PP

.PP
Definition at line 41 of file ConsoleExceptionEvent\&.php\&.
.SS "getExitCode ()"
Gets the exit code\&.
.PP
\fBReturns:\fP
.RS 4
int The command exit code 
.RE
.PP

.PP
Definition at line 63 of file ConsoleExceptionEvent\&.php\&.
.SS "setException (\\Exception $exception)"
Replaces the thrown exception\&.
.PP
This exception will be thrown if no response is set in the event\&.
.PP
\fBParameters:\fP
.RS 4
\fI$exception\fP The thrown exception 
.RE
.PP

.PP
Definition at line 53 of file ConsoleExceptionEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
