.TH "RequestContextAwareInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RequestContextAwareInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBUrlGeneratorInterface\fP, and \fBUrlMatcherInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetContext\fP (\fBRequestContext\fP $context)"
.br
.ti -1c
.RI "\fBgetContext\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line 17 of file RequestContextAwareInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getContext ()"
Gets the request context\&.
.PP
\fBReturns:\fP
.RS 4
\fBRequestContext\fP The context
.RE
.PP

.PP
Implemented in \fBRouter\fP, \fBUrlGenerator\fP, and \fBUrlMatcher\fP\&.
.SS "setContext (\fBRequestContext\fP $context)"
Sets the request context\&.
.PP
\fBParameters:\fP
.RS 4
\fI$context\fP The context
.RE
.PP

.PP
Implemented in \fBRouter\fP, \fBUrlGenerator\fP, and \fBUrlMatcher\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
