.TH "UsernamePasswordTokenTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UsernamePasswordTokenTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructor\fP ()"
.br
.ti -1c
.RI "\fBtestSetAuthenticatedToTrue\fP ()"
.br
.ti -1c
.RI "\fBtestSetAuthenticatedToFalse\fP ()"
.br
.ti -1c
.RI "\fBtestEraseCredentials\fP ()"
.br
.ti -1c
.RI "\fBtestToString\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file UsernamePasswordTokenTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstructor ()"

.PP
Definition at line 19 of file UsernamePasswordTokenTest\&.php\&.
.SS "testEraseCredentials ()"

.PP
Definition at line 46 of file UsernamePasswordTokenTest\&.php\&.
.SS "testSetAuthenticatedToFalse ()"

.PP
Definition at line 39 of file UsernamePasswordTokenTest\&.php\&.
.SS "testSetAuthenticatedToTrue ()"

.PP
Definition at line 33 of file UsernamePasswordTokenTest\&.php\&.
.SS "testToString ()"

.PP
Definition at line 53 of file UsernamePasswordTokenTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
