.TH "CustomApplication" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomApplication \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBApplication\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetDefaultInputDefinition\fP ()"
.br
.ti -1c
.RI "\fBgetDefaultHelperSet\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 1024 of file ApplicationTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDefaultHelperSet ()\fC [protected]\fP"
Gets the default helper set with the helpers that should always be available\&.
.PP
\fBReturns:\fP
.RS 4
HelperSet \fBA\fP HelperSet instance 
.RE
.PP

.PP
Definition at line 1041 of file ApplicationTest\&.php\&.
.SS "getDefaultInputDefinition ()\fC [protected]\fP"
Overwrites the default input definition\&.
.PP
\fBReturns:\fP
.RS 4
InputDefinition An InputDefinition instance 
.RE
.PP

.PP
Definition at line 1031 of file ApplicationTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
