.TH "ChoiceQuestion" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ChoiceQuestion \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBQuestion\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($question, array $choices, $default=null)"
.br
.ti -1c
.RI "\fBgetChoices\fP ()"
.br
.ti -1c
.RI "\fBsetMultiselect\fP ($multiselect)"
.br
.ti -1c
.RI "\fBgetPrompt\fP ()"
.br
.ti -1c
.RI "\fBsetPrompt\fP ($prompt)"
.br
.ti -1c
.RI "\fBsetErrorMessage\fP ($errorMessage)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a choice question\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 19 of file ChoiceQuestion\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $question, array $choices,  $default = \fCnull\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$question\fP The question to ask to the user 
.br
\fI$choices\fP The list of available choices 
.br
\fI$default\fP The default answer to return 
.RE
.PP

.PP
Definition at line 33 of file ChoiceQuestion\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getChoices ()"
Returns available choices\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 47 of file ChoiceQuestion\&.php\&.
.SS "getPrompt ()"
Gets the prompt for choices\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 74 of file ChoiceQuestion\&.php\&.
.SS "setErrorMessage ( $errorMessage)"
Sets the error message for invalid values\&.
.PP
The error message has a string placeholder (s) for the invalid value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$errorMessage\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBChoiceQuestion\fP The current instance 
.RE
.PP

.PP
Definition at line 102 of file ChoiceQuestion\&.php\&.
.SS "setMultiselect ( $multiselect)"
Sets multiselect option\&.
.PP
When multiselect is set to true, multiple choices can be answered\&.
.PP
\fBParameters:\fP
.RS 4
\fI$multiselect\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBChoiceQuestion\fP The current instance 
.RE
.PP

.PP
Definition at line 61 of file ChoiceQuestion\&.php\&.
.SS "setPrompt ( $prompt)"
Sets the prompt for choices\&.
.PP
\fBParameters:\fP
.RS 4
\fI$prompt\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBChoiceQuestion\fP The current instance 
.RE
.PP

.PP
Definition at line 86 of file ChoiceQuestion\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
