.TH "ApplicationTesterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApplicationTesterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestRun\fP ()"
.br
.ti -1c
.RI "\fBtestGetInput\fP ()"
.br
.ti -1c
.RI "\fBtestGetOutput\fP ()"
.br
.ti -1c
.RI "\fBtestGetDisplay\fP ()"
.br
.ti -1c
.RI "\fBtestGetStatusCode\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$application\fP"
.br
.ti -1c
.RI "\fB$tester\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file ApplicationTesterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 23 of file ApplicationTesterTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 36 of file ApplicationTesterTest\&.php\&.
.SS "testGetDisplay ()"

.PP
Definition at line 60 of file ApplicationTesterTest\&.php\&.
.SS "testGetInput ()"

.PP
Definition at line 49 of file ApplicationTesterTest\&.php\&.
.SS "testGetOutput ()"

.PP
Definition at line 54 of file ApplicationTesterTest\&.php\&.
.SS "testGetStatusCode ()"

.PP
Definition at line 65 of file ApplicationTesterTest\&.php\&.
.SS "testRun ()"

.PP
Definition at line 42 of file ApplicationTesterTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$application\fC [protected]\fP"

.PP
Definition at line 20 of file ApplicationTesterTest\&.php\&.
.SS "$tester\fC [protected]\fP"

.PP
Definition at line 21 of file ApplicationTesterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
