.TH "FileinfoMimeTypeGuesser" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileinfoMimeTypeGuesser \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMimeTypeGuesserInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($magicFile=null)"
.br
.ti -1c
.RI "\fBguess\fP ($\fBpath\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBisSupported\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Guesses the mime type using the PECL extension FileInfo\&.
.PP
\fBAuthor:\fP
.RS 4
Bernhard Schussek bschussek@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file FileinfoMimeTypeGuesser\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $magicFile = \fCnull\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$magicFile\fP \fBA\fP magic file to use with the finfo instance
.RE
.PP
\fBhttp://www\&.php\&.net/manual/en/function\&.finfo-open\&.php\fP
.PP
Definition at line 33 of file FileinfoMimeTypeGuesser\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "guess ( $path)"
{Guesses the mime type of the file with the given path\&.
.PP
\fBParameters:\fP
.RS 4
\fI$path\fP The path to the file
.RE
.PP
\fBReturns:\fP
.RS 4
string The mime type or NULL, if none could be guessed
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIFileNotFoundException\fP If the file does not exist 
.br
\fIAccessDeniedException\fP If the file could not be read
.RE
.PP
} 
.PP
Implements \fBMimeTypeGuesserInterface\fP\&.
.PP
Definition at line 51 of file FileinfoMimeTypeGuesser\&.php\&.
.SS "static isSupported ()\fC [static]\fP"
Returns whether this guesser is supported on the current OS/PHP setup\&.
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 43 of file FileinfoMimeTypeGuesser\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
