.TH "TranslatorListener" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranslatorListener \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventSubscriberInterface\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBTranslatorInterface\fP $translator, \fBRequestStack\fP $requestStack)"
.br
.ti -1c
.RI "\fBonKernelRequest\fP (\fBGetResponseEvent\fP $\fBevent\fP)"
.br
.ti -1c
.RI "\fBonKernelFinishRequest\fP (\fBFinishRequestEvent\fP $\fBevent\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetSubscribedEvents\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Synchronizes the locale between the request and the translator\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 27 of file TranslatorListener\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBTranslatorInterface\fP $translator, \fBRequestStack\fP $requestStack)"

.PP
Definition at line 32 of file TranslatorListener\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getSubscribedEvents ()\fC [static]\fP"

.PP
Definition at line 52 of file TranslatorListener\&.php\&.
.SS "onKernelFinishRequest (\fBFinishRequestEvent\fP $event)"

.PP
Definition at line 43 of file TranslatorListener\&.php\&.
.SS "onKernelRequest (\fBGetResponseEvent\fP $event)"

.PP
Definition at line 38 of file TranslatorListener\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
