.TH "ExpressionTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpressionTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestTypeGuesser\fP ($expr, $type)"
.br
.ti -1c
.RI "\fBtestCaseSensitive\fP ($expr, $\fBisCaseSensitive\fP)"
.br
.ti -1c
.RI "\fBtestRegexRendering\fP ($expr, $body)"
.br
.ti -1c
.RI "\fBgetTypeGuesserData\fP ()"
.br
.ti -1c
.RI "\fBgetCaseSensitiveData\fP ()"
.br
.ti -1c
.RI "\fBgetRegexRenderingData\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file ExpressionTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getCaseSensitiveData ()"

.PP
Definition at line 52 of file ExpressionTest\&.php\&.
.SS "getRegexRenderingData ()"

.PP
Definition at line 61 of file ExpressionTest\&.php\&.
.SS "getTypeGuesserData ()"

.PP
Definition at line 42 of file ExpressionTest\&.php\&.
.SS "testCaseSensitive ( $expr,  $isCaseSensitive)"
getCaseSensitiveData 
.PP
Definition at line 29 of file ExpressionTest\&.php\&.
.SS "testRegexRendering ( $expr,  $body)"
getRegexRenderingData 
.PP
Definition at line 37 of file ExpressionTest\&.php\&.
.SS "testTypeGuesser ( $expr,  $type)"
getTypeGuesserData 
.PP
Definition at line 21 of file ExpressionTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
