.TH "Symfony\Component\HttpKernel\Tests\Fixtures" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\HttpKernel\Tests\Fixtures \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBExtensionAbsentBundle\fP"
.br
.ti -1c
.RI " \fBExtensionLoadedBundle\fP"
.br
.ti -1c
.RI " \fBExtensionPresentBundle\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBFooBarBundle\fP"
.br
.ti -1c
.RI "class \fBKernelForOverrideName\fP"
.br
.ti -1c
.RI "class \fBKernelForTest\fP"
.br
.ti -1c
.RI "class \fBTestClient\fP"
.br
.ti -1c
.RI "class \fBTestEventDispatcher\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
