.TH "TestEventSubscriberWithMultipleListeners" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestEventSubscriberWithMultipleListeners \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits EventSubscriberInterface\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBgetSubscribedEvents\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 360 of file AbstractEventDispatcherTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static getSubscribedEvents ()\fC [static]\fP"

.PP
Definition at line 362 of file AbstractEventDispatcherTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
