.TH "DumpException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DumpException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntimeException\fP\&.
.SH "Detailed Description"
.PP 
\fBException\fP class thrown when an error occurs during dumping\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 21 of file DumpException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
