.TH "CustomFilterIterator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CustomFilterIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFilterIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\\Iterator $iterator, array $filters)"
.br
.ti -1c
.RI "\fBaccept\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCustomFilterIterator\fP filters files by applying anonymous functions\&.
.PP
The anonymous function receives a  and must return false to remove files\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 22 of file CustomFilterIterator\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\\Iterator $iterator, array $filters)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$iterator\fP The \fBIterator\fP to filter 
.br
\fI$filters\fP An array of \fBPHP\fP callbacks
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 34 of file CustomFilterIterator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "accept ()"
Filters the iterator values\&.
.PP
\fBReturns:\fP
.RS 4
bool true if the value should be kept, false otherwise 
.RE
.PP

.PP
Definition at line 51 of file CustomFilterIterator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
