.TH "WrappedListener" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WrappedListener \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($listener, $\fBname\fP, Stopwatch $stopwatch, \fBEventDispatcherInterface\fP $dispatcher=null)"
.br
.ti -1c
.RI "\fBgetWrappedListener\fP ()"
.br
.ti -1c
.RI "\fBwasCalled\fP ()"
.br
.ti -1c
.RI "\fBstoppedPropagation\fP ()"
.br
.ti -1c
.RI "\fB__invoke\fP (\fBEvent\fP $\fBevent\fP, $eventName, \fBEventDispatcherInterface\fP $dispatcher)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 21 of file WrappedListener\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $listener,  $name, Stopwatch $stopwatch, \fBEventDispatcherInterface\fP $dispatcher = \fCnull\fP)"

.PP
Definition at line 30 of file WrappedListener\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__invoke (\fBEvent\fP $event,  $eventName, \fBEventDispatcherInterface\fP $dispatcher)"

.PP
Definition at line 55 of file WrappedListener\&.php\&.
.SS "getWrappedListener ()"

.PP
Definition at line 40 of file WrappedListener\&.php\&.
.SS "stoppedPropagation ()"

.PP
Definition at line 50 of file WrappedListener\&.php\&.
.SS "wasCalled ()"

.PP
Definition at line 45 of file WrappedListener\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
