.TH "ExceptionListenerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExceptionListenerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstruct\fP ()"
.br
.ti -1c
.RI "\fBtestHandleWithoutLogger\fP ($\fBevent\fP, $event2)"
.br
.ti -1c
.RI "\fBtestHandleWithLogger\fP ($\fBevent\fP, $event2)"
.br
.ti -1c
.RI "\fBprovider\fP ()"
.br
.ti -1c
.RI "\fBtestSubRequestFormat\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBExceptionListenerTest\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Robert Schönthal seroscho@googlemail.com 
.RE
.PP

.PP
Definition at line 27 of file ExceptionListenerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provider ()"

.PP
Definition at line 86 of file ExceptionListenerTest\&.php\&.
.SS "testConstruct ()"

.PP
Definition at line 29 of file ExceptionListenerTest\&.php\&.
.SS "testHandleWithLogger ( $event,  $event2)"
provider 
.PP
Definition at line 66 of file ExceptionListenerTest\&.php\&.
.SS "testHandleWithoutLogger ( $event,  $event2)"
provider 
.PP
Definition at line 46 of file ExceptionListenerTest\&.php\&.
.SS "testSubRequestFormat ()"

.PP
Definition at line 102 of file ExceptionListenerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
