.TH "NotFoundResourceException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NotFoundResourceException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits InvalidArgumentException, and \fBExceptionInterface\fP\&.
.SH "Detailed Description"
.PP 
Thrown when a resource does not exist\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 21 of file NotFoundResourceException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
