.TH "ExecutableFinderTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExecutableFinderTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestFind\fP ()"
.br
.ti -1c
.RI "\fBtestFindWithDefault\fP ()"
.br
.ti -1c
.RI "\fBtestFindWithExtraDirs\fP ()"
.br
.ti -1c
.RI "\fBtestFindWithOpenBaseDir\fP ()"
.br
.ti -1c
.RI "\fBtestFindProcessInOpenBasedir\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Chris Smith chris@cs278.org 
.RE
.PP

.PP
Definition at line 19 of file ExecutableFinderTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 23 of file ExecutableFinderTest\&.php\&.
.SS "testFind ()"

.PP
Definition at line 37 of file ExecutableFinderTest\&.php\&.
.SS "testFindProcessInOpenBasedir ()"

.PP
Definition at line 113 of file ExecutableFinderTest\&.php\&.
.SS "testFindWithDefault ()"

.PP
Definition at line 55 of file ExecutableFinderTest\&.php\&.
.SS "testFindWithExtraDirs ()"

.PP
Definition at line 71 of file ExecutableFinderTest\&.php\&.
.SS "testFindWithOpenBaseDir ()"

.PP
Definition at line 91 of file ExecutableFinderTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
