.TH "ValueInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValueInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBExpression\fP, \fBExpression\fP, \fBGlob\fP, \fBRegex\fP, and \fBRegex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBrender\fP ()"
.br
.ti -1c
.RI "\fBrenderPattern\fP ()"
.br
.ti -1c
.RI "\fBisCaseSensitive\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBprepend\fP ($expr)"
.br
.ti -1c
.RI "\fBappend\fP ($expr)"
.br
.ti -1c
.RI "\fBrender\fP ()"
.br
.ti -1c
.RI "\fBrenderPattern\fP ()"
.br
.ti -1c
.RI "\fBisCaseSensitive\fP ()"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBprepend\fP ($expr)"
.br
.ti -1c
.RI "\fBappend\fP ($expr)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jean-François Simon contact@jfsimon.fr 
.RE
.PP

.PP
Definition at line 15240 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "append ( $expr)"

.PP
\fBParameters:\fP
.RS 4
\fI$expr\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBValueInterface\fP 
.RE
.PP

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "append ( $expr)"

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "getType ()"
Returns expression type\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "getType ()"

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "isCaseSensitive ()"
Returns value case sensitivity\&.
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "isCaseSensitive ()"

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "prepend ( $expr)"

.PP
\fBParameters:\fP
.RS 4
\fI$expr\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBValueInterface\fP 
.RE
.PP

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "prepend ( $expr)"

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "render ()"
Renders string representation of expression\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "render ()"

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "renderPattern ()"
Renders string representation of pattern\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.
.SS "renderPattern ()"

.PP
Implemented in \fBExpression\fP, \fBRegex\fP, \fBRegex\fP, \fBExpression\fP, and \fBGlob\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
