.TH "SessionBagInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SessionBagInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBAttributeBagInterface\fP, \fBAttributeBagInterface\fP, \fBFlashBagInterface\fP, \fBMetadataBag\fP, and \fBMetadataBag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBinitialize\fP (array &$array)"
.br
.ti -1c
.RI "\fBgetStorageKey\fP ()"
.br
.ti -1c
.RI "\fBclear\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.ti -1c
.RI "\fBinitialize\fP (array &$array)"
.br
.ti -1c
.RI "\fBgetStorageKey\fP ()"
.br
.ti -1c
.RI "\fBclear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBSession\fP Bag store\&.
.PP
\fBAuthor:\fP
.RS 4
Drak drak@zikula.org 
.RE
.PP

.PP
Definition at line 3769 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "clear ()"
Clears out data from bag\&.
.PP
\fBReturns:\fP
.RS 4
mixed Whatever data was contained\&. 
.RE
.PP

.PP
Implemented in \fBMetadataBag\fP, \fBAttributeBag\fP, \fBAutoExpireFlashBag\fP, \fBFlashBag\fP, \fBMetadataBag\fP, and \fBAttributeBag\fP\&.
.SS "clear ()"

.PP
Implemented in \fBMetadataBag\fP, \fBAttributeBag\fP, \fBAutoExpireFlashBag\fP, \fBFlashBag\fP, \fBMetadataBag\fP, and \fBAttributeBag\fP\&.
.SS "getName ()"
Gets this bag's name\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBMetadataBag\fP, \fBAttributeBag\fP, \fBMetadataBag\fP, \fBFlashBag\fP, \fBAutoExpireFlashBag\fP, and \fBAttributeBag\fP\&.
.SS "getName ()"

.PP
Implemented in \fBMetadataBag\fP, \fBAttributeBag\fP, \fBMetadataBag\fP, \fBFlashBag\fP, \fBAutoExpireFlashBag\fP, and \fBAttributeBag\fP\&.
.SS "getStorageKey ()"
Gets the storage key for this bag\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBMetadataBag\fP, \fBAttributeBag\fP, \fBAutoExpireFlashBag\fP, \fBFlashBag\fP, \fBMetadataBag\fP, and \fBAttributeBag\fP\&.
.SS "getStorageKey ()"

.PP
Implemented in \fBMetadataBag\fP, \fBAttributeBag\fP, \fBAutoExpireFlashBag\fP, \fBFlashBag\fP, \fBMetadataBag\fP, and \fBAttributeBag\fP\&.
.SS "initialize (array & $array)"
Initializes the Bag\&.
.PP
\fBParameters:\fP
.RS 4
\fI$array\fP 
.RE
.PP

.PP
Implemented in \fBMetadataBag\fP, \fBAttributeBag\fP, \fBMetadataBag\fP, \fBFlashBag\fP, \fBAutoExpireFlashBag\fP, and \fBAttributeBag\fP\&.
.SS "initialize (array & $array)"

.PP
Implemented in \fBMetadataBag\fP, \fBAttributeBag\fP, \fBMetadataBag\fP, \fBFlashBag\fP, \fBAutoExpireFlashBag\fP, and \fBAttributeBag\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
