.TH "CommandTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructor\fP ()"
.br
.ti -1c
.RI "\fBtestCommandNameCannotBeEmpty\fP ()"
.br
.ti -1c
.RI "\fBtestSetApplication\fP ()"
.br
.ti -1c
.RI "\fBtestSetGetDefinition\fP ()"
.br
.ti -1c
.RI "\fBtestAddArgument\fP ()"
.br
.ti -1c
.RI "\fBtestAddOption\fP ()"
.br
.ti -1c
.RI "\fBtestGetNamespaceGetNameSetName\fP ()"
.br
.ti -1c
.RI "\fBtestInvalidCommandNames\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBprovideInvalidCommandNames\fP ()"
.br
.ti -1c
.RI "\fBtestGetSetDescription\fP ()"
.br
.ti -1c
.RI "\fBtestGetSetHelp\fP ()"
.br
.ti -1c
.RI "\fBtestGetProcessedHelp\fP ()"
.br
.ti -1c
.RI "\fBtestGetSetAliases\fP ()"
.br
.ti -1c
.RI "\fBtestGetSynopsis\fP ()"
.br
.ti -1c
.RI "\fBtestGetHelper\fP ()"
.br
.ti -1c
.RI "\fBtestGet\fP ()"
.br
.ti -1c
.RI "\fBtestMergeApplicationDefinition\fP ()"
.br
.ti -1c
.RI "\fBtestMergeApplicationDefinitionWithoutArgsThenWithArgsAddsArgs\fP ()"
.br
.ti -1c
.RI "\fBtestRunInteractive\fP ()"
.br
.ti -1c
.RI "\fBtestRunNonInteractive\fP ()"
.br
.ti -1c
.RI "\fBtestExecuteMethodNeedsToBeOverridden\fP ()"
.br
.ti -1c
.RI "\fBtestRunWithInvalidOption\fP ()"
.br
.ti -1c
.RI "\fBtestRunReturnsIntegerExitCode\fP ()"
.br
.ti -1c
.RI "\fBtestRunReturnsAlwaysInteger\fP ()"
.br
.ti -1c
.RI "\fBtestSetCode\fP ()"
.br
.ti -1c
.RI "\fBtestSetCodeWithNonClosureCallable\fP ()"
.br
.ti -1c
.RI "\fBtestSetCodeWithNonCallable\fP ()"
.br
.ti -1c
.RI "\fBcallableMethodCommand\fP (\fBInputInterface\fP $input, \fBOutputInterface\fP $output)"
.br
.ti -1c
.RI "\fBtestLegacyAsText\fP ()"
.br
.ti -1c
.RI "\fBtestLegacyAsXml\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBsetUpBeforeClass\fP ()"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$fixturesPath\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 26 of file CommandTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "callableMethodCommand (\fBInputInterface\fP $input, \fBOutputInterface\fP $output)"

.PP
Definition at line 316 of file CommandTest\&.php\&.
.SS "provideInvalidCommandNames ()"

.PP
Definition at line 110 of file CommandTest\&.php\&.
.SS "static setUpBeforeClass ()\fC [static]\fP"

.PP
Definition at line 30 of file CommandTest\&.php\&.
.SS "testAddArgument ()"

.PP
Definition at line 71 of file CommandTest\&.php\&.
.SS "testAddOption ()"

.PP
Definition at line 79 of file CommandTest\&.php\&.
.SS "testCommandNameCannotBeEmpty ()"
The command defined in 'Symfony\\Component\\Console\\Command\\Command' cannot have an empty name\&. 
.PP
Definition at line 46 of file CommandTest\&.php\&.
.SS "testConstructor ()"

.PP
Definition at line 36 of file CommandTest\&.php\&.
.SS "testExecuteMethodNeedsToBeOverridden ()"
You must override the execute() method in the concrete command class\&. 
.PP
Definition at line 246 of file CommandTest\&.php\&.
.SS "testGet ()"

.PP
Definition at line 170 of file CommandTest\&.php\&.
.SS "testGetHelper ()"

.PP
Definition at line 161 of file CommandTest\&.php\&.
.SS "testGetNamespaceGetNameSetName ()"

.PP
Definition at line 87 of file CommandTest\&.php\&.
.SS "testGetProcessedHelp ()"

.PP
Definition at line 136 of file CommandTest\&.php\&.
.SS "testGetSetAliases ()"

.PP
Definition at line 144 of file CommandTest\&.php\&.
.SS "testGetSetDescription ()"

.PP
Definition at line 118 of file CommandTest\&.php\&.
.SS "testGetSetHelp ()"

.PP
Definition at line 127 of file CommandTest\&.php\&.
.SS "testGetSynopsis ()"

.PP
Definition at line 153 of file CommandTest\&.php\&.
.SS "testInvalidCommandNames ( $name)"
provideInvalidCommandNames 
.PP
Definition at line 102 of file CommandTest\&.php\&.
.SS "testLegacyAsText ()"
legacy 
.PP
Definition at line 324 of file CommandTest\&.php\&.
.SS "testLegacyAsXml ()"
legacy 
.PP
Definition at line 338 of file CommandTest\&.php\&.
.SS "testMergeApplicationDefinition ()"

.PP
Definition at line 179 of file CommandTest\&.php\&.
.SS "testMergeApplicationDefinitionWithoutArgsThenWithArgsAddsArgs ()"

.PP
Definition at line 201 of file CommandTest\&.php\&.
.SS "testRunInteractive ()"

.PP
Definition at line 224 of file CommandTest\&.php\&.
.SS "testRunNonInteractive ()"

.PP
Definition at line 233 of file CommandTest\&.php\&.
.SS "testRunReturnsAlwaysInteger ()"

.PP
Definition at line 277 of file CommandTest\&.php\&.
.SS "testRunReturnsIntegerExitCode ()"

.PP
Definition at line 263 of file CommandTest\&.php\&.
.SS "testRunWithInvalidOption ()"
The '--bar' option does not exist\&. 
.PP
Definition at line 256 of file CommandTest\&.php\&.
.SS "testSetApplication ()"

.PP
Definition at line 51 of file CommandTest\&.php\&.
.SS "testSetCode ()"

.PP
Definition at line 284 of file CommandTest\&.php\&.
.SS "testSetCodeWithNonCallable ()"
Invalid callable provided to \fBCommand::setCode\fP\&. 
.PP
Definition at line 310 of file CommandTest\&.php\&.
.SS "testSetCodeWithNonClosureCallable ()"

.PP
Definition at line 296 of file CommandTest\&.php\&.
.SS "testSetGetDefinition ()"

.PP
Definition at line 59 of file CommandTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$fixturesPath\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 28 of file CommandTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
