.TH "Symfony\Component\VarDumper\Caster" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\VarDumper\Caster \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBConstStub\fP"
.br
.ti -1c
.RI "class \fBCutStub\fP"
.br
.ti -1c
.RI "class \fBDoctrineCaster\fP"
.br
.ti -1c
.RI "class \fBDOMCaster\fP"
.br
.ti -1c
.RI "class \fBExceptionCaster\fP"
.br
.ti -1c
.RI "class \fBPdoCaster\fP"
.br
.ti -1c
.RI "class \fBReflectionCaster\fP"
.br
.ti -1c
.RI "class \fBResourceCaster\fP"
.br
.ti -1c
.RI "class \fBSplCaster\fP"
.br
.ti -1c
.RI "class \fBStubCaster\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
