.TH "AbstractEventDispatcherTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbstractEventDispatcherTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.PP
Inherited by \fBContainerAwareEventDispatcherTest\fP, and \fBEventDispatcherTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestInitialState\fP ()"
.br
.ti -1c
.RI "\fBtestAddListener\fP ()"
.br
.ti -1c
.RI "\fBtestGetListenersSortsByPriority\fP ()"
.br
.ti -1c
.RI "\fBtestGetAllListenersSortsByPriority\fP ()"
.br
.ti -1c
.RI "\fBtestDispatch\fP ()"
.br
.ti -1c
.RI "\fBtestDispatchForClosure\fP ()"
.br
.ti -1c
.RI "\fBtestStopEventPropagation\fP ()"
.br
.ti -1c
.RI "\fBtestDispatchByPriority\fP ()"
.br
.ti -1c
.RI "\fBtestRemoveListener\fP ()"
.br
.ti -1c
.RI "\fBtestAddSubscriber\fP ()"
.br
.ti -1c
.RI "\fBtestAddSubscriberWithPriorities\fP ()"
.br
.ti -1c
.RI "\fBtestAddSubscriberWithMultipleListeners\fP ()"
.br
.ti -1c
.RI "\fBtestRemoveSubscriber\fP ()"
.br
.ti -1c
.RI "\fBtestRemoveSubscriberWithPriorities\fP ()"
.br
.ti -1c
.RI "\fBtestRemoveSubscriberWithMultipleListeners\fP ()"
.br
.ti -1c
.RI "\fBtestEventReceivesTheDispatcherInstance\fP ()"
.br
.ti -1c
.RI "\fBtestEventReceivesTheDispatcherInstanceAsArgument\fP ()"
.br
.ti -1c
.RI "\fBtestWorkaroundForPhpBug62976\fP ()"
.br
.ti -1c
.RI "\fBtestHasListenersWhenAddedCallbackListenerIsRemoved\fP ()"
.br
.ti -1c
.RI "\fBtestGetListenersWhenAddedCallbackListenerIsRemoved\fP ()"
.br
.ti -1c
.RI "\fBtestHasListenersWithoutEventsReturnsFalseAfterHasListenersWithEventHasBeenCalled\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBpreFoo\fP = '\fBpre\&.foo\fP'"
.br
.ti -1c
.RI "const \fBpostFoo\fP = '\fBpost\&.foo\fP'"
.br
.ti -1c
.RI "const \fBpreBar\fP = 'pre\&.bar'"
.br
.ti -1c
.RI "const \fBpostBar\fP = 'post\&.bar'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.ti -1c
.RI "\fBcreateEventDispatcher\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file AbstractEventDispatcherTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createEventDispatcher ()\fC [abstract]\fP, \fC [protected]\fP"

.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 32 of file AbstractEventDispatcherTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 38 of file AbstractEventDispatcherTest\&.php\&.
.SS "testAddListener ()"

.PP
Definition at line 53 of file AbstractEventDispatcherTest\&.php\&.
.SS "testAddSubscriber ()"

.PP
Definition at line 179 of file AbstractEventDispatcherTest\&.php\&.
.SS "testAddSubscriberWithMultipleListeners ()"

.PP
Definition at line 201 of file AbstractEventDispatcherTest\&.php\&.
.SS "testAddSubscriberWithPriorities ()"

.PP
Definition at line 187 of file AbstractEventDispatcherTest\&.php\&.
.SS "testDispatch ()"

.PP
Definition at line 110 of file AbstractEventDispatcherTest\&.php\&.
.SS "testDispatchByPriority ()"

.PP
Definition at line 151 of file AbstractEventDispatcherTest\&.php\&.
.SS "testDispatchForClosure ()"

.PP
Definition at line 125 of file AbstractEventDispatcherTest\&.php\&.
.SS "testEventReceivesTheDispatcherInstance ()"

.PP
Definition at line 242 of file AbstractEventDispatcherTest\&.php\&.
.SS "testEventReceivesTheDispatcherInstanceAsArgument ()"

.PP
Definition at line 252 of file AbstractEventDispatcherTest\&.php\&.
.SS "testGetAllListenersSortsByPriority ()"

.PP
Definition at line 86 of file AbstractEventDispatcherTest\&.php\&.
.SS "testGetListenersSortsByPriority ()"

.PP
Definition at line 64 of file AbstractEventDispatcherTest\&.php\&.
.SS "testGetListenersWhenAddedCallbackListenerIsRemoved ()"

.PP
Definition at line 287 of file AbstractEventDispatcherTest\&.php\&.
.SS "testHasListenersWhenAddedCallbackListenerIsRemoved ()"

.PP
Definition at line 279 of file AbstractEventDispatcherTest\&.php\&.
.SS "testHasListenersWithoutEventsReturnsFalseAfterHasListenersWithEventHasBeenCalled ()"

.PP
Definition at line 295 of file AbstractEventDispatcherTest\&.php\&.
.SS "testInitialState ()"

.PP
Definition at line 46 of file AbstractEventDispatcherTest\&.php\&.
.SS "testRemoveListener ()"

.PP
Definition at line 170 of file AbstractEventDispatcherTest\&.php\&.
.SS "testRemoveSubscriber ()"

.PP
Definition at line 212 of file AbstractEventDispatcherTest\&.php\&.
.SS "testRemoveSubscriberWithMultipleListeners ()"

.PP
Definition at line 232 of file AbstractEventDispatcherTest\&.php\&.
.SS "testRemoveSubscriberWithPriorities ()"

.PP
Definition at line 223 of file AbstractEventDispatcherTest\&.php\&.
.SS "testStopEventPropagation ()"

.PP
Definition at line 137 of file AbstractEventDispatcherTest\&.php\&.
.SS "testWorkaroundForPhpBug62976 ()"

.PP
\fBSee also:\fP
.RS 4
https://bugs.php.net/bug.php?id=62976
.RE
.PP
This bug affects:
.IP "\(bu" 2
The \fBPHP\fP 5\&.3 branch for versions < 5\&.3\&.18
.IP "\(bu" 2
The \fBPHP\fP 5\&.4 branch for versions < 5\&.4\&.8
.IP "\(bu" 2
The \fBPHP\fP 5\&.5 branch is not affected 
.PP

.PP
Definition at line 271 of file AbstractEventDispatcherTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const postBar = 'post\&.bar'"

.PP
Definition at line 23 of file AbstractEventDispatcherTest\&.php\&.
.SS "const postFoo = '\fBpost\&.foo\fP'"

.PP
Definition at line 21 of file AbstractEventDispatcherTest\&.php\&.
.SS "const preBar = 'pre\&.bar'"

.PP
Definition at line 22 of file AbstractEventDispatcherTest\&.php\&.
.SS "const preFoo = '\fBpre\&.foo\fP'"

.PP
Definition at line 20 of file AbstractEventDispatcherTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
