.TH "ClassNotFoundFatalErrorHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClassNotFoundFatalErrorHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestHandleClassNotFound\fP ($error, $translatedMessage)"
.br
.ti -1c
.RI "\fBtestLegacyHandleClassNotFound\fP ($error, $translatedMessage, $autoloader)"
.br
.ti -1c
.RI "\fBprovideClassNotFoundData\fP ()"
.br
.ti -1c
.RI "\fBprovideLegacyClassNotFoundData\fP ()"
.br
.ti -1c
.RI "\fBtestCannotRedeclareClass\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file ClassNotFoundFatalErrorHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "provideClassNotFoundData ()"

.PP
Definition at line 65 of file ClassNotFoundFatalErrorHandlerTest\&.php\&.
.SS "provideLegacyClassNotFoundData ()"

.PP
Definition at line 116 of file ClassNotFoundFatalErrorHandlerTest\&.php\&.
.SS "testCannotRedeclareClass ()"

.PP
Definition at line 160 of file ClassNotFoundFatalErrorHandlerTest\&.php\&.
.SS "testHandleClassNotFound ( $error,  $translatedMessage)"
provideClassNotFoundData 
.PP
Definition at line 24 of file ClassNotFoundFatalErrorHandlerTest\&.php\&.
.SS "testLegacyHandleClassNotFound ( $error,  $translatedMessage,  $autoloader)"
provideLegacyClassNotFoundData  legacy 
.PP
Definition at line 41 of file ClassNotFoundFatalErrorHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
