.TH "XliffFileDumper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XliffFileDumper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileDumper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdump\fP (\fBMessageCatalogue\fP $messages, $\fBoptions\fP=array())"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBformat\fP (\fBMessageCatalogue\fP $messages, $domain)"
.br
.ti -1c
.RI "\fBgetExtension\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBXliffFileDumper\fP generates xliff files from a message catalogue\&.
.PP
\fBAuthor:\fP
.RS 4
Michel Salib michelsalib@hotmail.com 
.RE
.PP

.PP
Definition at line 21 of file XliffFileDumper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "dump (\fBMessageCatalogue\fP $messages,  $options = \fCarray()\fP)"
{Dumps the message catalogue\&.
.PP
\fBParameters:\fP
.RS 4
\fI$messages\fP The message catalogue 
.br
\fI$options\fP Options that are used by the dumper
.RE
.PP
} 
.PP
Implements \fBDumperInterface\fP\&.
.PP
Definition at line 31 of file XliffFileDumper\&.php\&.
.SS "format (\fBMessageCatalogue\fP $messages,  $domain)\fC [protected]\fP"
{} 
.PP
Definition at line 45 of file XliffFileDumper\&.php\&.
.SS "getExtension ()\fC [protected]\fP"
{} 
.PP
Definition at line 105 of file XliffFileDumper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
