.TH "ApplicationTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ApplicationTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructor\fP ()"
.br
.ti -1c
.RI "\fBtestSetGetName\fP ()"
.br
.ti -1c
.RI "\fBtestSetGetVersion\fP ()"
.br
.ti -1c
.RI "\fBtestGetLongVersion\fP ()"
.br
.ti -1c
.RI "\fBtestHelp\fP ()"
.br
.ti -1c
.RI "\fBtestAll\fP ()"
.br
.ti -1c
.RI "\fBtestRegister\fP ()"
.br
.ti -1c
.RI "\fBtestAdd\fP ()"
.br
.ti -1c
.RI "\fBtestAddCommandWithEmptyConstructor\fP ()"
.br
.ti -1c
.RI "\fBtestHasGet\fP ()"
.br
.ti -1c
.RI "\fBtestSilentHelp\fP ()"
.br
.ti -1c
.RI "\fBtestGetInvalidCommand\fP ()"
.br
.ti -1c
.RI "\fBtestGetNamespaces\fP ()"
.br
.ti -1c
.RI "\fBtestFindNamespace\fP ()"
.br
.ti -1c
.RI "\fBtestFindNamespaceWithSubnamespaces\fP ()"
.br
.ti -1c
.RI "\fBtestFindAmbiguousNamespace\fP ()"
.br
.ti -1c
.RI "\fBtestFindInvalidNamespace\fP ()"
.br
.ti -1c
.RI "\fBtestFindUniqueNameButNamespaceName\fP ()"
.br
.ti -1c
.RI "\fBtestFind\fP ()"
.br
.ti -1c
.RI "\fBtestFindWithAmbiguousAbbreviations\fP ($abbreviation, $expectedExceptionMessage)"
.br
.ti -1c
.RI "\fBprovideAmbiguousAbbreviations\fP ()"
.br
.ti -1c
.RI "\fBtestFindCommandEqualNamespace\fP ()"
.br
.ti -1c
.RI "\fBtestFindCommandWithAmbiguousNamespacesButUniqueName\fP ()"
.br
.ti -1c
.RI "\fBtestFindCommandWithMissingNamespace\fP ()"
.br
.ti -1c
.RI "\fBtestFindAlternativeExceptionMessageSingle\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBprovideInvalidCommandNamesSingle\fP ()"
.br
.ti -1c
.RI "\fBtestFindAlternativeExceptionMessageMultiple\fP ()"
.br
.ti -1c
.RI "\fBtestFindAlternativeCommands\fP ()"
.br
.ti -1c
.RI "\fBtestFindAlternativeCommandsWithAnAlias\fP ()"
.br
.ti -1c
.RI "\fBtestFindAlternativeNamespace\fP ()"
.br
.ti -1c
.RI "\fBtestFindNamespaceDoesNotFailOnDeepSimilarNamespaces\fP ()"
.br
.ti -1c
.RI "\fBtestFindWithDoubleColonInNameThrowsException\fP ()"
.br
.ti -1c
.RI "\fBtestSetCatchExceptions\fP ()"
.br
.ti -1c
.RI "\fBtestLegacyAsText\fP ()"
.br
.ti -1c
.RI "\fBtestLegacyAsXml\fP ()"
.br
.ti -1c
.RI "\fBtestRenderException\fP ()"
.br
.ti -1c
.RI "\fBtestRenderExceptionWithDoubleWidthCharacters\fP ()"
.br
.ti -1c
.RI "\fBtestRun\fP ()"
.br
.ti -1c
.RI "\fBtestVerboseValueNotBreakArguments\fP ()"
.br
.ti -1c
.RI "\fBtestRunReturnsIntegerExitCode\fP ()"
.br
.ti -1c
.RI "\fBtestRunReturnsExitCodeOneForExceptionCodeZero\fP ()"
.br
.ti -1c
.RI "\fBtestAddingAlreadySetDefinitionElementData\fP ($def)"
.br
.ti -1c
.RI "\fBgetAddingAlreadySetDefinitionElementData\fP ()"
.br
.ti -1c
.RI "\fBtestGetDefaultHelperSetReturnsDefaultValues\fP ()"
.br
.ti -1c
.RI "\fBtestAddingSingleHelperSetOverwritesDefaultValues\fP ()"
.br
.ti -1c
.RI "\fBtestOverwritingDefaultHelperSetOverwritesDefaultValues\fP ()"
.br
.ti -1c
.RI "\fBtestGetDefaultInputDefinitionReturnsDefaultValues\fP ()"
.br
.ti -1c
.RI "\fBtestOverwritingDefaultInputDefinitionOverwritesDefaultValues\fP ()"
.br
.ti -1c
.RI "\fBtestSettingCustomInputDefinitionOverwritesDefaultValues\fP ()"
.br
.ti -1c
.RI "\fBtestRunWithDispatcher\fP ()"
.br
.ti -1c
.RI "\fBtestRunWithExceptionAndDispatcher\fP ()"
.br
.ti -1c
.RI "\fBtestRunDispatchesAllEventsWithException\fP ()"
.br
.ti -1c
.RI "\fBtestRunWithDispatcherSkippingCommand\fP ()"
.br
.ti -1c
.RI "\fBtestTerminalDimensions\fP ()"
.br
.ti -1c
.RI "\fBtestSetRunCustomDefaultCommand\fP ()"
.br
.ti -1c
.RI "\fBtestCanCheckIfTerminalIsInteractive\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBsetUpBeforeClass\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBnormalizeLineBreaks\fP ($\fBtext\fP)"
.br
.ti -1c
.RI "\fBensureStaticCommandHelp\fP (\fBApplication\fP $application)"
.br
.ti -1c
.RI "\fBgetDispatcher\fP ($skipCommand=false)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "static \fB$fixturesPath\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 33 of file ApplicationTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "ensureStaticCommandHelp (\fBApplication\fP $application)\fC [protected]\fP"
Replaces the dynamic placeholders of the command help text with a static version\&. The placeholder command\&.full_name% includes the script path that is not predictable and can not be tested against\&. 
.PP
Definition at line 62 of file ApplicationTest\&.php\&.
.SS "getAddingAlreadySetDefinitionElementData ()"

.PP
Definition at line 754 of file ApplicationTest\&.php\&.
.SS "getDispatcher ( $skipCommand = \fCfalse\fP)\fC [protected]\fP"

.PP
Definition at line 957 of file ApplicationTest\&.php\&.
.SS "normalizeLineBreaks ( $text)\fC [protected]\fP"

.PP
Definition at line 52 of file ApplicationTest\&.php\&.
.SS "provideAmbiguousAbbreviations ()"

.PP
Definition at line 278 of file ApplicationTest\&.php\&.
.SS "provideInvalidCommandNamesSingle ()"

.PP
Definition at line 326 of file ApplicationTest\&.php\&.
.SS "static setUpBeforeClass ()\fC [static]\fP"

.PP
Definition at line 37 of file ApplicationTest\&.php\&.
.SS "testAdd ()"

.PP
Definition at line 121 of file ApplicationTest\&.php\&.
.SS "testAddCommandWithEmptyConstructor ()"
\fBCommand\fP class 'Foo5Command' is not correctly initialized\&. You probably forgot to call the parent constructor\&. 
.PP
Definition at line 138 of file ApplicationTest\&.php\&.
.SS "testAddingAlreadySetDefinitionElementData ( $def)"
getAddingAlreadySetDefinitionElementData 
.PP
Definition at line 738 of file ApplicationTest\&.php\&.
.SS "testAddingSingleHelperSetOverwritesDefaultValues ()"

.PP
Definition at line 776 of file ApplicationTest\&.php\&.
.SS "testAll ()"

.PP
Definition at line 103 of file ApplicationTest\&.php\&.
.SS "testCanCheckIfTerminalIsInteractive ()"

.PP
Definition at line 1005 of file ApplicationTest\&.php\&.
.SS "testConstructor ()"

.PP
Definition at line 69 of file ApplicationTest\&.php\&.
.SS "testFind ()"

.PP
Definition at line 251 of file ApplicationTest\&.php\&.
.SS "testFindAlternativeCommands ()"

.PP
Definition at line 376 of file ApplicationTest\&.php\&.
.SS "testFindAlternativeCommandsWithAnAlias ()"

.PP
Definition at line 406 of file ApplicationTest\&.php\&.
.SS "testFindAlternativeExceptionMessageMultiple ()"

.PP
Definition at line 334 of file ApplicationTest\&.php\&.
.SS "testFindAlternativeExceptionMessageSingle ( $name)"
provideInvalidCommandNamesSingle    Did you mean this 
.PP
Definition at line 319 of file ApplicationTest\&.php\&.
.SS "testFindAlternativeNamespace ()"

.PP
Definition at line 419 of file ApplicationTest\&.php\&.
.SS "testFindAmbiguousNamespace ()"
The namespace 'f' is ambiguous (foo, foo1)\&. 
.PP
Definition at line 218 of file ApplicationTest\&.php\&.
.SS "testFindCommandEqualNamespace ()"

.PP
Definition at line 287 of file ApplicationTest\&.php\&.
.SS "testFindCommandWithAmbiguousNamespacesButUniqueName ()"

.PP
Definition at line 297 of file ApplicationTest\&.php\&.
.SS "testFindCommandWithMissingNamespace ()"

.PP
Definition at line 306 of file ApplicationTest\&.php\&.
.SS "testFindInvalidNamespace ()"
There are no commands defined in the 'bar' namespace\&. 
.PP
Definition at line 231 of file ApplicationTest\&.php\&.
.SS "testFindNamespace ()"

.PP
Definition at line 196 of file ApplicationTest\&.php\&.
.SS "testFindNamespaceDoesNotFailOnDeepSimilarNamespaces ()"

.PP
Definition at line 448 of file ApplicationTest\&.php\&.
.SS "testFindNamespaceWithSubnamespaces ()"

.PP
Definition at line 206 of file ApplicationTest\&.php\&.
.SS "testFindUniqueNameButNamespaceName ()"
\fBCommand\fP 'foo1' is not defined 
.PP
Definition at line 241 of file ApplicationTest\&.php\&.
.SS "testFindWithAmbiguousAbbreviations ( $abbreviation,  $expectedExceptionMessage)"
provideAmbiguousAbbreviations 
.PP
Definition at line 266 of file ApplicationTest\&.php\&.
.SS "testFindWithDoubleColonInNameThrowsException ()"
\fBCommand\fP 'foo::bar' is not defined\&. 
.PP
Definition at line 462 of file ApplicationTest\&.php\&.
.SS "testGetDefaultHelperSetReturnsDefaultValues ()"

.PP
Definition at line 763 of file ApplicationTest\&.php\&.
.SS "testGetDefaultInputDefinitionReturnsDefaultValues ()"

.PP
Definition at line 810 of file ApplicationTest\&.php\&.
.SS "testGetInvalidCommand ()"
The command 'foofoo' does not exist\&. 
.PP
Definition at line 182 of file ApplicationTest\&.php\&.
.SS "testGetLongVersion ()"

.PP
Definition at line 91 of file ApplicationTest\&.php\&.
.SS "testGetNamespaces ()"

.PP
Definition at line 188 of file ApplicationTest\&.php\&.
.SS "testHasGet ()"

.PP
Definition at line 144 of file ApplicationTest\&.php\&.
.SS "testHelp ()"

.PP
Definition at line 97 of file ApplicationTest\&.php\&.
.SS "testLegacyAsText ()"
legacy 
.PP
Definition at line 496 of file ApplicationTest\&.php\&.
.SS "testLegacyAsXml ()"
legacy 
.PP
Definition at line 510 of file ApplicationTest\&.php\&.
.SS "testOverwritingDefaultHelperSetOverwritesDefaultValues ()"

.PP
Definition at line 793 of file ApplicationTest\&.php\&.
.SS "testOverwritingDefaultInputDefinitionOverwritesDefaultValues ()"

.PP
Definition at line 829 of file ApplicationTest\&.php\&.
.SS "testRegister ()"

.PP
Definition at line 114 of file ApplicationTest\&.php\&.
.SS "testRenderException ()"

.PP
Definition at line 521 of file ApplicationTest\&.php\&.
.SS "testRenderExceptionWithDoubleWidthCharacters ()"

.PP
Definition at line 558 of file ApplicationTest\&.php\&.
.SS "testRun ()"

.PP
Definition at line 589 of file ApplicationTest\&.php\&.
.SS "testRunDispatchesAllEventsWithException ()"

.PP
Definition at line 909 of file ApplicationTest\&.php\&.
.SS "testRunReturnsExitCodeOneForExceptionCodeZero ()"

.PP
Definition at line 719 of file ApplicationTest\&.php\&.
.SS "testRunReturnsIntegerExitCode ()"

.PP
Definition at line 704 of file ApplicationTest\&.php\&.
.SS "testRunWithDispatcher ()"

.PP
Definition at line 875 of file ApplicationTest\&.php\&.
.SS "testRunWithDispatcherSkippingCommand ()"

.PP
Definition at line 926 of file ApplicationTest\&.php\&.
.SS "testRunWithExceptionAndDispatcher ()"
caught 
.PP
Definition at line 894 of file ApplicationTest\&.php\&.
.SS "testSetCatchExceptions ()"

.PP
Definition at line 470 of file ApplicationTest\&.php\&.
.SS "testSetGetName ()"

.PP
Definition at line 77 of file ApplicationTest\&.php\&.
.SS "testSetGetVersion ()"

.PP
Definition at line 84 of file ApplicationTest\&.php\&.
.SS "testSetRunCustomDefaultCommand ()"

.PP
Definition at line 983 of file ApplicationTest\&.php\&.
.SS "testSettingCustomInputDefinitionOverwritesDefaultValues ()"

.PP
Definition at line 851 of file ApplicationTest\&.php\&.
.SS "testSilentHelp ()"

.PP
Definition at line 166 of file ApplicationTest\&.php\&.
.SS "testTerminalDimensions ()"

.PP
Definition at line 942 of file ApplicationTest\&.php\&.
.SS "testVerboseValueNotBreakArguments ()"
Issue #9285
.PP
If the 'verbose' option is just before an argument in ArgvInput, an argument value should not be treated as verbosity value\&. This test will fail with 'Not enough arguments\&.' if broken 
.PP
Definition at line 688 of file ApplicationTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$fixturesPath\fC [static]\fP, \fC [protected]\fP"

.PP
Definition at line 35 of file ApplicationTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
