.TH "ConsoleOutputInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleOutputInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOutputInterface\fP\&.
.PP
Inherited by \fBConsoleOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetErrorOutput\fP ()"
.br
.ti -1c
.RI "\fBsetErrorOutput\fP (\fBOutputInterface\fP $error)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBConsoleOutputInterface\fP is the interface implemented by \fBConsoleOutput\fP class\&. This adds information about stderr output stream\&.
.PP
\fBAuthor:\fP
.RS 4
Dariusz Górecki darek.krk@gmail.com 
.RE
.PP

.PP
Definition at line 20 of file ConsoleOutputInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getErrorOutput ()"
Gets the \fBOutputInterface\fP for errors\&.
.PP
\fBReturns:\fP
.RS 4
\fBOutputInterface\fP 
.RE
.PP

.PP
Implemented in \fBConsoleOutput\fP\&.
.SS "setErrorOutput (\fBOutputInterface\fP $error)"
Sets the \fBOutputInterface\fP used for errors\&.
.PP
\fBParameters:\fP
.RS 4
\fI$error\fP 
.RE
.PP

.PP
Implemented in \fBConsoleOutput\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
