.TH "FileTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestGetMimeTypeUsesMimeTypeGuessers\fP ()"
.br
.ti -1c
.RI "\fBtestGuessExtensionWithoutGuesser\fP ()"
.br
.ti -1c
.RI "\fBtestGuessExtensionIsBasedOnMimeType\fP ()"
.br
.ti -1c
.RI "\fBtestConstructWhenFileNotExists\fP ()"
.br
.ti -1c
.RI "\fBtestMove\fP ()"
.br
.ti -1c
.RI "\fBtestMoveWithNewName\fP ()"
.br
.ti -1c
.RI "\fBgetFilenameFixtures\fP ()"
.br
.ti -1c
.RI "\fBtestMoveWithNonLatinName\fP ($filename, $sanitizedFilename)"
.br
.ti -1c
.RI "\fBtestMoveToAnUnexistentDirectory\fP ()"
.br
.ti -1c
.RI "\fBtestGetExtension\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateMockGuesser\fP ($\fBpath\fP, $mimeType)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$file\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file FileTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createMockGuesser ( $path,  $mimeType)\fC [protected]\fP"

.PP
Definition at line 157 of file FileTest\&.php\&.
.SS "getFilenameFixtures ()"

.PP
Definition at line 94 of file FileTest\&.php\&.
.SS "testConstructWhenFileNotExists ()"

.PP
Definition at line 48 of file FileTest\&.php\&.
.SS "testGetExtension ()"

.PP
Definition at line 151 of file FileTest\&.php\&.
.SS "testGetMimeTypeUsesMimeTypeGuessers ()"

.PP
Definition at line 21 of file FileTest\&.php\&.
.SS "testGuessExtensionIsBasedOnMimeType ()"

.PP
Definition at line 38 of file FileTest\&.php\&.
.SS "testGuessExtensionWithoutGuesser ()"

.PP
Definition at line 31 of file FileTest\&.php\&.
.SS "testMove ()"

.PP
Definition at line 55 of file FileTest\&.php\&.
.SS "testMoveToAnUnexistentDirectory ()"

.PP
Definition at line 129 of file FileTest\&.php\&.
.SS "testMoveWithNewName ()"

.PP
Definition at line 75 of file FileTest\&.php\&.
.SS "testMoveWithNonLatinName ( $filename,  $sanitizedFilename)"
getFilenameFixtures 
.PP
Definition at line 109 of file FileTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$file\fC [protected]\fP"

.PP
Definition at line 19 of file FileTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
