.TH "JsonResponse" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonResponse \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBResponse\fP\&.
.PP
Inherited by \fBJsonResponse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBdata\fP=null, $status=200, $headers=array())"
.br
.ti -1c
.RI "\fBsetCallback\fP ($\fBcallback\fP=null)"
.br
.ti -1c
.RI "\fBsetData\fP ($\fBdata\fP=array())"
.br
.ti -1c
.RI "\fBgetEncodingOptions\fP ()"
.br
.ti -1c
.RI "\fBsetEncodingOptions\fP ($encodingOptions)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcreate\fP ($\fBdata\fP=null, $status=200, $headers=array())"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBupdate\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$data\fP"
.br
.ti -1c
.RI "\fB$callback\fP"
.br
.ti -1c
.RI "\fB$encodingOptions\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBResponse\fP represents an HTTP response in JSON format\&.
.PP
Note that this class does not force the returned JSON content to be an object\&. It is however recommended that you do return an object as it protects yourself against XSSI and JSON-JavaScript Hijacking\&.
.PP
\fBSee also:\fP
.RS 4
https://www.owasp.org/index.php/OWASP_AJAX_Security_Guidelines#Always_return_JSON_with_an_Object_on_the_outside
.RE
.PP
\fBAuthor:\fP
.RS 4
Igor Wiedler igor@wiedler.ch 
.RE
.PP

.PP
Definition at line 25 of file JsonResponse\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $data = \fCnull\fP,  $status = \fC200\fP,  $headers = \fCarray()\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$data\fP The response data 
.br
\fI$status\fP The response status code 
.br
\fI$headers\fP An array of response headers 
.RE
.PP

.PP
Definition at line 38 of file JsonResponse\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static create ( $data = \fCnull\fP,  $status = \fC200\fP,  $headers = \fCarray()\fP)\fC [static]\fP"
{} 
.PP
Definition at line 55 of file JsonResponse\&.php\&.
.SS "getEncodingOptions ()"
Returns options used while encoding data to JSON\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 134 of file JsonResponse\&.php\&.
.SS "setCallback ( $callback = \fCnull\fP)"
Sets the JSONP callback\&.
.PP
\fBParameters:\fP
.RS 4
\fI$callback\fP The JSONP callback or null to use none
.RE
.PP
\fBReturns:\fP
.RS 4
\fBJsonResponse\fP
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 69 of file JsonResponse\&.php\&.
.SS "setData ( $data = \fCarray()\fP)"
Sets the data to be sent as JSON\&.
.PP
\fBParameters:\fP
.RS 4
\fI$data\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBJsonResponse\fP
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 96 of file JsonResponse\&.php\&.
.SS "setEncodingOptions ( $encodingOptions)"
Sets options used while encoding data to JSON\&.
.PP
\fBParameters:\fP
.RS 4
\fI$encodingOptions\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBJsonResponse\fP 
.RE
.PP

.PP
Definition at line 146 of file JsonResponse\&.php\&.
.SS "update ()\fC [protected]\fP"
Updates the content and headers according to the JSON data and callback\&.
.PP
\fBReturns:\fP
.RS 4
\fBJsonResponse\fP 
.RE
.PP

.PP
Definition at line 158 of file JsonResponse\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBcallback\fP\fC [protected]\fP"

.PP
Definition at line 28 of file JsonResponse\&.php\&.
.SS "$\fBdata\fP\fC [protected]\fP"

.PP
Definition at line 27 of file JsonResponse\&.php\&.
.SS "$encodingOptions\fC [protected]\fP"

.PP
Definition at line 29 of file JsonResponse\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
