.TH "Security" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Security \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBACCESS_DENIED_ERROR\fP = '_security\&.403_error'"
.br
.ti -1c
.RI "const \fBAUTHENTICATION_ERROR\fP = '_security\&.last_error'"
.br
.ti -1c
.RI "const \fBLAST_USERNAME\fP = '_security\&.last_username'"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class holds security information\&.
.PP
\fBAuthor:\fP
.RS 4
Johannes M\&. Schmitt schmittjoh@gmail.com 
.RE
.PP

.PP
Definition at line 19 of file Security\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const ACCESS_DENIED_ERROR = '_security\&.403_error'"

.PP
Definition at line 21 of file Security\&.php\&.
.SS "const AUTHENTICATION_ERROR = '_security\&.last_error'"

.PP
Definition at line 22 of file Security\&.php\&.
.SS "const LAST_USERNAME = '_security\&.last_username'"

.PP
Definition at line 23 of file Security\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
