.TH "TokenStorageInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TokenStorageInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTokenStorage\fP, and \fBSecurityContextInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetToken\fP ()"
.br
.ti -1c
.RI "\fBsetToken\fP (\fBTokenInterface\fP $token=null)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBTokenStorageInterface\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Johannes M\&. Schmitt schmittjoh@gmail.com 
.RE
.PP

.PP
Definition at line 21 of file TokenStorageInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getToken ()"
Returns the current security token\&.
.PP
\fBReturns:\fP
.RS 4
TokenInterface|null \fBA\fP \fBTokenInterface\fP instance or null if no authentication information is available 
.RE
.PP

.PP
Implemented in \fBSecurityContext\fP, and \fBTokenStorage\fP\&.
.SS "setToken (\fBTokenInterface\fP $token = \fCnull\fP)"
Sets the authentication token\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP \fBA\fP \fBTokenInterface\fP token, or null if no further authentication information should be stored 
.RE
.PP

.PP
Implemented in \fBSecurityContext\fP, and \fBTokenStorage\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
