.TH "GeneratorDumperInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GeneratorDumperInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGeneratorDumper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdump\fP (array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBgetRoutes\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBGeneratorDumperInterface\fP is the interface that all generator dumper classes must implement\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 23 of file GeneratorDumperInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "dump (array $options = \fCarray()\fP)"
Dumps a set of routes to a string representation of executable code that can then be used to generate a \fBURL\fP of such a route\&.
.PP
\fBParameters:\fP
.RS 4
\fI$options\fP An array of options
.RE
.PP
\fBReturns:\fP
.RS 4
string Executable code 
.RE
.PP

.PP
Implemented in \fBPhpGeneratorDumper\fP\&.
.SS "getRoutes ()"
Gets the routes to dump\&.
.PP
\fBReturns:\fP
.RS 4
\fBRouteCollection\fP \fBA\fP \fBRouteCollection\fP instance 
.RE
.PP

.PP
Implemented in \fBGeneratorDumper\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
