.TH "AnonymousToken" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AnonymousToken \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAbstractToken\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($key, $user, array $roles=array())"
.br
.ti -1c
.RI "\fBgetCredentials\fP ()"
.br
.ti -1c
.RI "\fBgetKey\fP ()"
.br
.ti -1c
.RI "\fBserialize\fP ()"
.br
.ti -1c
.RI "\fBunserialize\fP ($serialized)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAnonymousToken\fP represents an anonymous token\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 21 of file AnonymousToken\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $key,  $user, array $roles = \fCarray()\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The key shared with the authentication provider 
.br
\fI$user\fP The user 
.br
\fIRoleInterface[]\fP $roles An array of roles 
.RE
.PP

.PP
Definition at line 32 of file AnonymousToken\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getCredentials ()"
{Returns the user credentials\&.
.PP
\fBReturns:\fP
.RS 4
mixed The user credentials
.RE
.PP
} 
.PP
Implements \fBTokenInterface\fP\&.
.PP
Definition at line 44 of file AnonymousToken\&.php\&.
.SS "getKey ()"
Returns the key\&.
.PP
\fBReturns:\fP
.RS 4
string The Key 
.RE
.PP

.PP
Definition at line 54 of file AnonymousToken\&.php\&.
.SS "serialize ()"
{} 
.PP
Definition at line 62 of file AnonymousToken\&.php\&.
.SS "unserialize ( $serialized)"
{} 
.PP
Definition at line 70 of file AnonymousToken\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
