.TH "HIncludeFragmentRenderer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HIncludeFragmentRenderer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRoutableFragmentRenderer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($templating=null, \fBUriSigner\fP $signer=null, $globalDefaultTemplate=null, $charset= 'utf-8')"
.br
.ti -1c
.RI "\fBsetTemplating\fP ($templating)"
.br
.ti -1c
.RI "\fBhasTemplating\fP ()"
.br
.ti -1c
.RI "\fBrender\fP ($uri, \fBRequest\fP $request, array $\fBoptions\fP=array())"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Implements the Hinclude rendering strategy\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 25 of file HIncludeFragmentRenderer\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $templating = \fCnull\fP, \fBUriSigner\fP $signer = \fCnull\fP,  $globalDefaultTemplate = \fCnull\fP,  $charset = \fC'utf-8'\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$templating\fP An EngineInterface or a  instance 
.br
\fI$signer\fP \fBA\fP \fBUriSigner\fP instance 
.br
\fI$globalDefaultTemplate\fP The global default content (it can be a template name or the content) 
.br
\fI$charset\fP 
.RE
.PP

.PP
Definition at line 40 of file HIncludeFragmentRenderer\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getName ()"
{Gets the name of the strategy\&.
.PP
\fBReturns:\fP
.RS 4
string The strategy name
.RE
.PP
} 
.PP
Implements \fBFragmentRendererInterface\fP\&.
.PP
Definition at line 160 of file HIncludeFragmentRenderer\&.php\&.
.SS "hasTemplating ()"
Checks if a templating engine has been set\&.
.PP
\fBReturns:\fP
.RS 4
bool true if the templating engine has been set, false otherwise 
.RE
.PP

.PP
Definition at line 69 of file HIncludeFragmentRenderer\&.php\&.
.SS "render ( $uri, \fBRequest\fP $request, array $options = \fCarray()\fP)"
{Renders a URI and returns the \fBResponse\fP content\&.
.PP
\fBParameters:\fP
.RS 4
\fI$uri\fP \fBA\fP URI as a string or a ControllerReference instance 
.br
\fI$request\fP \fBA\fP \fBRequest\fP instance 
.br
\fI$options\fP An array of options
.RE
.PP
\fBReturns:\fP
.RS 4
\fBResponse\fP \fBA\fP \fBResponse\fP instance
.RE
.PP
}
.PP
Additional available options:
.PP
.IP "\(bu" 2
default: The default content (it can be a template name or the content)
.IP "\(bu" 2
id: An optional hx:include tag id attribute
.IP "\(bu" 2
attributes: An optional array of hx:include tag attributes 
.PP

.PP
Implements \fBFragmentRendererInterface\fP\&.
.PP
Definition at line 83 of file HIncludeFragmentRenderer\&.php\&.
.SS "setTemplating ( $templating)"
Sets the templating engine to use to render the default content\&.
.PP
\fBParameters:\fP
.RS 4
\fI$templating\fP An EngineInterface or a  instance
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 55 of file HIncludeFragmentRenderer\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
