.TH "EsiFragmentRendererTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EsiFragmentRendererTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestRenderFallbackToInlineStrategyIfNoRequest\fP ()"
.br
.ti -1c
.RI "\fBtestRenderFallbackToInlineStrategyIfEsiNotSupported\fP ()"
.br
.ti -1c
.RI "\fBtestRender\fP ()"
.br
.ti -1c
.RI "\fBtestRenderControllerReference\fP ()"
.br
.ti -1c
.RI "\fBtestRenderControllerReferenceWithoutSignerThrowsException\fP ()"
.br
.ti -1c
.RI "\fBtestRenderAltControllerReferenceWithoutSignerThrowsException\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file EsiFragmentRendererTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testRender ()"

.PP
Definition at line 34 of file EsiFragmentRendererTest\&.php\&.
.SS "testRenderAltControllerReferenceWithoutSignerThrowsException ()"

.PP
Definition at line 82 of file EsiFragmentRendererTest\&.php\&.
.SS "testRenderControllerReference ()"

.PP
Definition at line 47 of file EsiFragmentRendererTest\&.php\&.
.SS "testRenderControllerReferenceWithoutSignerThrowsException ()"

.PP
Definition at line 68 of file EsiFragmentRendererTest\&.php\&.
.SS "testRenderFallbackToInlineStrategyIfEsiNotSupported ()"

.PP
Definition at line 28 of file EsiFragmentRendererTest\&.php\&.
.SS "testRenderFallbackToInlineStrategyIfNoRequest ()"

.PP
Definition at line 22 of file EsiFragmentRendererTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
