.TH "RouteCompilerInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RouteCompilerInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRouteCompiler\fP, and \fBRouteCompiler\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcompile\fP (\fBRoute\fP $route)"
.br
.ti -1c
.RI "static \fBcompile\fP (\fBRoute\fP $route)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBRouteCompilerInterface\fP is the interface that all \fBRouteCompiler\fP classes must implement\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 7893 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static compile (\fBRoute\fP $route)\fC [static]\fP"
Compiles the current route instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$route\fP \fBA\fP \fBRoute\fP instance
.RE
.PP
\fBReturns:\fP
.RS 4
\fBCompiledRoute\fP \fBA\fP \fBCompiledRoute\fP instance
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implemented in \fBRouteCompiler\fP, and \fBRouteCompiler\fP\&.
.SS "static compile (\fBRoute\fP $route)\fC [static]\fP"

.PP
Implemented in \fBRouteCompiler\fP, and \fBRouteCompiler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
