.TH "MongoDbProfilerStorageTestDataCollector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MongoDbProfilerStorageTestDataCollector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDataCollector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetData\fP ($\fBdata\fP)"
.br
.ti -1c
.RI "\fBgetData\fP ()"
.br
.ti -1c
.RI "\fBcollect\fP (\fBRequest\fP $request, \fBResponse\fP $response,\\Exception $exception=null)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 28 of file MongoDbProfilerStorageTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "collect (\fBRequest\fP $request, \fBResponse\fP $response, \\Exception $exception = \fCnull\fP)"
Collects data for the given \fBRequest\fP and \fBResponse\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$request\fP \fBA\fP \fBRequest\fP instance 
.br
\fI$response\fP \fBA\fP \fBResponse\fP instance 
.br
\fI$exception\fP An \fBException\fP instance
.RE
.PP

.PP
Implements \fBDataCollectorInterface\fP\&.
.PP
Definition at line 40 of file MongoDbProfilerStorageTest\&.php\&.
.SS "getData ()"

.PP
Definition at line 35 of file MongoDbProfilerStorageTest\&.php\&.
.SS "getName ()"
Returns the name of the collector\&.
.PP
\fBReturns:\fP
.RS 4
string The collector name
.RE
.PP

.PP
Implements \fBDataCollectorInterface\fP\&.
.PP
Definition at line 44 of file MongoDbProfilerStorageTest\&.php\&.
.SS "setData ( $data)"

.PP
Definition at line 30 of file MongoDbProfilerStorageTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
