.TH "ExpressionVoterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExpressionVoterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSupportsAttribute\fP ()"
.br
.ti -1c
.RI "\fBtestVote\fP ($roles, $attributes, $expected, $tokenExpectsGetRoles=true, $expressionLanguageExpectsEvaluate=true)"
.br
.ti -1c
.RI "\fBgetVoteTests\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetToken\fP (array $roles, $tokenExpectsGetRoles=true)"
.br
.ti -1c
.RI "\fBcreateExpressionLanguage\fP ($expressionLanguageExpectsEvaluate=true)"
.br
.ti -1c
.RI "\fBcreateTrustResolver\fP ()"
.br
.ti -1c
.RI "\fBcreateRoleHierarchy\fP ()"
.br
.ti -1c
.RI "\fBcreateExpression\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file ExpressionVoterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createExpression ()\fC [protected]\fP"

.PP
Definition at line 91 of file ExpressionVoterTest\&.php\&.
.SS "createExpressionLanguage ( $expressionLanguageExpectsEvaluate = \fCtrue\fP)\fC [protected]\fP"

.PP
Definition at line 68 of file ExpressionVoterTest\&.php\&.
.SS "createRoleHierarchy ()\fC [protected]\fP"

.PP
Definition at line 86 of file ExpressionVoterTest\&.php\&.
.SS "createTrustResolver ()\fC [protected]\fP"

.PP
Definition at line 81 of file ExpressionVoterTest\&.php\&.
.SS "getToken (array $roles,  $tokenExpectsGetRoles = \fCtrue\fP)\fC [protected]\fP"

.PP
Definition at line 52 of file ExpressionVoterTest\&.php\&.
.SS "getVoteTests ()"

.PP
Definition at line 39 of file ExpressionVoterTest\&.php\&.
.SS "testSupportsAttribute ()"

.PP
Definition at line 20 of file ExpressionVoterTest\&.php\&.
.SS "testVote ( $roles,  $attributes,  $expected,  $tokenExpectsGetRoles = \fCtrue\fP,  $expressionLanguageExpectsEvaluate = \fCtrue\fP)"
getVoteTests 
.PP
Definition at line 32 of file ExpressionVoterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
