.TH "PdoSessionHandlerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PdoSessionHandlerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestWrongPdoErrMode\fP ()"
.br
.ti -1c
.RI "\fBtestInexistentTable\fP ()"
.br
.ti -1c
.RI "\fBtestCreateTableTwice\fP ()"
.br
.ti -1c
.RI "\fBtestWithLazyDsnConnection\fP ()"
.br
.ti -1c
.RI "\fBtestWithLazySavePathConnection\fP ()"
.br
.ti -1c
.RI "\fBtestReadWriteReadWithNullByte\fP ()"
.br
.ti -1c
.RI "\fBtestReadConvertsStreamToString\fP ()"
.br
.ti -1c
.RI "\fBtestReadLockedConvertsStreamToString\fP ()"
.br
.ti -1c
.RI "\fBtestReadingRequiresExactlySameId\fP ()"
.br
.ti -1c
.RI "\fBtestWriteDifferentSessionIdThanRead\fP ()"
.br
.ti -1c
.RI "\fBtestWrongUsageStillWorks\fP ()"
.br
.ti -1c
.RI "\fBtestSessionDestroy\fP ()"
.br
.ti -1c
.RI "\fBtestSessionGC\fP ()"
.br
.ti -1c
.RI "\fBtestGetConnection\fP ()"
.br
.ti -1c
.RI "\fBtestGetConnectionConnectsIfNeeded\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.ti -1c
.RI "\fBgetPersistentSqliteDsn\fP ()"
.br
.ti -1c
.RI "\fBgetMemorySqlitePdo\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file PdoSessionHandlerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getMemorySqlitePdo ()\fC [protected]\fP"

.PP
Definition at line 42 of file PdoSessionHandlerTest\&.php\&.
.SS "getPersistentSqliteDsn ()\fC [protected]\fP"

.PP
Definition at line 35 of file PdoSessionHandlerTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 20 of file PdoSessionHandlerTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 27 of file PdoSessionHandlerTest\&.php\&.
.SS "testCreateTableTwice ()"

.PP
Definition at line 78 of file PdoSessionHandlerTest\&.php\&.
.SS "testGetConnection ()"

.PP
Definition at line 294 of file PdoSessionHandlerTest\&.php\&.
.SS "testGetConnectionConnectsIfNeeded ()"

.PP
Definition at line 304 of file PdoSessionHandlerTest\&.php\&.
.SS "testInexistentTable ()"

.PP
Definition at line 66 of file PdoSessionHandlerTest\&.php\&.
.SS "testReadConvertsStreamToString ()"

.PP
Definition at line 138 of file PdoSessionHandlerTest\&.php\&.
.SS "testReadingRequiresExactlySameId ()"

.PP
Definition at line 185 of file PdoSessionHandlerTest\&.php\&.
.SS "testReadLockedConvertsStreamToString ()"

.PP
Definition at line 155 of file PdoSessionHandlerTest\&.php\&.
.SS "testReadWriteReadWithNullByte ()"

.PP
Definition at line 121 of file PdoSessionHandlerTest\&.php\&.
.SS "testSessionDestroy ()"

.PP
Definition at line 242 of file PdoSessionHandlerTest\&.php\&.
.SS "testSessionGC ()"

.PP
Definition at line 265 of file PdoSessionHandlerTest\&.php\&.
.SS "testWithLazyDsnConnection ()"

.PP
Definition at line 84 of file PdoSessionHandlerTest\&.php\&.
.SS "testWithLazySavePathConnection ()"

.PP
Definition at line 102 of file PdoSessionHandlerTest\&.php\&.
.SS "testWriteDifferentSessionIdThanRead ()"
Simulates session_regenerate_id(true) which will require an INSERT or UPDATE (replace) 
.PP
Definition at line 210 of file PdoSessionHandlerTest\&.php\&.
.SS "testWrongPdoErrMode ()"

.PP
Definition at line 55 of file PdoSessionHandlerTest\&.php\&.
.SS "testWrongUsageStillWorks ()"

.PP
Definition at line 226 of file PdoSessionHandlerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
