.TH "ControllerResolverInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ControllerResolverInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBControllerResolver\fP, \fBTraceableControllerResolver\fP, \fBTestHttpKernel\fP, \fBTestMultipleHttpKernel\fP, and \fBTestHttpKernel\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetController\fP (\fBRequest\fP $request)"
.br
.ti -1c
.RI "\fBgetArguments\fP (\fBRequest\fP $request, $controller)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBA\fP \fBControllerResolverInterface\fP implementation knows how to determine the controller to execute based on a \fBRequest\fP object\&.
.PP
It can also determine the arguments to pass to the \fBController\fP\&.
.PP
\fBA\fP \fBController\fP can be any valid \fBPHP\fP callable\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 28 of file ControllerResolverInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getArguments (\fBRequest\fP $request,  $controller)"
Returns the arguments to pass to the controller\&.
.PP
\fBParameters:\fP
.RS 4
\fI$request\fP \fBA\fP \fBRequest\fP instance 
.br
\fI$controller\fP \fBA\fP \fBPHP\fP callable
.RE
.PP
\fBReturns:\fP
.RS 4
array An array of arguments to pass to the controller
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implemented in \fBControllerResolver\fP, \fBTestHttpKernel\fP, \fBTestMultipleHttpKernel\fP, \fBTraceableControllerResolver\fP, and \fBTestHttpKernel\fP\&.
.SS "getController (\fBRequest\fP $request)"
Returns the \fBController\fP instance associated with a \fBRequest\fP\&.
.PP
As several resolvers can exist for a single application, a resolver must return false when it is not able to determine the controller\&.
.PP
The resolver must only throw an exception when it should be able to load controller but cannot because of some errors made by the developer\&.
.PP
\fBParameters:\fP
.RS 4
\fI$request\fP \fBA\fP \fBRequest\fP instance
.RE
.PP
\fBReturns:\fP
.RS 4
callable|false \fBA\fP \fBPHP\fP callable representing the \fBController\fP, or false if this resolver is not able to determine the controller
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Implemented in \fBTestHttpKernel\fP, \fBTestMultipleHttpKernel\fP, \fBControllerResolver\fP, \fBTraceableControllerResolver\fP, and \fBTestHttpKernel\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
