.TH "DateRangeFilterIterator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateRangeFilterIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFilterIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\\Iterator $iterator, array $comparators)"
.br
.ti -1c
.RI "\fBaccept\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDateRangeFilterIterator\fP filters out files that are not in the given date range (last modified dates)\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 21 of file DateRangeFilterIterator\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\\Iterator $iterator, array $comparators)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$iterator\fP The \fBIterator\fP to filter 
.br
\fIDateComparator[]\fP $comparators An array of DateComparator instances 
.RE
.PP

.PP
Definition at line 31 of file DateRangeFilterIterator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "accept ()"
Filters the iterator values\&.
.PP
\fBReturns:\fP
.RS 4
bool true if the value should be kept, false otherwise 
.RE
.PP

.PP
Definition at line 43 of file DateRangeFilterIterator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
