.TH "InlineTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InlineTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestParse\fP ($yaml, $value)"
.br
.ti -1c
.RI "\fBtestParseWithMapObjects\fP ($yaml, $value)"
.br
.ti -1c
.RI "\fBtestDump\fP ($yaml, $value)"
.br
.ti -1c
.RI "\fBtestDumpNumericValueWithLocale\fP ()"
.br
.ti -1c
.RI "\fBtestHashStringsResemblingExponentialNumericsShouldNotBeChangedToINF\fP ()"
.br
.ti -1c
.RI "\fBtestParseScalarWithIncorrectlyQuotedStringShouldThrowException\fP ()"
.br
.ti -1c
.RI "\fBtestParseScalarWithIncorrectlyDoubleQuotedStringShouldThrowException\fP ()"
.br
.ti -1c
.RI "\fBtestParseInvalidMappingKeyShouldThrowException\fP ()"
.br
.ti -1c
.RI "\fBtestParseInvalidMappingShouldThrowException\fP ()"
.br
.ti -1c
.RI "\fBtestParseInvalidSequenceShouldThrowException\fP ()"
.br
.ti -1c
.RI "\fBtestParseScalarWithCorrectlyQuotedStringShouldReturnString\fP ()"
.br
.ti -1c
.RI "\fBtestParseReferences\fP ($yaml, $expected)"
.br
.ti -1c
.RI "\fBgetDataForParseReferences\fP ()"
.br
.ti -1c
.RI "\fBtestParseMapReferenceInSequence\fP ()"
.br
.ti -1c
.RI "\fBtestParseUnquotedAsterisk\fP ()"
.br
.ti -1c
.RI "\fBtestParseUnquotedAsteriskFollowedByAComment\fP ()"
.br
.ti -1c
.RI "\fBgetTestsForParse\fP ()"
.br
.ti -1c
.RI "\fBgetTestsForParseWithMapObjects\fP ()"
.br
.ti -1c
.RI "\fBgetTestsForDump\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file InlineTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getDataForParseReferences ()"

.PP
Definition at line 130 of file InlineTest\&.php\&.
.SS "getTestsForDump ()"

.PP
Definition at line 326 of file InlineTest\&.php\&.
.SS "getTestsForParse ()"

.PP
Definition at line 172 of file InlineTest\&.php\&.
.SS "getTestsForParseWithMapObjects ()"

.PP
Definition at line 247 of file InlineTest\&.php\&.
.SS "testDump ( $yaml,  $value)"
getTestsForDump 
.PP
Definition at line 39 of file InlineTest\&.php\&.
.SS "testDumpNumericValueWithLocale ()"

.PP
Definition at line 46 of file InlineTest\&.php\&.
.SS "testHashStringsResemblingExponentialNumericsShouldNotBeChangedToINF ()"

.PP
Definition at line 64 of file InlineTest\&.php\&.
.SS "testParse ( $yaml,  $value)"
getTestsForParse 
.PP
Definition at line 21 of file InlineTest\&.php\&.
.SS "testParseInvalidMappingKeyShouldThrowException ()"

.PP
Definition at line 92 of file InlineTest\&.php\&.
.SS "testParseInvalidMappingShouldThrowException ()"

.PP
Definition at line 101 of file InlineTest\&.php\&.
.SS "testParseInvalidSequenceShouldThrowException ()"

.PP
Definition at line 109 of file InlineTest\&.php\&.
.SS "testParseMapReferenceInSequence ()"

.PP
Definition at line 144 of file InlineTest\&.php\&.
.SS "testParseReferences ( $yaml,  $expected)"
getDataForParseReferences 
.PP
Definition at line 125 of file InlineTest\&.php\&.
.SS "testParseScalarWithCorrectlyQuotedStringShouldReturnString ()"

.PP
Definition at line 114 of file InlineTest\&.php\&.
.SS "testParseScalarWithIncorrectlyDoubleQuotedStringShouldThrowException ()"

.PP
Definition at line 83 of file InlineTest\&.php\&.
.SS "testParseScalarWithIncorrectlyQuotedStringShouldThrowException ()"

.PP
Definition at line 74 of file InlineTest\&.php\&.
.SS "testParseUnquotedAsterisk ()"
\fBA\fP reference must contain at least one character\&. 
.PP
Definition at line 158 of file InlineTest\&.php\&.
.SS "testParseUnquotedAsteriskFollowedByAComment ()"
\fBA\fP reference must contain at least one character\&. 
.PP
Definition at line 167 of file InlineTest\&.php\&.
.SS "testParseWithMapObjects ( $yaml,  $value)"
getTestsForParseWithMapObjects 
.PP
Definition at line 29 of file InlineTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
