.TH "HeaderBag" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HeaderBag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IteratorAggregate, Countable, IteratorAggregate, and Countable\&.
.PP
Inherited by \fBResponseHeaderBag\fP, and \fBResponseHeaderBag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $headers=array())"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBall\fP ()"
.br
.ti -1c
.RI "\fBkeys\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP (array $headers=array())"
.br
.ti -1c
.RI "\fBadd\fP (array $headers)"
.br
.ti -1c
.RI "\fBget\fP ($key, $default=null, $first=true)"
.br
.ti -1c
.RI "\fBset\fP ($key, $\fBvalues\fP, $\fBreplace\fP=true)"
.br
.ti -1c
.RI "\fBhas\fP ($key)"
.br
.ti -1c
.RI "\fBcontains\fP ($key, $value)"
.br
.ti -1c
.RI "\fBremove\fP ($key)"
.br
.ti -1c
.RI "\fBgetDate\fP ($key,\\DateTime $default=null)"
.br
.ti -1c
.RI "\fBaddCacheControlDirective\fP ($key, $value=true)"
.br
.ti -1c
.RI "\fBhasCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBgetCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBremoveCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBgetIterator\fP ()"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.ti -1c
.RI "\fB__construct\fP (array $headers=array())"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBall\fP ()"
.br
.ti -1c
.RI "\fBkeys\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP (array $headers=array())"
.br
.ti -1c
.RI "\fBadd\fP (array $headers)"
.br
.ti -1c
.RI "\fBget\fP ($key, $default=null, $first=true)"
.br
.ti -1c
.RI "\fBset\fP ($key, $\fBvalues\fP, $\fBreplace\fP=true)"
.br
.ti -1c
.RI "\fBhas\fP ($key)"
.br
.ti -1c
.RI "\fBcontains\fP ($key, $value)"
.br
.ti -1c
.RI "\fBremove\fP ($key)"
.br
.ti -1c
.RI "\fBgetDate\fP ($key,\\DateTime $default=null)"
.br
.ti -1c
.RI "\fBaddCacheControlDirective\fP ($key, $value=true)"
.br
.ti -1c
.RI "\fBhasCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBgetCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBremoveCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBgetIterator\fP ()"
.br
.ti -1c
.RI "\fBcount\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetCacheControlHeader\fP ()"
.br
.ti -1c
.RI "\fBparseCacheControl\fP ($header)"
.br
.ti -1c
.RI "\fBgetCacheControlHeader\fP ()"
.br
.ti -1c
.RI "\fBparseCacheControl\fP ($header)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$headers\fP = array()"
.br
.ti -1c
.RI "\fB$cacheControl\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBHeaderBag\fP is a container for HTTP headers\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 3592 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $headers = \fCarray()\fP)"

.PP
Definition at line 3596 of file compiled\&.php\&.
.SS "__construct (array $headers = \fCarray()\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$headers\fP An array of HTTP headers
.RE
.PP

.PP
Definition at line 33 of file HeaderBag\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"
Returns the headers as a string\&.
.PP
\fBReturns:\fP
.RS 4
string The headers 
.RE
.PP

.PP
Definition at line 45 of file HeaderBag\&.php\&.
.SS "__toString ()"

.PP
Definition at line 3602 of file compiled\&.php\&.
.SS "add (array $headers)"
Adds new headers the current HTTP headers set\&.
.PP
\fBParameters:\fP
.RS 4
\fI$headers\fP An array of HTTP headers
.RE
.PP

.PP
Definition at line 108 of file HeaderBag\&.php\&.
.SS "add (array $headers)"

.PP
Definition at line 3631 of file compiled\&.php\&.
.SS "addCacheControlDirective ( $key,  $value = \fCtrue\fP)"
Adds a custom Cache-Control directive\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The Cache-Control directive name 
.br
\fI$value\fP The Cache-Control directive value 
.RE
.PP

.PP
Definition at line 249 of file HeaderBag\&.php\&.
.SS "addCacheControlDirective ( $key,  $value = \fCtrue\fP)"

.PP
Definition at line 3690 of file compiled\&.php\&.
.SS "all ()"
Returns the headers\&.
.PP
\fBReturns:\fP
.RS 4
array An array of headers
.RE
.PP

.PP
Definition at line 71 of file HeaderBag\&.php\&.
.SS "all ()"

.PP
Definition at line 3618 of file compiled\&.php\&.
.SS "contains ( $key,  $value)"
Returns true if the given HTTP header contains the given value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The HTTP header name 
.br
\fI$value\fP The HTTP value
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the value is contained in the header, false otherwise
.RE
.PP

.PP
Definition at line 195 of file HeaderBag\&.php\&.
.SS "contains ( $key,  $value)"

.PP
Definition at line 3668 of file compiled\&.php\&.
.SS "count ()"
Returns the number of headers\&.
.PP
\fBReturns:\fP
.RS 4
int The number of headers 
.RE
.PP

.PP
Definition at line 307 of file HeaderBag\&.php\&.
.SS "count ()"

.PP
Definition at line 3712 of file compiled\&.php\&.
.SS "get ( $key,  $default = \fCnull\fP,  $first = \fCtrue\fP)"
Returns a header value by name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The header name 
.br
\fI$default\fP The default value 
.br
\fI$first\fP Whether to return the first value or all header values
.RE
.PP
\fBReturns:\fP
.RS 4
string|array The first header value if $first is true, an array of values otherwise
.RE
.PP

.PP
Definition at line 126 of file HeaderBag\&.php\&.
.SS "get ( $key,  $default = \fCnull\fP,  $first = \fCtrue\fP)"

.PP
Definition at line 3637 of file compiled\&.php\&.
.SS "getCacheControlDirective ( $key)"
Returns a Cache-Control directive value by name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The directive name
.RE
.PP
\fBReturns:\fP
.RS 4
mixed|null The directive value if defined, null otherwise 
.RE
.PP

.PP
Definition at line 275 of file HeaderBag\&.php\&.
.SS "getCacheControlDirective ( $key)"

.PP
Definition at line 3699 of file compiled\&.php\&.
.SS "getCacheControlHeader ()\fC [protected]\fP"

.PP
Definition at line 312 of file HeaderBag\&.php\&.
.SS "getCacheControlHeader ()\fC [protected]\fP"

.PP
Definition at line 3716 of file compiled\&.php\&.
.SS "getDate ( $key, \\DateTime $default = \fCnull\fP)"
Returns the HTTP header value converted to a date\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The parameter key 
.br
\fI$default\fP The default value
.RE
.PP
\fBReturns:\fP
.RS 4
null| The parsed DateTime or the default value if the header does not exist
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 230 of file HeaderBag\&.php\&.
.SS "getDate ( $key, \\DateTime $default = \fCnull\fP)"

.PP
Definition at line 3680 of file compiled\&.php\&.
.SS "getIterator ()"
Returns an iterator for headers\&.
.PP
\fBReturns:\fP
.RS 4
An  instance 
.RE
.PP

.PP
Definition at line 297 of file HeaderBag\&.php\&.
.SS "getIterator ()"

.PP
Definition at line 3708 of file compiled\&.php\&.
.SS "has ( $key)"
Returns true if the HTTP header is defined\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The HTTP header
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the parameter exists, false otherwise
.RE
.PP

.PP
Definition at line 180 of file HeaderBag\&.php\&.
.SS "has ( $key)"

.PP
Definition at line 3664 of file compiled\&.php\&.
.SS "hasCacheControlDirective ( $key)"
Returns true if the Cache-Control directive is defined\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The Cache-Control directive
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the directive exists, false otherwise 
.RE
.PP

.PP
Definition at line 263 of file HeaderBag\&.php\&.
.SS "hasCacheControlDirective ( $key)"

.PP
Definition at line 3695 of file compiled\&.php\&.
.SS "keys ()"
Returns the parameter keys\&.
.PP
\fBReturns:\fP
.RS 4
array An array of parameter keys
.RE
.PP

.PP
Definition at line 83 of file HeaderBag\&.php\&.
.SS "keys ()"

.PP
Definition at line 3622 of file compiled\&.php\&.
.SS "parseCacheControl ( $header)\fC [protected]\fP"
Parses a Cache-Control HTTP header\&.
.PP
\fBParameters:\fP
.RS 4
\fI$header\fP The value of the Cache-Control HTTP header
.RE
.PP
\fBReturns:\fP
.RS 4
array An array representing the attribute values 
.RE
.PP

.PP
Definition at line 338 of file HeaderBag\&.php\&.
.SS "parseCacheControl ( $header)\fC [protected]\fP"

.PP
Definition at line 3732 of file compiled\&.php\&.
.SS "remove ( $key)"
Removes a header\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The HTTP header name
.RE
.PP

.PP
Definition at line 207 of file HeaderBag\&.php\&.
.SS "remove ( $key)"

.PP
Definition at line 3672 of file compiled\&.php\&.
.SS "removeCacheControlDirective ( $key)"
Removes a Cache-Control directive\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The Cache-Control directive 
.RE
.PP

.PP
Definition at line 285 of file HeaderBag\&.php\&.
.SS "removeCacheControlDirective ( $key)"

.PP
Definition at line 3703 of file compiled\&.php\&.
.SS "replace (array $headers = \fCarray()\fP)"
Replaces the current HTTP headers by a new set\&.
.PP
\fBParameters:\fP
.RS 4
\fI$headers\fP An array of HTTP headers
.RE
.PP

.PP
Definition at line 95 of file HeaderBag\&.php\&.
.SS "replace (array $headers = \fCarray()\fP)"

.PP
Definition at line 3626 of file compiled\&.php\&.
.SS "set ( $key,  $values,  $replace = \fCtrue\fP)"
Sets a header by name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$key\fP The key 
.br
\fI$values\fP The value or an array of values 
.br
\fI$replace\fP Whether to replace the actual value or not (true by default)
.RE
.PP

.PP
Definition at line 154 of file HeaderBag\&.php\&.
.SS "set ( $key,  $values,  $replace = \fCtrue\fP)"

.PP
Definition at line 3651 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$cacheControl = array()\fC [protected]\fP"

.PP
Definition at line 3595 of file compiled\&.php\&.
.SS "$headers = array()\fC [protected]\fP"

.PP
Definition at line 3594 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
