.TH "EventTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestIsPropagationStopped\fP ()"
.br
.ti -1c
.RI "\fBtestStopPropagationAndIsPropagationStopped\fP ()"
.br
.ti -1c
.RI "\fBtestLegacySetDispatcher\fP ()"
.br
.ti -1c
.RI "\fBtestLegacyGetDispatcher\fP ()"
.br
.ti -1c
.RI "\fBtestLegacyGetName\fP ()"
.br
.ti -1c
.RI "\fBtestLegacySetName\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$event\fP"
.br
.ti -1c
.RI "\fB$dispatcher\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Test class for \fBEvent\fP\&. 
.PP
Definition at line 20 of file EventTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"
Sets up the fixture, for example, opens a network connection\&. This method is called before a test is executed\&. 
.PP
Definition at line 36 of file EventTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"
Tears down the fixture, for example, closes a network connection\&. This method is called after a test is executed\&. 
.PP
Definition at line 46 of file EventTest\&.php\&.
.SS "testIsPropagationStopped ()"

.PP
Definition at line 52 of file EventTest\&.php\&.
.SS "testLegacyGetDispatcher ()"
legacy 
.PP
Definition at line 76 of file EventTest\&.php\&.
.SS "testLegacyGetName ()"
legacy 
.PP
Definition at line 85 of file EventTest\&.php\&.
.SS "testLegacySetDispatcher ()"
legacy 
.PP
Definition at line 66 of file EventTest\&.php\&.
.SS "testLegacySetName ()"
legacy 
.PP
Definition at line 94 of file EventTest\&.php\&.
.SS "testStopPropagationAndIsPropagationStopped ()"

.PP
Definition at line 57 of file EventTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$dispatcher\fC [protected]\fP"

.PP
Definition at line 30 of file EventTest\&.php\&.
.SS "$\fBevent\fP\fC [protected]\fP"

.PP
Definition at line 25 of file EventTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
