.TH "KernelEvents" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KernelEvents \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBREQUEST\fP = 'kernel\&.request'"
.br
.ti -1c
.RI "const \fBEXCEPTION\fP = 'kernel\&.exception'"
.br
.ti -1c
.RI "const \fBVIEW\fP = 'kernel\&.view'"
.br
.ti -1c
.RI "const \fBCONTROLLER\fP = 'kernel\&.controller'"
.br
.ti -1c
.RI "const \fBRESPONSE\fP = 'kernel\&.response'"
.br
.ti -1c
.RI "const \fBTERMINATE\fP = 'kernel\&.terminate'"
.br
.ti -1c
.RI "const \fBFINISH_REQUEST\fP = 'kernel\&.finish_request'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains all events thrown in the \fBHttpKernel\fP component\&.
.PP
\fBAuthor:\fP
.RS 4
Bernhard Schussek bschussek@gmail.com
.RE
.PP

.PP
Definition at line 21 of file KernelEvents\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const CONTROLLER = 'kernel\&.controller'"

.PP
Definition at line 87 of file KernelEvents\&.php\&.
.SS "const EXCEPTION = 'kernel\&.exception'"

.PP
Definition at line 54 of file KernelEvents\&.php\&.
.SS "const FINISH_REQUEST = 'kernel\&.finish_request'"

.PP
Definition at line 126 of file KernelEvents\&.php\&.
.SS "const REQUEST = 'kernel\&.request'"

.PP
Definition at line 38 of file KernelEvents\&.php\&.
.SS "const RESPONSE = 'kernel\&.response'"

.PP
Definition at line 103 of file KernelEvents\&.php\&.
.SS "const TERMINATE = 'kernel\&.terminate'"

.PP
Definition at line 116 of file KernelEvents\&.php\&.
.SS "const VIEW = 'kernel\&.view'"

.PP
Definition at line 71 of file KernelEvents\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
