.TH "TestMultiplePcreFilterIterator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestMultiplePcreFilterIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMultiplePcreFilterIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBaccept\fP ()"
.br
.ti -1c
.RI "\fBisRegex\fP ($str)"
.br
.ti -1c
.RI "\fBtoRegex\fP ($str)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 47 of file MultiplePcreFilterIteratorTest\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 49 of file MultiplePcreFilterIteratorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "accept ()"

.PP
Definition at line 53 of file MultiplePcreFilterIteratorTest\&.php\&.
.SS "isRegex ( $str)"

.PP
Definition at line 58 of file MultiplePcreFilterIteratorTest\&.php\&.
.SS "toRegex ( $str)"

.PP
Definition at line 63 of file MultiplePcreFilterIteratorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
