.TH "DateComparator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DateComparator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBComparator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($\fBtest\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
DateCompare compiles date comparisons\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 19 of file DateComparator\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $test)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$test\fP \fBA\fP comparison string
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 28 of file DateComparator\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
