.TH "RegisterListenersPassTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterListenersPassTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestEventSubscriberWithoutInterface\fP ()"
.br
.ti -1c
.RI "\fBtestValidEventSubscriber\fP ()"
.br
.ti -1c
.RI "\fBtestPrivateEventListener\fP ()"
.br
.ti -1c
.RI "\fBtestPrivateEventSubscriber\fP ()"
.br
.ti -1c
.RI "\fBtestAbstractEventListener\fP ()"
.br
.ti -1c
.RI "\fBtestAbstractEventSubscriber\fP ()"
.br
.ti -1c
.RI "\fBtestEventSubscriberResolvableClassName\fP ()"
.br
.ti -1c
.RI "\fBtestEventSubscriberUnresolvableClassName\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file RegisterListenersPassTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testAbstractEventListener ()"
The service 'foo' must not be abstract as event listeners are lazy-loaded\&. 
.PP
Definition at line 132 of file RegisterListenersPassTest\&.php\&.
.SS "testAbstractEventSubscriber ()"
The service 'foo' must not be abstract as event subscribers are lazy-loaded\&. 
.PP
Definition at line 146 of file RegisterListenersPassTest\&.php\&.
.SS "testEventSubscriberResolvableClassName ()"

.PP
Definition at line 156 of file RegisterListenersPassTest\&.php\&.
.SS "testEventSubscriberUnresolvableClassName ()"
You have requested a non-existent parameter 'subscriber\&.class' 
.PP
Definition at line 184 of file RegisterListenersPassTest\&.php\&.
.SS "testEventSubscriberWithoutInterface ()"
\fBTests\fP that event subscribers not implementing EventSubscriberInterface trigger an exception\&.
.PP
Definition at line 25 of file RegisterListenersPassTest\&.php\&.
.SS "testPrivateEventListener ()"
The service 'foo' must be public as event listeners are lazy-loaded\&. 
.PP
Definition at line 104 of file RegisterListenersPassTest\&.php\&.
.SS "testPrivateEventSubscriber ()"
The service 'foo' must be public as event subscribers are lazy-loaded\&. 
.PP
Definition at line 118 of file RegisterListenersPassTest\&.php\&.
.SS "testValidEventSubscriber ()"

.PP
Definition at line 61 of file RegisterListenersPassTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
