.TH "MultiplePcreFilterIterator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultiplePcreFilterIterator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFilterIterator\fP, and \fBFilterIterator\fP\&.
.PP
Inherited by \fBFilecontentFilterIterator\fP, \fBFilenameFilterIterator\fP, \fBPathFilterIterator\fP, \fBPathFilterIterator\fP, and \fBTestMultiplePcreFilterIterator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\\Iterator $iterator, array $matchPatterns, array $noMatchPatterns)"
.br
.ti -1c
.RI "\fB__construct\fP (\\Iterator $iterator, array $matchPatterns, array $noMatchPatterns)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBisRegex\fP ($str)"
.br
.ti -1c
.RI "\fBtoRegex\fP ($str)"
.br
.ti -1c
.RI "\fBisRegex\fP ($str)"
.br
.ti -1c
.RI "\fBtoRegex\fP ($str)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$matchRegexps\fP = array()"
.br
.ti -1c
.RI "\fB$noMatchRegexps\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBMultiplePcreFilterIterator\fP filters files using patterns (regexps, globs or strings)\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 15344 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\\Iterator $iterator, array $matchPatterns, array $noMatchPatterns)"

.PP
Definition at line 15348 of file compiled\&.php\&.
.SS "__construct (\\Iterator $iterator, array $matchPatterns, array $noMatchPatterns)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$iterator\fP The \fBIterator\fP to filter 
.br
\fI$matchPatterns\fP An array of patterns that need to match 
.br
\fI$noMatchPatterns\fP An array of patterns that need to not match 
.RE
.PP

.PP
Definition at line 33 of file MultiplePcreFilterIterator\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "isRegex ( $str)\fC [protected]\fP"
Checks whether the string is a regex\&.
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool Whether the given string is a regex 
.RE
.PP

.PP
Definition at line 53 of file MultiplePcreFilterIterator\&.php\&.
.SS "isRegex ( $str)\fC [protected]\fP"

.PP
Definition at line 15358 of file compiled\&.php\&.
.SS "toRegex ( $str)\fC [abstract]\fP, \fC [protected]\fP"
Converts string into regexp\&.
.PP
\fBParameters:\fP
.RS 4
\fI$str\fP Pattern
.RE
.PP
\fBReturns:\fP
.RS 4
string regexp corresponding to a given string 
.RE
.PP

.SS "toRegex ( $str)\fC [abstract]\fP, \fC [protected]\fP"

.SH "Field Documentation"
.PP 
.SS "$matchRegexps = array()\fC [protected]\fP"

.PP
Definition at line 15346 of file compiled\&.php\&.
.SS "$noMatchRegexps = array()\fC [protected]\fP"

.PP
Definition at line 15347 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
