.TH "DumperCollection" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DumperCollection \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits IteratorAggregate\&.
.PP
Inherited by \fBDumperPrefixCollection\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBall\fP ()"
.br
.ti -1c
.RI "\fBadd\fP ($child)"
.br
.ti -1c
.RI "\fBsetAll\fP (array $children)"
.br
.ti -1c
.RI "\fBgetIterator\fP ()"
.br
.ti -1c
.RI "\fBgetRoot\fP ()"
.br
.ti -1c
.RI "\fBhasAttribute\fP ($\fBname\fP)"
.br
.ti -1c
.RI "\fBgetAttribute\fP ($\fBname\fP, $default=null)"
.br
.ti -1c
.RI "\fBsetAttribute\fP ($\fBname\fP, $value)"
.br
.ti -1c
.RI "\fBsetAttributes\fP ($attributes)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBgetParent\fP ()"
.br
.ti -1c
.RI "\fBsetParent\fP (\fBDumperCollection\fP $parent)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Collection of routes\&.
.PP
\fBAuthor:\fP
.RS 4
Arnaud Le Blanc arnaud.lb@gmail.com 
.RE
.PP

.PP
Definition at line 19 of file DumperCollection\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "add ( $child)"
Adds a route or collection\&.
.PP
\fBParameters:\fP
.RS 4
\fIDumperRoute|DumperCollection\fP The route or collection 
.RE
.PP

.PP
Definition at line 51 of file DumperCollection\&.php\&.
.SS "all ()"
Returns the children routes and collections\&.
.PP
\fBReturns:\fP
.RS 4
(DumperCollection|DumperRoute)[] Array of DumperCollection|DumperRoute 
.RE
.PP

.PP
Definition at line 41 of file DumperCollection\&.php\&.
.SS "getAttribute ( $name,  $default = \fCnull\fP)"
Returns an attribute by name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The attribute name 
.br
\fI$default\fP Default value is the attribute doesn't exist
.RE
.PP
\fBReturns:\fP
.RS 4
mixed The attribute value 
.RE
.PP

.PP
Definition at line 134 of file DumperCollection\&.php\&.
.SS "getIterator ()"
Returns an iterator over the children\&.
.PP
\fBReturns:\fP
.RS 4
The iterator 
.RE
.PP

.PP
Definition at line 79 of file DumperCollection\&.php\&.
.SS "getParent ()\fC [protected]\fP"
Returns the parent collection\&.
.PP
\fBReturns:\fP
.RS 4
DumperCollection|null The parent collection or null if the collection has no parent 
.RE
.PP

.PP
Definition at line 99 of file DumperCollection\&.php\&.
.SS "getRoot ()"
Returns the root of the collection\&.
.PP
\fBReturns:\fP
.RS 4
\fBDumperCollection\fP The root collection 
.RE
.PP

.PP
Definition at line 89 of file DumperCollection\&.php\&.
.SS "hasAttribute ( $name)"
Returns true if the attribute is defined\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The attribute name
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the attribute is defined, false otherwise 
.RE
.PP

.PP
Definition at line 121 of file DumperCollection\&.php\&.
.SS "setAll (array $children)"
Sets children\&.
.PP
\fBParameters:\fP
.RS 4
\fI$children\fP The children 
.RE
.PP

.PP
Definition at line 64 of file DumperCollection\&.php\&.
.SS "setAttribute ( $name,  $value)"
Sets an attribute by name\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP The attribute name 
.br
\fI$value\fP The attribute value 
.RE
.PP

.PP
Definition at line 145 of file DumperCollection\&.php\&.
.SS "setAttributes ( $attributes)"
Sets multiple attributes\&.
.PP
\fBParameters:\fP
.RS 4
\fI$attributes\fP The attributes 
.RE
.PP

.PP
Definition at line 155 of file DumperCollection\&.php\&.
.SS "setParent (\fBDumperCollection\fP $parent)\fC [protected]\fP"
Sets the parent collection\&.
.PP
\fBParameters:\fP
.RS 4
\fI$parent\fP The parent collection 
.RE
.PP

.PP
Definition at line 109 of file DumperCollection\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
