.TH "Symfony\Component\Finder\Adapter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\Finder\Adapter \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAbstractAdapter\fP"
.br
.ti -1c
.RI "class \fBAbstractFindAdapter\fP"
.br
.ti -1c
.RI "interface \fBAdapterInterface\fP"
.br
.ti -1c
.RI "class \fBBsdFindAdapter\fP"
.br
.ti -1c
.RI "class \fBGnuFindAdapter\fP"
.br
.ti -1c
.RI "class \fBPhpAdapter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
