.TH "ConcreteFileDumper" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConcreteFileDumper \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFileDumper\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBformat\fP (\fBMessageCatalogue\fP $messages, $domain)"
.br
.ti -1c
.RI "\fBgetExtension\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 59 of file FileDumperTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "format (\fBMessageCatalogue\fP $messages,  $domain)\fC [protected]\fP"

.PP
Definition at line 61 of file FileDumperTest\&.php\&.
.SS "getExtension ()\fC [protected]\fP"

.PP
Definition at line 66 of file FileDumperTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
