.TH "RoleHierarchyVoter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoleHierarchyVoter \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRoleVoter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBRoleHierarchyInterface\fP $roleHierarchy, $prefix= 'ROLE_')"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBextractRoles\fP (\fBTokenInterface\fP $token)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBRoleHierarchyVoter\fP uses a RoleHierarchy to determine the roles granted to the user before voting\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 23 of file RoleHierarchyVoter\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBRoleHierarchyInterface\fP $roleHierarchy,  $prefix = \fC'ROLE_'\fP)"

.PP
Definition at line 27 of file RoleHierarchyVoter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "extractRoles (\fBTokenInterface\fP $token)\fC [protected]\fP"
{} 
.PP
Definition at line 37 of file RoleHierarchyVoter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
