.TH "InlineFragmentRendererTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InlineFragmentRendererTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestRender\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithControllerReference\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithObjectsAsAttributes\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithObjectsAsAttributesPassedAsObjectsInTheController\fP ()"
.br
.ti -1c
.RI "\fBtestRenderWithTrustedHeaderDisabled\fP ()"
.br
.ti -1c
.RI "\fBtestRenderExceptionNoIgnoreErrors\fP ()"
.br
.ti -1c
.RI "\fBtestRenderExceptionIgnoreErrors\fP ()"
.br
.ti -1c
.RI "\fBtestRenderExceptionIgnoreErrorsWithAlt\fP ()"
.br
.ti -1c
.RI "\fBtestExceptionInSubRequestsDoesNotMangleOutputBuffers\fP ()"
.br
.ti -1c
.RI "\fBtestESIHeaderIsKeptInSubrequest\fP ()"
.br
.ti -1c
.RI "\fBtestESIHeaderIsKeptInSubrequestWithTrustedHeaderDisabled\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 22 of file InlineFragmentRendererTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testESIHeaderIsKeptInSubrequest ()"

.PP
Definition at line 174 of file InlineFragmentRendererTest\&.php\&.
.SS "testESIHeaderIsKeptInSubrequestWithTrustedHeaderDisabled ()"

.PP
Definition at line 191 of file InlineFragmentRendererTest\&.php\&.
.SS "testExceptionInSubRequestsDoesNotMangleOutputBuffers ()"

.PP
Definition at line 143 of file InlineFragmentRendererTest\&.php\&.
.SS "testRender ()"

.PP
Definition at line 24 of file InlineFragmentRendererTest\&.php\&.
.SS "testRenderExceptionIgnoreErrors ()"

.PP
Definition at line 95 of file InlineFragmentRendererTest\&.php\&.
.SS "testRenderExceptionIgnoreErrorsWithAlt ()"

.PP
Definition at line 105 of file InlineFragmentRendererTest\&.php\&.
.SS "testRenderExceptionNoIgnoreErrors ()"

.PP
Definition at line 85 of file InlineFragmentRendererTest\&.php\&.
.SS "testRenderWithControllerReference ()"

.PP
Definition at line 31 of file InlineFragmentRendererTest\&.php\&.
.SS "testRenderWithObjectsAsAttributes ()"

.PP
Definition at line 38 of file InlineFragmentRendererTest\&.php\&.
.SS "testRenderWithObjectsAsAttributesPassedAsObjectsInTheController ()"

.PP
Definition at line 52 of file InlineFragmentRendererTest\&.php\&.
.SS "testRenderWithTrustedHeaderDisabled ()"

.PP
Definition at line 70 of file InlineFragmentRendererTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
