.TH "DummyMongoDbProfilerStorage" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DummyMongoDbProfilerStorage \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMongoDbProfilerStorage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMongo\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 20 of file MongoDbProfilerStorageTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getMongo ()"

.PP
Definition at line 22 of file MongoDbProfilerStorageTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
