.TH "ParseException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParseException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRuntimeException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message, $parsedLine=-1, $snippet=null, $parsedFile=null,\\Exception $previous=null)"
.br
.ti -1c
.RI "\fBgetSnippet\fP ()"
.br
.ti -1c
.RI "\fBsetSnippet\fP ($snippet)"
.br
.ti -1c
.RI "\fBgetParsedFile\fP ()"
.br
.ti -1c
.RI "\fBsetParsedFile\fP ($parsedFile)"
.br
.ti -1c
.RI "\fBgetParsedLine\fP ()"
.br
.ti -1c
.RI "\fBsetParsedLine\fP ($parsedLine)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBException\fP class thrown when an error occurs during parsing\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 21 of file ParseException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message,  $parsedLine = \fC-1\fP,  $snippet = \fCnull\fP,  $parsedFile = \fCnull\fP, \\Exception $previous = \fCnull\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$message\fP The error message 
.br
\fI$parsedLine\fP The line where the error occurred 
.br
\fI$snippet\fP The snippet of code near the problem 
.br
\fI$parsedFile\fP The file name where the error occurred 
.br
\fI$previous\fP The previous exception 
.RE
.PP

.PP
Definition at line 37 of file ParseException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getParsedFile ()"
Gets the filename where the error occurred\&.
.PP
This method returns null if a string is parsed\&.
.PP
\fBReturns:\fP
.RS 4
string The filename 
.RE
.PP

.PP
Definition at line 78 of file ParseException\&.php\&.
.SS "getParsedLine ()"
Gets the line where the error occurred\&.
.PP
\fBReturns:\fP
.RS 4
int The file line 
.RE
.PP

.PP
Definition at line 100 of file ParseException\&.php\&.
.SS "getSnippet ()"
Gets the snippet of code near the error\&.
.PP
\fBReturns:\fP
.RS 4
string The snippet of code 
.RE
.PP

.PP
Definition at line 54 of file ParseException\&.php\&.
.SS "setParsedFile ( $parsedFile)"
Sets the filename where the error occurred\&.
.PP
\fBParameters:\fP
.RS 4
\fI$parsedFile\fP The filename 
.RE
.PP

.PP
Definition at line 88 of file ParseException\&.php\&.
.SS "setParsedLine ( $parsedLine)"
Sets the line where the error occurred\&.
.PP
\fBParameters:\fP
.RS 4
\fI$parsedLine\fP The file line 
.RE
.PP

.PP
Definition at line 110 of file ParseException\&.php\&.
.SS "setSnippet ( $snippet)"
Sets the snippet of code near the error\&.
.PP
\fBParameters:\fP
.RS 4
\fI$snippet\fP The code snippet 
.RE
.PP

.PP
Definition at line 64 of file ParseException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
