.TH "PdoCaster" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PdoCaster \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBcastPdo\fP (\\PDO $\fBc\fP, array $\fBa\fP, \fBStub\fP $stub, $isNested)"
.br
.ti -1c
.RI "static \fBcastPdoStatement\fP (\\PDOStatement $\fBc\fP, array $\fBa\fP, \fBStub\fP $stub, $isNested)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Casts PDO related classes to array representation\&.
.PP
\fBAuthor:\fP
.RS 4
Nicolas Grekas p@tchwork.com 
.RE
.PP

.PP
Definition at line 21 of file PdoCaster\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static castPdo (\\PDO $c, array $a, \fBStub\fP $stub,  $isNested)\fC [static]\fP"

.PP
Definition at line 60 of file PdoCaster\&.php\&.
.SS "static castPdoStatement (\\PDOStatement $c, array $a, \fBStub\fP $stub,  $isNested)\fC [static]\fP"

.PP
Definition at line 103 of file PdoCaster\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
