.TH "NullLogger" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NullLogger \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNullLogger\fP, and \fBLoggerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBemerg\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBcrit\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBerr\fP ($message, array $context=array())"
.br
.ti -1c
.RI "\fBwarn\fP ($message, array $context=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBNullLogger\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 23 of file NullLogger\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "crit ( $message, array $context = \fCarray()\fP)"

.PP
\fBDeprecated\fP
.RS 4
since 2\&.2, to be removed in 3\&.0\&. Use \fBcritical()\fP which is PSR-3 compatible\&. 
.RE
.PP

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 39 of file NullLogger\&.php\&.
.SS "emerg ( $message, array $context = \fCarray()\fP)"

.PP
\fBDeprecated\fP
.RS 4
since 2\&.2, to be removed in 3\&.0\&. Use \fBemergency()\fP which is PSR-3 compatible\&. 
.RE
.PP

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 30 of file NullLogger\&.php\&.
.SS "err ( $message, array $context = \fCarray()\fP)"

.PP
\fBDeprecated\fP
.RS 4
since 2\&.2, to be removed in 3\&.0\&. Use \fBerror()\fP which is PSR-3 compatible\&. 
.RE
.PP

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 48 of file NullLogger\&.php\&.
.SS "warn ( $message, array $context = \fCarray()\fP)"

.PP
\fBDeprecated\fP
.RS 4
since 2\&.2, to be removed in 3\&.0\&. Use \fBwarning()\fP which is PSR-3 compatible\&. 
.RE
.PP

.PP
Implements \fBLoggerInterface\fP\&.
.PP
Definition at line 57 of file NullLogger\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
