.TH "RequestContextTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RequestContextTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstruct\fP ()"
.br
.ti -1c
.RI "\fBtestFromRequest\fP ()"
.br
.ti -1c
.RI "\fBtestGetParameters\fP ()"
.br
.ti -1c
.RI "\fBtestHasParameter\fP ()"
.br
.ti -1c
.RI "\fBtestGetParameter\fP ()"
.br
.ti -1c
.RI "\fBtestSetParameter\fP ()"
.br
.ti -1c
.RI "\fBtestMethod\fP ()"
.br
.ti -1c
.RI "\fBtestScheme\fP ()"
.br
.ti -1c
.RI "\fBtestHost\fP ()"
.br
.ti -1c
.RI "\fBtestQueryString\fP ()"
.br
.ti -1c
.RI "\fBtestPort\fP ()"
.br
.ti -1c
.RI "\fBtestFluentInterface\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file RequestContextTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstruct ()"

.PP
Definition at line 19 of file RequestContextTest\&.php\&.
.SS "testFluentInterface ()"

.PP
Definition at line 144 of file RequestContextTest\&.php\&.
.SS "testFromRequest ()"

.PP
Definition at line 42 of file RequestContextTest\&.php\&.
.SS "testGetParameter ()"

.PP
Definition at line 85 of file RequestContextTest\&.php\&.
.SS "testGetParameters ()"

.PP
Definition at line 67 of file RequestContextTest\&.php\&.
.SS "testHasParameter ()"

.PP
Definition at line 76 of file RequestContextTest\&.php\&.
.SS "testHost ()"

.PP
Definition at line 118 of file RequestContextTest\&.php\&.
.SS "testMethod ()"

.PP
Definition at line 102 of file RequestContextTest\&.php\&.
.SS "testPort ()"

.PP
Definition at line 134 of file RequestContextTest\&.php\&.
.SS "testQueryString ()"

.PP
Definition at line 126 of file RequestContextTest\&.php\&.
.SS "testScheme ()"

.PP
Definition at line 110 of file RequestContextTest\&.php\&.
.SS "testSetParameter ()"

.PP
Definition at line 94 of file RequestContextTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
