.TH "FilterIteratorTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilterIteratorTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRealIteratorTestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestFilterFilesystemIterators\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Alex Bogomazov 
.RE
.PP

.PP
Definition at line 17 of file FilterIteratorTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testFilterFilesystemIterators ()"

.PP
Definition at line 19 of file FilterIteratorTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
