.TH "Symfony\Component\Security\Core\Authorization" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\Security\Core\Authorization \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBVoter\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAccessDecisionManager\fP"
.br
.ti -1c
.RI "interface \fBAccessDecisionManagerInterface\fP"
.br
.ti -1c
.RI "class \fBAuthorizationChecker\fP"
.br
.ti -1c
.RI "interface \fBAuthorizationCheckerInterface\fP"
.br
.ti -1c
.RI "class \fBExpressionLanguage\fP"
.br
.ti -1c
.RI "class \fBExpressionLanguageProvider\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
