.TH "TimeDataCollector" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimeDataCollector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBDataCollector\fP, and \fBLateDataCollectorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBKernelInterface\fP $kernel=null, $stopwatch=null)"
.br
.ti -1c
.RI "\fBcollect\fP (\fBRequest\fP $request, \fBResponse\fP $response,\\Exception $exception=null)"
.br
.ti -1c
.RI "\fBlateCollect\fP ()"
.br
.ti -1c
.RI "\fBsetEvents\fP (array $events)"
.br
.ti -1c
.RI "\fBgetEvents\fP ()"
.br
.ti -1c
.RI "\fBgetDuration\fP ()"
.br
.ti -1c
.RI "\fBgetInitTime\fP ()"
.br
.ti -1c
.RI "\fBgetStartTime\fP ()"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$kernel\fP"
.br
.ti -1c
.RI "\fB$stopwatch\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBTimeDataCollector\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 23 of file TimeDataCollector\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBKernelInterface\fP $kernel = \fCnull\fP,  $stopwatch = \fCnull\fP)"

.PP
Definition at line 28 of file TimeDataCollector\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "collect (\fBRequest\fP $request, \fBResponse\fP $response, \\Exception $exception = \fCnull\fP)"
{Collects data for the given \fBRequest\fP and \fBResponse\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$request\fP \fBA\fP \fBRequest\fP instance 
.br
\fI$response\fP \fBA\fP \fBResponse\fP instance 
.br
\fI$exception\fP An \fBException\fP instance
.RE
.PP
} 
.PP
Implements \fBDataCollectorInterface\fP\&.
.PP
Definition at line 37 of file TimeDataCollector\&.php\&.
.SS "getDuration ()"
Gets the request elapsed time\&.
.PP
\fBReturns:\fP
.RS 4
float The elapsed time 
.RE
.PP

.PP
Definition at line 92 of file TimeDataCollector\&.php\&.
.SS "getEvents ()"
Gets the request events\&.
.PP
\fBReturns:\fP
.RS 4
array The request events 
.RE
.PP

.PP
Definition at line 82 of file TimeDataCollector\&.php\&.
.SS "getInitTime ()"
Gets the initialization time\&.
.PP
This is the time spent until the beginning of the request handling\&.
.PP
\fBReturns:\fP
.RS 4
float The elapsed time 
.RE
.PP

.PP
Definition at line 110 of file TimeDataCollector\&.php\&.
.SS "getName ()"
{Returns the name of the collector\&.
.PP
\fBReturns:\fP
.RS 4
string The collector name
.RE
.PP
} 
.PP
Implements \fBDataCollectorInterface\fP\&.
.PP
Definition at line 132 of file TimeDataCollector\&.php\&.
.SS "getStartTime ()"
Gets the request time\&.
.PP
\fBReturns:\fP
.RS 4
int The time 
.RE
.PP

.PP
Definition at line 124 of file TimeDataCollector\&.php\&.
.SS "lateCollect ()"
{Collects data as late as possible\&.} 
.PP
Implements \fBLateDataCollectorInterface\fP\&.
.PP
Definition at line 55 of file TimeDataCollector\&.php\&.
.SS "setEvents (array $events)"
Sets the request events\&.
.PP
\fBParameters:\fP
.RS 4
\fI$events\fP The request events 
.RE
.PP

.PP
Definition at line 68 of file TimeDataCollector\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$kernel\fC [protected]\fP"

.PP
Definition at line 25 of file TimeDataCollector\&.php\&.
.SS "$stopwatch\fC [protected]\fP"

.PP
Definition at line 26 of file TimeDataCollector\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
