.TH "TranslatorWithInvalidLocale" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranslatorWithInvalidLocale \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTranslator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetLocale\fP ($\fBlocale\fP)"
.br
.ti -1c
.RI "\fBproxyLoadCatalogue\fP ($\fBlocale\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 217 of file TranslatorCacheTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "proxyLoadCatalogue ( $locale)"

.PP
Definition at line 227 of file TranslatorCacheTest\&.php\&.
.SS "setLocale ( $locale)"
{Sets the current locale\&.
.PP
\fBParameters:\fP
.RS 4
\fI$locale\fP The locale
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP
} 
.PP
Implements \fBTranslatorInterface\fP\&.
.PP
Definition at line 222 of file TranslatorCacheTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
