.TH "NullOutput" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NullOutput \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOutputInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsetFormatter\fP (\fBOutputFormatterInterface\fP $formatter)"
.br
.ti -1c
.RI "\fBgetFormatter\fP ()"
.br
.ti -1c
.RI "\fBsetDecorated\fP ($decorated)"
.br
.ti -1c
.RI "\fBisDecorated\fP ()"
.br
.ti -1c
.RI "\fBsetVerbosity\fP ($level)"
.br
.ti -1c
.RI "\fBgetVerbosity\fP ()"
.br
.ti -1c
.RI "\fBisQuiet\fP ()"
.br
.ti -1c
.RI "\fBisVerbose\fP ()"
.br
.ti -1c
.RI "\fBisVeryVerbose\fP ()"
.br
.ti -1c
.RI "\fBisDebug\fP ()"
.br
.ti -1c
.RI "\fBwriteln\fP ($messages, $type=self::OUTPUT_NORMAL)"
.br
.ti -1c
.RI "\fBwrite\fP ($messages, $newline=false, $type=self::OUTPUT_NORMAL)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBNullOutput\fP suppresses all output\&. 
.PP
.nf
$output = new NullOutput();

.fi
.PP
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.PP
Tobias Schultze http://tobion.de
.RE
.PP

.PP
Definition at line 27 of file NullOutput\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getFormatter ()"
{Returns current output formatter instance\&.
.PP
\fBReturns:\fP
.RS 4
OutputFormatterInterface
.RE
.PP
} 
.PP
Implements \fBOutputInterface\fP\&.
.PP
Definition at line 40 of file NullOutput\&.php\&.
.SS "getVerbosity ()"
{Gets the current verbosity of the output\&.
.PP
\fBReturns:\fP
.RS 4
int The current level of verbosity (one of the VERBOSITY constants)
.RE
.PP
} 
.PP
Implements \fBOutputInterface\fP\&.
.PP
Definition at line 73 of file NullOutput\&.php\&.
.SS "isDebug ()"

.PP
Definition at line 93 of file NullOutput\&.php\&.
.SS "isDecorated ()"
{Gets the decorated flag\&.
.PP
\fBReturns:\fP
.RS 4
bool true if the output will decorate messages, false otherwise
.RE
.PP
} 
.PP
Implements \fBOutputInterface\fP\&.
.PP
Definition at line 57 of file NullOutput\&.php\&.
.SS "isQuiet ()"

.PP
Definition at line 78 of file NullOutput\&.php\&.
.SS "isVerbose ()"

.PP
Definition at line 83 of file NullOutput\&.php\&.
.SS "isVeryVerbose ()"

.PP
Definition at line 88 of file NullOutput\&.php\&.
.SS "setDecorated ( $decorated)"
{Sets the decorated flag\&.
.PP
\fBParameters:\fP
.RS 4
\fI$decorated\fP Whether to decorate the messages
.RE
.PP
} 
.PP
Implements \fBOutputInterface\fP\&.
.PP
Definition at line 49 of file NullOutput\&.php\&.
.SS "setFormatter (\fBOutputFormatterInterface\fP $formatter)"
{Sets output formatter\&.
.PP
\fBParameters:\fP
.RS 4
\fI$formatter\fP 
.RE
.PP
} 
.PP
Implements \fBOutputInterface\fP\&.
.PP
Definition at line 32 of file NullOutput\&.php\&.
.SS "setVerbosity ( $level)"
{Sets the verbosity of the output\&.
.PP
\fBParameters:\fP
.RS 4
\fI$level\fP The level of verbosity (one of the VERBOSITY constants)
.RE
.PP
} 
.PP
Implements \fBOutputInterface\fP\&.
.PP
Definition at line 65 of file NullOutput\&.php\&.
.SS "write ( $messages,  $newline = \fCfalse\fP,  $type = \fCself::OUTPUT_NORMAL\fP)"
{Writes a message to the output\&.
.PP
\fBParameters:\fP
.RS 4
\fI$messages\fP The message as an array of lines or a single string 
.br
\fI$newline\fP Whether to add a newline 
.br
\fI$type\fP The type of output (one of the OUTPUT constants)
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP
} 
.PP
Implements \fBOutputInterface\fP\&.
.PP
Definition at line 109 of file NullOutput\&.php\&.
.SS "writeln ( $messages,  $type = \fCself::OUTPUT_NORMAL\fP)"
{Writes a message to the output and adds a newline at the end\&.
.PP
\fBParameters:\fP
.RS 4
\fI$messages\fP The message as an array of lines of a single string 
.br
\fI$type\fP The type of output (one of the OUTPUT constants)
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP
} 
.PP
Implements \fBOutputInterface\fP\&.
.PP
Definition at line 101 of file NullOutput\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
