.TH "Symfony\Component\Security\Core\Authentication\Provider" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\Security\Core\Authentication\Provider \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAnonymousAuthenticationProvider\fP"
.br
.ti -1c
.RI "interface \fBAuthenticationProviderInterface\fP"
.br
.ti -1c
.RI "class \fBDaoAuthenticationProvider\fP"
.br
.ti -1c
.RI "class \fBPreAuthenticatedAuthenticationProvider\fP"
.br
.ti -1c
.RI "class \fBRememberMeAuthenticationProvider\fP"
.br
.ti -1c
.RI "class \fBSimpleAuthenticationProvider\fP"
.br
.ti -1c
.RI "class \fBUserAuthenticationProvider\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
