.TH "IOExceptionInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IOExceptionInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBExceptionInterface\fP\&.
.PP
Inherited by \fBIOException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetPath\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBIOException\fP interface for file and input/output stream related exceptions thrown by the component\&.
.PP
\fBAuthor:\fP
.RS 4
Christian Gärtner christiangaertner.film@googlemail.com 
.RE
.PP

.PP
Definition at line 19 of file IOExceptionInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getPath ()"
Returns the associated path for the exception
.PP
\fBReturns:\fP
.RS 4
string The path\&. 
.RE
.PP

.PP
Implemented in \fBIOException\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
