.TH "Symfony\Component\Security\Core\Authentication\Token" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\Security\Core\Authentication\Token \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBStorage\fP"
.br
.in -1c
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAbstractToken\fP"
.br
.ti -1c
.RI "class \fBAnonymousToken\fP"
.br
.ti -1c
.RI "class \fBPreAuthenticatedToken\fP"
.br
.ti -1c
.RI "class \fBRememberMeToken\fP"
.br
.ti -1c
.RI "interface \fBTokenInterface\fP"
.br
.ti -1c
.RI "class \fBUsernamePasswordToken\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
