.TH "JsonFileLoader" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
JsonFileLoader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBArrayLoader\fP, and \fBLoaderInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBload\fP ($resource, $\fBlocale\fP, $domain= 'messages')"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBJsonFileLoader\fP loads translations from an json file\&.
.PP
\fBAuthor:\fP
.RS 4
singles 
.RE
.PP

.PP
Definition at line 23 of file JsonFileLoader\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "load ( $resource,  $locale,  $domain = \fC'messages'\fP)"
{Loads a locale\&.
.PP
\fBParameters:\fP
.RS 4
\fI$resource\fP \fBA\fP resource 
.br
\fI$locale\fP \fBA\fP locale 
.br
\fI$domain\fP The domain
.RE
.PP
\fBReturns:\fP
.RS 4
\fBMessageCatalogue\fP \fBA\fP \fBMessageCatalogue\fP instance
.RE
.PP
.PP
\fBExceptions:\fP
.RS 4
\fINotFoundResourceException\fP when the resource cannot be found 
.br
\fIInvalidResourceException\fP when the resource cannot be loaded
.RE
.PP
} 
.PP
Implements \fBLoaderInterface\fP\&.
.PP
Definition at line 28 of file JsonFileLoader\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
