.TH "HelperSetTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelperSetTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestConstructor\fP ()"
.br
.ti -1c
.RI "\fBtestSet\fP ()"
.br
.ti -1c
.RI "\fBtestHas\fP ()"
.br
.ti -1c
.RI "\fBtestGet\fP ()"
.br
.ti -1c
.RI "\fBtestSetCommand\fP ()"
.br
.ti -1c
.RI "\fBtestGetCommand\fP ()"
.br
.ti -1c
.RI "\fBtestIteration\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file HelperSetTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstructor ()"
::__construct 
.PP
Definition at line 22 of file HelperSetTest\&.php\&.
.SS "testGet ()"
::get 
.PP
Definition at line 65 of file HelperSetTest\&.php\&.
.SS "testGetCommand ()"
::getCommand 
.PP
Definition at line 106 of file HelperSetTest\&.php\&.
.SS "testHas ()"
::has 
.PP
Definition at line 55 of file HelperSetTest\&.php\&.
.SS "testIteration ()"
::getIterator 
.PP
Definition at line 117 of file HelperSetTest\&.php\&.
.SS "testSet ()"
\fBset\fP 
.PP
Definition at line 34 of file HelperSetTest\&.php\&.
.SS "testSetCommand ()"
::setCommand 
.PP
Definition at line 88 of file HelperSetTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
