.TH "Symfony\Component\Debug\Tests\FatalErrorHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\Debug\Tests\FatalErrorHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBClassNotFoundFatalErrorHandlerTest\fP"
.br
.ti -1c
.RI "class \fBUndefinedFunctionFatalErrorHandlerTest\fP"
.br
.ti -1c
.RI "class \fBUndefinedMethodFatalErrorHandlerTest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtest_namespaced_function\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Symfony\\Component\\Debug\\Tests\\FatalErrorHandler\\test_namespaced_function ()"

.PP
Definition at line 78 of file UndefinedFunctionFatalErrorHandlerTest\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
