.TH "EncoderAwareInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncoderAwareInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBEncAwareUser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetEncoderName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Christophe Coevoet stof@notk.org 
.RE
.PP

.PP
Definition at line 17 of file EncoderAwareInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getEncoderName ()"
Gets the name of the encoder used to encode the password\&.
.PP
If the method returns null, the standard way to retrieve the encoder will be used instead\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Implemented in \fBEncAwareUser\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
