.TH "StoreTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StoreTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestReadsAnEmptyArrayWithReadWhenNothingCachedAtKey\fP ()"
.br
.ti -1c
.RI "\fBtestUnlockFileThatDoesExist\fP ()"
.br
.ti -1c
.RI "\fBtestUnlockFileThatDoesNotExist\fP ()"
.br
.ti -1c
.RI "\fBtestRemovesEntriesForKeyWithPurge\fP ()"
.br
.ti -1c
.RI "\fBtestStoresACacheEntry\fP ()"
.br
.ti -1c
.RI "\fBtestSetsTheXContentDigestResponseHeaderBeforeStoring\fP ()"
.br
.ti -1c
.RI "\fBtestFindsAStoredEntryWithLookup\fP ()"
.br
.ti -1c
.RI "\fBtestDoesNotFindAnEntryWithLookupWhenNoneExists\fP ()"
.br
.ti -1c
.RI "\fBtestCanonizesUrlsForCacheKeys\fP ()"
.br
.ti -1c
.RI "\fBtestDoesNotFindAnEntryWithLookupWhenTheBodyDoesNotExist\fP ()"
.br
.ti -1c
.RI "\fBtestRestoresResponseHeadersProperlyWithLookup\fP ()"
.br
.ti -1c
.RI "\fBtestRestoresResponseContentFromEntityStoreWithLookup\fP ()"
.br
.ti -1c
.RI "\fBtestInvalidatesMetaAndEntityStoreEntriesWithInvalidate\fP ()"
.br
.ti -1c
.RI "\fBtestSucceedsQuietlyWhenInvalidateCalledWithNoMatchingEntries\fP ()"
.br
.ti -1c
.RI "\fBtestDoesNotReturnEntriesThatVaryWithLookup\fP ()"
.br
.ti -1c
.RI "\fBtestStoresMultipleResponsesForEachVaryCombination\fP ()"
.br
.ti -1c
.RI "\fBtestOverwritesNonVaryingResponseWithStore\fP ()"
.br
.ti -1c
.RI "\fBtestLocking\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.ti -1c
.RI "\fBstoreSimpleEntry\fP ($\fBpath\fP=null, $headers=array())"
.br
.ti -1c
.RI "\fBgetStoreMetadata\fP ($key)"
.br
.ti -1c
.RI "\fBgetStorePath\fP ($key)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$request\fP"
.br
.ti -1c
.RI "\fB$response\fP"
.br
.ti -1c
.RI "\fB$store\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 18 of file StoreTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getStoreMetadata ( $key)\fC [protected]\fP"

.PP
Definition at line 236 of file StoreTest\&.php\&.
.SS "getStorePath ( $key)\fC [protected]\fP"

.PP
Definition at line 251 of file StoreTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 24 of file StoreTest\&.php\&.
.SS "storeSimpleEntry ( $path = \fCnull\fP,  $headers = \fCarray()\fP)\fC [protected]\fP"

.PP
Definition at line 224 of file StoreTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 34 of file StoreTest\&.php\&.
.SS "testCanonizesUrlsForCacheKeys ()"

.PP
Definition at line 111 of file StoreTest\&.php\&.
.SS "testDoesNotFindAnEntryWithLookupWhenNoneExists ()"

.PP
Definition at line 104 of file StoreTest\&.php\&.
.SS "testDoesNotFindAnEntryWithLookupWhenTheBodyDoesNotExist ()"

.PP
Definition at line 121 of file StoreTest\&.php\&.
.SS "testDoesNotReturnEntriesThatVaryWithLookup ()"

.PP
Definition at line 161 of file StoreTest\&.php\&.
.SS "testFindsAStoredEntryWithLookup ()"

.PP
Definition at line 95 of file StoreTest\&.php\&.
.SS "testInvalidatesMetaAndEntityStoreEntriesWithInvalidate ()"

.PP
Definition at line 145 of file StoreTest\&.php\&.
.SS "testLocking ()"

.PP
Definition at line 212 of file StoreTest\&.php\&.
.SS "testOverwritesNonVaryingResponseWithStore ()"

.PP
Definition at line 192 of file StoreTest\&.php\&.
.SS "testReadsAnEmptyArrayWithReadWhenNothingCachedAtKey ()"

.PP
Definition at line 43 of file StoreTest\&.php\&.
.SS "testRemovesEntriesForKeyWithPurge ()"

.PP
Definition at line 61 of file StoreTest\&.php\&.
.SS "testRestoresResponseContentFromEntityStoreWithLookup ()"

.PP
Definition at line 138 of file StoreTest\&.php\&.
.SS "testRestoresResponseHeadersProperlyWithLookup ()"

.PP
Definition at line 130 of file StoreTest\&.php\&.
.SS "testSetsTheXContentDigestResponseHeaderBeforeStoring ()"

.PP
Definition at line 86 of file StoreTest\&.php\&.
.SS "testStoresACacheEntry ()"

.PP
Definition at line 79 of file StoreTest\&.php\&.
.SS "testStoresMultipleResponsesForEachVaryCombination ()"

.PP
Definition at line 171 of file StoreTest\&.php\&.
.SS "testSucceedsQuietlyWhenInvalidateCalledWithNoMatchingEntries ()"

.PP
Definition at line 154 of file StoreTest\&.php\&.
.SS "testUnlockFileThatDoesExist ()"

.PP
Definition at line 48 of file StoreTest\&.php\&.
.SS "testUnlockFileThatDoesNotExist ()"

.PP
Definition at line 56 of file StoreTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$request\fC [protected]\fP"

.PP
Definition at line 20 of file StoreTest\&.php\&.
.SS "$response\fC [protected]\fP"

.PP
Definition at line 21 of file StoreTest\&.php\&.
.SS "$store\fC [protected]\fP"

.PP
Definition at line 22 of file StoreTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
