.TH "CommandTesterTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CommandTesterTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestExecute\fP ()"
.br
.ti -1c
.RI "\fBtestGetInput\fP ()"
.br
.ti -1c
.RI "\fBtestGetOutput\fP ()"
.br
.ti -1c
.RI "\fBtestGetDisplay\fP ()"
.br
.ti -1c
.RI "\fBtestGetStatusCode\fP ()"
.br
.ti -1c
.RI "\fBtestCommandFromApplication\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$command\fP"
.br
.ti -1c
.RI "\fB$tester\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 19 of file CommandTesterTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 24 of file CommandTesterTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 35 of file CommandTesterTest\&.php\&.
.SS "testCommandFromApplication ()"

.PP
Definition at line 69 of file CommandTesterTest\&.php\&.
.SS "testExecute ()"

.PP
Definition at line 41 of file CommandTesterTest\&.php\&.
.SS "testGetDisplay ()"

.PP
Definition at line 59 of file CommandTesterTest\&.php\&.
.SS "testGetInput ()"

.PP
Definition at line 48 of file CommandTesterTest\&.php\&.
.SS "testGetOutput ()"

.PP
Definition at line 53 of file CommandTesterTest\&.php\&.
.SS "testGetStatusCode ()"

.PP
Definition at line 64 of file CommandTesterTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$command\fC [protected]\fP"

.PP
Definition at line 21 of file CommandTesterTest\&.php\&.
.SS "$tester\fC [protected]\fP"

.PP
Definition at line 22 of file CommandTesterTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
