.TH "UndefinedFunctionException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UndefinedFunctionException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFatalErrorException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ($message,\\ErrorException $previous)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Undefined Function \fBException\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Konstanton Myakshin koc-dp@yandex.ru 
.RE
.PP

.PP
Definition at line 19 of file UndefinedFunctionException\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ( $message, \\ErrorException $previous)"

.PP
Definition at line 21 of file UndefinedFunctionException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
