.TH "DumperTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DumperTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestSetIndentation\fP ()"
.br
.ti -1c
.RI "\fBtestSpecifications\fP ()"
.br
.ti -1c
.RI "\fBtestInlineLevel\fP ()"
.br
.ti -1c
.RI "\fBtestObjectSupportEnabled\fP ()"
.br
.ti -1c
.RI "\fBtestObjectSupportDisabledButNoExceptions\fP ()"
.br
.ti -1c
.RI "\fBtestObjectSupportDisabledWithExceptions\fP ()"
.br
.ti -1c
.RI "\fBtestEscapedEscapeSequencesInQuotedScalar\fP ($input, $expected)"
.br
.ti -1c
.RI "\fBgetEscapeSequences\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$parser\fP"
.br
.ti -1c
.RI "\fB$dumper\fP"
.br
.ti -1c
.RI "\fB$path\fP"
.br
.ti -1c
.RI "\fB$array\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file DumperTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getEscapeSequences ()"

.PP
Definition at line 209 of file DumperTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 38 of file DumperTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 45 of file DumperTest\&.php\&.
.SS "testEscapedEscapeSequencesInQuotedScalar ( $input,  $expected)"
getEscapeSequences 
.PP
Definition at line 204 of file DumperTest\&.php\&.
.SS "testInlineLevel ()"

.PP
Definition at line 104 of file DumperTest\&.php\&.
.SS "testObjectSupportDisabledButNoExceptions ()"

.PP
Definition at line 186 of file DumperTest\&.php\&.
.SS "testObjectSupportDisabledWithExceptions ()"

.PP
Definition at line 196 of file DumperTest\&.php\&.
.SS "testObjectSupportEnabled ()"

.PP
Definition at line 179 of file DumperTest\&.php\&.
.SS "testSetIndentation ()"

.PP
Definition at line 53 of file DumperTest\&.php\&.
.SS "testSpecifications ()"

.PP
Definition at line 79 of file DumperTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$array\fC [protected]\fP"
\fBInitial value:\fP
.PP
.nf
= array(
        '' => 'bar',
        'foo' => '#bar',
        'foo\'bar' => array(),
        'bar' => array(1, 'foo'),
        'foobar' => array(
            'foo' => 'bar',
            'bar' => array(1, 'foo'),
            'foobar' => array(
                'foo' => 'bar',
                'bar' => array(1, 'foo'),
            ),
        ),
    )
.fi
.PP
Definition at line 23 of file DumperTest\&.php\&.
.SS "$dumper\fC [protected]\fP"

.PP
Definition at line 20 of file DumperTest\&.php\&.
.SS "$parser\fC [protected]\fP"

.PP
Definition at line 19 of file DumperTest\&.php\&.
.SS "$\fBpath\fP\fC [protected]\fP"

.PP
Definition at line 21 of file DumperTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
