.TH "TranslationWriter" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TranslationWriter \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaddDumper\fP ($\fBformat\fP, \fBDumperInterface\fP $dumper)"
.br
.ti -1c
.RI "\fBdisableBackup\fP ()"
.br
.ti -1c
.RI "\fBgetFormats\fP ()"
.br
.ti -1c
.RI "\fBwriteTranslations\fP (\fBMessageCatalogue\fP $catalogue, $\fBformat\fP, $\fBoptions\fP=array())"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTranslationWriter\fP writes translation messages\&.
.PP
\fBAuthor:\fP
.RS 4
Michel Salib michelsalib@hotmail.com 
.RE
.PP

.PP
Definition at line 22 of file TranslationWriter\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "addDumper ( $format, \fBDumperInterface\fP $dumper)"
Adds a dumper to the writer\&.
.PP
\fBParameters:\fP
.RS 4
\fI$format\fP The format of the dumper 
.br
\fI$dumper\fP The dumper 
.RE
.PP

.PP
Definition at line 37 of file TranslationWriter\&.php\&.
.SS "disableBackup ()"
Disables dumper backup\&. 
.PP
Definition at line 45 of file TranslationWriter\&.php\&.
.SS "getFormats ()"
Obtains the list of supported formats\&.
.PP
\fBReturns:\fP
.RS 4
array 
.RE
.PP

.PP
Definition at line 57 of file TranslationWriter\&.php\&.
.SS "writeTranslations (\fBMessageCatalogue\fP $catalogue,  $format,  $options = \fCarray()\fP)"
Writes translation from the catalogue according to the selected format\&.
.PP
\fBParameters:\fP
.RS 4
\fI$catalogue\fP The message catalogue to dump 
.br
\fI$format\fP The format to use to dump the messages 
.br
\fI$options\fP Options that are passed to the dumper
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 71 of file TranslationWriter\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
