.TH "LockedException" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LockedException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAccountStatusException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetMessageKey\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLockedException\fP is thrown if the user account is locked\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.PP
Alexander iam.asm89@gmail.com 
.RE
.PP

.PP
Definition at line 20 of file LockedException\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getMessageKey ()"
{} 
.PP
Definition at line 25 of file LockedException\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
