.TH "CallableClass" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallableClass \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__invoke\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 302 of file AbstractEventDispatcherTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__invoke ()"

.PP
Definition at line 304 of file AbstractEventDispatcherTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
