.TH "RememberMeAuthenticationProvider" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RememberMeAuthenticationProvider \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAuthenticationProviderInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBUserCheckerInterface\fP $userChecker, $key, $providerKey)"
.br
.ti -1c
.RI "\fBauthenticate\fP (\fBTokenInterface\fP $token)"
.br
.ti -1c
.RI "\fBsupports\fP (\fBTokenInterface\fP $token)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file RememberMeAuthenticationProvider\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBUserCheckerInterface\fP $userChecker,  $key,  $providerKey)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$userChecker\fP An UserCheckerInterface interface 
.br
\fI$key\fP \fBA\fP key 
.br
\fI$providerKey\fP \fBA\fP provider key 
.RE
.PP

.PP
Definition at line 32 of file RememberMeAuthenticationProvider\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "authenticate (\fBTokenInterface\fP $token)"
{Attempts to authenticate a TokenInterface object\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP The TokenInterface instance to authenticate
.RE
.PP
\fBReturns:\fP
.RS 4
TokenInterface An authenticated TokenInterface instance, never null
.RE
.PP
\fBExceptions:\fP
.RS 4
\fIAuthenticationException\fP if the authentication fails
.RE
.PP
} 
.PP
Implements \fBAuthenticationManagerInterface\fP\&.
.PP
Definition at line 42 of file RememberMeAuthenticationProvider\&.php\&.
.SS "supports (\fBTokenInterface\fP $token)"
{Checks whether this provider supports the given token\&.
.PP
\fBParameters:\fP
.RS 4
\fI$token\fP \fBA\fP TokenInterface instance
.RE
.PP
\fBReturns:\fP
.RS 4
bool true if the implementation supports the \fBToken\fP, false otherwise
.RE
.PP
} 
.PP
Implements \fBAuthenticationProviderInterface\fP\&.
.PP
Definition at line 64 of file RememberMeAuthenticationProvider\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
