.TH "SessionHandlerProxyTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SessionHandlerProxyTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestOpen\fP ()"
.br
.ti -1c
.RI "\fBtestOpenFalse\fP ()"
.br
.ti -1c
.RI "\fBtestClose\fP ()"
.br
.ti -1c
.RI "\fBtestCloseFalse\fP ()"
.br
.ti -1c
.RI "\fBtestRead\fP ()"
.br
.ti -1c
.RI "\fBtestWrite\fP ()"
.br
.ti -1c
.RI "\fBtestDestroy\fP ()"
.br
.ti -1c
.RI "\fBtestGc\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBTests\fP for SessionHandlerProxy class\&.
.PP
\fBAuthor:\fP
.RS 4
Drak drak@zikula.org
.RE
.PP
disabled 
.PP
Definition at line 24 of file SessionHandlerProxyTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 36 of file SessionHandlerProxyTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 42 of file SessionHandlerProxyTest\&.php\&.
.SS "testClose ()"

.PP
Definition at line 74 of file SessionHandlerProxyTest\&.php\&.
.SS "testCloseFalse ()"

.PP
Definition at line 85 of file SessionHandlerProxyTest\&.php\&.
.SS "testDestroy ()"

.PP
Definition at line 112 of file SessionHandlerProxyTest\&.php\&.
.SS "testGc ()"

.PP
Definition at line 120 of file SessionHandlerProxyTest\&.php\&.
.SS "testOpen ()"

.PP
Definition at line 48 of file SessionHandlerProxyTest\&.php\&.
.SS "testOpenFalse ()"

.PP
Definition at line 63 of file SessionHandlerProxyTest\&.php\&.
.SS "testRead ()"

.PP
Definition at line 96 of file SessionHandlerProxyTest\&.php\&.
.SS "testWrite ()"

.PP
Definition at line 104 of file SessionHandlerProxyTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
