.TH "AuthenticationFailureEvent" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AuthenticationFailureEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBAuthenticationEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBTokenInterface\fP $token, \fBAuthenticationException\fP $ex)"
.br
.ti -1c
.RI "\fBgetAuthenticationException\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This event is dispatched on authentication failure\&.
.PP
\fBAuthor:\fP
.RS 4
Johannes M\&. Schmitt schmittjoh@gmail.com 
.RE
.PP

.PP
Definition at line 22 of file AuthenticationFailureEvent\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBTokenInterface\fP $token, \fBAuthenticationException\fP $ex)"

.PP
Definition at line 26 of file AuthenticationFailureEvent\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getAuthenticationException ()"

.PP
Definition at line 33 of file AuthenticationFailureEvent\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
