.TH "TestSessionListenerTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestSessionListenerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestShouldSaveMasterRequestSession\fP ()"
.br
.ti -1c
.RI "\fBtestShouldNotSaveSubRequestSession\fP ()"
.br
.ti -1c
.RI "\fBtestDoesNotDeleteCookieIfUsingSessionLifetime\fP ()"
.br
.ti -1c
.RI "\fBtestUnstartedSessionIsNotSave\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
SessionListenerTest\&.
.PP
\fBTests\fP SessionListener\&.
.PP
\fBAuthor:\fP
.RS 4
Bulat Shakirzyanov mallluhuct@gmail.com 
.RE
.PP

.PP
Definition at line 27 of file TestSessionListenerTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 39 of file TestSessionListenerTest\&.php\&.
.SS "testDoesNotDeleteCookieIfUsingSessionLifetime ()"

.PP
Definition at line 60 of file TestSessionListenerTest\&.php\&.
.SS "testShouldNotSaveSubRequestSession ()"

.PP
Definition at line 53 of file TestSessionListenerTest\&.php\&.
.SS "testShouldSaveMasterRequestSession ()"

.PP
Definition at line 45 of file TestSessionListenerTest\&.php\&.
.SS "testUnstartedSessionIsNotSave ()"

.PP
Definition at line 73 of file TestSessionListenerTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
