.TH "Symfony\Component\Process\Pipes" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\Process\Pipes \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAbstractPipes\fP"
.br
.ti -1c
.RI "interface \fBPipesInterface\fP"
.br
.ti -1c
.RI "class \fBUnixPipes\fP"
.br
.ti -1c
.RI "class \fBWindowsPipes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
