.TH "PhpExecutableFinder" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhpExecutableFinder \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBfind\fP ($includeArgs=true)"
.br
.ti -1c
.RI "\fBfindArguments\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
An executable finder specifically designed for the \fBPHP\fP executable\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.PP
Johannes M\&. Schmitt schmittjoh@gmail.com 
.RE
.PP

.PP
Definition at line 20 of file PhpExecutableFinder\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct ()"

.PP
Definition at line 24 of file PhpExecutableFinder\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "find ( $includeArgs = \fCtrue\fP)"
Finds The \fBPHP\fP executable\&.
.PP
\fBParameters:\fP
.RS 4
\fI$includeArgs\fP Whether or not include command arguments
.RE
.PP
\fBReturns:\fP
.RS 4
string|false The \fBPHP\fP executable path or false if it cannot be found 
.RE
.PP

.PP
Definition at line 36 of file PhpExecutableFinder\&.php\&.
.SS "findArguments ()"
Finds the \fBPHP\fP executable arguments\&.
.PP
\fBReturns:\fP
.RS 4
array The \fBPHP\fP executable arguments 
.RE
.PP

.PP
Definition at line 75 of file PhpExecutableFinder\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
