.TH "DataCollectorInterface" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataCollectorInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBDataCollector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcollect\fP (\fBRequest\fP $request, \fBResponse\fP $response,\\Exception $exception=null)"
.br
.ti -1c
.RI "\fBgetName\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDataCollectorInterface\fP\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 24 of file DataCollectorInterface\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "collect (\fBRequest\fP $request, \fBResponse\fP $response, \\Exception $exception = \fCnull\fP)"
Collects data for the given \fBRequest\fP and \fBResponse\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$request\fP \fBA\fP \fBRequest\fP instance 
.br
\fI$response\fP \fBA\fP \fBResponse\fP instance 
.br
\fI$exception\fP An \fBException\fP instance
.RE
.PP

.PP
Implemented in \fBDumpDataCollector\fP, \fBConfigDataCollector\fP, \fBRouterDataCollector\fP, \fBRequestDataCollector\fP, \fBMongoDbProfilerStorageTestDataCollector\fP, \fBLoggerDataCollector\fP, \fBTimeDataCollector\fP, \fBEventDataCollector\fP, \fBMemoryDataCollector\fP, and \fBExceptionDataCollector\fP\&.
.SS "getName ()"
Returns the name of the collector\&.
.PP
\fBReturns:\fP
.RS 4
string The collector name
.RE
.PP

.PP
Implemented in \fBRequestDataCollector\fP, \fBConfigDataCollector\fP, \fBDumpDataCollector\fP, \fBTimeDataCollector\fP, \fBEventDataCollector\fP, \fBExceptionDataCollector\fP, \fBRouterDataCollector\fP, \fBLoggerDataCollector\fP, \fBMemoryDataCollector\fP, and \fBMongoDbProfilerStorageTestDataCollector\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
