.TH "XmlFileLoader" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
XmlFileLoader \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits FileLoader\&.
.PP
Inherited by \fBCustomXmlFileLoader\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBload\fP ($file, $type=null)"
.br
.ti -1c
.RI "\fBsupports\fP ($resource, $type=null)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBNAMESPACE_URI\fP = 'http://symfony\&.com/schema/routing'"
.br
.ti -1c
.RI "const \fBSCHEME_PATH\fP = '/schema/routing/routing-1\&.0\&.xsd'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBparseNode\fP (\fBRouteCollection\fP $collection,\\DOMElement $\fBnode\fP, $\fBpath\fP, $file)"
.br
.ti -1c
.RI "\fBparseRoute\fP (\fBRouteCollection\fP $collection,\\DOMElement $\fBnode\fP, $\fBpath\fP)"
.br
.ti -1c
.RI "\fBparseImport\fP (\fBRouteCollection\fP $collection,\\DOMElement $\fBnode\fP, $\fBpath\fP, $file)"
.br
.ti -1c
.RI "\fBloadFile\fP ($file)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBXmlFileLoader\fP loads XML routing files\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.PP
Tobias Schultze http://tobion.de
.RE
.PP

.PP
Definition at line 28 of file XmlFileLoader\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "load ( $file,  $type = \fCnull\fP)"
Loads an XML file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP An XML file path 
.br
\fI$type\fP The resource type
.RE
.PP
\fBReturns:\fP
.RS 4
\fBRouteCollection\fP \fBA\fP \fBRouteCollection\fP instance
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 46 of file XmlFileLoader\&.php\&.
.SS "loadFile ( $file)\fC [protected]\fP"
Loads an XML file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$file\fP An XML file path
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 197 of file XmlFileLoader\&.php\&.
.SS "parseImport (\fBRouteCollection\fP $collection, \\DOMElement $node,  $path,  $file)\fC [protected]\fP"
Parses an import and adds the routes in the resource to the \fBRouteCollection\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$collection\fP \fBRouteCollection\fP instance 
.br
\fI$node\fP Element to parse that represents a \fBRoute\fP 
.br
\fI$path\fP Full path of the XML file being processed 
.br
\fI$file\fP Loaded file name
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 148 of file XmlFileLoader\&.php\&.
.SS "parseNode (\fBRouteCollection\fP $collection, \\DOMElement $node,  $path,  $file)\fC [protected]\fP"
Parses a node from a loaded XML file\&.
.PP
\fBParameters:\fP
.RS 4
\fI$collection\fP Collection to associate with the node 
.br
\fI$node\fP Element to parse 
.br
\fI$path\fP Full path of the XML file being processed 
.br
\fI$file\fP Loaded file name
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 77 of file XmlFileLoader\&.php\&.
.SS "parseRoute (\fBRouteCollection\fP $collection, \\DOMElement $node,  $path)\fC [protected]\fP"
Parses a route and adds it to the \fBRouteCollection\fP\&.
.PP
\fBParameters:\fP
.RS 4
\fI$collection\fP \fBRouteCollection\fP instance 
.br
\fI$node\fP Element to parse that represents a \fBRoute\fP 
.br
\fI$path\fP Full path of the XML file being processed
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 114 of file XmlFileLoader\&.php\&.
.SS "supports ( $resource,  $type = \fCnull\fP)"
{}
.PP
Definition at line 100 of file XmlFileLoader\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const NAMESPACE_URI = 'http://symfony\&.com/schema/routing'"

.PP
Definition at line 30 of file XmlFileLoader\&.php\&.
.SS "const SCHEME_PATH = '/schema/routing/routing-1\&.0\&.xsd'"

.PP
Definition at line 31 of file XmlFileLoader\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
