.TH "TestOutput" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestOutput \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBclear\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fB$output\fP = ''"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBdoWrite\fP ($message, $newline)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 143 of file OutputTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "clear ()"

.PP
Definition at line 147 of file OutputTest\&.php\&.
.SS "doWrite ( $message,  $newline)\fC [protected]\fP"

.PP
Definition at line 152 of file OutputTest\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$output = ''"

.PP
Definition at line 145 of file OutputTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
