.TH "ResponseHeaderBag" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResponseHeaderBag \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBHeaderBag\fP, and \fBHeaderBag\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (array $headers=array())"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBallPreserveCase\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP (array $headers=array())"
.br
.ti -1c
.RI "\fBset\fP ($key, $\fBvalues\fP, $\fBreplace\fP=true)"
.br
.ti -1c
.RI "\fBremove\fP ($key)"
.br
.ti -1c
.RI "\fBhasCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBgetCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBsetCookie\fP (\fBCookie\fP $cookie)"
.br
.ti -1c
.RI "\fBremoveCookie\fP ($\fBname\fP, $\fBpath\fP= '/', $domain=null)"
.br
.ti -1c
.RI "\fBgetCookies\fP ($\fBformat\fP=self::COOKIES_FLAT)"
.br
.ti -1c
.RI "\fBclearCookie\fP ($\fBname\fP, $\fBpath\fP= '/', $domain=null, $secure=false, $httpOnly=true)"
.br
.ti -1c
.RI "\fBmakeDisposition\fP ($disposition, $filename, $filenameFallback= '')"
.br
.ti -1c
.RI "\fB__construct\fP (array $headers=array())"
.br
.ti -1c
.RI "\fB__toString\fP ()"
.br
.ti -1c
.RI "\fBallPreserveCase\fP ()"
.br
.ti -1c
.RI "\fBreplace\fP (array $headers=array())"
.br
.ti -1c
.RI "\fBset\fP ($key, $\fBvalues\fP, $\fBreplace\fP=true)"
.br
.ti -1c
.RI "\fBremove\fP ($key)"
.br
.ti -1c
.RI "\fBhasCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBgetCacheControlDirective\fP ($key)"
.br
.ti -1c
.RI "\fBsetCookie\fP (\fBCookie\fP $cookie)"
.br
.ti -1c
.RI "\fBremoveCookie\fP ($\fBname\fP, $\fBpath\fP= '/', $domain=null)"
.br
.ti -1c
.RI "\fBgetCookies\fP ($\fBformat\fP=self::COOKIES_FLAT)"
.br
.ti -1c
.RI "\fBclearCookie\fP ($\fBname\fP, $\fBpath\fP= '/', $domain=null, $secure=false, $httpOnly=true)"
.br
.ti -1c
.RI "\fBmakeDisposition\fP ($disposition, $filename, $filenameFallback= '')"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBCOOKIES_FLAT\fP = 'flat'"
.br
.ti -1c
.RI "const \fBCOOKIES_ARRAY\fP = 'array'"
.br
.ti -1c
.RI "const \fBDISPOSITION_ATTACHMENT\fP = 'attachment'"
.br
.ti -1c
.RI "const \fBDISPOSITION_INLINE\fP = 'inline'"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBcomputeCacheControlValue\fP ()"
.br
.ti -1c
.RI "\fBcomputeCacheControlValue\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$computedCacheControl\fP = array()"
.br
.ti -1c
.RI "\fB$cookies\fP = array()"
.br
.ti -1c
.RI "\fB$headerNames\fP = array()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBResponseHeaderBag\fP is a container for \fBResponse\fP HTTP headers\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com
.RE
.PP

.PP
Definition at line 14706 of file compiled\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (array $headers = \fCarray()\fP)"

.PP
Definition at line 14715 of file compiled\&.php\&.
.SS "__construct (array $headers = \fCarray()\fP)"
Constructor\&.
.PP
\fBParameters:\fP
.RS 4
\fI$headers\fP An array of HTTP headers
.RE
.PP

.PP
Definition at line 51 of file ResponseHeaderBag\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "__toString ()"
{} 
.PP
Definition at line 63 of file ResponseHeaderBag\&.php\&.
.SS "__toString ()"

.PP
Definition at line 14722 of file compiled\&.php\&.
.SS "allPreserveCase ()"
Returns the headers, with original capitalizations\&.
.PP
\fBReturns:\fP
.RS 4
array An array of headers 
.RE
.PP

.PP
Definition at line 80 of file ResponseHeaderBag\&.php\&.
.SS "allPreserveCase ()"

.PP
Definition at line 14732 of file compiled\&.php\&.
.SS "clearCookie ( $name,  $path = \fC'/'\fP,  $domain = \fCnull\fP,  $secure = \fCfalse\fP,  $httpOnly = \fCtrue\fP)"
Clears a cookie in the browser\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$path\fP 
.br
\fI$domain\fP 
.br
\fI$secure\fP 
.br
\fI$httpOnly\fP 
.RE
.PP

.PP
Definition at line 237 of file ResponseHeaderBag\&.php\&.
.SS "clearCookie ( $name,  $path = \fC'/'\fP,  $domain = \fCnull\fP,  $secure = \fCfalse\fP,  $httpOnly = \fCtrue\fP)"

.PP
Definition at line 14808 of file compiled\&.php\&.
.SS "computeCacheControlValue ()\fC [protected]\fP"
Returns the calculated value of the cache-control header\&.
.PP
This considers several other headers and calculates or modifies the cache-control header to a sensible, conservative value\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 299 of file ResponseHeaderBag\&.php\&.
.SS "computeCacheControlValue ()\fC [protected]\fP"

.PP
Definition at line 14835 of file compiled\&.php\&.
.SS "getCacheControlDirective ( $key)"
{} 
.PP
Definition at line 150 of file ResponseHeaderBag\&.php\&.
.SS "getCacheControlDirective ( $key)"

.PP
Definition at line 14769 of file compiled\&.php\&.
.SS "getCookies ( $format = \fCself::COOKIES_FLAT\fP)"
Returns an array with all cookies\&.
.PP
\fBParameters:\fP
.RS 4
\fI$format\fP 
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 204 of file ResponseHeaderBag\&.php\&.
.SS "getCookies ( $format = \fCself::COOKIES_FLAT\fP)"

.PP
Definition at line 14790 of file compiled\&.php\&.
.SS "hasCacheControlDirective ( $key)"
{} 
.PP
Definition at line 142 of file ResponseHeaderBag\&.php\&.
.SS "hasCacheControlDirective ( $key)"

.PP
Definition at line 14765 of file compiled\&.php\&.
.SS "makeDisposition ( $disposition,  $filename,  $filenameFallback = \fC''\fP)"
Generates a HTTP Content-Disposition field-value\&.
.PP
\fBParameters:\fP
.RS 4
\fI$disposition\fP \fBOne\fP of 'inline' or 'attachment' 
.br
\fI$filename\fP \fBA\fP unicode string 
.br
\fI$filenameFallback\fP \fBA\fP string containing only ASCII characters that is semantically equivalent to $filename\&. If the filename is already ASCII, it can be omitted, or just copied from $filename
.RE
.PP
\fBReturns:\fP
.RS 4
string \fBA\fP string suitable for use as a Content-Disposition field-value\&.
.RE
.PP
\fBExceptions:\fP
.RS 4
\fI\fP .RE
.PP

.PP
Definition at line 257 of file ResponseHeaderBag\&.php\&.
.SS "makeDisposition ( $disposition,  $filename,  $filenameFallback = \fC''\fP)"

.PP
Definition at line 14812 of file compiled\&.php\&.
.SS "remove ( $key)"
{}
.PP
Definition at line 127 of file ResponseHeaderBag\&.php\&.
.SS "remove ( $key)"

.PP
Definition at line 14756 of file compiled\&.php\&.
.SS "removeCookie ( $name,  $path = \fC'/'\fP,  $domain = \fCnull\fP)"
Removes a cookie from the array, but does not unset it in the browser\&.
.PP
\fBParameters:\fP
.RS 4
\fI$name\fP 
.br
\fI$path\fP 
.br
\fI$domain\fP 
.RE
.PP

.PP
Definition at line 176 of file ResponseHeaderBag\&.php\&.
.SS "removeCookie ( $name,  $path = \fC'/'\fP,  $domain = \fCnull\fP)"

.PP
Definition at line 14777 of file compiled\&.php\&.
.SS "replace (array $headers = \fCarray()\fP)"
{}
.PP
Definition at line 90 of file ResponseHeaderBag\&.php\&.
.SS "replace (array $headers = \fCarray()\fP)"

.PP
Definition at line 14736 of file compiled\&.php\&.
.SS "set ( $key,  $values,  $replace = \fCtrue\fP)"
{}
.PP
Definition at line 106 of file ResponseHeaderBag\&.php\&.
.SS "set ( $key,  $values,  $replace = \fCtrue\fP)"

.PP
Definition at line 14744 of file compiled\&.php\&.
.SS "setCookie (\fBCookie\fP $cookie)"
Sets a cookie\&.
.PP
\fBParameters:\fP
.RS 4
\fI$cookie\fP 
.RE
.PP

.PP
Definition at line 162 of file ResponseHeaderBag\&.php\&.
.SS "setCookie (\fBCookie\fP $cookie)"

.PP
Definition at line 14773 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$computedCacheControl = array()\fC [protected]\fP"

.PP
Definition at line 14712 of file compiled\&.php\&.
.SS "$cookies = array()\fC [protected]\fP"

.PP
Definition at line 14713 of file compiled\&.php\&.
.SS "$headerNames = array()\fC [protected]\fP"

.PP
Definition at line 14714 of file compiled\&.php\&.
.SS "const COOKIES_ARRAY = 'array'"

.PP
Definition at line 14709 of file compiled\&.php\&.
.SS "const COOKIES_FLAT = 'flat'"

.PP
Definition at line 14708 of file compiled\&.php\&.
.SS "const DISPOSITION_ATTACHMENT = 'attachment'"

.PP
Definition at line 14710 of file compiled\&.php\&.
.SS "const DISPOSITION_INLINE = 'inline'"

.PP
Definition at line 14711 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
