.TH "Symfony\Component\HttpKernel\Exception" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Symfony\Component\HttpKernel\Exception \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBAccessDeniedHttpException\fP"
.br
.ti -1c
.RI "class \fBBadRequestHttpException\fP"
.br
.ti -1c
.RI "class \fBConflictHttpException\fP"
.br
.ti -1c
.RI "class \fBFatalErrorException\fP"
.br
.ti -1c
.RI "class \fBFlattenException\fP"
.br
.ti -1c
.RI "class \fBGoneHttpException\fP"
.br
.ti -1c
.RI "class \fBHttpException\fP"
.br
.ti -1c
.RI "interface \fBHttpExceptionInterface\fP"
.br
.ti -1c
.RI "class \fBLengthRequiredHttpException\fP"
.br
.ti -1c
.RI "class \fBMethodNotAllowedHttpException\fP"
.br
.ti -1c
.RI "class \fBNotAcceptableHttpException\fP"
.br
.ti -1c
.RI "class \fBNotFoundHttpException\fP"
.br
.ti -1c
.RI "class \fBPreconditionFailedHttpException\fP"
.br
.ti -1c
.RI "class \fBPreconditionRequiredHttpException\fP"
.br
.ti -1c
.RI "class \fBServiceUnavailableHttpException\fP"
.br
.ti -1c
.RI "class \fBTooManyRequestsHttpException\fP"
.br
.ti -1c
.RI "class \fBUnauthorizedHttpException\fP"
.br
.ti -1c
.RI "class \fBUnprocessableEntityHttpException\fP"
.br
.ti -1c
.RI "class \fBUnsupportedMediaTypeHttpException\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
