.TH "Shell" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shell \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBtestCommand\fP ($command)"
.br
.ti -1c
.RI "\fBgetType\fP ()"
.br
.ti -1c
.RI "\fBtestCommand\fP ($command)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBTYPE_UNIX\fP = 1"
.br
.ti -1c
.RI "const \fBTYPE_DARWIN\fP = 2"
.br
.ti -1c
.RI "const \fBTYPE_CYGWIN\fP = 3"
.br
.ti -1c
.RI "const \fBTYPE_WINDOWS\fP = 4"
.br
.ti -1c
.RI "const \fBTYPE_BSD\fP = 5"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jean-François Simon contact@jfsimon.fr 
.RE
.PP

.PP
Definition at line 15503 of file compiled\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getType ()"
Returns guessed OS type\&.
.PP
\fBReturns:\fP
.RS 4
int 
.RE
.PP

.PP
Definition at line 35 of file Shell\&.php\&.
.SS "getType ()"

.PP
Definition at line 15511 of file compiled\&.php\&.
.SS "testCommand ( $command)"
\fBTests\fP if a command is available\&.
.PP
\fBParameters:\fP
.RS 4
\fI$command\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
bool 
.RE
.PP

.PP
Definition at line 51 of file Shell\&.php\&.
.SS "testCommand ( $command)"

.PP
Definition at line 15518 of file compiled\&.php\&.
.SH "Field Documentation"
.PP 
.SS "const TYPE_BSD = 5"

.PP
Definition at line 15509 of file compiled\&.php\&.
.SS "const TYPE_CYGWIN = 3"

.PP
Definition at line 15507 of file compiled\&.php\&.
.SS "const TYPE_DARWIN = 2"

.PP
Definition at line 15506 of file compiled\&.php\&.
.SS "const TYPE_UNIX = 1"

.PP
Definition at line 15505 of file compiled\&.php\&.
.SS "const TYPE_WINDOWS = 4"

.PP
Definition at line 15508 of file compiled\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
