.TH "TraceableUrlMatcher" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TraceableUrlMatcher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBUrlMatcher\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBgetTraces\fP ($pathinfo)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const \fBROUTE_DOES_NOT_MATCH\fP = 0"
.br
.ti -1c
.RI "const \fBROUTE_ALMOST_MATCHES\fP = 1"
.br
.ti -1c
.RI "const \fBROUTE_MATCHES\fP = 2"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBmatchCollection\fP ($pathinfo, \fBRouteCollection\fP $routes)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$traces\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBTraceableUrlMatcher\fP helps debug path info matching by tracing the match\&.
.PP
\fBAuthor:\fP
.RS 4
Fabien Potencier fabien@symfony.com 
.RE
.PP

.PP
Definition at line 23 of file TraceableUrlMatcher\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "getTraces ( $pathinfo)"

.PP
Definition at line 31 of file TraceableUrlMatcher\&.php\&.
.SS "matchCollection ( $pathinfo, \fBRouteCollection\fP $routes)\fC [protected]\fP"

.PP
Definition at line 43 of file TraceableUrlMatcher\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$traces\fC [protected]\fP"

.PP
Definition at line 29 of file TraceableUrlMatcher\&.php\&.
.SS "const ROUTE_ALMOST_MATCHES = 1"

.PP
Definition at line 26 of file TraceableUrlMatcher\&.php\&.
.SS "const ROUTE_DOES_NOT_MATCH = 0"

.PP
Definition at line 25 of file TraceableUrlMatcher\&.php\&.
.SS "const ROUTE_MATCHES = 2"

.PP
Definition at line 27 of file TraceableUrlMatcher\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
