.TH "TemplateMethodsTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TemplateMethodsTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPHPUnit_Framework_TestCase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestOne\fP ()"
.br
.ti -1c
.RI "\fBtestTwo\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBsetUpBeforeClass\fP ()"
.br
.ti -1c
.RI "static \fBtearDownAfterClass\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsetUp\fP ()"
.br
.ti -1c
.RI "\fBassertPreConditions\fP ()"
.br
.ti -1c
.RI "\fBassertPostConditions\fP ()"
.br
.ti -1c
.RI "\fBtearDown\fP ()"
.br
.ti -1c
.RI "\fBonNotSuccessfulTest\fP (Exception $\fBe\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 2 of file TemplateMethodsTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "assertPostConditions ()\fC [protected]\fP"

.PP
Definition at line 31 of file TemplateMethodsTest\&.php\&.
.SS "assertPreConditions ()\fC [protected]\fP"

.PP
Definition at line 14 of file TemplateMethodsTest\&.php\&.
.SS "onNotSuccessfulTest (Exception $e)\fC [protected]\fP"

.PP
Definition at line 46 of file TemplateMethodsTest\&.php\&.
.SS "setUp ()\fC [protected]\fP"

.PP
Definition at line 9 of file TemplateMethodsTest\&.php\&.
.SS "static setUpBeforeClass ()\fC [static]\fP"

.PP
Definition at line 4 of file TemplateMethodsTest\&.php\&.
.SS "tearDown ()\fC [protected]\fP"

.PP
Definition at line 36 of file TemplateMethodsTest\&.php\&.
.SS "static tearDownAfterClass ()\fC [static]\fP"

.PP
Definition at line 41 of file TemplateMethodsTest\&.php\&.
.SS "testOne ()"

.PP
Definition at line 19 of file TemplateMethodsTest\&.php\&.
.SS "testTwo ()"

.PP
Definition at line 25 of file TemplateMethodsTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
