.TH "TestSlaveRequestHandler" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestSlaveRequestHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtearDown\fP (self)"
.br
.ti -1c
.RI "def \fBtestUnhandledFunction\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadCoils\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadDigitalInputs\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadCoilsOutOfBlocks\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadDiscreteInputsOutOfBlocks\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadCoilsOnContinuousBlocks\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadDiscreteInputsOnContinuousBlocks\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadHoldingRegisters\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadAnalogInputs\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadTooManyHoldingRegisters\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadTooManyAnalogInputs\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadHoldingRegistersOutOfBlocks\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadInputRegistersOutOfBlocks\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadHoldingRegistersOnContinuousBlocks\fP (self)"
.br
.ti -1c
.RI "def \fBtestHandleReadInputregistersOnContinuousBlocks\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file unittest_modbus\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def setUp ( self)"

.PP
Definition at line 23 of file unittest_modbus\&.py\&.
.SS "def tearDown ( self)"

.PP
Definition at line 27 of file unittest_modbus\&.py\&.
.SS "def testHandleReadAnalogInputs ( self)"

.PP
.nf
test that the correct response pdu is sent when receiving a pdu for reading input registers
.fi
.PP
 
.PP
Definition at line 119 of file unittest_modbus\&.py\&.
.SS "def testHandleReadCoils ( self)"

.PP
.nf
test that the correct response pdu is sent when receiving a pdu for reading coils
.fi
.PP
 
.PP
Definition at line 76 of file unittest_modbus\&.py\&.
.SS "def testHandleReadCoilsOnContinuousBlocks ( self)"

.PP
.nf
test that an error response pdu is sent when receiving a pdu for reading coils at an address shared on distinct blocks
.fi
.PP
 
.PP
Definition at line 92 of file unittest_modbus\&.py\&.
.SS "def testHandleReadCoilsOutOfBlocks ( self)"

.PP
.nf
test that an error response pdu is sent when receiving a pdu for reading coils at an unknown addresses
.fi
.PP
 
.PP
Definition at line 84 of file unittest_modbus\&.py\&.
.SS "def testHandleReadDigitalInputs ( self)"

.PP
.nf
test that the correct response pdu is sent when receiving a pdu for reading discrete inputs
.fi
.PP
 
.PP
Definition at line 80 of file unittest_modbus\&.py\&.
.SS "def testHandleReadDiscreteInputsOnContinuousBlocks ( self)"

.PP
.nf
test that an error response pdu is sent when receiving a pdu for reading discrete inputs at an address shared on distinct blocks
.fi
.PP
 
.PP
Definition at line 96 of file unittest_modbus\&.py\&.
.SS "def testHandleReadDiscreteInputsOutOfBlocks ( self)"

.PP
.nf
test that an error response pdu is sent when receiving a pdu for reading discrete inputs at an unknown addresses
.fi
.PP
 
.PP
Definition at line 88 of file unittest_modbus\&.py\&.
.SS "def testHandleReadHoldingRegisters ( self)"

.PP
.nf
test that the correct response pdu is sent when receiving a pdu for reading holding registers
.fi
.PP
 
.PP
Definition at line 115 of file unittest_modbus\&.py\&.
.SS "def testHandleReadHoldingRegistersOnContinuousBlocks ( self)"

.PP
.nf
test that an error response pdu is sent when receiving a pdu for reading coils at an address shared on distinct blocks
.fi
.PP
 
.PP
Definition at line 145 of file unittest_modbus\&.py\&.
.SS "def testHandleReadHoldingRegistersOutOfBlocks ( self)"

.PP
.nf
test that an error is returned when handling a pdu for reading out of blocks
.fi
.PP
 
.PP
Definition at line 137 of file unittest_modbus\&.py\&.
.SS "def testHandleReadInputregistersOnContinuousBlocks ( self)"

.PP
.nf
test that an error response pdu is sent when receiving a pdu for reading discrete inputs at an address shared on distinct blocks
.fi
.PP
 
.PP
Definition at line 149 of file unittest_modbus\&.py\&.
.SS "def testHandleReadInputRegistersOutOfBlocks ( self)"

.PP
.nf
test that an error is returned when handling a pdu for reading reading out of blocks
.fi
.PP
 
.PP
Definition at line 141 of file unittest_modbus\&.py\&.
.SS "def testHandleReadTooManyAnalogInputs ( self)"

.PP
.nf
test that an error is returned when handling a pdu for reading more than 125 input registers
.fi
.PP
 
.PP
Definition at line 133 of file unittest_modbus\&.py\&.
.SS "def testHandleReadTooManyHoldingRegisters ( self)"

.PP
.nf
test that an error is returned when handling a pdu for reading more than 125 holding registers
.fi
.PP
 
.PP
Definition at line 129 of file unittest_modbus\&.py\&.
.SS "def testUnhandledFunction ( self)"

.PP
.nf
test that an error is sent back when using an unknown function
.fi
.PP
 
.PP
Definition at line 30 of file unittest_modbus\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
