.TH "TestCommand" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBconfigure\fP ()"
.br
.ti -1c
.RI "\fBexecute\fP (\fBInputInterface\fP $input, \fBOutputInterface\fP $output)"
.br
.ti -1c
.RI "\fBinteract\fP (\fBInputInterface\fP $input, \fBOutputInterface\fP $output)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 7 of file TestCommand\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "configure ()\fC [protected]\fP"

.PP
Definition at line 9 of file TestCommand\&.php\&.
.SS "execute (\fBInputInterface\fP $input, \fBOutputInterface\fP $output)\fC [protected]\fP"

.PP
Definition at line 19 of file TestCommand\&.php\&.
.SS "interact (\fBInputInterface\fP $input, \fBOutputInterface\fP $output)\fC [protected]\fP"

.PP
Definition at line 24 of file TestCommand\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
