.TH "TestRtuSpecific" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestRtuSpecific \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestQueriesSetupAndTeardown, and TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtestExpectedLength\fP (self)"
.br
.ti -1c
.RI "def \fBtestExpectedLengthTooShort\fP (self)"
.br
.ti -1c
.RI "def \fBtestExpectedLengthTooLong\fP (self)"
.br
.ti -1c
.RI "def \fBtestReadWithWrongFunction\fP (self)"
.br
.ti -1c
.RI "def \fBtestWriteSingleCoilInvalidValue\fP (self)"
.br
.ti -1c
.RI "def \fBtestMultiThreadAccess\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file functest_modbus_rtu\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def testExpectedLength ( self)"

.PP
.nf
check that expected length doesn't cause an error
.fi
.PP
 
.PP
Definition at line 109 of file functest_modbus_rtu\&.py\&.
.SS "def testExpectedLengthTooLong ( self)"

.PP
.nf
check that no impact if expected_length is too high
.fi
.PP
 
.PP
Definition at line 141 of file functest_modbus_rtu\&.py\&.
.SS "def testExpectedLengthTooShort ( self)"

.PP
.nf
check that an error is raised if expected_length is too low
.fi
.PP
 
.PP
Definition at line 117 of file functest_modbus_rtu\&.py\&.
.SS "def testMultiThreadAccess ( self)"

.PP
.nf
check that the modbus call are thread safe
.fi
.PP
 
.PP
Definition at line 170 of file functest_modbus_rtu\&.py\&.
.SS "def testReadWithWrongFunction ( self)"

.PP
.nf
check that an error is raised when sending a query with an invalid function code
.fi
.PP
 
.PP
Definition at line 147 of file functest_modbus_rtu\&.py\&.
.SS "def testWriteSingleCoilInvalidValue ( self)"

.PP
.nf
Check that an error is raised when writing a coil with an invalid value
.fi
.PP
 
.PP
Definition at line 160 of file functest_modbus_rtu\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
