.TH "tests.unittest_modbus" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tests.unittest_modbus \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBTestServer\fP"
.br
.ti -1c
.RI "class \fBTestSlaveBlocks\fP"
.br
.ti -1c
.RI "class \fBTestSlaveRequestHandler\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBLOGGER\fP = \fBmodbus_tk\&.utils\&.create_logger\fP('udp')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple LOGGER = \fBmodbus_tk\&.utils\&.create_logger\fP('udp')"

.PP
Definition at line 20 of file unittest_modbus\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
