.TH "TestTcpServer" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestTcpServer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtearDown\fP (self)"
.br
.ti -1c
.RI "def \fBtestGetRequestLength\fP (self)"
.br
.ti -1c
.RI "def \fBtestGetRequestLengthFailsOnInvalid\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 270 of file unittest_modbus_tcp\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def setUp ( self)"

.PP
Definition at line 271 of file unittest_modbus_tcp\&.py\&.
.SS "def tearDown ( self)"

.PP
Definition at line 272 of file unittest_modbus_tcp\&.py\&.
.SS "def testGetRequestLength ( self)"

.PP
.nf
Test than _get_request_length returns the length field of request mbap
.fi
.PP
 
.PP
Definition at line 274 of file unittest_modbus_tcp\&.py\&.
.SS "def testGetRequestLengthFailsOnInvalid ( self)"

.PP
.nf
Test than an error is raised in _get_request_length is the length field of request mbap is not filled
.fi
.PP
 
.PP
Definition at line 283 of file unittest_modbus_tcp\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
