.TH "TestStress" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestStress \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtearDown\fP (self)"
.br
.ti -1c
.RI "def \fBtestGarbageData\fP (self)"
.br
.ti -1c
.RI "def \fBtestSeveralClients\fP (self)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBserver\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Test the TcpMbap class
.fi
.PP
 
.PP
Definition at line 26 of file perftest_modbus_tcp\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def setUp ( self)"

.PP
Definition at line 29 of file perftest_modbus_tcp\&.py\&.
.SS "def tearDown ( self)"

.PP
Definition at line 32 of file perftest_modbus_tcp\&.py\&.
.SS "def testGarbageData ( self)"

.PP
.nf
Send Garbage data and make sure that it doesn't kill everything
.fi
.PP
 
.PP
Definition at line 35 of file perftest_modbus_tcp\&.py\&.
.SS "def testSeveralClients ( self)"

.PP
.nf
check that the server can serve 15 clients in parallel
.fi
.PP
 
.PP
Definition at line 58 of file perftest_modbus_tcp\&.py\&.
.SH "Field Documentation"
.PP 
.SS "server"

.PP
Definition at line 30 of file perftest_modbus_tcp\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
