.TH "TestingAidsTest" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestingAidsTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestFixture\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtestTestingAidsWithTestNowNotSet\fP ()"
.br
.ti -1c
.RI "\fBtestTestingAidsWithTestNowSet\fP ()"
.br
.ti -1c
.RI "\fBtestConstructorWithTestValueSet\fP ()"
.br
.ti -1c
.RI "\fBtestNowWithTestValueSet\fP ()"
.br
.ti -1c
.RI "\fBtestParseWithTestValueSet\fP ()"
.br
.ti -1c
.RI "\fBtestParseRelativeWithTestValueSet\fP ()"
.br
.ti -1c
.RI "\fBtestParseRelativeWithMinusSignsInDate\fP ()"
.br
.ti -1c
.RI "\fBtestTimeZoneWithTestValueSet\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file TestingAidsTest\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "testConstructorWithTestValueSet ()"

.PP
Definition at line 33 of file TestingAidsTest\&.php\&.
.SS "testNowWithTestValueSet ()"

.PP
Definition at line 44 of file TestingAidsTest\&.php\&.
.SS "testParseRelativeWithMinusSignsInDate ()"

.PP
Definition at line 106 of file TestingAidsTest\&.php\&.
.SS "testParseRelativeWithTestValueSet ()"

.PP
Definition at line 63 of file TestingAidsTest\&.php\&.
.SS "testParseWithTestValueSet ()"

.PP
Definition at line 52 of file TestingAidsTest\&.php\&.
.SS "testTestingAidsWithTestNowNotSet ()"

.PP
Definition at line 16 of file TestingAidsTest\&.php\&.
.SS "testTestingAidsWithTestNowSet ()"

.PP
Definition at line 24 of file TestingAidsTest\&.php\&.
.SS "testTimeZoneWithTestValueSet ()"

.PP
Definition at line 115 of file TestingAidsTest\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
