.TH "TestCase" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestCase \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTestCase\fP\&.
.PP
Inherited by \fBExampleTest\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcreateApplication\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 3 of file TestCase\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "createApplication ()"
Creates the application\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 10 of file TestCase\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
