.TH "vendor/jeremeamia/SuperClosure/src/Analyzer/Visitor/ThisDetectorVisitor.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/jeremeamia/SuperClosure/src/Analyzer/Visitor/ThisDetectorVisitor.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBThisDetectorVisitor\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSuperClosure\\Analyzer\\Visitor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
