.TH "vendor/phpunit/php-code-coverage/tests/PHP/CodeCoverage/UtilTest.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/phpunit/php-code-coverage/tests/PHP/CodeCoverage/UtilTest.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBPHP_CodeCoverage_UtilTest\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBCodeCoverage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
