.TH "Validator" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Validator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBValidator\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBmake\fP ($\fBdata\fP, $rules, $messages=array(), $customAttributes=array())"
.br
.ti -1c
.RI "static \fBextend\fP ($rule, $extension, $message=null)"
.br
.ti -1c
.RI "static \fBextendImplicit\fP ($rule, $extension, $message=null)"
.br
.ti -1c
.RI "static \fBreplacer\fP ($rule, $replacer)"
.br
.ti -1c
.RI "static \fBresolver\fP ($resolver)"
.br
.ti -1c
.RI "static \fBgetTranslator\fP ()"
.br
.ti -1c
.RI "static \fBgetPresenceVerifier\fP ()"
.br
.ti -1c
.RI "static \fBsetPresenceVerifier\fP ($presenceVerifier)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 11776 of file _ide_helper\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "static extend ( $rule,  $extension,  $message = \fCnull\fP)\fC [static]\fP"
Register a custom validator extension\&.
.PP
\fBParameters:\fP
.RS 4
\fI$rule\fP 
.br
\fI$extension\fP 
.br
\fI$message\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11801 of file _ide_helper\&.php\&.
.SS "static extendImplicit ( $rule,  $extension,  $message = \fCnull\fP)\fC [static]\fP"
Register a custom implicit validator extension\&.
.PP
\fBParameters:\fP
.RS 4
\fI$rule\fP 
.br
\fI$extension\fP 
.br
\fI$message\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11814 of file _ide_helper\&.php\&.
.SS "static getPresenceVerifier ()\fC [static]\fP"
Get the Presence Verifier implementation\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11857 of file _ide_helper\&.php\&.
.SS "static getTranslator ()\fC [static]\fP"
Get the Translator implementation\&.
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11847 of file _ide_helper\&.php\&.
.SS "static make ( $data,  $rules,  $messages = \fCarray()\fP,  $customAttributes = \fCarray()\fP)\fC [static]\fP"
Create a new \fBValidator\fP instance\&.
.PP
\fBParameters:\fP
.RS 4
\fI$data\fP 
.br
\fI$rules\fP 
.br
\fI$messages\fP 
.br
\fI$customAttributes\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 11788 of file _ide_helper\&.php\&.
.SS "static replacer ( $rule,  $replacer)\fC [static]\fP"
Register a custom implicit validator message replacer\&.
.PP
\fBParameters:\fP
.RS 4
\fI$rule\fP 
.br
\fI$replacer\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11826 of file _ide_helper\&.php\&.
.SS "static resolver ( $resolver)\fC [static]\fP"
Set the \fBValidator\fP instance resolver\&.
.PP
\fBParameters:\fP
.RS 4
\fI$resolver\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11837 of file _ide_helper\&.php\&.
.SS "static setPresenceVerifier ( $presenceVerifier)\fC [static]\fP"
Set the Presence Verifier implementation\&.
.PP
\fBParameters:\fP
.RS 4
\fI$presenceVerifier\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
void 
.RE
.PP

.PP
Definition at line 11868 of file _ide_helper\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
