.TH "app/Http/Controllers/WelcomeController.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/Http/Controllers/WelcomeController.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWelcomeController\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBApp\\Http\\Controllers\fP"
.br
.ti -1c
.RI " \fBApp\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
