.TH "vendor/symfony/routing/Symfony/Component/Routing/Tests/Fixtures/with_define_path_variable.php" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vendor/symfony/routing/Symfony/Component/Routing/Tests/Fixtures/with_define_path_variable.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$path\fP = '/1/2/3'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$\fBpath\fP = '/1/2/3'"

.PP
Definition at line 3 of file with_define_path_variable\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
