.TH "ZipArchive" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ZipArchive \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBzip_it\fP (self, dirName, files)"
.br
.ti -1c
.RI "def \fBrun\fP (self, \fBfolder\fP, \fBname\fP)"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBexclude_list\fP"
.br
.ti -1c
.RI "\fBfolder\fP"
.br
.ti -1c
.RI "\fBarchive\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file zip_module\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def run ( self,  folder,  name)"

.PP
Definition at line 31 of file zip_module\&.py\&.
.SS "def zip_it ( self,  dirName,  files)"

.PP
Definition at line 17 of file zip_module\&.py\&.
.SH "Field Documentation"
.PP 
.SS "archive"

.PP
Definition at line 35 of file zip_module\&.py\&.
.SS "exclude_list"

.PP
Definition at line 32 of file zip_module\&.py\&.
.SS "folder"

.PP
Definition at line 34 of file zip_module\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
