.TH "zip_module" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zip_module \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBZipArchive\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tuple \fBarch\fP = \fBZipArchive\fP()"
.br
.ti -1c
.RI "tuple \fBold_dir\fP = os\&.getcwd()"
.br
.ti -1c
.RI "tuple \fBwkdir\fP = os\&.path\&.abspath(os\&.path\&.dirname(sys\&.argv[0])+'\\\\\&.\&.')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "tuple arch = \fBZipArchive\fP()"

.PP
Definition at line 40 of file zip_module\&.py\&.
.SS "tuple old_dir = os\&.getcwd()"

.PP
Definition at line 41 of file zip_module\&.py\&.
.SS "tuple wkdir = os\&.path\&.abspath(os\&.path\&.dirname(sys\&.argv[0])+'\\\\\&.\&.')"

.PP
Definition at line 42 of file zip_module\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
