var _undefined_function_fatal_error_handler_test_8php =
[
    [ "UndefinedFunctionFatalErrorHandlerTest", "class_symfony_1_1_component_1_1_debug_1_1_tests_1_1_fatal_error_handler_1_1_undefined_function_fatal_error_handler_test.html", "class_symfony_1_1_component_1_1_debug_1_1_tests_1_1_fatal_error_handler_1_1_undefined_function_fatal_error_handler_test" ],
    [ "test_namespaced_function", "_undefined_function_fatal_error_handler_test_8php.html#aadb79ee66df734dff7132fbe0293f58f", null ]
];