var class_swift___mime___embedded_file_test =
[
    [ "_createAttachment", "class_swift___mime___embedded_file_test.html#adad6b8a2b48ab8888c0d6de36a4f1e49", null ],
    [ "testDefaultDispositionIsInline", "class_swift___mime___embedded_file_test.html#a70bf7a577f71cc770dd7f823517804d7", null ],
    [ "testIdIsAutoGenerated", "class_swift___mime___embedded_file_test.html#a3799ab54e2f275fbdebf8a889b8e33e2", null ],
    [ "testNestingLevelIsAttachment", "class_swift___mime___embedded_file_test.html#a3d4863f6b19ff69c3586730d84f558c2", null ],
    [ "testNestingLevelIsEmbedded", "class_swift___mime___embedded_file_test.html#a88ac532508baab13de054ee376f79c91", null ]
];