var namespace_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization =
[
    [ "Voter", "namespace_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_voter.html", "namespace_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_voter" ],
    [ "AccessDecisionManager", "class_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_access_decision_manager.html", "class_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_access_decision_manager" ],
    [ "AccessDecisionManagerInterface", "interface_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_access_decision_manager_interface.html", "interface_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_access_decision_manager_interface" ],
    [ "AuthorizationChecker", "class_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_authorization_checker.html", "class_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_authorization_checker" ],
    [ "AuthorizationCheckerInterface", "interface_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_authorization_checker_interface.html", "interface_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_authorization_checker_interface" ],
    [ "ExpressionLanguage", "class_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_expression_language.html", "class_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_expression_language" ],
    [ "ExpressionLanguageProvider", "class_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_expression_language_provider.html", "class_symfony_1_1_component_1_1_security_1_1_core_1_1_authorization_1_1_expression_language_provider" ]
];