var namespace_symfony_1_1_component_1_1_http_kernel_1_1_tests_1_1_dependency_injection =
[
    [ "ContainerAwareHttpKernelTest", "class_symfony_1_1_component_1_1_http_kernel_1_1_tests_1_1_dependency_injection_1_1_container_aware_http_kernel_test.html", "class_symfony_1_1_component_1_1_http_kernel_1_1_tests_1_1_dependency_injection_1_1_container_aware_http_kernel_test" ],
    [ "MergeExtensionConfigurationPassTest", "class_symfony_1_1_component_1_1_http_kernel_1_1_tests_1_1_dependency_injection_1_1_merge_extension_configuration_pass_test.html", "class_symfony_1_1_component_1_1_http_kernel_1_1_tests_1_1_dependency_injection_1_1_merge_extension_configuration_pass_test" ]
];