var namespace_monolog_1_1_handler_1_1_fingers_crossed =
[
    [ "ActivationStrategyInterface", "interface_monolog_1_1_handler_1_1_fingers_crossed_1_1_activation_strategy_interface.html", "interface_monolog_1_1_handler_1_1_fingers_crossed_1_1_activation_strategy_interface" ],
    [ "ChannelLevelActivationStrategy", "class_monolog_1_1_handler_1_1_fingers_crossed_1_1_channel_level_activation_strategy.html", "class_monolog_1_1_handler_1_1_fingers_crossed_1_1_channel_level_activation_strategy" ],
    [ "ErrorLevelActivationStrategy", "class_monolog_1_1_handler_1_1_fingers_crossed_1_1_error_level_activation_strategy.html", "class_monolog_1_1_handler_1_1_fingers_crossed_1_1_error_level_activation_strategy" ]
];