var namespace_doctrine_test_1_1_instantiator_test_1_1_exception =
[
    [ "InvalidArgumentExceptionTest", "class_doctrine_test_1_1_instantiator_test_1_1_exception_1_1_invalid_argument_exception_test.html", "class_doctrine_test_1_1_instantiator_test_1_1_exception_1_1_invalid_argument_exception_test" ],
    [ "UnexpectedValueExceptionTest", "class_doctrine_test_1_1_instantiator_test_1_1_exception_1_1_unexpected_value_exception_test.html", "class_doctrine_test_1_1_instantiator_test_1_1_exception_1_1_unexpected_value_exception_test" ]
];